/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 24a55b98ca6d6867f997031475e73fd8)
interface __BaseEnv_Env {
	DB: D1Database;
	ROOMS: DurableObjectNamespace<import("./src/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room";
	}
	interface StagingEnv {
		DB: D1Database;
		ROOMS: DurableObjectNamespace<import("./src/index").Room>;
	}
	interface ProductionEnv {
		DB: D1Database;
		ROOMS: DurableObjectNamespace<import("./src/index").Room>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
