/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 82b857f7e274f9f1c6f075afc7512fc6)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ENVIRONMENT: "staging" | "production" | "local";
	BASE_URL: "https://madou-senki-staging.catalgorithm.workers.dev" | "https://madou-senki.catalgorithm.workers.dev" | "http://localhost:8787";
	EMAIL_FROM_ADDRESS: "noreply@madou-senki.com" | "noreply@madou-senki.local";
	ROOMS: DurableObjectNamespace<import("./src/index").Room>;
	AUTH_SECRET?: "local-development-only-secret-0123456789abcdef";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room";
	}
	interface StagingEnv {
		DB: D1Database;
		EMAIL: SendEmail;
		ENVIRONMENT: "staging";
		BASE_URL: "https://madou-senki-staging.catalgorithm.workers.dev";
		EMAIL_FROM_ADDRESS: "noreply@madou-senki.com";
		ROOMS: DurableObjectNamespace<import("./src/index").Room>;
	}
	interface ProductionEnv {
		DB: D1Database;
		EMAIL: SendEmail;
		ENVIRONMENT: "production";
		BASE_URL: "https://madou-senki.catalgorithm.workers.dev";
		EMAIL_FROM_ADDRESS: "noreply@madou-senki.com";
		ROOMS: DurableObjectNamespace<import("./src/index").Room>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BASE_URL" | "EMAIL_FROM_ADDRESS" | "AUTH_SECRET">> {}
}
