import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {substitutePhysicalScenarios,substituteMode} from './fixtures/substitute-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(substitutePhysicalScenarios)('%s persists actual selected hit transfer restrictions and returns through restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),card='a2-p02-r2c1',m=substituteMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`substitute-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;await step();}throw Error('SUBSTITUTE_DO_LIMIT');}
 await send('A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:m.multi?['B','C']:['B'],dedicated:m.multi});await until(s=>!!Object.keys(s.groups??{}).length);if(m.follower)await until(s=>s.windows?.at(-1)?.kind==='hit');await until(s=>viewFor(s,'C').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId==='B'&&o.hitIndex===m.hit));const parent=Object.values((await state()).groups!)[0]!,damage=parent.targets[0]!.hits[m.hit]!.damage,hand=(await state()).players.C!.hand.length;if(m.multi)expect(parent.targets.map(t=>t.hits.length)).toEqual([3,3]);
 if(scenario==='substitute-decline'){await until(s=>!s.windows?.length);expect((await state()).players.C!.hand).toContain(card);expect([(await state()).players.B!.damage,(await state()).players.C!.damage]).toEqual([4,0]);return;}
 const o=viewFor(await state(),'C').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId==='B'&&o.hitIndex===m.hit)!;await send('C',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:o.targetId!,groupId:o.groupId!,hitIndex:o.hitIndex!});expect((await state()).players.C!.hand).toHaveLength(hand);
 if(scenario==='substitute-canceled'){const child=Object.values((await state()).actions!).find(a=>a.cardInstanceId===card)!;await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='D';});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});}else{
 await until(s=>s.windows?.at(-1)?.kind==='normal-defense'&&!!viewFor(s,'C').currentAttack?.substitution);expect(viewFor(await state(),'C').currentAttack!.substitution).toEqual({originalTargetId:'B',originalHitIndex:m.hit});expect(viewFor(await state(),'C').legalChoices).not.toContain('START_FOLLOWERS');expect(viewFor(await state(),'C').anytimeCardOptions).toEqual([]);expect((await state()).players.C!.damage).toBe(0);
 if(scenario==='substitute-counter')await send('C',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p10-r3c3',dedicated:false});if(m.ability){const a=viewFor(await state(),'C').abilityOptions.find(o=>o.abilityId===m.ability)!;await send('C',{type:'USE_ABILITY',abilityId:a.abilityId,targetEventId:a.targetEventId});}if(scenario==='substitute-near'){expect((await state()).distances.A!.C).toBe('far');await send('C',{type:'REVEAL_CHARACTER'});}if(scenario==='substitute-refill')expect((await state()).players.C!.open).toContain('a2-p01-r1c3');
 if(scenario==='substitute-third'){await until(s=>viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p01-r2c3'));const t=viewFor(await state(),'D').anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p01-r2c3')!;expect(t.targetEventId).toBe(parent.actionId);await send('D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:t.cardInstanceId,targetEventId:t.targetEventId});}
 if(scenario==='substitute-chain'){await until(s=>s.windows?.at(-1)?.kind==='hit'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');const offers=viewFor(await state(),'D').sadLove!.substitutions;expect(offers).toHaveLength(3);expect(offers.every(o=>o.groupId===parent.id&&o.targetId==='C')).toBe(true);await send('D',{type:'USE_ABILITY',abilityId:'c2-p05-r1c2-ab05',mode:'substitute',...offers[0]!});}
 }
 await until(s=>!s.windows?.length);const final=await state(),zero=['substitute-counter','substitute-mental','substitute-water','substitute-third'].includes(scenario);expect(final.players.B!.damage).toBe(scenario==='substitute-canceled'?4:m.follower?4:m.multi?14:0);expect(final.players.C!.damage).toBe(zero||scenario==='substitute-canceled'?0:scenario==='substitute-chain'?21:m.receiver?8:m.follower?23:m.multi?28:damage);expect(final.players.A!.damage).toBe(scenario==='substitute-counter'?5:0);if(scenario==='substitute-chain')expect(final.players.D!.damage).toBe(7);expect(final.discard.filter(id=>id===card)).toHaveLength(1);expect(final.resolution).toEqual([]);
},15000);
