import {reset} from 'cloudflare:test';
import {afterEach,expect,it} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {maaiOtherScenarios,maaiOtherCards,maaiOtherSecond as SECOND} from './fixtures/maai-other-physical-scenarios.js';
afterEach(async()=>{await reset();});
it.each(maaiOtherScenarios)('%s real prior injury and physical REST or MAAI survive every command restart and duplicate replay',async scenario=>{
 const room=await openTestRoom(scenario),card=maaiOtherCards[Number(scenario.split('-')[2])-1]!,rest=scenario.endsWith('-rest');let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`maai-other-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<400;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('MAAI_OTHER_DO_LIMIT');}
 const before=structuredClone(await state()),owner=rest?'A':'B';expect(before.players[owner]!.damage).toBe(4);
 if(rest){await send('A',{type:'REST',cardInstanceIds:[card,SECOND]});const after=await state(),id=after.windows!.at(-1)!.continuation.id;expect(after.players.A!.damage).toBe(4);expect(after.players.A!.hand).toEqual(before.players.A!.hand.filter(x=>x!==card&&x!==SECOND));expect(after.deck).toEqual(before.deck);expect(after.resolution).toEqual(expect.arrayContaining([card,SECOND]));await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');expect(viewFor(await state(),'D').currentAction).toMatchObject({cardInstanceId:card});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(3);expect((await state()).players.B!.damage).toBe(0);expect((await state()).phase).toBe('hand-adjustment');for(const id of [card,SECOND])expect((await state()).discard.filter(x=>x===id)).toHaveLength(1);}
 else {await send('B',{type:'PLAY_MAAI',cardInstanceId:card});const after=await state();expect(after.players.B!.hand).toEqual(before.players.B!.hand.filter(x=>x!==card));expect(after.deck).toEqual(before.deck);expect(after.players.B!.damage).toBe(4);await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(4);expect((await state()).discard.filter(x=>x===card)).toHaveLength(1);expect((await state()).phase).toBe('withdrawal');expect((await state()).distances).toEqual(before.distances);}
},15000);
