import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {wingedFolkPhysicalMode} from './fixtures/winged-folk-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['winged-setup', false], ['winged-turn', false], ['winged-equal', false], ['winged-higher', false], ['winged-morale-fail', false], ['winged-waive', false], ['winged-earth', false], ['winged-earth-fail', false], ['winged-earth-waive', false], ['winged-earth-rear', false], ['winged-earth-ignore', false], ['winged-army', false], ['winged-ded-hand', false], ['winged-ded-field', false], ['winged-grant-hand', false], ['winged-grant-field', false], ['winged-ded-hand', true], ['winged-ded-field', true], ['winged-army', true], ['winged-grant-field', true]] as const)('%s canceled=%s persists actual Winged Folk defense or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=wingedFolkPhysicalMode(scenario),SK='a2-p21-r1c3';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`winged-folk-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WINGED_FOLK_DO_SETTLE');}
 if(m.rear)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});for(const id of ['A','B','C','D'])await send(id,{type:'PASS_SETUP'});await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.defense){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WINGED_FOLK_DO_TURN');}if(m.earth){if(m.ignore)await send('B',{type:'REVEAL_CHARACTER'});await send('B',{type:'ATTACK',cardInstanceId:'a2-p16-r2c3',targetIds:m.rear||m.ignore?['A']:['A','C'],dedicated:!m.rear&&!m.ignore});if(m.ignore){await settle('follower-entry-abilities');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r1c1-ab02')!;await send('B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,costCardInstanceId:'a2-p24-r2c1'});}}
 else{await send('B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'});await settle();const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});}if(m.waive){await settle('normal-defense');await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[SK]});}}
 else{if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B','C','D']});else if(m.grant){const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B','C','D']}]});}else await send('A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B','C','D'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const id=m.grant?Object.values(s.abilities!).find(a=>a.abilityId==='c2-p06-r1c2-ab04')!.id:Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':SK))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.grant?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}

 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&!m.fail&&(m.earth||m.waive||m.attackLevel<5);expect(['A','B','C','D'].map(id=>s.players[id]!.damage)).toEqual(m.defense?m.earth?m.ignore?[6,0,0,0]:m.rear?[0,0,0,0]:[m.fail?9:0,0,9,0]:[m.fail||m.attackLevel>5&&!m.waive?18:0,0,0,0]:[0,canceled?0:12,canceled?0:12,canceled?0:12]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?m.rear?['a2-p22-r1c1',SK]:[SK]:[]);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.defense?m.waive||m.ignore||m.rear?0:1:m.army&&!canceled?1:0);if(!m.defense&&!canceled){expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.rolls!.find(r=>r.purpose==='attack-damage')).toMatchObject({faces:[1,1],total:2});}if(m.ignore||m.rear)expect(s.players.A!.followers.find(f=>f.cardInstanceId===SK)!.revealed).toBe(false);expect(s.resolution).toEqual([]);
},15000);
