import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {revelationPhysicalScenarios,revelationTarget} from './fixtures/revelation-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(revelationPhysicalScenarios)('%s persists actual private inspection and fixed history through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),card='a2-p02-r1c2',target=['A','B','C','D'][revelationTarget(scenario)]!;let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`revelation-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('REVELATION_DO_PHASE');}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(await state()))return;await step();}throw Error('REVELATION_DO_LIMIT');}
 if(scenario==='revelation-otherworld'){expect((await state()).players.B!.presence).toBe('otherworld');expect(viewFor(await state(),'D').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId==='B')).toBe(false);await send('C',{type:'PASS_ACTION'});expect((await state()).players.D!.hand).toContain(card);expect(viewFor(await state(),'D').inspectionHistory).toEqual([]);return;}
 if(scenario==='revelation-combat')await send('A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['C'],dedicated:false});
 await until(s=>viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId===target));const o=viewFor(await state(),'D').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===target)!,hand=(await state()).players.D!.hand.length;await send('D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:target});expect((await state()).players.D!.hand).toHaveLength(hand);const original=structuredClone((await state()).players[target]!);
 if(scenario==='revelation-canceled'){const child=Object.values((await state()).actions!).find(a=>a.cardInstanceId===card)!;await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='C';});await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});await until(s=>!s.windows?.length);expect(viewFor(await state(),'D').inspectionHistory).toEqual([]);}else{
 await until(s=>!!viewFor(s,'D').inspection);const d=structuredClone(viewFor(await state(),'D').inspection!),expected=(['hand','followers','chants'] as const).flatMap<{zone:'hand'|'followers'|'chants';position:number;cardInstanceId:string}>(zone=>zone==='hand'?original.hand.map((cardInstanceId,position)=>({zone,position,cardInstanceId})):original[zone].map((c,position)=>({zone,position,cardInstanceId:c.cardInstanceId})));expect(d).toMatchObject({targetId:target,zone:'all',cards:expected,discardMode:'none',choices:['finish']});for(const id of ['A','B','C']){const v=viewFor(await state(),id);expect(v.inspection).toBeNull();expect(v.inspectionHistory).toEqual([]);if(id!==target)for(const card of expected)expect(JSON.stringify(v)).not.toContain(card.cardInstanceId);}
 if(scenario==='revelation-pass')await send('D',{type:'PASS'});else await send('D',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});await until(s=>!s.windows?.length);expect(viewFor(await state(),'D').inspectionHistory).toEqual([d]);
 if(scenario==='revelation-history'){await until(s=>!s.windows?.length&&s.seatOrder[s.turnSeat]==='B'&&s.phase==='draw');const before=[...(await state()).players.B!.hand];await send('B',{type:'CHOOSE_DRAW',draw:true});await until(s=>!s.windows?.length);const fresh=(await state()).players.B!.hand.filter(id=>!before.includes(id));expect(fresh).toHaveLength(1);expect(viewFor(await state(),'D').inspectionHistory).toEqual([d]);expect(JSON.stringify(viewFor(await state(),'D'))).not.toContain(fresh[0]);expect((await state()).players.B!.followers).toEqual(original.followers);expect((await state()).players.B!.chants).toEqual(original.chants);}
 }
 if(scenario!=='revelation-history')expect((await state()).players[target]).toEqual(original);if(scenario==='revelation-combat')expect((await state()).players.C!.damage).toBe(4);expect(viewFor(await state(),'D').inspection).toBeNull();expect((await state()).discard.filter(id=>id===card)).toHaveLength(1);expect((await state()).resolution).toEqual([]);
},15000);
