import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {deathSongPhysicalMode} from './fixtures/death-song-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['death-song-ordinary',false],['death-song-dedicated',false],['death-song-ordinary',true],['death-song-dedicated',true],['death-song-ordinary-teleport',false],['death-song-dedicated-teleport',false],['death-song-dedicated-resist',false],['death-song-dedicated-fail',false]] as const)('%s actual cancel=%s persists actual CHANT selected cast and target-local Gadyura resistance',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=deathSongPhysicalMode(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`death-song-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(defense=false){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||defense&&w.kind==='normal-defense')return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('DEATH_SONG_DO_SETTLE');}
 {await send('A',{type:'CHANT',cardInstanceId:m.card});for(let n=0;n<160;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w){await settle();continue;}if(s.phase==='action'){if(id==='A')break;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DEATH_SONG_DO_TURN');}}await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else if(m.teleport){await settle(true);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});}await settle();const s=(await room.stored()).state.game!;expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);expect(s.players.B!.damage).toBe(canceled||m.teleport||m.gad&&!m.fail?0:m.damage);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.damage).toBe(!canceled&&m.dedicated?m.damage:0);expect(s.players.C!.followers).toHaveLength(1);const rolls=(s.rolls??[]).filter(r=>r.purpose==='hit-resistance');expect(rolls).toHaveLength(m.gad&&!canceled?1:0);if(rolls.length)expect(rolls[0]).toMatchObject({rollerId:'B',modifier:0,threshold:m.fail?1:14,success:!m.fail});if(!m.dedicated&&!canceled)expect(s.randomRolls).toEqual([expect.objectContaining({formula:'2d6x2',faces:[1,1],total:4})]);expect(s.players.D!.damage).toBe(0);
},15000);
