import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,gameStats,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {ritualPhysicalScenarios,ritualCard} from './fixtures/ritual-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(ritualPhysicalScenarios)('%s saves actual physical ritual transformation optional reactions or private gift across every restart and replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});
 const room=await openTestRoom(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`ritual-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('RITUAL_DO_LIMIT');}
 const initial=await state();
 if(scenario==='ritual-wrong-owner'){expect(viewFor(initial,'C').legalChoices).not.toContain('TRANSFER_RITUAL');expect(viewFor(initial,'C').legalChoices).not.toContain('USE_REVIVAL_RITUAL');expect(initial.players.C!.hand).toContain(ritualCard);return;}
 if(scenario==='ritual-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(ritualCard);return;}
 if(scenario.includes('gift')){
  if(scenario==='ritual-gift-stopped'||scenario==='ritual-gift-dead-target'){if(scenario==='ritual-gift-stopped'){expect(initial.players.B!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(viewFor(initial,'B').legalChoices).not.toContain('TRANSFER_RITUAL');}else expect(initial.players.A).toMatchObject({presence:'dead',revealed:true});expect(initial.players.B!.hand).toContain(ritualCard);return;}
  if(scenario==='ritual-gift-hidden-target'){expect(initial.players.A!.revealed).toBe(false);await send('A',{type:'REVEAL_CHARACTER'});await until(s=>!s.windows?.length);}
  if(scenario==='ritual-gift-suppressed')expect(initial.players.B!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);
  const before=structuredClone(await state());await send('B',{type:'TRANSFER_RITUAL',targetId:'A'});const after=await state();expect(after.players.A!.hand).toEqual([...before.players.A!.hand,ritualCard]);expect(after.players.B!.hand).toEqual(before.players.B!.hand.filter(id=>id!==ritualCard));expect(after.players.B!.revealed).toBe(before.players.B!.revealed);for(const key of ['deck','discard','resolution','actions','phase'] as const)expect(after[key]).toEqual(before[key]);expect(after.windows?.map(w=>w.id)).toEqual(before.windows?.map(w=>w.id));expect(after.events.slice(before.events.length).find(e=>e.type==='CARD_GIFTED'&&e.audience==='public')).not.toHaveProperty('cardInstanceId');
  if(scenario==='ritual-gift-window')await until(s=>!s.windows?.length);
  if((await state()).phase==='action'){await send('A',{type:'USE_REVIVAL_RITUAL'});await until(s=>!s.windows?.length);expect((await state()).players.A!.characterId).toBe('c2-p07-r1c2');expect((await state()).discard.filter(id=>id===ritualCard)).toHaveLength(1);}return;
 }
 const before=structuredClone(initial.players.A!),used=[...initial.used!],rolls=initial.rolls?.length??0;
 await send('A',{type:'USE_REVIVAL_RITUAL'});expect((await state()).players.A!.hand).toEqual(before.hand.filter(id=>id!==ritualCard));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(ritualCard);
 if(scenario==='ritual-fate'){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===ritualCard)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.A).toEqual({...before,hand:before.hand.filter(id=>id!==ritualCard)});expect((await state()).discard).toContain(ritualCard);return;}
 await until(s=>s.windows?.at(-1)?.kind==='lifecycle-boundary');const boundary=(await state()).windows!.at(-1)!;expect(boundary.participants[boundary.cursor]).toBe('A');expect((await state()).players.A).toMatchObject({characterId:'c2-p07-r1c2',revealed:true,damage:0,abilityCharacterIds:['c2-p07-r1c2'],faction:'ヴァンミール',protection:{characterIds:[]}});expect(gameStats(await state(),'A').endurance).toBe(25);for(const key of ['followers','attachments','chants','open','permanent'] as const)expect((await state()).players.A![key]).toEqual(before[key]);expect((await state()).distances).toEqual(initial.distances);expect((await state()).used).toEqual(expect.arrayContaining(used));expect((await state()).outcome).toBeUndefined();
 const sub=scenario==='ritual-subordinates'||scenario==='ritual-both',conspiracy=scenario==='ritual-conspiracy'||scenario==='ritual-both';
 if(sub){await send('A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'});await until(s=>s.windows?.at(-1)?.id===boundary.id);}
 await until(s=>s.windows?.at(-1)?.participants[s.windows.at(-1)!.cursor]==='C');expect(viewFor(await state(),'C').lifecycleAbilities).toContain('arseil-conspiracy');if(conspiracy)await send('C',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'});await until(s=>!s.windows?.length);
 const final=await state();expect(final.rolls?.length??0).toBe(rolls);expect(final.players.B!.faction).toBe(sub?'ヴァンミール':'EVIL');expect(final.players.D!.faction).toBe(sub?'ヴァンミール':'EVIL');expect(final.players.C!.presence).toBe(conspiracy?'exited':'active');expect(final.individualResults?.C).toBe(conspiracy?'won':undefined);expect(final.discard.filter(id=>id===ritualCard)).toHaveLength(1);expect(final.phase).toBe('hand-adjustment');expect(final.outcome).toBeUndefined();
},15000);
