import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {palaceGuardPhysicalMode} from './fixtures/palace-guard-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['guard-setup', false], ['guard-turn', false], ['guard-equal', false], ['guard-higher', false], ['guard-fail', false], ['guard-waive', false], ['guard-ignore', false], ['guard-ignore-decline', false], ['guard-sky', false], ['guard-sky-decline', false], ['guard-destroy', false], ['guard-invalid', false], ['guard-army', false], ['guard-ded-hand', false], ['guard-ded-field', false], ['guard-grant-hand', false], ['guard-grant-field', false], ['guard-army', true], ['guard-ded-hand', true], ['guard-ded-field', true], ['guard-grant-field', true]] as const)('%s canceled=%s persists actual Palace Guard defense or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=palaceGuardPhysicalMode(scenario),SK='a2-p22-r1c3';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`palace-guard-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('PALACE_GUARD_DO_SETTLE');}
 if(m.column)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.front});if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});for(const id of ['A','B','C','D'])await send(id,{type:'PASS_SETUP'});await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.defense){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PALACE_GUARD_DO_TURN');}if(m.ignore)await send('B',{type:'ATTACK',cardInstanceId:'a2-p21-r1c1',targetIds:['A','C'],dedicated:true});else if(m.sky||m.destroy)await send('B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p13-r1c2',targetIds:m.sky?['A','C']:['A'],dedicated:true});else{await send('B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'});await settle();if(m.invalid){await send('B',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p21-r1c1',targetIds:['A']});await settle('attack-abilities');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c1-ab02')!;await send('B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,abilityEffectIds:['human-invalidation']});}else{const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});}}if(m.special){await settle('normal-defense');await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[SK]});}}
 else{await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await settle();if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B']});else if(m.grant){const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B']}]});}else await send('A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const id=m.grant?Object.values(s.abilities!).find(a=>a.abilityId==='c2-p06-r1c2-ab04')!.id:Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':SK))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.grant?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}

 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&!m.fail&&!m.sky&&!m.destroy&&(m.ignore||m.invalid||m.attackLevel<6),remaining=alive?m.column?[m.front,SK]:[SK]:m.column&&m.fail?[m.front]:[];expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.defense?m.ignore?[m.fail?5:0,0,5]:m.sky?[m.fail?12:5,0,12]:m.invalid?[5,0,0]:[m.destroy?0:m.fail?18:m.attackLevel>6?6:0,0,0]:[0,canceled?0:8,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(remaining);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);if(m.invalid)expect(s.players.A!.followers.every(f=>!f.revealed)).toBe(true);if(m.ignore&&!m.fail)expect(s.players.A!.followers[1]!.revealed).toBe(true);if(m.army)expect(s.discard.filter(id=>id==='a2-p05-r2c2')).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
