import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {getAction} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it('S26 actual protected death wandering and resurrection preserve distinct destinations and both setup continuations through every restart',async()=>{vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(4294967291);return array;});const room=await openTestRoom('r6-s26-attack');let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`s26-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S26_DO_WINDOW');}
 const initial=await game(),oldHand=[...initial.players.B!.hand],oldFollower=initial.players.B!.followers[0]!.cardInstanceId,deadHand=[...initial.players.C!.hand];await send('A',{type:'ATTACK',cardInstanceId:'a2-p07-r3c3',targetIds:['C'],dedicated:false});await until(s=>!s.windows?.length);let s=await game();expect(s.players.C!.presence).toBe('dead');expect(s.players.B).toMatchObject({presence:'wandering',hand:[],followers:[],damage:2});expect(s.outcome).toBeUndefined();for(const id of [...oldHand,oldFollower]){expect(s.deck).toContain(id);expect(s.discard).not.toContain(id);}for(const id of deadHand){expect(s.discard).toContain(id);expect(s.deck).not.toContain(id);}
 for(let n=0;n<40;n++){s=await game();const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'&&actor==='A')break;if(s.phase==='turn-start')await send(actor,{type:'START_TURN'});else if(s.phase==='draw')await send(actor,{type:'CHOOSE_DRAW',draw:false});else if(s.phase==='action')await send(actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment'){await send(actor,{type:'END_TURN',discardIds:[]});await until(s=>!s.windows?.length);}else throw Error('S26_DO_TURN');}
 await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});await send('A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['C'],dedicated:true});await until(s=>s.windows?.at(-1)?.kind==='re-setup');s=await game();expect(s.players.C).toMatchObject({presence:'active',damage:0,followers:[]});expect(s.players.C!.hand).toHaveLength(5);expect(s.players.B!.presence).toBe('wandering');await send('C',{type:'PASS_SETUP'});s=await game();expect(s.windows!.at(-1)).toMatchObject({kind:'re-setup',participants:['B']});expect(s.players.B).toMatchObject({presence:'active',damage:2,followers:[]});expect(s.players.B!.hand).toHaveLength(5);expect(s.players.B!.hand.every(id=>!oldHand.includes(id)&&id!==oldFollower)).toBe(true);const follower=s.players.B!.hand.find(id=>getAction(id)!.name==='小人族')!;expect(follower).toBeDefined();await send('B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:follower});expect((await game()).players.B!.followers[0]!.cardInstanceId).toBe(follower);expect((await game()).players.B!.hand).toHaveLength(5);await send('B',{type:'PASS_SETUP'});await until(s=>!s.windows?.length);s=await game();expect(s.phase).toBe('hand-adjustment');expect(s.turnSeat).toBe(0);expect(s.outcome).toBeUndefined();expect(s.events.filter(e=>['PLAYER_DIED','PLAYER_WANDERING','PLAYER_REVIVED','PLAYER_RETURNED'].includes(e.type)).map(e=>[e.type,e.actorId])).toEqual([['PLAYER_DIED','C'],['PLAYER_WANDERING','B'],['PLAYER_REVIVED','C'],['PLAYER_RETURNED','B']]);expect(s.discard.filter(id=>id==='a2-p13-r3c1')).toHaveLength(1);});
