import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {whiteMagicPhysicalMode} from './fixtures/white-magic-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['white-light-ordinary',false],['white-light-ordinary',true],['white-light-dedicated',false],['white-light-dedicated',true],['white-ring-ordinary',false],['white-ring-ordinary',true],['white-ring-dedicated',false],['white-ring-dedicated',true],['white-dance-ordinary',false],['white-dance-ordinary',true],['white-dance-dedicated',false],['white-dance-dedicated',true],['white-light-counter',false],['white-light-counter',true]] as const)('%s actual cancel=%s persists selected profile follower outcomes and optional counter',async(scenario,cancel)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=whiteMagicPhysicalMode(scenario),counter=scenario.endsWith('-counter');let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`white-magic-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stopDefense=false){for(let n=0;n<400;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||stopDefense&&w.kind==='normal-defense')return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WHITE_DO_FINISH');}async function nextOwn(){for(let n=0;n<160;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==m.card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WHITE_DO_TURN');}throw Error('WHITE_DO_LIMIT');}
 if(m.dance){await send('A',{type:'CHANT',cardInstanceId:m.card});await nextOwn();}if(counter){await send('A',{type:'ATTACK',cardInstanceId:'a2-p15-r3c2',targetIds:['B'],dedicated:false});await settle(true);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:m.card,dedicated:true});}else await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dance&&m.dedicated?['B','C','D']:['B'],dedicated:m.dedicated});if(cancel){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}await settle();const s=(await room.stored()).state.game!;expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);if(counter){expect([s.players.A!.damage,s.players.B!.damage]).toEqual(cancel?[0,5]:[6,0]);expect(s.players.A!.followers).toHaveLength(cancel?2:0);return;}const blocked=m.light&&!m.dedicated;expect(s.players.B!.damage).toBe(cancel||blocked?0:m.damage);expect(s.players.B!.followers).toHaveLength(cancel||blocked?2:0);expect(s.players.C!.damage).toBe(m.dance&&m.dedicated&&!cancel?15:0);expect(s.players.C!.followers).toHaveLength(m.dance&&m.dedicated&&!cancel?0:2);expect(s.players.D!.damage).toBe(m.dance&&m.dedicated&&!cancel?15:0);expect(s.players.A!.chants).toEqual([]);
},15000);
