import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {mountainBreakerMode} from './fixtures/mountain-breaker-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(['mountain-base','mountain-lia','mountain-lancelot','mountain-lancelot-ii','mountain-relative','breaker-base'] as const)('%s persists its physical owner package and actual Prayer relative threshold once across eviction',async(scenario)=>{
 let changed=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(changed?5:1);return array;});const room=await openTestRoom(scenario);let seq=0;const m=mountainBreakerMode(scenario),relative=scenario==='mountain-relative';
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`mountain-breaker-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(saved.state.game!.rolls?.some(r=>r.faces.length===1))changed=true;await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:m.dedicated});let boosted=false;for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;if(relative&&!boosted&&w.kind==='effect-level'){await send('A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:w.continuation.id});boosted=true;}else await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!;expect([done.players.B!.damage,done.players.C!.damage]).toEqual([m.damage,0]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);if(relative){expect(done.players.B!.followers).toEqual([]);const roll=done.rolls!.find(r=>r.faces.length===1)!;expect(roll).toMatchObject({faces:[2],total:2});expect(roll.attempts).toHaveLength(1);expect(done.discard).toContain('a2-p22-r1c2');}expect(done.phase).toBe('withdrawal');
});
