import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {angelPhysicalMode} from './fixtures/angel-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['angel-setup', false], ['angel-turn', false], ['angel-equal', false], ['angel-higher', false], ['angel-morale-fail', false], ['angel-shelim-waive', false], ['angel-lia-waive', false], ['angel-magic-low', false], ['angel-magic-equal', false], ['angel-magic-high', false], ['angel-magic-fail', false], ['angel-sky', false], ['angel-destroy', false], ['angel-army', false], ['angel-army', true]] as const)('%s canceled=%s persists exact Angel defense and paid attack',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=angelPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`angel-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;if(m.select&&w.kind==='normal-defense'&&w.participants[w.cursor]==='A'){await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[m.card]});continue;}await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('ANGEL_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.army){await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p05-r2c2')!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}
 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ANGEL_DO_TURN');}if(!m.sky&&!m.destroy&&!m.magic){const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});}else await send('B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':m.destroy?'a2-p13-r1c2':m.low?'a2-p18-r1c3':'a2-p14-r1c3',targetIds:m.sky?['A','C']:['A'],dedicated:!m.low});}
 if(m.high){await settle('effect-level');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p14-r1c3')!.id;await send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}
 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&(m.sky||(!m.destroy&&!m.fail&&(m.magic?m.low:m.attackLevel<6)));expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.army?[0,canceled?0:6,0]:m.sky?[12,0,12]:[m.destroy?0:m.magic?m.fail?8:m.high?10:0:m.fail?18:m.attackLevel>6?18:0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);if(m.sky)expect(s.players.A!.followers[0]!.revealed).toBe(false);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.select||canceled?0:1);expect(s.resolution).toEqual([]);
},15000);
