import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {shockPhysicalMode} from './fixtures/shock-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['shock-small',false],['shock-small',true],['shock-large',false],['shock-large',true],['phantom-resist',false],['phantom-resist',true],['phantom-fail',false],['phantom-fail',true],['shock-small-teleport',false],['shock-large-teleport',false],['phantom-teleport',false]] as const)('%s actual cancel=%s persists ordinary follower defense or target resistance and failure-only ten',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=shockPhysicalMode(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`shock-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(defense=false){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||defense&&w.kind==='normal-defense')return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SHOCK_DO_SETTLE');}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:false});if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else if(m.teleport){await settle(true);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});}await settle();const s=(await room.stored()).state.game!;expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);expect(s.players.B!.damage).toBe(!canceled&&!m.teleport&&m.fail?10:0);expect(s.players.B!.followers).toHaveLength(canceled||m.teleport||m.phantom||m.level===4?2:1);expect(s.players.B!.statuses??[]).toEqual([]);const rolls=(s.rolls??[]).filter(r=>r.purpose==='status-resistance');expect(rolls).toHaveLength(m.phantom&&!canceled&&!m.teleport?1:0);if(rolls.length)expect(rolls[0]).toMatchObject({rollerId:'B',modifier:-1,threshold:m.fail?1:13,success:!m.fail});expect(s.players.C!.damage).toBe(0);expect(s.players.C!.followers).toHaveLength(1);expect(s.players.D!.damage).toBe(0);
},15000);
