import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {healingPhysicalMode} from './fixtures/healing-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['heal-warrior',false],['heal-warrior',true],['heal-magic-1',false],['heal-magic-1',true],['heal-magic-2',false],['heal-magic-2',true],['heal-jill-1',false],['heal-jill-1',true],['heal-jill-2',false],['heal-jill-2',true]] as const)('%s actual near and selected healing canceled=%s save and replay exactly once',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=healingPhysicalMode(scenario);let seq=0;const initial=(await room.stored()).state.game!,other=[...initial.players.C!.hand];expect([initial.players.A!.damage,initial.players.B!.damage]).toEqual([5,4]);
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`healing-physical-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function finish(){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('HEAL_DO_FINISH');}
 if(m.dedicated){await send('A',{type:'APPROACH',targetId:'B',cardInstanceId:'a2-p24-r1c2'});await finish();const s=(await room.stored()).state.game!;expect([s.distances.A!.B,s.distances.B!.A,s.phase]).toEqual(['near','near','action']);}await send('A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:m.card,targetIds:m.dedicated?['B']:['A'],dedicated:m.dedicated});if(canceled){const s=(await room.stored()).state.game!,id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;await send('A',{type:'PASS'});await send('B',{type:'PASS'});await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}await finish();const done=(await room.stored()).state.game!;expect([done.players.A!.damage,done.players.B!.damage,done.players.C!.damage]).toEqual(canceled?[5,4,0]:m.dedicated?[5,0,0]:[0,4,0]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.players.A!.hand).not.toContain(m.card);expect(done.players.A!.chants).toEqual([]);expect(done.players.C!.hand.filter(id=>id!== 'a2-p02-r2c3')).toEqual(expect.arrayContaining(other.filter(id=>id!=='a2-p02-r2c3')));expect(done.phase).toBe('hand-adjustment');expect(done.outcome).toBeUndefined();
},15000);
