import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {lightKingScenarios,lightKingCard as CARD,lightKingMode} from './fixtures/light-king-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(lightKingScenarios)('%s physical normal defense and whole substitution survive every restart and replay',async name=>{
 let faces:number[]=[1,1];vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let i=0;i<array.length;i++)array[i]=faces[i%faces.length]!-1;return array;});const room=await openTestRoom(name);let seq=0;
 async function act(s:GameState,actorId:string,command:unknown,dice:number[]=[1,1]){faces=dice.length?dice:[1,1];const before=await room.stored();expect(before.state.game).toEqual(s);const envelope={protocolVersion:1 as const,commandId:`light-king-${seq++}`,expectedRevision:before.revision,...activeWindowRef(s),command:command as GameCommand},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);return saved.state.game!;}
 async function reject(s:GameState,actorId:string,command:unknown){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`light-king-reject-${seq++}`,expectedRevision:before.revision,...activeWindowRef(s),command:command as GameCommand},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(s);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(s);}
 async function pass(s:GameState,dice:number[]=[1,1]){const w=s.windows!.at(-1)!;return act(s,w.participants[w.cursor]!,{type:'PASS'},dice);}
 async function until(s:GameState,done:(s:GameState)=>boolean,dice:number[]=[3,4]){for(let n=0;n<700;n++){if(done(s))return s;s=await pass(s,s.windows?.at(-1)?.kind==='damage'||s.rolls?.at(-1)?.purpose==='attack-damage'||s.rolls?.at(-1)?.stage==='after-roll'?dice:[1,1]);}throw Error('LIGHT_KING_DO_LIMIT');}
 async function settle(s:GameState){return until(s,s=>!s.windows?.length);}
 async function closeWindow(s:GameState,dice:number[]=[1,1]){const id=s.windows!.at(-1)!.id;while(s.windows?.at(-1)?.id===id)s=await pass(s,dice);return s;}
 function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
 let s=(await room.stored()).state.game!;const m=lightKingMode(name),hand=[...s.players.C!.hand];if(m.suffix==='root'){for(const dedicated of [false,true]){await reject(s,'C',{type:'ATTACK',cardInstanceId:CARD,targetIds:['A'],dedicated});await reject(s,'C',{type:'CHANT',cardInstanceId:CARD,dedicated});}return;}const normal={type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:m.dedicated};
 if(m.suffix==='evil'||m.suffix==='low-effect'){await reject(s,'C',normal);expect(s.players.C!.hand).toEqual(hand);return;}if(m.suffix==='decline'){s=await settle(s);expect(s.players.C!.damage).toBe(4);expect(s.players.C!.hand).toEqual(hand);return;}
 const original=Object.values(s.groups!)[0]!;if(m.prohibited){expect(viewFor(s,'C').groupDefenseOptions).toEqual([]);await reject(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId:original.id,dedicated:true});return;}
 if(m.group){const option=viewFor(s,'C').groupDefenseOptions[0]!;expect(option).toBeDefined();s=await act(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId:original.id,dedicated:true});const action=source(s);expect(action.substitution!.hits).toHaveLength(m.multi?6:2);expect(action.substitution!.hits.every(h=>h.targetId!=='C')).toBe(true);}else s=await act(s,'C',normal);
 expect(s.players.C!.hand).toEqual(hand.filter(id=>id!==CARD));expect(source(s).technique).toMatchObject({school:'magic',range:'none',useLevel:6,effectLevel:6,attributes:['魔','白','反'],damageFormula:'d6-product-min10',counter:true,noChecks:m.dedicated});
 if(m.suffix==='group-fate'){const id=source(s).id;s=await until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=await act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
 if(m.suffix==='precheck-fail'||m.suffix==='usage-fail'||m.suffix==='group-fail'){s=await until(s,s=>s.rolls?.at(-1)?.stage==='before-roll');if(m.suffix==='usage-fail'){expect(s.rolls!.at(-1)).toMatchObject({purpose:'activation',modifier:-2});s=await closeWindow(s,[2,2]);s=await until(s,s=>s.rolls?.at(-1)?.purpose==='excess-level'&&s.rolls.at(-1)?.stage==='before-roll');s=await closeWindow(s,[3,4]);}else{s=await closeWindow(s,m.group?[2,2]:[2,3]);}s=await settle(s);expect(s.players.C!.damage).toBe(m.group?0:4);if(m.group){expect(s.players.B!.damage).toBe(15);expect(s.players.D!.damage).toBe(15);}expect(s.players.A!.damage).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 if(m.suffix==='reroll'){s=await until(s,s=>s.rolls?.at(-1)?.formula==='d6-product-min10'&&s.rolls.at(-1)?.stage==='after-roll',[2,3]);const id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.total).toBe(10);s=await until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=await act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=await until(s,s=>s.rolls!.find(r=>r.id===id)?.generation===1,[3,4]);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[3,4],total:12,generation:1});}
 if(m.group&&m.suffix!=='group-fate'){s=await until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'A').activeWindow?.pendingActorId==='A');const g=Object.values(s.groups!).find(g=>g.attackerId==='C')!;expect(g.targets.map(t=>t.actorId)).toEqual(['A']);expect(g.targets[0]!.hits).toHaveLength(1);expect(g.technique.followerIgnore).toBe(false);expect(g.technique.damage).toBe(12);if(m.suffix==='return-maai')s=await act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(m.suffix==='return-evade')s=await act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 s=await settle(s);const cancelled=m.suffix==='group-fate';expect(s.players.A!.damage).toBe(m.group&&!cancelled&&!m.nightmare&&!m.suffix.startsWith('return')?12:0);expect(s.players.B!.damage).toBe(cancelled?15:0);expect(s.players.D!.damage).toBe(cancelled?15:0);expect(s.players.C!.damage).toBe(m.suffix==='group-self'?15:0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);if(m.suffix==='return-water'||m.nightmare)expect(s.players.A!.followers).toHaveLength(1);
},30000);
