import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {amuletPhysicalScenarios,amuletMode} from './fixtures/amulet-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(amuletPhysicalScenarios)('%s persists actual named mental cancellation and unchanged prior effects with restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(scenario==='amulet-card-charm'?5:0);return array;});const room=await openTestRoom(scenario),card='a2-p01-r3c2',m=amuletMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`amulet-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('AMULET_DO_PHASE');}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(await state()))return;await step();}throw Error('AMULET_DO_LIMIT');}
 async function use(){const o=viewFor(await state(),'B').abilityOptions.find(o=>o.abilityId===m.abilityId)!;expect(o).toBeDefined();await send('B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});}
 const prior=structuredClone((await state()).players.C!),rollCount=(await state()).rolls?.length??0,hand=(await state()).players.D!.hand.length;
 if(scenario==='amulet-card-charm')await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r1c2',targetId:'C'});else{await send('A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false});await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await use();}
 const ignored=scenario==='amulet-decline'||scenario==='amulet-card-charm'||m.other;
 if(ignored){await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='D';});expect(viewFor(await state(),'D').anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(scenario==='amulet-decline');}
 else{await until(s=>viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId===card));const o=viewFor(await state(),'D').anytimeCardOptions.find(o=>o.cardInstanceId===card)!,base=gameStats(await state(),'D');await send('D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId});expect((await state()).players.D!.hand).toHaveLength(hand);if(scenario==='amulet-refill'){expect((await state()).players.D!.open).toContain('a2-p01-r1c3');expect(gameStats(await state(),'D')).toMatchObject({warrior_level:base.warrior_level+1,magic_level:base.magic_level+1,spirit:base.spirit+1});}if(scenario==='amulet-canceled'){const child=Object.values((await state()).actions!).find(a=>a.cardInstanceId===card)!;await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='C';});await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});}}
 await until(s=>!s.windows?.length);let s=await state();if(!ignored&&scenario!=='amulet-canceled'){expect(s.players.B!.damage).toBe(4);expect(s.rolls?.length??0).toBe(rollCount);expect(s.players.A!.statuses??[]).toEqual([]);}else if(scenario==='amulet-decline'||scenario==='amulet-canceled'){expect(s.players.B!.damage).toBe(0);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.rolls!.length).toBe(rollCount+1);}if(scenario==='amulet-card-charm')expect(s.players.C!.faction).toBe('EVIL');if(m.prior)expect(s.players.C).toEqual(prior);if(ignored)expect(s.players.D!.hand).toContain(card);else expect(s.discard.filter(id=>id===card)).toHaveLength(1);
 if(scenario==='amulet-later'){await until(s=>!s.windows?.length&&s.seatOrder[s.turnSeat]==='A'&&s.phase==='action');await send('A',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['B'],dedicated:false});await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await use();await until(s=>!s.windows?.length);s=await state();expect(s.players.B!.damage).toBe(4);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);}
 expect((await state()).resolution).toEqual([]);
},15000);
