import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {beastKingScenarios,beastKingCard as CARD,beastKingMode} from './fixtures/beast-king-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(beastKingScenarios)('%s physical composite source choice followers and damage persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(['beast-king-nonbeast','beast-king-multi'].includes(scenario)?0:2);return array;});const room=await openTestRoom(scenario),m=beastKingMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`beast-king-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`beast-king-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<800;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BEAST_KING_DO_LIMIT');}
 const initial=structuredClone(await state()),targets=m.suffix==='placed-griffin'?['B','C']:['B'];const command:GameCommand={type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated,...(m.co?{coSource:{cardInstanceId:m.co,dedicated:m.coDedicated}}:{})};
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'){await reject('A',command);expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='unchanted'||m.suffix==='level-low'){await reject('A',command);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand);return;}
 if(m.suffix==='invalid-co'){for(const co of ['a2-p12-r2c2','a2-p05-r3c1','a2-p24-r2c2',CARD])await reject('A',{...command,coSource:{cardInstanceId:co,dedicated:false}});await reject('A',{...command,coSource:{cardInstanceId:'a2-p08-r3c3',dedicated:true}});}
 if(m.suffix==='same-faction')await reject('A',{...command,targetIds:['C']});if(m.suffix==='near-far'){await reject('A',command);await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await until(s=>!s.windows?.length);}
 const before=await state();await send('A',m.suffix==='counter'?{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true,coSource:{cardInstanceId:m.co!,dedicated:false}}:command);expect((await state()).players.A!.hand).toEqual(before.players.A!.hand.filter(id=>![CARD,m.co].includes(id)));expect((await state()).deck).toEqual(before.deck);expect((await state()).resolution).toEqual(expect.arrayContaining([CARD,...(m.co?[m.co]:[])]));if(m.coDedicated)expect((await state()).players.A!.followers).toEqual([]);
 const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(m.suffix==='fate'){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(0);expect((await state()).players.B!.followers).toEqual(initial.players.B!.followers);for(const id of [CARD,m.co])expect((await state()).discard.filter(c=>c===id)).toHaveLength(1);return;}
 if(m.suffix==='multi-fail'){await until(s=>!s.windows?.length);const final=await state();expect(final.players.B!.damage).toBe(0);expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.rolls!.at(-1)).toMatchObject({purpose:'activation',threshold:4,total:6,success:false});expect(final.rolls!.filter(r=>r.kind==='numeric')).toHaveLength(0);for(const id of [CARD,m.co])expect(final.discard.filter(c=>c===id)).toHaveLength(1);return;}
 if(m.suffix==='multi'){await until(s=>s.windows?.at(-1)?.kind==='damage');expect((await state()).rolls!.at(-1)).toMatchObject({purpose:'activation',threshold:4,total:2,success:true});vi.mocked(crypto.getRandomValues).mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities'&&Object.values(s.groups!).some(g=>g.actionId===source(s).id));const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!,damage=({bow:14,spirit:16,null:10,wolf:16,multi:17,chant:22,'invalid-co':14,'near-far':15,union:16,'maai-one':17,'maai-two':17,'evade-restrict':18,counter:15,'placed-griffin':18} as Record<string,number>)[m.suffix]??10,hits=m.suffix==='multi'?3:m.coDedicated?2:1;
 expect(g.technique).toMatchObject({school:'warrior',useLevel:6,effectLevel:6,damage,noChecks:m.dedicated});expect(g.technique.attributes).toEqual(expect.arrayContaining(['戦','剣','獣']));expect(g.sourceCardInstanceIds).toEqual([CARD,...(m.co?[m.co]:[])]);expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual(targets.map(()=>Array(hits).fill(damage)));if(m.chant)expect(source(prepared).coSource!.fromChant).toBe(true);if(m.suffix==='null')expect(source(prepared).coSource!.technique.damage).toBeNull();if(m.suffix==='union')expect(g.technique.destroyFollowerAttributes).toEqual(['獣','白']);
 if(m.suffix.startsWith('maai')||m.suffix==='evade-restrict'){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.suffix==='evade-restrict'){expect(viewFor(await state(),'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);await reject('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}else{await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});await until(s=>s.windows?.at(-1)?.kind!=='reclaim');expect(viewFor(await state(),'B').maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});if(m.suffix==='maai-two')await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}}
 await until(s=>!s.windows?.length);const final=await state(),blocked=m.guard&&(!m.dedicated||m.suffix==='nonbeast')||m.suffix==='maai-two';expect(final.players.B!.damage).toBe(blocked?0:damage*hits);expect(final.players.C!.damage).toBe(m.coDedicated?34:0);expect(final.players.A!.damage).toBe(0);if(m.guard){const survives=blocked||m.suffix==='spirit';expect(final.players.B!.followers).toHaveLength(survives?1:0);if(survives)expect(final.players.B!.followers[0]!.revealed).toBe(!['spirit','maai-two'].includes(m.suffix));}for(const id of [CARD,...(m.co?[m.co]:[])])expect(final.discard.filter(c=>c===id)).toHaveLength(1);if(m.suffix==='low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.filter(r=>r.purpose==='excess-level').length??0).toBe(initial.rolls?.filter(r=>r.purpose==='excess-level').length??0);if(m.suffix==='wolf'||m.suffix==='multi')expect(final.rolls!.filter(r=>r.kind==='numeric')).toHaveLength(1);
},15000);
