import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {earthMagicMode} from './fixtures/earth-magic-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(['earth-spear-ordinary','earth-spear-dedicated','earth-stream-ordinary','earth-stream-dedicated'] as const)('%s persists physical earth magic and one or two maai while preserving other selected targets',async(scenario)=>{
 const room=await openTestRoom(scenario);let seq=0;const m=earthMagicMode(scenario);
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`earth-magic-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});let used=0;for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;if(used<m.maai&&w.kind==='normal-defense'){await send('B',{type:'PLAY_MAAI',cardInstanceId:used===0?'a2-p07-r1c1':'a2-p07-r1c2'});used++;}else await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!;expect([done.players.B!.damage,done.players.C!.damage,done.players.D!.damage]).toEqual([0,m.dedicated?m.damage:0,0]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.discard).toContain('a2-p07-r1c1');expect(done.players.B!.hand.includes('a2-p07-r1c2')).toBe(m.maai===1);expect(done.phase).toBe('withdrawal');
});

it.each([['earth-spear-dedicated',true],['earth-stream-dedicated',true]] as const)('%s actual Fate reclaim later turn and printed maai save every command with canceledThenReused=%s',async(scenario,canceled)=>{
 const m=earthMagicMode(scenario),{dedicated,damage}=m;
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario);let seq=0;const card=m.card;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`earth-magic-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function nextOwn(){for(let n=0;n<100;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('EARTH_MAGIC_DO_TURN');}throw Error('EARTH_MAGIC_DO_TURN_LIMIT');}
 async function finish(reclaim=false){let taken=false;for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;const d=viewFor(s,'A').reclaim;if(reclaim&&!taken&&w.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){await send('A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});taken=true;}else await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('EARTH_MAGIC_DO_FINISH');}
 await send('A',{type:'ATTACK',cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated});if(canceled){const s=(await room.stored()).state.game!,id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;await send('A',{type:'PASS'});await send('B',{type:'PASS'});await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await finish(true);expect((await room.stored()).state.game!.players.A!.hand).toContain(card);await nextOwn();await send('A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true});}
 for(let n=0;n<200;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(w?.kind==='normal-defense')break;if(!w)throw Error('EARTH_MAGIC_NO_DEFENSE');await send(w.participants[w.cursor]!,{type:'PASS'});}
 for(const maai of ['a2-p07-r1c1','a2-p07-r1c2'].slice(0,m.maai)){await send('B',{type:'PLAY_MAAI',cardInstanceId:maai});for(let n=0;n<100;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(w?.kind!=='reclaim')break;await send(w.participants[w.cursor]!,{type:'PASS'});}}
 await finish();const done=(await room.stored()).state.game!;expect([done.players.B!.damage,done.players.C!.damage,done.players.D!.damage]).toEqual([0,dedicated?damage:0,0]);expect(done.players.A!.chants).toEqual([]);expect(done.discard.filter(id=>id===card)).toHaveLength(1);expect(done.players.A!.hand).not.toContain(card);expect(done.phase).toBe('withdrawal');expect(done.discard).toEqual(expect.arrayContaining(['a2-p07-r1c1','a2-p07-r1c2'].slice(0,m.maai)));
},15000);
