import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {getAction} from '@madou/catalog';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(['s06','s08','s09','s10'] as const)('S06-S10 %s real DO resumes every defense command and duplicate receipt without replaying costs or hits',async(mode)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(1);return array;});const room=await openTestRoom(`r6-${mode}`);let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,error=false){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`${mode}-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(error){expect(saved.state.game).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);}await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S06_10_DO_WINDOW');}
 const s=await game(),main=Object.values(s.actions!).find(a=>a.kind==='attack')!;
 if(mode==='s06'){expect(main.technique.effectLevel).toBe(6);const hand=[...s.players.A!.hand],used=[...s.used!];await send('A',{type:'USE_ABILITY',abilityId:'c2-p01-r2c1-ab03',targetEventId:main.eventId},true);expect((await game()).players.A!.hand).toEqual(hand);expect((await game()).used).toEqual(used);}
 else {const name=mode==='s08'?'閃光槍':'妖撃破山剣',counter=s.players.B!.hand.find(id=>getAction(id)!.name===name)!;
 if(mode==='s08'){const teleport=s.discard.find(id=>getAction(id)!.name==='転移')!;expect(teleport).toBeDefined();expect(s.rolls!.some(r=>r.faces.join(',')==='6,6'&&r.success===false)).toBe(true);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false},true);}
 await send('B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false,...(mode==='s09'?{declarationAbilityIds:['c2-p05-r2c1-ab03']}: {})});
 if(mode==='s09'){await until(s=>s.windows?.at(-1)?.kind==='damage');expect(Object.values((await game()).actions!).find(a=>a.kind==='defense')!.technique).toMatchObject({effectLevel:6,defense:'counter'});await until(s=>s.windows?.at(-1)?.kind==='normal-defense');const now=await game(),g=Object.values(now.groups!)[0]!;expect(now.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});expect(g.targets[0]!.hits[0]!.defended).toBe(true);expect(g.technique.effectLevel).toBe(6);expect(g.targets[1]!.hits[0]).toMatchObject({damage:12,defended:false});}
 if(mode==='s10'){expect(main.technique.effectLevel).toBe(5);expect(s.distances.A!.B).toBe('far');await until(s=>s.windows?.at(-1)?.kind==='effect-level'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='B');const now=await game(),id=Object.values(now.actions!).find(a=>a.kind==='defense')!.id,prayer=now.players.B!.hand.find(id=>getAction(id)!.name==='必勝の祈り')!;await send('B',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:id});await until(s=>s.windows?.at(-1)?.kind==='damage'&&s.windows.at(-1)!.continuation.id===id);expect((await game()).actions![id]!.technique).toMatchObject({effectLevel:7,range:'near'});}}
 await until(s=>!s.windows?.length);const done=await game();expect([done.players.A!.damage,done.players.B!.damage,done.players.C!.damage]).toEqual(mode==='s06'?[0,5,0]:mode==='s08'?[5,0,0]:mode==='s09'?[0,0,12]:[0,0,0]);expect(done.groups).toEqual({});expect(done.phase).toBe('withdrawal');
});
