import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {shurikenScenarios,shurikenCard as CARD,shurikenChants as CHANTS,shurikenMode} from './fixtures/shuriken-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(shurikenScenarios)('%s physical attack counter numeric damage and per-target all-chant choice survive every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=shurikenMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`shuriken-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){const s=await state();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SHURIKEN_DO_LIMIT');}
 const initial=structuredClone(await state());if(scenario==='shuriken-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');return;}if(scenario==='shuriken-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(scenario==='shuriken-wrong-owner'){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:'shuriken-invalid-owner',expectedRevision:stored.revision,command:{type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:true}},error=await room.command('A',envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(initial);await room.restart();expect(await room.command('A',envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(initial);return;}
 const targets=m.counter?['B']:scenario==='shuriken-all'?['B','C','D']:m.dedicated&&!['shuriken-subset','shuriken-near'].includes(scenario)?['B','C']:['B'];await send('A',m.counter?{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:m.dedicated}:{type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);
 if(scenario==='shuriken-fate'){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);for(const id of ['B','C'])expect((await state()).players[id]).toEqual(initial.players[id]);expect((await state()).rolls?.length??0).toBe(initial.rolls?.length??0);return;}
 if(!m.counter){await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(Object.values((await state()).groups!).at(-1)!.technique).toMatchObject({useLevel:4,effectLevel:m.dedicated?6:4,damage:m.dedicated?15:5,attributes:['戦','忍','反'],noChecks:m.dedicated,followerIgnore:m.dedicated,counter:true});}
 if(scenario==='shuriken-maai'||scenario==='shuriken-evade'){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',scenario==='shuriken-maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 const removed:string[]=[];let choices=0;for(let n=0;n<500;n++){const s=await state(),w=s.windows?.at(-1);if(!w)break;if(w.kind==='on-hit-choice'){if(w.continuation.kind!=='group')throw Error('SHURIKEN_HIT_GROUP');const id=w.continuation.targetId!,discard=scenario!=='shuriken-keep'&&(scenario!=='shuriken-mixed'||id==='B');choices++;for(const chant of s.players[id]!.chants)expect(JSON.stringify(viewFor(s,'A'))).not.toContain(chant.cardInstanceId);if(discard)removed.push(id);await send('A',{type:'DISCARD_HIT_CHANTS',discard});}else await send(w.participants[w.cursor]!,{type:'PASS'});}
 const final=await state(),evaded=['shuriken-maai','shuriken-evade'].includes(scenario);expect(final.windows??[]).toEqual([]);for(const id of ['B','C','D'])expect(final.players[id]!.damage).toBe(scenario==='shuriken-counter-equal'||id==='B'&&evaded?0:targets.includes(id)&&(!m.guard||m.dedicated)?m.dedicated?15:5:0);expect(final.players.A!.damage).toBe(0);if(m.dedicated){expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);expect(final.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);}else if(m.guard)expect(final.players.B!.followers[0]!.revealed).toBe(true);for(const id of ['B','C'])expect(final.players[id]!.chants).toEqual(removed.includes(id)?[]:initial.players[id]!.chants);expect(choices).toBe(m.dedicated?targets.filter(id=>id==='C'||id==='B'&&!evaded).length:0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);if(scenario==='shuriken-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});
},15000);
