import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {blackDragonScenarios,blackDragonCard as CARD,blackDragonMode} from './fixtures/black-dragon-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(blackDragonScenarios)('%s physical near sword white destruction and ordered followers persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(['black-dragon-double-fail','black-dragon-double-reroll'].includes(scenario)?3:2);return array;});const room=await openTestRoom(scenario),m=blackDragonMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`black-dragon-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`black-dragon-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<600;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BLACK_DRAGON_DO_LIMIT');}
 const initial=structuredClone(await state()),command:GameCommand={type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:m.dedicated};
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'){await reject('A',command);expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='far'){await reject('A',command);await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await until(s=>!s.windows?.length);}if(m.suffix==='same-faction')await reject('A',{...command,targetIds:['C']});const before=await state();await send('A',command);expect((await state()).players.A!.hand).toEqual(before.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(before.deck);expect((await state()).resolution).toContain(CARD);
 if(m.suffix==='fate'){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===CARD)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(0);expect((await state()).players.B!.followers).toEqual(initial.players.B!.followers);expect((await state()).discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 let doubled=false;
 if(m.dedicated){await until(s=>s.windows?.at(-1)?.kind==='technique-double-choice');const actionId=Object.values((await state()).actions!).find(a=>a.cardInstanceId===CARD)!.id;expect(viewFor(await state(),'A').techniqueDecision).toMatchObject({kind:'damage-double',actionId});expect((await state()).rolls?.length??0).toBe(initial.rolls?.length??0);await reject('B',{type:'CHOOSE_DAMAGE_DOUBLE',actionId,attempt:true});await send('A',{type:'CHOOSE_DAMAGE_DOUBLE',actionId,attempt:m.attempt});
  if(m.attempt){const rollId=(await state()).rolls!.at(-1)!.id,forced=m.suffix.includes('force'),reroll=m.suffix.includes('reroll');await reject('A',{type:'CHOOSE_DAMAGE_DOUBLE',actionId,attempt:true});if(forced){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:rollId});}await until(s=>s.windows?.at(-1)?.kind==='after-roll');let roll=(await state()).rolls!.find(r=>r.id===rollId)!;expect(roll).toMatchObject({purpose:'technique-check',threshold:m.suffix==='double-lowspirit'?0:6,success:!forced&&!['double-lowspirit','double-fail','double-reroll'].includes(m.suffix)});
   if(reroll){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');vi.mocked(crypto.getRandomValues).mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:rollId});await until(s=>s.rolls!.find(r=>r.id===rollId)?.generation===1&&s.rolls!.find(r=>r.id===rollId)?.stage==='after-roll');roll=(await state()).rolls!.find(r=>r.id===rollId)!;expect(roll).toMatchObject({faces:[1,1],total:2,generation:1,success:!forced});}doubled=roll.success!;
  }
 }
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(Object.values((await state()).groups!)[0]!.technique).toMatchObject({school:'warrior',range:'near',useLevel:5,effectLevel:m.dedicated?6:5,damage:m.dedicated?doubled?20:10:6,attributes:['戦','剣'],destroyFollowerAttributes:['白'],target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});
 if(['maai','evade','double-maai','double-evade'].includes(m.suffix)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(await state(),'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:false,evadeProhibited:false});await send('B',m.suffix.endsWith('maai')?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 await until(s=>!s.windows?.length);const final=await state(),avoided=['maai','evade','double-maai','double-evade'].includes(m.suffix),blocked=m.suffix==='nonwhite',reduced=['lower','double-lower'].includes(m.suffix),damage=m.dedicated?doubled?20:10:6;expect(final.players.B!.damage).toBe(avoided||blocked?0:damage-(reduced?2:0));expect(final.players.C!.damage).toBe(0);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);if(avoided)expect(final.players.B!.followers).toEqual(initial.players.B!.followers);else{expect(final.players.B!.followers).toEqual([]);for(const id of m.followers)expect(final.discard).toContain(id);}expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);if(m.suffix==='low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.length??0).toBe((initial.rolls?.length??0)+(m.attempt?1:0));if(m.attempt)expect(final.rolls!.filter(r=>r.purpose==='technique-check')).toHaveLength(1);if(m.suffix.includes('force'))expect(final.discard.filter(id=>id==='a2-p02-r2c3')).toHaveLength(1);if(m.suffix.includes('reroll'))expect(final.discard.filter(id=>id==='a2-p02-r1c3')).toHaveLength(1);
},15000);
