import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {lesterSongsPhysicalMode} from './fixtures/lester-songs-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['poem-ordinary',false],['poem-ordinary',true],['poem-dedicated',false],['poem-dedicated',true],['chant-song-ordinary',false],['chant-song-ordinary',true],['chant-song-dedicated',false],['chant-song-dedicated',true],['poem-ordinary-teleport',false],['poem-dedicated-teleport',false],['chant-song-ordinary-teleport',false],['chant-song-dedicated-teleport',false]] as const)('%s cancel=%s actual selected attacks resistance and recovery persist through every command',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=lesterSongsPhysicalMode(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`lester-songs-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:'normal-defense'|'resistance'){for(let n=0;n<350;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||stop==='normal-defense'&&w.kind===stop||stop==='resistance'&&w.kind==='after-roll'&&s.rolls?.at(-1)?.purpose==='status-resistance')return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('LESTER_SONGS_DO_SETTLE');}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});const forced=m.poem&&!canceled&&!m.teleport;if(canceled||forced){if(forced)await settle('resistance');let s=(await room.stored()).state.game!;const actionId=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id,rollId=s.rolls?.at(-1)?.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',forced?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:rollId!}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId});}else if(m.teleport){await settle('normal-defense');await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});}await settle();let s=(await room.stored()).state.game!;const damage=m.poem&&!m.dedicated?4:m.damage;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,canceled||m.teleport?0:damage,!canceled&&m.dedicated?m.damage:0,0]);expect(s.players.B!.followers).toHaveLength(!canceled&&!m.teleport&&m.poem&&!m.dedicated?1:2);expect(s.players.C!.followers).toHaveLength(1);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);expect(s.players.B!.statuses??[]).toHaveLength(forced?1:0);expect(s.players.C!.statuses??[]).toEqual([]);if(!m.poem&&!canceled)expect(s.randomRolls).toEqual([expect.objectContaining({formula:m.dedicated?'d6x4':'d6x2',faces:[1],total:m.damage})]);if(!forced)return;const status=s.players.B!.statuses![0]!;expect(status).toMatchObject({kind:'stopped',modifiers:m.dedicated?[-3]:[-3,-2,-1],nextCheck:1,sourceActorId:'A',sourceCardInstanceId:m.card});for(let n=0;n<180;n++){s=(await room.stored()).state.game!;const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='turn-start')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('LESTER_SONGS_DO_TURN');}await send('B',{type:'START_TURN'});expect((await room.stored()).state.game!.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:m.dedicated?-3:-2});await settle();s=(await room.stored()).state.game!;expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.damage).toBe(damage);expect(s.phase).toBe('draw');await send('B',{type:'CHOOSE_DRAW',draw:false});expect((await room.stored()).state.game!.phase).toBe('action');
},15000);
