import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {wightPhysicalMode} from './fixtures/wight-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['wight-defense-turn',false],['wight-defense-equal',false],['wight-defense-revive',false],['wight-defense-mixed',false],['wight-defense-destroy',false],['wight-attack-hand',false],['wight-attack-field',false],['wight-army',false],['wight-attack-maai',false],['wight-attack-hand',true],['wight-attack-field',true],['wight-army',true],['wight-attack-ignore',false],['wight-army-ignore',false],['wight-attack-guard',false],['wight-attack-mirror',false]] as const)('%s canceled=%s persists actual Wight revival or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=wightPhysicalMode(scenario),SK='a2-p21-r1c1';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wight-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WIGHT_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});for(const id of ['A','B','C','D']){if(id==='B'&&(m.ignore||m.guard)){await send('B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});if(m.guard)await send('B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r3c3'});}await send(id,{type:'PASS_SETUP'});}await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.defense){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WIGHT_DO_TURN');}await send('B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'});await settle();if(m.destroy)await send('B',{type:'ATTACK',cardInstanceId:'a2-p14-r1c2',targetIds:['A'],dedicated:false});else{const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:(m.mixed?['a2-p21-r2c3','a2-p22-r1c3']:['a2-p21-r2c3']).map(cardInstanceId=>({cardInstanceId,dedicated:false,targetIds:['A']}))});}}
 else{if(m.army){await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await settle();await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B']});}else await send('A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B','C'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':SK))!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id});}else if(m.maai||m.mirror){await settle('normal-defense');await send('B',m.mirror?{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}:{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});}}
 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&!m.destroy&&!m.mixed;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.defense?[m.destroy?6:m.mixed?26:m.level===5?0:18,0,0]:[0,canceled||m.maai||m.guard||m.mirror?0:5,canceled||m.army?0:5]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[SK]:[]);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);if(m.ignore)expect(s.players.B!.followers).toContainEqual(expect.objectContaining({cardInstanceId:'a2-p22-r1c1',revealed:false}));if(m.guard){expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1','a2-p22-r3c3']);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);}expect(s.resolution).toEqual([]);
},15000);
