import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {knightOrdersPhysicalMode} from './fixtures/knight-orders-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['black-knights-setup',false],['black-knights-turn',false],['holy-knights-setup',false],['holy-knights-turn',false],['black-knights-army',false],['holy-knights-army',false],['black-knights-ded-hand',false],['black-knights-ded-field',false],['holy-knights-ded-hand',false],['holy-knights-ded-field',false],['black-knights-sword',false],['holy-knights-inherited',false],['black-knights-ded-hand',true],['black-knights-ded-field',true],['holy-knights-ded-hand',true],['holy-knights-ded-field',true],['black-knights-army',true],['holy-knights-army',true]] as const)('%s canceled=%s persists exact Knight Order defense and paid attack',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=knightOrdersPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`knight-orders-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('KNIGHT_ORDERS_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.dedicated||m.army){if(!m.sword){await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await settle();}if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});else await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true,...(m.sword?{declarationAbilityIds:['c2-p05-r2c1-ab03']}:{})});if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':m.card))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}
 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('KNIGHT_ORDERS_DO_TURN');}await send('B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
 await settle();const s=(await room.stored()).state.game!,alive=!m.dedicated&&!m.army;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.dedicated||m.army?[0,canceled?0:m.sword?14:m.dedicated&&m.black?10:m.attackDamage,0]:[0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
