import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['wolf-ordinary','a2-p10-r3c1',false,null,5],['wolf-dedicated','a2-p10-r3c1',true,null,9],['lance-ordinary','a2-p10-r3c2',false,null,5],['lance-one','a2-p10-r3c2',true,'one-hit',7],['lance-two','a2-p10-r3c2',true,'two-hit',14]] as const)('%s physical %s dedicated=%s variant=%s persists damage%s once',async(scenario,card,dedicated,variant,damage)=>{
 let changed=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let i=0;i<array.length;i++)array[i]=changed?5:i%3+1;return array;});const room=await openTestRoom(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wolf-lance-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(saved.state.game!.rolls?.some(r=>r.purpose==='attack-damage'&&r.stage==='after-roll'))changed=true;await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated,...(variant?{techniqueVariant:variant}:{})});for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!;expect(done.windows).toEqual([]);expect(done.players.B!.damage).toBe(damage);expect(done.discard.filter(id=>id===card)).toHaveLength(1);expect(done.players.A!.hand).not.toContain(card);expect(done.phase).toBe('withdrawal');if(scenario.startsWith('wolf')){const roll=done.rolls!.find(r=>r.purpose==='attack-damage')!;expect(roll).toMatchObject({faces:dedicated?[2,3,4]:[2,3],total:damage});expect(roll.attempts).toHaveLength(1);}
});
