import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {madKingPhysicalMode,madKingPhysicalScenarios} from './fixtures/mad-king-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(madKingPhysicalScenarios)('%s actual attack counter stop and own-turn recovery persist through every command replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=madKingPhysicalMode(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`mad-king-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||stop===w.kind)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('MAD_KING_DO_SETTLE');}
 async function toTurn(phase='action'){for(let n=0;n<180;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w){await settle();continue;}if(id==='B'&&s.phase===phase)return;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('MAD_KING_DO_TURN');}throw Error('MAD_KING_DO_TURN_LIMIT');}
 if(m.counter){await send('A',{type:'PASS_ACTION'});await toTurn();await send('B',{type:'ATTACK',cardInstanceId:'a2-p15-r3c2',targetIds:['A'],dedicated:false});await settle('normal-defense');await send('A',{type:'PLAY_DEFENSE',cardInstanceId:m.card,dedicated:false});}else await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:false});
 if(m.cancel||m.recover){if(m.recover){for(let n=0;n<200;n++){const s=(await room.stored()).state.game!,w=s.windows!.at(-1)!;if(w.kind==='after-roll'&&s.rolls?.at(-1)?.purpose==='status-resistance')break;await send(w.participants[w.cursor]!,{type:'PASS'});}}let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id,roll=s.rolls?.at(-1)?.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.recover?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else if(m.teleport){await settle('normal-defense');await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});}await settle();let s=(await room.stored()).state.game!;const stopped=!m.cancel&&!m.resist&&!m.teleport;expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,m.cancel||m.teleport?0:4,0]);expect(s.players.B!.followers).toHaveLength(m.cancel||m.teleport?2:1);expect(s.players.B!.statuses??[]).toHaveLength(stopped?1:0);if(!stopped)return;const status=s.players.B!.statuses![0]!;expect(status).toMatchObject({kind:'stopped',modifiers:[-2,-1,0],nextCheck:1,sourceActorId:'A',sourceCardInstanceId:m.card});for(let i=1;i<=(m.recover?1:2);i++){await toTurn('turn-start');await send('B',{type:'START_TURN'});expect((await room.stored()).state.game!.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:i===1?-1:0});await settle();s=(await room.stored()).state.game!;if(!m.recover&&i===1){expect(s.players.B!.statuses![0]).toMatchObject({id:status.id,nextCheck:2});expect(s.phase).toBe('turn-start');expect(s.seatOrder[s.turnSeat]).toBe('C');}else{expect(s.players.B!.statuses).toEqual([]);expect(s.phase).toBe('draw');expect(s.seatOrder[s.turnSeat]).toBe('B');}expect(s.players.B!.damage).toBe(4);}
},15000);
