import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {starBowScenarios,starBowCard as CARD,starBowMode} from './fixtures/star-bow-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(starBowScenarios)('%s physical chanted bow destruction and defense restrictions persist through every restart replay',async scenario=>{
 let countDice=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let n=0;n<array.length;n++)array[n]=countDice?2:n%2;return array;});const room=await openTestRoom(scenario),m=starBowMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`star-bow-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`star-bow-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('STAR_BOW_DO_LIMIT');}
 let initial=structuredClone(await state());const attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:m.targets.map(i=>['A','B','C','D'][i]!),dedicated:m.dedicated};
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'||m.suffix==='white-prohibited'||m.suffix.startsWith('unprepared')){await reject('A',attack);if(m.suffix==='white-prohibited')for(const dedicated of [false,true])await reject('A',{type:'CHANT',cardInstanceId:CARD,dedicated});return;}
 if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.incoming){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);const s=await state();expect(s.players.A!.damage).toBe(4);expect(s.players.A!.chants.some(c=>c.cardInstanceId===CARD)).toBe(true);expect(s.discard).not.toContain(CARD);return;}
 if(m.suffix.startsWith('chant-')){await reject('A',attack);await send('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await reject('A',attack);const visited=new Set<string>();for(let n=0;n<300;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')break;visited.add(id);await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('STAR_BOW_DO_TURN');}expect([...visited]).toEqual(['B','C','D']);initial=structuredClone(await state());}
 if(m.suffix==='same-faction')await reject('A',{...attack,targetIds:['C']});if(m.suffix.includes('blessed')){expect(initial.players.B!.open).toContain('a2-p01-r2c1');expect(gameStats(initial,'B').followerLevelBonus).toBe(1);}
 await send('A',attack);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand);expect((await state()).players.A!.chants).toEqual([]);const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(m.cancel){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);const s=await state();expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toEqual(initial.players.B!.followers);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const s=await state(),g=Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;expect(g.technique).toMatchObject({range:'far',useLevel:7,effectLevel:m.dedicated?8:7,damage:m.damage,attributes:['戦','弓','白','詠'],chant:true,counter:false,evadeProhibited:true,maaiRequired:2,noChecks:m.dedicated,target:m.dedicated?'all':'one',destroyFollowerAttributes:['黒','死']});expect(!!g.technique.destroyFollowersAtOrBelowEffectLevel).toBe(m.dedicated);expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual(m.targets.map(()=>[m.damage]));
 let damage=m.damage;if(m.maai||m.evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.evade)await reject('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else{const count=m.suffix.includes('one')?1:2;for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}if(count===2)damage=0;}}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower&&damage){if(!m.dedicated&&!m.black&&!m.dead)damage=m.water?0:m.metal?5:8;const survives=m.suffix==='water-blessed-ordinary';expect(final.players.B!.followers).toHaveLength(survives?1:0);expect(final.discard.filter(id=>id===m.follower)).toHaveLength(survives?0:1);}else expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);expect(final.players.B!.damage).toBe(damage);for(const i of [2,3])expect(final.players[['A','B','C','D'][i]!]!.damage).toBe(m.targets.includes(i)?13:0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);
},20000);
