import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {deathKnightPhysicalMode} from './fixtures/death-knight-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([["death-knight-setup", "plain"], ["death-knight-turn", "plain"], ["death-knight-equal", "plain"], ["death-knight-higher", "plain"], ["death-knight-morale-fail", "plain"], ["death-knight-waive", "plain"], ["death-knight-white", "plain"], ["death-knight-destroy", "plain"], ["death-knight-army", "plain"], ["death-knight-ded-hand", "plain"], ["death-knight-ded-field", "plain"], ["death-knight-army", "canceled"], ["death-knight-ded-hand", "canceled"], ["death-knight-ded-field", "canceled"], ["death-knight-army", "bundle"], ["death-knight-ded-hand", "bundle"], ["death-knight-ded-field", "bundle"]] as const)('%s mode=%s persists exact Death Knight revival and paid attack',async(scenario,mode)=>{
 const canceled=mode==='canceled';
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=deathKnightPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`death-knight-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;if(m.waive&&w.kind==='normal-defense'&&w.participants[w.cursor]==='A'){await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[m.card]});continue;}await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('DEATH_KNIGHT_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(!m.defense){await send('A',m.army?{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B','C','D']}:{type:'ATTACK',cardInstanceId:m.card,targetIds:['B','C','D'],dedicated:true});
 if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':m.card))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
 if(mode==='bundle'){await settle('normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c3']});let s=(await room.stored()).state.game!;expect(s.players.B!.hand).not.toContain('a2-p07-r1c2');expect(s.players.B!.hand).not.toContain('a2-p07-r1c3');expect(s.resolution).toEqual(expect.arrayContaining(['a2-p07-r1c2','a2-p07-r1c3']));const first=s.windows!.at(-1)!.id;while(s.windows!.at(-1)!.id===first){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}expect(s.windows!.at(-1)!.kind).toBe('reclaim');expect(s.resolution).toContain('a2-p07-r1c3');expect(s.discard).toContain('a2-p07-r1c2');}}

 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DEATH_KNIGHT_DO_TURN');}if(!m.white&&!m.destroy){const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});}else await send('B',{type:'ATTACK',cardInstanceId:m.white?'a2-p14-r1c3':'a2-p13-r1c2',targetIds:['A'],dedicated:true});}
 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&!m.white&&!m.destroy&&!m.fail&&m.attackLevel<=7;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual(!m.defense?[0,canceled||mode==='bundle'?0:8,canceled?0:8,canceled?0:8]:[m.white?10:m.destroy?0:m.fail||m.attackLevel>7?18:0,0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.white||m.destroy||m.waive||m.dedicated||canceled?0:1);expect(s.resolution).toEqual([]);if(mode==='bundle')for(const id of ['a2-p07-r1c2','a2-p07-r1c3'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
},15000);
