import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {kiSlashScenarios,kiSlashCard as CARD,kiSlashMode} from './fixtures/ki-slash-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(kiSlashScenarios)('%s physical spirit formula and saved damage boundary persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=kiSlashMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`ki-slash-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`ki-slash-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('KI_SLASH_DO_LIMIT');}
 const initial=structuredClone(await state()),source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;if(scenario==='ki-slash-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});expect((await state()).players.A!.hand).toContain(CARD);return;}if(scenario==='ki-slash-wrong-owner'){await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});return;}if(scenario==='ki-slash-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(scenario==='ki-slash-same-faction')await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['C'],dedicated:true});
 await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(CARD);
 if(scenario==='ki-slash-fate'){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 let fixed=6*(m.dedicated?2:1);
 if(m.freeze){await until(s=>s.windows?.at(-1)?.kind===(m.after?'attack-abilities':'damage'));const parent=(await state()).windows!.at(-1)!.id,target=m.target?'B':'A',raised=12+(initial.players[target]!.permanent!.spirit??0);expect(source(await state()).technique.damage).toBe(m.after?fixed:null);await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');const option=viewFor(await state(),'D').anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId===target)!;expect(option).toBeDefined();const hand=(await state()).players.D!.hand.length;await send('D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r1c1',targetEventId:option.targetEventId,targetId:target});await until(s=>s.windows?.at(-1)?.id===parent);expect(gameStats(await state(),target).spirit).toBe(raised);expect((await state()).players.D!.hand).toHaveLength(hand);expect((await state()).discard.filter(id=>id==='a2-p02-r1c1')).toHaveLength(1);if(!m.after&&!m.target)fixed=raised*(m.dedicated?2:1);}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!;expect(source(prepared).valuesPrepared).toBe(true);expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:m.dedicated?7:6,damage:fixed,attributes:['戦','剣','精','忍'],target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:true});expect(g.targets[0]!.hits[0]!.damage).toBe(fixed);

 if(scenario==='ki-slash-maai'||scenario==='ki-slash-evade'){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(await state(),'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:false,evadeProhibited:true});if(scenario==='ki-slash-maai'){await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});fixed=0;}else{await reject('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});expect((await state()).players.B!.hand).toContain('a2-p05-r3c1');}}
 await until(s=>!s.windows?.length);const final=await state();expect(final.players.B!.damage).toBe(fixed);for(const id of ['A','C','D'])expect(final.players[id]!.damage).toBe(0);expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='ki-slash-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.length??0).toBe(initial.rolls?.length??0);
},15000);
