import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {dragonKingScenarios,dragonKingCard as CARD,dragonKingMaai as MAAI,dragonKingMode} from './fixtures/dragon-king-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(dragonKingScenarios)('%s physical shared Maai target resistance and actual next turn persist through restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(scenario==='dragon-king-resistance-fail'?3:2);return array;});const room=await openTestRoom(scenario),m=dragonKingMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dragon-king-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dragon-king-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<750;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('DRAGON_KING_DO_LIMIT');}
 const initial=structuredClone(await state()),targets=m.targets.map(i=>initial.seatOrder[i]!),command:GameCommand={type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated};
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'){await reject('A',command);expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='same-faction')await reject('A',{...command,targetIds:['C']});await reject('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await send('A',command);const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);
 if(m.suffix==='fate'){const actionId=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(0);expect((await state()).players.B!.skipTurns??0).toBe(0);expect((await state()).rolls??[]).toHaveLength(0);expect((await state()).discard.filter(c=>c===CARD)).toHaveLength(1);return;}
 if(m.dedicated){await until(s=>s.rolls?.at(-1)?.purpose==='technique-value');const r=(await state()).rolls!.at(-1)!;expect(r).toMatchObject({formula:'d6',rollerId:'A',faces:[m.suffix==='resistance-fail'?4:3]});if(m.suffix==='reroll'){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:r.id});await until(s=>s.rolls!.find(x=>x.id===r.id)?.generation===1);}}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:8,effectLevel:8,damage:10,attributes:['戦','剣'],target:m.dedicated?'all':'one',chant:false,counter:false,noChecks:m.dedicated});if(m.dedicated)expect(g.technique.maaiRequired).toBe(m.suffix==='resistance-fail'?5:4);
 if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.suffix.startsWith('evade'))await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else if(m.suffix==='maai-short'){await reject('B',{type:'PLAY_MAAI',cardInstanceId:MAAI[0],additionalCardInstanceIds:MAAI.slice(1,3)});for(const id of MAAI.slice(0,3)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}}else await send('B',{type:'PLAY_MAAI',cardInstanceId:MAAI[0],...(m.dedicated?{additionalCardInstanceIds:MAAI.slice(1,4)}:{})});}
 await until(s=>!s.windows?.length);const final=await state(),avoided=m.suffix.startsWith('evade')||m.suffix==='maai-full'||m.suffix==='maai-ordinary',newRolls=(final.rolls??[]).slice(initial.rolls?.length??0);for(const id of ['B','C','D']){const hit=targets.includes(id)&&!(id==='B'&&avoided);expect(final.players[id]!.damage).toBe(hit?(id==='B'&&m.water?6:10)*(m.suffix==='resistance-fail'?3:1):0);expect(final.players[id]!.skipTurns??0).toBe(hit&&m.dedicated?1:0);}expect(newRolls.filter(r=>r.purpose==='technique-value')).toHaveLength(m.dedicated?1:0);for(const r of newRolls.filter(r=>r.purpose==='hit-resistance'))expect(r).toMatchObject({checkBase:'fixed',threshold:6,formula:'2d6',success:m.suffix!=='resistance-fail'});expect(newRolls.filter(r=>r.purpose==='hit-resistance').map(r=>r.rollerId)).toEqual(m.dedicated?targets.filter(id=>!(id==='B'&&avoided)):[]);expect(final.discard.filter(c=>c===CARD)).toHaveLength(1);
 if(['pair','all','resistance-fail'].includes(m.suffix)){if(final.phase==='withdrawal')await send('A',{type:'PASS_WITHDRAWAL'});await send('A',{type:'END_TURN',discardIds:(await state()).players.A!.hand.slice(gameStats(await state(),'A').handLimit)});await until(s=>!s.windows?.length);for(const id of targets){const before=await state();await send(id,{type:'START_TURN'});const after=await state();expect(after.phase).toBe('turn-start');expect(after.turnSeat).toBe((before.turnSeat+1)%4);expect(after.players[id]!.skipTurns).toBe(0);expect(after.players[id]!.hand).toEqual(before.players[id]!.hand);expect(after.deck).toEqual(before.deck);expect(after.rolls).toEqual(before.rolls);await reject(id,{type:'CHOOSE_DRAW',draw:true});}}
});
