import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {dwarfPhysicalMode} from './fixtures/dwarf-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['dwarf-setup', false], ['dwarf-turn', false], ['dwarf-equal', false], ['dwarf-higher', false], ['dwarf-fail', false], ['dwarf-waive', false], ['dwarf-army', false], ['dwarf-ded-hand', false], ['dwarf-ded-field', false], ['dwarf-grant-hand', false], ['dwarf-grant-field', false], ['dwarf-army', true], ['dwarf-ded-hand', true], ['dwarf-ded-field', true], ['dwarf-grant-field', true]] as const)('%s canceled=%s persists actual Dwarf defense or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=dwarfPhysicalMode(scenario),SK='a2-p21-r2c3';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dwarf-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('DWARF_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});for(const id of ['A','B','C','D'])await send(id,{type:'PASS_SETUP'});await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.defense){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DWARF_DO_TURN');}
 await send('B',{type:'ATTACK',cardInstanceId:m.bow?'a2-p24-r1c2':'a2-p20-r3c1',targetIds:['A'],dedicated:!m.bow});
 if(m.boost){await settle('effect-level');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r3c1')!.id;await send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}
 if(m.waive){await settle('normal-defense');await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[SK]});}}
 else{if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B']});else if(m.grant){const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B']}]});}else await send('A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B'],dedicated:true});
 if(canceled){let s=(await room.stored()).state.game!;const id=m.grant?Object.values(s.abilities!).find(a=>a.abilityId==='c2-p06-r1c2-ab04')!.id:Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':SK))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.grant?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}
 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&m.bow;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.defense?[m.fail?16:m.boost?4:0,0,0]:[0,canceled?0:18,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[SK]:[]);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(id=>id==='a2-p05-r2c2')).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
