import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {diaLifetimePhysicalMode} from './fixtures/dia-lifetime-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['soul-physical-ordinary','drain'],['soul-physical-ordinary','cancel'],['soul-physical-dedicated','drain'],['soul-physical-dedicated','death'],['soul-physical-dedicated','resist'],['soul-physical-dedicated','cancel'],['heart-physical-ordinary','recover'],['heart-physical-ordinary','death'],['heart-physical-ordinary','cancel'],['heart-physical-dedicated','recover'],['heart-physical-dedicated','death'],['heart-physical-dedicated','cancel']] as const)('%s actual %s persists target resistance and committed lifetime outcome',async(scenario,outcome)=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=diaLifetimePhysicalMode(scenario);let seq=0;const initial=(await room.stored()).state.game!,before=gameStats(initial,'B');expect(initial.players.A!.damage).toBe(5);
 async function send(actorId:string,command:GameCommand,die=1){face=die;const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dia-lifetime-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function finish(recovery=false){for(let n=0;n<400;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d)await send('A',{type:'CHOOSE_LIFETIME_EFFECT',choice:outcome==='death'&&d.targetId==='B'?'apply':'decline'});else await send(w.participants[w.cursor]!,{type:'PASS'},r?.stage==='before-roll'&&(r.purpose==='status-resistance'&&outcome!=='resist'||recovery&&r.purpose==='status-recovery'&&outcome==='death')?6:1);}throw Error('DIA_DO_FINISH');}
 async function nextOwn(){for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==m.card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DIA_DO_TURN');}throw Error('DIA_DO_LIMIT');}
 if(m.heart){await send('A',{type:'CHANT',cardInstanceId:m.card});await nextOwn();}else if(!m.dedicated){await send('A',{type:'APPROACH',targetId:'B',cardInstanceId:'a2-p24-r1c2'});await finish();expect((await room.stored()).state.game!.distances.A!.B).toBe('near');}await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});if(outcome==='cancel'){const s=(await room.stored()).state.game!,id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;for(const actor of ['A','B','C'])await send(actor,{type:'PASS'});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}await finish();let done=(await room.stored()).state.game!;expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.players.A!.chants).toEqual([]);
 if(outcome==='cancel'||outcome==='resist'){expect(done.players.A!.damage).toBe(5);expect(gameStats(done,'B')).toEqual(before);expect(done.players.B!.statuses??[]).toEqual([]);expect(done.players.C!.statuses??[]).toEqual([]);return;}
 if(!m.heart){expect(done.players.A!.damage).toBe(outcome==='death'?0:5);expect(done.players.B!.presence).toBe(outcome==='death'?'dead':'active');if(outcome!=='death')expect(gameStats(done,'B')).toMatchObject({warrior_level:before.warrior_level-1,magic_level:before.magic_level-1,spirit:before.spirit-1});else expect(done.events.some(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toBe(true);expect(done.players.C!.statuses??[]).toHaveLength(m.dedicated?1:0);return;}
 expect(done.players.B!.statuses![0]).toMatchObject({kind:'stopped',timing:'deadly-recovery',modifiers:[m.dedicated?-3:-1]});await send('A',{type:'PASS_WITHDRAWAL'});await send('A',{type:'END_TURN',discardIds:[]});await send('B',{type:'START_TURN'});await finish(true);done=(await room.stored()).state.game!;expect(done.rolls!.filter(r=>r.purpose==='status-recovery').at(-1)).toMatchObject({rollerId:'B',threshold:m.dedicated?3:5,success:outcome==='recover'});expect(done.players.B!.presence).toBe(outcome==='recover'?'active':'dead');expect(done.players.B!.statuses??[]).toHaveLength(outcome==='recover'?0:1);expect(done.players.B!.hand).toHaveLength(outcome==='recover'?5:0);expect(done.players.A!.damage).toBe(5);if(outcome==='recover')expect(done.phase).toBe('draw');expect(done.players.C!.statuses??[]).toHaveLength(m.dedicated?1:0);
},15000);
