import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {trainingPhysicalScenarios,trainingMode} from './fixtures/training-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(trainingPhysicalScenarios)('%s persists strict training growth cancellation dedicated use and threshold freeze across every save restart replay',async scenario=>{
 let face=scenario.endsWith('-equal')||scenario.endsWith('-reroll')||scenario.endsWith('-lan-ordinary')?3:4;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=trainingMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`training-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('TRAINING_DO_LIMIT');}
 const initial=await state(),base=gameStats(initial,'A')[m.stat],other=gameStats(initial,'A')[m.warrior?'magic_level':'warrior_level'];if(m.stopped){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(viewFor(initial,'A').turnCardOptions.some(o=>o.cardInstanceId===m.card)).toBe(false);return;}if(scenario.endsWith('-decline')){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(m.card);expect(gameStats(await state(),'A')[m.stat]).toBe(base);return;}
 await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card,mode:m.dedicated?'dedicated':'ordinary'});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(m.card);expect((await state()).players.A!.attachments).not.toContain(m.card);
 if(m.fate){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.card)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).discard).toContain(m.card);expect((await state()).players.A!.attachments).not.toContain(m.card);expect((await state()).rolls?.some(r=>r.purpose==='training')??false).toBe(false);expect(gameStats(await state(),'A')[m.stat]).toBe(base);return;}
 let success=m.dedicated;if(m.dedicated){await until(s=>!s.windows?.length);expect((await state()).rolls?.some(r=>r.purpose==='training')??false).toBe(false);}else{
  await until(s=>s.rolls?.at(-1)?.purpose==='training');const id=(await state()).rolls!.at(-1)!.id;expect((await state()).rolls!.at(-1)).toMatchObject({kind:'check',formula:'2d6',stage:'before-roll',comparison:'greater-than'});
  async function blood(){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='A');const o=viewFor(await state(),'A').anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId==='B')!;await send('A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r1c1',targetEventId:o.targetEventId,targetId:'B'});expect((await state()).players.A!.open).toContain('a2-p01-r1c3');expect(gameStats(await state(),'A')[m.stat]).toBe(base+1);await until(s=>s.windows?.at(-1)?.continuation.id===id);}
  if(scenario.endsWith('-before'))await blood();await until(s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll');expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({threshold:base+(scenario.endsWith('-before')?1:0),faces:[face,face],total:face*2});if(scenario.endsWith('-after'))await blood();
  if(scenario.endsWith('-reroll')||scenario.endsWith('-forced')){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');if(scenario.endsWith('-forced')){await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});await until(s=>s.windows?.at(-1)?.continuation.id===id&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});face=6;await until(s=>s.rolls!.find(r=>r.id===id)!.generation===1);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({total:12,forcedFailure:scenario.endsWith('-forced'),success:!scenario.endsWith('-forced')});}
  const finalRoll=(await state()).rolls!.find(r=>r.id===id)!;success=finalRoll.success!;expect(finalRoll.threshold).toBe(base+(scenario.endsWith('-before')?1:0));await until(s=>!s.windows?.length);
 }
 const final=await state();expect(final.players.A!.attachments.includes(m.card)).toBe(success);expect(final.discard.includes(m.card)).toBe(!success);expect(gameStats(final,'A')[m.stat]).toBe(base+(m.blood?1:0)+(success?1:0));expect(gameStats(final,'A')[m.warrior?'magic_level':'warrior_level']).toBe(other+(m.blood?1:0));expect(final.phase).toBe('hand-adjustment');expect(final.resolution).toEqual([]);for(const actor of final.seatOrder)expect(viewFor(final,actor).players.A!.attachments.includes(m.card)).toBe(success);
},15000);
