import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {nightmareScenarios,nightmareCard as CARD,nightmareMode} from './fixtures/nightmare-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(nightmareScenarios)('%s physical mental damage and stopped recovery persist through every restart replay',async scenario=>{
 let recoveryFace=6,face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=nightmareMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),r=stored.state.game!.rolls?.at(-1);face=stored.state.game!.windows?.at(-1)?.kind==='damage'||r?.purpose==='attack-damage'?3:r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)?(m.success?1:r.purpose==='status-recovery'?recoveryFace:6):1;const envelope={protocolVersion:1 as const,commandId:`nightmare-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),r=stored.state.game!.rolls?.at(-1);face=stored.state.game!.windows?.at(-1)?.kind==='damage'||r?.purpose==='attack-damage'?3:r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)?(m.success?1:r.purpose==='status-recovery'?recoveryFace:6):1;const envelope={protocolVersion:1 as const,commandId:`nightmare-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('NIGHTMARE_DO_LIMIT');}
 async function nextB(){for(let n=0;n<350;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='turn-start'){if(id==='B')return;await send(id,{type:'START_TURN'});}else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('NIGHTMARE_DO_PHASE');}throw Error('NIGHTMARE_DO_TURN');}
 const initial=structuredClone(await state()),attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:m.targets.map(i=>['A','B','C','D'][i]!),dedicated:m.dedicated},source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(['stopped','wrong-owner','silenced'].includes(m.suffix)){await reject('A',attack);return;}if(m.decline){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='same-faction')await reject('A',{...attack,targetIds:['C']});await reject('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await send('A',attack);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));
 if(m.cancel){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(0);expect((await state()).players.B!.statuses??[]).toEqual([]);return;}
 if(m.reroll){await until(s=>s.rolls?.at(-1)?.purpose==='attack-damage'&&s.rolls.at(-1)?.stage==='after-roll');const id=(await state()).rolls!.at(-1)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});await until(s=>s.rolls!.find(r=>r.id===id)?.generation===1);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({generation:1,total:12});}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const s=await state(),g=Object.values(s.groups!).find(g=>g.actionId===source(s).id)!,damage=m.dedicated?12:2;expect(g.technique).toMatchObject({school:'magic',range:'far',useLevel:6,effectLevel:6,damage,attributes:['魔','精','黒'],maaiProhibited:true,followerIgnore:true,chant:false,counter:false,noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(g.targets.map(t=>t.hits[0]!.damage)).toEqual(m.targets.map(()=>damage));
 if(m.maai||m.evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await reject('B',m.maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 await until(s=>!s.windows?.length);let final=await state();expect(final.players.B!.damage).toBe(damage);expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect((final.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(0);expect(final.players.B!.statuses??[]).toHaveLength(m.success?0:1);if(!m.success)expect(final.players.B!.statuses![0]).toMatchObject({kind:'stopped',modifiers:[m.asfelt?-2:-1],sourceActorId:'A',sourceCardInstanceId:CARD});expect(final.rolls!.find(r=>r.purpose==='status-resistance'&&r.rollerId==='B')).toMatchObject({modifier:m.asfelt?-2:-1,success:m.success});for(const i of [2,3]){expect(final.players[['A','B','C','D'][i]!]!.damage).toBe(m.targets.includes(i)?damage:0);expect(final.players[['A','B','C','D'][i]!]!.statuses??[]).toEqual([]);}expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);
 if(m.recovery){const id=final.players.B!.statuses![0]!.id;await nextB();await send('B',{type:'START_TURN'});await until(s=>s.rolls?.at(-1)?.purpose==='status-recovery'&&s.rolls.at(-1)?.stage==='before-roll');expect((await state()).rolls!.at(-1)!.modifier).toBe(m.asfelt?-2:-1);await until(s=>!s.windows?.length);expect((await state()).players.B!.statuses![0]!.id).toBe(id);recoveryFace=2;await nextB();await send('B',{type:'START_TURN'});await until(s=>s.rolls?.at(-1)?.purpose==='status-recovery'&&s.rolls.at(-1)?.stage==='before-roll');expect((await state()).rolls!.at(-1)!.modifier).toBe(m.asfelt?-2:-1);await until(s=>!s.windows?.length);final=await state();expect(final.players.B!.statuses??[]).toEqual([]);expect(final.phase).toBe('draw');expect(final.players.B!.damage).toBe(damage);}
},30000);
