import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {yotsurmMagicPhysicalMode} from './fixtures/yotsurm-magic-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['beast-magic-ordinary',false],['beast-magic-ordinary',true],['beast-magic-dedicated',false],['beast-magic-dedicated',true],['wolf-magic-ordinary',false],['wolf-magic-ordinary',true],['wolf-magic-dedicated',false],['wolf-magic-dedicated',true]] as const)('%s actual cancel=%s persists white destruction mental passage and caster formula',async(scenario,cancel)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=yotsurmMagicPhysicalMode(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`yotsurm-magic-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C','D']:['B'],dedicated:m.dedicated});if(cancel){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;await send(w.participants[w.cursor]!,{type:'PASS'});}const s=(await room.stored()).state.game!;expect(s.windows??[]).toEqual([]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);expect(s.players.B!.damage).toBe(cancel?0:m.damage);expect(s.players.B!.followers).toHaveLength(cancel?2:0);expect(s.players.C!.damage).toBe(m.dedicated&&!cancel?m.damage-1:0);expect(s.players.C!.followers.map(f=>f.cardInstanceId)).toEqual(m.dedicated&&!cancel?['a2-p22-r1c1']:['a2-p22-r1c1','a2-p18-r3c3']);expect(s.players.D!.damage).toBe(m.dedicated&&!cancel?m.damage:0);
},15000);
