import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {bloodFlowScenarios,bloodFlowCard as CARD,bloodFlowMode} from './fixtures/blood-flow-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(bloodFlowScenarios)('%s physical chant target resistance and extra ten persist through every restart replay',async scenario=>{
 let diceIndex=scenario==='blood-flow-resistance-fail'?2:0;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(diceIndex);return array;});const room=await openTestRoom(scenario),m=bloodFlowMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`blood-flow-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`blood-flow-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<750;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BLOOD_FLOW_DO_LIMIT');}
 const targets=m.targets.map(i=>['A','B','C','D'][i]!),command:GameCommand={type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated};
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'||m.suffix.startsWith('unprepared')){await reject('A',command);expect((await state()).players.A!.hand.includes(CARD)||(await state()).players.A!.chants.some(c=>c.cardInstanceId===CARD)).toBe(true);return;}if(m.suffix==='good'){for(const dedicated of [false,true]){await reject('A',{type:'CHANT',cardInstanceId:CARD,dedicated});await reject('A',{...command,dedicated});}expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.chants.some(c=>c.cardInstanceId===CARD)).toBe(true);return;}
 if(m.suffix.startsWith('chant-')){await reject('A',command);await send('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});expect((await state()).players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);await reject('A',command);for(let n=0;n<250;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)await until(s=>!s.windows?.length);else if(s.phase==='action'){if(id==='A')break;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('BLOOD_FLOW_DO_CYCLE');}}
 const initial=structuredClone(await state());expect(initial.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);if(m.suffix==='same-faction')await reject('A',{...command,targetIds:['C']});await send('A',command);const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand);expect((await state()).players.A!.chants).toEqual([]);expect((await state()).deck).toEqual(initial.deck);expect(source(await state()).fromChant).toBe(true);
 if(m.suffix==='fate'){const actionId=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(0);expect((await state()).rolls??[]).toHaveLength(0);expect((await state()).discard.filter(c=>c===CARD)).toHaveLength(1);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:8,effectLevel:8,damage:10,attributes:['戦','黒','詠'],target:m.dedicated?'all':'one',chant:true,counter:false,noChecks:m.dedicated,onHitResistance:{modifiers:[m.dedicated?-3:-2],failureDamage:10}});
 if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',m.suffix.startsWith('evade')?{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}:{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});}
 if(m.suffix.includes('force')||m.suffix==='reroll'){await until(s=>s.rolls?.at(-1)?.purpose==='status-resistance');const rollId=(await state()).rolls!.at(-1)!.id,forced=m.suffix.includes('force'),reroll=m.suffix.includes('reroll');if(forced){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:rollId});}else diceIndex=2;await until(s=>s.rolls!.find(r=>r.id===rollId)?.stage==='after-roll');expect((await state()).rolls!.find(r=>r.id===rollId)).toMatchObject({success:false,threshold:3});if(reroll){diceIndex=0;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:rollId});await until(s=>s.rolls!.find(r=>r.id===rollId)?.generation===1&&s.rolls!.find(r=>r.id===rollId)?.stage==='after-roll');expect((await state()).rolls!.find(r=>r.id===rollId)).toMatchObject({total:2,success:!forced,generation:1});}}
 await until(s=>!s.windows?.length);const final=await state(),avoided=m.suffix.startsWith('evade')||m.suffix.startsWith('maai')||m.suffix==='water-equal',newRolls=(final.rolls??[]).slice(initial.rolls?.length??0);for(const id of ['B','C','D']){const hit=targets.includes(id)&&!(id==='B'&&avoided),resistance=newRolls.find(r=>r.purpose==='status-resistance'&&r.rollerId===id);if(hit)expect(resistance).toMatchObject({formula:'2d6',modifier:m.dedicated?-3:-2,threshold:gameStats(initial,id).spirit-(m.dedicated?3:2)});expect(final.players[id]!.damage).toBe(hit?(id==='B'&&m.water?6:10)+(resistance!.success?0:10):0);expect(final.players[id]!.skipTurns??0).toBe(0);expect(final.players[id]!.statuses??[]).toEqual([]);}expect(newRolls.filter(r=>r.purpose==='status-resistance').map(r=>r.rollerId)).toEqual(targets.filter(id=>!(id==='B'&&avoided)));expect(final.discard.filter(c=>c===CARD)).toHaveLength(1);expect(final.players.A!.chants).toEqual([]);
});
