import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it('Alseil actual two crystal returns have independent persisted name budgets and no second Farseeing base claim',async()=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom('reclaim-crystals');let seq=0;const game=async()=>(await room.stored()).state.game!,RED='a2-p03-r1c3',FAR='a2-p04-r2c2';
 async function send(actorId:string,command:GameCommand,error=false){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`alias-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(error){expect(saved.state.game).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);}await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('ALIAS_DO_WINDOW');}
 async function nextOwn(){for(let n=0;n<60;n++){const s=await game(),id=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment'){await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==RED&&x!==FAR).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});await until(s=>!s.windows?.length);}else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ALIAS_DO_TURN');}throw Error('ALIAS_DO_TURN_LIMIT');}
 async function take(card:string){await until(s=>s.windows?.at(-1)?.kind==='reclaim'&&viewFor(s,'A').reclaim?.cardInstanceId===card);const d=viewFor(await game(),'A').reclaim!;for(const actor of ['B','C','D'])expect((await room.snapshotFor(actor)).game!.reclaim!.claims).toEqual([]);await send('A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});await until(s=>!s.windows?.length);}
 await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:RED});await send('A',{type:'PASS'});await send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:viewFor(await game(),'B').reactionTargetActionId!});await take(RED);expect((await game()).players.A!.attachments).not.toContain(RED);expect((await game()).players.A!.reclaimUsage).toEqual({'赤い水晶球':{baseSpent:true,extraSpentByAbility:[]}});
 for(const spent of [false,true]){await nextOwn();await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:FAR,targetId:'B',mode:'ordinary'});await until(s=>s.windows?.at(-1)?.kind==='private-inspection');const d=viewFor(await game(),'A').inspection!;for(const actor of ['B','C','D'])expect((await room.snapshotFor(actor)).game!.inspection).toBeNull();await send('A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});if(!spent){await take(FAR);expect((await game()).players.A!.hand).toEqual(expect.arrayContaining([RED,FAR]));expect((await game()).players.A!.reclaimUsage).toEqual({'赤い水晶球':{baseSpent:true,extraSpentByAbility:[]},'遠見の水晶球':{baseSpent:true,extraSpentByAbility:[]}});}else{await until(s=>s.windows?.at(-1)?.kind==='reclaim');const d=viewFor(await game(),'A').reclaim!;expect(d.claims).toEqual([]);await send('A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:`${d.decisionId}-A-base`},true);await until(s=>!s.windows?.length);expect((await game()).discard).toContain(FAR);}}
});
