import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(['silence-physical-resist','silence-physical-recover','silence-physical-cancel'] as const)('%s actual prior CHANT resistance Fate and recovery persist every command and replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`silence-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(resistance=false){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1),r=s.rolls?.at(-1);if(!w||resistance&&w.kind==='after-roll'&&r?.purpose==='status-resistance')return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SILENCE_DO_SETTLE');}
 async function toTurn(target:string,phase='action'){for(let n=0;n<180;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w){await settle();continue;}if(id===target&&s.phase===phase)return;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SILENCE_DO_TURN');}throw Error('SILENCE_DO_LIMIT');}
 await send('A',{type:'PASS_ACTION'});await toTurn('B');await send('B',{type:'CHANT',cardInstanceId:'a2-p14-r2c3'});await toTurn('A');await send('A',{type:'ATTACK',cardInstanceId:'a2-p18-r1c1',targetIds:['B'],dedicated:false});if(scenario==='silence-physical-recover')await settle(true);if(scenario!=='silence-physical-resist'){let s=(await room.stored()).state.game!;const targetActionId=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p18-r1c1')!.id,targetRollId=s.rolls?.at(-1)?.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',scenario==='silence-physical-cancel'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:targetRollId!});}await settle();let s=(await room.stored()).state.game!;expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.B!.chants).toContainEqual({cardInstanceId:'a2-p14-r2c3',revealed:false});expect(s.discard.filter(id=>id==='a2-p18-r1c1')).toHaveLength(1);expect((s.players.B!.statuses??[]).length).toBe(scenario==='silence-physical-recover'?1:0);if(scenario!=='silence-physical-recover')return;expect(s.players.B!.statuses![0]).toMatchObject({kind:'silenced',modifiers:[-2,-1],nextCheck:1});await toTurn('B','turn-start');await send('B',{type:'START_TURN'});s=(await room.stored()).state.game!;expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:-1,faces:[]});await settle();s=(await room.stored()).state.game!;expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.damage).toBe(0);await send('B',{type:'CHOOSE_DRAW',draw:false});await send('B',{type:'ATTACK',cardInstanceId:'a2-p14-r2c3',targetIds:['A'],dedicated:false});await settle();s=(await room.stored()).state.game!;expect(s.players.A!.damage).toBe(16);expect(s.players.B!.chants).toEqual([]);
},15000);
