import {reset} from 'cloudflare:test';
import {afterEach,expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {wishPhysicalScenarios,wishMode} from './fixtures/wish-physical-scenarios.js';
afterEach(async()=>{await reset();});
it.each(wishPhysicalScenarios)('%s saves one committed acquisition and private choices capacity disposal without duplicate effects across every restart replay',async scenario=>{
 const room=await openTestRoom(scenario),m=wishMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wish-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WISH_PHYSICAL_DO_LIMIT');}
 const initial=await state();if(m.mode==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(m.card);return;}await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card,mode:'wish'});const paid=[...(await state()).players.A!.hand];expect(paid).toEqual(initial.players.A!.hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);
 if(m.mode==='fate'){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.card)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).wishes?.length??0).toBe(0);expect((await state()).discard).toContain(m.card);return;}
 await until(s=>!!viewFor(s,'A').wish);const d=viewFor(await state(),'A').wish!;for(const actor of ['B','C','D'])expect(viewFor(await state(),actor).wish).toBeNull();if(m.mode==='otherworld'){expect(d.handOwners.some(o=>o.ownerId==='B')).toBe(false);expect(d.publicSources.some(o=>o.ownerId==='B')).toBe(false);}expect(d.publicSources.some(o=>o.ownerId==='B'&&o.zone==='followers')).toBe(false);const source:Extract<GameCommand,{type:'CHOOSE_WISH'}>['source']=m.hand?{kind:'hand',ownerId:m.mode==='own-hand'?'A':'B'}:m.deck?{kind:'deck',cardName:m.mode==='deck-dawn'?getAction(m.desired!)!.name:'回復の薬'}:{kind:'public',cardInstanceId:m.mode==='chant'?d.publicSources.find(o=>o.ownerId==='B'&&o.zone==='chants')!.cardInstanceId:m.desired!};if(m.mode==='chant')expect(source).not.toMatchObject({cardInstanceId:m.desired});await send('A',{type:'CHOOSE_WISH',decisionId:d.decisionId,source});const acquired=(await state()).wishes!.find(x=>x.id===d.decisionId)!.acquisition!,id=acquired.cardInstanceId;if(m.desired)expect(id).toBe(m.desired);
 if(m.capacity){const cap=viewFor(await state(),'B').wishCapacity!;expect(cap).toMatchObject({followerCount:m.mode==='blessing'?1:0,chantCount:m.mode==='haja'?1:0});expect((await state()).resolution).toContain(m.card);if(m.mode==='blessing')expect(cap.followerIds).not.toContain('a2-p21-r2c1');await send('B',{type:'CHOOSE_WISH_CAPACITY',decisionId:cap.decisionId,followerIds:cap.followerIds.slice(0,cap.followerCount),chantIds:cap.chantIds.slice(0,cap.chantCount)});}await until(s=>!s.windows?.length);const final=await state();expect(final.wishes!.find(x=>x.id===d.decisionId)!.stage).toBe('complete');expect(final.discard.filter(x=>x===m.card)).toHaveLength(1);expect(final.phase).toBe('hand-adjustment');expect(final.events.filter(e=>e.type==='WISH_ACQUIRED'&&e.audience==='public')).toHaveLength(1);
 if(getAction(id)!.category==='open'){expect(final.players.A!.open).toContain(id);expect(final.players.A!.hand).toEqual(paid);expect(final.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===id)).toHaveLength(1);}else expect(final.players.A!.hand).toEqual([...(m.mode==='own-hand'?paid.filter(x=>x!==id):paid),id]);if(m.mode==='hand')expect(final.players.B!.hand).toEqual(initial.players.B!.hand.filter(x=>x!==id));if(m.mode==='attachment'){expect(gameStats(final,'B').magic_level).toBe(gameStats(initial,'B').magic_level-1);expect(final.players.A!.attachments).not.toContain(id);}if(m.mode==='chant'){expect(final.players.B!.chants).toEqual([]);expect(final.players.A!.chants).toEqual([]);}if(m.mode==='dawn')expect(final.players.C!.presence).toBe('otherworld');if(m.mode==='fusen')expect(final.players.C!.presence).toBe('dead');if(m.mode==='deck-dawn')expect(final.players.C!.presence).toBe('active');if(m.mode==='mother')for(const key of ['faction','objective','currentObjective','protection'] as const)expect(final.players.B![key]).toEqual(initial.players.B![key]);if(m.mode==='haja'){expect(final.players.B!.chants).toHaveLength(1);expect(final.players.B!.hand).toHaveLength(6);await send('A',{type:'END_TURN',discardIds:[]});await until(s=>!s.windows?.length);await send('B',{type:'START_TURN'});await until(s=>!s.windows?.length);await send('B',{type:'CHOOSE_DRAW',draw:false});expect((await state()).players.B!.hand).toHaveLength(6);await send('B',{type:'PASS_ACTION'});await send('B',{type:'END_TURN',discardIds:[(await state()).players.B!.hand[0]!]});await until(s=>!s.windows?.length);expect((await state()).players.B!.hand).toHaveLength(5);}
 const isPublic=!m.hand&&!m.deck&&m.mode!=='chant'&&m.mode!=='own-follower';for(const actor of ['C','D'])expect(viewFor(final,actor).logs.filter(e=>e.type==='WISH_ACQUIRED').every(e=>isPublic?e.cardInstanceId===id:e.cardInstanceId===undefined)).toBe(true);if(!isPublic)expect(viewFor(final,'A').privateLogs.some(e=>e.type==='WISH_ACQUIRED'&&e.cardInstanceId===id)).toBe(true);
},15000);
