import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {asfeltSwordsScenarios,asfeltSwordMode,type AsfeltSword,type AsfeltSwordMode} from './fixtures/asfelt-swords-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(asfeltSwordsScenarios)('%s real printed mode follower level HP and defense restrictions persist through saved restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),[,key,...rest]=scenario.split('-'),card=key as AsfeltSword,mode=rest.join('-') as AsfeltSwordMode,m=asfeltSwordMode(card,mode);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`asfelt-swords-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function refuse(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`asfelt-reject-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){const s=await state();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('ASFELT_SWORDS_DO_LIMIT');}
 const initial=structuredClone(await state());if(mode==='wrong-owner'){await refuse('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true});return;}
 const targets=mode==='all'?['B','C','D']:m.dedicated?['B','C']:['B'];await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:targets,dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);
 if(mode==='fate'){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);for(const id of ['B','C'])expect((await state()).players[id]).toEqual(initial.players[id]);expect((await state()).discard.filter(id=>id===m.card)).toHaveLength(1);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const technique=Object.values((await state()).groups!).at(-1)!.technique,damage=m.dedicated?m.damage*2:m.damage;expect(technique).toMatchObject({useLevel:m.level,effectLevel:m.dedicated?m.level+2:m.level,damage,attributes:['戦','剣','風'],noChecks:m.dedicated,followerIgnore:false});expect(technique.followerHpIgnore??false).toBe(m.hpIgnore);expect(technique.evadeProhibited??false).toBe(m.evadeProhibited);
 if(mode==='maai'||mode==='evade'){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(mode==='maai'){await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(m.maai===2){await until(s=>s.windows?.at(-1)?.kind!=='reclaim');await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}}else if(card==='wind')await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else await refuse('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 await until(s=>!s.windows?.length);const final=await state(),evaded=mode==='maai'||mode==='evade'&&card==='wind';expect(final.players.B!.damage).toBe(evaded?0:m.guard&&!m.hpIgnore?damage-2:damage);if(evaded)expect(final.players.B!.followers).toEqual(initial.players.B!.followers);else if(m.guard)expect(final.players.B!.followers).toEqual([]);if(targets.includes('C')){expect(final.players.C!.damage).toBe(card==='rend'?16:0);if(card==='wind')expect(final.players.C!.followers[0]).toMatchObject({cardInstanceId:'a2-p23-r1c1',revealed:true});else expect(final.players.C!.followers).toEqual([]);}else expect(final.players.C!.damage).toBe(0);if(targets.includes('D'))expect(final.players.D!.damage).toBe(card==='wind'?0:card==='thunder'?9:16);else expect(final.players.D!.damage).toBe(0);expect(final.discard.filter(id=>id===m.card)).toHaveLength(1);expect(final.rolls?.length??0).toBe(targets.includes('C')&&card!=='rend'?1:0);expect(final.phase).toBe('withdrawal');
},15000);
