import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {hundredSlashScenarios,hundredSlashCard as CARD,hundredSlashMode} from './fixtures/hundred-slash-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(hundredSlashScenarios)('%s physical chanted shared hit count and per hit defenses persist through every restart replay',async scenario=>{
 let countDice=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let n=0;n<array.length;n++)array[n]=countDice?2:n%2;return array;});const room=await openTestRoom(scenario),m=hundredSlashMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`hundred-slash-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`hundred-slash-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('HUNDRED_SLASH_DO_LIMIT');}
 let initial=structuredClone(await state());const attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:m.targets.map(i=>['A','B','C','D'][i]!),dedicated:m.dedicated};
 if(m.suffix==='stopped'){await reject('A',attack);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix.startsWith('unprepared')){await reject('A',attack);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='wrong-owner'){await reject('A',attack);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.chants.map(c=>c.cardInstanceId)).toContain(CARD);return;}
 if(m.suffix.startsWith('chant-')){await reject('A',attack);await send('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await reject('A',attack);const visited=new Set<string>();for(let n=0;n<300;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')break;visited.add(id);await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('HUNDRED_SLASH_DO_TURN');}expect([...visited]).toEqual(['B','C','D']);initial=structuredClone(await state());}
 if(m.suffix==='same-faction')await reject('A',{...attack,targetIds:['C']});
 expect(initial.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);await send('A',attack);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand);expect((await state()).players.A!.chants).toEqual([]);const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(m.suffix.startsWith('fate-')){const after=m.suffix.endsWith('after'),id=source(await state()).id;if(after)await until(s=>s.windows?.at(-1)?.kind==='before-roll'&&s.rolls!.at(-1)!.purpose==='excess-level');await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',after?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:(await state()).rolls!.at(-1)!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);const s=await state();expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='attack-hit-count')).toHaveLength(0);if(after){expect(s.rolls!.find(r=>r.purpose==='activation')!.success).toBe(true);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',forcedFailure:true,success:false});}expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const ready=await state(),g=Object.values(ready.groups!).find(g=>g.actionId===source(ready).id)!;
 expect(g.technique).toMatchObject({range:'far',useLevel:7,effectLevel:7,damage:7,attributes:['戦','剣','詠'],chant:true,counter:false,hitCount:3,noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual(m.targets.map(()=>[7,7,7]));
 let bDamage=21;
 if(m.suffix.startsWith('maai')||['parry','evade'].includes(m.suffix)){const ids=m.suffix==='maai-three'?['a2-p06-r1c3','a2-p06-r2c1','a2-p06-r2c2']:[m.suffix==='parry'?'a2-p12-r1c3':m.suffix==='evade'?'a2-p05-r3c1':'a2-p06-r1c3'];for(const id of ids){await until(s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'B').activeWindow?.pendingActorId==='B');await send('B',m.suffix.startsWith('maai')?{type:'PLAY_MAAI',cardInstanceId:id}:{type:'PLAY_DEFENSE',cardInstanceId:id,dedicated:false});}bDamage=(3-ids.length)*7;}
 if(m.ability){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');const option=viewFor(await state(),'B').abilityOptions.find(o=>o.abilityId===m.ability)!;expect(option).toBeDefined();await send('B',{type:'USE_ABILITY',abilityId:m.ability,targetEventId:option.targetEventId});await until(s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'C').activeWindow?.pendingActorId==='C');const s=await state(),saved=s.groups![g.id]!;expect(saved.targets[0]!.hits.map(h=>h.defended)).toEqual([true,true,true]);expect(saved.targets[1]!.hits.map(h=>h.defended)).toEqual([false,false,false]);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);bDamage=0;}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower){bDamage=m.suffix==='water'?0:m.suffix==='metal'?6:15;expect(final.players.B!.followers).toHaveLength(0);expect(final.discard.filter(id=>id===m.follower)).toHaveLength(1);}
 expect(final.players.B!.damage).toBe(bDamage);expect(final.players.C!.damage).toBe(m.targets.includes(2)?21:0);expect(final.players.D!.damage).toBe(m.targets.includes(3)?21:0);expect(final.players.A!.damage).toBe(0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.rolls!.filter(r=>r.purpose==='attack-hit-count')).toHaveLength(1);if(m.mental){expect(final.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(final.players.A!.statuses??[]).toEqual([]);}
},20000);
