import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {getCharacter} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {conversionPhysicalScenarios,conversionMode} from './fixtures/conversion-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(conversionPhysicalScenarios)('%s persists actual public-target resistance and exact allegiance replacement through every save restart replay',async scenario=>{
 let face=scenario.endsWith('-success')||scenario.endsWith('-forced')?1:6;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=conversionMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`conversion-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('CONVERSION_DO_LIMIT');}
 const profile=(s:GameState)=>{const p=viewFor(s,'B').self;return {faction:p.faction,objective:p.objective,currentObjective:p.currentObjective,protection:p.protection,defeatCondition:p.defeatCondition};};const initial=await state(),before=profile(initial);
 if(scenario.endsWith('-decline')){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(m.card);expect(profile(await state())).toEqual(before);return;}
 if(scenario.endsWith('-hidden')){expect(viewFor(await state(),'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===m.card)).toBeUndefined();await send('B',{type:'REVEAL_CHARACTER'});await until(s=>!s.windows?.length);}expect(viewFor(await state(),'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===m.card)!.targetIds).toEqual(['B']);await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card,targetId:'B',mode:'ordinary'});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(m.card);
 if(scenario.endsWith('-fate')){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.card)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect(profile(await state())).toEqual(before);expect((await state()).rolls?.some(r=>r.purpose==='faction-change')??false).toBe(false);expect((await state()).discard).toContain(m.card);return;}
 await until(s=>s.rolls?.at(-1)?.purpose==='faction-change');const id=(await state()).rolls!.at(-1)!.id;expect((await state()).rolls!.at(-1)).toMatchObject({rollerId:'B',kind:'check',formula:'2d6',stage:'before-roll'});await until(s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll');const threshold=6-(m.dedicated?2:1)+(m.resist||scenario==='conversion-evil-same'?2:0);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({threshold,faces:[face,face],total:face*2});expect(profile(await state())).toEqual(before);
 if(scenario.endsWith('-reroll')||scenario.endsWith('-forced')){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');if(scenario.endsWith('-forced')){await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});await until(s=>s.windows?.at(-1)?.continuation.id===id&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});face=1;await until(s=>s.rolls!.find(r=>r.id===id)!.generation===1);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({total:2,forcedFailure:scenario.endsWith('-forced'),success:!scenario.endsWith('-forced')});}
 const success=(await state()).rolls!.find(r=>r.id===id)!.success!;await until(s=>!s.windows?.length);const final=await state();if(success||m.fixed)expect(profile(final)).toEqual(before);else expect(profile(final)).toEqual({faction:m.faction,objective:(m.good?'EVIL':'GOOD')+'の全滅',currentObjective:{kind:'extinction',enemyFactions:[m.good?'EVIL':'GOOD']},protection:{characterIds:[m.protector]},defeatCondition:getCharacter(m.protector)!.name+'の死亡'});if(m.dead&&!success){expect(initial.players.C!.presence).toBe('dead');expect(final.players.B!.presence).toBe('wandering');expect(final.players.B!.hand).toEqual([]);expect(final.players.B!.followers).toEqual([]);for(const id of [...initial.players.B!.hand,...initial.players.B!.followers.map(f=>f.cardInstanceId)])expect(final.deck).toContain(id);expect(final.outcome).toBeUndefined();}else for(const key of ['characterId','hand','open','attachments','followers','chants','damage','permanent'] as const)expect(final.players.B![key]).toEqual(initial.players.B![key]);expect(final.discard).toContain(m.card);expect(final.resolution).toEqual([]);expect(final.phase).toBe('hand-adjustment');
},15000);
