import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {attributeJewelsPhysicalScenarios,jewelMode} from './fixtures/attribute-jewels-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(attributeJewelsPhysicalScenarios)('%s persists installed attribute and current-faction morale bonuses across every save restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=jewelMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`jewel-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('JEWEL_DO_LIMIT');}
 const initial=await state();if(m.early){if(scenario.endsWith('-decline')){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(m.card);expect((await state()).players.A!.attachments).toEqual([]);return;}await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(m.card);expect((await state()).players.A!.attachments).toEqual([]);if(scenario.endsWith('-fate')){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.card)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}await until(s=>!s.windows?.length);expect((await state()).phase).toBe('hand-adjustment');expect((await state()).players.A!.attachments).toEqual(scenario.endsWith('-fate')?[]:[m.card]);expect((await state()).discard.includes(m.card)).toBe(scenario.endsWith('-fate'));expect(gameStats(await state(),'A').magic_level).toBe(3);return;}
 expect(initial.players.A!.attachments).toContain(m.card);for(const id of initial.seatOrder)expect(viewFor(initial,id).players.A!.attachments).toContain(m.card);
 if(m.morale){const bonus=m.follower==='a2-p21-r2c2'&&m.finalEvil!==m.crown?m.bonus:0;if(m.converted){expect(initial.players.A!.faction).toBe(m.finalEvil?'EVIL':'GOOD');expect(initial.events.some(e=>e.type==='FACTION_CHANGED'&&e.actorId==='A')).toBe(true);}if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.follower,targetIds:['B']});else await send('B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});await until(s=>s.rolls?.at(-1)?.purpose==='follower-morale');const r=(await state()).rolls!.at(-1)!;expect(gameStats(await state(),'A',{provenance:{kind:'roll',id:r.id}}).moraleBonus).toBe(bonus);await until(s=>s.rolls!.find(x=>x.id===r.id)!.stage==='after-roll');expect((await state()).rolls!.find(x=>x.id===r.id)).toMatchObject({threshold:6+r.modifier+bonus,faces:[3,3],success:true});}
 else if(m.training){await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r2c3'});await until(s=>s.rolls?.at(-1)?.purpose==='training');const id=(await state()).rolls!.at(-1)!.id;await until(s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll');expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({threshold:3,total:6,success:true});}
 else{await send('A',{type:'ATTACK',cardInstanceId:m.spell,targetIds:['B'],dedicated:false});const a=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.spell)!,bonus=scenario.endsWith('-other')?0:m.bonus;expect(gameStats(await state(),'A',{provenance:{kind:'action',id:a.id}}).magic_level).toBe(3+bonus);expect(a.checkSpecs?.filter(c=>c.purpose==='excess-level')??[]).toHaveLength(Math.max(0,a.technique.useLevel-3-bonus));expect(a.technique.effectLevel).toBe(m.spell==='a2-p15-r2c2'?6:4);}
 await until(s=>!s.windows?.length);expect((await state()).players.A!.attachments).toContain(m.card);expect((await state()).discard).not.toContain(m.card);expect((await state()).resolution).toEqual([]);expect(gameStats(await state(),'A').magic_level).toBe(m.training?4:3);
},15000);
