import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {blackBowScenarios,blackBowCard as CARD,blackBowMode} from './fixtures/black-bow-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(blackBowScenarios)('%s physical attack owner choice followers and target results persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=blackBowMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`black-bow-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BLACK_BOW_DO_LIMIT');}
 const initial=structuredClone(await state());if(scenario==='black-bow-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');expect(initial.players.A!.hand).toContain(CARD);return;}if(scenario==='black-bow-wrong-owner'){expect(initial.players.A!.characterId).not.toBe('c2-p03-r2c2');expect(initial.players.A!.hand).toContain(CARD);return;}if(scenario==='black-bow-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 const targets=scenario==='black-bow-all'?['B','C','D']:m.dedicated&&!['black-bow-subset','black-bow-near'].includes(scenario)?['B','C']:['B'];await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(CARD);
 if(scenario==='black-bow-fate'){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).players.C).toEqual(initial.players.C);expect((await state()).discard).toContain(CARD);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values((await state()).groups!).at(-1)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:5,effectLevel:5,damage:10,attributes:['戦','弓'],chant:false,noChecks:m.dedicated,followerIgnore:m.dedicated});
 if(scenario==='black-bow-maai'||scenario==='black-bow-evade'){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',scenario==='black-bow-maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 await until(s=>!s.windows?.length);const final=await state();for(const id of ['B','C','D'])expect(final.players[id]!.damage).toBe(id==='B'&&['black-bow-maai','black-bow-evade'].includes(scenario)?0:targets.includes(id)&&(!m.guard||m.dedicated)?10:0);if(m.dedicated){expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);}else if(m.guard)expect(final.players.B!.followers[0]!.revealed).toBe(true);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='black-bow-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.length??0).toBe(initial.rolls?.length??0);
},15000);
