import {reset} from 'cloudflare:test';
import {afterEach,expect,it} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {windMagicMode} from './fixtures/wind-magic-scenarios.js';
afterEach(async()=>{await reset();});
it.each(['wind-arrow-ordinary','wind-arrow-dedicated','magic-wind-ordinary','magic-wind-dedicated','lightning-run-ordinary','lightning-run-dedicated'] as const)('%s persists physical selected magic, allowed or refused Evade and remaining target damage once',async(scenario)=>{
 const room=await openTestRoom(scenario);let seq=0;const m=windMagicMode(scenario);
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wind-magic-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});let defended=false;for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;if(!defended&&w.kind==='normal-defense'){defended=true;if(m.noEvade){const before=await room.stored();expect(await room.command('B',{protocolVersion:1,commandId:'forbidden-evade',expectedRevision:before.revision,...activeWindowRef(s),command:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}})).toMatchObject({type:'error',code:'INVALID_ACTION'});expect(await room.stored()).toEqual(before);await send('B',{type:'PASS'});}else await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}else await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!;expect([done.players.B!.damage,done.players.C!.damage,done.players.D!.damage]).toEqual([m.noEvade?m.damage:0,m.dedicated?m.damage:0,0]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.players.B!.hand.includes('a2-p05-r3c1')).toBe(m.noEvade);expect(done.phase).toBe('withdrawal');
});
