import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {getCharacter} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {motherTruthPhysicalScenarios,motherCard,motherGood,motherEvil} from './fixtures/mother-truth-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(motherTruthPhysicalScenarios)('%s saves checkless allegiance attachment lifetime and later conversion death outcomes across every restart replay',async scenario=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`mother-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('MOTHER_DO_LIMIT');}
 async function start(id:string){await send(id,{type:'START_TURN'});await until(s=>!s.windows?.length);await send(id,{type:'CHOOSE_DRAW',draw:false});}
 async function end(id:string){if((await state()).phase==='action')await send(id,{type:'PASS_ACTION'});await send(id,{type:'END_TURN',discardIds:[]});await until(s=>!s.windows?.length);}
 async function nextA(){await end('A');for(const id of ['B','C','D']){await start(id);await end(id);}await start('A');}
 function profile(s:GameState,faction:'GOOD'|'EVIL'='GOOD'){const p=viewFor(s,'B').self,protector=faction==='GOOD'?'c2-p03-r1c2':'c2-p05-r2c2';expect({faction:p.faction,objective:p.objective,currentObjective:p.currentObjective,protection:p.protection,defeatCondition:p.defeatCondition}).toEqual({faction,objective:(faction==='GOOD'?'EVIL':'GOOD')+'の全滅',currentObjective:{kind:'extinction',enemyFactions:[faction==='GOOD'?'EVIL':'GOOD']},protection:{characterIds:[protector]},defeatCondition:getCharacter(protector)!.name+'の死亡'});}
 const initial=await state();if(['mother-wrong-target','mother-asfelt-user','mother-otherworld','mother-stopped'].includes(scenario)){expect(viewFor(initial,'A').turnChoiceCardOptions.some(o=>o.cardInstanceId===motherCard)).toBe(false);expect(initial.players.A!.hand).toContain(motherCard);return;}if(scenario==='mother-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(motherCard);return;}if(scenario==='mother-hidden'){expect(viewFor(initial,'A').turnChoiceCardOptions.some(o=>o.cardInstanceId===motherCard)).toBe(false);await send('B',{type:'REVEAL_CHARACTER'});await until(s=>!s.windows?.length);}const before=structuredClone((await state()).players.B!),rolls=(await state()).rolls?.length??0;await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:motherCard,targetId:'B',mode:'ordinary'});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==motherCard));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(motherCard);expect((await state()).players.B).toEqual(before);
 if(scenario==='mother-fate'){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===motherCard)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(before);expect((await state()).discard).toContain(motherCard);return;}
 await until(s=>!s.windows?.length);profile(await state());expect((await state()).rolls?.length??0).toBe(rolls);expect((await state()).players.B!.attachments).toEqual([...before.attachments,motherCard]);expect((await state()).discard).not.toContain(motherCard);expect((await state()).phase).toBe('hand-adjustment');for(const actor of ['A','B','C','D'])expect(viewFor(await state(),actor).players.B!.attachments).toContain(motherCard);
 if(['mother-stay-good','mother-evil-resist','mother-evil-convert','mother-return-good'].includes(scenario)){await nextA();const same=scenario==='mother-stay-good',resist=scenario==='mother-evil-resist';face=resist?1:6;await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:same?motherGood:motherEvil,targetId:'B',mode:'ordinary'});await until(s=>!s.windows?.length);expect((await state()).rolls!.at(-1)).toMatchObject({purpose:'faction-change',success:resist});profile(await state(),same||resist?'GOOD':'EVIL');expect((await state()).players.B!.attachments.includes(motherCard)).toBe(same||resist);expect((await state()).discard.filter(id=>id===motherCard)).toHaveLength(same||resist?0:1);if(scenario==='mother-return-good'){await nextA();await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:motherGood,targetId:'B',mode:'ordinary'});await until(s=>!s.windows?.length);profile(await state());expect((await state()).players.B!.attachments).not.toContain(motherCard);expect((await state()).discard.filter(id=>id===motherCard)).toHaveLength(1);}}
 if(scenario==='mother-death'||scenario==='mother-protector-death'){await end('A');for(const id of ['B','C']){await start(id);await end(id);}await start('D');const target=scenario==='mother-death'?'B':'C';await send('D',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:[target],dedicated:false});await until(s=>s.windows?.at(-1)?.kind==='death-gift');expect((await state()).players.B!.attachments).toContain(motherCard);await until(s=>!s.windows?.length);profile(await state());expect((await state()).players.B!.presence).toBe(target==='B'?'dead':'wandering');expect((await state()).players.B!.attachments.includes(motherCard)).toBe(target==='C');expect((await state()).discard.includes(motherCard)).toBe(target==='B');}
},15000);
