import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {borderWoodPhysicalMode} from './fixtures/border-wood-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['border-setup',false],['border-turn',false],['wood-setup',false],['wood-turn',false],['border-grant-hand',false],['border-grant-field',false],['border-army',false],['wood-army',false],['wood-mental',false],['wood-mental-destroy',false],['border-grant-hand',true],['border-grant-field',true],['border-army',true],['wood-army',true]] as const)('%s canceled=%s persists exact Border Guard or Wood defense and paid attack',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=borderWoodPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`border-wood-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BORDER_WOOD_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.grant||m.army){await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await settle();if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});else{const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:m.card,dedicated:false,targetIds:['B']}]});}if(canceled){let s=(await room.stored()).state.game!;const id=m.army?Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p05-r2c2')!.id:Object.values(s.abilities!).find(a=>a.abilityId==='c2-p06-r1c2-ab04')!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.army?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id});}}
 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('BORDER_WOOD_DO_TURN');}await send('B',{type:'ATTACK',cardInstanceId:m.mental?(m.destroy?'a2-p13-r1c2':'a2-p16-r2c1'):'a2-p24-r1c2',targetIds:['A'],dedicated:m.destroy});}
 await settle();const s=(await room.stored()).state.game!,alive=!m.grant&&!m.army&&(m.mental?!m.destroy:m.level>3);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.grant||m.army?[0,canceled?0:m.attackDamage,0]:[m.mental&&!m.destroy?5:0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);if(m.mental&&!m.destroy)expect(s.players.A!.followers[0]!.revealed).toBe(false);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
