import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {PLAGUE} from './fixtures/plague-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['plague-physical-ordinary',false],['plague-physical-dedicated',false],['plague-physical-ordinary',true],['plague-physical-dedicated',true],['plague-physical-immunity',false],['plague-physical-dedicated-reflection',false]] as const)('%s actual cancel=%s persists follower destruction dead exception and personal immunity',async(scenario,cancel)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),dedicated=scenario.includes('dedicated'),reflection=scenario.endsWith('-reflection');let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`plague-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:PLAGUE,targetIds:dedicated?['B','C','D']:['B'],dedicated});let s=(await room.stored()).state.game!;if(cancel){const id=Object.values(s.actions!).find(a=>a.cardInstanceId===PLAGUE)!.id;for(const actor of ['A','B','C'])await send(actor,{type:'PASS'});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}let reflected=false;for(let n=0;n<400;n++){s=(await room.stored()).state.game!;const w=s.windows?.at(-1);if(!w)break;if(reflection&&!reflected&&w.kind==='normal-defense'&&w.participants[w.cursor]==='B'){await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p17-r3c2',dedicated:false});reflected=true;}else await send(w.participants[w.cursor]!,{type:'PASS'});}s=(await room.stored()).state.game!;expect(s.windows??[]).toEqual([]);expect(s.players.A!.damage).toBe(0);expect(s.players.B!.damage).toBe(cancel||reflection||scenario==='plague-physical-immunity'?0:12);expect(s.players.B!.followers).toHaveLength(cancel||reflection?2:0);expect(s.players.C!.damage).toBe(dedicated&&!cancel?8:0);expect(s.players.C!.followers).toHaveLength(dedicated&&!cancel?0:1);expect(s.players.D!.damage).toBe(dedicated&&!cancel?12:0);expect(s.discard.filter(id=>id===PLAGUE)).toHaveLength(1);if(reflection){expect(reflected).toBe(true);expect(s.players.A!.followers).toEqual([]);}if(scenario==='plague-physical-immunity')expect(s.players.B!.revealed).toBe(false);
},15000);
