import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {darkSaintPhysicalMode} from './fixtures/dark-saint-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['saint-setup', false], ['saint-turn', false], ['saint-magic5', false], ['saint-magic6', false], ['saint-magic7', false], ['saint-ignore', false], ['saint-decline', false], ['saint-guard', false], ['saint-army', false], ['saint-grant-hand', false], ['saint-grant-field', false], ['saint-destroy', false], ['saint-army-spirit', false], ['saint-army', true], ['saint-grant-hand', true], ['saint-grant-field', true]] as const)('%s canceled=%s persists actual Dark Saint defense or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=darkSaintPhysicalMode(scenario),SK='a2-p21-r2c1';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dark-saint-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('DARK_SAINT_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});if(m.guard)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r3c3'});for(const id of ['A','B','C','D']){if(id==='B'&&m.spirit)await send('B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});await send(id,{type:'PASS_SETUP'});}await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(!m.attack){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DARK_SAINT_DO_TURN');}const card=m.destroy?'a2-p13-r1c2':m.magic?m.magicLevel===5?'a2-p17-r2c2':'a2-p18-r1c3':'a2-p24-r1c2';await send('B',{type:'ATTACK',cardInstanceId:card,targetIds:['A'],dedicated:m.destroy});if(m.magic&&m.magicLevel===7){await settle('effect-level');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id});}if(m.ignore||m.decline){await settle('follower-entry-abilities');let s=(await room.stored()).state.game!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}expect(viewFor(s,'B').legalChoices).toContain('CHOOSE_DARK_SAINT_IGNORE');await send('B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:m.ignore});}}
 else{if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B']});else{const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B']}]});}if(canceled){let s=(await room.stored()).state.game!;const id=m.grant?Object.values(s.abilities!).find(a=>a.abilityId==='c2-p06-r1c2-ab04')!.id:Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p05-r2c2')!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.grant?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}

 await settle();const s=(await room.stored()).state.game!,alive=!m.attack&&!m.destroy&&(!m.magic||m.magicLevel===5);expect([s.players.A!.damage,s.players.B!.damage]).toEqual(m.attack?[0,canceled?0:6]:[m.ignore&&!m.guard?4:m.magic&&m.magicLevel===7?6:0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?m.guard?[SK,'a2-p22-r3c3']:[SK]:[]);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);expect(s.players.A!.hand).not.toContain(SK);if(m.ignore&&!m.guard)expect(s.players.A!.followers[0]!.revealed).toBe(false);if(m.ignore||m.decline)expect(s.players.B!.revealed).toBe(m.ignore);if(m.spirit)expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.resolution).toEqual([]);
},15000);
