import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {dispelPhysicalScenarios,dispelMode} from './fixtures/dispel-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(dispelPhysicalScenarios)('%s persists actual pre-attack golem destruction and committed attack through restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),card='a2-p02-r3c1',m=dispelMode(scenario),target=m.target===2?'C':'B',other=target==='B'?'C':'B';let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`dispel-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;await step();}throw Error('DISPEL_DO_LIMIT');}
 if(m.defense){await send('B',{type:'ATTACK',cardInstanceId:m.attack,targetIds:['A'],dedicated:false});await until(s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(await state(),'A').anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);await until(s=>!s.windows?.length);expect((await state()).players.A!.hand).toContain(card);expect((await state()).players.A!.damage).toBe(4);return;}
 const original=structuredClone((await state()).players[target]!),untouched=structuredClone((await state()).players[other]!.followers),hand=(await state()).players.A!.hand.length,deck=[...(await state()).deck],destroyed=original.followers.filter(f=>['a2-p19-r2c3','a2-p20-r2c3','a2-p22-r1c1'].includes(f.cardInstanceId)),remaining=original.followers.filter(f=>!destroyed.includes(f));await send('A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:m.multi?['B','C']:['B'],dedicated:m.multi||m.cost,...(m.cost?{advanceCardInstanceIds:['a2-p24-r1c3']}:{}),...(scenario==='dispel-decline'?{}:{dispel:{cardInstanceId:card,targetId:target}})});expect((await state()).players.A!.hand).toHaveLength(hand-(scenario==='dispel-decline'?1:m.multi?1:m.cost?3:2));expect((await state()).deck).toEqual(deck);const parent=Object.values((await state()).actions!).find(a=>a.kind==='attack')!;
 if(scenario==='dispel-decline'){expect((await state()).players.A!.hand).toContain(card);expect((await state()).players[target]!.followers).toEqual(original.followers);await until(s=>!s.windows?.length);return;}
 const child=Object.values((await state()).actions!).find(a=>a.cardInstanceId===card)!;expect(parent.preAttackPending).toBe(child.id);expect(Object.keys((await state()).groups??{})).toHaveLength(0);expect(viewFor(await state(),'B').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2')).toBe(false);
 if(scenario==='dispel-fate'){await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='D';});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});}await until(s=>!s.actions?.[child.id]);expect((await state()).players[target]!.followers).toEqual(scenario==='dispel-fate'?original.followers:remaining);expect((await state()).players[other]!.followers).toEqual(untouched);expect((await state()).players[target]!.hand).toEqual(original.hand);for(const id of ['A','B','C','D']){const v=viewFor(await state(),id);expect(v.logs.filter(e=>e.type==='FOLLOWER_DESTROYED').map(e=>e.cardInstanceId)).toEqual(scenario==='dispel-fate'?[]:destroyed.map(f=>f.cardInstanceId));if(id!==target)for(const f of remaining)expect(JSON.stringify(v)).not.toContain(f.cardInstanceId);}
 if(scenario==='dispel-parent-cancel'){await until(s=>viewFor(s,'B').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2'&&o.targetEventId===parent.id));await send('B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r2c2',targetEventId:parent.id});}else if(scenario==='dispel-attack-fate'){await until(s=>s.windows?.at(-1)?.kind==='declaration'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.id});}else{await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(Object.values((await state()).groups!)).toHaveLength(1);}
 await until(s=>!s.windows?.length);const final=await state();expect(final.phase).toBe('withdrawal');expect(final.discard.filter(id=>id===card)).toHaveLength(1);expect(final.resolution).toEqual([]);if(scenario!=='dispel-fate')for(const f of destroyed)expect(final.discard).toContain(f.cardInstanceId);if(m.cost)expect(final.discard).toContain('a2-p24-r1c3');
},15000);
