import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {griffinPhysicalMode} from './fixtures/griffin-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['griffin-setup',false],['griffin-turn',false],['griffin-morale-pass',false],['griffin-morale-fail',false],['griffin-morale-waive',false],['griffin-army',false],['griffin-ded-hand',false],['griffin-ded-field',false],['griffin-ded-maai',false],['griffin-grant-hand',false],['griffin-grant-field',false],['griffin-army',true],['griffin-ded-hand',true],['griffin-ded-field',true],['griffin-grant-field',true]] as const)('%s canceled=%s persists exact Griffin defense and paid attack',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=griffinPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`griffin-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('GRIFFIN_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of ['A','B','C','D']){if(id==='B'&&m.maai)await send('B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p20-r1c2'});await send(id,{type:'PASS_SETUP'});}await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.dedicated||m.army||m.grant){if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});else if(m.grant){const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p05-r1c2-ab02')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:m.card,dedicated:false,targetIds:['B']}]});}else await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B','C'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const id=m.grant?Object.values(s.abilities!).find(a=>a.abilityId==='c2-p05-r1c2-ab02')!.id:Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':m.card))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',m.grant?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}if(m.maai){await settle('normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});}}
 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('GRIFFIN_DO_TURN');}if(m.morale){await send('B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'});await settle();const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});if(m.waive){await settle('normal-defense');await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[m.card]});}}else await send('B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
 await settle();const s=(await room.stored()).state.game!,alive=!m.dedicated&&!m.army&&!m.grant&&!m.morale;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.dedicated||m.army||m.grant?[0,canceled?0:m.maai?3:16,!canceled&&m.dedicated?16:0]:[m.morale?m.fail?18:9:0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);if(m.morale)expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.waive?0:1);if(m.maai)expect(s.discard.filter(x=>x==='a2-p20-r1c2')).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
