import {readySetupAsync} from './fixtures/scenario-tools.js';
import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {hajaPhysicalScenarios} from './fixtures/haja-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(hajaPhysicalScenarios)('%s persists actual six-card two-chant lifecycle and ownership loss with idempotent replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),haja='a2-p01-r2c2',ice='a2-p13-r1c1',rift='a2-p14-r2c2';let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`haja-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('HAJA_DO_PHASE');}
 async function next(id:string,phase='action'){for(let n=0;n<250;n++){const s=await state();if(!s.windows?.length&&s.seatOrder[s.turnSeat]===id&&s.phase===phase)return;await step();}throw Error('HAJA_DO_TURN');}
 async function settle(stop?:string){for(let n=0;n<200;n++){const s=await state(),w=s.windows?.at(-1);if(!w||w.kind===stop)return;await step();}throw Error('HAJA_DO_WINDOW');}
 const base=gameStats(await state(),'A');await readySetupAsync(async()=>(await room.stored()).state.game!,id=>send(id,{type:'PASS_SETUP'}));await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:scenario!=='haja-book'});if(scenario==='haja-book'){await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r1c1'});await settle();}expect(gameStats(await state(),'A')).toEqual({...base,handLimit:6,chantLimit:2});expect((await state()).players.A!.hand).toHaveLength(scenario==='haja-book'?5:6);
 if(scenario==='haja-draw'||scenario==='haja-book'){await send('A',{type:'PASS_ACTION'});await next('B');expect((await state()).players.A!.hand).toHaveLength(6);if(scenario==='haja-draw'){await next('A','draw');await send('A',{type:'CHOOSE_DRAW',draw:true});expect((await state()).players.A!.hand).toHaveLength(7);await send('A',{type:'PASS_ACTION'});await step();expect((await state()).players.A!.hand).toHaveLength(6);}}
 else{
  await send('A',{type:'CHANT',cardInstanceId:ice});await next('A');await send('A',{type:'CHANT',cardInstanceId:rift});await next('B');expect((await state()).players.A!.hand).toHaveLength(6);expect((await state()).players.A!.chants.map(c=>c.cardInstanceId)).toEqual([ice,rift]);
  if(scenario==='haja-chants'){await next('A');await send('A',{type:'ATTACK',cardInstanceId:ice,targetIds:['B'],dedicated:false});await settle();expect((await state()).players.B!.damage).toBe(7);await next('A');await send('A',{type:'CHANT',cardInstanceId:'a2-p13-r2c3'});expect((await state()).players.A!.chants.map(c=>c.cardInstanceId)).toEqual([rift,'a2-p13-r2c3']);}
  else if(scenario==='haja-death'){await send('B',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['A'],dedicated:false});await settle();const s=await state();expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.chants).toEqual([]);expect(gameStats(s,'A')).toEqual(base);for(const id of [haja,ice,rift])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
  else{
   const hand=[...(await state()).players.A!.hand];await send('B',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c2',mode:'wish'});await settle('wish');await send('B',{type:'CHOOSE_WISH',decisionId:viewFor(await state(),'B').wish!.decisionId,source:{kind:'public',cardInstanceId:haja}});const d=viewFor(await state(),'A').wishCapacity!;expect(d).toMatchObject({followerCount:0,chantCount:1,chantIds:[ice,rift]});expect(gameStats(await state(),'A')).toEqual(base);for(const id of ['B','C','D'])expect((await room.snapshotFor(id)).game!.wishCapacity).toBeNull();await send('A',{type:'CHOOSE_WISH_CAPACITY',decisionId:d.decisionId,followerIds:[],chantIds:[ice]});await settle();expect((await state()).players.A!.hand).toEqual(hand);await next('A');expect((await state()).players.A!.hand).toEqual(hand);
   if(scenario==='haja-return'){await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c3',mode:'wish'});await settle('wish');await send('A',{type:'CHOOSE_WISH',decisionId:viewFor(await state(),'A').wish!.decisionId,source:{kind:'public',cardInstanceId:haja}});await settle();expect(gameStats(await state(),'A')).toEqual({...base,handLimit:6,chantLimit:2});expect((await state()).players.A!.open).toContain(haja);}
   else{await send('A',{type:'PASS_ACTION'});await send('A',{type:'END_TURN',discardIds:[hand[0]!]});await settle();expect((await state()).players.A!.hand).toHaveLength(5);}
   expect((await state()).players.A!.chants.map(c=>c.cardInstanceId)).toEqual([rift]);expect((await state()).discard.filter(id=>id===ice)).toHaveLength(1);
  }
 }
 const s=await state();expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===haja)).toHaveLength(1);expect(s.resolution).toEqual([]);
},15000);
