import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {SCYTHE} from './fixtures/scythe-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['scythe-physical-ordinary','decline'],['scythe-physical-ordinary','cancel'],['scythe-physical-dedicated','decline'],['scythe-physical-dedicated','death'],['scythe-physical-dedicated','resist'],['scythe-physical-dedicated','cancel']] as const)('%s actual %s persists chant optional spirit check and complete death batch',async(scenario,outcome)=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),dedicated=scenario.includes('dedicated');let seq=0;
 async function send(actorId:string,command:GameCommand,die=1){face=die;const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`scythe-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function nextOwn(){for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==SCYTHE).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SCYTHE_DO_TURN');}throw Error('SCYTHE_DO_LIMIT');}
 await send('A',{type:'CHANT',cardInstanceId:SCYTHE});await nextOwn();await send('A',{type:'ATTACK',cardInstanceId:SCYTHE,targetIds:dedicated?['B','C']:['B'],dedicated});if(outcome==='cancel'){const s=(await room.stored()).state.game!,id=Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!.id;for(const actor of ['A','B','C'])await send(actor,{type:'PASS'});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
 const choices:string[]=[];for(let n=0;n<400;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d){expect(s.players.B!.presence).toBe('active');expect(s.players.C!.presence).toBe('active');expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(viewFor(s,'B').lifetimeDecision).toBeNull();choices.push(d.targetId);await send('A',{type:'CHOOSE_LIFETIME_EFFECT',choice:outcome==='death'||outcome==='resist'?'apply':'decline'});}else await send(w.participants[w.cursor]!,{type:'PASS'},r?.stage==='before-roll'&&r.purpose==='status-resistance'&&outcome==='death'?6:1);}
 const done=(await room.stored()).state.game!;expect(done.windows??[]).toEqual([]);expect(done.discard.filter(id=>id===SCYTHE)).toHaveLength(1);expect(done.players.A!.chants).toEqual([]);expect(choices).toEqual(dedicated&&outcome!=='cancel'?['B','C']:[]);expect(done.players.B!.presence).toBe(outcome==='death'?'dead':'active');expect(done.players.C!.presence).toBe(outcome==='death'?'dead':'active');if(outcome!=='death')expect([done.players.B!.damage,done.players.C!.damage]).toEqual(outcome==='cancel'?[0,0]:[3,dedicated?7:0]);expect(done.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(outcome==='death'?['B','C']:[]);expect((done.rolls??[]).filter(r=>r.purpose==='status-resistance').map(r=>[r.rollerId,r.threshold,r.success])).toEqual(outcome==='death'||outcome==='resist'?['B','C'].map(id=>[id,4,outcome==='resist']):[]);expect(done.players.D!.presence).toBe('active');expect(done.outcome).toBeUndefined();
},15000);
