import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {royalKnightsPhysicalMode} from './fixtures/royal-knights-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['royal-knights-setup', false], ['royal-knights-turn', false], ['royal-knights-equal', false], ['royal-knights-higher', false], ['royal-knights-fail', false], ['royal-knights-waive', false], ['royal-knights-counterban', false], ['royal-knights-ignore', false], ['royal-knights-army', false], ['royal-knights-ded-hand', false], ['royal-knights-ded-field', false], ['royal-knights-grant-hand', false], ['royal-knights-grant-field', false], ['royal-knights-ded-hand', true], ['royal-knights-ded-field', true], ['royal-knights-army', true]] as const)('%s canceled=%s persists actual Royal Knights revival or paid attack with every saved replay',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=royalKnightsPhysicalMode(scenario),SK='a2-p21-r1c2';let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`royal-knights-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||w.kind===stop)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('ROYAL_KNIGHTS_DO_SETTLE');}
 if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});for(const id of ['A','B','C','D'])await send(id,{type:'PASS_SETUP'});await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.defense){if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ROYAL_KNIGHTS_DO_TURN');}if(m.counterban||m.ignore)await send('B',{type:'ATTACK',cardInstanceId:m.counterban?'a2-p19-r2c1':'a2-p21-r1c1',targetIds:['A','C'],dedicated:true});else{await send('B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'});await settle();const s=(await room.stored()).state.game!,o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']}]});}if(m.waive){await settle('normal-defense');await send('A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[SK]});}}
 else{await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await settle();if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SK,targetIds:['B']});else if(m.grant){const s=(await room.stored()).state.game!,o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;await send('A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B']}]});}else await send('A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':SK))!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id});}}

 await settle();const s=(await room.stored()).state.game!,alive=m.defense&&!m.fail&&m.attackLevel<5;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.defense?m.counterban?[0,2,2]:m.ignore?[5,0,5]:m.fail||m.attackLevel>5?[18,0,0]:m.attackLevel===5?[0,0,0]:[0,18,0]:[0,canceled?0:5,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?[SK]:[]);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.defense?m.waive||m.ignore?0:1:m.army&&!canceled?1:0);if(m.ignore)expect(s.players.A!.followers[0]!.revealed).toBe(false);expect(s.resolution).toEqual([]);
},15000);
