import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {blackWingScenarios,blackWingCard as CARD,blackWingMode} from './fixtures/black-wing-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(blackWingScenarios)('%s physical attack owner choice followers and target results persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=blackWingMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`black-wing-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BLACK_WING_DO_LIMIT');}
 const initial=structuredClone(await state());if(scenario==='black-wing-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');expect(initial.players.A!.hand).toContain(CARD);return;}if(scenario==='black-wing-wrong-owner'){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:'black-wing-invalid-owner',expectedRevision:stored.revision,command:{type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:true}},error=await room.command('A',envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(initial);await room.restart();expect(await room.command('A',envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(initial);return;}if(scenario==='black-wing-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 const targets=['B'];await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:targets,dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(CARD);
 if(scenario==='black-wing-fate'){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).players.C).toEqual(initial.players.C);expect((await state()).discard).toContain(CARD);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values((await state()).groups!).at(-1)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:5,effectLevel:m.dedicated?6:5,damage:m.dedicated?10:7,attributes:['戦','剣'],maaiRequired:2,target:'one',chant:false,noChecks:m.dedicated,followerIgnore:m.dedicated});
 const maai=scenario.includes('maai-'),two=scenario.endsWith('-two'),evade=scenario==='black-wing-evade';
 if(maai||evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});if(maai){await until(s=>s.windows?.at(-1)?.kind!=='reclaim');expect(viewFor(await state(),'B').maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});if(two)await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}}

 await until(s=>!s.windows?.length);const final=await state();for(const id of ['B','C','D'])expect(final.players[id]!.damage).toBe(id==='B'&&(two||evade)?0:targets.includes(id)&&(!m.guard||m.dedicated)?m.dedicated?10:7:0);if(m.dedicated){expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);}else if(m.guard)expect(final.players.B!.followers[0]!.revealed).toBe(true);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='black-wing-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.length??0).toBe(initial.rolls?.length??0);
},15000);
