import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {shadowCardScenarios,shadowCard as CARD,shadowChild as CHILD,shadowCardMode} from './fixtures/shadow-card-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(shadowCardScenarios)('%s physical defense source and one granted attack persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=shadowCardMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`shadow-card-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(command:GameCommand){const stored=await room.stored(),before=structuredClone(stored.state.game),envelope={protocolVersion:1 as const,commandId:`shadow-card-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command('B',envelope);expect(error).toMatchObject({type:'error',code:'INVALID_ACTION'});expect((await room.stored()).state.game).toEqual(before);await room.restart();expect(await room.command('B',envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(before);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<800;n++){const s=await state();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SHADOW_CARD_DO_LIMIT');}
 const initial=structuredClone(await state());if(['shadow-card-wrong-owner','shadow-card-prohibited','shadow-card-stopped'].includes(scenario)){await reject({type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true});if(scenario!=='shadow-card-wrong-owner')await reject({type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});expect((await state()).players.B!.hand).toContain(CARD);return;}
 if(scenario==='shadow-card-decline'){await until(s=>!s.windows?.length);expect((await state()).players.B!.hand).toContain(CARD);expect((await state()).players.B!.damage).toBe(4);return;}
 await send('B',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:m.dedicated});expect((await state()).players.B!.hand).toEqual(initial.players.B!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect(Object.values((await state()).actions!).find(a=>a.cardInstanceId===CARD)!.technique).toMatchObject({school:'warrior',range:'none',useLevel:5,effectLevel:5,damage:null,attributes:['戦','忍','反'],counter:true,noChecks:false,chant:false,defense:'fixed-negate'});
 async function fate(){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
 if(scenario==='shadow-card-defense-fate'){await fate();await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(4);expect((await state()).players.B!.hand).toContain(CHILD);expect((await state()).discard).toContain(CARD);return;}
 let usedChild=false;const selected=scenario==='shadow-card-child-unchanted'?CHILD:m.child;
 if(m.dedicated&&!m.shin){await until(s=>s.windows?.at(-1)?.kind==='ability-attack');expect(viewFor(await state(),'B').additionalAttack).toMatchObject({source:'card',sourceCardInstanceId:CARD,actorId:'B',targetId:'A'});expect(viewFor(await state(),'A').additionalAttackOptions).toEqual([]);if(scenario!=='shadow-card-grant-decline'){
   await reject({type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'A'});await reject({type:'ATTACK',cardInstanceId:selected,targetIds:['C'],dedicated:false});if(scenario==='shadow-card-child-unchanted')await reject({type:'ATTACK',cardInstanceId:'a2-p13-r1c1',targetIds:['A'],dedicated:false});
   await send('B',{type:'ATTACK',cardInstanceId:selected,targetIds:['A'],dedicated:scenario==='shadow-card-near'});usedChild=true;if(scenario==='shadow-card-child-fate')await fate();
  }}
 await until(s=>!s.windows?.length);const final=await state(),expectedB=m.multi?m.shin?21:14:m.shin?m.damage:0,expectedA=usedChild&&scenario!=='shadow-card-child-fate'&&scenario!=='shadow-card-child-follower'?scenario==='shadow-card-near'?5:7:0;expect(final.players.B!.damage).toBe(expectedB);expect(final.players.A!.damage).toBe(expectedA);expect(final.players.C!.damage).toBe(m.multi&&m.shin?21:0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.discard.filter(id=>id===m.incoming)).toHaveLength(1);if(usedChild)expect(final.discard.filter(id=>id===selected)).toHaveLength(1);else expect(final.players.B!.hand).toContain(CHILD);expect(final.distances).toEqual(initial.distances);expect(final.phase).toBe('withdrawal');expect(final.turnSeat).toBe(initial.turnSeat);expect(viewFor(final,'B').additionalAttack).toBeNull();
 if(!m.dedicated&&!m.shin)expect(final.rolls!.filter(r=>r.purpose==='technique-check')).toEqual([expect.objectContaining({rollerId:'A',modifier:-1,threshold:5,total:6,success:false})]);if(scenario.includes('-low'))expect(final.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(usedChild?2:1);if(scenario==='shadow-card-child-chant')expect(final.players.B!.chants).toEqual([]);if(scenario==='shadow-card-child-follower')expect(final.players.A!.followers[0]!.revealed).toBe(true);
},15000);
