import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['barrier-physical-1','a2-p18-r2c2'],['barrier-physical-2','a2-p18-r2c3']] as const)('%s persists failure of physical %s then success of the distinct copy',async(scenario,card)=>{
 let face=6;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario);let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,error=false){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`barrier-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);if(error){expect(saved.revision).toBe(before.revision);expect(saved.state.game).toEqual(before.state.game);}expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(saved.state.game!.rolls?.at(-1)?.stage==='after-roll')face=1;await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BARRIER_DO_WINDOW');}
 await send('B',{type:'PLAY_DEFENSE',cardInstanceId:card,dedicated:false});await until(s=>s.rolls?.at(-1)?.stage==='after-roll');const first=structuredClone((await game()).rolls!.at(-1)!);expect(first).toMatchObject({faces:[6,6],threshold:6,success:false});for(const actor of ['A','C','D']){expect((await room.snapshotFor(actor)).game!.currentRoll).not.toHaveProperty('threshold');expect((await room.snapshotFor(actor)).game!.currentRoll).not.toHaveProperty('success');}
 await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_DEFENSE',cardInstanceId:card,dedicated:false},true);const spare=card==='a2-p18-r2c2'?'a2-p18-r2c3':'a2-p18-r2c2';await send('B',{type:'PLAY_DEFENSE',cardInstanceId:spare,dedicated:false});await until(s=>!s.windows?.length);const done=await game();expect(done.rolls!.filter(r=>r.purpose==='excess-level').map(r=>[r.faces,r.success])).toEqual([[[6,6],false],[[1,1],true]]);expect(done.rolls!.find(r=>r.id===first.id)!.attempts).toEqual(first.attempts);expect([done.players.A!.damage,done.players.B!.damage]).toEqual([0,0]);expect(done.discard.filter(id=>id===card||id===spare)).toHaveLength(2);expect(done.players.B!.hand).not.toContain(card);expect(done.players.B!.hand).not.toContain(spare);
});
