import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {getAction} from '@madou/catalog';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
async function scenario(name:Parameters<typeof openTestRoom>[0]){
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(name);let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,error=false){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`combined-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored(),s=saved.state.game!,ids=allCardInstanceIds(s);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);for(const reserved of s.reclaimReservations){expect(s.deck).not.toContain(reserved);expect(s.discard).not.toContain(reserved);expect(s.resolution).not.toContain(reserved);for(const p of Object.values(s.players))expect(p.hand).not.toContain(reserved);}if(error){expect(s).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);}await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);for(const playerId of s.seatOrder)expect((await room.snapshotFor(playerId)).game).toEqual(viewFor(s,playerId));}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<400;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('R6_COMBINED_DO_WINDOW');}
 async function nextOwn(owner:string){for(let n=0;n<60;n++){const s=await game(),id=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(id===owner)return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment'){await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!=='a2-p13-r3c1').slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});await until(s=>!s.windows?.length);}else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error(`R6_COMBINED_DO_TURN_${s.phase}`);}throw Error('R6_COMBINED_DO_TURN_LIMIT');}
 return {room,game,send,until,nextOwn};
}
it('R6 DO commits counter follower and two-target three-hit deaths in one saved batch',async()=>{const f=await scenario('r6-combined-death'),s=await f.game(),b=s.players.B!.damage,c=s.players.C!.damage,counter=s.players.B!.hand.find(id=>getAction(id)!.name==='受け流し')!;await f.send('B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});await f.until(s=>s.players.B!.presence==='pending-death');const pending=await f.game();expect(pending.players.B).toMatchObject({presence:'pending-death',damage:b+14});expect(pending.players.C).toMatchObject({presence:'pending-death',damage:c+18});expect(pending.lifecycle!.find(t=>t.kind==='death-batch')).toMatchObject({actorIds:['B','C']});expect(pending.outcome).toBeUndefined();await f.send('B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false},true);await f.until(s=>!s.windows?.length);const done=await f.game();expect(done.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['B','C']);expect(done.resolution).toEqual([]);expect(done.outcome).toBeUndefined();});
it('R6 DO preserves frozen value then designation through actual death revival and a new-life rejected modifier',async()=>{const f=await scenario('r6-combined-suppression'),initial=await f.game(),id=Object.keys(initial.actions!)[0]!,life=initial.players.A!.lifeId,spirit=viewFor(initial,'A').abilityOptions.find(o=>o.abilityId==='c2-p01-r2c1-ab03')!;await f.send('A',{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:spirit.targetEventId});await f.until(s=>s.windows?.at(-1)?.kind==='damage'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');expect((await f.game()).actions![id]!.technique.effectLevel).toBe(6);const ban=viewFor(await f.game(),'C').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;await f.send('C',{type:'USE_ABILITY',abilityId:ban.abilityId,targetEventId:ban.targetEventId,targetIds:['A']});await f.until(s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values((await f.game()).groups!)[0]!.technique.effectLevel).toBe(6);const designation=structuredClone((await f.game()).suppressionDesignations);await f.until(s=>!s.windows?.length);await f.nextOwn('B');const lethal=(await f.game()).players.B!.hand.find(id=>getAction(id)!.name==='踏み込み／弓')!;await f.send('B',{type:'ATTACK',cardInstanceId:lethal,targetIds:['A'],dedicated:false});await f.until(s=>!s.windows?.length);expect((await f.game()).players.A!.presence).toBe('dead');expect((await f.game()).suppressionDesignations).toEqual(designation);expect((await f.game()).outcome).toBeUndefined();await f.nextOwn('D');await f.send('D',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['A'],dedicated:true});await f.until(s=>s.windows?.at(-1)?.kind==='re-setup');expect((await f.game()).players.A).toMatchObject({presence:'active',damage:0});expect((await f.game()).players.A!.lifeId).not.toBe(life);expect((await f.game()).suppressionDesignations).toEqual(designation);await f.send('A',{type:'PASS_SETUP'});await f.until(s=>!s.windows?.length);await f.nextOwn('A');const next=(await f.game()).players.A!.hand.find(id=>getAction(id)!.name==='手裏剣')!;await f.send('A',{type:'ATTACK',cardInstanceId:next,targetIds:['C'],dedicated:false});await f.until(s=>s.windows?.at(-1)?.kind==='effect-level');const now=await f.game(),event=Object.values(now.actions!).find(a=>a.kind==='attack')!.eventId;await f.send('A',{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:event},true);expect((await f.game()).suppressionDesignations).toEqual(designation);await f.until(s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values((await f.game()).groups!)[0]!.technique.effectLevel).toBe(4);await f.until(s=>!s.windows?.length);expect((await f.game()).players.C!.damage).toBe(5);});
it('R6 DO cancellation refill and normal recovery keep one replacement and one final return',async()=>{const f=await scenario('reclaim-owned'),s=await f.game(),heal=s.players.A!.hand.find(id=>getAction(id)!.name==='封傷')!,fate='a2-p02-r2c3',hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;await f.send('A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:heal,targetIds:['A'],dedicated:false});await f.send('A',{type:'PASS'});await f.send('B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:viewFor(await f.game(),'B').reactionTargetActionId!});const replacement=(await f.game()).players.B!.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();expect((await f.game()).players.B!.hand).toHaveLength(hand.length);await f.until(s=>s.windows?.at(-1)?.kind==='reclaim');const d=viewFor(await f.game(),'B').reclaim!,take={type:'CHOOSE_RECLAIM' as const,decisionId:d.decisionId,choice:'take' as const,claimId:d.claims[0]!.claimId};await f.send('B',take);expect((await f.game()).reclaimReservations).toContain(fate);await f.send('B',take,true);await f.until(s=>!s.windows?.length);const done=await f.game();expect(done.players.B!.hand).toHaveLength(hand.length+1);expect(done.players.B!.hand).toContain(replacement);expect(done.players.B!.hand.filter(id=>id===fate)).toHaveLength(1);expect(done.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(done.players.A!.damage).toBe(2);});
