import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {wolfFangScenarios,wolfFangCard as CARD,wolfFangMode} from './fixtures/wolf-fang-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(wolfFangScenarios)('%s physical two or three dice damage and optional range persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=wolfFangMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wolf-fang-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`wolf-fang-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WOLF_FANG_DO_LIMIT');}
 const initial=structuredClone(await state()),attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:m.dedicated},source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'){await reject('A',attack);return;}if(m.decline){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='far')await reject('A',{...attack,dedicated:false});if(m.suffix==='same-faction')await reject('A',{...attack,targetIds:['C']});await reject('A',{...attack,targetIds:['B','C']});await reject('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await send('A',attack);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);
 if(m.cancel){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);const s=await state();expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='attack-damage')).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 if(m.reroll){await until(s=>s.rolls?.at(-1)?.purpose==='attack-damage'&&s.rolls.at(-1)?.stage==='after-roll');const id=(await state()).rolls!.at(-1)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});await until(s=>s.rolls!.find(r=>r.id===id)?.generation===1);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({generation:1,total:m.dedicated?9:6});}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const ready=await state(),g=Object.values(ready.groups!).find(g=>g.actionId===source(ready).id)!;let damage=m.dedicated?9:6;expect(g.technique).toMatchObject({range:m.dedicated?'far':'near',useLevel:5,effectLevel:5,damage,damageFormula:m.dedicated?'3d6':'2d6',attributes:['戦','格'],noChecks:m.dedicated,target:'one',chant:false,counter:false});expect(g.technique.maaiRequired??1).toBe(m.dedicated?2:1);expect(ready.rolls!.find(r=>r.purpose==='attack-damage')).toMatchObject({faces:Array(m.dedicated?3:2).fill(3),total:damage});
 if(m.maai||m.evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.evade){await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});damage=0;}else{const count=m.suffix.includes('two')?2:1;for(const cardInstanceId of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId});}if(!m.dedicated||count===2)damage=0;}}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower){damage=m.suffix==='lower'?7:0;expect(final.players.B!.followers).toHaveLength(m.suffix==='lower'?0:1);}expect(final.players.B!.damage).toBe(damage);for(const id of ['A','C','D'])expect(final.players[id]!.damage).toBe(0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect((final.rolls??[]).filter(r=>r.purpose==='attack-damage')).toHaveLength(1);
},20000);
