import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
async function scenario(third=false,canceledChild=false){let face=4;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(canceledChild?'r6-s02-cancel-child':third?'r6-s01-s02-s05':'r6-s03-s04');let seq=0,savedRerolls=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,error?:string,oldWindow?:{windowId:string;windowRevision:number}){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`s01-05-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),...oldWindow,command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:error}:{type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);if(error){expect(saved.state.game).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);}expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if((saved.state.game!.rolls?.at(-1)?.attempts.length??0)>(before.state.game!.rolls?.at(-1)?.attempts.length??0)){savedRerolls++;face=6;}await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);return {envelope,ack};}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S01_05_DO_WINDOW');}
 return {room,game,send,until,rerolls:()=>savedRerolls};}
it('S01 S02 S05 DO rejects D first, accepts C at the unchanged revision, rejects old parent PASS generation and keeps forced failure after D reroll',async()=>{const f=await scenario(true),s=await f.game(),parent=structuredClone(s.windows!.at(-1)!),id=s.rolls!.at(-1)!.id,initial=await f.room.stored();expect(parent.passed).toEqual(['A','B']);const god={type:'PLAY_REACTION' as const,cardInstanceId:'a2-p02-r1c3',mode:'reroll' as const,targetRollId:id};await f.send('D',god,'INVALID_ACTION');expect((await f.room.stored()).revision).toBe(initial.revision);const accepted=await f.send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});expect(accepted.envelope.expectedRevision).toBe(initial.revision);await f.until(s=>s.windows?.at(-1)?.id===parent.id);expect((await f.game()).windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect((await f.game()).windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);await f.send('A',{type:'PASS'},'STALE_WINDOW',{windowId:parent.id,windowRevision:parent.revision});await f.until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await f.send('D',god);await f.until(s=>s.rolls!.at(-1)!.attempts.length===2);expect((await f.game()).rolls!.at(-1)).toMatchObject({id,faces:[4,4],total:8,threshold:9,forcedFailure:true,success:false,generation:1});expect(f.rerolls()).toBe(1);await f.until(s=>!s.windows?.length);expect((await f.game()).players.B!.statuses).toHaveLength(1);});
it('S03 DO cancellation preserves B payment refill and usage and never executes the canceled reroll',async()=>{const f=await scenario(),s=await f.game(),id=s.rolls!.at(-1)!.id,parent=s.windows!.at(-1)!.id,hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;await f.send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});const now=await f.game(),replacement=now.players.B!.hand.find(id=>!hand.includes(id))!,child=Object.values(now.actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;expect(now.players.B!.hand).toHaveLength(hand.length);expect(replacement).toBeDefined();await f.send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});await f.until(s=>s.windows?.at(-1)?.id===parent);expect((await f.game()).rolls!.at(-1)).toMatchObject({id,faces:[2,3],generation:0});expect(f.rerolls()).toBe(0);await f.until(s=>!s.windows?.length);const done=await f.game();expect(done.players.B!.hand).toContain(replacement);expect(done.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(done.discard).toEqual(expect.arrayContaining(['a2-p02-r1c3','a2-p02-r2c3']));expect(done.used!.some(k=>k.endsWith(':B:a2-p02-r1c3'))).toBe(true);expect(done.phase).toBe('withdrawal');expect(done.turnSeat).toBe(0);});
it('S04 DO disconnects directly after saving 4,4 and duplicate command cannot create a third attempt even with changed entropy',async()=>{const f=await scenario(),s=await f.game(),id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.faces).toEqual([2,3]);await f.send('B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});await f.until(s=>s.rolls!.at(-1)!.attempts.length===2);const roll=structuredClone((await f.game()).rolls!.at(-1)!);expect(roll).toMatchObject({id,faces:[4,4],success:true,generation:1});expect(roll.faces[0]===roll.faces[1]).toBe(true);expect(roll.attempts.map(a=>a.faces)).toEqual([[2,3],[4,4]]);expect(f.rerolls()).toBe(1);await f.until(s=>!s.windows?.length);expect((await f.game()).rolls!.find(r=>r.id===id)).toMatchObject({faces:[4,4],attempts:roll.attempts});expect((await f.game()).players.B!.statuses??[]).toEqual([]);});
it('S01 rejected D at C priority preserves all WebSocket views and creates no roll attempt or replacement',async()=>{
 const f=await scenario(true),before=await f.room.stored(),views=await Promise.all(['A','B','C','D'].map(id=>f.room.snapshotFor(id))),s=before.state.game!,roll=s.rolls!.at(-1)!;
 for(const view of views)expect(view.game!.activeWindow?.pendingActorId).toBe('C');
 const rolls=structuredClone(s.rolls),draws=s.events.filter(e=>e.type==='CARD_DRAWN');
 await f.send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:roll.id},'INVALID_ACTION');
 expect((await f.game()).rolls).toEqual(rolls);
 expect((await f.game()).events.filter(e=>e.type==='CARD_DRAWN')).toEqual(draws);
 expect((await f.room.stored()).state.game).toEqual(s);
 const restored=await Promise.all(['A','B','C','D'].map(id=>f.room.snapshotFor(id)));
 expect(restored.map(v=>({revision:v.revision,game:v.game}))).toEqual(views.map(v=>({revision:v.revision,game:v.game})));
 const receipt=await f.send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll.id});
 expect(receipt.envelope.expectedRevision).toBe(before.revision);
});

it('S02 DO child cancellation resets parent passes and rejects stale generation before accepting current A pass',async()=>{
 const f=await scenario(true,true),s=await f.game(),parent=structuredClone(s.windows!.at(-1)!),roll=structuredClone(s.rolls!.at(-1)!);
 expect(parent).toMatchObject({cursor:2,passed:['A','B']});
 await f.send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:roll.id});
 const child=Object.values((await f.game()).actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;
 await f.send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});
 await f.until(s=>s.windows?.at(-1)?.id===parent.id);
 expect((await f.game()).windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect((await f.game()).windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);
 expect((await f.game()).rolls!.at(-1)).toEqual(roll);expect(f.rerolls()).toBe(0);
 await f.send('A',{type:'PASS'},'STALE_WINDOW',{windowId:parent.id,windowRevision:parent.revision});
 await f.send('A',{type:'PASS'});expect((await f.game()).windows!.at(-1)).toMatchObject({id:parent.id,cursor:1,passed:['A']});
});
