import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {lightBowScenarios,lightBowCard as CARD,lightBowMode} from './fixtures/light-bow-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(lightBowScenarios)('%s physical ordinary eight Fury ten and Gadyura doubling and optional check waiver persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=lightBowMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`light-bow-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`light-bow-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('LIGHT_BOW_DO_LIMIT');}
 let initial=structuredClone(await state()),source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;if(scenario==='light-bow-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});expect((await state()).players.A!.hand).toContain(CARD);return;}if(scenario==='light-bow-wrong-owner'){await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});return;}if(m.decline){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);expect((await state()).players.B!.followers).toEqual(initial.players.B!.followers);return;}
 if(m.suffix==='white-prohibited'){for(const dedicated of [false,true])await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated});return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='same-faction')await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['C'],dedicated:true});
 await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:m.targets.map(i=>['A','B','C','D'][i]!),dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(CARD);
 if(m.cancel){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 let fixed=m.damage;
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!;expect(source(prepared).valuesPrepared).toBe(true);expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:6,damage:m.dedicated?10:8,attributes:['戦','弓','白'],destroyFollowerAttributes:['黒','死'],target:m.dedicated?'all':'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(g.technique.maaiRequired??1).toBe(m.dedicated?2:1);expect(g.targets[0]!.hits[0]!.damage).toBe(fixed);if(m.named){expect(prepared.players.B!.revealed).toBe(m.publicTarget);if(!m.publicTarget)expect(viewFor(prepared,'A').players.B!.characterId).toBeUndefined();}

 if(m.maai||m.evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.maai){const two=m.dedicated&&!m.suffix.includes('one-');for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,two?2:1)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}if(!m.dedicated||two)fixed=0;}else{expect(viewFor(await state(),'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});fixed=0;}}
 if((m.black||m.dead)&&!m.maai&&!m.evade){await until(s=>s.windows?.at(-1)?.kind==='follower-start');const w=(await state()).windows!.at(-1)!;for(let i=0;i<w.participants.length;i++){const active=(await state()).windows!.at(-1)!;await send(active.participants[active.cursor]!,{type:'PASS'});}const s=await state(),g=Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;expect(g.targets[0]!.followerDefense![0]!.hits[0]).toMatchObject({outcome:'attribute-destroyed',hpReduction:0});}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower){if(m.maai||m.evade)expect(final.players.B!.followers).toEqual(initial.players.B!.followers);else{if(!m.black&&!m.dead)fixed=m.suffix.includes('lower')?fixed-2:0;expect(final.players.B!.followers).toHaveLength(m.water?1:0);expect(final.discard.filter(id=>id===m.follower)).toHaveLength(m.water?0:1);}}else expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.B!.damage).toBe(fixed);if(m.named)expect(final.players.B!.revealed).toBe(fixed>0||m.publicTarget);expect(final.players.A!.damage).toBe(0);for(const i of [2,3])expect(final.players[['A','B','C','D'][i]!]!.damage).toBe(m.targets.includes(i)?10:0);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='light-bow-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});

},15000);
