import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {couragePhysicalScenarios,courageMode} from './fixtures/courage-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(couragePhysicalScenarios)('%s persists real Courage consent check beneficiary choice and delayed reservation with restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),card='a2-p01-r3c3',m=courageMode(scenario),owner=m.owner===2?'C':'D';let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`courage-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function step(){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('COURAGE_DO_PHASE');}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(await state()))return;await step();}throw Error('COURAGE_DO_LIMIT');}
 async function source(attackCard='a2-p24-r1c2'){await send('A',{type:'ATTACK',cardInstanceId:attackCard,targetIds:['B'],dedicated:false});await until(s=>s.windows?.at(-1)?.kind==='normal-defense');const o=viewFor(await state(),'B').abilityOptions.find(o=>o.abilityId===m.abilityId)!;await send('B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});}
 async function play(){await until(s=>viewFor(s,owner).anytimeCardOptions.some(o=>o.cardInstanceId===card));const o=viewFor(await state(),owner).anytimeCardOptions.find(o=>o.cardInstanceId===card)!;await send(owner,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId});}
 async function recover(){await until(s=>viewFor(s,'C').reclaim?.cardInstanceId===card&&viewFor(s,'C').reclaim?.pendingActorId==='C');if(scenario==='courage-reveal'){expect(viewFor(await state(),'C').reclaim!.claims).toEqual([]);await send('C',{type:'REVEAL_CHARACTER'});}const d=viewFor(await state(),'C').reclaim!;
  if(['courage-hidden','courage-check-decline','courage-stopped'].includes(scenario)){if(scenario!=='courage-check-decline')expect(d.claims).toEqual([]);await send('C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'decline'});return false;}
  const claim=d.claims.find(c=>c.action==='request-check')!;expect(claim).toBeDefined();await send('C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:claim.claimId});await until(s=>s.rolls?.some(r=>r.resume.kind==='reclaim-check'&&r.resume.decisionId===d.decisionId&&r.stage==='applied')===true);const roll=(await state()).rolls!.find(r=>r.resume.kind==='reclaim-check'&&r.resume.decisionId===d.decisionId)!;expect(roll.rollerId).toBe('C');expect(roll.success).toBe(scenario!=='courage-fail');if(!roll.success)return false;
  const target=viewFor(await state(),owner).reclaim!;expect(target.stage).toBe('beneficiary-choice');expect(target.pendingActorId).toBe(owner);if(owner!=='C')expect(viewFor(await state(),'C').reclaim!.claims).toEqual([]);if(scenario==='courage-user-decline'){await send(owner,{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'decline'});return false;}await send(owner,{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:target.claims[0]!.claimId});expect((await state()).reclaimReservations).toContain(card);expect((await state()).players[owner]!.hand).not.toContain(card);expect((await state()).discard).not.toContain(card);return true;
 }
 const prior=structuredClone((await state()).players.C!.statuses??[]),hand=(await state()).players[owner]!.hand.length;await source();const excluded=scenario==='courage-evil'||m.poem;let returned=false;
 if(excluded){await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]===owner;});expect(viewFor(await state(),owner).anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);}else{const before=gameStats(await state(),owner);await play();expect((await state()).players[owner]!.hand).toHaveLength(hand);if(scenario==='courage-refill'){expect((await state()).players[owner]!.open).toContain('a2-p01-r1c3');expect(gameStats(await state(),owner)).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});}if(scenario==='courage-canceled'){const child=Object.values((await state()).actions!).find(a=>a.cardInstanceId===card)!;await until(s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]==='A';});await send('A',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});}else returned=await recover();}
 await until(s=>!s.windows?.length);let s=await state();expect(s.players.B!.damage).toBe(excluded||scenario==='courage-canceled'?0:4);expect(s.players[owner]!.hand.includes(card)).toBe(excluded||returned);expect(s.reclaimReservations).not.toContain(card);if(returned){expect(s.players[owner]!.hand).toHaveLength(hand+1);if(owner!=='C')expect(s.players.C!.hand).not.toContain(card);}else if(!excluded)expect(s.discard.filter(id=>id===card)).toHaveLength(1);if(scenario==='courage-stopped')expect(s.players.C!.statuses).toEqual(prior);if(scenario==='courage-canceled')expect(s.reclaimDecisions?.some(d=>d.source.kind==='courage-resolution')).not.toBe(true);
 if(scenario==='courage-later'){await until(s=>!s.windows?.length&&s.seatOrder[s.turnSeat]==='A'&&s.phase==='action');await source('a2-p24-r2c2');await play();expect(await recover()).toBe(true);await until(s=>!s.windows?.length);s=await state();expect(s.players.B!.damage).toBe(8);expect(s.rolls!.filter(r=>r.resume.kind==='reclaim-check')).toHaveLength(2);expect(s.players[owner]!.hand.filter(id=>id===card)).toHaveLength(1);}
 expect((await state()).resolution).toEqual([]);
},15000);
