import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand,type GameState} from '@madou/engine';
import {getAction} from '@madou/catalog';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([false,true])('S14-S17 reflection=%s DO rejects closed defense then accepts a legal continuation across restart and duplicate receipt',async(reflection)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(1);return array;});const room=await openTestRoom(reflection?'r6-s17':'r6-s14');let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,error=false){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`s14-17-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(error?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(error){expect(saved.state.game).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);}await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S14_17_DO_WINDOW');}
 const s=await game(),card=(owner:string,name:string)=>s.players[owner]!.hand.find(id=>getAction(id)!.name===name)!;
 if(reflection){const mirror=s.resolution.find(id=>getAction(id)!.name==='ミラーシールド')!,ice=s.resolution.find(id=>getAction(id)!.name==='氷鏡')!;expect(Object.values(s.groups!)[2]!.targets[0]!.hits[0]!.lineage).toEqual([mirror,ice]);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false},true);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:card('B','転移'),dedicated:false});}
 else {await send('B',{type:'PLAY_DEFENSE',cardInstanceId:card('B','見切る'),dedicated:false},true);await until(s=>s.windows?.at(-1)?.kind==='after-roll'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');const roll=(await game()).rolls!.at(-1)!;expect(roll.purpose).toBe('follower-morale');await send('C',{type:'PLAY_REACTION',cardInstanceId:card('C','神性介入'),mode:'reroll',targetRollId:roll.id});await until(s=>s.rolls!.at(-1)!.attempts.length===2);expect((await game()).rolls!.at(-1)).toMatchObject({id:roll.id,faces:[2,2]});}
 await until(s=>!s.windows?.length);const done=await game();expect(done.groups).toEqual({});expect(done.players.B!.damage).toBe(0);if(reflection){expect(done.players.A!.statuses??[]).toEqual([]);expect(done.players.B!.statuses??[]).toEqual([]);}else {expect(done.players.B!.hand).toContain(card('B','見切る'));expect(done.players.B!.followers).toHaveLength(1);}expect(done.phase).toBe('withdrawal');
});
