import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {whirlwindKickScenarios,whirlwindKickCard as CARD,whirlwindKickMode} from './fixtures/whirlwind-kick-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(whirlwindKickScenarios)('%s physical fixed six and optional check waiver persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=whirlwindKickMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`whirlwind-kick-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`whirlwind-kick-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WHIRLWIND_KICK_DO_LIMIT');}
 let initial=structuredClone(await state()),source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;if(scenario==='whirlwind-kick-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});expect((await state()).players.A!.hand).toContain(CARD);return;}if(scenario==='whirlwind-kick-wrong-owner'){await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});return;}if(scenario==='whirlwind-kick-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});await until(s=>!s.windows?.length);expect((await state()).players.A!.damage).toBe(4);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='far'){await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:true});await send('A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'});await until(s=>!s.windows?.length);initial=structuredClone(await state());}
 if(m.suffix==='same-faction')await reject('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['C'],dedicated:true});
 await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==CARD));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(CARD);
 if(scenario==='whirlwind-kick-fate'){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 let fixed=6;
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const prepared=await state(),g=Object.values(prepared.groups!).find(g=>g.actionId===source(prepared).id)!;expect(source(prepared).valuesPrepared).toBe(true);expect(g.technique).toMatchObject({school:'warrior',range:'near',useLevel:6,effectLevel:6,damage:fixed,attributes:['戦','格'],maaiRequired:2,target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(g.targets[0]!.hits[0]!.damage).toBe(fixed);

 if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.suffix.startsWith('maai')){const count=m.suffix.includes('-two-')?2:1;for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}if(count===2)fixed=0;}else{expect(viewFor(await state(),'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});fixed=0;}}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower){fixed=m.suffix==='lower'?fixed-2:0;expect(final.players.B!.followers).toHaveLength(m.suffix.includes('water')?1:0);}else expect(final.players.B!.followers).toEqual(initial.players.B!.followers);expect(final.players.B!.damage).toBe(fixed);for(const id of ['A','C','D'])expect(final.players[id]!.damage).toBe(0);expect(final.players.C!.followers).toEqual(initial.players.C!.followers);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='whirlwind-kick-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});

},15000);
