import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['resurrection-ordinary',false],['resurrection-ordinary',true],['resurrection-dedicated',false],['resurrection-dedicated',true],['resurrection-chanted-dedicated',false],['resurrection-chanted-dedicated',true]] as const)('%s actual cast canceled=%s persists each re-setup and replay once',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario);let seq=0;const card='a2-p13-r3c1',dedicated=scenario!=='resurrection-ordinary',initial=(await room.stored()).state.game!;expect([initial.players.B!.presence,initial.players.C!.presence]).toEqual(['dead','dead']);const source=structuredClone(initial.players.A!);
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`resurrection-physical-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function nextOwn(){for(let n=0;n<100;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('RESURRECTION_DO_TURN');}throw Error('RESURRECTION_DO_TURN_LIMIT');}
 if(scenario!=='resurrection-dedicated'){await send('A',{type:'CHANT',cardInstanceId:card});await nextOwn();}await send('A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated,convertTargetIds:dedicated?['B']:[]});if(canceled){while(true){const s=(await room.stored()).state.game!,w=s.windows!.at(-1)!;if(w.participants[w.cursor]==='D'){await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id});break;}await send(w.participants[w.cursor]!,{type:'PASS'});}}
 const setups:string[]=[];for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;const id=w.participants[w.cursor]!;if(w.kind==='re-setup'){expect(s.outcome).toBeUndefined();expect(s.players[id]).toMatchObject({presence:'active',revealed:true,damage:0,attachments:[],followers:[]});expect(s.players[id]!.hand).toHaveLength(5);setups.push(id);await send(id,{type:'PASS_SETUP'});}else await send(id,{type:'PASS'});}
 const done=(await room.stored()).state.game!;expect(done.windows??[]).toEqual([]);expect(setups).toEqual(canceled?[]:dedicated?['B','C']:['B']);expect([done.players.B!.presence,done.players.C!.presence]).toEqual(canceled?['dead','dead']:dedicated?['active','active']:['active','dead']);expect(done.players.B!.faction).toBe(dedicated&&!canceled?'EVIL':'GOOD');if(dedicated&&!canceled)expect(done.players.B).toMatchObject({currentObjective:source.currentObjective,protection:source.protection,objective:source.objective});expect(done.discard.filter(id=>id===card)).toHaveLength(1);expect(done.discard).toContain('a2-p03-r3c1');expect(done.phase).toBe('hand-adjustment');expect(done.outcome).toBeUndefined();
},15000);
