import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {skyWingScenarios,skyWingCard as CARD,skyWingMode} from './fixtures/sky-wing-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(skyWingScenarios)('%s real CHANT full turn order and separately paid hit bonus persist through every restart replay',async scenario=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(2);return array;});const room=await openTestRoom(scenario),m=skyWingMode(scenario),costs=['a2-p24-r1c3','a2-p24-r2c1'];let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`sky-wing-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){const s=await state();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SKY_WING_DO_LIMIT');}
 const initial=structuredClone(await state());if(scenario==='sky-wing-stopped'){expect(initial.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');expect(initial.players.A!.hand).toContain(CARD);return;}if(scenario==='sky-wing-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 await send('A',{type:'CHANT',cardInstanceId:CARD,dedicated:false});expect((await state()).players.A!.chants.map(c=>c.cardInstanceId)).toContain(CARD);
 for(let n=0;n<300;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w){await send(w.participants[w.cursor]!,{type:'PASS'});continue;}if(s.phase==='action'&&id==='A')break;const command:GameCommand=s.phase==='action'?{type:'PASS_ACTION'}:s.phase==='hand-adjustment'?{type:'END_TURN',discardIds:[]}:s.phase==='turn-start'?{type:'START_TURN'}:s.phase==='draw'?{type:'CHOOSE_DRAW',draw:false}:{type:'PASS_WITHDRAWAL'};await send(id,command);}
 if(scenario==='sky-wing-wrong-owner'){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:'sky-wing-invalid-owner',expectedRevision:stored.revision,command:{type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:true}},error=await room.command('A',envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command('A',envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);return;}
 if(scenario==='sky-wing-near'){await send('A',{type:'APPROACH',cardInstanceId:costs[0]!,targetId:'B'});await until(s=>!s.windows?.length);expect((await state()).distances.A!.B).toBe('near');}
 const prepared=structuredClone(await state());await send('A',{type:'ATTACK',cardInstanceId:CARD,targetIds:['B'],dedicated:m.dedicated});expect((await state()).players.A!.hand).toEqual(prepared.players.A!.hand);expect((await state()).deck).toEqual(prepared.deck);expect((await state()).players.A!.chants).toEqual([]);
 if(scenario==='sky-wing-fate'){const id=(await state()).windows!.at(-1)!.continuation.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.B).toEqual(initial.players.B);expect((await state()).discard).toContain(CARD);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values((await state()).groups!).at(-1)!;expect(g.technique).toMatchObject({useLevel:7,effectLevel:m.dedicated?8:7,damage:m.dedicated?15:12,attributes:['戦','剣','詠'],chant:true,noChecks:m.dedicated,followerIgnore:m.dedicated,maaiRequired:2,target:'one'});
 const maai=scenario.includes('maai-')||scenario==='sky-wing-defense-advance',two=scenario.endsWith('-two')||scenario==='sky-wing-defense-advance',evade=scenario==='sky-wing-evade';
 if(maai||evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});if(maai){await until(s=>s.windows?.at(-1)?.kind!=='reclaim');expect(viewFor(await state(),'B').maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});if(two)await send('B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}if(scenario==='sky-wing-defense-advance'){await until(s=>s.windows?.at(-1)?.kind==='defense-advance');await send('A',{type:'PLAY_ADVANCE',cardInstanceId:costs[0]!});}}
 const payment=scenario==='sky-wing-post-two'?costs:scenario==='sky-wing-post-one'?[costs[0]!]:scenario==='sky-wing-defense-advance'?[costs[1]!]:[];
 if(payment.length){await until(s=>s.windows?.at(-1)?.kind==='hit-advance-choice');const before=await state();expect(before.players.B!.damage).toBe(0);await send('A',{type:'PAY_HIT_ADVANCES',groupId:before.windows!.at(-1)!.continuation.id,cardInstanceIds:payment});expect((await state()).deck).toEqual(before.deck);expect((await state()).players.A!.hand).toEqual(before.players.A!.hand.filter(id=>!payment.includes(id)));}
 await until(s=>!s.windows?.length);const final=await state(),evaded=scenario==='sky-wing-maai-two'||evade;expect(final.players.B!.damage).toBe(evaded?0:m.dedicated?15+payment.length*5:m.guard?7:12);expect(final.players.C!.damage).toBe(0);if(m.dedicated)expect(final.players.B!.followers).toEqual(initial.players.B!.followers);else if(m.guard)expect(final.players.B!.followers).toEqual([]);for(const id of payment)expect(final.discard.filter(x=>x===id)).toHaveLength(1);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect(final.phase).toBe('withdrawal');if(scenario==='sky-wing-low')expect(final.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:6,success:true});else expect(final.rolls?.length??0).toBe(prepared.rolls?.length??0);
},15000);
