import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {RIFT,DAWN,WISH,REVELATION} from './fixtures/rift-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['rift-physical-ordinary','dawn'],['rift-physical-dedicated','dawn'],['rift-physical-ordinary','cancel'],['rift-physical-dedicated','cancel']] as const)('%s actual %s persists chant resistance away possessions and return without duplicate events',async(scenario,outcome)=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),dedicated=scenario.includes('dedicated');let seq=0;
 async function send(actorId:string,command:GameCommand,die=1){face=die;const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`rift-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function finish(stopWish=false){for(let n=0;n<500;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w||stopWish&&w.kind==='wish')return;const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d)await send('A',{type:'CHOOSE_LIFETIME_EFFECT',choice:d.targetId==='B'?'apply':'decline'});else await send(w.participants[w.cursor]!,{type:'PASS'},r?.stage==='before-roll'&&r.purpose==='status-resistance'?6:1);}throw Error('RIFT_DO_FINISH');}
 async function nextOwn(chantB=false){for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')return;await send(id,chantB&&id==='B'&&s.players.B!.hand.includes('a2-p15-r3c1')?{type:'CHANT',cardInstanceId:'a2-p15-r3c1'}:{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>![RIFT,WISH,REVELATION].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('RIFT_DO_TURN');}throw Error('RIFT_DO_LIMIT');}
 await send('A',{type:'CHANT',cardInstanceId:RIFT});await nextOwn(true);const before=(await room.stored()).state.game!;expect(before.players.B!.chants).toHaveLength(1);await send('A',{type:'ATTACK',cardInstanceId:RIFT,targetIds:['B','C','D'],dedicated});if(outcome==='cancel'){const s=(await room.stored()).state.game!,id=Object.values(s.actions!).find(a=>a.cardInstanceId===RIFT)!.id;for(const actor of ['A','B','C'])await send(actor,{type:'PASS'});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}await finish();let done=(await room.stored()).state.game!;expect(done.discard.filter(id=>id===RIFT)).toHaveLength(1);expect(done.players.A!.chants).toEqual([]);for(const id of ['B','C','D']){expect(done.players[id]!.presence).toBe(outcome==='cancel'?'active':'otherworld');expect(done.players[id]!.damage).toBe(outcome==='cancel'?0:dedicated?12:8);expect(done.players[id]!.followers).toEqual(before.players[id]!.followers);expect(done.players[id]!.chants).toEqual(before.players[id]!.chants);}if(outcome==='cancel')return;
 expect(done.rolls!.filter(r=>r.purpose==='status-resistance').map(r=>r.threshold)).toEqual(dedicated?[3,6,6]:[6,6,6]);const away=structuredClone(done.players.B!);await nextOwn();done=(await room.stored()).state.game!;expect(done.players.B).toEqual(away);expect(viewFor(done,'A').anytimeCardOptions.filter(o=>o.cardInstanceId===REVELATION).some(o=>o.targetId==='B')).toBe(false);await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:WISH,mode:'wish'});await finish(true);done=(await room.stored()).state.game!;const wish=viewFor(done,'A').wish!;for(const id of ['B','C','D']){expect(wish.handOwners.some(o=>o.ownerId===id)).toBe(false);expect(wish.publicSources.some(o=>o.ownerId===id)).toBe(false);}await send('A',{type:'CHOOSE_WISH',decisionId:wish.decisionId,source:{kind:'deck',cardName:'大陸の夜明け'}});done=(await room.stored()).state.game!;expect(done.players.B).toEqual({...away,presence:'active'});expect(done.players.A!.open).toContain(DAWN);expect(done.events.filter(e=>e.type==='PLAYER_RETURNED').map(e=>e.actorId)).toEqual(['B','C','D']);expect(done.deck).toContain(RIFT);expect(done.windows?.some(w=>w.kind==='re-setup')).toBe(false);await finish();expect((await room.stored()).state.game!.players.B).toEqual({...away,presence:'active'});
},15000);
