import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it('S20 physical poem saves the same stop through minus3 minus2 minus1 and resumes refill draw and actual turn',async()=>{let faces=[3,4];vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let n=0;n<array.length;n++)array[n]=faces[n%2]!-1;return array;});const room=await openTestRoom('r6-s20-hit');let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`s20-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S20_DO_WINDOW');}
 async function nextStart(){for(let n=0;n<50;n++){const s=await game(),actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'){if(actor==='B')return;await send(actor,{type:'START_TURN'});}else if(s.phase==='action')await send(actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment'){await send(actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))});await until(s=>!s.windows?.length);}else if(s.phase==='draw')await send(actor,{type:'CHOOSE_DRAW',draw:false});else throw Error('S20_DO_TURN');}throw Error('S20_DO_TURN_LIMIT');}
 expect((await game()).players.B!.hand).toHaveLength(4);expect((await game()).rolls!.at(-1)).toMatchObject({modifier:-3,purpose:'status-resistance'});await until(s=>!s.windows?.length);let s=await game();const id=s.players.B!.statuses![0]!.id;expect(s.players.B!.statuses![0]).toMatchObject({sourceCardInstanceId:'a2-p17-r1c1',nextCheck:1});expect(s.players.B!.damage).toBe(5);await nextStart();await send('B',{type:'START_TURN'});expect((await game()).rolls!.at(-1)).toMatchObject({modifier:-2,purpose:'status-recovery'});await until(s=>!s.windows?.length);s=await game();expect(s.players.B!.statuses![0]).toMatchObject({id,nextCheck:2});expect(s.players.B!.hand).toHaveLength(4);expect(s.turnSeat).toBe(2);await nextStart();faces=[2,3];await send('B',{type:'START_TURN'});expect((await game()).rolls!.at(-1)).toMatchObject({modifier:-1,purpose:'status-recovery'});const draws=(await game()).events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;await until(s=>!s.windows?.length);s=await game();expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.hand).toHaveLength(5);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.phase).toBe('draw');await send('B',{type:'CHOOSE_DRAW',draw:true});expect((await game()).players.B!.hand).toHaveLength(6);await send('B',{type:'PASS_ACTION'});await send('B',{type:'END_TURN',discardIds:[(await game()).players.B!.hand[0]!]});await until(s=>!s.windows?.length);s=await game();expect(s.turnSeat).toBe(2);expect(s.rolls!.filter(r=>r.purpose==='status-resistance'||r.purpose==='status-recovery').map(r=>[r.modifier,r.success])).toEqual([[-3,false],[-2,false],[-1,true]]);});
it('S22 same refill saves FuSen then Dawn and rejects the old generation after original parent resume',async()=>{vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(3);return array;});const room=await openTestRoom('r6-s22');let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`s22-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<150;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S22_DO_WINDOW');}
 const initial=await game(),parent=structuredClone(initial.windows!.at(-1)!),hand=initial.players.C!.hand.length,draws=initial.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C').length;expect(initial.players.D!.presence).toBe('dead');await send('C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.continuation.id});expect((await game()).players.C!.open).toContain('a2-p01-r1c1');expect((await game()).players.C!.open).not.toContain('a2-p01-r1c2');await until(s=>s.windows?.at(-1)?.kind==='revival');expect((await game()).players.C!.hand).toHaveLength(hand-1);await send('D',{type:'CHOOSE_REVIVAL',revive:false});let s=await game();expect(s.players.C!.open).toEqual(expect.arrayContaining(['a2-p01-r1c1','a2-p01-r1c2']));expect(s.players.C!.hand).toHaveLength(hand);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C')).toHaveLength(draws+1);for(const id of ['a2-p02-r2c3','a2-p08-r1c1']){expect(s.resolution).toContain(id);expect(s.deck).not.toContain(id);}await until(s=>s.windows?.at(-1)?.id===parent.id);s=await game();expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);
 const before=await room.stored(),stale={protocolVersion:1 as const,commandId:'s22-stale-generation',expectedRevision:before.revision,windowId:parent.id,windowRevision:parent.revision,command:{type:'PASS' as const}};const error=await room.command('A',stale);expect(error).toMatchObject({type:'error',code:'STALE_WINDOW'});expect((await room.stored()).state.game).toEqual(before.state.game);await room.restart();expect(await room.command('A',stale)).toEqual(error);await until(s=>!s.windows?.length);s=await game();expect(s.players.C!.damage).toBe(0);for(const id of ['a2-p02-r2c3','a2-p08-r1c1'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.resolution).toEqual([]);expect(s.phase).toBe('withdrawal');});
it('S23 actual three-card draw naturally shuffles only two discard and preserves resolution across restart',async()=>{vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom('r6-s23');let seq=0;const initial=(await room.stored()).state.game!,first=initial.deck[0]!,discards=[...initial.discard],hand=initial.players.A!.hand.length;expect(initial.deck).toHaveLength(1);expect(discards).toHaveLength(2);expect(initial.resolution).toEqual(['a2-p03-r1c1']);expect(initial.rolls!.at(-1)).toMatchObject({purpose:'extra-draw',faces:[3]});let checked=false;
 for(let n=0;n<100;n++){const before=await room.stored(),s=before.state.game!,w=s.windows?.at(-1);if(!w)break;if(w.kind==='reclaim'&&!checked){expect(s.players.A!.hand.slice(hand)).toEqual([first,discards[1],discards[0]]);expect(s.deck).toEqual([]);expect(s.discard).toEqual([]);expect(s.resolution).toEqual(['a2-p03-r1c1']);checked=true;}const envelope={protocolVersion:1 as const,commandId:`s23-${seq++}`,expectedRevision:before.revision,...activeWindowRef(s),command:{type:'PASS' as const}},actor=w.participants[w.cursor]!,ack=await room.command(actor,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actor,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 expect(checked).toBe(true);const s=(await room.stored()).state.game!;expect(s.phase).toBe('action');expect(s.players.A!.hand).toHaveLength(hand+3);expect(s.players.A!.hand).not.toContain('a2-p03-r1c1');expect(s.discard).toEqual(['a2-p03-r1c1']);expect(s.resolution).toEqual([]);expect(s.lifecycle??[]).toEqual([]);});
