import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {GATE} from './fixtures/gate-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['gate-physical-empty',0,0,false],['gate-physical-spare',1,1,false],['gate-physical-full',0,0,false],['gate-physical-full',1,1,false],['gate-physical-full',0,1,true],['gate-physical-incompatible',0,0,false]] as const)('%s actual source%s destination%s cancel=%s persists paid capacity and exact physical transfer',async(scenario,targetPosition,destinationPosition,cancel)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario);let seq=0;async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`gate-physical-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 const initial=(await room.stored()).state.game!,donor=structuredClone(initial.players.B!.followers),own=structuredClone(initial.players.A!.followers),replacement=own.length===2?own[1]!.cardInstanceId:undefined;expect(viewFor(initial,'A').magicGateTargets).toEqual([{actorId:'B',positions:[0,1]}]);await send('A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:GATE,targetIds:['B'],dedicated:false,followerTransfer:{targetPosition,destinationPosition,...(replacement?{replacementCardInstanceId:replacement}:{})}});let saved=(await room.stored()).state.game!;expect(saved.players.B!.followers).toEqual(donor);if(replacement){expect(saved.players.A!.followers).toEqual([own[0]]);expect(saved.discard).toContain(replacement);}const source=Object.values(saved.actions!).find(a=>a.cardInstanceId===GATE)!;expect(source.followerTransfer).toMatchObject({donorId:'B',cardInstanceId:donor[targetPosition]!.cardInstanceId,destinationPosition});expect(JSON.stringify(viewFor(saved,'A'))).not.toContain(donor[targetPosition]!.cardInstanceId);if(cancel){for(const id of ['A','B','C'])await send(id,{type:'PASS'});await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:source.id});}for(let n=0;n<200;n++){saved=(await room.stored()).state.game!;const w=saved.windows?.at(-1);if(!w)break;expect(w.kind).not.toBe('normal-defense');await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!,success=!cancel&&scenario!=='gate-physical-incompatible',expected=own.filter(f=>f.cardInstanceId!==replacement);if(success)expected.splice(destinationPosition,0,donor[targetPosition]!);expect(done.players.A!.followers).toEqual(expected);expect(done.players.B!.followers).toEqual(success?donor.filter((_,i)=>i!==targetPosition):donor);expect(done.discard.filter(id=>id===GATE)).toHaveLength(1);if(replacement)expect(done.discard.filter(id=>id===replacement)).toHaveLength(1);expect(done.players.B!.damage).toBe(0);expect(done.phase).toBe('hand-adjustment');if(!success)for(const id of ['A','C','D'])expect(JSON.stringify(viewFor(done,id))).not.toContain(donor[targetPosition]!.cardInstanceId);
},15000);
