import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
type Room=Awaited<ReturnType<typeof openTestRoom>>;
const game=async(room:Room)=>(await room.stored()).state.game!;
async function send(room:Room,actorId:string,id:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:id,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);return ack;}
async function until(room:Room,done:(s:GameState)=>boolean,prefix:string){for(let n=0;n<300;n++){const s=await game(room);if(done(s))return;const w=s.windows!.at(-1)!;await send(room,w.participants[w.cursor]!,`${prefix}-${n}`,{type:'PASS'});}throw Error('SHARED_DO_LIMIT');}
it.each(['a09','a31','budget'] as const)('Shared %s paired hidden worlds retain public snapshots and identical PASS receipts through reload',async kind=>{vi.spyOn(Date,'now').mockReturnValue(1000);vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array)new Uint8Array(array.buffer,array.byteOffset,array.byteLength).fill(0);return array;});const names=kind==='a09'?['shared-a09-hidden','shared-a09-none'] as const:kind==='a31'?['shared-a31-hidden','shared-a31-none'] as const:['shared-budget-none','shared-budget-base','shared-budget-extra','shared-budget-both'] as const,rooms:Room[]=[];for(const name of names)rooms.push(await openTestRoom(name));const outsiders=kind==='budget'?['B','C','D']:['A','C','D'];for(let n=0;n<300;n++){const base=await game(rooms[0]!);for(const actor of outsiders){const first=(await rooms[0]!.snapshotFor(actor)).game;for(const room of rooms.slice(1))expect((await room.snapshotFor(actor)).game).toEqual(first);}for(const room of rooms){const saved=await room.stored();await room.restart();expect(await room.stored()).toEqual(saved);}const w=base.windows?.at(-1);if(!w)break;const receipts=[];for(const room of rooms)receipts.push(await send(room,w.participants[w.cursor]!,`shared-pair-${n}`,{type:'PASS'}));for(const ack of receipts.slice(1))expect(ack).toEqual(receipts[0]);}for(const room of rooms)expect((await game(room)).windows??[]).toEqual([]);});
it.each(['take','beneficiary-decline','checker-decline','failed-check'] as const)('Shared A09 %s saves distinct checker and beneficiary without duplicate source movement',async choice=>{const room=await openTestRoom(choice==='failed-check'?'shared-a09-fail':'shared-a09-hidden');await send(room,'A','pass-A',{type:'PASS'});const waiting=(await game(room)).windows!.at(-1)!;await send(room,'B','reveal-B',{type:'REVEAL_CHARACTER'});expect((await game(room)).windows!.at(-1)).toEqual(waiting);const d=viewFor(await game(room),'B').reclaim!,claim=d.claims.find(c=>c.right==='printed')!;if(choice==='checker-decline')await send(room,'B','pass-B',{type:'PASS'});else{await send(room,'B','request',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:claim.claimId});const checked=await game(room);expect(checked.rolls!.at(-1)).toMatchObject({rollerId:'B',formula:'2d6',modifier:0});await until(room,s=>s.windows?.at(-1)?.kind==='reclaim','check');const result=viewFor(await game(room),'A').reclaim!;if(choice!=='failed-check'){expect(result.stage).toBe('beneficiary-choice');expect(viewFor(await game(room),'B').reclaim!.claims).toEqual([]);if(choice==='take'){await send(room,'A','take',{type:'CHOOSE_RECLAIM',decisionId:result.decisionId,choice:'take',claimId:result.claims[0]!.claimId});expect((await game(room)).reclaimReservations).toContain('a2-p01-r3c3');expect((await game(room)).resolution).not.toContain('a2-p01-r3c3');}else await send(room,'A','decline',{type:'PASS'});}}await until(room,s=>!s.windows?.length,'finish');const done=await game(room);expect(done.players.A!.hand.filter(id=>id==='a2-p01-r3c3')).toHaveLength(choice==='take'?1:0);expect(done.players.B!.hand).not.toContain('a2-p01-r3c3');expect(done.reclaimReservations).toEqual([]);for(const actor of ['A','B'])expect(done.players[actor]!.reclaimUsage?.['勇気']).toBeUndefined();});
