import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {blastSwordScenarios,blastSwordCard as CARD,blastSwordMode} from './fixtures/blast-sword-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(blastSwordScenarios)('%s physical two target chant and dedicated counter persist through every restart replay',async scenario=>{
 let countDice=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)for(let n=0;n<array.length;n++)array[n]=countDice?2:n%2;return array;});const room=await openTestRoom(scenario),m=blastSwordMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`blast-sword-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function reject(actorId:string,command:GameCommand){const stored=await room.stored();countDice=stored.state.game!.windows?.at(-1)?.kind==='damage'||viewFor(stored.state.game!,'A').currentRoll?.purpose==='attack-hit-count';const envelope={protocolVersion:1 as const,commandId:`blast-sword-invalid-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},error=await room.command(actorId,envelope);expect(error).toMatchObject({type:'error'});expect((await room.stored()).state.game).toEqual(stored.state.game);await room.restart();expect(await room.command(actorId,envelope)).toEqual(error);expect((await room.stored()).state.game).toEqual(stored.state.game);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BLAST_SWORD_DO_LIMIT');}
 let initial=structuredClone(await state());const attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:m.targets.map(i=>['A','B','C','D'][i]!),dedicated:m.dedicated};
 if(m.suffix==='stopped'){await reject('A',attack);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix.startsWith('unprepared')){await reject('A',attack);expect((await state()).players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='wrong-owner'){await reject('A',attack);return;}
 if(m.incoming){const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;if(['counter-ordinary','counter-unprepared','counter-foreign','counter-decline'].includes(m.suffix)){if(m.suffix!=='counter-decline'){await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});if(m.suffix!=='counter-ordinary')await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true});}await until(s=>!s.windows?.length);const s=await state();expect(s.players.A!.damage).toBe(4);expect(s.players.B!.damage).toBe(0);expect(s.discard).not.toContain(CARD);expect(s.players.A!.hand.includes(CARD)||s.players.A!.chants.some(c=>c.cardInstanceId===CARD)).toBe(true);return;}
 await reject('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});await send('A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true});expect(source(await state()).fromChant).toBe(true);expect(source(await state()).checks).toEqual([]);if(m.suffix==='counter-fate'){const id=source(await state()).id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else{await until(s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'B').activeWindow?.pendingActorId==='B');const s=await state(),g=Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;expect(g.targets.map(t=>t.actorId)).toEqual(['B']);expect(g.technique).toMatchObject({effectLevel:8,damage:15,maaiRequired:2});if(m.maai){for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,m.suffix.endsWith('two')?2:1)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}}if(m.evade)await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}await until(s=>!s.windows?.length);const s=await state();expect(s.players.A!.damage).toBe(m.suffix==='counter-fate'?4:0);expect(s.players.B!.damage).toBe(m.suffix==='counter-fate'||m.evade||m.suffix.endsWith('two')?0:m.follower?11:15);expect(s.players.C!.damage).toBe(0);expect(s.players.D!.damage).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);return;}
 if(m.suffix.startsWith('chant-')){await reject('A',attack);await send('A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});await reject('A',attack);const visited=new Set<string>();for(let n=0;n<300;n++){const s=await state(),id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='action'){if(id==='A')break;visited.add(id);await send(id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('BLAST_SWORD_DO_TURN');}expect([...visited]).toEqual(['B','C','D']);initial=structuredClone(await state());}
 if(m.suffix==='same-faction')await reject('A',{...attack,targetIds:['C']});
 expect(initial.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);await send('A',attack);expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand);expect((await state()).players.A!.chants).toEqual([]);const source=(s:GameState)=>Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;
 if(m.suffix.startsWith('fate-')){const after=m.suffix.endsWith('after'),id=source(await state()).id;if(after)await until(s=>s.windows?.at(-1)?.kind==='before-roll'&&s.rolls!.at(-1)!.purpose==='excess-level');await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',after?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:(await state()).rolls!.at(-1)!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);const s=await state();expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='attack-hit-count')).toHaveLength(0);if(after){expect(s.rolls!.find(r=>r.purpose==='activation')!.success).toBe(true);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',forcedFailure:true,success:false});}expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);return;}
 await until(s=>s.windows?.at(-1)?.kind==='attack-abilities');const ready=await state(),g=Object.values(ready.groups!).find(g=>g.actionId===source(ready).id)!;
 expect(g.technique).toMatchObject({range:'far',useLevel:8,effectLevel:8,damage:15,attributes:['戦','剣','詠'],chant:true,counter:m.dedicated,hitCount:1,maxTargets:2,noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual(m.targets.map(()=>[15]));
 let bDamage=15;if(m.maai||m.evade){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.maai){const count=m.suffix.includes('-two-')?2:1;for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){await until(s=>s.windows?.at(-1)?.kind==='normal-defense');await send('B',{type:'PLAY_MAAI',cardInstanceId:id});}bDamage=!m.dedicated||count===2?0:15;}else{await send('B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});bDamage=0;}}
 await until(s=>!s.windows?.length);const final=await state();if(m.follower){bDamage=m.suffix==='water'?11:m.suffix==='metal'?10:13;expect(final.players.B!.followers).toHaveLength(0);expect(final.discard.filter(id=>id===m.follower)).toHaveLength(1);}
 expect(final.players.B!.damage).toBe(bDamage);expect(final.players.C!.damage).toBe(m.targets.includes(2)?15:0);expect(final.players.D!.damage).toBe(m.targets.includes(3)?15:0);expect(final.players.A!.damage).toBe(0);expect(final.discard.filter(id=>id===CARD)).toHaveLength(1);expect((final.rolls??[]).filter(r=>r.purpose==='attack-hit-count'||r.purpose==='attack-damage')).toHaveLength(0);
},20000);
