import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['spear-ordinary','a2-p10-r3c3',false,5],['spear-dedicated','a2-p10-r3c3',true,7],['mountain-ordinary','a2-p11-r1c2',false,4],['mountain-dedicated','a2-p11-r1c2',true,7]] as const)('%s physical %s selected=%s persists counter damage%s and the context-specific roll once',async(scenario,card,dedicated,damage)=>{
 let changed=false;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(changed?5:0);return array;});const room=await openTestRoom(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`spear-mountain-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);if(saved.state.game!.rolls?.some(r=>r.stage==='after-roll'))changed=true;await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('B',{type:'PLAY_DEFENSE',cardInstanceId:card,dedicated});for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;await send(w.participants[w.cursor]!,{type:'PASS'});}const done=(await room.stored()).state.game!;expect(done.windows).toEqual([]);expect([done.players.A!.damage,done.players.B!.damage]).toEqual([damage,0]);expect(done.discard.filter(id=>id===card)).toHaveLength(1);expect(done.players.B!.hand).not.toContain(card);const checks=done.rolls?.filter(r=>r.purpose==='counter'||r.purpose==='excess-level')??[];expect(checks).toHaveLength(scenario==='mountain-dedicated'?0:1);for(const roll of checks){expect(roll).toMatchObject({faces:[1,1],success:true});expect(roll.attempts).toHaveLength(1);}expect(done.phase).toBe('withdrawal');
});
