import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {farseeingPhysicalScenarios,farseeingMode,farseeingCard,astrologyAbility} from './fixtures/farseeing-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(farseeingPhysicalScenarios)('%s saves private identity or automatic hand inspection optional discard and native budget across every restart replay',async scenario=>{
 let face=scenario==='farseeing-fail'||scenario==='farseeing-reroll'||scenario==='farseeing-garwin'||scenario==='farseeing-asfelt'?6:3;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=farseeingMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`farseeing-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('FARSEEING_DO_LIMIT');}
 const initial=await state(),target=m.self?'A':'B',before=structuredClone(initial.players[target]!),used=structuredClone(initial.used),rolls=initial.rolls?.length??0;if(scenario==='farseeing-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(farseeingCard);return;}await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:farseeingCard,targetId:target,mode:m.astrology?'astrology':'ordinary'});expect((await state()).players.A!.hand).toEqual(initial.players.A!.hand.filter(id=>id!==farseeingCard));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(farseeingCard);const targetHand=[...(await state()).players[target]!.hand];
 if(m.fate){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===farseeingCard)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).rolls?.length??0).toBe(rolls);expect((await state()).events.some(e=>e.type==='CHARACTER_INSPECTED')).toBe(false);expect((await state()).players[target]!.hand).toEqual(targetHand);expect((await state()).discard).toContain(farseeingCard);return;}
 let success=true;if(!m.astrology){await until(s=>s.rolls?.at(-1)?.purpose==='card-inspection');const id=(await state()).rolls!.at(-1)!.id;await until(s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll');expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({rollerId:'A',threshold:6,total:face*2,faces:[face,face]});if(scenario==='farseeing-forced'||scenario==='farseeing-reroll'){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');if(scenario==='farseeing-forced'){await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});await until(s=>s.windows?.at(-1)?.continuation.id===id&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});face=1;await until(s=>s.rolls!.find(r=>r.id===id)!.generation===1);expect((await state()).rolls!.find(r=>r.id===id)).toMatchObject({total:2,forcedFailure:scenario==='farseeing-forced',success:scenario!=='farseeing-forced'});}success=(await state()).rolls!.find(r=>r.id===id)!.success!;}
 let drop:string|undefined;if(success){await until(s=>!!viewFor(s,'A').inspection);const s=await state(),d=viewFor(s,'A').inspection!;for(const id of ['B','C','D'])expect(viewFor(s,id).inspection).toBeNull();expect(s.resolution).toContain(farseeingCard);if(m.astrology){expect(d).toMatchObject({zone:'hand',cards:targetHand.map((cardInstanceId,position)=>({cardInstanceId,position}))});expect(d).not.toHaveProperty('characterId');expect(s.rolls?.length??0).toBe(rolls);expect(s.events.some(e=>e.type==='CHARACTER_INSPECTED')).toBe(false);expect(d.cards.some(c=>c.cardInstanceId==='a2-p18-r3c3')).toBe(false);if(m.discard)drop=d.cards[0]!.cardInstanceId;}else expect(d).toMatchObject({zone:'character',characterId:before.characterId,cards:[],choices:['finish']});await send('A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:drop?'discard-one':'finish',...(drop?{cardInstanceId:drop}:{})});}await until(s=>!s.windows?.length);const final=await state();expect(final.players[target]!.hand).toEqual(targetHand.filter(id=>id!==drop));expect(final.players[target]!.revealed).toBe(before.revealed);expect(final.players[target]!.followers).toEqual(before.followers);expect((final.used??[]).filter(k=>k.includes(astrologyAbility))).toEqual((used??[]).filter(k=>k.includes(astrologyAbility)));expect(final.discard).toContain(farseeingCard);if(drop)expect(final.discard).toContain(drop);expect(final.phase).toBe('hand-adjustment');if(!m.astrology)expect(viewFor(final,'A').privateLogs.some(e=>e.type==='CHARACTER_INSPECTED'&&e.characterId===before.characterId)).toBe(success);for(const id of ['B','C','D'])expect(viewFor(final,id).logs.filter(e=>e.type==='CHARACTER_INSPECTED').every(e=>!e.characterId)).toBe(true);
 if(scenario==='farseeing-astrology-after'){const o=viewFor(final,'A').abilityOptions.find(o=>o.abilityId===astrologyAbility)!;await send('A',{type:'USE_ABILITY',abilityId:astrologyAbility,targetEventId:o.targetEventId,targetId:'B'});await until(s=>!!viewFor(s,'A').inspection);expect((await state()).rolls!.at(-1)).toMatchObject({purpose:'ability-check',success:true});await send('A',{type:'CHOOSE_INSPECTION',decisionId:viewFor(await state(),'A').inspection!.decisionId,choice:'finish'});await until(s=>!s.windows?.length);expect((await state()).used!.filter(k=>k.includes(astrologyAbility))).toHaveLength(1);}
},15000);
