import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {waterStatusMode} from './fixtures/water-status-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['poison-flow-ordinary',false],['poison-flow-ordinary',true],['poison-flow-dedicated',false],['poison-flow-dedicated',true],['freeze-ordinary',false],['freeze-ordinary',true],['freeze-dedicated',false],['freeze-dedicated',true]] as const)('%s failed=%s saves target resistance and actual later recovery exactly once',async(scenario,failed)=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const m=waterStatusMode(scenario),room=await openTestRoom(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`water-status-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function finish(fail:boolean){for(let n=0;n<400;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;const r=s.rolls?.at(-1);face=fail&&r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)&&r.stage==='before-roll'?6:1;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('WATER_STATUS_DO_WINDOWS');}
 async function nextB(){for(let n=0;n<200;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)await send(w.participants[w.cursor]!,{type:'PASS'});else if(s.phase==='turn-start'){if(id==='B')return;await send(id,{type:'START_TURN'});}else if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WATER_STATUS_DO_PHASE');}throw Error('WATER_STATUS_DO_TURN');}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});await finish(failed);let done=(await room.stored()).state.game!;expect([done.players.B!.damage,done.players.C!.damage]).toEqual([m.damage+(m.poison&&failed?6:0),m.dedicated?m.damage:0]);expect(done.rolls!.filter(r=>r.purpose==='status-resistance').map(r=>({actor:r.rollerId,success:r.success,modifier:r.modifier}))).toEqual(m.dedicated?[{actor:'B',success:!failed,modifier:m.modifier},{actor:'C',success:true,modifier:m.modifier}]:[{actor:'B',success:!failed,modifier:m.modifier}]);expect(done.players.B!.statuses??[]).toHaveLength(!m.poison&&failed?1:0);
 if(!m.poison&&failed){const id=done.players.B!.statuses![0]!.id;await nextB();await send('B',{type:'START_TURN'});await finish(true);done=(await room.stored()).state.game!;expect(done.players.B!.statuses![0]).toMatchObject({id,modifiers:[m.modifier],nextCheck:2,sourceCardInstanceId:m.card});expect(done.seatOrder[done.turnSeat]).toBe('C');await nextB();await send('B',{type:'START_TURN'});await finish(false);done=(await room.stored()).state.game!;expect(done.players.B!.statuses).toEqual([]);expect(done.phase).toBe('draw');expect(done.rolls!.filter(r=>r.purpose==='status-recovery').map(r=>({modifier:r.modifier,success:r.success,faces:r.faces}))).toEqual([{modifier:m.modifier,success:false,faces:[6,6]},{modifier:m.modifier,success:true,faces:[1,1]}]);}expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);
},15000);
