import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {getAction} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {secretBookPhysicalScenarios,bookMode} from './fixtures/secret-book-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(secretBookPhysicalScenarios)('%s saves exact numeric draws and OPEN suspension without spending ordinary action across restart replay',async scenario=>{
 let face=scenario==='book-one'?1:scenario==='book-six'?6:3;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const room=await openTestRoom(scenario),m=bookMode(scenario);let seq=0;const state=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`book-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command},ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(await state()))return;const w=(await state()).windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('BOOK_DO_LIMIT');}
 const initial=await state(),hand=[...initial.players.A!.hand];let ordinary=initial.deck.filter(id=>getAction(id)!.category!=='open');if(m.fail){expect(initial.seatOrder[initial.turnSeat]).not.toBe('A');expect(viewFor(initial,'A').turnCardOptions.some(o=>o.cardInstanceId===m.card)).toBe(false);expect(hand).toHaveLength(4);return;}if(scenario==='book-late'){await send('A',{type:'APPROACH',cardInstanceId:m.advance,targetId:'B'});await until(s=>!s.windows?.length);expect((await state()).phase).toBe('action');expect(viewFor(await state(),'A').turnCardOptions.some(o=>o.cardInstanceId===m.card)).toBe(false);return;}if(scenario==='book-decline'){await send('A',{type:'PASS_ACTION'});expect((await state()).players.A!.hand).toContain(m.card);return;}
 if(m.recovery){expect(initial.rolls!.some(r=>r.purpose==='status-recovery'&&r.success)).toBe(true);expect(hand).toHaveLength(5);expect(initial.discard).toContain('a2-p06-r1c1');}await send('A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card});expect((await state()).players.A!.hand).toEqual(hand.filter(id=>id!==m.card));expect((await state()).deck).toEqual(initial.deck);expect((await state()).resolution).toContain(m.card);
 if(scenario==='book-fate'){const id=Object.values((await state()).actions!).find(a=>a.cardInstanceId===m.card)!.id;await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});await until(s=>!s.windows?.length);expect((await state()).players.A!.hand).toEqual(hand.filter(id=>id!==m.card));expect((await state()).rolls?.some(r=>r.purpose==='extra-draw')??false).toBe(false);expect((await state()).phase).toBe('action');return;}
 await until(s=>s.rolls?.at(-1)?.purpose==='extra-draw');const roll=(await state()).rolls!.at(-1)!;expect(roll).toMatchObject({kind:'numeric',formula:'d6',faces:[face],stage:'after-roll'});if(scenario==='book-reroll'){await until(s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:roll.id});ordinary=(await state()).deck.filter(id=>getAction(id)!.category!=='open');face=6;await until(s=>s.rolls!.find(r=>r.id===roll.id)!.generation===1);}
 if(m.opens){face=1;await until(s=>s.windows?.at(-1)?.kind==='revival');expect((await state()).players.A!.hand).toHaveLength(hand.length-1);expect((await state()).resolution).toContain(m.card);expect((await state()).players.A!.open).not.toContain('a2-p01-r1c3');await send('B',{type:'CHOOSE_REVIVAL',revive:scenario==='book-revive'});if(scenario==='book-revive'){await until(s=>s.windows?.at(-1)?.kind==='re-setup');expect((await state()).players.A!.hand).toHaveLength(hand.length-1);expect((await state()).players.B!.hand).toHaveLength(5);ordinary=(await state()).deck.filter(id=>getAction(id)!.category!=='open');await send('B',{type:'PASS_SETUP'});}}await until(s=>!s.windows?.length);const final=await state(),drawn=final.rolls!.find(r=>r.id===roll.id)!.total!;expect(final.players.A!.hand).toEqual([...hand.filter(id=>id!==m.card),...ordinary.slice(0,drawn)]);expect(final.rolls!.filter(r=>r.purpose==='extra-draw')).toHaveLength(1);expect(final.phase).toBe('action');expect(final.resolution).toEqual([]);expect(final.discard).toContain(m.card);for(const actor of ['B','C','D'])for(const id of ordinary.slice(0,drawn))expect(JSON.stringify(viewFor(final,actor))).not.toContain(id);if(m.opens){expect(final.players.A!.open).toContain('a2-p01-r1c1');expect(final.players[scenario==='book-revive'?'B':'A']!.open).toEqual(expect.arrayContaining(['a2-p01-r1c3','a2-p01-r2c2']));}
 if(scenario==='book-main-attack'){await send('A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:['B'],dedicated:false});await until(s=>!s.windows?.length);expect((await state()).players.B!.damage).toBe(4);return;}if(scenario==='book-main-chant')await send('A',{type:'CHANT',cardInstanceId:m.chant});else await send('A',{type:'PASS_ACTION'});const s=await state(),excess=Math.max(0,s.players.A!.hand.length-gameStats(s,'A').handLimit);await send('A',{type:'END_TURN',discardIds:excess?s.players.A!.hand.slice(-excess):[]});await until(s=>!s.windows?.length);expect((await state()).players.A!.hand.length).toBeLessThanOrEqual(gameStats(await state(),'A').handLimit);
},15000);
