import {reset} from 'cloudflare:test';
import {afterEach,expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand,type GameState} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
afterEach(async()=>{await reset();});
it('S30 actual away owner stays private through both live wishes and Revelation refusals then returns with possessions after Dawn and restart',async()=>{const room=await openTestRoom('r6-s30-first');let seq=0;const game=async()=>(await room.stored()).state.game!;
 async function send(actorId:string,command:GameCommand,reject=false){const before=await room.stored(),views=reject?await Promise.all(['A','B','C','D'].map(async id=>(await room.snapshotFor(id)).game)):[],envelope={protocolVersion:1 as const,commandId:`s30-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command},ack=await room.command(actorId,envelope);expect(ack).toMatchObject(reject?{type:'error',code:'INVALID_ACTION'}:{type:'ack'});const saved=await room.stored();if(reject){expect(saved.state.game).toEqual(before.state.game);expect(saved.revision).toBe(before.revision);expect(await Promise.all(['A','B','C','D'].map(async id=>(await room.snapshotFor(id)).game))).toEqual(views);}const ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function until(done:(s:GameState)=>boolean){for(let n=0;n<300;n++){const s=await game();if(done(s))return;const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('S30_DO_WINDOW');}
 async function nextC(){for(let n=0;n<60;n++){const s=await game(),actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'&&actor==='C')return;if(s.phase==='turn-start')await send(actor,{type:'START_TURN'});else if(s.phase==='draw')await send(actor,{type:'CHOOSE_DRAW',draw:false});else if(s.phase==='action')await send(actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment'){await send(actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.filter(id=>!['a2-p04-r3c3','a2-p02-r1c2'].includes(id)).slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))});await until(s=>!s.windows?.length);}else throw Error('S30_DO_TURN');}throw Error('S30_DO_TURN_LIMIT');}
 const b=structuredClone((await game()).players.B!),possessions={hand:b.hand,followers:b.followers,chants:b.chants,attachments:b.attachments,open:b.open};expect(b.presence).toBe('otherworld');expect(b.damage).toBe(12);expect(b.followers).toHaveLength(1);expect(b.chants).toHaveLength(1);expect(b.attachments).toHaveLength(1);
 for(const wish of ['a2-p04-r3c2','a2-p04-r3c3'] as const){let s=await game();const options=viewFor(s,'D').anytimeCardOptions.filter(o=>o.cardInstanceId==='a2-p02-r1c2');expect(options.length).toBeGreaterThan(0);expect(options.some(o=>o.targetId==='B')).toBe(false);await send('D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r1c2',targetId:'B',targetEventId:options[0]!.targetEventId},true);await send('C',{type:'PLAY_TURN_CARD',cardInstanceId:wish,mode:'wish'});await until(s=>s.windows?.at(-1)?.kind==='wish');s=await game();const d=viewFor(s,'C').wish!;expect(d.handOwners.some(o=>o.ownerId==='B')).toBe(false);expect(d.publicSources.some(o=>o.ownerId==='B')).toBe(false);for(const source of [{kind:'hand' as const,ownerId:'B'},...b.attachments.map(cardInstanceId=>({kind:'public' as const,cardInstanceId})),...b.chants.map(c=>({kind:'public' as const,cardInstanceId:c.cardInstanceId}))])await send('C',{type:'CHOOSE_WISH',decisionId:d.decisionId,source},true);expect((await game()).players.B).toMatchObject(possessions);await send('C',{type:'CHOOSE_WISH',decisionId:d.decisionId,source:wish==='a2-p04-r3c2'?{kind:'hand',ownerId:'A'}:{kind:'deck',cardName:getAction('a2-p01-r1c2')!.name}});await until(s=>!s.windows?.length);if(wish==='a2-p04-r3c2'){expect((await game()).players.B!.presence).toBe('otherworld');await nextC();}}
 const s=await game();expect(s.players.B).toMatchObject({...possessions,presence:'active',damage:12});expect(s.players.B!.lifeId).toBe(b.lifeId);expect(s.players.C!.open).toContain('a2-p01-r1c2');expect(s.events.filter(e=>e.type==='PLAYER_RETURNED'&&e.actorId==='B')).toHaveLength(1);expect(s.events.filter(e=>e.type==='PLAYER_REVIVED'&&e.actorId==='B')).toEqual([]);expect(s.players.D!.hand).toContain('a2-p02-r1c2');expect(s.phase).toBe('hand-adjustment');});
