import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,gameStats,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {singingShipPhysicalMode} from './fixtures/singing-ship-physical-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each([['ship-setup',false],['ship-turn',false],['ship-earth',false],['ship-earth-rear',false],['ship-earth-ignore',false],['ship-army',false],['ship-ded-hand',false],['ship-ded-field',false],['ship-army',true],['ship-ded-hand',true],['ship-ded-field',true]] as const)('%s canceled=%s persists exact Singing Ship defense and paid attack',async(scenario,canceled)=>{
 vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(0);return array;});const room=await openTestRoom(scenario),m=singingShipPhysicalMode(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const stored=await room.stored(),envelope={protocolVersion:1 as const,commandId:`singing-ship-${seq++}`,expectedRevision:stored.revision,...activeWindowRef(stored.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack,JSON.stringify({command,ack})).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 async function settle(){for(let n=0;n<300;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)return;await send(w.participants[w.cursor]!,{type:'PASS'});}throw Error('SINGING_SHIP_DO_SETTLE');}
 if(m.rear)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});if(m.initial)await send('A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of ['A','B','C','D'])await send(id,{type:'PASS_SETUP'});await send('A',{type:'START_TURN'});await send('A',{type:'CHOOSE_DRAW',draw:false});
 if(m.dedicated||m.army){if(m.army)await send('A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});else await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B','C'],dedicated:true});if(canceled){let s=(await room.stored()).state.game!;const id=Object.values(s.actions!).find(a=>a.cardInstanceId===(m.army?'a2-p05-r2c2':m.card))!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D'){await send(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!,{type:'PASS'});s=(await room.stored()).state.game!;}await send('D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}}
 else{if(!m.initial)await send('A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,id=s.seatOrder[s.turnSeat]!;if(s.windows?.length){await settle();continue;}if(id==='B'&&s.phase==='action')break;if(s.phase==='action')await send(id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')await send(id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')await send(id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')await send(id,{type:'START_TURN'});else if(s.phase==='draw')await send(id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SINGING_SHIP_DO_TURN');}if(m.ignore)await send('B',{type:'REVEAL_CHARACTER'});await send('B',{type:'ATTACK',cardInstanceId:m.earth?'a2-p16-r2c3':'a2-p24-r1c2',targetIds:m.earth&&!m.rear&&!m.ignore?['A','C']:['A'],dedicated:m.earth&&!m.rear&&!m.ignore});if(m.ignore){for(let n=0;n<150;n++){const s=(await room.stored()).state.game!,o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r1c1-ab02');if(o){await send('B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,costCardInstanceId:'a2-p24-r2c1'});break;}const w=s.windows!.at(-1)!;await send(w.participants[w.cursor]!,{type:'PASS'});}}}
 await settle();const s=(await room.stored()).state.game!,alive=!m.dedicated&&!m.army;expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.dedicated||m.army?[0,canceled?0:2,!canceled&&m.dedicated?2:0]:m.ignore?[6,0,0]:m.earth&&!m.rear?[0,0,9]:[0,0,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(alive?m.rear?['a2-p22-r1c1',m.card]:[m.card]:[]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(alive?0:1);if(m.army)expect(s.discard.filter(x=>x==='a2-p05-r2c2')).toHaveLength(1);if(m.ignore){expect(s.discard.filter(x=>x==='a2-p24-r2c1')).toHaveLength(1);expect(s.players.A!.followers[0]!.revealed).toBe(false);}expect(s.resolution).toEqual([]);
},15000);
