import {reset} from 'cloudflare:test';
import {afterEach,expect,it,vi} from 'vitest';
import {activeWindowRef,allCardInstanceIds,viewFor,type GameCommand} from '@madou/engine';
import {openTestRoom} from './fixtures/recovery-room.js';
import {iceMagicMode} from './fixtures/ice-magic-scenarios.js';
afterEach(async()=>{vi.restoreAllMocks();await reset();});
it.each(['ice-arrow-ordinary','ice-arrow-dedicated','ice-stream-ordinary','ice-stream-dedicated','ice-stream-declined','ice-stream-relative'] as const)('%s saves actual follower choice, relative limit and independent target results once',async scenario=>{
 let face=1;vi.spyOn(crypto,'getRandomValues').mockImplementation(<T extends ArrayBufferView|null>(array:T):T=>{if(array instanceof Uint32Array)array.fill(face-1);return array;});const m=iceMagicMode(scenario),room=await openTestRoom(scenario);let seq=0;
 async function send(actorId:string,command:GameCommand){const before=await room.stored(),envelope={protocolVersion:1 as const,commandId:`ice-magic-${seq++}`,expectedRevision:before.revision,...activeWindowRef(before.state.game!),command};const ack=await room.command(actorId,envelope);expect(ack).toMatchObject({type:'ack'});const saved=await room.stored(),ids=allCardInstanceIds(saved.state.game!);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);await room.restart();expect(await room.command(actorId,envelope)).toEqual(ack);expect(await room.stored()).toEqual(saved);}
 await send('A',{type:'ATTACK',cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated});let prayed=false;const offered:string[]=[];
 for(let n=0;n<350;n++){const s=(await room.stored()).state.game!,w=s.windows?.at(-1);if(!w)break;if(m.relative&&!prayed&&w.kind==='effect-level'){const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;await send('A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});prayed=true;}else if(w.kind==='follower-bypass-choice'){const target=viewFor(s,'A').currentAttack!.targetId!;offered.push(target);if(m.relative){expect(Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.technique.effectLevel).toBe(8);expect(s.rolls!.filter(r=>r.faces.length===1)).toHaveLength(1);expect(s.rolls!.find(r=>r.faces.length===1)!.faces).toEqual([1]);face=6;}const before=await room.stored();expect(await room.command('B',{protocolVersion:1,commandId:`ice-foreign-${seq++}`,expectedRevision:before.revision,...activeWindowRef(s),command:{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true}})).toMatchObject({type:'error',code:'INVALID_ACTION'});expect(await room.stored()).toEqual(before);await send('A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:target==='B'&&m.ignore});}else await send(w.participants[w.cursor]!,{type:'PASS'});}
 const done=(await room.stored()).state.game!;expect(offered).toEqual(!m.arrow&&m.dedicated?['B','C']:[]);expect([done.players.B!.damage,done.players.C!.damage]).toEqual([m.arrow?m.damage-1:m.dedicated&&m.ignore?6:0,m.dedicated?(m.arrow?6:5):0]);expect(done.players.B!.followers).toHaveLength(m.arrow||m.dedicated&&!m.ignore?0:1);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.phase).toBe('withdrawal');
},15000);
