/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/wrangler.jsonc --include-runtime=false test/worker-configuration.d.ts` (hash: 31dc7f813add1409843b84b88684df1b)
interface __BaseEnv_Env {
	DB: D1Database;
	PROBE: DurableObjectNamespace<import("./fixtures/store-worker").RoomStoreProbe>;
	ROOMS: DurableObjectNamespace<import("./fixtures/store-worker").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./fixtures/store-worker");
		durableNamespaces: "RoomStoreProbe" | "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
