/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/wrangler.jsonc --include-runtime=false test/worker-configuration.d.ts` (hash: 1fafb71cc5e97654f9e133ba4208588c)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ENVIRONMENT: "local";
	BASE_URL: "https://game.example";
	EMAIL_FROM_ADDRESS: "noreply@madou-senki.local";
	AUTH_SECRET: "worker-test-only-secret-0123456789abcdef";
	PROBE: DurableObjectNamespace<import("./fixtures/store-worker").RoomStoreProbe>;
	ROOMS: DurableObjectNamespace<import("./fixtures/store-worker").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./fixtures/store-worker");
		durableNamespaces: "RoomStoreProbe" | "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BASE_URL" | "EMAIL_FROM_ADDRESS" | "AUTH_SECRET">> {}
}
