packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - esbuild
  - workerd
patchedDependencies:
  '@cloudflare/vitest-pool-workers@0.22.0': patches/cloudflare-vitest-pool-workers-0.22.0.patch
