import {expect,test,type Locator} from '@playwright/test';
import {amuletPhysicalScenarios,amuletMode} from '../../apps/worker/test/fixtures/amulet-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of amuletPhysicalScenarios)test(`${scenario} actual Amulet named ability scope and saved prior effects survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,dp=table.pages[3]!,m=amuletMode(scenario),card='a2-p01-r3c2';const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function step(){const g=game(),w=g.activeWindow;if(w){const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));return;}const seat=g.turnSeat,p=table.pages[seat]!;if(g.phase==='hand-adjustment'){const v=views.get(ids[seat]!)!.game!.self,excess=Math.max(0,v.hand.length-v.stats.handLimit);for(const card of v.hand.slice(0,excess))await select(seat,card);await click(p.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));return;}const label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;if(!label)throw Error('AMULET_UI_PHASE');await click(p.getByRole('button',{name:label,exact:true}));}
 async function until(done:()=>boolean){for(let n=0;n<300;n++){if(done())return;await step();}throw Error('AMULET_UI_LIMIT');}
 async function attack(card:string){await select(0,card);await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await until(()=>game().activeWindow?.kind==='normal-defense');}
 async function use(){const o=views.get(b)!.game!.abilityOptions.find(o=>o.abilityId===m.abilityId)!;expect(o).toBeDefined();await click(table.pages[1]!.getByRole('button',{name:`${o.name}を使う`,exact:true}));}
 const prior=structuredClone(game().players[c]!),profile=structuredClone(views.get(c)!.game!.self.currentObjective),rollCount=game().recentRolls.length,hand=views.get(d)!.game!.self.hand.length;
 if(scenario==='amulet-card-charm'){const panel=page.getByRole('region',{name:'対象を選ぶ手番カード'});await panel.getByRole('combobox',{name:'魅了の対象',exact:true}).selectOption(c);await click(panel.getByRole('button',{name:'魅了を使う',exact:true}));}else{await attack('a2-p24-r1c2');await use();}
 const ignored=scenario==='amulet-decline'||scenario==='amulet-card-charm'||m.other;
 if(ignored){await until(()=>game().activeWindow?.pendingActorId===d);await dp.reload();const button=dp.getByRole('button',{name:'ソロモン王の護符を使う',exact:true});if(scenario==='amulet-decline')await expect(button).toBeEnabled();else await expect(button).toHaveCount(0);}
 else{await until(()=>views.get(d)!.game!.anytimeCardOptions.some(o=>o.cardInstanceId===card));await dp.reload();const before={...views.get(d)!.game!.self.stats};await click(dp.getByRole('button',{name:'ソロモン王の護符を使う',exact:true}));await dp.reload();expect(views.get(d)!.game!.self.hand).toHaveLength(hand);if(scenario==='amulet-refill'){expect(game().players[d]!.open).toContain('a2-p01-r1c3');expect(views.get(d)!.game!.self.stats).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});}if(scenario==='amulet-canceled'){await until(()=>game().activeWindow?.pendingActorId===c);const panel=table.pages[2]!.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}}
 await until(()=>!game().activeWindow);await dp.reload();if(!ignored&&scenario!=='amulet-canceled'){expect(game().players[b]!.damage).toBe(4);expect(game().recentRolls).toHaveLength(rollCount);expect(game().players[a]!.statuses).toEqual([]);}else if(scenario==='amulet-decline'||scenario==='amulet-canceled'){const roll=game().recentRolls.at(-1)!;expect(roll.purpose).toBe('ability-check');const double=roll.faces![0]===roll.faces![1];expect(game().players[b]!.damage).toBe(!roll.success||double?0:4);expect(game().players[a]!.statuses.some(t=>t.kind==='stopped')).toBe(double);expect(game().recentRolls).toHaveLength(rollCount+1);}if(scenario==='amulet-card-charm'){const roll=views.get(c)!.game!.recentRolls.at(-1)!;expect(roll.purpose).toBe('faction-change');expect(views.get(c)!.game!.self.faction).toBe(roll.success?'GOOD':'EVIL');}if(m.prior){expect(game().players[c]).toEqual(prior);expect(views.get(c)!.game!.self.currentObjective).toEqual(profile);}if(ignored)expect(views.get(d)!.game!.self.hand).toContain(card);else expect(game().discard.filter(id=>id===card)).toHaveLength(1);
 if(scenario==='amulet-later'){await until(()=>!game().activeWindow&&game().seatOrder[game().turnSeat]===a&&game().phase==='action');await attack('a2-p24-r2c2');await use();await table.pages[1]!.reload();await until(()=>!game().activeWindow);const roll=game().recentRolls.at(-1)!;expect(roll.purpose).toBe('ability-check');const double=roll.faces![0]===roll.faces![1];expect(game().players[b]!.damage).toBe(!roll.success||double?4:8);expect(game().players[a]!.statuses.some(t=>t.kind==='stopped')).toBe(double);expect(game().recentRolls.filter(r=>r.purpose==='ability-check')).toHaveLength(1);}
 expect(errors).toEqual([]);
 }finally{await table.close();}
});
