import {expect,test,type Locator} from '@playwright/test';
import {asfeltSwordMode,type AsfeltSword, type AsfeltSwordsScenario} from '../../apps/worker/test/fixtures/asfelt-swords-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const card of ['wind','thunder','rend'] as const)for(const mode of ['guard','dedicated','all','maai','evade','fate'] as const)test(`asfelt-${card}-${mode} actual source election follower outcomes and legal defense controls survive reload`,async({browser,request})=>{
 const scenario=`asfelt-${card}-${mode}` as AsfeltSwordsScenario,table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=asfeltSwordMode(card,mode),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('ASFELT_SWORDS_UI_LIMIT');}
  const targets=mode==='all'?[b,c,d]:m.dedicated?[b,c]:[b],hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers);
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(m.card)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));expect(own(a).hand).toEqual(hand.filter(id=>id!==m.card));expect(game().deckCount).toBe(deck);await page.reload();
  if(mode==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);expect(game().discard).toContain(m.card);return;}
  await until(()=>game().activeWindow?.kind==='attack-abilities');const damage=m.dedicated?m.damage*2:m.damage;expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?m.level+2:m.level,damage,attributes:['戦','剣','風']});
  if(mode==='maai'||mode==='evade'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'}),select=reaction.getByRole('combobox',{name:'使うカード',exact:true});if(mode==='maai'){for(const id of ['a2-p06-r1c3','a2-p07-r1c1'].slice(0,m.maai)){await select.selectOption(id);await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));await until(()=>game().activeWindow?.kind!=='reclaim');}await bp.reload();}else if(card==='wind'){await select.selectOption('a2-p05-r3c1');await click(reaction.getByRole('button',{name:'防御する',exact:true}));}else{await expect(select.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);expect(own(b).hand).toContain('a2-p05-r3c1');}}
  await until(()=>!game().activeWindow);const evaded=mode==='maai'||mode==='evade'&&card==='wind',moraleFailed=views.get(c)!.game!.recentRolls.some(r=>r.purpose==='follower-morale'&&r.rollerId===c&&r.success===false);expect(game().players[b]!.damage).toBe(evaded?0:m.guard&&!m.hpIgnore?damage-2:damage);if(evaded)expect(own(b).followers).toEqual(bFollowers);else expect(own(b).followers).toEqual([]);if(targets.includes(c)){expect(game().players[c]!.damage).toBe(card==='rend'||moraleFailed?damage:0);if(card==='wind'&&!moraleFailed)expect(own(c).followers[0]).toMatchObject({cardInstanceId:'a2-p23-r1c1',revealed:true});else expect(own(c).followers).toEqual([]);}if(targets.includes(d))expect(game().players[d]!.damage).toBe(card==='wind'?0:card==='thunder'?9:16);expect(game().discard.filter(id=>id===m.card)).toHaveLength(1);expect(game().phase).toBe('withdrawal');await page.reload();expect(own(a).hand).not.toContain(m.card);expect(errors).toEqual([]);
 }finally{await table.close();}
});
