import {expect,test,type Locator} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {attributeJewelsPhysicalScenarios,jewelMode} from '../../apps/worker/test/fixtures/attribute-jewels-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of attributeJewelsPhysicalScenarios)test(`${scenario} actual installation attribute checks and faction-sensitive morale survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,dp=table.pages[3]!,m=jewelMode(scenario);const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('JEWEL_UI_LIMIT');}
 async function attack(owner:number,card:string,target:number){const p=table.pages[owner]!,hand=views.get(ids[owner]!)!.game!.self.hand,index=hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await p.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();await p.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:p.getByRole('heading',{name:table.sessions[target]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(p.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}
 if(m.early){const hand=[...game().self.hand],deckCount=game().deckCount;if(scenario.endsWith('-decline')){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(game().self.hand).toContain(m.card);expect(game().players[a]!.attachments).toEqual([]);return;}await click(page.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:`${getAction(m.card)!.name}を使う`,exact:true}));expect(game().self.hand).toEqual(hand.filter(id=>id!==m.card));expect(game().deckCount).toBe(deckCount);expect(game().players[a]!.attachments).toEqual([]);await page.reload();if(scenario.endsWith('-fate')){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));}await until(()=>!game().activeWindow);expect(game().phase).toBe('hand-adjustment');expect(game().players[a]!.attachments).toEqual(scenario.endsWith('-fate')?[]:[m.card]);expect(game().discard.includes(m.card)).toBe(scenario.endsWith('-fate'));await page.reload();expect(game().self.stats.magic_level).toBe(3);return;}
 for(const id of ids)expect(views.get(id)!.game!.players[a]!.attachments).toContain(m.card);let trainingSuccess=false;
 if(m.morale){const bonus=m.follower==='a2-p21-r2c2'&&m.finalEvil!==m.crown?m.bonus:0;expect(game().self.faction).toBe(m.finalEvil?'EVIL':'GOOD');if(m.converted)expect(game().logs.some(e=>e.type==='FACTION_CHANGED'&&e.actorId===a)).toBe(true);if(m.army){const army=page.getByRole('region',{name:'全軍突撃せよ',exact:true});await army.getByRole('combobox',{name:'突撃に使う従者',exact:true}).selectOption(m.follower);await army.locator('input[name="all-army-target"]').nth(0).check();await click(army.getByRole('button',{name:'2枚を使って全軍突撃する',exact:true}));}else await attack(1,'a2-p24-r1c2',0);await until(()=>game().currentRoll?.purpose==='follower-morale');expect(game().currentRoll!.stage).toBe('before-roll');await page.reload();await until(()=>game().currentRoll?.purpose==='follower-morale'&&game().currentRoll!.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6+game().currentRoll!.modifier+bonus);await expect(page.getByRole('region',{name:'サイコロの結果',exact:true})).toContainText(`判定値: ${game().currentRoll!.threshold}以下`);}
 else if(m.training){await click(page.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:'修行（魔法技）を使う',exact:true}));await until(()=>game().currentRoll?.purpose==='training'&&game().currentRoll!.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(3);trainingSuccess=game().currentRoll!.success!;expect(trainingSuccess).toBe(game().currentRoll!.total!>3);await page.reload();}
 else{await attack(0,m.spell,1);const current=game().currentAction!;expect(current.technique?.useLevel).toBe(m.spell==='a2-p15-r2c2'?6:4);await page.reload();}
 await until(()=>!game().activeWindow);expect(game().players[a]!.attachments).toContain(m.card);expect(game().discard).not.toContain(m.card);expect(game().self.stats.magic_level).toBe(m.training&&trainingSuccess?4:3);if(!m.morale&&!m.training){const checks=game().recentRolls.filter(r=>r.purpose==='excess-level'&&r.rollerId===a);expect(checks).toHaveLength(scenario==='crown-element'?0:1);}await page.reload();expect(game().players[a]!.attachments).toContain(m.card);expect(errors).toEqual([]);
 }finally{await table.close();}
});
