import {expect,test,type Locator} from '@playwright/test';
import {beastKingScenarios,beastKingCard as CARD,beastKingMode} from '../../apps/worker/test/fixtures/beast-king-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of beastKingScenarios.filter(name=>name!=='beast-king-multi-fail'))test(`${scenario} actual Beast King composite choices inherited restrictions and sources survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=beastKingMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<800;n++){if(done())return;await step();}throw Error('BEAST_KING_UI_LIMIT');}
  async function select(card:string){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(card)).getByRole('button').first().click();}
  async function target(id:string){await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='near-far'){await select('a2-p24-r1c3');await target(b);await click(page.getByRole('button',{name:'接近',exact:true}));await until(()=>!game().activeWindow);}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),rolls=game().recentRolls.map(r=>r.rollId),targets=m.coDedicated?[b,c]:[b];let execute:Locator;
  if(m.suffix==='counter'){const panel=page.getByRole('region',{name:'技の追加効果',exact:true});execute=panel.getByRole('button',{name:'獣王剣の組み合わせで防御する',exact:true});await expect(execute).toBeDisabled();await panel.getByLabel('組み合わせる技').selectOption(`${m.co}:false:`);}
  else{await select(CARD);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await target(id);execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});
   if(m.suffix==='wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}
   if(m.suffix==='unchanted'||m.suffix==='level-low'){expect(game().combinationOptions.flatMap(o=>o.coSources).some(o=>o.cardInstanceId===m.co)).toBe(false);await expect(page.locator(`select option[value="${m.co}:false:"]`)).toHaveCount(0);expect(own(a).hand).toEqual(hand);return;}
   if(m.suffix==='invalid-co'){for(const key of ['a2-p12-r2c2:false:','a2-p05-r3c1:false:','a2-p24-r2c2:false:',`${CARD}:false:`,'a2-p08-r3c3:true:'])await expect(page.locator(`select option[value="${key}"]`)).toHaveCount(0);}
   if(m.co)await page.getByLabel('組み合わせる技').selectOption(`${m.co}:${m.coDedicated}:`);
  }
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>![CARD,m.co].includes(id)));expect(game().deckCount).toBe(deck);if(m.coDedicated)expect(own(a).followers).toEqual([]);if(m.chant)expect(own(a).chants).toEqual([]);await page.reload();if(m.co)await expect(page.getByRole('region',{name:'現在の行動',exact:true})).toContainText('組み合わせた技');
  if(m.suffix==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);for(const id of [CARD,m.co])expect((await storedDiscard()).filter(c=>c===id)).toHaveLength(1);return;}
  let success=true,damage=({bow:14,spirit:16,null:10,multi:17,chant:22,'invalid-co':14,'near-far':15,union:16,'maai-one':17,'maai-two':17,'evade-restrict':18,counter:15,'placed-griffin':18} as Record<string,number>)[m.suffix]??10,hits=m.coDedicated?2:1;
  if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(m.suffix==='multi'){await until(()=>game().currentRoll?.purpose==='activation'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(4);success=game().currentRoll!.success!;}
  if(success&&(m.suffix==='wolf'||m.suffix==='multi')){await until(()=>game().currentRoll?.purpose===(m.suffix==='wolf'?'attack-damage':'attack-hit-count')&&game().currentRoll?.stage==='after-roll');const roll=game().currentRoll!;expect(roll.faces).toHaveLength(m.suffix==='wolf'?2:1);if(m.suffix==='wolf')damage=10+roll.total!;else hits=roll.total!;await page.reload();}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities'&&game().currentAttack?.attackerId===a);expect(game().currentAttack!.technique).toMatchObject({effectLevel:6,damage});expect(game().currentAttack!.technique.attributes).toEqual(expect.arrayContaining(['戦','剣','獣']));if(m.suffix.startsWith('maai')||m.suffix==='evade-restrict'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'}),select=reaction.getByRole('combobox',{name:'使うカード',exact:true});if(m.suffix==='evade-restrict'){expect(views.get(b)!.game!.currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);await expect(select.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);}else{await select.selectOption('a2-p06-r1c3');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));await until(()=>game().activeWindow?.kind!=='reclaim');expect(views.get(b)!.game!.maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});if(m.suffix==='maai-two'){await select.selectOption('a2-p07-r1c1');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));}}}}
  await until(()=>!game().activeWindow);const morale=views.get(b)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale').at(-1),guarded=m.guard&&(!m.dedicated||m.suffix==='nonbeast');if(guarded)expect(morale).toBeDefined();const blocked=guarded&&morale!.success||m.suffix==='maai-two';expect(game().players[b]!.damage).toBe(!success||blocked?0:damage*hits);expect(game().players[c]!.damage).toBe(m.coDedicated?34:0);expect(game().players[a]!.damage).toBe(0);if(m.guard){const survives=!success||blocked||m.suffix==='spirit';expect(own(b).followers).toHaveLength(survives?1:0);if(survives)expect(own(b).followers[0]!.revealed).toBe(success&&!['spirit','maai-two'].includes(m.suffix));}for(const id of [CARD,...(m.co?[m.co]:[])])expect((await storedDiscard()).filter(c=>c===id)).toHaveLength(1);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
