import {expect,test,type Locator} from '@playwright/test';
import {blackBreakScenarios,blackBreakCard as CARD,blackBreakMode} from '../../apps/worker/test/fixtures/black-break-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of blackBreakScenarios)test(`${scenario} actual near sword owner choice and reached white destruction survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=blackBreakMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<600;n++){if(done())return;await step();}throw Error('BLACK_BREAK_UI_LIMIT');}
  async function select(card:string){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(card)).getByRole('button').first().click();}
  async function target(){await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[b]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='noncounter'){await expect(page.getByRole('complementary',{name:'現在の判断'}).locator(`option[value="${CARD}"]`)).toHaveCount(0);await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='far'){await select('a2-p24-r1c3');await target();await click(page.getByRole('button',{name:'接近',exact:true}));await until(()=>!game().activeWindow);}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),rolls=game().recentRolls.map(r=>r.rollId),execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});await select(CARD);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await target();if(m.suffix==='wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await expect(execute).toBeEnabled();return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(m.suffix==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);return;}
  let success=true;if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?5:4,damage:m.dedicated?7:5,attributes:['戦','剣']});if(m.suffix==='maai'||m.suffix==='evade'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.suffix==='maai'?'a2-p06-r1c3':'a2-p05-r3c1');await click(reaction.getByRole('button',{name:m.suffix==='maai'?'間合いを使う':'防御する',exact:true}));}}
  await until(()=>!game().activeWindow);const avoided=['maai','evade'].includes(m.suffix),blocked=['nonwhite','wall-first'].includes(m.suffix),reduced=['lower','front-white','back-white'].includes(m.suffix);expect(game().players[b]!.damage).toBe(!success||avoided||blocked?0:reduced?5:m.dedicated?7:5);expect(game().players[c]!.damage).toBe(0);expect(own(c).followers).toEqual(cFollowers);if(avoided)expect(own(b).followers).toEqual(bFollowers);else if(blocked){expect(own(b).followers.map(f=>f.cardInstanceId)).toEqual(m.followers);expect(own(b).followers[0]!.revealed).toBe(true);if(m.suffix==='wall-first')expect(own(b).followers[1]!.revealed).toBe(false);}else{expect(own(b).followers).toEqual([]);for(const id of m.followers)expect(game().discard).toContain(id);}expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);if(m.suffix!=='low')expect(game().recentRolls.map(r=>r.rollId)).toEqual(rolls);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
