import {expect,test,type Locator} from '@playwright/test';
import {blackWingScenarios,blackWingCard as CARD,blackWingMode} from '../../apps/worker/test/fixtures/black-wing-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of blackWingScenarios)test(`${scenario} actual Black Wing Sword owner election targets followers and defenses survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=blackWingMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('BLACK_WING_UI_LIMIT');}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});
  if(scenario==='black-wing-stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(scenario==='black-wing-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),rolls=game().recentRolls.map(r=>r.rollId),targets=[b];
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);
  for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();
  if(scenario==='black-wing-wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(scenario==='black-wing-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);expect(game().discard).toContain(CARD);return;}
  let success=true;if(scenario==='black-wing-low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?6:5,damage:m.dedicated?10:7,attributes:['戦','剣']});if(scenario.includes('maai-')||scenario==='black-wing-evade'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'}),maai=scenario.includes('maai-');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(maai?'a2-p06-r1c3':'a2-p05-r3c1');await click(reaction.getByRole('button',{name:maai?'間合いを使う':'防御する',exact:true}));if(maai){await until(()=>game().activeWindow?.kind!=='reclaim');expect(views.get(b)!.game!.maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});await bp.reload();if(scenario.endsWith('-two')){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p07-r1c1');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));}}}}

  await until(()=>!game().activeWindow);for(const id of [b,c,d])expect(game().players[id]!.damage).toBe(!success||id===b&&(scenario.endsWith('-two')||scenario==='black-wing-evade')?0:targets.includes(id)&&(!m.guard||m.dedicated)?m.dedicated?10:7:0);if(m.dedicated){expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);}else if(m.guard)expect(own(b).followers[0]!.revealed).toBe(true);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);expect(game().phase).toBe('withdrawal');if(scenario!=='black-wing-low')expect(game().recentRolls.map(r=>r.rollId)).toEqual(rolls);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
