import {expect,test,type Locator} from '@playwright/test';
import {bloodFlowScenarios,bloodFlowCard as CARD,bloodFlowMode} from '../../apps/worker/test/fixtures/blood-flow-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of bloodFlowScenarios)test(`${scenario} actual Blood Flow chant per target resistance and added damage survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!,dp=table.pages[3]!,m=bloodFlowMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<750;n++){if(done())return;await step();}throw Error('BLOOD_FLOW_UI_LIMIT');}
  async function selectHand(){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('CHANT');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='noncounter'){await expect(page.getByRole('complementary',{name:'現在の判断'}).locator(`option[value="${CARD}"]`)).toHaveCount(0);await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).chants.some(c=>c.cardInstanceId===CARD)).toBe(true);return;}
  if(m.suffix.startsWith('chant-')){await selectHand();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await expect(page.getByRole('button',{name:'攻撃を確認して実行',exact:true})).toBeDisabled();const hand=[...own(a).hand],deck=game().deckCount;await click(page.getByRole('button',{name:'詠唱',exact:true}));expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);expect(own(a).chants[0]!.cardInstanceId).toBe(CARD);await page.reload();for(let n=0;n<200;n++){const g=game();if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;if(g.activeWindow){await step();continue;}const p=table.pages[g.turnSeat]!,label=g.phase==='action'?'行動を終える':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;expect(label).not.toBeNull();await click(p.getByRole('button',{name:label!,exact:true}));}}
  const hand=[...own(a).hand],deck=game().deckCount,rolls=game().recentRolls.map(r=>r.rollId),targets=m.targets.map(i=>ids[i]!),execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true}),unprepared=m.suffix==='good'||m.suffix.startsWith('unprepared');if(unprepared)await selectHand();else{expect(own(a).chants[0]!.cardInstanceId).toBe(CARD);await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'血流を選ぶ',exact:true}).click();}await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();if(m.suffix==='wrong-owner'||unprepared){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);if(m.suffix==='good'){await expect(page.getByRole('button',{name:'詠唱',exact:true})).toBeDisabled();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).check();await expect(page.getByRole('button',{name:'詠唱',exact:true})).toBeDisabled();}return;}
  await click(execute);expect(own(a).hand).toEqual(hand);expect(own(a).chants).toEqual([]);expect(game().deckCount).toBe(deck);await page.reload();
  if(m.suffix==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId))).toHaveLength(0);expect((await storedDiscard()).filter(c=>c===CARD)).toHaveLength(1);return;}
  let success=true,avoided=false;if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:8,damage:10,attributes:['戦','黒','詠']});if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.suffix.startsWith('evade')?'a2-p05-r3c1':'a2-p06-r1c3');await click(reaction.getByRole('button',{name:m.suffix.startsWith('evade')?'防御する':'間合いを使う',exact:true}));avoided=true;}}
  if(m.suffix.includes('force')||m.suffix==='reroll'){await until(()=>game().currentRoll?.purpose==='status-resistance');const rollId=game().currentRoll!.rollId,forced=m.suffix.includes('force'),reroll=m.suffix.includes('reroll');if(forced){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByLabel('割り込み効果').selectOption('force-fail');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));}await until(()=>game().currentRoll?.rollId===rollId&&game().currentRoll?.stage==='after-roll');if(forced)expect(views.get(b)!.game!.currentRoll!.success).toBe(false);if(reroll){await until(()=>game().activeWindow?.pendingActorId===c);const reaction=cp.getByRole('complementary',{name:'現在の判断'});await reaction.getByLabel('割り込み効果').selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===rollId&&game().currentRoll?.generation===1&&game().currentRoll?.stage==='after-roll');if(forced)expect(views.get(b)!.game!.currentRoll!.success).toBe(false);}}
  await until(()=>!game().activeWindow);const newRolls=game().recentRolls.filter(r=>!rolls.includes(r.rollId)),expectedRollers:string[]=[];for(const id of [b,c,d]){const morale=views.get(id)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale').at(-1),hit=success&&targets.includes(id)&&!(id===b&&(avoided||m.suffix==='water-equal'&&morale?.success)),resistance=views.get(id)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='status-resistance'&&r.rollerId===id).at(-1);if(hit){expectedRollers.push(id);expect(resistance).toBeDefined();expect(resistance!.faces).toHaveLength(2);expect(resistance!.modifier).toBe(m.dedicated?-3:-2);expect(resistance!.threshold).toBe(own(id).stats.spirit-(m.dedicated?3:2));expect(resistance!.success).toBe(!m.suffix.includes('force')&&resistance!.total!<=resistance!.threshold!);}expect(game().players[id]!.damage).toBe(hit?(id===b&&m.water&&morale?.success?6:10)+(resistance!.success?0:10):0);expect(game().players[id]!.skipsNextTurn).toBe(false);}expect(newRolls.filter(r=>r.purpose==='status-resistance').map(r=>r.rollerId)).toEqual(expectedRollers);expect((await storedDiscard()).filter(c=>c===CARD)).toHaveLength(1);expect(own(a).chants).toEqual([]);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
