import {expect,test,type Locator} from '@playwright/test';
import {closeEarthPhysicalMode,closeEarthPhysicalScenarios} from '../../apps/worker/test/fixtures/close-earth-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of closeEarthPhysicalScenarios)test(`${scenario} actual approach CHANT and target-local outcomes survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=closeEarthPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=300){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('CLOSE_EARTH_UI_LIMIT');}async function target(index:number){await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();}
 if(m.dragon){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));for(let n=0;n<160;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}const index=views.get(a)!.game!.self.hand.indexOf('a2-p24-r1c2');await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();await target(1);await click(page.getByRole('button',{name:'接近',exact:true}));await settle(g=>!g.activeWindow);expect(views.get(a)!.game!.distances[a]![b]).toBe('near');await page.reload();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:`${m.name}を選ぶ`,exact:true}).click();}else await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();for(const i of m.dragon?[1]:[1,2])await target(i);await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await settle(g=>g.activeWindow?.kind==='normal-defense');expect(views.get(a)!.game!.currentAttack!.defenseRestrictions.counterProhibited).toBe(m.dragon);if(m.dragon&&!m.teleport){for(const id of ['a2-p11-r1c3','a2-p12-r3c2'])await expect(table.pages[1]!.locator(`option[value="${id}"]`)).toHaveCount(0);}if(m.teleport){const bp=table.pages[1]!;await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c1');await click(bp.getByRole('button',{name:'防御する',exact:true}));await bp.reload();}await settle(g=>!g.activeWindow);await page.reload();const done=views.get(a)!.game!;expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.self.chants).toEqual([]);expect(done.players[b]!.damage).toBe(m.teleport?0:m.damage-5);expect(done.players[b]!.followers).toHaveLength(m.teleport?2:0);expect(done.players[c]!.damage).toBe(0);expect(done.players[c]!.followers).toHaveLength(m.dragon?1:0);
 }finally{await table.close();}
});
