import {expect,test,type Locator} from '@playwright/test';
import {getAction,getCharacter} from '../../packages/catalog/src/index.js';
import {conversionPhysicalScenarios,conversionMode} from '../../apps/worker/test/fixtures/conversion-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of conversionPhysicalScenarios)test(`${scenario} actual public target controls resistance and allegiance survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=conversionMode(scenario);const game=()=>views.get(a)!.game!,target=()=>views.get(b)!.game!.self;const profile=()=>{const p=target();return {faction:p.faction,objective:p.objective,currentObjective:p.currentObjective,protection:p.protection,defeatCondition:p.defeatCondition};};
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('CONVERSION_UI_LIMIT');}
 const before=profile(),targetHand=[...target().hand],hand=[...game().self.hand],deckCount=game().deckCount,name=getAction(m.card)!.name,panel=page.getByRole('region',{name:'対象を選ぶ手番カード'});if(scenario.endsWith('-decline')){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(game().self.hand).toContain(m.card);expect(profile()).toEqual(before);return;}
 if(scenario.endsWith('-hidden')){await expect(panel.getByRole('button',{name:name+'を使う',exact:true})).toHaveCount(0);await click(bp.getByRole('button',{name:'正体を公開',exact:true}));await until(()=>!game().activeWindow);}const select=panel.getByRole('combobox',{name:name+'の対象',exact:true});await expect(select.locator('option')).toHaveCount(1);expect(await select.locator('option').getAttribute('value')).toBe(b);await select.selectOption(b);await click(panel.getByRole('button',{name:name+'を使う',exact:true}));expect(game().self.hand).toEqual(hand.filter(id=>id!==m.card));expect(game().deckCount).toBe(deckCount);expect(profile()).toEqual(before);await page.reload();
 if(scenario.endsWith('-fate')){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().recentRolls.some(r=>r.purpose==='faction-change')).toBe(false);expect(profile()).toEqual(before);expect((await storedDiscard())).toContain(m.card);return;}
 await until(()=>game().currentRoll?.purpose==='faction-change');const id=game().currentRoll!.rollId;expect(game().currentRoll).toMatchObject({rollerId:b,kind:'check',formula:'2d6',stage:'before-roll'});await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.stage==='after-roll');const threshold=6-(m.dedicated?2:1)+(m.resist||scenario==='conversion-evil-same'?2:0);expect(game().currentRoll!.threshold).toBe(threshold);expect(game().currentRoll!.faces).toHaveLength(2);expect(game().currentRoll!.success).toBe(game().currentRoll!.total!<=threshold);expect(profile()).toEqual(before);await expect(bp.getByRole('region',{name:'サイコロの結果',exact:true})).toContainText(`判定値: ${threshold}以下`);await bp.reload();
 if(scenario.endsWith('-reroll')||scenario.endsWith('-forced')){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});if(scenario.endsWith('-forced')){await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('force-fail');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().activeWindow?.kind==='after-roll'&&game().activeWindow?.pendingActorId===d);expect(game().currentRoll!.forcedFailure).toBe(true);}await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.generation===1);expect(game().currentRoll!.attempts).toHaveLength(2);if(scenario.endsWith('-forced'))expect(game().currentRoll).toMatchObject({forcedFailure:true,success:false});await dp.reload();}
 const success=game().currentRoll!.success!;await until(()=>!game().activeWindow);if(success||m.fixed)expect(profile()).toEqual(before);else expect(profile()).toEqual({faction:m.faction,objective:(m.good?'EVIL':'GOOD')+'の全滅',currentObjective:{kind:'extinction',enemyFactions:[m.good?'EVIL':'GOOD']},protection:{characterIds:[m.protector]},defeatCondition:getCharacter(m.protector)!.name+'の死亡'});if(m.dead&&!success){expect(game().players[c]!.presence).toBe('dead');expect(game().players[b]!.presence).toBe('wandering');expect(target().hand).toEqual([]);expect(target().followers).toEqual([]);}else expect(target().hand).toEqual(targetHand);expect((await storedDiscard())).toContain(m.card);expect(game().phase).toBe('hand-adjustment');const saved=profile();await bp.reload();expect(profile()).toEqual(saved);expect(errors).toEqual([]);
 }finally{await table.close();}
});
