import {expect,test,type Locator} from '@playwright/test';
import {couragePhysicalScenarios,courageMode} from '../../apps/worker/test/fixtures/courage-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of couragePhysicalScenarios)test(`${scenario} actual Courage consent and original beneficiary reservation survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c]=ids as [string,string,string],page=table.pages[0]!,cp=table.pages[2]!,m=courageMode(scenario),owner=ids[m.owner]!,op=table.pages[m.owner]!,card='a2-p01-r3c3';const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function step(){const g=game(),w=g.activeWindow;if(w){const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));return;}const seat=g.turnSeat,p=table.pages[seat]!;if(g.phase==='hand-adjustment'){const v=views.get(ids[seat]!)!.game!.self,excess=Math.max(0,v.hand.length-v.stats.handLimit);for(const id of v.hand.filter(id=>id!==card).slice(0,excess))await select(seat,id);await click(p.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));return;}const label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;if(!label)throw Error('COURAGE_UI_PHASE');await click(p.getByRole('button',{name:label,exact:true}));}
 async function until(done:()=>boolean){for(let n=0;n<300;n++){if(done())return;await step();}throw Error('COURAGE_UI_LIMIT');}
 async function source(attackCard='a2-p24-r1c2'){await select(0,attackCard);await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await until(()=>game().activeWindow?.kind==='normal-defense');const o=views.get(b)!.game!.abilityOptions.find(o=>o.abilityId===m.abilityId)!;await click(table.pages[1]!.getByRole('button',{name:`${o.name}を使う`,exact:true}));}
 async function play(){await until(()=>views.get(owner)!.game!.anytimeCardOptions.some(o=>o.cardInstanceId===card));await op.reload();await click(op.getByRole('button',{name:'勇気を使う',exact:true}));await op.reload();}
 async function recover(){await until(()=>views.get(c)!.game!.reclaim?.cardInstanceId===card&&views.get(c)!.game!.reclaim?.pendingActorId===c);await cp.reload();const checker=cp.getByRole('region',{name:'カードの回収'}),requestButton=checker.getByRole('button',{name:'レスターとして回収判定をする',exact:true});if(scenario==='courage-reveal'){await expect(requestButton).toHaveCount(0);await click(cp.getByRole('button',{name:'正体を公開',exact:true}));}
  if(['courage-hidden','courage-check-decline','courage-stopped'].includes(scenario)){if(scenario!=='courage-check-decline')await expect(requestButton).toHaveCount(0);else await expect(requestButton).toBeEnabled();await click(checker.getByRole('button',{name:'回収せずに進む',exact:true}));return false;}
  await click(requestButton);const rollId=views.get(c)!.game!.currentRoll!.rollId;await cp.reload();await until(()=>views.get(c)!.game!.recentRolls.some(r=>r.rollId===rollId&&r.stage==='applied'));const roll=views.get(c)!.game!.recentRolls.find(r=>r.rollId===rollId)!;expect(roll.rollerId).toBe(c);expect(roll.success).toBe(scenario!=='courage-fail');if(!roll.success)return false;
  await op.reload();const recipient=op.getByRole('region',{name:'カードの回収'});expect(views.get(owner)!.game!.reclaim!.stage).toBe('beneficiary-choice');expect(views.get(owner)!.game!.reclaim!.pendingActorId).toBe(owner);if(owner!==c)await expect(checker.getByRole('button')).toHaveCount(0);if(scenario==='courage-user-decline'){await click(recipient.getByRole('button',{name:'回収せずに進む',exact:true}));return false;}await click(recipient.getByRole('button',{name:'勇気を回収する',exact:true}));expect(views.get(owner)!.game!.reservedCards).toContain(card);expect(views.get(owner)!.game!.self.hand).not.toContain(card);expect(game().discard).not.toContain(card);await op.reload();return true;
 }
 const prior=structuredClone(game().players[c]!.statuses),hand=views.get(owner)!.game!.self.hand.length;await source();const excluded=scenario==='courage-evil'||m.poem;let returned=false;
 if(excluded){await until(()=>game().activeWindow?.pendingActorId===owner);await expect(op.getByRole('button',{name:'勇気を使う',exact:true})).toHaveCount(0);}else{const before={...views.get(owner)!.game!.self.stats};await play();expect(views.get(owner)!.game!.self.hand).toHaveLength(hand);if(scenario==='courage-refill'){expect(game().players[owner]!.open).toContain('a2-p01-r1c3');expect(views.get(owner)!.game!.self.stats).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});}if(scenario==='courage-canceled'){await until(()=>game().activeWindow?.pendingActorId===a);const panel=page.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}else returned=await recover();}
 await until(()=>!game().activeWindow);await op.reload();if(excluded||scenario==='courage-canceled'){const roll=game().recentRolls.at(-1)!;expect(roll.purpose).toBe('ability-check');expect(game().players[b]!.damage).toBe(!roll.success||roll.faces![0]===roll.faces![1]?0:4);expect(game().recentRolls.some(r=>r.purpose==='activation')).toBe(false);}else expect(game().players[b]!.damage).toBe(4);expect(views.get(owner)!.game!.self.hand.includes(card)).toBe(excluded||returned);expect(views.get(owner)!.game!.reservedCards).not.toContain(card);if(returned){expect(views.get(owner)!.game!.self.hand).toHaveLength(hand+1);if(owner!==c)expect(views.get(c)!.game!.self.hand).not.toContain(card);}else if(!excluded)expect(game().discard.filter(id=>id===card)).toHaveLength(1);if(scenario==='courage-stopped')expect(game().players[c]!.statuses).toEqual(prior);
 if(scenario==='courage-later'){await until(()=>!game().activeWindow&&game().seatOrder[game().turnSeat]===a&&game().phase==='action');await source('a2-p24-r2c2');await play();expect(await recover()).toBe(true);await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(8);expect(game().recentRolls.filter(r=>r.purpose==='activation')).toHaveLength(2);expect(views.get(owner)!.game!.self.hand.filter(id=>id===card)).toHaveLength(1);}
 expect(errors).toEqual([]);
 }finally{await table.close();}
});
