import {expect,test,type Locator} from '@playwright/test';
import {observe,passUntil,tableFixture} from './helpers.js';
for(const scenario of ['curse-ordinary','curse-dedicated'] as const)for(const teleport of [false,true])test(`${scenario} actual chant teleport=${teleport} preserves mental follower pass and target scope`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,page=table.pages[0]!,defender=table.pages[1]!,dedicated=scenario.endsWith('dedicated');async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'呪殺',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await passUntil(table,views,v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}
 await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'呪殺を選ぶ',exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const index of dedicated?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='normal-defense'&&g.activeWindow.pendingActorId===b);expect(views.get(b)!.game!.currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:true,evadeProhibited:true,counterProhibited:false});let hit=true;
 if(teleport){await defender.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c1');await defender.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await click(defender.getByRole('button',{name:'防御する',exact:true}));await passUntil(table,views,g=>g.currentRoll?.purpose==='teleport'&&g.currentRoll.stage==='after-roll');await defender.reload();hit=!views.get(b)!.game!.currentRoll!.success;}
 await passUntil(table,views,g=>!g.activeWindow,350);await page.reload();const done=views.get(a)!.game!;expect([done.players[a]!.damage,done.players[b]!.damage]).toEqual([0,hit?14:0]);expect(done.players[a]!.followers).toEqual([]);expect(done.players[b]!.followers).toHaveLength(1);expect(done.players[b]!.followers[0]!.face).toBe('back');expect(done.players[table.sessions[2]!.id]!.damage).toBe(dedicated?13:0);expect(done.self.chants).toEqual([]);
 }finally{await table.close();}
});
