import {expect,test,type Locator} from '@playwright/test';
import {dawnPhysicalScenarios} from '../../apps/worker/test/fixtures/dawn-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of dawnPhysicalScenarios)test(`${scenario} actual Dawn reveal shuffle and preserved otherworld possessions survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c]=ids as [string,string,string],source=scenario==='dawn-return'?c:a,page=table.pages[ids.indexOf(source)]!;const game=()=>views.get(a)!.game!,before=structuredClone(views.get(b)!.game!.self),beforeDamage=game().players[b]!.damage,beforeAttachments=[...game().players[b]!.attachments];
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function settle(stop?:string){for(let n=0;n<200;n++){const w=game().activeWindow;if(!w||w.kind===stop)return;const id=w.pendingActorId!,p=table.pages[ids.indexOf(id)]!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(p.getByRole('button',{name:w.kind==='revival'?'復活しない':windowPassButtonName}));}throw Error('DAWN_UI_WINDOW');}
 await click(page.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:'秘伝書を使う',exact:true}));await page.reload();await settle('reclaim');expect(game().players[source]!.open).toContain('a2-p01-r1c2');expect((await storedDiscard())).toEqual([]);if(scenario==='dawn-return'){expect(game().players[b]!.presence).toBe('active');const after=views.get(b)!.game!.self;for(const key of ['hand','followers','chants'] as const)expect(after[key]).toEqual(before[key]);expect(game().players[b]!.damage).toBe(beforeDamage);expect(game().players[b]!.attachments).toEqual(beforeAttachments);expect(game().logs.filter(e=>e.type==='PLAYER_RETURNED'&&e.actorId===b)).toHaveLength(1);}if(scenario==='dawn-deaths')for(const id of [b,c])expect(game().players[id]!.presence).toBe('dead');await page.reload();await settle();await page.reload();expect((await storedDiscard())).toEqual(['a2-p03-r1c1']);expect(game().phase).toBe('action');expect(game().players[source]!.open.filter(id=>id==='a2-p01-r1c2')).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
