import {expect,test,type Locator} from '@playwright/test';
import {deathSongPhysicalMode,deathSongPhysicalScenarios} from '../../apps/worker/test/fixtures/death-song-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of deathSongPhysicalScenarios)test(`${scenario} actual CHANT selected cast and Gadyura resistance survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=deathSongPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=300){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('DEATH_SONG_UI_LIMIT');}async function target(index:number){await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();}
 {await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));for(let n=0;n<160;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}await page.reload();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:`${m.name}を選ぶ`,exact:true}).click();}await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const i of m.dedicated?[1,2]:[1])await target(i);await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await settle(g=>g.activeWindow?.kind==='normal-defense');expect(views.get(a)!.game!.currentAttack!.defenseRestrictions.counterProhibited).toBe(m.dedicated);const damage=views.get(a)!.game!.currentAttack!.technique.damage!;expect(damage).toBeGreaterThanOrEqual(m.dedicated?21:4);expect(damage).toBeLessThanOrEqual(m.dedicated?21:24);if(m.teleport){const bp=table.pages[1]!;await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c1');await click(bp.getByRole('button',{name:'防御する',exact:true}));await bp.reload();}await settle(g=>!g.activeWindow);await page.reload();const done=views.get(a)!.game!;expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.self.chants).toEqual([]);expect(done.players[b]!.damage).toBe(m.teleport||m.gad&&!m.fail?0:damage);expect(done.players[b]!.followers).toHaveLength(2);expect(done.players[c]!.damage).toBe(m.dedicated?damage:0);expect(done.players[c]!.followers).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
