import type {Browser,APIRequestContext} from '@playwright/test';
import {expect,test,type Locator} from '@playwright/test';
import {deathGiftPhysicalScenarios,deathGiftMode} from '../../apps/worker/test/fixtures/death-gift-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
async function verifyDeathGift(browser:Browser,request:APIRequestContext,scenario:typeof deathGiftPhysicalScenarios[number]){
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=deathGiftMode(scenario),target=m.batch?d:c;const game=()=>views.get(a)!.game!,self=(id:string)=>views.get(id)!.game!.self;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}throw Error('DEATH_GIFT_UI_LIMIT');}
 const hand=[...self(b).hand],recipient=[...self(target).hand],deckCount=game().deckCount;expect(game().players[b]!.presence).toBe('pending-death');expect(self(b).faction).toBe(m.evil?'EVIL':'GOOD');const panel=bp.getByRole('complementary',{name:'死亡時の贈与'});await expect(panel).toBeVisible();for(const p of [page,table.pages[2]!,dp])await expect(p.getByRole('combobox',{name:'死亡時に使うカード',exact:true})).toHaveCount(0);
 const source=panel.getByRole('combobox',{name:'死亡時に使うカード',exact:true}),gift=panel.getByRole('combobox',{name:'相手に託す手札',exact:true}),receiver=panel.getByRole('combobox',{name:'カードを託す相手',exact:true});expect(await source.locator('option').evaluateAll(opts=>opts.map(o=>(o as HTMLOptionElement).value))).toEqual(['',m.card]);expect(await receiver.locator('option').evaluateAll(opts=>opts.map(o=>(o as HTMLOptionElement).value))).toEqual(['',...(m.batch?[a,d]:[a,c,d])]);await expect(panel.getByRole('button',{name:'選んだ手札を託す',exact:true})).toBeDisabled();await expect(panel.getByText('この使用による手札補充はありません。',{exact:false})).toBeVisible();
 if(m.decline){await click(panel.getByRole('button',{name:'託さずに進む',exact:true}));await until(()=>!game().activeWindow);expect(game().discard).toEqual(expect.arrayContaining(hand));expect(game().logs.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);return;}
 async function ability(){const section=panel.getByRole('region',{name:'みんな姫様を頼むね'});await section.getByRole('combobox',{name:'能力で託す手札',exact:true}).selectOption(m.second);await section.getByRole('combobox',{name:'能力で託す相手',exact:true}).selectOption(d);await click(section.getByRole('button',{name:'能力で手札を託す',exact:true}));await until(()=>game().activeWindow?.kind==='death-gift');expect(self(d).hand).toContain(m.second);await bp.reload();await expect(panel).toBeVisible();}
 if(m.abilityFirst)await ability();await source.selectOption(m.card);expect(await gift.locator('option').evaluateAll(opts=>opts.map(o=>(o as HTMLOptionElement).value))).not.toContain(m.card);await gift.selectOption(m.gift);await receiver.selectOption(target);await click(panel.getByRole('button',{name:'選んだ手札を託す',exact:true}));expect(self(b).hand).toEqual(hand.filter(id=>id!==m.card&&(!m.abilityFirst||id!==m.second)));expect(self(target).hand).toEqual(recipient);expect(game().deckCount).toBe(deckCount);for(const id of [a,c,d])expect(JSON.stringify(views.get(id)!.game)).not.toContain(m.gift);await bp.reload();
 if(m.fate){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));}await until(()=>game().activeWindow?.kind==='death-gift');expect(game().players[b]!.presence).toBe('pending-death');expect(game().discard).toContain(m.card);expect(game().discard).not.toContain(m.gift);expect(self(b).hand.includes(m.gift)).toBe(m.fate);expect(self(target).hand).toEqual(m.fate?recipient:[...recipient,m.gift]);if(!m.fate){expect(self(target).hand.length).toBeGreaterThan(self(target).stats.handLimit);for(const id of ids){const v=views.get(id)!.game!;expect(v.logs.filter(e=>e.type==='CARD_GIFTED').every(e=>e.cardInstanceId===undefined)).toBe(true);if(id===b||id===target)expect(v.privateLogs.some(e=>e.type==='CARD_GIFTED'&&e.cardInstanceId===m.gift)).toBe(true);else expect(JSON.stringify(v)).not.toContain(m.gift);}}else expect(game().logs.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);await table.pages[ids.indexOf(target)]!.reload();
 if(m.ability&&!m.abilityFirst)await ability();const residual=[...self(b).hand];await until(()=>!game().activeWindow);expect(game().players[b]!.presence).toBe('dead');expect(self(b).hand).toEqual([]);expect(game().discard).toEqual(expect.arrayContaining([m.card,...residual]));if(m.protection){expect(game().players[c]!.presence).toBe('wandering');expect(self(c).hand).toEqual([]);}else if(m.fate)expect(game().discard).toContain(m.gift);else expect(self(target).hand).toContain(m.gift);if(m.ability)expect(self(d).hand).toContain(m.second);await page.reload();expect(game().activeWindow).toBeNull();expect(errors).toEqual([]);
 }finally{await table.close();}
}
for(const scenario of deathGiftPhysicalScenarios.filter(s=>!s.endsWith('-first')))test(`${scenario} actual death gift selectors privacy cancellation and independent abilities survive reload`,async({browser,request})=>{await verifyDeathGift(browser,request,scenario);});
test('S25 death-gift-good-ability-first actual death gift selectors privacy and independent abilities survive reload',async({browser,request})=>{await verifyDeathGift(browser,request,'death-gift-good-ability-first');});
test('S25 death-gift-good-printed-first actual death gift selectors privacy and independent abilities survive reload',async({browser,request})=>{await verifyDeathGift(browser,request,'death-gift-good-printed-first');});
test('S25 death-gift-evil-ability-first actual death gift selectors privacy and independent abilities survive reload',async({browser,request})=>{await verifyDeathGift(browser,request,'death-gift-evil-ability-first');});
test('S25 death-gift-evil-printed-first actual death gift selectors privacy and independent abilities survive reload',async({browser,request})=>{await verifyDeathGift(browser,request,'death-gift-evil-printed-first');});
