import {expect,test,type Locator} from '@playwright/test';
import {dinonPhysicalScenarios,dinonCard} from '../../apps/worker/test/fixtures/dinon-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of dinonPhysicalScenarios)test(`${scenario} actual target selection hand exchange private ownership and excess survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!;const game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('DINON_UI_LIMIT');}
 const target=scenario==='dinon-self'?a:b,originalA=[...own(a).hand],originalB=[...own(b).hand],deckCount=game().deckCount,zone=(id:string)=>({open:[...game().players[id]!.open],attachments:[...game().players[id]!.attachments],followers:structuredClone(own(id).followers),chants:structuredClone(own(id).chants)}),az=zone(a),bz=zone(b);if(scenario==='dinon-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toEqual(originalA);expect(own(b).hand).toEqual(originalB);return;}
 const panel=page.getByRole('region',{name:'対象を選ぶ手番カード'}),select=panel.getByRole('combobox',{name:'ディノンの書の対象',exact:true});await expect(select.locator('option')).toHaveCount(4);await select.selectOption(target);await click(panel.getByRole('button',{name:'ディノンの書を使う',exact:true}));expect(own(a).hand).toEqual(originalA.filter(id=>id!==dinonCard));expect(own(b).hand).toEqual(originalB);expect(game().deckCount).toBe(deckCount);await page.reload();
 if(scenario==='dinon-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(own(a).hand).toEqual(originalA.filter(id=>id!==dinonCard));expect(own(b).hand).toEqual(originalB);expect((await storedDiscard())).toContain(dinonCard);return;}
 if(scenario==='dinon-source-refill'||scenario==='dinon-target-refill'){const owner=scenario==='dinon-source-refill'?a:b,recipient=owner===a?b:a,old=[...own(owner).hand];await until(()=>game().activeWindow?.pendingActorId===owner);const o=views.get(owner)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId===recipient)!;await click(table.pages[ids.indexOf(owner)]!.getByRole('button',{name:o.label,exact:true}));expect(own(owner).hand).toHaveLength(old.length);expect(own(owner).hand).not.toEqual(old);}
 const ah=[...own(a).hand],bh=[...own(target).hand],remainingDeck=game().deckCount;await until(()=>!game().activeWindow);expect(own(a).hand).toEqual(bh);expect(own(target).hand).toEqual(ah);expect(game().deckCount).toBe(remainingDeck);expect((await storedDiscard())).toContain(dinonCard);expect(game().phase).toBe('hand-adjustment');expect(zone(a)).toEqual(az);expect(zone(b)).toEqual(bz);for(const id of [c,d]){expect(views.get(id)!.game!.players[a]).not.toHaveProperty('hand');expect(views.get(id)!.game!.players[b]).not.toHaveProperty('hand');}await page.reload();await bp.reload();expect(own(a).hand).toEqual(bh);expect(own(target).hand).toEqual(ah);
 if(scenario.startsWith('dinon-overflow-')){const receiver=scenario==='dinon-overflow-source'?a:b,rp=table.pages[ids.indexOf(receiver)]!;expect(own(receiver).hand).toHaveLength(8);if(receiver===b){await click(page.getByRole('button',{name:'選んだ0枚を捨てて手番を終える',exact:true}));await until(()=>!game().activeWindow);await click(bp.getByRole('button',{name:'手番を始める',exact:true}));await until(()=>!game().activeWindow);await click(bp.getByRole('button',{name:'カードを引かない',exact:true}));expect(own(b).hand).toHaveLength(8);await click(bp.getByRole('button',{name:'行動を終える',exact:true}));}const end=rp.getByRole('button',{name:'選んだ3枚を捨てて手番を終える',exact:true});await expect(end).toBeDisabled();const drop=own(receiver).hand.slice(0,3);for(const id of drop){const i=own(receiver).hand.indexOf(id);await rp.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(i).getByRole('button').first().click();}await click(end);await until(()=>!game().activeWindow);expect(own(receiver).hand).toHaveLength(5);for(const id of drop)expect((await storedDiscard())).toContain(id);await rp.reload();expect(own(receiver).hand).toHaveLength(5);}expect(errors).toEqual([]);
 }finally{await table.close();}
});
