import {expect,test,type Locator} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {dispelPhysicalScenarios,dispelMode} from '../../apps/worker/test/fixtures/dispel-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of dispelPhysicalScenarios)test(`${scenario} actual pre-attack Dispel privacy payment and resumption survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=dispelMode(scenario),card='a2-p02-r3c1',target=ids[m.target]!,other=m.target===2?b:c,attacker=m.defense?1:0,ap=table.pages[attacker]!;const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('DISPEL_UI_LIMIT');}
 function parentVisible(){const action=game().currentAction;return !!action&&'cardInstanceId' in action&&action.cardInstanceId===m.attack&&action.kind==='attack';}
 const original=structuredClone(table.expected!.players[target]!),untouched=structuredClone(game().players[other]!.followers),hand=game().self.hand.length,deckCount=game().deckCount,destroyed=original.followers.filter(f=>['a2-p19-r2c3','a2-p20-r2c3','a2-p22-r1c1'].includes(f.cardInstanceId)),remaining=original.followers.filter(f=>!destroyed.includes(f));
 if(m.multi)await ap.getByRole('region',{name:'自分の詠唱'}).getByRole('button',{name:`${getAction(m.attack)!.name}を選ぶ`,exact:true}).click();else{const index=views.get(ids[attacker]!)!.game!.self.hand.indexOf(m.attack);expect(index).toBeGreaterThanOrEqual(0);await ap.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}if(m.multi||m.cost)await ap.getByRole('checkbox',{name:'専用技として使う',exact:true}).check();if(m.cost)await ap.getByRole('group',{name:'消費する踏み込み'}).getByRole('checkbox',{name:getAction('a2-p24-r1c3')!.name,exact:true}).check();for(const seat of m.defense?[0]:m.multi?[1,2]:[1])await ap.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:ap.getByRole('heading',{name:table.sessions[seat]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();if(!m.defense){const selector=ap.getByRole('combobox',{name:'呪払の対象',exact:true});await expect(selector).toBeVisible();await expect(ap.getByText('呪払の使用では手札を補充しません。',{exact:false})).toBeVisible();if(scenario!=='dispel-decline')await selector.selectOption(target);}await click(ap.getByRole('button',{name:'攻撃を確認して実行',exact:true}));
 if(m.defense){await until(()=>game().activeWindow?.kind==='normal-defense');expect(game().anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);await expect(page.getByRole('combobox',{name:'呪払の対象',exact:true})).toHaveCount(0);await until(()=>!game().activeWindow);expect(game().self.hand).toContain(card);expect(game().players[a]!.damage).toBe(4);return;}
 expect(game().self.hand).toHaveLength(hand-(scenario==='dispel-decline'?1:m.multi?1:m.cost?3:2));expect(game().deckCount).toBe(deckCount);await page.reload();if(scenario==='dispel-decline'){expect(game().self.hand).toContain(card);expect(game().players[target]!.followers).toHaveLength(original.followers.length);await until(()=>!game().activeWindow);return;}
 expect(game().currentAttack).toBeNull();expect(views.get(b)!.game!.anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2')).toBe(false);if(scenario==='dispel-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const panel=dp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}await until(()=>game().activeWindow?.kind==='declaration'&&parentVisible());
 const kept=scenario==='dispel-fate'?original.followers:remaining;expect(game().players[target]!.followers).toEqual(kept.map((_,position)=>({position,face:'back'})));expect(game().players[other]!.followers).toEqual(untouched);for(const id of ids){const v=views.get(id)!.game!;expect(v.logs.filter(e=>e.type==='FOLLOWER_DESTROYED').map(e=>e.cardInstanceId)).toEqual(scenario==='dispel-fate'?[]:destroyed.map(f=>f.cardInstanceId));if(id!==target)for(const f of kept)expect(JSON.stringify(v)).not.toContain(f.cardInstanceId);}await page.reload();expect(game().players[target]!.followers).toHaveLength(kept.length);
 if(scenario==='dispel-parent-cancel'){await until(()=>views.get(b)!.game!.anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2'));await click(bp.getByRole('button',{name:'人質を使う',exact:true}));}else if(scenario==='dispel-attack-fate'){await until(()=>game().activeWindow?.kind==='declaration'&&game().activeWindow!.pendingActorId===d);const panel=dp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}else{await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.targetIds).toEqual(m.multi?[b,c]:[b]);}await until(()=>!game().activeWindow);expect(game().phase).toBe('withdrawal');expect(game().discard.filter(id=>id===card)).toHaveLength(1);if(scenario!=='dispel-fate')for(const f of destroyed)expect(game().discard).toContain(f.cardInstanceId);if(m.cost)expect(game().discard).toContain('a2-p24-r1c3');await page.reload();expect(game().currentAttack).toBeNull();expect(errors).toEqual([]);
 }finally{await table.close();}
});
