import {expect,test,type Locator} from '@playwright/test';
import {dragonCultPhysicalMode,dragonCultPhysicalScenarios} from '../../apps/worker/test/fixtures/dragon-cult-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of dragonCultPhysicalScenarios)test(`${scenario} actual Dragon Cult defense or attack survives reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=dragonCultPhysicalMode(scenario),errors:string[]=[],SK='a2-p21-r3c1';for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!,bp=table.pages[1]!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const current=views.get(a)!,g=current.game!,w=g.activeWindow;if(!w||w.kind===stop)return;const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('CULT_UI_LIMIT');}
 async function select(seat:number,id:string){const p=table.pages[seat]!,who=table.sessions[seat]!.id,index=views.get(who)!.game!.self.hand.indexOf(id);expect(index).toBeGreaterThanOrEqual(0);await p.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function target(seat:number,to:number){const p=table.pages[seat]!;await p.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:p.getByRole('heading',{name:table.sessions[to]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();}
 if(m.initial){await select(0,SK);await click(page.getByRole('button',{name:'従者を置く',exact:true}));await page.reload();}for(let i=0;i<4;i++)await click(table.pages[i]!.getByRole('button',{name:'従者を置かず進む',exact:true}));await click(page.getByRole('button',{name:'手番を始める',exact:true}));await click(page.getByRole('button',{name:'カードを引かない',exact:true}));
 if(m.defense){if(!m.initial){const panel=page.getByRole('region',{name:'従者の配置',exact:true});await panel.getByRole('combobox',{name:'従者を加える',exact:true}).selectOption(SK);await click(panel.getByRole('button',{name:'この順番で確定',exact:true}));await page.reload();}for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle();continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===b)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}
 if(m.white){await select(1,'a2-p14-r1c3');await bp.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.whiteLevel>=7);await target(1,0);await click(bp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}else{const panel=bp.getByRole('region',{name:'複数従者の攻撃'});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption('c2-p06-r1c2-ab04');await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption('a2-p21-r2c3');await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await panel.getByRole('radio',{name:table.sessions[0]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));}
 if(m.white&&m.whiteLevel===8){await settle('effect-level');while(views.get(a)!.game!.activeWindow!.pendingActorId!==b){const who=views.get(a)!.game!.activeWindow!.pendingActorId!;await click(table.pages[table.sessions.findIndex(p=>p.id===who)]!.getByRole('button',{name:windowPassButtonName}));}const panel=bp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('effect-plus');await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p05-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}
 if(m.waive){await settle('normal-defense');await page.getByRole('checkbox',{name:'竜王教団の専用効果を使う',exact:true}).check();await click(page.getByRole('button',{name:'従者で受ける',exact:true}));}}
 else{if(m.army){const panel=page.getByRole('region',{name:'全軍突撃せよ',exact:true});await panel.getByRole('combobox',{name:'突撃に使う従者',exact:true}).selectOption(SK);await panel.getByRole('radio',{name:table.sessions[1]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'2枚を使って全軍突撃する',exact:true}));}else if(m.grant){const panel=page.getByRole('region',{name:'複数従者の攻撃'});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption('c2-p06-r1c2-ab04');await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption(SK);await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await panel.getByRole('radio',{name:table.sessions[1]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));}else{const panel=page.getByRole('region',{name:'従者による攻撃',exact:true});await panel.getByRole('combobox',{name:'攻撃に使う従者',exact:true}).selectOption(SK);await panel.getByRole('checkbox',{name:'専用の攻撃として使う',exact:true}).check();for(const i of [1,2])await panel.getByRole('checkbox',{name:table.sessions[i]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'従者で攻撃する',exact:true}));}}
 await page.reload();await settle();await page.reload();const done=views.get(a)!.game!,alive=m.defense&&!m.fail&&(m.white?m.whiteLevel<7:m.attackLevel<(m.waive?6:5));let damage=0;if(!m.defense){const rolls=done.recentRolls.filter(r=>r.purpose==='attack-damage');expect(rolls).toHaveLength(1);const roll=rolls[0]!;expect(roll.formula).toBe('2d6');expect(roll.faces).toHaveLength(2);damage=roll.faces.reduce((sum,face)=>sum+face,0);expect(damage).toBeGreaterThanOrEqual(2);expect(damage).toBeLessThanOrEqual(12);}
 expect([done.players[a]!.damage,done.players[b]!.damage,done.players[c]!.damage]).toEqual(m.defense?[m.white?m.whiteLevel>7?10:0:m.fail||m.attackLevel>(m.waive?6:5)?18:0,0,0]:[0,damage,m.dedicated?damage:0]);expect(done.self.followers.map(f=>f.cardInstanceId)).toEqual(alive?[SK]:[]);expect(done.self.hand).not.toContain(SK);expect((await storedDiscard()).filter(x=>x===SK)).toHaveLength(alive?0:1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
