import {expect,test,type Locator} from '@playwright/test';
import {dragonKingScenarios,dragonKingCard as CARD,dragonKingMaai as MAAI,dragonKingMode} from '../../apps/worker/test/fixtures/dragon-king-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of dragonKingScenarios)test(`${scenario} actual Dragon King shared die per target resistance and next turn survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!,dp=table.pages[3]!,m=dragonKingMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<750;n++){if(done())return;await step();}throw Error('DRAGON_KING_UI_LIMIT');}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='noncounter'){await expect(page.getByRole('complementary',{name:'現在の判断'}).locator(`option[value="${CARD}"]`)).toHaveCount(0);await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).hand).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,rolls=game().recentRolls.map(r=>r.rollId),targets=m.targets.map(i=>ids[i]!),execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();if(m.suffix==='wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(m.suffix==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().players[b]!.skipsNextTurn).toBe(false);expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId))).toHaveLength(0);expect(game().discard.filter(c=>c===CARD)).toHaveLength(1);return;}
  let success=true,required=1,avoided=false;if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(m.dedicated){await until(()=>game().currentRoll?.purpose==='technique-value');const r=game().currentRoll!;expect(r.formula).toBe('d6');expect(r.faces).toHaveLength(1);required=1+r.total!;if(m.suffix==='reroll'){await until(()=>game().activeWindow?.pendingActorId===c);const reaction=cp.getByRole('complementary',{name:'現在の判断'});await reaction.getByLabel('割り込み効果').selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===r.rollId&&game().currentRoll?.generation===1&&game().currentRoll?.stage==='after-roll');required=1+game().currentRoll!.total!;}}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:8,damage:10,attributes:['戦','剣']});if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});if(m.suffix.startsWith('evade')){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p05-r3c1');await click(reaction.getByRole('button',{name:'防御する',exact:true}));avoided=true;}else{const paid=Math.min(required-(m.suffix==='maai-short'?1:0),5);for(const [i,id] of MAAI.slice(0,paid).entries()){await until(()=>game().activeWindow?.kind==='normal-defense');await expect(bp.getByRole('region',{name:'間合いの状況',exact:true})).toContainText(`必要${required}枚・有効${i}枚・あと${required-i}枚`);await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(id);await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));expect(own(b).hand).not.toContain(id);}avoided=paid===required;}}}
  await until(()=>!game().activeWindow);const newRolls=game().recentRolls.filter(r=>!rolls.includes(r.rollId));for(const id of [b,c,d]){const hit=success&&targets.includes(id)&&!(id===b&&avoided),resistance=views.get(id)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='hit-resistance'&&r.rollerId===id).at(-1),morale=views.get(id)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale').at(-1);if(hit&&m.dedicated){expect(resistance).toBeDefined();expect(resistance!.faces).toHaveLength(2);expect(resistance!.threshold).toBe(6);expect(resistance!.success).toBe(resistance!.total!<=6);}expect(game().players[id]!.damage).toBe(hit?(id===b&&m.water&&morale?.success?6:10)*(m.dedicated&&!resistance!.success?3:1):0);expect(game().players[id]!.skipsNextTurn).toBe(hit&&m.dedicated);}expect(newRolls.filter(r=>r.purpose==='technique-value')).toHaveLength(m.dedicated?1:0);expect(newRolls.filter(r=>r.purpose==='hit-resistance')).toHaveLength(m.dedicated?targets.length-(avoided?1:0):0);expect(game().discard.filter(c=>c===CARD)).toHaveLength(1);await bp.reload();
  if(['pair','all','resistance-fail'].includes(m.suffix)){for(const id of targets)await expect(table.pages[ids.indexOf(id)]!.getByRole('region',{name:`${game().players[id]!.name}の状態異常`,exact:true})).toContainText('次の手番を飛ばします');if(game().phase==='withdrawal')await click(page.getByRole('button',{name:'離脱しない',exact:true}));await click(page.getByRole('button',{name:'選んだ0枚を捨てて手番を終える',exact:true}));await until(()=>!game().activeWindow);for(const id of targets){const beforeHand=[...own(id).hand],beforeDeck=game().deckCount,beforeRolls=structuredClone(game().recentRolls),p=table.pages[ids.indexOf(id)]!;await click(p.getByRole('button',{name:'手番を始める',exact:true}));expect(game().phase).toBe('turn-start');expect(game().seatOrder[game().turnSeat]).not.toBe(id);expect(game().players[id]!.skipsNextTurn).toBe(false);expect(own(id).hand).toEqual(beforeHand);expect(game().deckCount).toBe(beforeDeck);expect(game().recentRolls).toEqual(beforeRolls);await p.reload();await expect(p.getByRole('button',{name:'カードを引かない',exact:true})).toHaveCount(0);}}
  expect(errors).toEqual([]);
 }finally{await table.close();}
});
