import {expect,test,type Locator} from '@playwright/test';
import {getCharacter} from '../../packages/catalog/src/index.js';
import {farseeingPhysicalScenarios,farseeingMode,farseeingCard,astrologyAbility} from '../../apps/worker/test/fixtures/farseeing-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of farseeingPhysicalScenarios)test(`${scenario} actual ordinary or astrology controls private information choice and history survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,dp=table.pages[3]!,m=farseeingMode(scenario),target=m.self?a:b;const game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('FARSEEING_UI_LIMIT');}
 const original=[...own(a).hand],identity=own(target).characterId,revealed=game().players[target]!.revealed,followers=structuredClone(own(target).followers),deckCount=game().deckCount;if(scenario==='farseeing-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toEqual(original);return;}const panel=page.getByRole('region',{name:'対象を選ぶ手番カード'});await expect(panel.getByRole('button',{name:'遠見の水晶球を使う',exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'遠見の水晶球で占星する',exact:true})).toHaveCount(m.alseil?1:0);await panel.getByRole('combobox',{name:'遠見の水晶球の対象',exact:true}).selectOption(target);await click(panel.getByRole('button',{name:m.astrology?'遠見の水晶球で占星する':'遠見の水晶球を使う',exact:true}));expect(own(a).hand).toEqual(original.filter(id=>id!==farseeingCard));expect(game().deckCount).toBe(deckCount);const targetHand=[...own(target).hand];await page.reload();
 if(m.fate){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().recentRolls.some(r=>r.purpose==='card-inspection')).toBe(false);expect(game().privateLogs.some(e=>e.type==='CHARACTER_INSPECTED')).toBe(false);expect(own(target).hand).toEqual(targetHand);expect((await storedDiscard())).toContain(farseeingCard);return;}
 let success=true;if(!m.astrology){await until(()=>game().currentRoll?.purpose==='card-inspection');const id=game().currentRoll!.rollId;expect(game().currentRoll).toMatchObject({rollerId:a,kind:'check',formula:'2d6',stage:'before-roll'});await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);expect(game().currentRoll!.success).toBe(game().currentRoll!.total!<=6);await expect(page.getByRole('region',{name:'サイコロの結果',exact:true})).toContainText('判定値: 6以下');if(scenario==='farseeing-forced'||scenario==='farseeing-reroll'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});if(scenario==='farseeing-forced'){await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('force-fail');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().activeWindow?.kind==='after-roll'&&game().activeWindow?.pendingActorId===d);}await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.generation===1);if(scenario==='farseeing-forced')expect(game().currentRoll).toMatchObject({forcedFailure:true,success:false});}success=game().currentRoll!.success!;}
 let drop:string|undefined;if(success){await until(()=>!!game().inspection);const choice=page.getByRole('complementary',{name:'自分だけの確認内容',exact:true}),decision=structuredClone(game().inspection!);await expect(choice).toBeVisible();for(const id of [b,c,d]){expect(views.get(id)!.game!.inspection).toBeNull();await expect(table.pages[ids.indexOf(id)]!.getByRole('complementary',{name:'自分だけの確認内容',exact:true})).toHaveCount(0);}await page.reload();expect(game().inspection).toEqual(decision);if(m.astrology){expect(decision).toMatchObject({zone:'hand',cards:targetHand.map((cardInstanceId,position)=>({cardInstanceId,position}))});expect(decision).not.toHaveProperty('characterId');expect(game().recentRolls.some(r=>r.purpose==='card-inspection')).toBe(false);await expect(choice.getByRole('radio')).toHaveCount(targetHand.length);if(m.discard){drop=targetHand[0]!;await expect(choice.getByRole('button',{name:'選んだ1枚を捨てさせる',exact:true})).toBeDisabled();await choice.getByRole('radio').first().check();await click(choice.getByRole('button',{name:'選んだ1枚を捨てさせる',exact:true}));}else await click(choice.getByRole('button',{name:'確認を終える',exact:true}));}else{expect(decision).toMatchObject({zone:'character',characterId:identity,cards:[]});await expect(choice.getByRole('button',{name:getCharacter(identity)!.name,exact:true})).toBeVisible();await click(choice.getByRole('button',{name:'確認を終える',exact:true}));}}
 await until(()=>!game().activeWindow);expect(own(target).hand).toEqual(targetHand.filter(id=>id!==drop));expect(game().players[target]!.revealed).toBe(revealed);expect(own(target).followers).toEqual(followers);expect((await storedDiscard())).toContain(farseeingCard);if(drop)expect((await storedDiscard())).toContain(drop);expect(game().phase).toBe('hand-adjustment');if(!m.astrology){expect(game().privateLogs.some(e=>e.type==='CHARACTER_INSPECTED'&&e.characterId===identity)).toBe(success);if(success)await expect(page.getByRole('region',{name:'自分だけの正体確認履歴',exact:true})).toContainText(getCharacter(identity)!.name);}else expect(game().privateLogs.some(e=>e.type==='CHARACTER_INSPECTED')).toBe(false);await page.reload();expect(own(target).hand).toEqual(targetHand.filter(id=>id!==drop));
 if(scenario==='farseeing-astrology-after'){expect(game().abilityOptions.some(o=>o.abilityId===astrologyAbility)).toBe(true);const ability=page.locator('.panel').filter({has:page.getByRole('heading',{name:'占星',exact:true})});await ability.getByRole('combobox',{name:'能力の対象',exact:true}).selectOption(b);await click(ability.getByRole('button',{name:'占星を使う',exact:true}));await until(()=>game().currentRoll?.purpose==='ability-check'&&game().currentRoll!.stage==='after-roll');const nativeSuccess=game().currentRoll!.success!;if(nativeSuccess){await until(()=>!!game().inspection);expect(game().inspection!.zone).toBe('hand');await click(page.getByRole('complementary',{name:'自分だけの確認内容',exact:true}).getByRole('button',{name:'確認を終える',exact:true}));}await until(()=>!game().activeWindow);expect(game().abilityOptions.some(o=>o.abilityId===astrologyAbility)).toBe(false);}expect(errors).toEqual([]);
 }finally{await table.close();}
});
