import {expect,test,type Locator,type Page} from '@playwright/test';
import {griffinPhysicalMode,griffinPhysicalScenarios} from '../../apps/worker/test/fixtures/griffin-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of griffinPhysicalScenarios)test(`${scenario} actual Griffin morale or selected two-hit attack survives reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=griffinPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!,bp=table.pages[1]!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function settle(stop?:string){for(let n=0;n<300;n++){const current=views.get(a)!,g=current.game!,w=g.activeWindow;if(!w||w.kind===stop)return;const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('GRIFFIN_UI_LIMIT');}
 async function place(p:Page,name:string){await p.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name,exact:true}).click();await click(p.getByRole('button',{name:'従者を置く',exact:true}));}
 async function selectCard(p:Page,id:string,card:string){const index=views.get(id)!.game!.self.hand.indexOf(card);await p.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function target(p:Page,index:number){await p.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:p.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();}
 async function bundle(p:Page,ability:string,card:string,targetIndex:number){const panel=p.getByRole('region',{name:'複数従者の攻撃',exact:true});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption(ability);await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption(card);await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await panel.getByRole('radio',{name:table.sessions[targetIndex]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));}
 if(m.initial){await place(page,m.name);await page.reload();}for(let i=0;i<4;i++){if(i===1&&m.maai)await place(bp,'黒騎士団');await click(table.pages[i]!.getByRole('button',{name:'従者を置かず進む',exact:true}));}await click(page.getByRole('button',{name:'手番を始める',exact:true}));await click(page.getByRole('button',{name:'カードを引かない',exact:true}));
 if(m.dedicated||m.army||m.grant){if(m.army){const panel=page.getByRole('region',{name:'全軍突撃せよ',exact:true});await panel.getByRole('combobox',{name:'突撃に使う従者',exact:true}).selectOption(m.card);await panel.getByRole('radio',{name:table.sessions[1]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'2枚を使って全軍突撃する',exact:true}));}else if(m.grant)await bundle(page,'c2-p05-r1c2-ab02',m.card,1);else{const panel=page.getByRole('region',{name:'従者による攻撃',exact:true});await panel.getByRole('combobox',{name:'攻撃に使う従者',exact:true}).selectOption(m.card);await panel.getByRole('checkbox',{name:'専用の攻撃として使う',exact:true}).check();for(const i of [1,2])await panel.getByRole('checkbox',{name:table.sessions[i]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'従者で攻撃する',exact:true}));}if(m.maai){await settle('normal-defense');await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p07-r1c2');await click(bp.getByRole('button',{name:'間合いを使う',exact:true}));}}
 else{if(!m.initial){const panel=page.getByRole('region',{name:'従者の配置',exact:true});await panel.getByRole('combobox',{name:'従者を加える',exact:true}).selectOption(m.card);await click(panel.getByRole('button',{name:'この順番で確定',exact:true}));await page.reload();}for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle();continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===b)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}if(m.morale){await selectCard(bp,b,'a2-p24-r2c1');await target(bp,0);await click(bp.getByRole('button',{name:'接近',exact:true}));await settle();await bundle(bp,'c2-p06-r1c2-ab04','a2-p21-r2c3',0);if(m.waive){await settle('normal-defense');await page.getByRole('checkbox',{name:'グリフォンの専用効果を使う',exact:true}).check();await click(page.getByRole('button',{name:'従者で受ける',exact:true}));}}else{await selectCard(bp,b,'a2-p24-r1c2');await bp.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await target(bp,0);await click(bp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}}
 await page.reload();await settle();await page.reload();const done=views.get(a)!.game!,alive=!m.dedicated&&!m.army&&!m.grant&&!m.morale;expect([done.players[a]!.damage,done.players[b]!.damage,done.players[c]!.damage]).toEqual(m.dedicated||m.army||m.grant?[0,m.maai?3:16,m.dedicated?16:0]:[m.morale?m.fail?18:9:0,0,0]);expect(done.self.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);expect(done.self.hand).not.toContain(m.card);expect(done.discard.filter(id=>id===m.card)).toHaveLength(alive?0:1);if(m.army)expect(done.discard.filter(id=>id==='a2-p05-r2c2')).toHaveLength(1);if(m.morale)expect(done.recentRolls.filter(r=>r.purpose==='follower-morale')).toHaveLength(m.waive?0:1);if(m.maai)expect(done.discard.filter(id=>id==='a2-p20-r1c2')).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
