import {expect,test,type Locator} from '@playwright/test';
import {hajaPhysicalScenarios} from '../../apps/worker/test/fixtures/haja-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of hajaPhysicalScenarios)test(`${scenario} actual Haja hand chant ownership and saved capacity decisions survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b]=ids as [string,string],page=table.pages[0]!,bp=table.pages[1]!,base=structuredClone(views.get(a)!.game!.self.stats),haja='a2-p01-r2c2',ice='a2-p13-r1c1',rift='a2-p14-r2c2';const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function step(){const g=game(),w=g.activeWindow;if(w){const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));return;}const seat=g.turnSeat,p=table.pages[seat]!;if(g.phase==='hand-adjustment'){const v=views.get(ids[seat]!)!.game!.self,excess=Math.max(0,v.hand.length-v.stats.handLimit);for(const card of v.hand.slice(0,excess))await select(seat,card);await click(p.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));return;}const label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;if(!label)throw Error('HAJA_UI_PHASE');await click(p.getByRole('button',{name:label,exact:true}));}
 async function next(id:string,phase='action'){for(let n=0;n<250;n++){const g=game();if(!g.activeWindow&&g.seatOrder[g.turnSeat]===id&&g.phase===phase)return;await step();}throw Error('HAJA_UI_TURN');}
 async function settle(stop?:string){for(let n=0;n<200;n++){const w=game().activeWindow;if(!w||w.kind===stop)return;await step();}throw Error('HAJA_UI_WINDOW');}
 async function chant(card:string){await select(0,card);await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();}
 async function wish(seat:number){const p=table.pages[seat]!;await click(p.getByRole('button',{name:'祈願を使う（1枚目）',exact:true}));await settle('wish');await p.reload();const panel=p.getByRole('complementary',{name:'自分だけの祈願の選択'});await panel.getByRole('combobox',{name:'取得先',exact:true}).selectOption('public');await panel.getByRole('combobox',{name:'取得候補',exact:true}).selectOption(haja);await click(panel.getByRole('button',{name:'この候補から1枚取得する',exact:true}));}
 for(const p of table.pages)await click(p.getByRole('button',{name:'従者を置かず進む',exact:true}));await click(page.getByRole('button',{name:'手番を始める',exact:true}));await click(page.getByRole('button',{name:scenario==='haja-book'?'カードを引かない':'カードを引く',exact:true}));if(scenario==='haja-book'){await click(page.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:'秘伝書を使う',exact:true}));await settle();}await page.reload();expect(views.get(a)!.game!.self.stats).toEqual({...base,handLimit:6,chantLimit:2});expect(game().players[a]!.open).toContain(haja);
 if(scenario==='haja-draw'||scenario==='haja-book'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));await next(b);expect(views.get(a)!.game!.self.hand).toHaveLength(6);if(scenario==='haja-draw'){await next(a,'draw');await click(page.getByRole('button',{name:'カードを引く',exact:true}));expect(views.get(a)!.game!.self.hand).toHaveLength(7);await click(page.getByRole('button',{name:'行動を終える',exact:true}));await expect(page.getByRole('button',{name:'選んだ1枚を捨てて手番を終える',exact:true})).toBeDisabled();await step();expect(views.get(a)!.game!.self.hand).toHaveLength(6);}}
 else{
  await chant(ice);await next(a);await chant(rift);await next(b);expect(views.get(a)!.game!.self.hand).toHaveLength(6);expect(views.get(a)!.game!.self.chants.map(c=>c.cardInstanceId)).toEqual([ice,rift]);expect(game().players[a]!.chants.every(c=>c.face==='back')).toBe(true);
  if(scenario==='haja-chants'){await next(a);await select(0,'a2-p13-r2c3');await expect(page.getByRole('button',{name:'詠唱',exact:true})).toBeDisabled();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'氷狼乱舞陣を選ぶ',exact:true}).click();await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await settle();expect(game().players[b]!.damage).toBe(7);await next(a);await chant('a2-p13-r2c3');expect(views.get(a)!.game!.self.chants.map(c=>c.cardInstanceId)).toEqual([rift,'a2-p13-r2c3']);}
  else if(scenario==='haja-death'){await select(1,'a2-p24-r2c2');await bp.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:bp.getByRole('heading',{name:table.sessions[0]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(bp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await settle();expect(game().players[a]!.presence).toBe('dead');expect(views.get(a)!.game!.self.chants).toEqual([]);expect(views.get(a)!.game!.self.stats).toEqual(base);for(const id of [haja,ice,rift])expect((await storedDiscard()).filter(x=>x===id)).toHaveLength(1);}
  else{const hand=[...views.get(a)!.game!.self.hand];await wish(1);await page.reload();expect(views.get(a)!.game!.self.stats).toEqual(base);expect(views.get(a)!.game!.self.hand).toEqual(hand);const capacity=page.getByRole('complementary',{name:'祈願後の上限調整'});await expect(capacity.getByRole('button',{name:'選んだ札を捨てて続ける',exact:true})).toBeDisabled();for(const p of table.pages.slice(1))await expect(p.getByRole('complementary',{name:'祈願後の上限調整'})).toHaveCount(0);await capacity.getByRole('checkbox',{name:'氷狼乱舞陣',exact:true}).check();await click(capacity.getByRole('button',{name:'選んだ札を捨てて続ける',exact:true}));await settle();await next(a);expect(views.get(a)!.game!.self.hand).toEqual(hand);
   if(scenario==='haja-return'){await wish(0);await settle();await page.reload();expect(views.get(a)!.game!.self.stats).toEqual({...base,handLimit:6,chantLimit:2});expect(game().players[a]!.open).toContain(haja);}else{await click(page.getByRole('button',{name:'行動を終える',exact:true}));await expect(page.getByRole('button',{name:'選んだ1枚を捨てて手番を終える',exact:true})).toBeDisabled();await step();expect(views.get(a)!.game!.self.hand).toHaveLength(5);}expect(views.get(a)!.game!.self.chants.map(c=>c.cardInstanceId)).toEqual([rift]);expect((await storedDiscard()).filter(id=>id===ice)).toHaveLength(1);
  }
 }
 expect(game().logs.filter(e=>e.type==='OPEN'&&e.cardInstanceId===haja)).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
