import {expect,test,type Locator} from '@playwright/test';
import {healingPhysicalMode} from '../../apps/worker/test/fixtures/healing-physical-scenarios.js';
import {observe,passUntil,tableFixture} from './helpers.js';
for(const scenario of ['heal-warrior','heal-magic-1','heal-magic-2','heal-jill-1','heal-jill-2'] as const)test(`${scenario} real wounds and actual approach heal only the selected recipient across reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,page=table.pages[0]!,m=healingPhysicalMode(scenario);expect([views.get(a)!.game!.players[a]!.damage,views.get(a)!.game!.players[b]!.damage]).toEqual([5,4]);async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 if(m.dedicated){const index=views.get(a)!.game!.self.hand.indexOf('a2-p24-r1c2');expect(index).toBeGreaterThanOrEqual(0);await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'接近',exact:true}));await passUntil(table,views,g=>!g.activeWindow);await page.reload();expect(views.get(a)!.game!.distances[a]![b]).toBe('near');}
 await page.getByLabel('手番技として使うカード').selectOption(m.card);if(!m.warrior)await page.getByLabel('専用効果を使う',{exact:true}).setChecked(m.dedicated);if(m.dedicated)await page.getByRole('combobox',{name:'回復させる近くの相手',exact:true}).selectOption(b);await click(page.getByRole('button',{name:'手番技を使う',exact:true}));await page.reload();await passUntil(table,views,g=>!g.activeWindow);await table.pages[1]!.reload();const done=views.get(a)!.game!;expect([done.players[a]!.damage,done.players[b]!.damage]).toEqual(m.dedicated?[5,0]:[0,4]);expect(done.self.hand).not.toContain(m.card);expect(done.self.chants).toEqual([]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect(done.phase).toBe('hand-adjustment');
 }finally{await table.close();}
});
