import {expect,test,type Locator} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {hostagePhysicalScenarios,hostageMode} from '../../apps/worker/test/fixtures/hostage-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of hostagePhysicalScenarios)test(`${scenario} actual Hostage and Cham printed cancellation survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!,dp=table.pages[3]!,m=hostageMode(scenario),card='a2-p02-r2c2',owner=ids[m.owner]!,op=table.pages[m.owner]!,wide=m.multi||m.late||scenario==='hostage-counter';const game=()=>views.get(a)!.game!,user=()=>views.get(owner)!.game!,cham=()=>views.get(c)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('HOSTAGE_UI_LIMIT');}
 if(wide)await page.getByRole('region',{name:'自分の詠唱'}).getByRole('button',{name:`${getAction(m.attack)!.name}を選ぶ`,exact:true}).click();else{const index=game().self.hand.indexOf(m.attack);expect(index).toBeGreaterThanOrEqual(0);await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}if(wide)await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).check();for(const seat of wide?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[seat]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));const root=game().currentAction!.actionId;
 if(m.multi){await until(()=>!!game().currentAttack);expect(game().currentAttack!.targets).toHaveLength(2);expect(game().currentAttack!.targets[0]!.hits.length).toBeGreaterThanOrEqual(1);}if(m.late)await until(()=>game().currentAttack?.targets.find(t=>t.actorId===b)?.hits.every(h=>h.hit||h.defended)===true&&game().activeWindow?.kind==='hit');if(m.follower)await until(()=>game().activeWindow?.kind==='follower-start');if(scenario==='hostage-counter'){await until(()=>game().activeWindow?.kind==='normal-defense');const panel=bp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p10-r3c3');await panel.getByRole('checkbox',{name:'専用技として使う',exact:true}).check();await click(panel.getByRole('button',{name:'防御する',exact:true}));}
 const unused=['hostage-wrong-user','hostage-wrong-attacker','hostage-follower','hostage-decline'].includes(scenario);if(unused){if(scenario!=='hostage-decline'){await until(()=>game().activeWindow?.pendingActorId===b);expect(user().anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);await expect(bp.getByRole('button',{name:'人質を使う',exact:true})).toHaveCount(0);}await until(()=>!game().activeWindow);expect(user().self.hand).toContain(card);expect(game().players[b]!.damage).toBe(m.follower?3:4);return;}
 await until(()=>user().anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetEventId===root));const hand=user().self.hand.length,o=user().anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetEventId===root)!;await click(op.getByRole('button',{name:o.label,exact:true}).first());expect(user().self.hand).toHaveLength(hand);await op.reload();
 if(scenario==='hostage-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const panel=dp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}else if(m.respond){await until(()=>game().activeWindow?.pendingActorId===c);if(scenario==='hostage-reveal'){await expect(cp.getByRole('button',{name:'人質を中止する',exact:true})).toHaveCount(0);const w=game().activeWindow!.windowId;await click(cp.getByRole('button',{name:'正体を公開',exact:true}));expect(game().activeWindow!.windowId).toBe(w);}expect(cham().abilityOptions.some(o=>o.name==='人質を中止する')).toBe(true);await cp.reload();await click(cp.getByRole('button',{name:'人質を中止する',exact:true}));await until(()=>game().activeWindow?.pendingActorId===d);expect(views.get(d)!.game!.reactionTargetAbilityId).toBeNull();expect(views.get(d)!.game!.self.hand).toContain('a2-p02-r2c3');await dp.reload();expect(views.get(d)!.game!.reactionTargetAbilityId).toBeNull();}else if(['hostage-cham-decline','hostage-unrelated','hostage-stopped','hostage-hidden'].includes(scenario)){await until(()=>game().activeWindow?.pendingActorId===c);const available=scenario==='hostage-cham-decline';expect(cham().abilityOptions.some(o=>o.name==='人質を中止する')).toBe(available);await expect(cp.getByRole('button',{name:'人質を中止する',exact:true})).toHaveCount(available?1:0);}
 await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(m.respond||scenario==='hostage-fate'?4:m.late?15:0);expect(game().players[c]!.damage).toBe(0);if(scenario==='hostage-counter'){const checks=views.get(b)!.game!.recentRolls.filter(r=>r.rollerId===b&&r.kind==='check');expect(checks.length).toBeGreaterThanOrEqual(1);expect(game().players[a]!.damage).toBe(checks.every(r=>r.success)?7:0);}else expect(game().players[a]!.damage).toBe(0);expect(game().discard.filter(id=>id===card)).toHaveLength(1);if(scenario==='hostage-refill')expect(game().players[b]!.open).toContain('a2-p01-r1c3');if(scenario==='hostage-hidden')expect(game().players[a]!.revealed).toBe(false);await op.reload();expect(user().currentAttack).toBeNull();expect(errors).toEqual([]);
 }finally{await table.close();}
});
