import {expect,test,type Locator} from '@playwright/test';
import {observe,passUntil,tableFixture} from './helpers.js';
import {iceMagicMode} from '../../apps/worker/test/fixtures/ice-magic-scenarios.js';
for(const scenario of ['ice-arrow-ordinary','ice-arrow-dedicated','ice-stream-ordinary','ice-stream-dedicated','ice-stream-declined','ice-stream-relative'] as const)test(`${scenario} real target-local follower choice persists across reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const m=iceMagicMode(scenario),views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const index of m.dedicated?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();
 if(m.relative){await passUntil(table,views,g=>g.activeWindow?.kind==='effect-level');await page.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('effect-plus');await page.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p05-r2c3');await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await click(page.getByRole('button',{name:'割り込みを使う',exact:true}));}
 const offered:string[]=[];for(let n=0;n<10;n++){await passUntil(table,views,g=>!g.activeWindow||g.activeWindow.kind==='follower-bypass-choice',300);const g=views.get(a)!.game!;if(!g.activeWindow)break;await page.reload();const target=views.get(a)!.game!.currentAttack!.targetId!;offered.push(target);if(m.relative)expect(views.get(a)!.game!.currentAttack!.technique.effectLevel).toBeGreaterThanOrEqual(8);await click(page.getByRole('button',{name:target===b&&m.ignore?'条件を満たす従者を無視する':'無視しない',exact:true}));await page.reload();}
 const done=views.get(a)!.game!;expect(done.activeWindow).toBeNull();expect(offered).toEqual(!m.arrow&&m.dedicated?[b,c]:[]);expect([done.players[b]!.damage,done.players[c]!.damage]).toEqual([m.arrow?m.damage-1:m.dedicated&&m.ignore?6:0,m.dedicated?(m.arrow?6:5):0]);expect(done.players[b]!.followers).toHaveLength(m.arrow||m.dedicated&&!m.ignore?0:1);expect(done.self.hand).not.toContain(m.card);
 }finally{await table.close();}
});
