import {expect,test,type Locator} from '@playwright/test';
import {judgmentPhysicalMode,judgmentPhysicalScenarios} from '../../apps/worker/test/fixtures/judgment-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of judgmentPhysicalScenarios)test(`${scenario} real CHANT and selected attack or counter survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=judgmentPhysicalMode(scenario);const errors:string[]=[];for(const page of table.pages)page.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,d=table.sessions[3]!.id,page=table.pages[0]!;async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=300){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);const actorPage=table.pages[table.sessions.findIndex(p=>p.id===actor)]!;await actorPage.getByRole('button',{name:windowPassButtonName}).click();expect(errors,{message:`${scenario} ${w.kind} actor=${actor}`}).toEqual([]);await expect.poll(()=>views.get(a)?.revision,{message:`${scenario} ${w.kind} actor=${actor} revision=${current.revision} errors=${errors.join(',')}`}).toBeGreaterThan(current.revision);}throw Error('JUDGMENT_UI_LIMIT');}async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'神罰',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));for(let n=0;n<180;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===(m.counter?b:a))break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}await page.reload();const caster=m.counter?table.pages[1]!:page;if(m.counter){const index=views.get(b)!.game!.self.hand.indexOf('a2-p15-r3c2');await caster.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}else await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'神罰を選ぶ',exact:true}).click();await caster.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.counter?false:m.dedicated);for(const i of m.counter?[0]:m.dedicated?[1,2,3]:[1])await caster.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:caster.getByRole('heading',{name:table.sessions[i]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(caster.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await caster.reload();if(m.counter){await settle(g=>g.activeWindow?.kind==='normal-defense');await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await page.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.card);await click(page.getByRole('button',{name:'防御する',exact:true}));await page.reload();}await settle(g=>!g.activeWindow,300);await page.reload();const done=views.get(a)!.game!;expect((await storedDiscard()).filter(id=>id===m.card)).toHaveLength(1);expect(done.self.chants).toEqual([]);expect(done.players[a]!.damage).toBe(0);expect(done.players[b]).toMatchObject({damage:m.damage-6,followers:[]});expect([done.players[c]!.damage,done.players[d]!.damage]).toEqual(!m.counter&&m.dedicated?[m.damage,m.damage]:[0,0]);expect(done.players[c]!.followers).toHaveLength(!m.counter&&m.dedicated?0:1);
 }finally{await table.close();}
});
