import {expect,test,type Locator} from '@playwright/test';
import {keilPhysicalScenarios,keilMode} from '../../apps/worker/test/fixtures/keil-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of keilPhysicalScenarios)test(`${scenario} actual Keil protection growth and later lifecycle survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,m=keilMode(scenario),owner=ids[m.owner]!,op=table.pages[m.owner]!,card='a2-p01-r3c1';const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function step(){const g=game(),w=g.activeWindow;if(w){const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:w.kind==='re-setup'?'従者の配置を終える':windowPassButtonName}));return;}const seat=g.turnSeat,p=table.pages[seat]!;if(g.phase==='hand-adjustment'){const v=views.get(ids[seat]!)!.game!.self,excess=Math.max(0,v.hand.length-v.stats.handLimit);for(const card of v.hand.slice(0,excess))await select(seat,card);await click(p.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));return;}const label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;if(!label)throw Error('KEIL_UI_PHASE');await click(p.getByRole('button',{name:label,exact:true}));}
 async function until(done:()=>boolean){for(let n=0;n<300;n++){if(done())return;await step();}throw Error('KEIL_UI_LIMIT');}
 async function next(id:string,phase='action'){await until(()=>!game().activeWindow&&game().seatOrder[game().turnSeat]===id&&game().phase===phase);}
 async function attack(bow=false){if(bow)await select(0,'a2-p24-r1c2');else await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:`${m.multi?'天地爆砕剣':'天地百撃斬'}を選ぶ`,exact:true}).click();for(const seat of !bow&&m.multi?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[seat]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}
 async function protect(){await until(()=>!!views.get(owner)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===b));await op.reload();const o=views.get(owner)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===b)!;await click(op.getByRole('button',{name:o.label,exact:true}));await op.reload();}
 const base=views.get(b)!.game!.self.stats.spirit,hand=views.get(owner)!.game!.self.hand.length;await attack();await until(()=>game().activeWindow?.kind==='attack-abilities');const hits=game().currentAttack!.targets[0]!.hits.length;if(m.follower)await until(()=>game().activeWindow?.kind==='hit');const declined=['keil-hidden','keil-unrelated','keil-follower'].includes(scenario);
 if(declined){await until(()=>game().activeWindow?.pendingActorId===owner);await op.reload();await expect(op.getByRole('button',{name:/^聖騎士団長ケイルベイツを使う/})).toHaveCount(0);}
 else{const before={...views.get(owner)!.game!.self.stats};await protect();expect(views.get(owner)!.game!.self.hand).toHaveLength(hand);if(scenario==='keil-refill'){expect(game().players[owner]!.open).toContain('a2-p01-r1c3');expect(views.get(owner)!.game!.self.stats).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});}if(scenario==='keil-canceled'){await until(()=>game().activeWindow?.pendingActorId===a);const panel=page.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}}
 await until(()=>!game().activeWindow);await op.reload();expect(game().players[b]!.damage).toBe(scenario==='keil-follower'?4*hits:declined||scenario==='keil-canceled'?7*hits:0);expect(game().players[c]!.damage).toBe(m.multi?15:0);expect(game().players[d]!.damage).toBe(0);expect(views.get(b)!.game!.self.stats.spirit).toBe(base+(declined||scenario==='keil-canceled'||scenario==='keil-lia'?0:1));if(declined)expect(views.get(owner)!.game!.self.hand).toContain(card);else expect(game().discard.filter(id=>id===card)).toHaveLength(1);
 if(scenario==='keil-growth'){await next(d,'draw');await click(op.getByRole('button',{name:'カードを引く',exact:true}));await until(()=>!game().activeWindow);expect(game().players[d]!.open).toContain('a2-p01-r1c2');if(!views.get(d)!.game!.self.hand.includes(card)){await click(op.getByRole('button',{name:'祈願を使う（1枚目）',exact:true}));await until(()=>game().activeWindow?.kind==='wish');await op.reload();const panel=op.getByRole('complementary',{name:'自分だけの祈願の選択'});await panel.getByRole('combobox',{name:'取得先',exact:true}).selectOption('deck');await panel.getByRole('combobox',{name:'取得候補',exact:true}).selectOption('聖騎士団長ケイルベイツ');await click(panel.getByRole('button',{name:'この候補から1枚取得する',exact:true}));await until(()=>!game().activeWindow);}await next(a);await attack(true);await protect();await until(()=>!game().activeWindow);expect(views.get(b)!.game!.self.stats.spirit).toBe(base+2);expect(game().players[b]!.damage).toBe(0);}
 if(scenario==='keil-transform'){await click(table.pages[2]!.getByRole('button',{name:'正体を公開',exact:true}));await until(()=>!game().activeWindow);await click(table.pages[1]!.getByRole('button',{name:'ランスロットⅡへ変身する',exact:true}));await until(()=>!game().activeWindow);await table.pages[1]!.reload();expect(views.get(b)!.game!.self.characterId).toBe('c2-p07-r1c1');expect(views.get(b)!.game!.self.stats.spirit).toBe(base+2);}
 if(scenario==='keil-revive'){await next(a);await attack(true);await until(()=>!game().activeWindow);expect(game().players[b]!.presence).toBe('dead');await next(d);await op.getByLabel('手番技として使うカード').selectOption('a2-p13-r3c1');await op.getByLabel('専用効果を使う',{exact:true}).check();await op.getByRole('group',{name:'復活させる相手（複数選択可）'}).getByLabel(table.sessions[1]!.name,{exact:true}).check();await click(op.getByRole('button',{name:'手番技を使う',exact:true}));await until(()=>game().activeWindow?.kind==='re-setup');await table.pages[1]!.reload();expect(game().players[b]).toMatchObject({presence:'active',damage:0,revealed:true});expect(views.get(b)!.game!.self.stats.spirit).toBe(base+1);await click(table.pages[1]!.getByRole('button',{name:'従者の配置を終える',exact:true}));await until(()=>!game().activeWindow);}
 if(m.follower)expect(game().discard.filter(id=>id==='a2-p20-r3c1')).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
