import {expect,test,type Locator} from '@playwright/test';
import {kiSlashScenarios,kiSlashCard as CARD,kiSlashMode} from '../../apps/worker/test/fixtures/ki-slash-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of kiSlashScenarios)test(`${scenario} actual Ki Slash spirit boundary owner choice and mental defenses survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=kiSlashMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('KI_SLASH_UI_LIMIT');}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});
  if(scenario==='ki-slash-stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(scenario==='ki-slash-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),rolls=game().recentRolls.map(r=>r.rollId);expect(own(a).stats.spirit).toBe(6);expect(own(b).stats.spirit).toBe(11);
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);
  await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[b]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();
  if(scenario==='ki-slash-wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await expect(execute).toBeEnabled();return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(scenario==='ki-slash-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
  let success=true,fixed=6*(m.dedicated?2:1);if(scenario==='ki-slash-low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(m.freeze){await until(()=>game().activeWindow?.kind===(m.after?'attack-abilities':'damage'));const parent=game().activeWindow!.windowId,target=m.target?b:a,priorSpirit=own(target).stats.spirit;if(m.after)expect(game().currentAttack!.technique.damage).toBe(fixed);await page.reload();await until(()=>game().activeWindow?.pendingActorId===d);await expect.poll(()=>views.get(d)?.revision).toBe(views.get(a)!.revision);const option=views.get(d)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId===target)!;expect(option).toBeDefined();const dHand=own(d).hand.length;await dp.reload();await click(dp.getByRole('button',{name:option.label,exact:true}));await until(()=>game().activeWindow?.windowId===parent);await expect.poll(()=>views.get(target)?.revision).toBe(views.get(a)!.revision);expect(own(target).stats.spirit).toBeGreaterThan(priorSpirit);expect(own(d).hand).toHaveLength(dHand);expect((await storedDiscard()).filter(id=>id==='a2-p02-r1c1')).toHaveLength(1);if(!m.after&&!m.target)fixed=own(a).stats.spirit*(m.dedicated?2:1);await page.reload();}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?7:6,damage:fixed,attributes:['戦','剣','精','忍']});if(scenario==='ki-slash-maai'||scenario==='ki-slash-evade'){await until(()=>game().activeWindow?.kind==='normal-defense');expect(views.get(b)!.game!.currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:false,evadeProhibited:true});const reaction=bp.getByRole('complementary',{name:'現在の判断'}),select=reaction.getByRole('combobox',{name:'使うカード',exact:true});if(scenario==='ki-slash-maai'){await select.selectOption('a2-p06-r1c3');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));fixed=0;}else{await expect(select.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);expect(own(b).hand).toContain('a2-p05-r3c1');}}}
  await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(success?fixed:0);for(const id of [a,c,d])expect(game().players[id]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);expect(game().phase).toBe('withdrawal');if(scenario!=='ki-slash-low')expect(game().recentRolls.map(r=>r.rollId)).toEqual(rolls);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
