import {expect,test,type Locator} from '@playwright/test';
import {lesterSongsPhysicalMode,lesterSongsPhysicalScenarios} from '../../apps/worker/test/fixtures/lester-songs-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of lesterSongsPhysicalScenarios)test(`${scenario} actual selected song target defense and own recovery survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=lesterSongsPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,d=table.sessions[3]!.id,page=table.pages[0]!,bp=table.pages[1]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=350){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('LESTER_SONGS_UI_LIMIT');}async function toB(){for(let n=0;n<180;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase==='turn-start'&&g.seatOrder[g.turnSeat]===b)return;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}throw Error('LESTER_SONGS_UI_TURN');}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const index of m.dedicated?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await settle(g=>g.activeWindow?.kind==='normal-defense');const attack=views.get(a)!.game!.currentAttack!,damage=attack.technique.damage!;expect(attack.technique).toMatchObject({effectLevel:m.effect,attributes:['魔','精','歌']});expect(attack.defenseRestrictions).toMatchObject({evadeProhibited:true,counterProhibited:!m.poem&&m.dedicated,maaiProhibited:false});if(!m.poem){expect(damage%m.damage).toBe(0);expect(damage).toBeGreaterThanOrEqual(m.damage);expect(damage).toBeLessThanOrEqual(m.damage*6);}if(m.teleport){await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c1');await click(bp.getByRole('button',{name:'防御する',exact:true}));}else if(m.poem){await settle(g=>g.activeWindow?.kind==='after-roll'&&g.currentRoll?.purpose==='status-resistance');await settle(g=>g.activeWindow?.pendingActorId===d);const panel=table.pages[3]!.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('force-fail');await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}await settle(g=>!g.activeWindow);await bp.reload();let done=views.get(b)!.game!;expect((await storedDiscard()).filter(id=>id===m.card)).toHaveLength(1);expect([done.players[a]!.damage,done.players[b]!.damage,done.players[c]!.damage]).toEqual([0,m.teleport?0:m.poem&&!m.dedicated?4:damage,m.dedicated?damage:0]);expect(done.players[b]!.followers).toHaveLength(!m.teleport&&m.poem&&!m.dedicated?1:2);expect(done.players[c]!.followers).toHaveLength(1);expect(done.players[b]!.statuses).toHaveLength(m.poem&&!m.teleport?1:0);if(m.poem&&!m.teleport){await toB();await click(bp.getByRole('button',{name:'手番を始める',exact:true}));expect(views.get(b)!.game!.currentRoll).toMatchObject({purpose:'status-recovery',modifier:m.dedicated?-3:-2});await bp.reload();await settle(g=>!g.activeWindow);expect(views.get(b)!.game!.players[b]!.statuses).toEqual([]);await click(bp.getByRole('button',{name:'カードを引かない',exact:true}));await bp.reload();done=views.get(b)!.game!;expect(done.phase).toBe('action');expect(done.players[b]!.damage).toBe(m.dedicated?7:4);}expect(errors).toEqual([]);
 }finally{await table.close();}
});
