import {expect,test,type Locator} from '@playwright/test';
import {lightKingScenarios,lightKingMode,lightKingCard as CARD,type LightKingScenario} from '../../apps/worker/test/fixtures/light-king-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of lightKingScenarios)test(`${scenario} actual ordinary defense or Lia whole group interception survives reload`,async({browser,request})=>{
 const m=lightKingMode(scenario),name=(m.group?scenario.replace('light-king-','light-king-ui-'):scenario) as LightKingScenario,table=await tableFixture(browser,request,name),errors:string[]=[];
 for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[2]!,ap=table.pages[0]!,dp=table.pages[3]!,game=()=>views.get(c)!.game!,own=(id:string)=>views.get(id)!.game!.self;
 async function click(button:Locator){const rev=views.get(c)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(c)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(a)?.revision).toBe(views.get(c)!.revision);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(c)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<700;n++){if(done())return;await step();}throw Error('LIGHT_KING_UI_LIMIT');}
 const hand=[...own(c).hand],rolls=game().recentRolls.map(r=>r.rollId);
 if(m.suffix==='root'){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(c).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[a]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();await expect(page.getByRole('button',{name:'攻撃を確認して実行',exact:true})).toBeDisabled();return;}
 if(m.suffix==='decline'){await until(()=>!game().activeWindow);expect(game().players[c]!.damage).toBe(4);expect(own(c).hand).toEqual(hand);return;}
 if(m.prohibited){expect(game().groupDefenseOptions).toEqual([]);await expect(page.getByRole('button',{name:'光王陣でまとめて防ぐ',exact:true})).toHaveCount(0);return;}
 if(m.group){expect(own(c).stats.spirit).toBe(m.suffix==='group-fail'?3:15);const option=game().groupDefenseOptions[0]!;expect(option.targetIds).toEqual([b,d]);await page.reload();await click(page.getByRole('region',{name:'技の追加効果'}).getByRole('button',{name:'光王陣でまとめて防ぐ',exact:true}));}else{const reaction=page.getByRole('complementary',{name:'現在の判断'});if(['evil','low-effect'].includes(m.suffix)){if(await reaction.locator(`option[value="${CARD}"]`).count()){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);await expect(reaction.getByRole('button',{name:'防御する',exact:true})).toBeDisabled();}expect(own(c).hand).toEqual(hand);return;}await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);await reaction.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await click(reaction.getByRole('button',{name:'防御する',exact:true}));}
 expect(own(c).hand).toEqual(hand.filter(id=>id!==CARD));await page.reload();
 if(m.suffix==='group-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(15);expect(game().players[d]!.damage).toBe(15);expect(game().players[a]!.damage).toBe(0);return;}
 if(!m.group){await until(()=>!game().activeWindow);const failed=game().recentRolls.some(r=>!rolls.includes(r.rollId)&&r.kind==='check'&&r.success===false);expect(game().players[c]!.damage).toBe(failed?4:0);expect(game().players[a]!.damage).toBe(0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
 if(m.suffix==='group-fail'){await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(15);expect(game().players[d]!.damage).toBe(15);expect(game().players[a]!.damage).toBe(0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
 await until(()=>game().currentRoll?.formula==='d6-product-min10'&&game().currentRoll?.stage==='after-roll');if(m.suffix==='reroll'){const id=game().currentRoll!.rollId;await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByLabel('割り込み効果').selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().currentRoll?.generation===1);}
 const roll=game().currentRoll!;expect(roll.faces).toHaveLength(2);const product=Math.max(10,roll.faces[0]!*roll.faces[1]!);expect(roll.total).toBe(product);await page.reload();await until(()=>game().activeWindow?.kind==='normal-defense'&&game().activeWindow?.pendingActorId===a);expect(game().currentAttack!.targets.map(t=>t.actorId)).toEqual([a]);expect(game().currentAttack!.technique).toMatchObject({effectLevel:15,damage:product});let damage=product;
 if(m.suffix==='return-maai'||m.suffix==='return-evade'){const reaction=ap.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.suffix==='return-maai'?'a2-p06-r1c3':'a2-p05-r3c1');await click(reaction.getByRole('button',{name:m.suffix==='return-maai'?'間合いを使う':'防御する',exact:true}));damage=0;}
 await until(()=>!game().activeWindow);if(m.suffix==='return-water'||m.nightmare){const morale=views.get(a)!.game!.recentRolls.find(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale');expect(morale).toBeDefined();if(morale!.success)damage=Math.max(0,product-4);expect(own(a).followers).toHaveLength(0);}expect(game().players[a]!.damage).toBe(damage);expect(game().players[b]!.damage).toBe(0);expect(game().players[d]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(m.suffix==='group-self'?15:0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);await page.reload();expect(errors).toEqual([]);
 }finally{await table.close();}
});
