import {expect,test,type Locator} from '@playwright/test';
import {maaiOtherScenarios,maaiOtherCards,maaiOtherSecond as SECOND} from '../../apps/worker/test/fixtures/maai-other-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of maaiOtherScenarios)test(`${scenario} exact physical REST cancellation or incoming MAAI remains consistent after reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,card=maaiOtherCards[Number(scenario.split('-')[2])-1]!,rest=scenario.endsWith('-rest'),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<400;n++){if(done())return;await step();}throw Error('MAAI_OTHER_UI_LIMIT');}
  const owner=rest?a:b,hand=[...own(owner).hand],deck=game().deckCount;expect(own(owner).damage).toBe(4);
  if(rest){for(const id of [card,SECOND]){const index=own(a).hand.indexOf(id);expect(index).toBeGreaterThanOrEqual(0);await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}await click(page.getByRole('button',{name:'休息',exact:true}));expect(own(a).hand).toEqual(hand.filter(id=>id!==card&&id!==SECOND));expect(game().deckCount).toBe(deck);expect(own(a).damage).toBe(4);await page.reload();await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(own(a).damage).toBe(3);expect(own(b).damage).toBe(0);expect(game().phase).toBe('hand-adjustment');for(const id of [card,SECOND])expect(game().discard.filter(x=>x===id)).toHaveLength(1);await page.reload();expect(own(a).damage).toBe(3);}
  else {const reaction=bp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(card);await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));expect(own(b).hand).toEqual(hand.filter(id=>id!==card));expect(game().deckCount).toBe(deck);expect(own(b).damage).toBe(4);await bp.reload();await until(()=>!game().activeWindow);expect(own(b).damage).toBe(4);expect(game().discard.filter(id=>id===card)).toHaveLength(1);expect(game().phase).toBe('withdrawal');await bp.reload();expect(own(b).damage).toBe(4);}
  expect(errors).toEqual([]);
 }finally{await table.close();}
});
