import {expect,test,type Locator} from '@playwright/test';
import {madKingPhysicalMode,madKingPhysicalScenarios} from '../../apps/worker/test/fixtures/mad-king-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of madKingPhysicalScenarios)test(`${scenario} actual attack counter resistance and recovery survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=madKingPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,d=table.sessions[3]!.id,page=table.pages[0]!,bp=table.pages[1]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=300){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(current.revision);}throw Error('MAD_KING_UI_LIMIT');}async function toTurn(phase='action'){for(let n=0;n<180;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase===phase&&g.seatOrder[g.turnSeat]===b)return;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}throw Error('MAD_KING_UI_TURN');}
 const sourcePage=m.counter?bp:page;if(m.counter){await click(page.getByRole('button',{name:'行動を終える',exact:true}));await toTurn();}await sourcePage.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.counter?'炎矢':m.name,exact:true}).click();await sourcePage.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await sourcePage.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:sourcePage.getByRole('heading',{name:table.sessions[m.counter?0:1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(sourcePage.getByRole('button',{name:'攻撃を確認して実行',exact:true}));if(m.counter){await settle(g=>g.activeWindow?.kind==='normal-defense');await page.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.card);await click(page.getByRole('button',{name:'防御する',exact:true}));}await page.reload();if(m.recover)await settle(g=>g.activeWindow?.kind==='after-roll'&&g.currentRoll?.purpose==='status-resistance');if(m.cancel||m.recover){await settle(g=>g.activeWindow?.pendingActorId===d);const panel=table.pages[3]!.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption(m.recover?'force-fail':'cancel');await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}else if(m.teleport){await settle(g=>g.activeWindow?.kind==='normal-defense');await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c1');await click(bp.getByRole('button',{name:'防御する',exact:true}));}await settle(g=>!g.activeWindow);await bp.reload();let done=views.get(b)!.game!;expect(done.discard.filter(id=>id===m.card)).toHaveLength(1);expect([done.players[a]!.damage,done.players[b]!.damage,done.players[c]!.damage]).toEqual([0,m.cancel||m.teleport?0:4,0]);expect(done.players[b]!.followers).toHaveLength(m.cancel||m.teleport?2:1);expect(done.players[b]!.statuses).toHaveLength(m.cancel||m.resist||m.teleport?0:1);if(m.recover){await toTurn('turn-start');await click(bp.getByRole('button',{name:'手番を始める',exact:true}));expect(views.get(b)!.game!.currentRoll).toMatchObject({purpose:'status-recovery',modifier:-1});await bp.reload();await settle(g=>!g.activeWindow);expect(views.get(b)!.game!.players[b]!.statuses).toEqual([]);await click(bp.getByRole('button',{name:'カードを引かない',exact:true}));await bp.reload();done=views.get(b)!.game!;expect(done.phase).toBe('action');expect(done.players[b]!.damage).toBe(4);}expect(errors).toEqual([]);
 }finally{await table.close();}
});
