import {expect,test,type Locator} from '@playwright/test';
import {getAction,getCharacter} from '../../packages/catalog/src/index.js';
import {motherTruthPhysicalScenarios,motherCard,motherGood,motherEvil} from '../../apps/worker/test/fixtures/mother-truth-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of motherTruthPhysicalScenarios)test(`${scenario} actual Mother target restrictions allegiance attachment and later lifetime changes survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!;const game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self,at=(id:string)=>table.pages[ids.indexOf(id)]!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(at(id).getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('MOTHER_UI_LIMIT');}
 async function start(id:string){await click(at(id).getByRole('button',{name:'手番を始める',exact:true}));await until(()=>!game().activeWindow);await click(at(id).getByRole('button',{name:'カードを引かない',exact:true}));}
 async function end(id:string){if(game().phase==='action')await click(at(id).getByRole('button',{name:'行動を終える',exact:true}));await click(at(id).getByRole('button',{name:'選んだ0枚を捨てて手番を終える',exact:true}));await until(()=>!game().activeWindow);}
 async function nextA(){await end(a);for(const id of [b,c,d]){await start(id);await end(id);}await start(a);}
 function profile(faction:'GOOD'|'EVIL'='GOOD'){const p=own(b),protector=faction==='GOOD'?'c2-p03-r1c2':'c2-p05-r2c2';expect({faction:p.faction,objective:p.objective,currentObjective:p.currentObjective,protection:p.protection,defeatCondition:p.defeatCondition}).toEqual({faction,objective:(faction==='GOOD'?'EVIL':'GOOD')+'の全滅',currentObjective:{kind:'extinction',enemyFactions:[faction==='GOOD'?'EVIL':'GOOD']},protection:{characterIds:[protector]},defeatCondition:getCharacter(protector)!.name+'の死亡'});}
 const panel=page.getByRole('region',{name:'対象を選ぶ手番カード'}),button=panel.getByRole('button',{name:'母様の真実を使う',exact:true}),original=[...own(a).hand],deckCount=game().deckCount;if(['mother-wrong-target','mother-asfelt-user','mother-otherworld','mother-stopped'].includes(scenario)){await expect(button).toHaveCount(0);expect(own(a).hand).toContain(motherCard);if(scenario==='mother-otherworld')expect(game().players[b]!.presence).toBe('otherworld');if(scenario==='mother-stopped')expect(game().seatOrder[game().turnSeat]).not.toBe(a);return;}if(scenario==='mother-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(motherCard);return;}if(scenario==='mother-hidden'){await expect(button).toHaveCount(0);await click(bp.getByRole('button',{name:'正体を公開',exact:true}));await until(()=>!game().activeWindow);}const before={faction:own(b).faction,objective:own(b).objective,protection:structuredClone(own(b).protection)},attachments=[...game().players[b]!.attachments],rolls=game().recentRolls.map(r=>r.rollId);await expect(panel.getByRole('combobox',{name:'母様の真実の対象',exact:true}).locator('option')).toHaveCount(1);await panel.getByRole('combobox',{name:'母様の真実の対象',exact:true}).selectOption(b);await click(button);expect(own(a).hand).toEqual(original.filter(id=>id!==motherCard));expect(game().deckCount).toBe(deckCount);expect(game().players[b]!.attachments).toEqual(attachments);await page.reload();
 if(scenario==='mother-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect({faction:own(b).faction,objective:own(b).objective,protection:own(b).protection}).toEqual(before);expect(game().players[b]!.attachments).toEqual(attachments);expect(game().discard).toContain(motherCard);return;}
 await until(()=>!game().activeWindow);profile();expect(game().players[b]!.attachments).toEqual([...attachments,motherCard]);expect(game().recentRolls.map(r=>r.rollId)).toEqual(rolls);expect(game().discard).not.toContain(motherCard);expect(game().phase).toBe('hand-adjustment');await bp.reload();profile();
 if(['mother-stay-good','mother-evil-resist','mother-evil-convert','mother-return-good'].includes(scenario)){let faction:'GOOD'|'EVIL'='GOOD',everLeft=false;async function convert(card:typeof motherGood|typeof motherEvil){await nextA();const label=getAction(card)!.name;await panel.getByRole('combobox',{name:label+'の対象',exact:true}).selectOption(b);await click(panel.getByRole('button',{name:label+'を使う',exact:true}));await until(()=>game().currentRoll?.purpose==='faction-change'&&game().currentRoll!.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(7);const success=game().currentRoll!.success!;if(!success)faction=card===motherGood?'GOOD':'EVIL';everLeft=everLeft||faction==='EVIL';await until(()=>!game().activeWindow);profile(faction);expect(game().players[b]!.attachments.includes(motherCard)).toBe(!everLeft);expect(game().discard.includes(motherCard)).toBe(everLeft);await bp.reload();profile(faction);}await convert(scenario==='mother-stay-good'?motherGood:motherEvil);if(scenario==='mother-return-good')await convert(motherGood);}
 if(scenario==='mother-death'||scenario==='mother-protector-death'){await end(a);for(const id of [b,c]){await start(id);await end(id);}await start(d);const target=scenario==='mother-death'?b:c,i=own(d).hand.indexOf('a2-p24-r1c2');expect(i).toBeGreaterThanOrEqual(0);await dp.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(i).getByRole('button').first().click();await dp.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:dp.getByRole('heading',{name:game().players[target]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();await click(dp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await until(()=>game().activeWindow?.kind==='death-gift');expect(game().players[b]!.attachments).toContain(motherCard);await until(()=>!game().activeWindow);profile();expect(game().players[b]!.presence).toBe(target===b?'dead':'wandering');expect(game().players[b]!.attachments.includes(motherCard)).toBe(target===c);expect(game().discard.includes(motherCard)).toBe(target===b);await bp.reload();profile();}expect(errors).toEqual([]);
 }finally{await table.close();}
});
