import {expect,test,type Locator} from '@playwright/test';
import {nightmareScenarios,nightmareCard as CARD,nightmareMode} from '../../apps/worker/test/fixtures/nightmare-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of nightmareScenarios)test(`${scenario} actual Nightmare mental damage and recovery and physical defenses survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=nightmareMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('NIGHTMARE_UI_LIMIT');}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});
  if(scenario==='nightmare-stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.decline){const guards=[structuredClone(own(b).followers),structuredClone(own(c).followers)];await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);expect([own(b).followers,own(c).followers]).toEqual(guards);return;}
  if(m.suffix==='noncounter'){const reaction=page.getByRole('complementary',{name:'現在の判断'});if(await reaction.locator(`option[value="${CARD}"]`).count()){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);for(const dedicated of [false,true]){await reaction.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);await expect(reaction.getByRole('button',{name:'防御する',exact:true})).toBeDisabled();}}await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).hand).toContain(CARD);return;}
  async function selectCard(id:string){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(id)).getByRole('button').first().click();}
  async function target(){for(const i of m.targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[ids[i]!]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),rolls=game().recentRolls.map(r=>r.rollId);expect(own(a).stats.spirit).toBe(6);expect(own(b).stats.spirit).toBe(6);await selectCard(CARD);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await target();
  if(m.suffix==='wrong-owner'||m.suffix==='silenced'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);if(m.suffix==='wrong-owner'){await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await expect(execute).toBeEnabled();}return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(m.cancel){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
  let success=true;if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}if(!success){await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='attack-damage')).toHaveLength(0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
  if(m.reroll){await until(()=>game().currentRoll?.purpose==='attack-damage'&&game().currentRoll?.stage==='after-roll');const id=game().currentRoll!.rollId;await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByLabel('割り込み効果').selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().currentRoll?.generation===1);await page.reload();}
  await until(()=>game().activeWindow?.kind==='attack-abilities');let damage=2;if(m.dedicated){const roll=game().recentRolls.find(r=>!rolls.includes(r.rollId)&&r.purpose==='attack-damage')!;expect(roll.faces).toHaveLength(2);expect(roll.total).toBe(roll.faces.reduce((sum,face)=>sum+face,0)*2);damage=roll.total!;if(m.reroll)expect(roll.generation).toBe(1);}expect(game().currentAttack!.technique).toMatchObject({effectLevel:6,damage,attributes:['魔','精','黒']});await page.reload();
  if(m.maai||m.evade){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});if(m.maai){await expect(reaction).toContainText('間合い不可');await expect(reaction.locator('option[value="a2-p06-r1c3"]')).toHaveCount(0);}else{await expect(reaction.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);}}
  await until(()=>!game().activeWindow);const resistance=game().recentRolls.find(r=>!rolls.includes(r.rollId)&&r.purpose==='status-resistance'&&r.rollerId===b)!;expect(resistance).toMatchObject({modifier:m.asfelt?-2:-1});expect(game().players[b]!.damage).toBe(damage);expect(own(b).followers).toEqual(bFollowers);expect(game().players[b]!.statuses.some(s=>s.kind==='stopped')).toBe(!resistance.success);for(const i of [2,3])expect(game().players[ids[i]!]!.damage).toBe(m.targets.includes(i)?damage:0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);
  if(m.recovery&&!resistance.success){for(let n=0;n<150;n++){const g=game();if(g.phase==='turn-start'&&g.seatOrder[g.turnSeat]===b)break;if(g.activeWindow){await step();continue;}const p=table.pages[g.turnSeat]!,label=g.phase==='action'?'行動を終える':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':g.phase==='withdrawal'?'離脱しない':null;expect(label).not.toBeNull();await click(p.getByRole('button',{name:label!,exact:true}));}await click(bp.getByRole('button',{name:'手番を始める',exact:true}));await until(()=>game().currentRoll?.purpose==='status-recovery'&&game().currentRoll?.stage==='after-roll');const recovery=structuredClone(game().currentRoll!);expect(recovery.modifier).toBe(m.asfelt?-2:-1);await bp.reload();await until(()=>!game().activeWindow);expect(game().players[b]!.statuses.some(s=>s.kind==='stopped')).toBe(!recovery.success);expect(game().players[b]!.damage).toBe(damage);}
  await page.reload();expect(errors).toEqual([]);
 }finally{await table.close();}
});
