import {expect,test,type Locator} from '@playwright/test';
import {openBlessingPhysicalScenarios,openBlessingMode} from '../../apps/worker/test/fixtures/open-blessing-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of openBlessingPhysicalScenarios)test(`${scenario} actual OPEN guardian capacity morale and Wish loss survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b]=ids as [string,string],page=table.pages[0]!,bp=table.pages[1]!,m=openBlessingMode(scenario),base=structuredClone(views.get(a)!.game!.self.stats),transfer=scenario.endsWith('-transfer')||m.irremovable,placement=scenario.endsWith('-placement');const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function settle(stop?:string){for(let n=0;n<200;n++){const w=game().activeWindow;if(!w||w.kind===stop)return;const id=w.pendingActorId!,p=table.pages[ids.indexOf(id)]!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(p.getByRole('button',{name:windowPassButtonName}));}throw Error('BLESS_UI_WINDOW');}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 for(const card of m.initial){await select(0,card);await click(page.getByRole('button',{name:'従者を置く',exact:true}));}for(const p of table.pages)await click(p.getByRole('button',{name:'従者を置かず進む',exact:true}));await click(page.getByRole('button',{name:'手番を始める',exact:true}));await click(page.getByRole('button',{name:'カードを引く',exact:true}));await page.reload();expect(views.get(a)!.game!.self.stats).toEqual({...base,followerLimit:3,followerLevelBonus:1,moraleBonus:1});expect(game().players[a]!.open).toContain('a2-p01-r2c1');
 if(placement||transfer){const panel=page.getByRole('region',{name:'従者の配置',exact:true});await panel.getByRole('combobox',{name:'従者を加える',exact:true}).selectOption(m.third);if(transfer)await panel.getByRole('listitem').nth(2).getByRole('button',{name:'前へ',exact:true}).click();await click(panel.getByRole('button',{name:'この順番で確定',exact:true}));await page.reload();expect(game().players[a]!.followers).toHaveLength(3);expect(game().players[a]!.followers.every(f=>f.face==='back')).toBe(true);}
 if(scenario.endsWith('-army')){const panel=page.getByRole('region',{name:'全軍突撃せよ',exact:true});await panel.getByRole('combobox',{name:'突撃に使う従者',exact:true}).selectOption('a2-p20-r3c1');await panel.getByRole('radio',{name:table.sessions[1]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'2枚を使って全軍突撃する',exact:true}));await page.reload();await settle();const roll=game().recentRolls.find(r=>r.purpose==='follower-morale')!;expect(roll.threshold).toBe(7);expect(game().players[b]!.damage).toBe(roll.success?16:0);}
 else{
  if(game().phase==='action')await click(page.getByRole('button',{name:'行動を終える',exact:true}));const excess=Math.max(0,views.get(a)!.game!.self.hand.length-5);if(excess)await select(0,views.get(a)!.game!.self.hand[0]!);await click(page.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));await settle();await click(bp.getByRole('button',{name:'手番を始める',exact:true}));await click(bp.getByRole('button',{name:'カードを引かない',exact:true}));
  if(transfer){await click(bp.getByRole('button',{name:'祈願を使う（1枚目）',exact:true}));await settle('wish');await bp.reload();const panel=bp.getByRole('complementary',{name:'自分だけの祈願の選択'});await panel.getByRole('combobox',{name:'取得先',exact:true}).selectOption('public');await panel.getByRole('combobox',{name:'取得候補',exact:true}).selectOption('a2-p01-r2c1');await click(panel.getByRole('button',{name:'この候補から1枚取得する',exact:true}));await page.reload();expect(views.get(a)!.game!.self.stats).toEqual(base);expect(views.get(b)!.game!.self.stats).toMatchObject({followerLimit:3,followerLevelBonus:1,moraleBonus:1});const capacity=page.getByRole('complementary',{name:'祈願後の上限調整'});await expect(capacity.getByRole('button',{name:'選んだ札を捨てて続ける',exact:true})).toBeDisabled();if(m.irremovable)await expect(capacity.getByRole('checkbox',{name:'闇の聖女',exact:true})).toHaveCount(0);for(const p of table.pages.slice(1))await expect(p.getByRole('complementary',{name:'祈願後の上限調整'})).toHaveCount(0);await capacity.getByRole('checkbox',{name:'兵士',exact:true}).check();await click(capacity.getByRole('button',{name:'選んだ札を捨てて続ける',exact:true}));await settle();await page.reload();expect(views.get(a)!.game!.self.followers.map(f=>f.cardInstanceId)).toEqual([m.third,'a2-p20-r2c3']);expect((await storedDiscard()).filter(id=>id==='a2-p18-r3c3')).toHaveLength(1);expect(game().players[b]!.open).toContain('a2-p01-r2c1');}
  else if(scenario.endsWith('-death')){await select(1,'a2-p15-r2c2');await bp.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:bp.getByRole('heading',{name:table.sessions[0]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(bp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await settle();expect(game().players[a]!.presence).toBe('dead');expect(views.get(a)!.game!.self.stats).toEqual(base);expect((await storedDiscard()).filter(id=>id==='a2-p01-r2c1')).toHaveLength(1);}
  else{const panel=bp.getByRole('region',{name:'複数従者の攻撃'});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption('c2-p06-r1c2-ab04');await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption('a2-p21-r2c3');await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await panel.getByRole('radio',{name:table.sessions[0]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));await page.reload();await settle();if(m.defense){const roll=game().recentRolls.find(r=>r.purpose==='follower-morale')!;expect(roll.threshold).toBe(scenario.endsWith('-morale')?1:7);expect(game().players[a]!.damage).toBe(roll.success?0:18);}}
 }
 expect(game().logs.filter(e=>e.type==='OPEN'&&e.cardInstanceId==='a2-p01-r2c1')).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
