import {expect,test,type Locator} from '@playwright/test';
import {peacePhysicalScenarios,peaceMode} from '../../apps/worker/test/fixtures/peace-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of peacePhysicalScenarios)test(`${scenario} actual Peace replacement and public action expiry survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=peaceMode(scenario),target=ids[m.target]!,card='a2-p02-r1c1';const game=()=>views.get(a)!.game!,spirit=()=>views.get(target)!.game!.self.stats.spirit;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function select(seat:number,card:string){const index=views.get(ids[seat]!)!.game!.self.hand.indexOf(card);expect(index).toBeGreaterThanOrEqual(0);await table.pages[seat]!.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function step(){const g=game(),w=g.activeWindow;if(w){const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));return;}const seat=g.turnSeat,p=table.pages[seat]!;if(g.phase==='hand-adjustment'){const v=views.get(ids[seat]!)!.game!.self,excess=Math.max(0,v.hand.length-v.stats.handLimit);for(const id of v.hand.slice(0,excess))await select(seat,id);await click(p.getByRole('button',{name:`選んだ${excess}枚を捨てて手番を終える`,exact:true}));return;}const label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;if(!label)throw Error('PEACE_UI_PHASE');await click(p.getByRole('button',{name:label,exact:true}));}
 async function until(done:()=>boolean){for(let n=0;n<300;n++){if(done())return;await step();}throw Error('PEACE_UI_LIMIT');}
 async function next(id:string,phase='action'){await until(()=>!game().activeWindow&&game().seatOrder[game().turnSeat]===id&&game().phase===phase);}
 async function attack(seat:number,cardId:string,targetSeat:number){const p=table.pages[seat]!;await select(seat,cardId);await p.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:p.getByRole('heading',{name:table.sessions[targetSeat]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(p.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}
 async function play(){await until(()=>views.get(d)!.game!.anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId===target));await dp.reload();const o=views.get(d)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===target)!;await click(dp.getByRole('button',{name:o.label,exact:true}));await dp.reload();}
 const base=spirit(),hand=views.get(d)!.game!.self.hand.length;
 if(scenario==='peace-own-ability'){await page.getByRole('combobox',{name:'消費する間合い',exact:true}).selectOption('a2-p07-r1c1');await click(page.getByRole('button',{name:'隠行を使う',exact:true}));}else if(m.current||scenario==='peace-receiving'||scenario==='peace-defense-ability'){await attack(0,m.roll?'a2-p12-r2c2':'a2-p24-r1c2',1);if(m.roll)await until(()=>game().activeWindow?.kind===(scenario==='peace-frozen'?'after-roll':'before-roll'));if(scenario==='peace-receiving')await until(()=>game().activeWindow?.kind==='attack-abilities');if(scenario==='peace-defense-ability'){await until(()=>game().activeWindow?.kind==='normal-defense');await click(bp.getByRole('button',{name:'魅了を使う',exact:true}));}}
 if(scenario==='peace-evil'){await expect(dp.getByRole('button',{name:/^この世界に愛と平和をを使う/})).toHaveCount(0);await next(b);expect(spirit()).toBe(base);expect(views.get(d)!.game!.self.hand).toContain(card);return;}
 const roll=m.roll?structuredClone(game().currentRoll):undefined;await play();expect(views.get(d)!.game!.self.hand).toHaveLength(hand);if(scenario==='peace-canceled'){await until(()=>game().activeWindow?.pendingActorId===c);const panel=table.pages[2]!.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);}else{await until(()=>game().peaceExpiries.length>0);expect(spirit()).toBe(14);const current=m.current||scenario==='peace-defense-ability';for(const p of table.pages)await expect(p.getByRole('region',{name:'愛と平和の期限'})).toContainText(current?'現在の行動とそこから続く反応が終わるまで':'次の本人の手番行動が終わるまで');await table.pages[m.target]!.reload();expect(game().peaceExpiries).toEqual([{targetId:target,timing:current?'current-action':'next-own-action'}]);if(roll&&scenario==='peace-frozen')expect(game().recentRolls.find(r=>r.rollId===roll.rollId)!.threshold).toBe(roll.threshold);
  if(scenario==='peace-counter'){await until(()=>game().activeWindow?.kind==='normal-defense');const panel=bp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p10-r3c3');await click(panel.getByRole('button',{name:'防御する',exact:true}));await until(()=>game().currentAttack?.attackerId===b);expect(spirit()).toBe(14);await page.reload();await expect(page.getByRole('region',{name:'愛と平和の期限'})).toContainText('現在の行動とそこから続く反応が終わるまで');}
  await until(()=>!game().activeWindow);if(current){expect(spirit()).toBe(base);if(scenario==='peace-counter')expect(game().players[a]!.damage).toBe(5);if(roll)expect(game().recentRolls.find(r=>r.rollId===roll.rollId)!.threshold).toBe(scenario==='peace-before-roll'?14:base);}
  else{expect(spirit()).toBe(14);if(m.repeated){await click(dp.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:'秘伝書を使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[d]!.open).toContain('a2-p01-r1c2');if(!views.get(d)!.game!.self.hand.includes(card)){await click(dp.getByRole('button',{name:'祈願を使う（1枚目）',exact:true}));await until(()=>game().activeWindow?.kind==='wish');const panel=dp.getByRole('complementary',{name:'自分だけの祈願の選択'});await panel.getByRole('combobox',{name:'取得先',exact:true}).selectOption('deck');await panel.getByRole('combobox',{name:'取得候補',exact:true}).selectOption('この世界に愛と平和を');await click(panel.getByRole('button',{name:'この候補から1枚取得する',exact:true}));await until(()=>!game().activeWindow);}await play();await until(()=>!game().activeWindow);expect(spirit()).toBe(14);}
   await next(b,scenario==='peace-blood'?'draw':'action');if(scenario==='peace-blood'){await click(bp.getByRole('button',{name:'カードを引く',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.open).toContain('a2-p01-r1c3');expect(spirit()).toBe(15);}if(scenario==='peace-book'){await click(bp.getByRole('region',{name:'手番カードの効果'}).getByRole('button',{name:'秘伝書を使う',exact:true}));await until(()=>!game().activeWindow);expect(spirit()).toBe(14);expect(game().phase).toBe('action');}if(scenario==='peace-next'){await attack(1,'a2-p24-r2c2',0);expect(spirit()).toBe(14);await until(()=>!game().activeWindow);}else if(scenario==='peace-chant'){await select(1,'a2-p13-r1c1');await click(bp.getByRole('button',{name:'詠唱',exact:true}));}else await click(bp.getByRole('button',{name:'行動を終える',exact:true}));
  }
 }
 expect(spirit()).toBe(base+(scenario==='peace-blood'?1:0));expect(game().peaceExpiries).toEqual([]);for(const p of table.pages)await expect(p.getByRole('region',{name:'愛と平和の期限'})).toHaveCount(0);expect((await storedDiscard()).filter(id=>id===card)).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
