import {expect,test,type Locator} from '@playwright/test';
import {PETRIFY,REVIVE} from '../../apps/worker/test/fixtures/petrify-physical-scenarios.js';
import {observe,passUntil,tableFixture} from './helpers.js';
for(const scenario of ['petrify-physical-high','petrify-physical-low'] as const)test(`${scenario} actual spirit result and stone death resurrection retain history after reload`,async({browser,request})=>{
 test.setTimeout(90000);const table=await tableFixture(browser,request,scenario),lethal=scenario.endsWith('-low');
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,page=table.pages[0]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function nextOwn(){for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await passUntil(table,views,v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)return;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}throw Error('PETRIFY_UI_TURN');}async function chant(name:string){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name,exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();await nextOwn();}
 await chant('石化');await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'石化を選ぶ',exact:true}).click();await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='before-roll');expect(views.get(a)!.game!.players[b]).toMatchObject({presence:'active',damage:0});await passUntil(table,views,g=>!g.activeWindow,300);await page.reload();await table.pages[1]!.reload();let done=views.get(a)!.game!;expect(done.players[b]!.presence).toBe(lethal?'dead':'active');expect(done.discard.filter(id=>id===PETRIFY)).toHaveLength(1);if(!lethal){expect(done.players[b]!.damage).toBe(5);expect(done.logs.filter(e=>e.type==='PLAYER_DIED')).toEqual([]);return;}const death=done.logs.find(e=>e.type==='PLAYER_DIED'&&e.actorId===b)!;expect(death).toMatchObject({death:{cause:'petrification',sourceActorId:a,sourceCardInstanceId:PETRIFY}});expect(views.get(b)!.game!.self.hand).toEqual([]);await nextOwn();await chant('復活');await page.getByLabel('手番技として使うカード').selectOption(REVIVE);await page.getByLabel('専用効果を使う',{exact:true}).setChecked(false);await page.getByRole('combobox',{name:'復活させる相手',exact:true}).selectOption(b);await click(page.getByRole('button',{name:'手番技を使う',exact:true}));await page.reload();await passUntil(table,views,g=>g.lifecycleDecision?.kind==='re-setup',300);await table.pages[1]!.reload();await expect.poll(()=>views.get(b)?.game?.self.hand.length).toBe(5);await click(table.pages[1]!.getByRole('button',{name:'従者の配置を終える',exact:true}));await passUntil(table,views,g=>!g.activeWindow);await page.reload();done=views.get(a)!.game!;expect(done.players[b]).toMatchObject({presence:'active',damage:0,statuses:[],followers:[]});expect(done.logs.find(e=>e.type==='PLAYER_DIED'&&e.actorId===b)).toEqual(death);expect(done.discard).toContain(REVIVE);expect(done.phase).toBe('hand-adjustment');
 }finally{await table.close();}
});
