import {expect,test,type Locator} from '@playwright/test';
import {observe,passUntil,tableFixture,storedDiscard} from './helpers.js';
for(const [scenario,selection] of [['prison-ordinary','none'],['prison-dedicated','none'],['prison-dedicated','B'],['prison-dedicated','both']] as const)test(`${scenario} actual chant and optional stop=${selection} retain shared personal duration after reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!,dedicated=scenario==='prison-dedicated';async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function nextOwn(){for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await passUntil(table,views,v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)return;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}throw Error('PRISON_BROWSER_TURN');}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'封獄死霊陣',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));await nextOwn();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'封獄死霊陣を選ぶ',exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const index of dedicated?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();const chosen:string[]=[];
 for(let n=0;n<4;n++){await passUntil(table,views,g=>!g.activeWindow||!!g.lifetimeDecision);const g=views.get(a)!.game!,d=g.lifetimeDecision;if(!d)break;const apply=selection==='both'||selection==='B'&&d.targetId===b;await page.reload();await click(page.getByRole('button',{name:apply?'期間付きの停止を与える':'停止させない',exact:true}));if(apply)chosen.push(d.targetId);}
 await passUntil(table,views,g=>!g.activeWindow);let done=views.get(a)!.game!;expect([done.players[b]!.damage,done.players[c]!.damage]).toEqual([10,dedicated?10:0]);expect(done.players[b]!.followers).toEqual([]);expect(done.players[c]!.followers).toHaveLength(dedicated?0:1);expect((await storedDiscard()).filter(id=>id==='a2-p13-r3c3')).toHaveLength(1);expect(chosen).toEqual(selection==='both'?[b,c]:selection==='B'?[b]:[]);const fixed=chosen.length?done.players[chosen[0]!]!.statuses[0]:undefined;const turns=fixed?.timing==='fixed-turns'?fixed.remainingTurns:0;
 for(const id of [b,c]){expect(done.players[id]!.statuses).toHaveLength(chosen.includes(id)?1:0);if(chosen.includes(id))expect(done.players[id]!.statuses[0]).toMatchObject({timing:'fixed-turns',remainingTurns:turns});}if(chosen.length){expect(turns).toBeGreaterThanOrEqual(1);expect(turns).toBeLessThanOrEqual(6);await table.pages[1]!.reload();await expect(table.pages[1]!.getByRole('region',{name:`${table.sessions[1]!.name}の状態異常`}).first()).toContainText(`あと自分の手番${turns}回`);for(let round=1;round<=turns;round++){if(round>1)await click(page.getByRole('button',{name:'行動を終える',exact:true}));await nextOwn();done=views.get(a)!.game!;for(const id of chosen){expect(done.players[id]!.statuses).toHaveLength(round===turns?0:1);if(round<turns)expect(done.players[id]!.statuses[0]).toMatchObject({remainingTurns:turns-round});}}await table.pages[1]!.reload();expect(views.get(b)!.game!.players[b]!.statuses).toEqual([]);}
 }finally{await table.close();}
});
