import {expect,test,type Locator} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {observe,passUntil,tableFixture} from './helpers.js';
type Table=Awaited<ReturnType<typeof tableFixture>>;type Views=Awaited<ReturnType<typeof observe>>;
async function click(table:Table,views:Views,button:Locator){const a=table.sessions[0]!.id,rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
test('R6 actual parry and Soldier across three hits retain one simultaneous death batch on reload',async({browser,request})=>{const table=await tableFixture(browser,request,'r6-combined-death');try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,bp=table.pages[1]!,oldB=views.get(b)!.game!.self.damage,oldC=views.get(c)!.game!.self.damage;await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p12-r1c3');await click(table,views,bp.getByRole('button',{name:'防御する',exact:true}));await bp.reload();await passUntil(table,views,g=>g.players[b]!.presence==='pending-death',400);expect(views.get(a)!.game!.players[c]!.presence).toBe('pending-death');expect(views.get(b)!.game!.self.damage).toBe(oldB+14);expect(views.get(c)!.game!.self.damage).toBe(oldC+18);await table.pages[2]!.reload();await passUntil(table,views,g=>!g.activeWindow,400);await bp.reload();expect(views.get(a)!.game!.players[b]!.presence).toBe('dead');expect(views.get(a)!.game!.players[c]!.presence).toBe('dead');expect(views.get(a)!.game!.outcome).toBeNull();}finally{await table.close();}});
for(const revived of [false,true])test(`R6 suppression ${revived?'after actual revival':'after frozen value'} keeps the applicable ability boundary across reload`,async({browser,request})=>{const table=await tableFixture(browser,request,revived?'r6-combined-revived':'r6-combined-suppression');try{const views=await observe(table),a=table.sessions[0]!.id,c=table.sessions[2]!.id,ap=table.pages[0]!;if(revived){expect(views.get(a)!.game!.self.damage).toBe(0);await expect(ap.getByRole('button',{name:'気合いを使う',exact:true})).toHaveCount(0);await ap.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='normal-defense',400);expect(views.get(a)!.game!.currentAttack!.technique.effectLevel).toBe(4);}
else {await click(table,views,ap.getByRole('button',{name:'気合いを使う',exact:true}));await passUntil(table,views,g=>g.activeWindow?.kind==='damage'&&g.activeWindow.pendingActorId===c,400);expect(views.get(a)!.game!.actionCalculation!.effectLevel).toBe(6);const panel=table.pages[2]!.getByRole('region',{name:'能力の禁止と祝福'});await panel.getByRole('checkbox',{name:table.sessions[0]!.name,exact:true}).check();await click(table,views,panel.getByRole('button',{name:'神と人の差を使う',exact:true}));await table.pages[2]!.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='normal-defense',400);expect(views.get(a)!.game!.currentAttack!.technique.effectLevel).toBe(6);}
await passUntil(table,views,g=>!g.activeWindow,400);await ap.reload();expect(views.get(a)!.game!.phase).toBe('withdrawal');}finally{await table.close();}});
test('R6 cancellation refills once then reserves and returns the same physical card with its replacement retained',async({browser,request})=>{const table=await tableFixture(browser,request,'reclaim-owned');try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,ap=table.pages[0]!,bp=table.pages[1]!,hand=[...views.get(b)!.game!.self.hand],heal=views.get(a)!.game!.self.hand.find(id=>getAction(id)!.name==='封傷')!,fate='a2-p02-r2c3';await ap.getByLabel('手番技として使うカード').selectOption(heal);await click(table,views,ap.getByRole('button',{name:'手番技を使う',exact:true}));await click(table,views,ap.getByRole('button',{name:'パス',exact:true}));await bp.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(fate);await click(table,views,bp.getByRole('button',{name:'割り込みを使う',exact:true}));expect(views.get(b)!.game!.self.hand).toHaveLength(hand.length);const replacement=views.get(b)!.game!.self.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();await passUntil(table,views,g=>g.activeWindow?.kind==='reclaim',300);await click(table,views,bp.getByRole('button',{name:'通常回収（この名称は試合中1回）',exact:true}));await bp.reload();expect(views.get(b)!.game!.reservedCards).toContain(fate);expect(views.get(b)!.game!.self.hand).not.toContain(fate);await passUntil(table,views,g=>!g.activeWindow,300);await bp.reload();expect(views.get(b)!.game!.self.hand).toHaveLength(hand.length+1);expect(views.get(b)!.game!.self.hand).toContain(replacement);expect(views.get(b)!.game!.self.hand.filter(id=>id===fate)).toHaveLength(1);}finally{await table.close();}});
