import {expect,test,type Locator} from '@playwright/test';
import {observe,passUntil,tableFixture} from './helpers.js';
for(const [scenario,convert] of [['resurrection-ordinary',false],['resurrection-dedicated',false],['resurrection-dedicated',true],['resurrection-chanted-dedicated',true]] as const)test(`${scenario} actual chant cast conversion=${convert} and sequential re-setup survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!,dedicated=scenario!=='resurrection-ordinary';expect([views.get(a)!.game!.players[b]!.presence,views.get(a)!.game!.players[c]!.presence]).toEqual(['dead','dead']);async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 if(scenario!=='resurrection-dedicated'){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'復活',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await passUntil(table,views,v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}}
 await page.getByLabel('手番技として使うカード').selectOption('a2-p13-r3c1');await page.getByLabel('専用効果を使う',{exact:true}).setChecked(dedicated);if(dedicated){for(const index of [1,2])await page.getByRole('group',{name:'復活させる相手（複数選択可）'}).getByLabel(table.sessions[index]!.name,{exact:true}).check();if(convert)await page.getByLabel(`${table.sessions[1]!.name}の陣営・目的を自分と同じにする`).check();}else await page.getByRole('combobox',{name:'復活させる相手',exact:true}).selectOption(b);await click(page.getByRole('button',{name:'手番技を使う',exact:true}));await page.reload();
 for(const index of dedicated?[1,2]:[1]){const id=table.sessions[index]!.id;await passUntil(table,views,g=>g.lifecycleDecision?.kind==='re-setup');await expect.poll(()=>views.get(id)?.game?.self.hand.length).toBe(5);expect(views.get(a)!.game!.players[id]).toMatchObject({presence:'active',damage:0,attachments:[],followers:[]});await table.pages[index]!.reload();await click(table.pages[index]!.getByRole('button',{name:'従者の配置を終える',exact:true}));}
 await passUntil(table,views,g=>!g.activeWindow);await page.reload();const done=views.get(a)!.game!;expect([done.players[b]!.presence,done.players[c]!.presence]).toEqual(dedicated?['active','active']:['active','dead']);expect(views.get(b)!.game!.self.faction).toBe(convert?'EVIL':'GOOD');expect(done.discard.filter(id=>id==='a2-p13-r3c1')).toHaveLength(1);expect(done.discard).toContain('a2-p03-r3c1');expect(done.phase).toBe('hand-adjustment');
 }finally{await table.close();}
});
