import {expect,test,type Locator} from '@playwright/test';
import {RIFT,DAWN} from '../../apps/worker/test/fixtures/rift-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of ['rift-physical-ordinary-low','rift-physical-dedicated-low'] as const)test(`${scenario} actual chant multi target choices and Wish Dawn return survive reload`,async({browser,request})=>{
 test.setTimeout(90000);const table=await tableFixture(browser,request,scenario,6),dedicated=scenario.includes('dedicated');
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,page=table.pages[0]!,targets=table.sessions.slice(1,dedicated?6:4).map(p=>p.id);async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean){for(let n=0;n<600;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await click(table.pages[table.sessions.findIndex(p=>p.id===actor)]!.getByRole('button',{name:windowPassButtonName}));}throw Error('RIFT_UI_WINDOW_LIMIT');}async function nextOwn(){for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)return;const actor=g.seatOrder[g.turnSeat]!;await expect.poll(()=>views.get(actor)?.revision).toBe(views.get(a)!.revision);const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}throw Error('RIFT_UI_TURN_LIMIT');}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'裂界',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();expect(views.get(a)!.game!.self.chants[0]!.cardInstanceId).toBe(RIFT);await nextOwn();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'裂界を選ぶ',exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const session of table.sessions.filter(p=>targets.includes(p.id)))await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:session.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();const before=views.get(b)!.game!.self;await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();const chosen:string[]=[];for(let n=0;n<6;n++){await settle(g=>!g.activeWindow||!!g.lifetimeDecision);const d=views.get(a)!.game!.lifetimeDecision;if(!d)break;await page.reload();await click(page.getByRole('button',{name:d.targetId===b?'精神力−3で判定する':'補正なしで判定する',exact:true}));chosen.push(d.targetId);}await settle(g=>!g.activeWindow);await page.reload();let done=views.get(a)!.game!;expect(chosen).toEqual(dedicated?targets:[]);for(const id of targets)expect(done.players[id]).toMatchObject({presence:'otherworld',damage:dedicated?12:8});expect(done.discard.filter(id=>id===RIFT)).toHaveLength(1);expect(done.players[b]!.followers).toHaveLength(1);await table.pages[1]!.reload();expect(views.get(b)!.game!.self.hand).toEqual(before.hand);expect(views.get(b)!.game!.self.followers).toEqual(before.followers);await nextOwn();await click(page.getByRole('button',{name:'祈願を使う（1枚目）',exact:true}));await settle(g=>g.activeWindow?.kind==='wish');await page.reload();const wish=views.get(a)!.game!.wish!,panel=page.getByRole('complementary',{name:'自分だけの祈願の選択'});for(const id of targets){expect(wish.handOwners.some(o=>o.ownerId===id)).toBe(false);expect(wish.publicSources.some(o=>o.ownerId===id)).toBe(false);}await panel.getByRole('combobox',{name:'取得候補',exact:true}).selectOption('大陸の夜明け');await click(panel.getByRole('button',{name:'この候補から1枚取得する',exact:true}));await settle(g=>!g.activeWindow);await page.reload();await table.pages[1]!.reload();done=views.get(a)!.game!;for(const id of targets)expect(done.players[id]).toMatchObject({presence:'active',damage:dedicated?12:8});expect(done.players[a]!.open).toContain(DAWN);expect(done.logs.filter(e=>e.type==='PLAYER_RETURNED').map(e=>e.actorId)).toEqual(targets);expect(views.get(b)!.game!.self.hand).toEqual(before.hand);expect(views.get(b)!.game!.self.followers).toEqual(before.followers);
 }finally{await table.close();}
});
