import type {Browser,APIRequestContext} from '@playwright/test';
import {expect,test} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {observe,passUntil,tableFixture} from './helpers.js';
async function verifyS26(browser:Browser,request:APIRequestContext,scenario:'r6-s26-revive'|'r6-s26-return'){const table=await tableFixture(browser,request,scenario);try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,ap=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!;
 if(scenario==='r6-s26-revive'){expect(views.get(a)!.game!.players[b]!.presence).toBe('wandering');expect(views.get(a)!.game!.players[c]!.presence).toBe('dead');await ap.reload();const panel=ap.getByRole('region',{name:'回復と復活の手番技'});await panel.getByRole('combobox',{name:'手番技として使うカード'}).selectOption('a2-p13-r3c1');await panel.getByRole('checkbox',{name:'専用効果を使う',exact:true}).check();await panel.getByRole('checkbox',{name:table.sessions[2]!.name,exact:true}).check();let revision=views.get(a)!.revision;await panel.getByRole('button',{name:'手番技を使う',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(revision);await passUntil(table,views,g=>g.activeWindow?.kind==='re-setup',300);expect(views.get(c)!.game!.self.hand).toHaveLength(5);expect(views.get(a)!.game!.players[b]!.presence).toBe('wandering');await cp.reload();revision=views.get(a)!.revision;await cp.getByRole('button',{name:'従者の配置を終える',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(revision);}
 await bp.reload();expect(views.get(a)!.game!.players[b]).toMatchObject({presence:'active',damage:2});expect(views.get(b)!.game!.self.hand).toHaveLength(5);expect(views.get(b)!.game!.self.followers).toEqual([]);const follower=views.get(b)!.game!.self.hand.find(id=>getAction(id)!.name==='小人族')!;await bp.getByRole('combobox',{name:'配置する従者',exact:true}).selectOption(follower);let revision=views.get(a)!.revision;await bp.getByRole('button',{name:'この従者を配置する',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(revision);expect(views.get(b)!.game!.self.hand).toHaveLength(5);expect(views.get(b)!.game!.self.followers[0]!.cardInstanceId).toBe(follower);await bp.reload();revision=views.get(a)!.revision;await bp.getByRole('button',{name:'従者の配置を終える',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(revision);await passUntil(table,views,g=>!g.activeWindow,300);expect(views.get(a)!.game!.phase).toBe('hand-adjustment');expect(views.get(a)!.game!.turnSeat).toBe(0);expect(views.get(a)!.game!.outcome).toBeNull();}finally{await table.close();}}
test('S26 r6-s26-revive restores protected wanderer with five fresh cards and a newly placed follower',async({browser,request})=>{await verifyS26(browser,request,'r6-s26-revive');});
test('S26 r6-s26-return restores protected wanderer with five fresh cards and a newly placed follower',async({browser,request})=>{await verifyS26(browser,request,'r6-s26-return');});
