import {expect,test,type Page,type Browser,type APIRequestContext} from '@playwright/test';
import {observe,passUntil,tableFixture} from './helpers.js';
async function choose(page:Page,card:string,mode:string){await page.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption(mode);await page.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(card);await page.getByRole('button',{name:'割り込みを使う',exact:true}).click();}
async function verifyRoll(browser:Browser,request:APIRequestContext,mode:'force'|'cancel'|'reroll'){const table=await tableFixture(browser,request,mode==='force'?'r6-s01-s02-s05':mode==='reroll'?'canonical-S04':'r6-s03-s04');try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,parent=views.get(a)!.game!.activeWindow!,original=views.get(b)!.game!.currentRoll!,bp=table.pages[1]!;expect(original.faces).toEqual([2,3]);
 if(mode==='force'){await expect(table.pages[3]!.getByRole('button',{name:'割り込みを使う',exact:true})).toHaveCount(0);let rev=views.get(a)!.revision;await choose(table.pages[2]!,'a2-p02-r2c3','force-fail');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);await passUntil(table,views,g=>g.activeWindow?.windowId===parent.windowId,300);expect(views.get(a)!.game!.activeWindow!.windowRevision).toBeGreaterThan(parent.windowRevision);await table.pages[2]!.reload();await passUntil(table,views,g=>g.activeWindow?.pendingActorId===table.sessions[3]!.id,300);rev=views.get(a)!.revision;await choose(table.pages[3]!,'a2-p02-r1c3','reroll');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 else {const rev=views.get(a)!.revision;await choose(bp,'a2-p02-r1c3','reroll');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);await bp.reload();expect(views.get(b)!.game!.self.hand).not.toContain('a2-p02-r1c3');if(mode==='cancel'){const rev=views.get(a)!.revision;await choose(table.pages[2]!,'a2-p02-r2c3','cancel');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}}
 await passUntil(table,views,g=>g.activeWindow?.windowId===parent.windowId,300);const roll=structuredClone(views.get(b)!.game!.currentRoll!);expect(roll.rollId).toBe(original.rollId);expect(roll.generation).toBe(mode==='cancel'?0:1);if(mode==='cancel')expect(roll.faces).toEqual([2,3]);if(mode==='force')expect(roll).toMatchObject({forcedFailure:true,success:false});if(mode==='reroll'){expect(roll).toMatchObject({faces:[4,4],total:8,success:true});expect(roll.attempts.map(attempt=>attempt.faces)).toEqual([[2,3],[4,4]]);for(const [seat,page] of table.pages.entries()){await page.reload();expect(views.get(table.sessions[seat]!.id)!.game!.currentRoll).toMatchObject({rollId:original.rollId,faces:[4,4],generation:1});}}await bp.reload();expect(views.get(b)!.game!.currentRoll).toEqual(roll);await passUntil(table,views,g=>!g.activeWindow,300);expect(views.get(b)!.game!.recentRolls.find(r=>r.rollId===roll.rollId)!.faces).toEqual(roll.faces);expect(views.get(a)!.game!.phase).toBe('withdrawal');if(mode==='reroll')for(const [seat,page] of table.pages.entries()){await page.reload();const final=views.get(table.sessions[seat]!.id)!.game!.recentRolls.find(r=>r.rollId===roll.rollId)!;expect(final.faces).toEqual([4,4]);expect(final.attempts.map(attempt=>attempt.faces)).toEqual([[2,3],[4,4]]);}}finally{await table.close();}}
test('S01-S05 force retains priority paid cards and roll continuation across reload',async({browser,request})=>{await verifyRoll(browser,request,'force');});
test('S01-S05 cancel retains priority paid cards and roll continuation across reload',async({browser,request})=>{await verifyRoll(browser,request,'cancel');});
test('S01-S05 reroll retains priority paid cards and roll continuation across reload',async({browser,request})=>{await verifyRoll(browser,request,'reroll');});
test('S02 canceled C intervention returns parent priority to A across reload',async({browser,request})=>{
 const table=await tableFixture(browser,request,'r6-s02-cancel-child');try{
 const views=await observe(table),[a,b,c,d]=table.sessions.map(p=>p.id) as [string,string,string,string],parent=structuredClone(views.get(a)!.game!.activeWindow!),roll=structuredClone(views.get(b)!.game!.currentRoll!);
 expect(parent.pendingActorId).toBe(c);
 let rev=views.get(a)!.revision;await choose(table.pages[2]!,'a2-p02-r1c3','reroll');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);await table.pages[2]!.reload();expect(views.get(a)!.game!.activeWindow!.pendingActorId).toBe(d);
 rev=views.get(a)!.revision;await choose(table.pages[3]!,'a2-p02-r2c3','cancel');await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);
 await passUntil(table,views,g=>g.activeWindow?.windowId===parent.windowId,300);await table.pages[0]!.reload();
 const restored=views.get(a)!.game!.activeWindow!;expect(restored.pendingActorId).toBe(a);expect(restored.windowRevision).toBeGreaterThan(parent.windowRevision);expect(views.get(b)!.game!.currentRoll).toEqual(roll);
 rev=views.get(a)!.revision;await table.pages[0]!.getByRole('button',{name:'パス',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);expect(views.get(a)!.game!.activeWindow!.pendingActorId).toBe(b);
 }finally{await table.close();}
});
