import {expect,test,type Locator} from '@playwright/test';
import {SCYTHE} from '../../apps/worker/test/fixtures/scythe-physical-scenarios.js';
import {observe,passUntil,tableFixture,storedDiscard} from './helpers.js';
for(const [scenario,requestB] of [['scythe-physical-ordinary-low',false],['scythe-physical-dedicated-low',false],['scythe-physical-dedicated-low',true]] as const)test(`${scenario} actual chant and optional B death=${requestB} retain body damage and persisted choices`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),dedicated=scenario.includes('dedicated');
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,page=table.pages[0]!;async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
 await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:'死刻鎌',exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();expect(views.get(a)!.game!.self.chants[0]!.cardInstanceId).toBe(SCYTHE);for(let n=0;n<150;n++){const g=views.get(a)!.game!;if(g.activeWindow){await passUntil(table,views,v=>!v.activeWindow);continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':'手番を始める';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'死刻鎌を選ぶ',exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const index of dedicated?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='normal-defense');expect(views.get(b)!.game!.currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);const choices:string[]=[];for(let n=0;n<3;n++){await passUntil(table,views,g=>!g.activeWindow||!!g.lifetimeDecision,300);const d=views.get(a)!.game!.lifetimeDecision;if(!d)break;await page.reload();expect(views.get(a)!.game!.players[b]!.presence).toBe('active');expect(views.get(a)!.game!.players[b]!.damage).toBe(0);expect(views.get(b)!.game!.lifetimeDecision).toBeNull();await click(page.getByRole('button',{name:requestB&&d.targetId===b?'即死の判定を要求する':'要求しない',exact:true}));choices.push(d.targetId);}await passUntil(table,views,g=>!g.activeWindow,300);await page.reload();await table.pages[1]!.reload();const done=views.get(a)!.game!;expect(choices).toEqual(dedicated?[b,c]:[]);expect(done.players[b]!.presence).toBe(requestB?'dead':'active');if(!requestB)expect(done.players[b]!.damage).toBe(3);expect(done.players[c]).toMatchObject({presence:'active',damage:dedicated?7:0});expect((await storedDiscard()).filter(id=>id===SCYTHE)).toHaveLength(1);expect(done.self.chants).toEqual([]);expect(done.logs.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(requestB?[b]:[]);if(requestB)expect(views.get(b)!.game!.self.hand).toEqual([]);
 }finally{await table.close();}
});
