import {expect,test,type Locator} from '@playwright/test';
import {shadowCard as CARD,shadowChild as CHILD,shadowCardMode} from '../../apps/worker/test/fixtures/shadow-card-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of ['shadow-card-ordinary','shadow-card-owner-ordinary','shadow-card-dedicated','shadow-card-low-dedicated','shadow-card-shin-ordinary','shadow-card-shin-dedicated','shadow-card-high','shadow-card-near','shadow-card-suppressed','shadow-card-silenced','shadow-card-stopped','shadow-card-prohibited','shadow-card-wrong-owner','shadow-card-decline','shadow-card-grant-decline','shadow-card-defense-fate','shadow-card-child-fate','shadow-card-child-chant','shadow-card-child-unchanted','shadow-card-child-follower','shadow-card-multi','shadow-card-shin-multi'] as const)test(`${scenario} actual fixed defense and one printed child use survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[1]!,dp=table.pages[3]!,m=shadowCardMode(scenario),game=()=>views.get(a)!.game!,bg=()=>views.get(b)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<800;n++){if(done())return;await step();}throw Error('SHADOW_CARD_UI_LIMIT');}
  const defense=page.getByRole('complementary',{name:'現在の判断'}),hand=[...own(b).hand],followers=structuredClone(own(a).followers),distances=structuredClone(game().distances);
  if(scenario==='shadow-card-stopped'){expect(bg().legalChoices).not.toContain('PLAY_DEFENSE');expect(own(b).hand).toContain(CARD);return;}
  if(scenario==='shadow-card-decline'){await until(()=>!game().activeWindow);expect(own(b).hand).toContain(CARD);expect(game().players[b]!.damage).toBe(4);return;}
  await defense.getByLabel('専用技として使う',{exact:true}).setChecked(m.dedicated);if(scenario==='shadow-card-prohibited'){await expect(defense.getByRole('combobox',{name:'使うカード',exact:true}).locator(`option[value="${CARD}"]`)).toHaveCount(0);expect(own(b).hand).toEqual(hand);return;}
  await defense.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);if(scenario==='shadow-card-wrong-owner'){await expect(defense.getByRole('button',{name:'防御する',exact:true})).toBeDisabled();expect(own(b).hand).toEqual(hand);return;}await click(defense.getByRole('button',{name:'防御する',exact:true}));expect(own(b).hand).toEqual(hand.filter(id=>id!==CARD));await page.reload();
  async function fate(){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));}
  if(scenario==='shadow-card-defense-fate'){await fate();await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(4);expect(own(b).hand).toContain(CHILD);expect(game().discard).toContain(CARD);return;}
  let usedChild=false,defenseSuccess=true,childSuccess=true,enemySuccess=false;const selected=scenario==='shadow-card-child-unchanted'?CHILD:m.child;
  if(scenario==='shadow-card-low-dedicated'){await until(()=>bg().currentRoll?.purpose==='excess-level'&&bg().currentRoll?.stage==='after-roll');expect(bg().currentRoll!.threshold).toBe(6);defenseSuccess=bg().currentRoll!.success!;}
  if(defenseSuccess&&m.dedicated&&!m.shin){await until(()=>game().activeWindow?.kind==='ability-attack');expect(bg().additionalAttack).toMatchObject({source:'card',sourceCardInstanceId:CARD,actorId:b,targetId:a});expect(game().additionalAttackOptions).toEqual([]);await page.reload();const grant=page.getByRole('complementary',{name:'影分身による追加攻撃'});await expect(grant.getByRole('heading',{name:'影分身による追加攻撃を選ぶ',exact:true})).toBeVisible();
   if(scenario==='shadow-card-grant-decline')await click(grant.getByRole('button',{name:'追加攻撃をしない',exact:true}));else{const select=grant.getByLabel('追加攻撃に使うカード');if(scenario==='shadow-card-child-unchanted'){await expect(select.locator('option[value="a2-p13-r1c1"]')).toHaveCount(0);await expect(select.locator('option[value="a2-p08-r3c1"]')).toHaveCount(0);}if(scenario==='shadow-card-child-chant')await expect(select.locator('option[value="a2-p13-r1c1"]')).toHaveText('氷狼乱舞陣（詠唱中）');await select.selectOption(selected);if(scenario==='shadow-card-near')await grant.getByLabel('専用技として使う',{exact:true}).check();await click(grant.getByRole('button',{name:'追加攻撃を行う',exact:true}));usedChild=true;if(scenario==='shadow-card-child-fate')await fate();else if(scenario==='shadow-card-low-dedicated'){await until(()=>bg().currentRoll?.purpose==='excess-level'&&bg().currentRoll?.stage==='after-roll');childSuccess=bg().currentRoll!.success!;}}
  }else if(defenseSuccess&&!m.dedicated&&!m.shin){await until(()=>game().currentRoll?.purpose==='technique-check'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll).toMatchObject({rollerId:a,modifier:-1,threshold:5});enemySuccess=game().currentRoll!.success!;}
  await until(()=>!game().activeWindow);const expectedB=m.multi?m.shin?21:14:!defenseSuccess||m.shin||enemySuccess?m.damage:0,expectedA=usedChild&&childSuccess&&scenario!=='shadow-card-child-fate'&&scenario!=='shadow-card-child-follower'?scenario==='shadow-card-near'?5:7:0;expect(game().players[b]!.damage).toBe(expectedB);expect(game().players[a]!.damage).toBe(expectedA);expect(game().players[c]!.damage).toBe(m.multi&&m.shin?21:0);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);if(usedChild)expect(game().discard.filter(id=>id===selected)).toHaveLength(1);else expect(own(b).hand).toContain(CHILD);expect(game().distances).toEqual(distances);expect(game().phase).toBe('withdrawal');if(scenario==='shadow-card-child-follower'){expect(own(a).followers[0]!.revealed).toBe(true);expect(own(a).followers[0]!.cardInstanceId).toBe(followers[0]!.cardInstanceId);}if(scenario==='shadow-card-child-chant')expect(own(b).chants).toEqual([]);await page.reload();expect(own(b).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
