import {expect,test,type Locator} from '@playwright/test';
import {shurikenCard as CARD,shurikenChants as CHANTS,shurikenMode} from '../../apps/worker/test/fixtures/shuriken-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of ['shuriken-guard','shuriken-owner-ordinary','shuriken-dedicated','shuriken-all','shuriken-keep','shuriken-mixed','shuriken-fate','shuriken-maai','shuriken-evade','shuriken-counter-ordinary','shuriken-counter-equal','shuriken-counter-dedicated','shuriken-wrong-owner','shuriken-decline'] as const)test(`${scenario} actual attack and counter controls keep random damage and all-chant election through reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=shurikenMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('SHURIKEN_UI_LIMIT');}
  if(scenario==='shuriken-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  const targets=m.counter?[b]:scenario==='shuriken-all'?[b,c,d]:m.dedicated?[b,c]:[b],hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),bChants=structuredClone(own(b).chants),cChants=structuredClone(own(c).chants);if(m.guard){expect(bChants.map(c=>c.cardInstanceId)).toEqual(CHANTS.slice(0,2));expect(cChants.map(c=>c.cardInstanceId)).toEqual([CHANTS[2]]);for(const id of CHANTS)expect(JSON.stringify(game())).not.toContain(id);}
  if(m.counter){const reaction=page.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);await click(reaction.getByRole('button',{name:'防御する',exact:true}));}
  else {await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});if(scenario==='shuriken-wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}await click(execute);}
  expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(scenario==='shuriken-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(0);expect(own(b).chants).toEqual(bChants);expect(own(c).chants).toEqual(cChants);expect(game().discard).toContain(CARD);return;}
  let damage=5;if(m.dedicated){await until(()=>game().currentRoll?.purpose==='attack-damage'&&game().currentRoll?.stage==='after-roll');damage=game().currentRoll!.total!;expect([5,10,15,20,25,30]).toContain(damage);expect(game().currentRoll!.formula).toBe('d6x5');await page.reload();}
  if(!m.counter){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?6:4,damage,attributes:['戦','忍','反']});}
  if(scenario==='shuriken-maai'||scenario==='shuriken-evade'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(scenario==='shuriken-maai'?'a2-p06-r1c3':'a2-p05-r3c1');await click(reaction.getByRole('button',{name:scenario==='shuriken-maai'?'間合いを使う':'防御する',exact:true}));}
  const removed:string[]=[];let choices=0;for(let n=0;n<500&&game().activeWindow;n++){if(game().activeWindow!.kind==='on-hit-choice'){const id=game().currentAttack!.targetId!;choices++;const discard=scenario!=='shuriken-keep'&&(scenario!=='shuriken-mixed'||id===b);for(const ch of own(id).chants)expect(JSON.stringify(game())).not.toContain(ch.cardInstanceId);await page.reload();const reaction=page.getByRole('complementary',{name:'現在の判断'});await expect(reaction).toContainText(`詠唱 ${own(id).chants.length}枚`);if(discard)removed.push(id);await click(reaction.getByRole('button',{name:discard?'詠唱中の技をすべて捨てさせる':'使用しない',exact:true}));}else await step();}
  const evaded=['shuriken-maai','shuriken-evade'].includes(scenario);expect(game().activeWindow).toBeNull();for(const id of [b,c,d])expect(game().players[id]!.damage).toBe(scenario==='shuriken-counter-equal'||id===b&&evaded?0:targets.includes(id)&&(!m.guard||m.dedicated)?damage:0);expect(game().players[a]!.damage).toBe(0);if(m.dedicated){expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);}else if(m.guard)expect(own(b).followers[0]!.revealed).toBe(true);expect(own(b).chants).toEqual(removed.includes(b)?[]:bChants);expect(own(c).chants).toEqual(removed.includes(c)?[]:cChants);expect(choices).toBe(m.dedicated?targets.filter(id=>id===c||id===b&&!evaded).length:0);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
