import {expect,test,type Locator} from '@playwright/test';
import {skyWingCard as CARD,skyWingMode} from '../../apps/worker/test/fixtures/sky-wing-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of ['sky-wing-ordinary','sky-wing-guard','sky-wing-dedicated','sky-wing-post-one','sky-wing-post-two','sky-wing-defense-advance','sky-wing-maai-two','sky-wing-fate','sky-wing-wrong-owner','sky-wing-decline'] as const)test(`${scenario} real chant intervening turns and separate physical hit costs survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=skyWingMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('SKY_WING_UI_LIMIT');}
  if(scenario==='sky-wing-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true}),target=page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[b]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true});
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await target.check();await expect(execute).toBeDisabled();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();expect(own(a).chants.map(c=>c.cardInstanceId)).toContain(CARD);
  for(let n=0;n<300;n++){const g=game();if(g.activeWindow){await step();continue;}if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;const label=g.phase==='action'?'行動を終える':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':'離脱しない';await click(table.pages[g.turnSeat]!.getByRole('button',{name:label,exact:true}));}
  await page.reload();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'黒翼天翔剣を選ぶ',exact:true}).click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await target.check();if(scenario==='sky-wing-wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).chants.map(c=>c.cardInstanceId)).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,followers=structuredClone(own(b).followers);await click(execute);expect(own(a).hand).toEqual(hand);expect(own(a).chants).toEqual([]);expect(game().deckCount).toBe(deck);await page.reload();
  if(scenario==='sky-wing-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(followers);expect(game().discard).toContain(CARD);return;}
  await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?8:7,damage:m.dedicated?15:12,attributes:['戦','剣','詠']});
  if(scenario==='sky-wing-maai-two'||scenario==='sky-wing-defense-advance'){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});for(const card of ['a2-p06-r1c3','a2-p07-r1c1']){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(card);await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));await until(()=>game().activeWindow?.kind!=='reclaim');}if(scenario==='sky-wing-defense-advance'){await until(()=>game().activeWindow?.kind==='defense-advance');const attackReaction=page.getByRole('complementary',{name:'現在の判断'});await attackReaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p24-r1c3');await click(attackReaction.getByRole('button',{name:'踏み込みを使う',exact:true}));}}
  const payment=scenario==='sky-wing-post-two'?['a2-p24-r1c3','a2-p24-r2c1']:scenario==='sky-wing-post-one'?['a2-p24-r1c3']:scenario==='sky-wing-defense-advance'?['a2-p24-r2c1']:[];
  if(m.dedicated&&scenario!=='sky-wing-maai-two'){await until(()=>game().activeWindow?.kind==='hit-advance-choice');expect(game().players[b]!.damage).toBe(0);await page.reload();const panel=page.getByRole('region',{name:'技の追加効果',exact:true}),decision=game().techniqueDecision!;expect(decision.kind).toBe('hit-advance');if(decision.kind==='hit-advance'){const pool=decision.cardInstanceIds.filter(id=>own(a).hand.includes(id));for(const id of payment)await panel.getByRole('checkbox').nth(pool.indexOf(id)).check();}const before=[...own(a).hand];await click(panel.getByRole('button',{name:payment.length?'踏み込みを消費して追加する':'追加しない',exact:true}));expect(own(a).hand).toEqual(before.filter(id=>!payment.includes(id)));expect(game().deckCount).toBe(deck);}
  await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(scenario==='sky-wing-maai-two'?0:m.dedicated?15+5*payment.length:m.guard?7:12);if(m.dedicated)expect(own(b).followers).toEqual(followers);else if(m.guard)expect(own(b).followers).toEqual([]);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);for(const id of payment)expect(game().discard.filter(x=>x===id)).toHaveLength(1);await page.reload();expect(own(a).chants).toEqual([]);expect(errors).toEqual([]);
 }finally{await table.close();}
});
