import {expect,test,type Locator} from '@playwright/test';
import {slayingFistScenarios,slayingFistCard as CARD,slayingFistMode} from '../../apps/worker/test/fixtures/slaying-fist-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of slayingFistScenarios)test(`${scenario} actual Slaying Fist fixed ten named target doubling owner choice and physical defenses survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=slayingFistMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('SLAYING_FIST_UI_LIMIT');}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});
  if(scenario==='slaying-fist-stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.decline){const guards=[structuredClone(own(b).followers),structuredClone(own(c).followers)];await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);expect([own(b).followers,own(c).followers]).toEqual(guards);return;}
  if(m.suffix==='noncounter'){const reaction=page.getByRole('complementary',{name:'現在の判断'});expect(game().declarationCandidates.some(candidate=>candidate.kind==='defense'&&candidate.choice.cardInstanceId===CARD&&candidate.abilities.some(ability=>ability.effects.counter))).toBe(true);await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);for(const dedicated of [false,true]){await reaction.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);await expect(reaction.getByRole('button',{name:'防御する',exact:true})).toBeDisabled();}await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).hand).toContain(CARD);return;}
  async function selectCard(id:string){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(id)).getByRole('button').first().click();}
  async function target(){await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[b]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();}
  if(m.suffix==='far'){await selectCard('a2-p24-r1c3');await target();await click(page.getByRole('button',{name:'接近',exact:true}));await until(()=>!game().activeWindow);}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),rolls=game().recentRolls.map(r=>r.rollId);expect(own(a).stats.spirit).toBe(6);expect(own(b).stats.spirit).toBe(11);await selectCard(CARD);await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await target();
  if(m.suffix==='wrong-owner'||m.suffix==='white-prohibited'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);if(m.suffix==='wrong-owner'){await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).uncheck();await expect(execute).toBeEnabled();}return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(m.cancel){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);return;}
  let success=true,fixed=m.damage;if(scenario==='slaying-fist-low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:8,damage:10,attributes:['戦','格','白'],destructionEffects:['黒・死属性の従者を破壊']});expect(game().currentAttack!.targets[0]!.hits[0]!.technique?.damage).toBe(m.damage);if(m.named){expect(game().players[b]!.revealed).toBe(m.publicTarget);if(!m.publicTarget)expect(game().players[b]!.characterId).toBeUndefined();}if(m.maai||m.evade){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});if(m.maai){await expect(bp.getByRole('region',{name:'間合いの状況',exact:true})).toContainText('必要1枚・有効0枚・あと1枚');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c3');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));}else{expect(views.get(b)!.game!.currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p05-r3c1');await click(reaction.getByRole('button',{name:'防御する',exact:true}));}fixed=0;}}
  await until(()=>!game().activeWindow);const morale=views.get(b)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale').at(-1);if(m.follower){if(m.maai||m.evade)expect(own(b).followers).toEqual(bFollowers);else{if(m.black||m.dead)expect(morale).toBeUndefined();else{if(m.water)expect(morale).toBeDefined();if(morale?.success??true)fixed-=m.suffix==='lower'?2:m.suffix==='metal'?5:4;}expect(own(b).followers).toHaveLength(0);expect((await storedDiscard()).filter(id=>id===m.follower)).toHaveLength(1);}}else expect(own(b).followers).toEqual(bFollowers);expect(game().players[b]!.damage).toBe(success?fixed:0);if(m.named)expect(game().players[b]!.revealed).toBe(success&&fixed>0||m.publicTarget);for(const id of [a,c,d])expect(game().players[id]!.damage).toBe(0);expect(own(c).followers).toEqual(cFollowers);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);expect(game().phase).toBe('withdrawal');await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);

 }finally{await table.close();}
});
