import {expect,test,type Locator} from '@playwright/test';
import {starBowScenarios,starBowCard as CARD,starBowMode} from '../../apps/worker/test/fixtures/star-bow-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of starBowScenarios)test(`${scenario} actual Star Bow chant destruction and defense restrictions survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!,dp=table.pages[3]!,m=starBowMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<750;n++){if(done())return;await step();}throw Error('STAR_BOW_UI_LIMIT');}
  async function selectHand(){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('CHANT');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.incoming){const reaction=page.getByRole('complementary',{name:'現在の判断'});if(await reaction.locator(`option[value="${CARD}"]`).count()){await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(CARD);for(const dedicated of [false,true]){await reaction.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);await expect(reaction.getByRole('button',{name:'防御する',exact:true})).toBeDisabled();}}await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).chants.some(c=>c.cardInstanceId===CARD)).toBe(true);return;}
  if(m.suffix.startsWith('chant-')){await selectHand();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);await expect(page.getByRole('button',{name:'攻撃を確認して実行',exact:true})).toBeDisabled();const hand=[...own(a).hand],deck=game().deckCount;await click(page.getByRole('button',{name:'詠唱',exact:true}));expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);expect(own(a).chants[0]!.cardInstanceId).toBe(CARD);await page.reload();for(let n=0;n<200;n++){const g=game();if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;if(g.activeWindow){await step();continue;}const p=table.pages[g.turnSeat]!,label=g.phase==='action'?'行動を終える':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;expect(label).not.toBeNull();await click(p.getByRole('button',{name:label!,exact:true}));}}
  const hand=[...own(a).hand],deck=game().deckCount,rolls=game().recentRolls.map(r=>r.rollId),targets=m.targets.map(i=>ids[i]!),execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true}),unprepared=m.suffix.startsWith('unprepared')||m.suffix==='white-prohibited';if(unprepared)await selectHand();else{expect(own(a).chants[0]!.cardInstanceId).toBe(CARD);await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:'星流弓を選ぶ',exact:true}).click();}await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();if(m.suffix==='wrong-owner'||unprepared){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);if(m.suffix==='white-prohibited')await expect(page.getByRole('button',{name:'詠唱',exact:true})).toBeDisabled();return;}
  await click(execute);expect(own(a).hand).toEqual(hand);expect(own(a).chants).toEqual([]);expect(game().deckCount).toBe(deck);await page.reload();
  if(m.cancel){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);if(m.follower)expect(own(b).followers[0]!.cardInstanceId).toBe(m.follower);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);return;}
  await until(()=>!game().activeWindow||game().activeWindow?.kind==='attack-abilities');if(!game().activeWindow){const checks=game().recentRolls.filter(r=>!rolls.includes(r.rollId)&&['activation','excess-level'].includes(r.purpose));expect(checks.some(r=>r.success===false)).toBe(true);expect(game().players[b]!.damage).toBe(0);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);return;}
  expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?8:7,damage:m.damage,attributes:['戦','弓','白','詠']});expect(game().currentAttack!.targets.map(t=>t.hits.length)).toEqual(targets.map(()=>1));expect(game().currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);await page.reload();
  let bDamage=m.damage;if(m.maai||m.evade){await until(()=>game().activeWindow?.kind==='normal-defense'&&game().activeWindow?.pendingActorId===b);const reaction=bp.getByRole('complementary',{name:'現在の判断'});if(m.evade){await expect(reaction).toContainText('見切り不可');await expect(reaction.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);expect(own(b).hand).toContain('a2-p05-r3c1');}else{const count=m.suffix.includes('one')?1:2;await expect(bp.getByRole('region',{name:'間合いの状況',exact:true})).toContainText('必要2枚・有効0枚・あと2枚');for(const id of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){await until(()=>game().activeWindow?.kind==='normal-defense'&&game().activeWindow?.pendingActorId===b);await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(id);await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));await bp.reload();}if(count===2)bDamage=0;}}
  await until(()=>!game().activeWindow);if(m.follower){if(bDamage===0){expect(own(b).followers[0]!.cardInstanceId).toBe(m.follower);}else{const morale=views.get(b)!.game!.recentRolls.find(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale');let survives=false;if(!m.dedicated&&!m.black&&!m.dead){if(m.water)expect(morale).toBeDefined();if(morale?.success??true){bDamage=m.water?0:m.metal?5:8;survives=m.suffix==='water-blessed-ordinary';}}else expect(morale).toBeUndefined();expect(own(b).followers).toHaveLength(survives?1:0);expect(game().discard.filter(id=>id===m.follower)).toHaveLength(survives?0:1);}}
  expect(game().players[b]!.damage).toBe(bDamage);expect(game().players[c]!.damage).toBe(targets.includes(c)?13:0);expect(game().players[d]!.damage).toBe(targets.includes(d)?13:0);expect(game().discard.filter(id=>id===CARD)).toHaveLength(1);expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId)&&['attack-hit-count','attack-damage'].includes(r.purpose))).toHaveLength(0);expect(own(a).chants).toEqual([]);await page.reload();expect(errors).toEqual([]);
 }finally{await table.close();}
});
