import {stormMagicMode} from '../../apps/worker/test/fixtures/storm-magic-scenarios.js';
import {expect,test,type Locator} from '@playwright/test';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of ['gale-ordinary','gale-dedicated','thunder-ordinary','thunder-dedicated'] as const)test(`${scenario} actual chant follower rules and target cap persist across reload`,async({browser,request})=>{
 const m=stormMagicMode(scenario),{chanted,dedicated,damage}=m;if(chanted)test.setTimeout(90000);
 const table=await tableFixture(browser,request,scenario,m.gale?4:6);
 const errors:string[]=[];for(const page of table.pages)page.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,c=table.sessions[2]!.id,d=table.sessions[3]!.id,page=table.pages[0]!,card=m.card;async function settle(done:(g:NonNullable<NonNullable<ReturnType<typeof views.get>>['game']>)=>boolean,maxSteps=500){for(let n=0;n<maxSteps;n++){const current=views.get(a)!,g=current.game!;if(done(g))return;const w=g.activeWindow!;expect(w).not.toBeNull();const actor=w.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);const actorPage=table.pages[table.sessions.findIndex(p=>p.id===actor)]!;await actorPage.getByRole('button',{name:windowPassButtonName}).click();await expect.poll(()=>({revision:views.get(a)?.revision,errors}),{message:`storm ${scenario} ${w.kind} actor=${actor} window=${w.windowId}`}).toMatchObject({revision:expect.any(Number),errors:[]});await expect.poll(()=>views.get(a)?.revision,{message:`storm ${scenario} ${w.kind} actor=${actor} errors=${errors.join(',')}`}).toBeGreaterThan(current.revision);}throw Error('STORM_UI_WINDOW_LIMIT');}async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);}
  if(chanted){await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();await click(page.getByRole('button',{name:'詠唱',exact:true}));await page.reload();expect(views.get(a)!.game!.self.chants[0]!.cardInstanceId).toBe(card);for(let n=0;n<100;n++){const g=views.get(a)!.game!;if(g.phase==='action'&&g.seatOrder[g.turnSeat]===a)break;if(g.activeWindow){await settle(v=>!v.activeWindow);continue;}const turnPage=table.pages[g.turnSeat]!,label=g.phase==='action'?'行動を終える':g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='turn-start'?'手番を始める':g.phase==='draw'?'カードを引かない':null;expect(label).not.toBeNull();await click(turnPage.getByRole('button',{name:label!,exact:true}));}await page.reload();await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:`${m.name}を選ぶ`,exact:true}).click();}
  else await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:m.name,exact:true}).click();
  await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const index of m.gale?(dedicated?[1,2]:[1]):(dedicated?[1,2,3,4,5]:[1,2,3,4]))await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[index]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await page.reload();await settle(g=>g.activeWindow?.kind==='normal-defense');await page.reload();expect(views.get(a)!.game!.currentAttack!.targets[0]!.hits[0]!.technique!.damage).toBe(damage);await settle(g=>!g.activeWindow,500);await page.reload();const done=views.get(a)!.game!;expect([done.players[b]!.damage,done.players[c]!.damage,done.players[d]!.damage]).toEqual([m.gale?damage-1:damage-(dedicated?2:3),m.gale?(dedicated?damage:0):damage,m.gale?0:damage]);expect(done.players[b]!.followers).toHaveLength(m.gale?1:0);if(!m.gale){expect(done.players[table.sessions[4]!.id]!.damage).toBe(damage);expect(done.players[table.sessions[5]!.id]!.damage).toBe(dedicated?damage:0);}expect(done.self.chants).toEqual([]);expect(done.self.hand).not.toContain(card);
 }finally{await table.close();}
});
