import {expect,test,type Locator} from '@playwright/test';
import {tragedyPhysicalScenarios,tragedyMode} from '../../apps/worker/test/fixtures/tragedy-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of tragedyPhysicalScenarios)test(`${scenario} actual Tragedy attack response and preserved boundaries survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c]=ids as [string,string,string],page=table.pages[0]!,m=tragedyMode(scenario),owner=ids[m.owner]!,op=table.pages[m.owner]!,card='a2-p01-r2c3';const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function until(done:()=>boolean){for(let n=0;n<250;n++){if(done())return;const w=game().activeWindow;if(!w)throw Error('TRAGEDY_UI_WINDOW');const id=w.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}throw Error('TRAGEDY_UI_LIMIT');}
 const prior=game().players[b]!.damage,hand=views.get(owner)!.game!.self.hand.length;await page.getByRole('region',{name:'自分の詠唱',exact:true}).getByRole('button',{name:`${m.multi?'天地爆砕剣':'天地百撃斬'}を選ぶ`,exact:true}).click();for(const seat of m.multi?[1,2]:[1])await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[seat]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await click(page.getByRole('button',{name:'攻撃を確認して実行',exact:true}));await until(()=>game().activeWindow?.kind==='attack-abilities');const parent=game().currentAttack!.actionId,hits=game().currentAttack!.targets[0]!.hits.length;
 if(m.late)await until(()=>game().activeWindow?.kind==='hit'&&game().currentAttack?.targetId===c);
 if(m.follower)await until(()=>game().activeWindow?.kind==='hit');
 if(scenario==='tragedy-counter'){await until(()=>game().activeWindow?.kind==='normal-defense');const panel=table.pages[1]!.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('checkbox',{name:'専用技として使う'}).check();await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p10-r3c3');await click(panel.getByRole('button',{name:'防御する',exact:true}));await until(()=>game().currentAttack?.attackerId===b);}
 const declined=['tragedy-hidden','tragedy-unrelated','tragedy-follower'].includes(scenario);
 if(declined){await until(()=>game().activeWindow?.pendingActorId===owner);await op.reload();await expect(op.getByRole('button',{name:'アレキサンドリア城の悲劇を使う',exact:true})).toHaveCount(0);}
 else{await until(()=>!!views.get(owner)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetEventId===parent));await op.reload();const before={...views.get(owner)!.game!.self.stats},option=views.get(owner)!.game!.anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetEventId===parent)!;await click(op.getByRole('button',{name:option.label,exact:true}));await op.reload();expect(views.get(owner)!.game!.self.hand).toHaveLength(hand);if(scenario==='tragedy-refill'){expect(game().players[owner]!.open).toContain('a2-p01-r1c3');expect(views.get(owner)!.game!.self.stats).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});}if(scenario==='tragedy-canceled'){await until(()=>game().activeWindow?.pendingActorId===a);const panel=page.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(panel.getByRole('button',{name:'割り込みを使う',exact:true}));}}
 await until(()=>!game().activeWindow);await op.reload();expect(game().players[b]!.damage).toBe(prior+(m.late?15:scenario==='tragedy-follower'?4*hits:declined||scenario==='tragedy-canceled'?7*hits:0));expect(game().players[c]!.damage).toBe(0);expect(game().players[a]!.damage).toBe(scenario==='tragedy-counter'?7:0);expect(game().players[b]!.presence).toBe(scenario==='tragedy-late-death'?'dead':'active');if(declined)expect(views.get(owner)!.game!.self.hand).toContain(card);else expect(game().discard.filter(id=>id===card)).toHaveLength(1);if(m.follower)expect(game().discard.filter(id=>id==='a2-p20-r3c1')).toHaveLength(1);expect(errors).toEqual([]);
 }finally{await table.close();}
});
