import {expect,test,type Locator} from '@playwright/test';
import {getAction} from '../../packages/catalog/src/index.js';
import {trainingPhysicalScenarios,trainingMode} from '../../apps/worker/test/fixtures/training-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of trainingPhysicalScenarios)test(`${scenario} actual strict training result dedicated choice and roll interventions survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,dp=table.pages[3]!,m=trainingMode(scenario);const game=()=>views.get(a)!.game!;
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
 async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('TRAINING_UI_LIMIT');}
 const base=game().self.stats[m.stat],other=game().self.stats[m.warrior?'magic_level':'warrior_level'],hand=[...game().self.hand],deckCount=game().deckCount,label=`${getAction(m.card)!.name}を使う`,panel=page.getByRole('region',{name:'手番カードの効果'});if(m.stopped){expect(game().seatOrder[game().turnSeat]).not.toBe(a);await expect(panel.getByRole('button',{name:label,exact:true})).toHaveCount(0);expect(game().self.hand).toContain(m.card);return;}if(scenario.endsWith('-decline')){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(game().self.hand).toContain(m.card);expect(game().self.stats[m.stat]).toBe(base);return;}if(m.lancelot){await expect(panel.getByRole('button',{name:label,exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:label+'（判定不要）',exact:true})).toBeVisible();}
 await click(panel.getByRole('button',{name:label+(m.dedicated?'（判定不要）':''),exact:true}));expect(game().self.hand).toEqual(hand.filter(id=>id!==m.card));expect(game().deckCount).toBe(deckCount);expect(game().players[a]!.attachments).not.toContain(m.card);await page.reload();
 if(m.fate){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().recentRolls.some(r=>r.purpose==='training')).toBe(false);expect(game().players[a]!.attachments).not.toContain(m.card);expect(game().discard).toContain(m.card);expect(game().self.stats[m.stat]).toBe(base);expect(game().phase).toBe('hand-adjustment');return;}
 let success=m.dedicated;if(m.dedicated){await until(()=>!game().activeWindow);expect(game().recentRolls.some(r=>r.purpose==='training')).toBe(false);}else{
  await until(()=>game().currentRoll?.purpose==='training');const id=game().currentRoll!.rollId;expect(game().currentRoll).toMatchObject({kind:'check',formula:'2d6',stage:'before-roll',comparison:'greater-than'});
  async function blood(){await until(()=>game().activeWindow?.pendingActorId===a);const o=game().anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId===b)!;expect(o).toBeDefined();await click(page.getByRole('button',{name:o.label,exact:true}));expect(game().players[a]!.open).toContain('a2-p01-r1c3');expect(game().self.stats[m.stat]).toBe(base+1);await until(()=>game().currentRoll?.rollId===id&&game().activeWindow?.kind===(scenario.endsWith('-before')?'before-roll':'after-roll'));}
  if(scenario.endsWith('-before'))await blood();await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(base+(scenario.endsWith('-before')?1:0));expect(game().currentRoll!.faces).toHaveLength(2);expect(game().currentRoll!.success).toBe(game().currentRoll!.total!>game().currentRoll!.threshold!);await expect(page.getByRole('region',{name:'サイコロの結果',exact:true})).toContainText(`判定値: ${game().currentRoll!.threshold}より大きい`);await page.reload();if(scenario.endsWith('-after'))await blood();
  if(scenario.endsWith('-reroll')||scenario.endsWith('-forced')){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});if(scenario.endsWith('-forced')){await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('force-fail');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().activeWindow?.kind==='after-roll'&&game().activeWindow?.pendingActorId===d);expect(game().currentRoll!.forcedFailure).toBe(true);}await reaction.getByRole('combobox',{name:'割り込み効果',exact:true}).selectOption('reroll');await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.rollId===id&&game().currentRoll!.generation===1);expect(game().currentRoll!.attempts).toHaveLength(2);if(scenario.endsWith('-forced'))expect(game().currentRoll).toMatchObject({forcedFailure:true,success:false});await dp.reload();}
  expect(game().currentRoll!.threshold).toBe(base+(scenario.endsWith('-before')?1:0));success=game().currentRoll!.success!;await until(()=>!game().activeWindow);
 }
 expect(game().players[a]!.attachments.includes(m.card)).toBe(success);expect(game().discard.includes(m.card)).toBe(!success);expect(game().self.stats[m.stat]).toBe(base+(m.blood?1:0)+(success?1:0));expect(game().self.stats[m.warrior?'magic_level':'warrior_level']).toBe(other+(m.blood?1:0));expect(game().phase).toBe('hand-adjustment');for(const actor of [b,c,d])expect(views.get(actor)!.game!.players[a]!.attachments.includes(m.card)).toBe(success);await page.reload();expect(game().players[a]!.attachments.includes(m.card)).toBe(success);expect(errors).toEqual([]);
 }finally{await table.close();}
});
