import {expect,test,type Locator} from '@playwright/test';
import {uraSwordCard as CARD,uraSwordMode} from '../../apps/worker/test/fixtures/ura-sword-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture,storedDiscard} from './helpers.js';
for(const scenario of ['ura-sword-ordinary','ura-sword-guard','ura-sword-owner-ordinary','ura-sword-owner-hit','ura-sword-dedicated','ura-sword-far','ura-sword-fate','ura-sword-maai','ura-sword-evade','ura-sword-suppressed','ura-sword-silenced','ura-sword-wrong-owner','ura-sword-decline','ura-sword-critical-one','ura-sword-critical-two','ura-sword-cancel','ura-sword-reroll'] as const)test(`${scenario} actual near sword controls and optional critical results survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,cp=table.pages[2]!,dp=table.pages[3]!,m=uraSwordMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<500;n++){if(done())return;await step();}throw Error('URA_SWORD_UI_LIMIT');}
  const execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});if(scenario==='ura-sword-decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,followers=structuredClone(own(b).followers),rolls=game().recentRolls.map(r=>r.rollId);
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);const target=page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[b]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true});
  if(scenario==='ura-sword-far'){await target.check();const rev=views.get(a)!.revision,before=JSON.stringify(game());await execute.click();await expect.poll(()=>errors).toEqual(['INVALID_ACTION']);await expect(page.getByRole('alert')).toHaveText('現在はその操作を実行できません');expect(views.get(a)!.revision).toBe(rev);expect(JSON.stringify(game())).toBe(before);expect(own(a).hand).toEqual(hand);errors.length=0;await page.reload();await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf('a2-p24-r1c3')).getByRole('button').first().click();await target.check();await click(page.getByRole('button',{name:'接近',exact:true}));await until(()=>!game().activeWindow);expect(game().distances[a]![b]).toBe('near');await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).check();await target.check();await click(execute);await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(5);expect(own(b).followers).toEqual(followers);expect((await storedDiscard())).toContain(CARD);expect(errors).toEqual([]);return;}await target.check();if(scenario==='ura-sword-wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD));expect(game().deckCount).toBe(deck);await page.reload();
  if(scenario==='ura-sword-fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(own(b).followers).toEqual(followers);expect((await storedDiscard())).toContain(CARD);return;}
  await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:5,damage:5,attributes:['戦','剣','忍']});const defense=scenario==='ura-sword-maai'||scenario==='ura-sword-evade';if(defense){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'}),maai=scenario==='ura-sword-maai';await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(maai?'a2-p06-r1c3':'a2-p05-r3c1');await click(reaction.getByRole('button',{name:maai?'間合いを使う':'防御する',exact:true}));}
  const attempts=scenario==='ura-sword-critical-two'||scenario==='ura-sword-cancel'||scenario==='ura-sword-reroll'?2:scenario==='ura-sword-owner-hit'||scenario==='ura-sword-critical-one'?1:0;let multiplier=1,instant=false,numeric=0;
  if(attempts){await until(()=>game().activeWindow?.kind==='hit-abilities'&&game().activeWindow?.pendingActorId===a);for(let i=0;i<attempts;i++){await page.reload();await click(page.getByRole('button',{name:'必殺を使う',exact:true}));
    if(i===0&&(scenario==='ura-sword-cancel'||scenario==='ura-sword-reroll')){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().activeWindow?.kind==='hit-abilities'&&game().activeWindow?.pendingActorId===a);continue;}
    await until(()=>game().currentRoll?.purpose==='ability-value'&&game().currentRoll?.stage==='after-roll');numeric++;let faces=game().currentRoll!.faces;
    if(scenario==='ura-sword-reroll'){await until(()=>game().activeWindow?.pendingActorId===c);const reaction=cp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r1c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>game().currentRoll?.generation===1&&game().currentRoll?.stage==='after-roll');faces=game().currentRoll!.faces;}
    if(faces[0]===faces[1])instant=true;else if(Math.abs(faces[0]!-faces[1]!)===1)multiplier*=2;
    await until(()=>game().activeWindow?.kind==='hit-abilities'&&game().activeWindow?.pendingActorId===a);expect(game().players[b]!.presence).toBe('active');expect(game().players[b]!.damage).toBe(0);if(i+1===attempts&&(attempts===2||scenario==='ura-sword-owner-hit'))await expect(page.getByRole('button',{name:'必殺を使う',exact:true})).toHaveCount(0);
   }
  }
  await until(()=>!game().activeWindow);if(instant){expect(game().players[b]!.presence).toBe('dead');expect(own(b).followers).toEqual([]);}else{expect(game().players[b]!.damage).toBe(defense||m.guard&&!m.dedicated?0:5*multiplier);if(m.dedicated)expect(own(b).followers).toEqual(followers);else if(m.guard)expect(own(b).followers[0]!.revealed).toBe(true);}expect(game().players[a]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(0);expect((await storedDiscard()).filter(id=>id===CARD)).toHaveLength(1);expect(game().phase).toBe('withdrawal');expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='ability-value')).toHaveLength(numeric);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
