import {expect,test,type Locator} from '@playwright/test';
import {voidSwordScenarios,voidSwordCard as CARD,voidSwordAdvances as ADV,voidSwordMode} from '../../apps/worker/test/fixtures/void-sword-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of voidSwordScenarios)test(`${scenario} actual Void Sword advance payment target subset and defense survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!,dp=table.pages[3]!,m=voidSwordMode(scenario),game=()=>views.get(a)!.game!,own=(id:string)=>views.get(id)!.game!.self;
  async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);await expect.poll(()=>views.get(b)?.revision).toBe(views.get(a)!.revision);}
  async function step(){const id=game().activeWindow!.pendingActorId!;await expect.poll(()=>views.get(id)?.revision).toBe(views.get(a)!.revision);await click(table.pages[ids.indexOf(id)]!.getByRole('button',{name:windowPassButtonName}));}
  async function until(done:()=>boolean){for(let n=0;n<750;n++){if(done())return;await step();}throw Error('VOID_SWORD_UI_LIMIT');}
  if(m.suffix==='stopped'){expect(game().seatOrder[game().turnSeat]).not.toBe(a);expect(game().legalChoices).not.toContain('ATTACK');expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='decline'){await click(page.getByRole('button',{name:'行動を終える',exact:true}));expect(own(a).hand).toContain(CARD);return;}
  if(m.suffix==='noncounter'){await expect(page.getByRole('complementary',{name:'現在の判断'}).locator(`option[value="${CARD}"]`)).toHaveCount(0);await until(()=>!game().activeWindow);expect(game().players[a]!.damage).toBe(4);expect(own(a).hand).toContain(CARD);return;}
  const hand=[...own(a).hand],deck=game().deckCount,bFollowers=structuredClone(own(b).followers),cFollowers=structuredClone(own(c).followers),distances=structuredClone(game().distances),markers=structuredClone(game().distanceMarkers),rolls=game().recentRolls.map(r=>r.rollId),targets=m.targets.map(i=>ids[i]!),execute=page.getByRole('button',{name:'攻撃を確認して実行',exact:true});await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(own(a).hand.indexOf(CARD)).getByRole('button').first().click();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(m.dedicated);for(const id of targets)await page.getByRole('region',{name:'参加者の公開状態',exact:true}).getByRole('article').filter({has:page.getByRole('heading',{name:game().players[id]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ',exact:true}).check();if(m.suffix==='wrong-owner'){await expect(execute).toBeDisabled();expect(own(a).hand).toEqual(hand);return;}
  if(m.costs.length){const pool=game().advanceCostOptions.find(o=>o.cardInstanceId===CARD)!.advanceCardInstanceIds.filter(id=>own(a).hand.includes(id)),panel=page.getByRole('group',{name:'消費する踏み込み',exact:true});if(m.suffix==='invalid-cost'){for(const id of ['a2-p06-r1c3','a2-p08-r3c3',ADV[2],CARD])expect(pool).not.toContain(id);expect(pool).toEqual(expect.arrayContaining(m.costs));}for(const id of m.costs){expect(pool.indexOf(id)).toBeGreaterThanOrEqual(0);await panel.getByRole('checkbox').nth(pool.indexOf(id)).check();}}
  await click(execute);expect(own(a).hand).toEqual(hand.filter(id=>id!==CARD&&!m.costs.includes(id as never)));expect(game().deckCount).toBe(deck);await page.reload();await until(()=>game().activeWindow?.kind!=='reclaim');for(const id of m.costs)expect(game().discard.filter(c=>c===id)).toHaveLength(1);expect(game().distances).toEqual(distances);expect(game().distanceMarkers).toEqual(markers);
  if(m.suffix==='fate'){await until(()=>game().activeWindow?.pendingActorId===d);const reaction=dp.getByRole('complementary',{name:'現在の判断'});await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p02-r2c3');await click(reaction.getByRole('button',{name:'割り込みを使う',exact:true}));await until(()=>!game().activeWindow);expect(game().players[b]!.damage).toBe(0);expect(game().players[c]!.damage).toBe(0);expect(own(b).followers).toEqual(bFollowers);expect(own(c).followers).toEqual(cFollowers);for(const id of [CARD,...m.costs])expect(game().discard.filter(c=>c===id)).toHaveLength(1);return;}
  let success=true;if(m.suffix==='low'){await until(()=>game().currentRoll?.purpose==='excess-level'&&game().currentRoll?.stage==='after-roll');expect(game().currentRoll!.threshold).toBe(6);success=game().currentRoll!.success!;}
  if(success){await until(()=>game().activeWindow?.kind==='attack-abilities');expect(game().currentAttack!.technique).toMatchObject({effectLevel:m.dedicated?7+m.costs.length:6,damage:m.dedicated?15:10,attributes:['戦','剣']});if(m.suffix.startsWith('maai')||m.suffix.startsWith('evade')){await until(()=>game().activeWindow?.kind==='normal-defense');const reaction=bp.getByRole('complementary',{name:'現在の判断'});if(m.suffix.startsWith('evade')){expect(views.get(b)!.game!.currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);await expect(reaction.locator('option[value="a2-p05-r3c1"]')).toHaveCount(0);}else{await reaction.getByRole('combobox',{name:'使うカード',exact:true}).selectOption('a2-p06-r1c3');await click(reaction.getByRole('button',{name:'間合いを使う',exact:true}));await until(()=>game().activeWindow?.kind==='defense-advance');const advance=page.getByRole('complementary',{name:'現在の判断'});await expect(advance.locator(`option[value="${ADV[0]}"]`)).toHaveCount(0);if(m.suffix==='maai-spare'){await advance.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(ADV[1]);await click(advance.getByRole('button',{name:'踏み込みを使う',exact:true}));}expect(game().currentAttack!.technique.effectLevel).toBe(8);}}}
  await until(()=>!game().activeWindow);const damage=m.dedicated?15:10,morale=views.get(b)!.game!.recentRolls.filter(r=>!rolls.includes(r.rollId)&&r.purpose==='follower-morale').at(-1);if(m.water)expect(morale).toBeDefined();for(const id of [b,c,d])expect(game().players[id]!.damage).toBe(!success||!targets.includes(id)?0:id===b&&m.suffix==='maai'?0:id===b&&m.water?morale!.success?m.dedicated&&m.costs.length>0?11:0:damage:damage-(id===c?1:0));const survives=m.suffix==='maai'||m.suffix==='water-ordinary'&&morale!.success;expect(own(b).followers).toHaveLength(survives?1:0);if(survives)expect(own(b).followers[0]!.revealed).toBe(m.water);for(const id of [CARD,...m.costs,...(m.suffix==='maai-spare'?[ADV[1]]:[])])expect(game().discard.filter(c=>c===id)).toHaveLength(1);expect(game().distances).toEqual(distances);expect(game().distanceMarkers).toEqual(markers);if(m.suffix!=='low')expect(game().recentRolls.filter(r=>!rolls.includes(r.rollId))).toHaveLength(m.water?1:0);await page.reload();expect(own(a).hand).not.toContain(CARD);expect(errors).toEqual([]);
 }finally{await table.close();}
});
