import {expect,test,type Locator} from '@playwright/test';
import {waterDragonPhysicalMode,waterDragonPhysicalScenarios} from '../../apps/worker/test/fixtures/water-dragon-physical-scenarios.js';
import {observe,windowPassButtonName,tableFixture} from './helpers.js';
for(const scenario of waterDragonPhysicalScenarios)test(`${scenario} actual Water Dragon defense attack and source expiry survive reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario),m=waterDragonPhysicalMode(scenario),errors:string[]=[];for(const p of table.pages)p.on('websocket',socket=>socket.on('framereceived',frame=>{const message=JSON.parse(String(frame.payload));if(message.type==='error')errors.push(message.code);}));
 try{const views=await observe(table),ids=table.sessions.map(p=>p.id),[a,b,c,d]=ids as [string,string,string,string],page=table.pages[0]!,bp=table.pages[1]!;
 const game=()=>views.get(a)!.game!;const stops=(id:string)=>game().players[id]!.statuses.filter(t=>t.sourceCardInstanceId===m.card&&t.timing==='source-turn');
 async function click(button:Locator){const rev=views.get(a)!.revision;await button.click();await expect.poll(()=>{expect(errors).toEqual([]);return views.get(a)?.revision;}).toBeGreaterThan(rev);}
 async function pass(){const current=views.get(a)!,actor=current.game!.activeWindow!.pendingActorId!;await expect.poll(()=>views.get(actor)?.revision).toBe(current.revision);await click(table.pages[ids.indexOf(actor)]!.getByRole('button',{name:windowPassButtonName}));}
 async function settle(stop?:string){for(let n=0;n<300;n++){const w=game().activeWindow;if(!w||w.kind===stop)return;await pass();}throw Error('WATER_UI_SETTLE');}
 async function step(){const g=game();if(g.activeWindow){await pass();return;}const p=table.pages[g.turnSeat]!,label=g.phase==='withdrawal'?'離脱しない':g.phase==='hand-adjustment'?'選んだ0枚を捨てて手番を終える':g.phase==='action'?'行動を終える':g.phase==='draw'?'カードを引かない':g.phase==='turn-start'?'手番を始める':null;if(!label)throw Error(`WATER_UI_PHASE_${g.phase}`);await click(p.getByRole('button',{name:label,exact:true}));}
 async function advance(id:string,phase='turn-start'){for(let n=0;n<300;n++){const g=game();if(!g.activeWindow&&g.seatOrder[g.turnSeat]===id&&g.phase===phase)return;await step();}throw Error('WATER_UI_CLOCK');}
 async function select(seat:number,id:string){const p=table.pages[seat]!,index=views.get(ids[seat]!)!.game!.self.hand.indexOf(id);expect(index).toBeGreaterThanOrEqual(0);await p.getByRole('region',{name:'自分の手札',exact:true}).getByRole('article').nth(index).getByRole('button').first().click();}
 async function target(seat:number,to:number){const p=table.pages[seat]!;await p.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:p.getByRole('heading',{name:table.sessions[to]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();}
 async function cardAttack(card:string,targets:number[],dedicated:boolean){await select(1,card);await bp.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);for(const to of targets)await target(1,to);await click(bp.getByRole('button',{name:'攻撃を確認して実行',exact:true}));}
 if(m.initial){await select(0,m.card);await click(page.getByRole('button',{name:'従者を置く',exact:true}));await page.reload();}await click(page.getByRole('button',{name:'従者を置かず進む',exact:true}));for(const card of m.pair??[]){await select(1,card);await click(bp.getByRole('button',{name:'従者を置く',exact:true}));}for(let i=1;i<4;i++)await click(table.pages[i]!.getByRole('button',{name:'従者を置かず進む',exact:true}));await click(page.getByRole('button',{name:'手番を始める',exact:true}));await click(page.getByRole('button',{name:'カードを引かない',exact:true}));
 if(m.defense){if(!m.initial){const panel=page.getByRole('region',{name:'従者の配置',exact:true});await panel.getByRole('combobox',{name:'従者を加える',exact:true}).selectOption(m.card);await click(panel.getByRole('button',{name:'この順番で確定',exact:true}));await page.reload();}await advance(b,'action');if(m.sky||m.destroy)await cardAttack(m.sky?'a2-p15-r1c3':'a2-p13-r1c2',m.sky?[0,2]:[0],true);else{const panel=bp.getByRole('region',{name:'複数従者の攻撃'});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption('c2-p06-r1c2-ab04');await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption('a2-p21-r2c3');await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await panel.getByRole('radio',{name:table.sessions[0]!.name,exact:true}).check();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));}}
 else{
  if(m.overlap){await advance(b,'action');await cardAttack('a2-p15-r2c2',[2],false);await settle();await advance(a,'action');}
  if(m.army){const panel=page.getByRole('region',{name:'全軍突撃せよ',exact:true});await panel.getByRole('combobox',{name:'突撃に使う従者',exact:true}).selectOption(m.card);await click(panel.getByRole('button',{name:'2枚を使って全軍突撃する',exact:true}));}else{const panel=page.getByRole('region',{name:'複数従者の攻撃'});await panel.getByRole('combobox',{name:'使う能力',exact:true}).selectOption('c2-p05-r1c2-ab02');await panel.getByRole('combobox',{name:'追加する従者',exact:true}).selectOption(m.card);await panel.getByRole('button',{name:'攻撃に加える',exact:true}).click();await click(panel.getByRole('button',{name:'選んだ従者で攻撃する',exact:true}));}
  if(m.maai||m.mirror){await settle('normal-defense');const panel=bp.getByRole('complementary',{name:'現在の判断'});await panel.getByRole('combobox',{name:'使うカード',exact:true}).selectOption(m.mirror?'a2-p11-r1c3':'a2-p07-r1c2');await click(panel.getByRole('button',{name:m.mirror?'防御する':'間合いを使う',exact:true}));}
 }
 await page.reload();await settle();await page.reload();const done=game(),alive=m.defense&&(m.sky||!m.destroy&&!m.fail&&m.attackLevel<7);expect(done.self.followers.map(f=>f.cardInstanceId)).toEqual(alive?[m.card]:[]);expect(done.discard.filter(id=>id===m.card)).toHaveLength(alive?0:1);
 if(m.defense){expect([done.players[a]!.damage,done.players[c]!.damage]).toEqual(m.sky?[12,12]:[m.destroy?0:m.fail?18:m.attackLevel>7?6:0,0]);if(m.sky)expect(done.self.followers[0]!.revealed).toBe(false);}
 else{
  const recipients=m.dead?[c,d]:m.wander?[b,d]:m.maai||m.mirror||m.block?[c,d]:[b,c,d];for(const id of recipients)expect(stops(id)).toEqual([expect.objectContaining({kind:'stopped',sourceActorId:a})]);if(!recipients.includes(b))expect(stops(b)).toEqual([]);if(m.block||m.hp)expect(done.players[b]!.damage).toBe(0);else if(!m.dead&&!m.wander)expect(done.players[b]!.damage).toBe(m.maai||m.mirror?0:5);
  if(m.mirror&&!m.dead){expect(done.players[a]!.damage).toBe(5);expect(stops(a)).toEqual([expect.objectContaining({sourceActorId:b,sourceCardInstanceId:m.card,kind:'stopped'})]);}
  if(m.dead||m.wander){expect(done.players[a]!.presence).toBe(m.dead?'dead':'wandering');await advance(d);for(const id of recipients)expect(stops(id)).toHaveLength(1);await advance(b);}
  else{await advance(b);if(m.mirror)expect(stops(a)).toEqual([]);for(const id of [c,d])expect(stops(id)).toHaveLength(1);if(m.skip){await advance(b,'action');await cardAttack('a2-p09-r2c2',[0],true);await settle();expect(game().players[a]!.skipsNextTurn).toBe(true);}await advance(a);if(m.skip){expect(game().players[a]!.skipsNextTurn).toBe(true);for(const id of recipients)expect(stops(id)).toEqual([]);await click(page.getByRole('button',{name:'手番を始める',exact:true}));expect(game().seatOrder[game().turnSeat]).toBe(b);}}
  await page.reload();for(const id of ids)expect(stops(id)).toEqual([]);if(m.overlap)expect(game().players[c]!.statuses).toContainEqual(expect.objectContaining({sourceCardInstanceId:'a2-p15-r2c2',kind:'stopped'}));else expect(game().recentRolls.filter(r=>r.purpose==='status-recovery')).toEqual([]);
 }
 expect(errors).toEqual([]);
 }finally{await table.close();}
});
