import {expect,test} from '@playwright/test';
import {observe,passUntil,tableFixture} from './helpers.js';
for(const [scenario,card,dedicated,variant] of [['wolf-ordinary','a2-p10-r3c1',false,null],['wolf-dedicated','a2-p10-r3c1',true,null],['lance-ordinary','a2-p10-r3c2',false,null],['lance-one','a2-p10-r3c2',true,'one-hit'],['lance-two','a2-p10-r3c2',true,'two-hit']] as const)test(`${scenario} actual attack selection preserves dice or hit choice across reload`,async({browser,request})=>{
 const table=await tableFixture(browser,request,scenario);
 try{const views=await observe(table),a=table.sessions[0]!.id,b=table.sessions[1]!.id,page=table.pages[0]!;
  await page.getByRole('region',{name:'自分の手札',exact:true}).getByRole('button',{name:scenario.startsWith('wolf')?'狼牙':'連槍撃',exact:true}).click();await page.getByRole('region',{name:'参加者の公開状態'}).getByRole('article').filter({has:page.getByRole('heading',{name:table.sessions[1]!.name,exact:true})}).getByRole('checkbox',{name:'対象に選ぶ'}).check();await page.getByRole('checkbox',{name:'専用技として使う',exact:true}).setChecked(dedicated);if(variant)await page.getByRole('combobox',{name:'専用効果の選択',exact:true}).selectOption(variant);
  const rev=views.get(a)!.revision;await page.getByRole('button',{name:'攻撃を確認して実行',exact:true}).click();await expect.poll(()=>views.get(a)?.revision).toBeGreaterThan(rev);await page.reload();await passUntil(table,views,g=>g.activeWindow?.kind==='normal-defense');await page.reload();const attack=views.get(a)!.game!.currentAttack!;expect(attack.targets[0]!.hits).toHaveLength(variant==='two-hit'?2:1);await passUntil(table,views,g=>!g.activeWindow);await page.reload();const done=views.get(a)!.game!;
  let damage=dedicated?(variant==='two-hit'?14:7):5;if(scenario.startsWith('wolf')){const roll=done.recentRolls.find(r=>r.purpose==='attack-damage')!;expect(roll.faces).toHaveLength(dedicated?3:2);damage=roll.total!;}expect(done.players[b]!.damage).toBe(damage);expect(done.self.hand).not.toContain(card);expect(done.phase).toBe('withdrawal');
 }finally{await table.close();}
});
