import { DeclarationFields } from './DeclarationFields.js';
import { applyDeclarationSelection, candidateFor, defenseCardChoices, type DeclarationCommand } from './declaration-input.js';
import type { GameCommand } from '@madou/protocol';
import type { PlayerView } from '@madou/engine';
import { getAction, getCharacter } from '@madou/catalog';
import { useState } from 'react';
import { buildCardCommand, eligibleReactionCards, reactionModes, type CardCommandInput } from './commands.js';
import { lifecycleCommands } from './LifecyclePanel.js';
import { lifetimeCommands } from './lifetime-input.js';
import { abilityCommands } from './ability-input.js';
import { FollowerDefenseFields } from './FollowerDefenseFields.js';
import { followerDefenseCommand } from './follower-input.js';
import { combinationCommands } from './combination-input.js';

const choiceLabels:Record<string,string>={PASS:'パス',START_FOLLOWERS:'従者で受ける',PLAY_DEFENSE:'防御する',PLAY_MAAI:'間合いを使う',PLAY_ADVANCE:'踏み込みを使う',PLAY_REACTION:'割り込みを使う',CANCEL_REACTION:'アルセイルの固有反応で命運凶変を取り消す'};
export function ReactionPanel({view,disabled,send}:{view:PlayerView;disabled:boolean;send:(command:GameCommand)=>boolean}){
  const [declarationIds,setDeclarationIds]=useState<string[]>([]);
  const [dedicatedFollowers,setDedicatedFollowers]=useState<string[]>([]);
  const [cardId,setCardId]=useState('');const [mode,setMode]=useState<NonNullable<CardCommandInput['reactionMode']>>('cancel');const [dedicated,setDedicated]=useState(false);const mine=view.activeWindow?.pendingActorId===view.self.id;
  if(!view.activeWindow||view.lifecycleDecision||view.lifetimeDecision||view.techniqueDecision||view.activeWindow.kind==='ability-attack'||view.activeWindow.kind==='beast-capture'||view.activeWindow.kind==='private-inspection')return null;const pending=view.players[view.activeWindow.pendingActorId]?.name??'参加者';
  const allowedModes=reactionModes(view.activeWindow.kind,view.currentRoll?.kind,!!view.reactionTargetRollId,!!view.reactionTargetAbilityId);
  const selectedMode=allowedModes.includes(mode)?mode:allowedModes[0];
  const modeNames={'cancel-ability':'命運凶変: 能力の使用を取り消し',cancel:'命運凶変: カードの使用を取り消し','force-fail':'命運凶変: 強制失敗','effect-plus':'必勝の祈り: 効果値+1d6',reroll:'神性介入: ロール全体を振り直す'};
  const context={faction:view.self.faction,limitedDefenses:view.currentAttack?.defenseRestrictions.limitedDefenses,characterName:getCharacter(view.self.characterId)?.name,dedicated,defenseRestrictions:view.currentAttack?.defenseRestrictions,rollKind:view.currentRoll?.kind,incomingAttributes:view.currentAttack?.technique.attributes,incomingEffectLevel:view.currentAttack?.technique.effectLevel,statusKinds:view.players[view.self.id]!.statuses.map(status=>status.kind)};
  const restrictions=context.defenseRestrictions;
  const restrictionLabels=[context.limitedDefenses?'転移・反撃・特殊能力で防御':null,restrictions?.maaiProhibited?'間合い不可':null,restrictions?.evadeProhibited?'見切り不可':null,restrictions?.counterProhibited?'反撃不可':null].filter(Boolean);
  const reactionChoices=view.legalChoices.filter(choice=>choice!=='REVEAL_CHARACTER'&&!lifecycleCommands.has(choice)&&!lifetimeCommands.has(choice)&&!abilityCommands.has(choice)&&!combinationCommands.has(choice)&&(choice!=='PLAY_REACTION'||allowedModes.length>0));
  const cardChoices=reactionChoices.flatMap(choice=>eligibleReactionCards(choice,view.self.hand,view.self.chants.map(card=>card.cardInstanceId),selectedMode,context));
  const usesCard=reactionChoices.some(choice=>['PLAY_DEFENSE','PLAY_REACTION','PLAY_MAAI','PLAY_ADVANCE'].includes(choice));
  const uniqueChoices=defenseCardChoices(view,cardChoices,dedicated);
  const defenseBase=buildCardCommand('PLAY_DEFENSE',{cardId,dedicated}) as DeclarationCommand|null;
  const defenseCandidate=candidateFor(view,defenseBase);
  const defenseCommand=defenseCandidate||eligibleReactionCards('PLAY_DEFENSE',view.self.hand,view.self.chants.map(card=>card.cardInstanceId),selectedMode,context).includes(cardId)?applyDeclarationSelection(view,defenseBase,declarationIds):null;
  function simple(choice:string){if(choice==='PLAY_DEFENSE'){if(defenseCommand)send(defenseCommand);}else if(choice==='PASS')send({type:'PASS'});else if(choice==='START_FOLLOWERS'){const command=followerDefenseCommand(view,dedicatedFollowers);if(command)send(command);}else if(choice==='CANCEL_REACTION'&&view.reactionTargetActionId)send({type:'CANCEL_REACTION',targetActionId:view.reactionTargetActionId});else {const command=buildCardCommand(choice as GameCommand['type'],{cardId,targetActionId:view.reactionTargetActionId??undefined,targetAbilityId:view.reactionTargetAbilityId??undefined,targetRollId:view.reactionTargetRollId??undefined,reactionMode:selectedMode,dedicated});if(command)send(command);}}
  if(view.activeWindow.kind==='follower-bypass-choice')return <aside className="decision" aria-label="現在の判断"><p role="status">{mine?'あなたの判断です':`${pending}さんの判断を待っています`}</p><h2>凍流の従者への効果</h2>{view.currentAttack?.targetId?<p>対象: {view.players[view.currentAttack.targetId]?.name}</p>:null}<p>効果Lv {view.currentAttack?.technique.effectLevel} 以下の従者を、この対象への攻撃では無視するか選べます。</p>{mine?<div className="button-row"><button disabled={disabled} onClick={()=>send({type:'CHOOSE_FOLLOWER_BYPASS',ignore:true})}>条件を満たす従者を無視する</button><button className="secondary" disabled={disabled} onClick={()=>send({type:'CHOOSE_FOLLOWER_BYPASS',ignore:false})}>無視しない</button></div>:null}</aside>;
  if(view.activeWindow.kind==='on-hit-choice')return <aside className="decision" aria-label="現在の判断"><p role="status">{mine?'あなたの判断です':`${pending}さんの判断を待っています`}</p><h2>命中時の効果</h2>{view.currentAttack?.targetId?<p>対象: {view.players[view.currentAttack.targetId]?.name}（詠唱 {view.players[view.currentAttack.targetId]?.chantCount}枚）</p>:null}{mine?<div className="button-row"><button disabled={disabled} onClick={()=>send({type:'DISCARD_HIT_CHANTS',discard:true})}>詠唱中の技をすべて捨てさせる</button><button className="secondary" disabled={disabled} onClick={()=>send({type:'DISCARD_HIT_CHANTS',discard:false})}>使用しない</button></div>:null}</aside>;
  return <aside className="decision" aria-label="現在の判断"><p role="status">{mine?'あなたの判断です':`${pending}さんの判断を待っています`}</p><h2>{view.activeWindow.kind==='normal-defense'?'防御の選択':view.activeWindow.kind==='follower-entry-abilities'?'従者登場前の能力':'反応の選択'}</h2>{restrictionLabels.length?<p>この攻撃の制限: {restrictionLabels.join('・')}</p>:null}{view.activeWindow.reason==='follower-defense-closed'?<p>従者受け開始後は通常防御へ戻れません。</p>:null}{mine?<>{usesCard?<label>使うカード<select value={cardId} onChange={e=>{setCardId(e.target.value);setDeclarationIds([]);}}><option value="">選択してください</option>{uniqueChoices.map(id=><option key={id} value={id}>{getAction(id)?.name??'カード'}{view.self.chants.some(card=>card.cardInstanceId===id)?'（詠唱中）':''}</option>)}</select></label>:null}{view.legalChoices.includes('PLAY_REACTION')&&selectedMode?<><label>割り込み効果<select value={selectedMode} onChange={e=>{setMode(e.target.value as typeof mode);setCardId('')}}>{allowedModes.map(value=><option key={value} value={value}>{modeNames[value]}</option>)}</select></label></>:null}{(view.legalChoices.includes('PLAY_REACTION')&&selectedMode==='effect-plus')||view.legalChoices.includes('PLAY_DEFENSE')?<label className="inline"><input type="checkbox" checked={dedicated} onChange={e=>{setDedicated(e.target.checked);setDeclarationIds([]);}}/> 専用技として使う</label>:null}<DeclarationFields candidate={defenseCandidate} selected={declarationIds} disabled={disabled} onChange={setDeclarationIds}/><FollowerDefenseFields view={view} selected={dedicatedFollowers} disabled={disabled} onChange={setDedicatedFollowers}/><div className="button-row">{reactionChoices.map(choice=>{const needsCard=!['PASS','START_FOLLOWERS','CANCEL_REACTION'].includes(choice);const eligible=choice==='PLAY_DEFENSE'?!!defenseCommand:choice==='START_FOLLOWERS'?!!followerDefenseCommand(view,dedicatedFollowers):!needsCard||eligibleReactionCards(choice,view.self.hand,view.self.chants.map(card=>card.cardInstanceId),selectedMode,context).includes(cardId);return <button key={choice} disabled={disabled||!eligible} onClick={()=>simple(choice)}>{choiceLabels[choice]??choice}</button>})}</div></>:null}</aside>;
}
