import {describe,it,expect} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
const STAFF='c2-p01-r1c1-ab02',FIST='c2-p01-r1c2-ab02',SPIRIT='c2-p01-r2c1-ab03',AXE='c2-p03-r1c1-ab03',POWER='c2-p05-r1c1-ab02';
function priority(s:GameState,actor='A'){for(let i=0;i<30;i++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('PRIORITY');}
function attack(owner:string,cardName:string){let s=ready();character(s,'A',owner);s.distances.A!.B='near';s.distances.B!.A='near';const card=handCard(s,'A',cardName);return act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});}
function use(s:GameState,id:string){s=priority(s);const option=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id);expect(option).toBeDefined();return act(s,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:option!.targetEventId});}
function main(s:GameState){return Object.values(s.actions!).find(a=>a.kind==='attack')!;}
function rejected(s:GameState,actorId:string,command:unknown){const saved=JSON.stringify(s);expect(transition(s,{actorId,command} as Parameters<typeof transition>[1],entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);}
const cases=[['白魔術師シェリム','白光',STAFF,6],['大神官ジル','狼牙',FIST,6],['侍大将のシン','黒翼飛翔剣',SPIRIT,6],['小人のランバ','黒翼飛翔剣',AXE,5],['邪祭ウーノス','妖獣',POWER,5]] as const;
describe('canonical action-value abilities',()=>{
 it.each(cases)('%s can explicitly select its own complete numerical package',(owner,card,id,effect)=>{let s=until(attack(owner,card),id===AXE?'damage':'effect-level');const usage=main(s).technique.useLevel;s=use(s,id);expect(viewFor(s,'A').currentAction).toMatchObject({source:'ability',abilityId:id});expect(JSON.stringify(viewFor(s,'B'))).not.toContain(id);s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(effect);expect(main(s).technique.useLevel).toBe(usage);if(id===AXE)expect(main(s).technique.damage).toBe(14);if(id===FIST)expect(main(s).technique.damage).toBe(3);s=finish(s);});
 it.each(cases)('%s can decline with no automatic modification',(owner,card,id)=>{let s=until(attack(owner,card),'effect-level');const base=main(s).technique.effectLevel;s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(base);expect(s.rolls?.some(r=>r.purpose==='ability-value'||r.purpose==='ability-check')??false).toBe(false);s=finish(s);});
 it.each([true,false])('real Prayer and Fist compose max(base,warrior)+addition in either selection order (%s)',prayerFirst=>{let s=until(attack('大神官ジル','狼牙'),'effect-level');const prayer=handCard(s,'A','必勝の祈り');const prayerUse=(state:GameState)=>{state=priority(state);state=act(state,'A',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:main(state).id});state=closeWindow(state,[3]);return closeWindow(state);};if(prayerFirst)s=prayerUse(s);s=use(s,FIST);s=closeWindow(s);if(!prayerFirst)s=prayerUse(s);expect(main(s).technique.effectLevel).toBe(9);s=until(s,'damage');expect(main(s).technique.effectLevel).toBe(9);expect(main(s).technique.useLevel).toBe(5);});
});
describe('action-value cutoff, rolls and public projection',()=>{
 it('keeps parent numeric summary through a concealed Shin check and freezes only at cutoff',()=>{let s=until(attack('侍大将のシン','黒翼飛翔剣'),'effect-level');const id=main(s).id;s=use(s,SPIRIT);expect(viewFor(s,'B')).toMatchObject({actionCalculation:{actionId:id,actorId:'A',effectLevel:5,calculation:{effectLevel:'pending',damage:'pending'}}});expect(JSON.stringify(viewFor(s,'B'))).not.toContain(SPIRIT);s=closeWindow(s);expect(viewFor(s,'B').currentRoll).toMatchObject({purpose:'ability-check',modifier:0});expect(viewFor(s,'B')).toMatchObject({actionCalculation:{actionId:id,effectLevel:5}});s=closeWindow(s,[2,3]);s=closeWindow(s);expect(viewFor(s,'B')).toMatchObject({actionCalculation:{effectLevel:6,calculation:{effectLevel:'pending'}}});s=until(s,'damage');expect(viewFor(s,'B')).toMatchObject({actionCalculation:{effectLevel:6,calculation:{effectLevel:'final',damage:'pending'}}});s=until(s,'attack-abilities');expect(viewFor(s,'B')).toMatchObject({actionCalculation:{damage:7,calculation:{effectLevel:'final',damage:'final'}}});});
 it.each(cases)('canceled %s is spent on the same event and has no value contribution',(owner,card,id)=>{let s=until(attack(owner,card),id===AXE?'damage':'effect-level');const event=main(s).eventId;const base=main(s).technique.effectLevel;const fate=handCard(s,'B','命運凶変');s=use(s,id);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});s=closeWindow(s);s=closeWindow(s);expect(s.used).toContain(`${event}:A:${id}`);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===id)).toBe(false);s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(base);expect(s.rolls?.some(r=>r.purpose.startsWith('ability-'))??false).toBe(false);});
 it.each(['before-effect','after-effect','during-damage-roll','after-damage'] as const)('Fist live source suppression at %s respects independent component freezes',boundary=>{let s=until(attack('大神官ジル','狼牙'),'effect-level');s=use(s,FIST);s=closeWindow(s);if(boundary!=='before-effect')s=until(s,'damage');if(boundary==='during-damage-roll'){s=closeWindow(s,[2,3]);s=closeWindow(s,[4]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'ability-value',faces:[4]});}if(boundary==='after-damage')s=until(s,'attack-abilities');s.players.A!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(boundary==='before-effect'?5:6);expect(main(s).technique.damage).toBe(boundary==='during-damage-roll'?5:boundary==='after-damage'?3:2);expect(s.rolls?.filter(r=>r.purpose==='ability-value')??[]).toHaveLength(boundary==='during-damage-roll'||boundary==='after-damage'?1:0);});
 it.each([SPIRIT,STAFF,FIST,POWER])('late %s selection is atomically rejected after effect cutoff',id=>{const row=cases.find(c=>c[2]===id)!;let s=until(attack(row[0],row[1]),'damage');rejected(s,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:main(s).eventId});});
 it('Axe late selection is rejected after damage cutoff',()=>{const s=until(attack('小人のランバ','黒翼飛翔剣'),'attack-abilities');rejected(s,'A',{type:'USE_ABILITY',abilityId:AXE,targetEventId:main(s).eventId});});
 it('Shin failed check consumes its attempt without an addition',()=>{let s=until(attack('侍大将のシン','黒翼飛翔剣'),'effect-level');s=use(s,SPIRIT);s=closeWindow(s);s=closeWindow(s,[6,6]);s=closeWindow(s);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===SPIRIT)).toBe(false);s=until(s,'damage');expect(main(s).technique.effectLevel).toBe(5);});
 it('Fist native 2d6 and independent d6 survive whole-roll reroll and JSON replay',()=>{let s=until(attack('大神官ジル','狼牙'),'effect-level');const god=handCard(s,'B','神性介入');const fate=handCard(s,'A','命運凶変');s=use(s,FIST);s=until(s,'damage');expect(s.rolls?.some(r=>r.purpose==='ability-value')??false).toBe(false);s=closeWindow(s,[2,3]);const native=s.rolls!.at(-1)!.id;s=closeWindow(s,[4]);const bonus=s.rolls!.at(-1)!.id;expect(bonus).not.toBe(native);expect(s.rolls!.at(-1)).toMatchObject({formula:'d6',purpose:'ability-value',faces:[4]});rejected(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:bonus});s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:bonus});s=closeWindow(s,[6]);s=closeWindow(s);expect(s.rolls!.find(r=>r.id===native)).toMatchObject({faces:[2,3],total:5});expect(s.rolls!.find(r=>r.id===bonus)).toMatchObject({faces:[6],total:6,attempts:[{faces:[4]},{faces:[6]}]});expect(main(s).technique.damage).toBe(11);expect(Object.values(s.groups!)[0]!.targets[0]!.hits[0]!.damage).toBe(11);});
});
describe('printed eligibility and shared source semantics',()=>{
 it.each([
  ['小人のランバ','踏み込み／弓',0,false],['小人のランバ','黒翼飛翔剣',-4,true],['小人のランバ','死鬼旋風脚',5,false],
 ] as const)('Axe on %s %s retains declared qualification after warrior delta %s',(owner,card,delta,eligible)=>{let s=attack(owner,card);s.players.A!.permanent={warrior_level:delta};s=until(s,'damage');expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===AXE)).toBe(eligible);if(eligible){s=use(s,AXE);s=until(s,'attack-abilities');expect(main(s).technique.damage).toBe(14);}});
 it('selected Dwarf dynamic usage matches saved warrior despite later reduction and applies to all three hits once',()=>{let s=ready();character(s,'A','小人のランバ');s.distances.A!.B=s.distances.B!.A='near';const card=handCard(s,'A','小人族');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true});s.players.A!.permanent={warrior_level:-4};s=until(s,'damage');expect(main(s).technique.useLevel).toBe(5);s=use(s,AXE);s=until(s,'attack-abilities');expect(Object.values(s.groups!)[0]!.targets[0]!.hits.map(h=>h.damage)).toEqual([12,12,12]);});
 it('Fist uses warrior at effect cutoff, never lowers stronger base, and freezes that result',()=>{let s=until(attack('大神官ジル','死鬼滅殺拳'),'effect-level');s=use(s,FIST);s=closeWindow(s);expect(main(s).technique.effectLevel).toBe(8);s.players.A!.permanent={warrior_level:4};s=until(s,'damage');expect(main(s).technique.effectLevel).toBe(10);s.players.A!.permanent={warrior_level:-5};s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(10);expect(main(s).technique.damage).toBe(11);});
 it('Spirit never treats a generic evade defense placeholder as a technique',()=>{let s=ready();character(s,'B','侍大将のシン');const card=handCard(s,'A','黒翼飛翔剣');const maai=handCard(s,'B','見切る');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:maai,dedicated:false});s=until(s,'effect-level');s=priority(s,'B');expect(viewFor(s,'B').abilityOptions.some(o=>o.abilityId===SPIRIT)).toBe(false);});
 it.each([['白魔術師シェリム','黒翼飛翔剣',STAFF],['大神官ジル','黒翼飛翔剣',FIST],['邪祭ウーノス','黒翼飛翔剣',POWER],['小人のランバ','妖獣',AXE]] as const)('does not offer %s on an unrelated printed school/attribute', (owner,card,id)=>{let s=until(attack(owner,card),id===AXE?'damage':'effect-level');expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===id)).toBe(false);});
 it('Shin strengthens a legitimately declared counter and its returned technique only once',()=>{let s=ready();character(s,'B','侍大将のシン');s.distances.A!.B=s.distances.B!.A='near';const card=handCard(s,'A','黒翼飛翔剣');const defense=handCard(s,'B','妖撃破山剣');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false});s=until(s,'effect-level');s=priority(s,'B');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===SPIRIT)!;expect(option).toBeDefined();s=act(s,'B',{type:'USE_ABILITY',abilityId:SPIRIT,targetEventId:option.targetEventId});s=until(s,'attack-abilities');const returned=Object.values(s.groups!).find(g=>g.attackerId==='B')!;expect(returned.technique).toMatchObject({effectLevel:6,damage:4,useLevel:5});expect(returned.targets[0]!.hits[0]!.damage).toBe(4);});
 it('already insufficient counters remain rejected before prospective Spirit boost or card payment',()=>{let s=attack('大神官ジル','死鬼旋風脚');character(s,'B','侍大将のシン');const defense=handCard(s,'B','妖撃破山剣');s=until(s,'normal-defense');rejected(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false});expect(s.players.B!.hand).toContain(defense);});
 it('Shin can strengthen actual parry with null damage and resolved incoming use requirement',()=>{let s=ready();character(s,'B','侍大将のシン');const card=handCard(s,'A','黒翼飛翔剣');const defense=handCard(s,'B','受け流し');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false});s=until(s,'effect-level');s=priority(s,'B');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===SPIRIT)!;s=act(s,'B',{type:'USE_ABILITY',abilityId:SPIRIT,targetEventId:option.targetEventId});s=until(s,'damage');const a=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(a.technique).toMatchObject({effectLevel:6,useLevel:5,damage:null});});
 it('Staff on the played reflection card does not boost copied incoming magic',()=>{let s=ready();character(s,'B','白魔術師シェリム');const card=handCard(s,'A','白光');const defense=handCard(s,'B','神王界');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false});s=until(s,'effect-level');s=priority(s,'B');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===STAFF)!;s=act(s,'B',{type:'USE_ABILITY',abilityId:STAFF,targetEventId:option.targetEventId});s=until(s,'damage');expect(Object.values(s.actions!).find(a=>a.kind==='defense')!.technique.effectLevel).toBe(6);s=until(s,'attack-abilities');const returned=Object.values(s.groups!).find(g=>g.attackerId==='B')!;expect(returned.technique).toMatchObject({effectLevel:5,damage:6});});
 it('Shin freezes relative reflection limit after own effect composition',()=>{let s=ready();character(s,'B','侍大将のシン');const card=handCard(s,'A','白光');const defense=handCard(s,'B','ミラーシールド');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false});s=until(s,'effect-level');s=priority(s,'B');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===SPIRIT)!;s=act(s,'B',{type:'USE_ABILITY',abilityId:SPIRIT,targetEventId:option.targetEventId});s=until(s,'damage');expect(Object.values(s.actions!).find(a=>a.kind==='defense')!.technique).toMatchObject({effectLevel:6,useLevel:5,blockWarriorLimit:6,reflectMagicLimit:7,damage:null});});
 it('Staff strengthens an actual own turn healing technique without creating damage',()=>{let s=ready();character(s,'A','白魔術師シェリム');s.players.A!.damage=10;const card=handCard(s,'A','封傷');s=act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:card,targetIds:['A'],dedicated:false});s=until(s,'effect-level');s=use(s,STAFF);s=until(s,'damage');expect(Object.values(s.actions!).find(a=>a.kind==='turn-technique')!.technique).toMatchObject({effectLevel:6,damage:null});s=finish(s);expect(s.players.A!.damage).toBe(0);});
});
describe('source continuations and ability result ownership',()=>{
 it('Uonos numeric value is independently rerollable and keeps printed usage unchanged',()=>{let s=until(attack('邪祭ウーノス','妖獣'),'effect-level');const god=handCard(s,'B','神性介入');const fate=handCard(s,'A','命運凶変');s=use(s,POWER);s=closeWindow(s,[2]);const id=s.rolls!.at(-1)!.id;expect(viewFor(s,'B').currentRoll).toMatchObject({purpose:'ability-value',formula:'d6',faces:[2]});expect(viewFor(s,'B').currentRoll).not.toHaveProperty('resume');rejected(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:id});s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:id});s=closeWindow(s,[5]);s=closeWindow(s);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[5],attempts:[{faces:[2]},{faces:[5]}]});s=until(s,'damage');expect(main(s).technique).toMatchObject({effectLevel:9,useLevel:4});});
 it('Shin force-failure remains failed through reroll, with a single spent check attempt',()=>{let s=until(attack('侍大将のシン','黒翼飛翔剣'),'effect-level');const fate=handCard(s,'A','命運凶変');const god=handCard(s,'B','神性介入');s=use(s,SPIRIT);s=closeWindow(s);const id=s.rolls!.at(-1)!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:id});s=closeWindow(s);s=closeWindow(s,[1,1]);s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:id});s=closeWindow(s,[2,2]);s=closeWindow(s);s=until(s,'damage');expect(main(s).technique.effectLevel).toBe(5);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({forcedFailure:true,success:false});});
 it.each([STAFF,SPIRIT,POWER,AXE])('selected %s is revalidated if disabled before its own cutoff',id=>{const row=cases.find(c=>c[2]===id)!;let s=until(attack(row[0],row[1]),id===AXE?'damage':'effect-level');const base=main(s).technique.effectLevel;s=use(s,id);if(id===POWER){s=closeWindow(s,[4]);s=closeWindow(s);}else if(id===SPIRIT){s=closeWindow(s);s=closeWindow(s,[1,1]);s=closeWindow(s);}else s=closeWindow(s);s.players.A!.statuses=[{id:'stop',kind:'stopped',modifiers:[0],nextCheck:0}];s=until(s,'attack-abilities');expect(main(s).technique.effectLevel).toBe(base);if(id===AXE)expect(main(s).technique.damage).toBe(7);});
 it('foreign actor and forged same-prefix source cannot select a pending real action modifier',()=>{let s=until(attack('侍大将のシン','黒翼飛翔剣'),'effect-level');rejected(s,'A',{type:'USE_ABILITY',abilityId:'c2-p01-r2c1-ab99',targetEventId:main(s).eventId});s=priority(s,'B');character(s,'B','侍大将のシン');expect(viewFor(s,'B').abilityOptions.some(o=>o.abilityId===SPIRIT)).toBe(false);rejected(s,'B',{type:'USE_ABILITY',abilityId:SPIRIT,targetEventId:main(s).eventId});});
 it('public windows do not depend on hidden owner and no internal modifier record enters another view',()=>{let s=until(attack('侍大将のシン','黒翼飛翔剣'),'effect-level');const other=structuredClone(s);character(other,'A','黒騎士ガーウィン');expect(viewFor(s,'B').activeWindow).toEqual(viewFor(other,'B').activeWindow);expect(viewFor(s,'B').actionCalculation).toEqual(viewFor(other,'B').actionCalculation);s=use(s,SPIRIT);s=until(s,'damage');const wire=JSON.stringify(viewFor(s,'B'));for(const secret of ['declarationWarrior','usageRequirement','effectBase','prayerAddition','damageRollId',SPIRIT])expect(wire).not.toContain(secret);});
 it('actual Shin shared multi-target/multi-hit group freezes one effect contribution',()=>{let s=ready();character(s,'A','侍大将のシン');const card=handCard(s,'A','天地百撃斬');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==card);s.players.A!.chants.push({cardInstanceId:card,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true});s=until(s,'effect-level');s=use(s,SPIRIT);s=until(s,'damage');s=closeWindow(s,[3]);s=until(s,'attack-abilities');const g=Object.values(s.groups!)[0]!;expect(g.technique).toMatchObject({effectLevel:8,useLevel:7,damage:7});expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual([[7,7,7],[7,7,7]]);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);});
 it('C10 ordinary Fairy resolves usage before checks; Prayer modifies only that selected source effect',()=>{let s=ready();character(s,'A','魔聖母ディア');s.distances.A!.B=s.distances.B!.A='near';const fairy=handCard(s,'A','妖精族');const soldier=handCard(s,'A','兵士');const prayer=handCard(s,'A','必勝の祈り');s=act(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources:[{cardInstanceId:fairy,dedicated:false,targetIds:['B']},{cardInstanceId:soldier,dedicated:false,targetIds:['B']}]});s=closeWindow(s);s=closeWindow(s,[4]);s=closeWindow(s);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',stage:'before-roll'});s=until(s,'effect-level');const a=Object.values(s.actions!).find(a=>a.cardInstanceId===fairy)!;expect(a.modifiers).toMatchObject({usageRequirement:7,declarationWarrior:0});s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:a.id});s=closeWindow(s,[3]);s=closeWindow(s);s=until(s,'damage');s=closeWindow(s,[2]);s=until(s,'attack-abilities');const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.hits.map(h=>[h.technique!.useLevel,h.technique!.effectLevel,h.damage])).toEqual([[7,10,6],[1,1,1]]);expect(viewFor(s,'B').followerBundle!.sources.map(a=>a.technique.calculation)).toEqual([{effectLevel:'final',damage:'final'},{effectLevel:'final',damage:'final'}]);});
 it('Beast actual composed declaration saves use6 and one native 2d6 base plus ten',()=>{let s=ready();character(s,'A','獣使いのウパニシャット');s.distances.A!.B=s.distances.B!.A='near';const beast=handCard(s,'A','獣王剣');const wolf=handCard(s,'A','狼牙');s=act(s,'A',{type:'ATTACK',cardInstanceId:beast,targetIds:['B'],dedicated:true,coSource:{cardInstanceId:wolf,dedicated:false}});expect(main(s).modifiers).toMatchObject({usageRequirement:6,declarationWarrior:6});s=until(s,'damage');s=closeWindow(s,[3,4]);s=until(s,'attack-abilities');expect(main(s).technique).toMatchObject({effectLevel:6,useLevel:6,damage:17});expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);});
 it('Vanmil actual transformation does not inherit Uonos numerical ability',()=>{let s=ready();character(s,'A','邪祭ウーノス');handCard(s,'A','復活の儀式');s=act(s,'A',{type:'USE_REVIVAL_RITUAL'});s=finish(s);expect(s.players.A!.abilityCharacterIds).toEqual(['c2-p07-r1c2']);s=act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(5)});for(const actor of ['B','C','D']){s=act(s,actor,{type:'START_TURN'});s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});s=act(s,actor,{type:'PASS_ACTION'});s=act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(5)});}s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});const card=handCard(s,'A','妖獣');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'effect-level');expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===POWER)).toBe(false);});
});
