import {expect,it} from 'vitest';
import {viewFor,transition,gameStats,type GameState, discardIds } from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeArmyPhysicalScenario,armyPhysicalCard as ARMY} from './fixtures/all-army-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=Array(40).fill(1)){for(let n=0;n<600;n++){if(done(s))return s;s=pass(s,dice);}throw Error('ARMY_PHYSICAL_LIMIT');}
function settle(s:GameState,dice=Array(40).fill(1)){return until(s,s=>!s.windows?.length,dice);}
function command(follower:string,targetIds=['B']){return {type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:follower,targetIds};}
function reject(s:GameState,id:string,cmd:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:cmd} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['griffon','upa','female','dwarf','suppressed'] as const)('%s actual hand follower pays two sources then separate parent follower and required morale lead to printed ordinary hits',name=>{
 let {s,follower}=makeArmyPhysicalScenario(name,players);if(name==='suppressed')expect(s.players.A!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);const hand=[...s.players.A!.hand],deck=[...s.deck],placed=structuredClone(s.players.A!.followers),rollCount=s.rolls?.length??0,option=viewFor(s,'A').allArmyOptions.find(o=>o.followerCardInstanceId===follower)!;expect(option.moraleRequired).toBe(true);s=act(s,'A',command(follower));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==ARMY&&id!==follower));expect(s.deck).toEqual(deck);expect(s.resolution).toEqual(expect.arrayContaining([ARMY,follower]));expect(viewFor(s,'A').currentAction).toMatchObject({cardInstanceId:ARMY});reject(s,'A',command(follower));
 s=closeWindow(s);expect(viewFor(s,'A').currentAction).toMatchObject({cardInstanceId:follower});s=closeWindow(s);expect(s.rolls!.at(-1)).toMatchObject({purpose:'follower-morale',modifier:name==='dwarf'?-2:0});s=closeWindow(s,[1,1]);expect(s.rolls!.at(-1)!.threshold).toBe(name==='dwarf'?4:6);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values(s.groups!).at(-1)!;expect(g.technique.effectLevel).toBe(name==='female'||name==='dwarf'?4:5);expect(g.technique.attributes).toEqual(name==='female'?['遠','魔','弓']:name==='dwarf'?['遠','戦','斧']:['遠','戦','格']);expect(g.targets[0]!.hits.map(h=>h.damage)).toEqual(name==='female'?[6]:name==='dwarf'?[6,6,6]:[8,8]);
 s=settle(s);expect(s.players.B!.damage).toBe(name==='female'?6:name==='dwarf'?18:16);expect(s.players.A!.followers).toEqual(placed);expect(s.rolls!.slice(rollCount).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);for(const id of [ARMY,follower])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(s.phase).toBe('withdrawal');expect(Object.keys(s.actions!)).toEqual([]);expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==ARMY&&id!==follower));
});
it.each([['griffon',3,3,true],['morale-fail',3,4,false]] as const)('%s actual morale roll %s plus %s freezes equality success or above-threshold failure with both cards consumed',(name,x,y,success)=>{let {s,follower}=makeArmyPhysicalScenario(name,players);s=closeWindow(closeWindow(act(s,'A',command(follower))));s=closeWindow(s,[x,y]);const roll=structuredClone(s.rolls!.at(-1)!);expect(roll).toMatchObject({purpose:'follower-morale',threshold:6,total:x+y,success});s=settle(s);expect(s.rolls!.find(r=>r.id===roll.id)).toEqual({...roll,stage:'applied'});expect(s.players.B!.damage).toBe(success?16:0);for(const id of [ARMY,follower])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);expect(s.phase).toBe('withdrawal');reject(s,'A',command(follower));});
it.each(['wood','soldier'] as const)('%s actual prior approach validates near printed bottom and attacks without any morale roll or placement',name=>{let {s,follower}=makeArmyPhysicalScenario(name,players);reject(s,'A',command(follower));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c2',targetId:'B'}));expect(s.distances.A!.B).toBe('near');expect(viewFor(s,'A').allArmyOptions.find(o=>o.followerCardInstanceId===follower)).toMatchObject({range:'near',moraleRequired:false,effectLevel:name==='wood'?3:1});s=settle(act(s,'A',command(follower)));expect(s.players.B!.damage).toBe(name==='wood'?5:1);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);expect(s.players.A!.followers).toEqual([]);expect(discardIds(s)).toEqual(expect.arrayContaining([ARMY,follower]));});
it.each(['parent','child','force','reroll'] as const)('%s actual Fate cancels one dependency or morale and forced failure persists through actual God reroll',name=>{
 let {s,follower}=makeArmyPhysicalScenario(name,players);s=act(s,'A',command(follower));if(name!=='parent')s=closeWindow(s);if(name==='force'||name==='reroll')s=closeWindow(s);s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');const v=viewFor(s,'D'),rollId=v.reactionTargetRollId!;s=act(s,'D',name==='force'||name==='reroll'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:rollId}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:v.reactionTargetActionId!});
 if(name==='reroll'){s=until(s,s=>s.rolls!.find(r=>r.id===rollId)!.stage==='after-roll'&&s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:rollId});}
 s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);expect(Object.keys(s.groups??{})).toEqual([]);for(const id of [ARMY,follower])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);if(name==='force'||name==='reroll')expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({forcedFailure:true,success:false,...(name==='reroll'?{generation:1,total:2}:{})});expect(s.phase).toBe('withdrawal');
});
it('fairy actual morale precedes random printed use level and its frozen nine creates four ordinary excess-level checks',()=>{let {s,follower}=makeArmyPhysicalScenario('fairy',players);s=closeWindow(closeWindow(act(s,'A',command(follower))));s=closeWindow(s,[1,1]);s=closeWindow(s,[6]);expect(s.rolls!.at(-1)!.purpose).toBe('technique-value');s=closeWindow(s);expect(s.rolls!.at(-1)!.purpose).toBe('excess-level');expect(Object.values(s.actions!).find(a=>a.allArmyParentId)!.technique.useLevel).toBe(9);s=settle(s);expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(4);expect(s.players.B!.damage).toBe(5);});
it('earth actual mandatory-all bottom rejects partial targets and destroys a real placed ground follower before all three damage results',()=>{let {s,follower}=makeArmyPhysicalScenario('earth',players);const o=viewFor(s,'A').allArmyOptions.find(o=>o.followerCardInstanceId===follower)!;expect(o.targetMode).toBe('mandatory-all');expect(o.legalTargetIds).toEqual(['B','C','D']);reject(s,'A',command(follower));expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toContain('a2-p18-r3c3');s=settle(act(s,'A',command(follower,o.legalTargetIds)));for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(8);expect(s.players.B!.followers).toEqual([]);expect(discardIds(s)).toContain('a2-p18-r3c3');});
it.each(['placed','foreign','stopped','silenced'] as const)('%s actual setup placement foreign deal Hypnosis skip or Silence forbids source before either payment',name=>{const {s,follower}=makeArmyPhysicalScenario(name,players);if(name==='placed')expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toContain(follower);if(name==='foreign')expect(s.players.B!.hand).toContain(follower);if(name==='stopped')expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);if(name==='silenced')expect(s.players.A!.statuses?.some(x=>x.kind==='silenced')).toBe(true);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===follower)).toBe(false);reject(s,'A',command(follower));expect(s.players.A!.hand).toContain(ARMY);});
it('decline actual timing identity one-card payload and target refusals preserve all views and passing keeps both sources',()=>{let {s,follower}=makeArmyPhysicalScenario('decline',players,true);reject(s,'A',command(follower));s=act(s,'A',{type:'START_TURN'});reject(s,'A',command(follower));s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});const hand=[...s.players.A!.hand];reject(s,'B',command(follower));for(const targetIds of [[],['A'],['B','C'],['B','B'],['missing']])reject(s,'A',command(follower,targetIds));reject(s,'A',{...command(follower),followerCardInstanceIds:[follower,follower]});reject(s,'A',{...command(follower),followerCardInstanceId:ARMY});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toEqual(hand);expect(s.resolution).toEqual([]);});
