import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,finish,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeAmuletPhysicalScenario,amuletMode,type AmuletPhysicalScenario} from '../../../apps/worker/test/fixtures/amulet-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p01-r3c2';
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1,2]){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('AMULET_WINDOW');}
function at(s:GameState,kind:string){return until(s,s=>s.windows?.at(-1)?.kind===kind);}
function priority(s:GameState,id:string){return until(s,s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]===id;});}
function attack(name:AmuletPhysicalScenario){return at(act(makeAmuletPhysicalScenario(name,players),'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false}),'normal-defense');}
function use(s:GameState,name:AmuletPhysicalScenario){const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===amuletMode(name).abilityId)!;expect(o).toBeDefined();return act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});}
function option(s:GameState){return viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===card);}
function play(s:GameState){s=until(s,s=>!!option(s));return act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:option(s)!.targetEventId});}
function settle(s:GameState,dice=[1,2]){return until(s,s=>!s.windows?.length,dice);}
function nextA(s:GameState){for(let n=0;n<300;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('AMULET_TURN_PHASE');}throw Error('AMULET_TURN');}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['amulet-lester','amulet-dia','amulet-fear'] as const)('%s actual named ability cancellation consumes one card and refill but creates no enemy roll or secondary effect',name=>{let s=attack(name);const faction=s.players.A!.faction,profile=structuredClone(s.players.A!.currentObjective);s=priority(use(s,name),'D');const event=option(s)!.targetEventId,hand=s.players.D!.hand.length,draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='D').length;for(const [id,target] of [['C',event],['D','stale']] as const)reject(s,id,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:target});const source=Object.values(s.groups!)[0]!.actionId;reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:source});s=play(s);expect(s.players.D!.hand).toHaveLength(hand);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='D')).toHaveLength(draws+1);s=until(s,s=>!s.abilities?.[event]);expect(viewFor(s,'B').abilityOptions.some(o=>o.abilityId===amuletMode(name).abilityId)).toBe(false);s=settle(s,[6,6]);expect(s.rolls?.filter(r=>r.purpose==='ability-check')??[]).toEqual([]);expect(s.players.A).toMatchObject({presence:'active',faction,currentObjective:profile});expect(s.players.A!.statuses??[]).toEqual([]);expect(s.players.B!.damage).toBe(4);expect(s.discard.filter(id=>id===card)).toHaveLength(1);reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});});
it.each(['amulet-lester','amulet-dia','amulet-fear'] as const)('%s declining the Amulet permits actual non-double mental check and leaves physical response unspent',name=>{let s=attack(name),hand=[...s.players.D!.hand];s=settle(use(s,name),[1,2]);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.players.B!.damage).toBe(4);expect(s.players.D!.hand).toEqual(hand);expect(s.players.A!.statuses??[]).toEqual([]);});
it.each(['amulet-lester','amulet-dia','amulet-fear'] as const)('%s late after-roll and completed ability cannot be canceled retroactively',name=>{let s=use(attack(name),name),event=Object.values(s.abilities!)[0]!.id;s=until(s,s=>s.windows?.at(-1)?.kind==='after-roll',[2,2]);s=priority(s,'D');expect(option(s)).toBeUndefined();reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});s=settle(s,[2,2]);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.players.B!.damage).toBe(0);expect(s.players.D!.hand).toContain(card);reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});});
it.each(['amulet-lester','amulet-dia','amulet-fear'] as const)('%s without Amulet actual double-six demonstrates the canceled conversion or fatal consequence',name=>{const initial=attack(name),old=initial.players.A!.faction;const s=settle(use(initial,name),[6,6]);expect(s.rolls!.find(r=>r.purpose==='ability-check')!.faces).toEqual([6,6]);expect(s.players.B!.damage).toBe(0);if(name==='amulet-fear')expect(s.players.A!.presence).toBe('dead');else{expect(s.players.A!.faction).toBe(name==='amulet-lester'?'GOOD':'EVIL');expect(s.players.A!.faction).not.toBe(old);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);}expect(s.players.D!.hand).toContain(card);});
it('actual Fate cancellation of Amulet restores mental check and double effect while preserving immediate refill',()=>{let s=play(use(attack('amulet-canceled'),'amulet-canceled'));const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!,hand=s.players.D!.hand.length;s=priority(s,'C');s=settle(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}),[2,2]);expect(s.players.B!.damage).toBe(0);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.players.D!.hand).toHaveLength(hand);for(const id of [card,'a2-p02-r2c3'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);});
it('actual immediate Blood OPEN refill finishes before Amulet child and canceled mental parent never resumes a roll',()=>{let s=use(attack('amulet-refill'),'amulet-refill');const before=gameStats(s,'D');s=play(s);expect(s.players.D!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'D')).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});s=settle(s);expect(s.players.B!.damage).toBe(4);expect(s.rolls?.filter(r=>r.purpose==='ability-check')??[]).toEqual([]);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId==='a2-p01-r1c3')).toHaveLength(1);});
it.each(['amulet-past-stop','amulet-past-charm'] as const)('%s a new canceled declaration leaves actual prior stop and allegiance exactly intact',name=>{let s=attack(name);const prior=structuredClone(s.players.C!),rolls=s.rolls!.length;expect(prior.statuses?.some(t=>t.kind==='stopped')).toBe(true);if(name==='amulet-past-charm')expect(prior.faction).toBe('EVIL');s=settle(play(use(s,name)));expect(s.players.C).toEqual(prior);expect(s.rolls).toHaveLength(rolls);expect(s.players.B!.damage).toBe(4);});
it('actual next attack offers the same mental ability again after Amulet canceled only the prior declaration',()=>{let s=settle(play(use(attack('amulet-later'),'amulet-later')));s=nextA(s);s=at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['B'],dedicated:false}),'normal-defense');s=settle(use(s,'amulet-later'),[2,2]);expect(s.players.B!.damage).toBe(4);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual same-name Charm turn card never exposes an Amulet ability cancellation candidate',()=>{let s=act(makeAmuletPhysicalScenario('amulet-card-charm',players),'A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r1c2',targetId:'C'});s=priority(s,'D');expect(option(s)).toBeUndefined();const event=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p04-r1c2')!.id;reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});s=settle(s,[6,6]);expect(s.players.D!.hand).toContain(card);expect(s.discard.filter(id=>id==='a2-p04-r1c2')).toHaveLength(1);expect(s.players.C!.faction).toBe('EVIL');});
it('actual Ida Shadow ability stays outside the three named mental defenses',()=>{let s=priority(use(attack('amulet-other-ability'),'amulet-other-ability'),'D');expect(option(s)).toBeUndefined();reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:Object.values(s.abilities!)[0]!.id});s=settle(s,[1,2]);expect(s.players.D!.hand).toContain(card);expect(s.rolls!.filter(r=>r.purpose==='ability-check').length).toBeGreaterThan(0);});
