import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeAttributeJewelsPhysicalScenario,jewelMode} from './fixtures/attribute-jewels-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,face=1){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s,[face,face]);}throw Error('JEWEL_LIMIT');}
function settle(s:GameState,face=1){return until(s,s=>!s.windows?.length,face);}
function reject(s:GameState,id:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['crown-install','crystal-install'] as const)('%s actual own-turn installation pays one card without refill consumes main action and publicly stays on self',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players);const m=jewelMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],command={type:'PLAY_TURN_CARD',cardInstanceId:m.card};reject(s,'B',command);reject(s,'A',{...command,mode:'dedicated'});reject(s,'A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:m.card});s=act(s,'A',command);expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==m.card));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(m.card);expect(s.players.A!.attachments).not.toContain(m.card);reject(s,'A',command);s=settle(s);expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.attachments).toEqual([m.card]);expect(s.discard).not.toContain(m.card);expect(s.resolution).toEqual([]);for(const id of s.seatOrder)expect(viewFor(s,id).players.A!.attachments).toEqual([m.card]);expect(gameStats(s,'A').magic_level).toBe(3);expect(gameStats(s,'A').moraleBonus).toBe(0);reject(s,'A',{type:'PASS_ACTION'});reject(s,'A',command);});
it.each([
 ['crown-element','a2-p16-r2c3',1],['crown-element','a2-p12-r2c2',1],['crown-element','a2-p15-r3c2',1],['crown-element','a2-p14-r3c3',1],['crown-element','a2-p14-r1c1',0],['crown-element','a2-p13-r2c1',0],['crown-element','a2-p15-r2c2',0],['crown-element','a2-p14-r1c2',0],['crown-element','a2-p24-r2c2',0],
 ['crystal-element','a2-p16-r2c3',0],['crystal-element','a2-p12-r2c2',0],['crystal-element','a2-p15-r3c2',0],['crystal-element','a2-p14-r3c3',0],['crystal-element','a2-p14-r1c1',2],['crystal-element','a2-p13-r2c1',2],['crystal-element','a2-p15-r2c2',2],['crystal-element','a2-p14-r1c2',0],['crystal-element','a2-p24-r2c2',0]
] as const)('%s actual spell %s receives only attribute-selected magic bonus %s and changes excess checks without effect-level increase',(name,spell,bonus)=>{let s=makeAttributeJewelsPhysicalScenario(name,players,{spell});const m=jewelMode(name);expect(s.players.A!.attachments).toContain(m.card);expect(gameStats(s,'A').magic_level).toBe(3);s=act(s,'A',{type:'ATTACK',cardInstanceId:spell,targetIds:['B'],dedicated:false});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===spell)!;expect(gameStats(s,'A',{provenance:{kind:'action',id:a.id}}).magic_level).toBe(3+bonus);expect(gameStats(s,'B',{provenance:{kind:'action',id:a.id}}).magic_level).toBe(gameStats(s,'B',{provenance:{kind:'none'}}).magic_level);const base=a.technique.school==='magic'?3+bonus:gameStats(s,'A').warrior_level;expect(a.checkSpecs?.filter(c=>c.purpose==='excess-level')??[]).toHaveLength(Math.max(0,a.technique.useLevel-base));const level=a.technique.effectLevel;s=settle(s);expect(s.players.A!.attachments).toContain(m.card);expect(gameStats(s,'A').magic_level).toBe(3);expect(s.phase).toBe('withdrawal');expect(s.discard).toContain(spell);expect(level).toBe(({'a2-p16-r2c3':4,'a2-p12-r2c2':4,'a2-p15-r3c2':4,'a2-p14-r3c3':4,'a2-p14-r1c1':5,'a2-p13-r2c1':4,'a2-p15-r2c2':6,'a2-p14-r1c2':5,'a2-p24-r2c2':3} as Record<string,number>)[spell]);});
it.each(['crown-human','crystal-human','crown-wrong','crystal-wrong','crown-nonhuman','crystal-nonhuman','crown-convert-on','crystal-convert-on','crown-convert-off','crystal-convert-off','crown-army-human','crystal-army-human','crown-army-nonhuman','crystal-army-nonhuman'] as const)('%s actual human follower morale uses current faction after installation and real conversion',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players);const m=jewelMode(name),bonus=m.follower==='a2-p21-r2c2'&&m.finalEvil!==m.crown?m.bonus:0;expect(s.players.A!.attachments).toContain(m.card);expect(s.players.A!.faction).toBe(m.finalEvil?'EVIL':'GOOD');if(m.converted){expect(s.initialFactions![0]).toBe(m.initialEvil?'EVIL':'GOOD');expect(s.events.some(e=>e.type==='FACTION_CHANGED'&&e.actorId==='A')).toBe(true);}s=m.army?act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.follower,targetIds:['B']}):act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});s=until(s,s=>s.rolls?.at(-1)?.purpose==='follower-morale');const roll=s.rolls!.at(-1)!;expect(roll.stage).toBe('before-roll');expect(gameStats(s,'A',{provenance:{kind:'roll',id:roll.id}}).moraleBonus).toBe(bonus);s=until(s,s=>s.rolls!.find(r=>r.id===roll.id)!.stage==='after-roll',3);expect(s.rolls!.find(r=>r.id===roll.id)).toMatchObject({threshold:6+roll.modifier+bonus,faces:[3,3],success:true});s=settle(s);expect(s.players.A!.attachments).toContain(m.card);expect(s.players.A!.faction).toBe(m.finalEvil?'EVIL':'GOOD');});
it.each(['crown-training','crystal-training'] as const)('%s actual magic training compares unconditional level excluding attribute-specific attachment',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players,{magic:6});const m=jewelMode(name);s=act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r2c3'});s=until(s,s=>s.rolls?.at(-1)?.purpose==='training');const id=s.rolls!.at(-1)!.id;s=until(s,s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll',3);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({threshold:6,total:6,comparison:'greater-than',success:false});s=settle(s);expect(s.players.A!.attachments).toEqual([m.card]);expect(s.discard).toContain('a2-p03-r2c3');expect(gameStats(s,'A').magic_level).toBe(6);});
it.each(['crown-fate','crystal-fate'] as const)('%s actual Fate cancellation pays source but creates no attachment or bonus',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players);const m=jewelMode(name),hand=s.players.A!.hand.length;s=act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card});const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.A!.hand).toHaveLength(hand-1);expect(s.players.A!.attachments).not.toContain(m.card);expect(s.discard).toContain(m.card);expect(s.phase).toBe('hand-adjustment');expect(gameStats(s,'A').magic_level).toBe(3);});
it.each(['crown-decline','crystal-decline'] as const)('%s actual turn decline retains source in hand and no passive correction',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players);const m=jewelMode(name);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(m.card);expect(s.players.A!.attachments).toEqual([]);expect(gameStats(s,'A').magic_level).toBe(3);});
it.each(['crown-training','crystal-training'] as const)('%s actual Blood OPEN contributes to magic training while installed attribute bonus remains excluded',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players,{magic:6,blood:true});const m=jewelMode(name);expect(s.players.A!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'A').magic_level).toBe(7);s=act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r2c3'});s=until(s,s=>s.rolls?.at(-1)?.purpose==='training');const id=s.rolls!.at(-1)!.id;s=until(s,s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll',4);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({threshold:7,total:8,success:true});s=settle(s);expect(s.players.A!.attachments).toEqual([m.card,'a2-p03-r2c3']);expect(gameStats(s,'A').magic_level).toBe(8);});
it.each(['crown-install','crystal-install'] as const)('%s installed physical card is disposed once by actual lethal attack after surviving turn end',name=>{let s=makeAttributeJewelsPhysicalScenario(name,players,{endurance:4});const m=jewelMode(name);s=settle(act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:m.card}));s=settle(act(s,'A',{type:'END_TURN',discardIds:[]}));expect(s.players.A!.attachments).toContain(m.card);s=settle(act(s,'B',{type:'START_TURN'}));s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});s=until(s,s=>s.windows?.at(-1)?.kind==='death-gift');expect(s.players.A!.attachments).toContain(m.card);s=settle(s);expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.attachments).toEqual([]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);});
