import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeBeastKingPhysical,beastKingCard as CARD,beastKingMode} from '../../../apps/worker/test/fixtures/beast-king-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=Array(30).fill(1)){for(let n=0;n<800;n++){if(done(s))return s;s=pass(s,dice);}throw Error('BEAST_KING_LIMIT');}
function settle(s:GameState,dice=Array(30).fill(1)){return until(s,s=>!s.windows?.length,dice);}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function cmd(dedicated=true,co?:string,targetIds=['B'],coDedicated=false){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated,...(co?{coSource:{cardInstanceId:co,dedicated:coDedicated}}:{})};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['beast-king-ordinary','beast-king-guard','beast-king-owner-ordinary','beast-king-dedicated','beast-king-nonbeast','beast-king-near','beast-king-same-faction','beast-king-suppressed','beast-king-silenced'] as const)('%s actual optional standalone sword retains use6 damage10 and destroys only beast followers',name=>{
 let s=makeBeastKingPhysical(name,players);const m=beastKingMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],rolls=s.rolls?.length??0;if(m.suffix==='same-faction')reject(s,'A',cmd(true,undefined,['C']));if(m.near)expect(s.distances.A!.B).toBe('near');reject(s,'A',cmd(m.dedicated,undefined,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:6,damage:10,attributes:['戦','剣','獣'],target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});if(m.dedicated)expect(group(s).technique.destroyFollowerAttributes).toEqual(['獣']);s=settle(s);expect(s.players.B!.damage).toBe(m.guard&&(!m.dedicated||m.suffix==='nonbeast')?0:10);expect(s.players.C!.damage).toBe(0);if(m.guard&&m.dedicated&&m.suffix!=='nonbeast'){expect(s.players.B!.followers).toEqual([]);expect(s.discard).toContain('a2-p23-r1c1');}else if(m.guard){expect(s.players.B!.followers).toHaveLength(1);expect(s.players.B!.followers[0]!.revealed).toBe(true);}expect(s.rolls?.length??0).toBe(rolls+(m.guard&&(!m.dedicated||m.suffix==='nonbeast')?1:0));expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.phase).toBe('withdrawal');
});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior5 spirit6 shortage check %s plus %s succeeds=%s',(x,y,success)=>{let s=act(makeBeastKingPhysical('beast-king-low',players),'A',cmd(false));s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?10:0);expect(s.rolls).toHaveLength(1);});
it.each([['beast-king-bow',14],['beast-king-spirit',16],['beast-king-null',10],['beast-king-chant',22],['beast-king-union',16]] as const)('%s actual two paid physical sources inherit components while composite levels remain6 and result=%s',(name,damage)=>{
 let s=makeBeastKingPhysical(name,players);const m=beastKingMode(name),hand=[...s.players.A!.hand],deck=[...s.deck];expect(viewFor(s,'A').combinationOptions.flatMap(o=>o.coSources)).toContainEqual({cardInstanceId:m.co,dedicated:false});expect(viewFor(s,'B').combinationOptions).toEqual([]);s=act(s,'A',cmd(true,m.co));expect(s.players.A!.hand).toEqual(hand.filter(id=>![CARD,m.co].includes(id)));expect(s.deck).toEqual(deck);expect(s.resolution).toEqual(expect.arrayContaining([CARD,m.co]));if(name==='beast-king-null')expect(source(s).coSource!.technique.damage).toBeNull();if(m.chant){expect(source(s).coSource!.fromChant).toBe(true);expect(s.players.A!.chants).toEqual([]);}s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',useLevel:6,effectLevel:6,damage,noChecks:true});expect(group(s).sourceCardInstanceIds).toEqual([CARD,m.co]);expect(group(s).technique.attributes).toEqual(expect.arrayContaining(['戦','剣','獣']));if(name==='beast-king-spirit')expect(group(s).technique).toMatchObject({followerIgnore:true,attributes:['戦','剣','獣','精','忍']});if(name==='beast-king-null')expect(group(s).technique).toMatchObject({counter:true,damage:10});if(name==='beast-king-union')expect(group(s).technique).toMatchObject({range:'near',destroyFollowerAttributes:['獣','白']});s=settle(s);expect(s.players.B!.damage).toBe(damage);if(name==='beast-king-spirit'){expect(s.players.B!.followers).toHaveLength(1);expect(s.players.B!.followers[0]!.revealed).toBe(false);}else expect(s.players.B!.followers).toEqual([]);expect(s.rolls?.length??0).toBe(0);for(const id of [CARD,m.co])expect(s.discard.filter(c=>c===id)).toHaveLength(1);
});
it('actual physical Wolf co-source shares one numeric2d6 and adds ten once',()=>{let s=act(makeBeastKingPhysical('beast-king-wolf',players),'A',cmd(true,'a2-p10-r3c1'));s=until(s,s=>s.windows?.at(-1)?.kind==='damage');s=closeWindow(s,[3,4]);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({useLevel:6,effectLevel:6,damage:17,range:'near'});expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.rolls!.at(-1)).toMatchObject({faces:[3,4],total:7,kind:'numeric'});s=settle(s);expect(s.players.B!.damage).toBe(17);});
it.each([[2,2,true],[2,3,false]] as const)('actual prepared HundredSlash retains spirit6 minus2 activation %s plus %s success=%s before one d6 hit count',(x,y,success)=>{let s=makeBeastKingPhysical('beast-king-multi',players);expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain('a2-p10-r1c3');s=act(s,'A',cmd(true,'a2-p10-r1c3'));s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'activation',threshold:4,total:x+y,success});if(!success){s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.rolls).toHaveLength(1);for(const id of [CARD,'a2-p10-r1c3'])expect(s.discard.filter(c=>c===id)).toHaveLength(1);return;}s=until(s,s=>s.windows?.at(-1)?.kind==='damage');s=closeWindow(s,[3]);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({useLevel:6,effectLevel:6,damage:17,hitCount:3,chant:true,noChecks:true});expect(group(s).targets[0]!.hits.map(h=>h.damage)).toEqual([17,17,17]);expect(s.rolls!.filter(r=>r.purpose==='attack-hit-count')).toHaveLength(1);expect(s.rolls!.some(r=>r.purpose==='excess-level')).toBe(false);s=settle(s);expect(s.players.B!.damage).toBe(51);expect(s.players.C!.damage).toBe(0);for(const id of [CARD,'a2-p10-r1c3'])expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it('actual placed Griffin dedicated co-source inherits two selected targets and two shared eighteen damage hits',()=>{let s=makeBeastKingPhysical('beast-king-placed-griffin',players);const co='a2-p20-r3c1';expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toContain(co);s=act(s,'A',cmd(true,co,['B','C'],true));expect(s.players.A!.followers).toEqual([]);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({useLevel:6,effectLevel:6,damage:18,hitCount:2,target:'all'});expect(group(s).targets.map(t=>t.hits.map(h=>h.damage))).toEqual([[18,18],[18,18]]);s=settle(s);expect(s.players.B!.damage).toBe(36);expect(s.players.C!.damage).toBe(34);expect(s.players.D!.damage).toBe(0);for(const id of [CARD,co])expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it.each(['beast-king-maai-one','beast-king-maai-two','beast-king-evade-restrict'] as const)('%s actual co-source defense restrictions govern the whole composite',name=>{let s=makeBeastKingPhysical(name,players);const m=beastKingMode(name);s=until(act(s,'A',cmd(true,m.co)),s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.suffix==='evade-restrict'){expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}else{s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});s=until(s,s=>s.windows?.at(-1)?.kind!=='reclaim');expect(viewFor(s,'B').maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});if(m.suffix==='maai-two')s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}s=settle(s);expect(s.players.B!.damage).toBe(m.suffix==='maai-two'?0:m.suffix==='maai-one'?17:18);expect(s.players.B!.followers).toHaveLength(m.suffix==='maai-two'?1:0);});
it('actual physical Fate cancellation spends both elected sources once and records separate source use without a hit',()=>{let s=act(makeBeastKingPhysical('beast-king-fate',players),'A',cmd(true,'a2-p08-r3c3'));const a=source(s);s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.used).toEqual(expect.arrayContaining([`${a.eventId}:A:${CARD}`,`${a.eventId}:A:a2-p08-r3c3`]));for(const id of [CARD,'a2-p08-r3c3'])expect(s.discard.filter(c=>c===id)).toHaveLength(1);expect(s.rolls?.length??0).toBe(0);});
it('actual inherited Shuriken counter returns composed15 with effect6 against incomingBow3',()=>{let s=makeBeastKingPhysical('beast-king-counter',players);reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true});s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true,coSource:{cardInstanceId:'a2-p08-r2c3',dedicated:false}});s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities'&&Object.values(s.groups!).some(g=>g.actionId===source(s).id));expect(group(s).technique).toMatchObject({useLevel:6,effectLevel:6,damage:15,counter:true,noChecks:true});s=settle(s);expect(s.players.A!.damage).toBe(0);expect(s.players.B!.damage).toBe(15);for(const id of [CARD,'a2-p08-r2c3'])expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it('actual near component rejects far before payment and becomes legal after physical approach',()=>{let s=makeBeastKingPhysical('beast-king-near-far',players);reject(s,'A',cmd(true,'a2-p08-r3c1'));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(true,'a2-p08-r3c1')));expect(s.players.B!.damage).toBe(15);expect(s.discard).toEqual(expect.arrayContaining([CARD,'a2-p08-r3c1']));});
it('actual unprepared physical chant co-source rejects even though primary dedicated has no usage checks',()=>{const s=makeBeastKingPhysical('beast-king-unchanted',players);reject(s,'A',cmd(true,'a2-p11-r3c3'));expect(s.players.A!.hand).toEqual(expect.arrayContaining([CARD,'a2-p11-r3c3']));});
it('actual co-source above current warrior5 is not advertised and cannot be paid by spirit checks',()=>{let s=makeBeastKingPhysical('beast-king-level-low',players);expect(gameStats(s,'A').warrior_level).toBe(5);expect(viewFor(s,'A').combinationOptions.flatMap(o=>o.coSources).some(c=>c.cardInstanceId==='a2-p08-r3c3')).toBe(false);reject(s,'A',cmd(true,'a2-p08-r3c3'));s=settle(act(s,'A',cmd()));expect(s.players.B!.damage).toBe(10);expect(s.rolls?.length??0).toBe(0);expect(s.players.A!.hand).toContain('a2-p08-r3c3');});
it('actual exact one own warrior co-source rejects magic unclassified foreign self arrays ordinary primary and wrong dedicated owner',()=>{let s=makeBeastKingPhysical('beast-king-invalid-co',players);for(const co of ['a2-p12-r2c2','a2-p05-r3c1','a2-p24-r2c2',CARD])reject(s,'A',cmd(true,co));reject(s,'A',cmd(true,'a2-p08-r3c3',['B'],true));reject(s,'A',cmd(false,'a2-p24-r1c2'));reject(s,'A',{...cmd(),coSource:[{cardInstanceId:'a2-p24-r1c2',dedicated:false},{cardInstanceId:'a2-p08-r3c3',dedicated:false}]});reject(s,'A',cmd(true,'a2-p24-r1c2',['B','C']));for(const ids of [[],['A'],['B','B'],['missing']])reject(s,'A',cmd(true,undefined,ids));s=settle(act(s,'A',cmd(true,'a2-p24-r1c2')));expect(s.players.B!.damage).toBe(14);expect(s.players.A!.hand).toEqual(expect.arrayContaining(['a2-p12-r2c2','a2-p05-r3c1','a2-p08-r3c3']));});
it('actual wrong source owner stopped recovery and declined own action retain unpaid physical sword',()=>{let s=makeBeastKingPhysical('beast-king-wrong-owner',players);reject(s,'A',cmd());s=makeBeastKingPhysical('beast-king-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd());s=makeBeastKingPhysical('beast-king-decline',players,{beforeStart:true});reject(s,'A',cmd(false));s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd(false));s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'B',cmd(false));reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
