import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeBlackWingPhysical,blackWingCard as CARD,blackWingMode} from '../../../apps/worker/test/fixtures/black-wing-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s);}throw Error('BLACK_WING_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['black-wing-ordinary','black-wing-guard','black-wing-owner-ordinary','black-wing-dedicated','black-wing-near','black-wing-suppressed','black-wing-silenced','black-wing-same-faction'] as const)('%s actual setup Sword ordinary5 seven damage versus elected Arness6 ten damage retains one target and extra MAAI',name=>{
 let s=makeBlackWingPhysical(name,players);const m=blackWingMode(name),damage=m.dedicated?10:7,hand=[...s.players.A!.hand],deck=[...s.deck],followers=structuredClone({B:s.players.B!.followers,C:s.players.C!.followers}),rolls=s.rolls?.length??0;if(name==='black-wing-suppressed')expect(s.players.A!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);if(name==='black-wing-silenced')expect(s.players.A!.statuses?.some(x=>x.kind==='silenced')).toBe(true);if(name==='black-wing-near')expect(s.distances.A!.B).toBe('near');if(name==='black-wing-same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});
 s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(CARD);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values(s.groups!).at(-1)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:5,effectLevel:m.dedicated?6:5,damage,attributes:['戦','剣'],chant:false,noChecks:m.dedicated,followerIgnore:m.dedicated,maaiRequired:2,target:'one'});expect(g.targets.map(t=>t.actorId)).toEqual(['B']);expect(g.targets[0]!.hits.map(h=>h.damage)).toEqual([damage]);expect(s.rolls?.length??0).toBe(rolls);
 s=settle(s);expect(s.players.B!.damage).toBe(!m.guard||m.dedicated?damage:0);for(const id of ['C','D'])expect(s.players[id]!.damage).toBe(0);expect(s.players.C!.followers).toEqual(followers.C);if(m.dedicated){expect(s.players.B!.followers).toEqual(followers.B);expect(s.players.B!.followers[0]!.revealed).toBe(false);}else if(m.guard)expect(s.players.B!.followers[0]!.revealed).toBe(true);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.phase).toBe('withdrawal');expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.rolls?.length??0).toBe(rolls);reject(s,'A',cmd(m.dedicated));
});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior4 needs one actual spirit6 check roll %s plus %s success=%s',(x,y,success)=>{let s=makeBlackWingPhysical('black-wing-low',players);s=act(s,'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?7:0);expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(1);expect(s.discard).toContain(CARD);});
it('dedicated actual Arness warrior0 spirit0 skips five use checks and replaces effect and damage despite placed MetalGolem',()=>{let s=makeBlackWingPhysical('black-wing-dedicated',players,{warrior:0,spirit:0});expect(gameStats(s,'A').warrior_level).toBe(0);expect(gameStats(s,'A').spirit).toBe(0);s=settle(act(s,'A',cmd(true)));expect(s.rolls?.length??0).toBe(0);expect(s.players.B!.damage).toBe(10);expect(s.players.B!.followers[0]!.revealed).toBe(false);});
it('fate actual declaration cancellation pays Sword once while target and placed followers stay unchanged',()=>{let s=makeBlackWingPhysical('black-wing-fate',players);const before=structuredClone(s.players);s=act(s,'A',cmd(true));const action=s.windows!.at(-1)!.continuation.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetActionId:action});s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:action}));expect(s.players.B).toEqual(before.B);expect(s.players.C).toEqual(before.C);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(0);});
it.each(['black-wing-maai-one','black-wing-maai-two','black-wing-ordinary-maai-one','black-wing-ordinary-maai-two','black-wing-evade'] as const)('%s actual defense needs two distinct MAAI in both modes and ordinary evade remains usable',name=>{
 let s=makeBlackWingPhysical(name,players);const m=blackWingMode(name),followers=structuredClone(s.players.B!.followers),two=name.endsWith('-two'),evade=name==='black-wing-evade';s=act(s,'A',cmd(m.dedicated));s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);
 if(evade)s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else{s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});s=until(s,s=>s.windows?.at(-1)?.kind!=='reclaim');expect(viewFor(s,'B').maaiDefense!.targets[0]).toMatchObject({submitted:1,remaining:1});reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(two)s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});}
 s=settle(s);expect(s.players.B!.damage).toBe(two||evade?0:m.dedicated?10:7);expect(s.players.C!.damage).toBe(0);expect(s.players.B!.followers).toEqual(followers);if(!evade){expect(s.discard.filter(id=>id==='a2-p06-r1c3')).toHaveLength(1);expect(s.players.B!.hand.includes('a2-p07-r1c1')).toBe(!two);}expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);
});
it('wrong owner actual ordinary use remains legal but dedicated and malformed single targets reject unchanged',()=>{let s=makeBlackWingPhysical('black-wing-wrong-owner',players);reject(s,'A',cmd(true));for(const ids of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,ids));reject(s,'B',cmd(false));s=settle(act(s,'A',cmd(false)));expect(s.discard).toContain(CARD);expect(s.players.B!.damage).toBe(0);});
it('stopped actual Hypnosis and failed recovery skip the owner turn and refuse both Sword modes',()=>{const s=makeBlackWingPhysical('black-wing-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd(false));reject(s,'A',cmd(true));expect(s.players.A!.hand).toContain(CARD);});
it('decline actual attack-only timing and mode refusals preserve source before passing the ordinary main',()=>{let s=makeBlackWingPhysical('black-wing-decline',players,{beforeStart:true});reject(s,'A',cmd());s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);expect(s.discard).not.toContain(CARD);});
