import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeBlackBreakPhysical,blackBreakCard as CARD,blackBreakMode} from './fixtures/black-break-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<600;n++){if(done(s))return s;s=pass(s);}throw Error('BLACK_BREAK_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['black-break-ordinary','black-break-guard','black-break-owner-ordinary','black-break-dedicated','black-break-same-faction','black-break-white-equal','black-break-white-lower','black-break-suppressed','black-break-silenced'] as const)('%s actual physical approach enables near sword and destroys reached white followers before level defense or morale',name=>{let s=makeBlackBreakPhysical(name,players);const m=blackBreakMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],rolls=s.rolls?.length??0,cFollowers=structuredClone(s.players.C!.followers);expect(s.distances.A!.B).toBe('near');if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values(s.groups!)[0]!;expect(g.technique).toMatchObject({school:'warrior',range:'near',useLevel:4,effectLevel:m.dedicated?5:4,damage:m.dedicated?7:5,attributes:['戦','剣'],destroyFollowerAttributes:['白'],target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(s.players.B!.damage).toBe(0);s=settle(s);expect(s.players.B!.damage).toBe(m.dedicated?7:5);expect(s.players.B!.followers).toEqual([]);expect(s.players.C!.followers).toEqual(cFollowers);expect(s.players.C!.damage).toBe(0);for(const id of [CARD,...m.followers])expect(s.discard.filter(c=>c===id)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);expect(s.phase).toBe('withdrawal');reject(s,'A',cmd(m.dedicated));});
it.each(['black-break-nonwhite','black-break-lower','black-break-front-white','black-break-back-white','black-break-wall-first'] as const)('%s actual nonwhite level HP and front order prevent board-wide white destruction',name=>{let s=makeBlackBreakPhysical(name,players);const m=blackBreakMode(name);if(m.followers.length===2)expect(s.players.B!.open).toContain('a2-p01-r2c1');s=settle(act(s,'A',cmd(true)));const blocked=['nonwhite','wall-first'].includes(m.suffix);expect(s.players.B!.damage).toBe(blocked?0:5);if(blocked){expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual(m.followers);expect(s.players.B!.followers[0]!.revealed).toBe(true);if(m.suffix==='wall-first')expect(s.players.B!.followers[1]!.revealed).toBe(false);}else{expect(s.players.B!.followers).toEqual([]);for(const id of m.followers)expect(s.discard).toContain(id);}expect(s.rolls?.length??0).toBe(0);});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior3 spirit6 actual shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeBlackBreakPhysical('black-break-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?5:0);expect(s.rolls).toHaveLength(1);});
it('actual elected Garwin with warrior0 spirit0 omits all four shortage checks but keeps near restriction',()=>{let s=makeBlackBreakPhysical('black-break-dedicated',players,{spirit:0});expect(gameStats(s,'A')).toMatchObject({warrior_level:0,spirit:0});s=settle(act(s,'A',cmd(true)));expect(s.players.B!.damage).toBe(7);expect(s.rolls?.length??0).toBe(0);});
it.each([false,true] as const)('actual far sword rejects unpaid then real approach admits selected mode dedicated=%s',dedicated=>{let s=makeBlackBreakPhysical('black-break-far',players,{warrior:4});reject(s,'A',cmd(dedicated));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(dedicated)));expect(s.players.B!.damage).toBe(dedicated?7:5);expect(s.players.B!.followers).toEqual([]);});
it.each(['black-break-maai','black-break-evade'] as const)('%s actual normal defense prevents white destruction and retains hidden follower',name=>{let s=makeBlackBreakPhysical(name,players);const followers=structuredClone(s.players.B!.followers);s=until(act(s,'A',cmd(true)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:false,evadeProhibited:false,counterProhibited:false});s=settle(act(s,'B',name==='black-break-maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toEqual(followers);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual Fate cancels the paid sword before white destruction without reopening use checks',()=>{let s=act(makeBlackBreakPhysical('black-break-fate',players),'A',cmd(true));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetActionId:id});s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(0);});
it('actual incoming Bow refuses both attack-only sword defense modes and leaves sword unpaid',()=>{let s=makeBlackBreakPhysical('black-break-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner malformed targets modes and foreign actor reject before payment',()=>{const s=makeBlackBreakPhysical('black-break-wrong-owner',players,{warrior:4});reject(s,'A',cmd(true));for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());reject(s,'A',{...cmd(),coSource:{cardInstanceId:'a2-p24-r1c3',dedicated:false}});expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(5);});
it('actual stopped recovery skips owner and declining the own action preserves the sword',()=>{let s=makeBlackBreakPhysical('black-break-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd(true));s=makeBlackBreakPhysical('black-break-decline',players,{beforeStart:true});reject(s,'A',cmd());s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
