import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,ready,until,finish,closeWindow,pass} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
function incoming(printed=false){let s=ready();character(s,'B','小妖精のチャム');character(s,'C','大神官ジル');character(s,'D','魔導王ガイナス');for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20,magic_level:20};s.players.B!.damage=gameStats(s,'B').endurance-1;const card=handCard(s,'A','地槍'),gift=handCard(s,'B','香具羅');handCard(s,'C','命運凶変');if(printed){handCard(s,'B',getAction('a2-p02-r3c3')!.name);handCard(s,'B','手裏剣');}s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'death-gift');return {s,gift};}
function give(s:GameState,gift:string){return act(s,'B',{type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:gift,targetId:'C'});}
it('Pending-death Cham gives one residual hand card before final disposal without a paid source or refill',()=>{let {s,gift}=incoming();const hand=[...s.players.B!.hand],recipient=[...s.players.C!.hand];s=closeWindow(give(s,gift));expect(s.players.B!.presence).toBe('pending-death');expect(s.players.B!.hand).toEqual(hand.filter(id=>id!==gift));expect(s.players.C!.hand).toEqual([...recipient,gift]);expect(s.resolution).not.toContain(gift);expect(s.outcome).toBeUndefined();s=finish(s);expect(s.players.B!.presence).toBe('dead');expect(s.players.C!.hand).toContain(gift);});
it('Cham projection provides her own finite choice only at the death decision',()=>{const {s,gift}=incoming();expect(viewFor(s,'B').legalChoices).toContain('CHAM_DEATH_GIFT');expect((viewFor(s,'B').lifecycleDecision as any).chamGift).toMatchObject({decisionId:s.windows!.at(-1)!.eventId,cardInstanceIds:expect.arrayContaining([gift]),eligibleTargetIds:['A','C','D']});for(const actor of ['A','C','D'])expect((viewFor(s,actor).lifecycleDecision as any).chamGift).toBeUndefined();});

function reject(s:GameState,actorId:string,command:unknown){const saved=JSON.stringify(s);expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);}
it('Cham decline leaves every residual card for actual ordinary death disposal',()=>{let {s,gift}=incoming();s=finish(s);expect(s.discard).toContain(gift);expect(s.events.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);});
it('Actual Fate cancellation leaves the selected card for disposal and prevents another attempt',()=>{let {s,gift}=incoming();s=give(s,gift);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='C')s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:viewFor(s,'C').reactionTargetAbilityId!});s=until(s,'death-gift');expect(s.players.B!.hand).toContain(gift);expect(viewFor(s,'B').legalChoices).not.toContain('CHAM_DEATH_GIFT');reject(s,'B',{type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:gift,targetId:'C'});s=finish(s);expect(s.discard).toContain(gift);expect(s.players.C!.hand).not.toContain(gift);});
it('Cham rejects foreign actor, foreign hand, resolution source, self target and expired decision',()=>{const {s,gift}=incoming(),c={type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:gift,targetId:'C'};for(const change of [{cardInstanceId:s.players.C!.hand[0]},{cardInstanceId:s.resolution[0]},{targetId:'B'},{decisionId:'death-old'}])reject(s,'B',{...c,...change});reject(s,'A',c);});
it('A moved Cham card cannot be chosen twice, and gift identity reaches only giver and recipient',()=>{let {s,gift}=incoming();s=closeWindow(give(s,gift));const c={type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:gift,targetId:'D'};reject(s,'B',c);for(const actor of ['A','D'])expect(JSON.stringify(viewFor(s,actor))).not.toContain(gift);for(const actor of ['B','C'])expect(viewFor(s,actor).privateLogs.some(e=>e.type==='CARD_GIFTED'&&e.cardInstanceId===gift)).toBe(true);});
it.each(['ability','printed'] as const)('Cham ability and printed death gift both execute with different cards (%s first)',first=>{let {s,gift}=incoming(true);const second=s.players.B!.hand.find(id=>getAction(id)!.name==='手裏剣')!,printed={type:'PLAY_DEATH_GIFT',cardInstanceId:'a2-p02-r3c3',giftCardInstanceId:second,targetId:'D'};if(first==='ability'){s=until(give(s,gift),'death-gift');expect(s.outcome).toBeUndefined();reject(s,'B',{...printed,giftCardInstanceId:gift});s=until(act(s,'B',printed),'death-gift');}else{s=until(act(s,'B',printed),'death-gift');expect(s.outcome).toBeUndefined();expect(s.discard).toContain('a2-p02-r3c3');expect(viewFor(s,'B').lifecycleDecision!.chamGift!.cardInstanceIds).not.toContain('a2-p02-r3c3');reject(s,'B',{type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:'a2-p02-r3c3',targetId:'C'});reject(s,'B',{type:'CHAM_DEATH_GIFT',decisionId:s.windows!.at(-1)!.eventId,cardInstanceId:second,targetId:'C'});s=until(give(s,gift),'death-gift');}expect(s.players.C!.hand).toContain(gift);expect(s.players.D!.hand).toContain(second);expect(s.players.B!.hand).not.toContain(gift);expect(s.players.B!.hand).not.toContain(second);s=finish(s);expect(s.discard).toContain('a2-p02-r3c3');expect(s.events.filter(e=>e.type==='CARD_GIFTED'&&e.audience==='public')).toHaveLength(2);});
it('Cham resolution revalidates the selected card and surviving recipient (structural invalidation)',()=>{for(const mode of ['card','recipient']){let {s,gift}=incoming();s=give(s,gift);if(mode==='card'){s.players.B!.hand=s.players.B!.hand.filter(id=>id!==gift);s.players.D!.hand.push(gift);}else{s=pass(s);s.players.C!.presence='otherworld';}s=finish(s);expect(s.players.C!.hand).not.toContain(gift);expect(s.events.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);}});
it('Cham excludes every member of the saved simultaneous death batch, including a structurally revived member',()=>{let {s,gift}=incoming();const task=s.lifecycle!.find(t=>t.kind==='death-batch')!;if(task.kind!=='death-batch')throw Error('NO_BATCH');task.actorIds.push('C');s.players.C!.presence='pending-death';expect(viewFor(s,'B').lifecycleDecision!.chamGift!.eligibleTargetIds).toEqual(['A','D']);s.players.C!.presence='active';reject(s,'B',{type:'CHAM_DEATH_GIFT',decisionId:task.id,cardInstanceId:gift,targetId:'C'});});
