import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,ready,finish,pass,until,closeWindow} from './combat-helpers.js';
import {character,handCard,entropy,freshGame} from './fixtures.js';
const ABSORB='c2-p06-r1c2-ab03',HUNGER='c2-p06-r2c2-ab04';
function source(name:string,spirit=8){let s=ready();character(s,'A',name);for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20,warrior_level:20};s.players.A!.damage=8;s.players.B!.permanent!.spirit=spirit-gameStats({...s,players:{...s.players,B:{...s.players.B!,permanent:{...s.players.B!.permanent,spirit:0}}}},'B').spirit;s.players.B!.damage=gameStats(s,'B').endurance-3;const card=handCard(s,'A',getAction('a2-p07-r3c3')!.name);handCard(s,'C','命運凶変');return act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});}
function opportunity(s:GameState,id:string,actor='A'){for(let n=0;n<300;n++){if(viewFor(s,actor).abilityOptions.some(o=>o.abilityId===id))return s;s=pass(s);}throw Error('REWARD_NOT_REACHED');}
function use(s:GameState,id:string,actor='A'){const o=viewFor(s,actor).abilityOptions.find(o=>o.abilityId===id)!;return act(s,actor,{type:'USE_ABILITY',abilityId:id,targetEventId:o.targetEventId});}
it('Dia absorbs actual body ten only up to remaining three',()=>{let s=opportunity(source('魔聖母ディア'),ABSORB);expect(s.players.A!.damage).toBe(8);s=finish(use(s,ABSORB));expect(s.players.A!.damage).toBe(5);expect(s.players.B!.presence).toBe('dead');});
it('Yotsurm chooses hunger only after actual spirit-eight victim death and grows once',()=>{let s=source('餓狼ヨーツルム');const stats=gameStats(s,'A');s=opportunity(s,HUNGER);expect(s.players.B!.presence).toBe('dead');s=finish(use(s,HUNGER));expect(s.players.A!.damage).toBe(0);expect(gameStats(s,'A')).toMatchObject({warrior_level:stats.warrior_level+2,magic_level:stats.magic_level+2});});

function absent(s:GameState,id:string,actor='A'){for(let n=0;n<400;n++){expect(viewFor(s,actor).abilityOptions.some(o=>o.abilityId===id)).toBe(false);if(!s.windows?.length)return s;s=pass(s);}throw Error('REWARD_ABSENCE_LIMIT');}
function priority(s:GameState,actor:string){for(let n=0;n<100;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('REWARD_PRIORITY');}
for(const [name,id] of [['魔聖母ディア',ABSORB],['餓狼ヨーツルム',HUNGER]]){
 it(`${name} decline leaves damage and growth unchanged`,()=>{const s=finish(opportunity(source(name!),id!));expect(s.players.A!.damage).toBe(8);expect(s.players.A!.combatRewardIds).toBeUndefined();});
 it(`${name} actual Fate cancellation consumes only the saved attempt`,()=>{let s=opportunity(source(name!),id!);const eventId=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id)!.targetEventId;s=priority(use(s,id!),'C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:viewFor(s,'C').reactionTargetAbilityId!});s=absent(s,id!);expect(s.players.A!.damage).toBe(8);expect(s.players.A!.combatRewardIds).toBeUndefined();expect(transition(s,{actorId:'A',command:{type:'USE_ABILITY',abilityId:id!,targetEventId:eventId}},entropy()).ok).toBe(false);});
 it(`${name} rejects a foreign actor and old opportunity without mutation`,()=>{const s=opportunity(source(name!),id!),before=JSON.stringify(s),eventId=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id)!.targetEventId;for(const [actorId,targetEventId] of [['B',eventId],['A','expired']])expect(transition(s,{actorId:actorId!,command:{type:'USE_ABILITY',abilityId:id!,targetEventId:targetEventId!}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);});
}
it('Spirit seven death never offers hunger',()=>{const s=absent(source('餓狼ヨーツルム',7),HUNGER);expect(s.players.B!.presence).toBe('dead');expect(s.players.A!.damage).toBe(8);});
it('Saved predeath spirit eight remains eligible after the victim value changes (snapshot boundary)',()=>{let s=opportunity(source('餓狼ヨーツルム'),HUNGER);s.players.B!.permanent!.spirit=-100;s=finish(use(s,HUNGER));expect(s.players.A!.combatRewardIds).toHaveLength(1);});
it('Dia caps recovery at her own maximum',()=>{let s=opportunity(source('魔聖母ディア'),ABSORB);s.players.A!.damage=1;s=finish(use(s,ABSORB));expect(s.players.A!.damage).toBe(0);});
it('Pure instant death offers no numeric absorption while the printed soul-drain rider still heals',()=>{let s=ready();character(s,'A','魔聖母ディア');s.players.A!.damage=5;const card=handCard(s,'A',getAction('a2-p15-r2c3')!.name);s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true}),'hit');s=until(closeWindow(s),'before-roll');s=closeWindow(s,[6,6]);s=closeWindow(s);s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'});s=absent(s,ABSORB);expect(s.players.B!.presence).toBe('dead');expect(s.players.A!.damage).toBe(0);expect(s.players.A!.combatRewardIds).toBeUndefined();});
it('Actual physical Ice Mirror credits numeric absorption to its reflecting Dia',()=>{let s=ready();character(s,'B','魔聖母ディア');for(const p of Object.values(s.players))p.permanent={endurance:100,magic_level:20,spirit:20};s.players.B!.damage=8;const attack=handCard(s,'A','地槍'),mirror=handCard(s,'B',getAction('a2-p12-r3c2')!.name);s=until(act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false}),'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false});s=opportunity(s,ABSORB,'B');const task=s.lifecycle!.find(t=>t.kind==='combat-reward'&&t.actorId==='B');expect(task).toMatchObject({targetId:'A',amount:6,sourceCardInstanceId:attack});s=finish(use(s,ABSORB,'B'));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([6,2]);});
it('Dia absorbs only nine body damage after the actual initial Soldier takes one',()=>{let s=freshGame();character(s,'A','魔聖母ディア');character(s,'B','黒騎士ガーウィン');for(const p of Object.values(s.players))p.permanent={spirit:20,warrior_level:20,endurance:100};s.players.A!.damage=10;const attack=handCard(s,'A',getAction('a2-p07-r3c3')!.name),soldier=handCard(s,'B','兵士');for(const actor of s.seatOrder){if(actor==='B')s=act(s,actor,{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:soldier});s=act(s,actor,{type:'PASS_SETUP'});}s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=opportunity(act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false}),ABSORB);s=finish(use(s,ABSORB));expect(s.players.A!.damage).toBe(1);expect(s.players.B!.damage).toBe(9);});

function nextOwn(s:GameState,owner='A'){for(let n=0;n<50;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(actor===owner)return s;s=act(s,actor,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error(`REWARD_TURN_${s.phase}`);}throw Error('REWARD_TURN_LIMIT');}
function combatSetup(name:string){const s=ready();character(s,'A',name);character(s,'C','魔導王ガイナス');character(s,'D','大神官ジル');for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20,warrior_level:20,magic_level:20};s.players.A!.damage=8;s.deck=[...s.deck.filter(id=>getAction(id)!.category!=='open'),...s.deck.filter(id=>getAction(id)!.category==='open')];return s;}
it.each([['魔聖母ディア','c2-p06-r1c2-ab03'],['餓狼ヨーツルム','c2-p06-r2c2-ab04']] as const)('%s %s actual chanted three-hit kill and later distinct kill reward once each',(name,id)=>{let s=combatSetup(name!);const card=handCard(s,'A','天地百撃斬'),second=handCard(s,'A','黒翼飛翔剣');for(const actor of ['B','C']){const p=s.players[actor]!;p.damage=gameStats(s,actor).endurance-3;p.permanent!.spirit=(p.permanent!.spirit??0)+8-gameStats(s,actor).spirit;}s=act(s,'A',{type:'CHANT',cardInstanceId:card});s=nextOwn(s);const before={...s.players.A!.permanent};s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'damage');s=closeWindow(s,[3]);s=opportunity(s,id!);s=finish(use(s,id!));s=nextOwn(s);s=opportunity(act(s,'A',{type:'ATTACK',cardInstanceId:second,targetIds:['C'],dedicated:false}),id!);s=finish(use(s,id!));expect(s.players.A!.combatRewardIds).toHaveLength(2);expect([s.players.B!.presence,s.players.C!.presence]).toEqual(['dead','dead']);expect(s.players.A!.damage).toBe(id===ABSORB?2:0);expect(s.players.A!.permanent!.warrior_level).toBe(before.warrior_level!+(id===HUNGER?4:0));expect(s.players.A!.permanent!.magic_level).toBe(before.magic_level!+(id===HUNGER?4:0));});
it.each(['魔聖母ディア','餓狼ヨーツルム'] as const)('%s actual chanted destruction kills its source simultaneously and grants no reward',name=>{let s=combatSetup(name);s.players.A!.damage=gameStats(s,'A').endurance-9;s.players.B!.damage=gameStats(s,'B').endurance-3;const card=handCard(s,'A',getAction('a2-p13-r2c3')!.name);s=act(s,'A',{type:'CHANT',cardInstanceId:card});s=nextOwn(s);s=absent(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),name==='魔聖母ディア'?ABSORB:HUNGER);expect([s.players.A!.presence,s.players.B!.presence]).toEqual(['dead','dead']);expect(s.players.A!.combatRewardIds).toBeUndefined();});
it('An actual kill by another actor grants no hunger to the observing Yotsurm',()=>{let s=combatSetup('侍大将のシン');character(s,'C','餓狼ヨーツルム');s.players.C!.damage=8;s.players.B!.damage=gameStats(s,'B').endurance-3;const card=handCard(s,'A','黒翼飛翔剣');s=absent(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),HUNGER,'C');expect(s.players.C!.damage).toBe(8);expect(s.players.C!.combatRewardIds).toBeUndefined();});
it('Predeath spirit seven cannot become eligible when death actually removes its until-death drain',()=>{let s=source('餓狼ヨーツルム',7);s.players.B!.statuses=[{id:'prior-drain',kind:'stat-drain',timing:'until-death',amount:1}];s.players.B!.permanent!.spirit=(s.players.B!.permanent!.spirit??0)+1;expect(gameStats(s,'B').spirit).toBe(7);s=absent(s,HUNGER);expect(s.players.B!.presence).toBe('dead');expect(gameStats(s,'B').spirit).toBe(8);expect(s.players.A!.combatRewardIds).toBeUndefined();});
it('Actual Ice Mirror makes surviving Yotsurm the killer of the original attacker',()=>{let s=combatSetup('侍大将のシン');character(s,'B','餓狼ヨーツルム');s.players.A!.damage=gameStats(s,'A').endurance-3;s.players.A!.permanent!.spirit=(s.players.A!.permanent!.spirit??0)+8-gameStats(s,'A').spirit;s.players.B!.damage=8;const attack=handCard(s,'A','地槍'),mirror=handCard(s,'B',getAction('a2-p12-r3c2')!.name);s=until(act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false}),'normal-defense');s=opportunity(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}),HUNGER,'B');expect(s.players.A!.presence).toBe('dead');s=finish(use(s,HUNGER,'B'));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.combatRewardIds).toHaveLength(1);});
it.each(['attack','counter','reflection'] as const)('Yotsurm hunger preserves actual %s killing source through death',mode=>{
 let s=combatSetup(mode==='attack'?'餓狼ヨーツルム':'侍大将のシン');
 const owner=mode==='attack'?'A':'B',victim=mode==='attack'?'B':'A';
 if(owner==='B')character(s,'B','餓狼ヨーツルム');
 s.players[owner]!.damage=8;s.players[victim]!.damage=gameStats(s,victim).endurance-3;
 s.players[victim]!.permanent!.spirit=(s.players[victim]!.permanent!.spirit??0)+8-gameStats(s,victim).spirit;
 const incoming=handCard(s,'A',mode==='reflection'?'地槍':'踏み込み／弓');
 const response=mode==='attack'?undefined:handCard(s,'B',getAction(mode==='counter'?'a2-p08-r2c3':'a2-p12-r3c2')!.name);
 const before=gameStats(s,owner);
 s=act(s,'A',{type:'ATTACK',cardInstanceId:incoming,targetIds:['B'],dedicated:false});
 if(response){s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:response,dedicated:false});}
 s=opportunity(s,HUNGER,owner);expect(s.players[victim]!.presence).toBe('dead');
 const reward=s.lifecycle!.find(t=>t.kind==='combat-reward'&&t.mode==='kill'&&t.actorId===owner)!;
 expect(reward).toMatchObject({actorId:owner,targetId:victim,targetSpirit:8,amount:3,sourceCardInstanceId:mode==='counter'?response:incoming});
 s=JSON.parse(JSON.stringify(s));s=finish(use(s,HUNGER,owner));
 expect(s.players[owner]!.combatRewardIds).toHaveLength(1);expect(s.players[owner]!.damage).toBe(0);
 expect(gameStats(s,owner)).toMatchObject({warrior_level:before.warrior_level+2,magic_level:before.magic_level+2});
});
