import {expect,it,describe} from 'vitest';
import {getAction} from '@madou/catalog';
import {allCardInstanceIds,transition,type GameState,viewFor,gameStats, discardIds } from '../src/index.js';
import {act,finish,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeR6CombinedDeathScenario} from './fixtures/r6-combined-death-scenario.js';
import {makeReclaimScenario} from './fixtures/reclaim-scenarios.js';
import {makeR6CombinedSuppressionScenario} from './fixtures/r6-combined-suppression-scenario.js';
import {makeR6Scenario} from './fixtures/r6-scenarios.js';

describe('combined chanted multi-hit death batch',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  it('R6 actual chanted two-target three-hit parry and Soldier HP settle B14 C18 in one simultaneous death batch',()=>{
   let s=makeR6CombinedDeathScenario(players),b=s.players.B!.damage,c=s.players.C!.damage;const counter=s.players.B!.hand.find(id=>getAction(id)!.name==='受け流し')!,soldier=s.players.C!.followers[0]!.cardInstanceId,group=Object.values(s.groups!)[0]!;const sword=s.actions![group.actionId]!.cardInstanceId;expect(group.hitIndices).toEqual([0,1,2]);expect(group.targets.map(t=>t.actorId)).toEqual(['B','C']);expect(s.outcome).toBeUndefined();
   s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});expect(Object.values(s.actions!).find(a=>a.kind==='defense')!.checks).toHaveLength(1);let sawParry=false,sawFollower=false;
   for(let n=0;n<400;n++){expect(s.outcome).toBeUndefined();if(s.players.B!.presence==='pending-death')break;const g=s.groups?.[group.id];if(g?.targets[0]!.hits[0]!.defended){sawParry=true;expect(g.targets[0]!.hits.map(h=>h.defended)).toEqual([true,false,false]);}if(g?.targets[1]!.followersSettled){sawFollower=true;expect(g.targets[1]!.hits.map(h=>h.damage)).toEqual([6,6,6]);expect(g.targets[1]!.followerDestroyed).toEqual([soldier]);}s=pass(s);}
   expect(sawParry).toBe(true);expect(sawFollower).toBe(true);expect(s.players.B).toMatchObject({presence:'pending-death',damage:b+14});expect(s.players.C).toMatchObject({presence:'pending-death',damage:c+18});expect(s.lifecycle!.find(t=>t.kind==='death-batch')).toMatchObject({actorIds:['B','C']});expect(s.events.filter(e=>e.type==='PLAYER_DIED')).toEqual([]);const before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=finish(JSON.parse(before) as GameState);expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['B','C']);expect(s.players.B!.presence).toBe('dead');expect(s.players.C!.presence).toBe('dead');expect(s.outcome).toBeUndefined();expect(s.windows).toEqual([]);expect(s.groups).toEqual({});expect(s.resolution).toEqual([]);expect(s.reclaimReservations).toEqual([]);for(const id of [counter,soldier,sword])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(allCardInstanceIds(s)).toHaveLength(220);expect(new Set(allCardInstanceIds(s)).size).toBe(220);
  });
});

describe('combined cancellation refill and ordinary recovery',()=>{
  it('R6 actual cancellation refills once then ordinary recovery reserves the same paid Fate until parent completion',()=>{
   let s=makeReclaimScenario('reclaim-owned',['A','B','C','D'].map(id=>({id,name:id})));const heal=s.players.A!.hand.find(id=>getAction(id)!.name==='封傷')!,fate='a2-p02-r2c3',hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;
   s=act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:heal,targetIds:['A'],dedicated:false});s=pass(s);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:viewFor(s,'B').reactionTargetActionId!});expect(s.players.B!.hand).toHaveLength(hand.length);const replacement=s.players.B!.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();expect(replacement).not.toBe(fate);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);s=until(s,'reclaim');const d=viewFor(s,'B').reclaim!,take={type:'CHOOSE_RECLAIM' as const,decisionId:d.decisionId,choice:'take' as const,claimId:d.claims[0]!.claimId};s=act(s,'B',take);expect(s.reclaimReservations).toContain(fate);expect(s.resolution).not.toContain(fate);expect(s.deck).not.toContain(fate);expect(discardIds(s)).not.toContain(fate);for(const p of Object.values(s.players))expect(p.hand).not.toContain(fate);const saved=JSON.stringify(s);expect(transition(s,{actorId:'B',command:take},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);s=finish(JSON.parse(saved));expect(s.players.B!.hand.filter(id=>id===fate)).toHaveLength(1);expect(s.players.B!.hand).toContain(replacement);expect(s.players.B!.hand).toHaveLength(hand.length+1);expect(s.players.A!.damage).toBe(2);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.reclaimReservations).toEqual([]);expect(s.players.B!.reclaimUsage?.['命運凶変']?.baseSpent).toBe(true);
  });
});

describe('combined freeze, ban and revival',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<400;n++){if(done(s))return s;s=pass(s);}throw Error('COMBINED_SUPPRESSION_TEST_WINDOW');}
  function nextOwn(s:GameState,owner:string){for(let n=0;n<60;n++){const id=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(id===owner)return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!=='a2-p13-r3c1').slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))}));else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error(`COMBINED_SUPPRESSION_TEST_TURN_${s.phase}`);}throw Error('COMBINED_SUPPRESSION_TEST_TURN_LIMIT');}
  it('R6 actual Spirit freezes6 then Vanmil ban persists through actual death revival and rejects the new-life modifier without changing the old frozen value',()=>{
   let s=makeR6CombinedSuppressionScenario(players);const id=Object.keys(s.actions!)[0]!,life=s.players.A!.lifeId,spirit=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p01-r2c1-ab03')!;s=act(s,'A',{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:spirit.targetEventId});s=until(s,s=>s.windows?.at(-1)?.kind==='damage'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');expect(s.actions![id]!.technique.effectLevel).toBe(6);expect(s.actions![id]!.modifiers!.effectFrozen).toBe(true);const ban=viewFor(s,'C').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=act(s,'C',{type:'USE_ABILITY',abilityId:ban.abilityId,targetEventId:ban.targetEventId,targetIds:['A']});s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values(s.groups!)[0]!.technique.effectLevel).toBe(6);const designation=structuredClone(s.suppressionDesignations);s=finish(s);expect(s.players.B!.damage).toBe(7);s=nextOwn(s,'B');const lethal=s.players.B!.hand.find(id=>getAction(id)!.name==='踏み込み／弓')!;s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:lethal,targetIds:['A'],dedicated:false}));expect(s.players.A!.presence).toBe('dead');expect(s.outcome).toBeUndefined();s=nextOwn(s,'D');s=until(act(s,'D',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['A'],dedicated:true}),s=>s.windows?.at(-1)?.kind==='re-setup');expect(s.players.A!.presence).toBe('active');expect(s.players.A!.damage).toBe(0);expect(s.players.A!.lifeId).not.toBe(life);expect(s.suppressionDesignations).toEqual(designation);s=finish(act(s,'A',{type:'PASS_SETUP'}));s=nextOwn(s,'A');const next=s.players.A!.hand.find(id=>getAction(id)!.name==='手裏剣')!;expect(next).toBeDefined();s=until(act(s,'A',{type:'ATTACK',cardInstanceId:next,targetIds:['C'],dedicated:false}),s=>s.windows?.at(-1)?.kind==='effect-level');expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===spirit.abilityId)).toBe(false);const before=JSON.stringify(s),action=Object.values(s.actions!).find(a=>a.kind==='attack')!;expect(transition(s,{actorId:'A',command:{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:action.eventId}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values(s.groups!)[0]!.technique.effectLevel).toBe(4);s=finish(s);expect(s.players.B!.damage).toBe(7);expect(s.players.C!.damage).toBe(5);expect(s.suppressionDesignations).toEqual(designation);
  });
  it('R6 browser revived prefix follows the same actual death and revival commands',()=>{const s=makeR6CombinedSuppressionScenario(players,true);expect(s.players.A!.damage).toBe(0);expect(s.events.filter(e=>e.type==='PLAYER_DIED'&&e.actorId==='A')).toHaveLength(1);expect(s.suppressionDesignations!.map(x=>x.targetId)).toEqual(['A']);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId==='c2-p01-r2c1-ab03')).toBe(false);});
});

describe('recorded matches S20 to S27',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  function nextStart(s:GameState){for(let n=0;n<50;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'){if(actor==='B')return s;s=act(s,actor,{type:'START_TURN'});}else if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error('S20_TURN');}throw Error('S20_TURN_LIMIT');}
  it('S20 physical ordinary poem advances the same stop from initial minus3 failure through minus2 failure and minus1 success with refill and normal draw',()=>{let s=makeR6Scenario('r6-s20-hit',players);expect(s.players.B!.hand).toHaveLength(4);expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-resistance',modifier:-3,faces:[]});s=finish(closeWindow(closeWindow(s,[3,4])));expect(s.players.B!.damage).toBe(5);const id=s.players.B!.statuses![0]!.id;expect(s.players.B!.statuses![0]).toMatchObject({sourceCardInstanceId:'a2-p17-r1c1',modifiers:[-3,-2,-1],nextCheck:1});s=nextStart(s);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:-2,faces:[]});s=finish(closeWindow(closeWindow(JSON.parse(JSON.stringify(s)),[3,4])));expect(s.players.B!.statuses![0]).toMatchObject({id,nextCheck:2});expect(s.players.B!.hand).toHaveLength(4);expect(s.turnSeat).toBe(2);s=nextStart(s);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:-1,faces:[]});const draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;s=finish(closeWindow(closeWindow(JSON.parse(JSON.stringify(s)),[2,3])));expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.hand).toHaveLength(5);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.phase).toBe('draw');s=act(s,'B',{type:'CHOOSE_DRAW',draw:true});expect(s.players.B!.hand).toHaveLength(6);expect(s.phase).toBe('action');s=act(s,'B',{type:'PASS_ACTION'});s=finish(act(s,'B',{type:'END_TURN',discardIds:[s.players.B!.hand[0]!]}));expect(s.turnSeat).toBe(2);expect(s.rolls!.filter(r=>r.purpose==='status-resistance'||r.purpose==='status-recovery').map(r=>({modifier:r.modifier,success:r.success}))).toEqual([{modifier:-3,success:false},{modifier:-2,success:false},{modifier:-1,success:true}]);});
  // S21 secrecy ends at mandatory G15 hit publication, as the current R6 plan requires.
  it('S21 actual White Light5 damage6 keeps unused Shelim ability private until mandatory G15 hit publication',()=>{let s=makeR6Scenario('r6-s21',players);expect(viewFor(s,'B').abilityOptions.some(o=>o.abilityId==='c2-p01-r1c1-ab01')).toBe(true);expect(viewFor(s,'B').currentAttack!.technique).toMatchObject({effectLevel:5,damage:6});const privateCheck=()=>{for(const id of ['A','C','D']){expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1');expect(viewFor(s,id).abilityOptions.some(o=>o.abilityId==='c2-p01-r1c1-ab01')).toBe(false);}};privateCheck();s=pass(JSON.parse(JSON.stringify(s)));privateCheck();expect(s.players.B!.revealed).toBe(false);s=finish(s);expect(s.players.B!.revealed).toBe(true);for(const id of ['A','C','D']){expect(viewFor(s,id).logs.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='B'&&e.characterId==='c2-p01-r1c1')).toBe(true);expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1-ab01');}expect(s.players.B!.damage).toBe(6);expect(s.phase).toBe('withdrawal');});

  it('S22 two OPEN share one actual reaction refill and resume the original parent generation after saved FuSen choice',()=>{let s=makeR6Scenario('r6-s22',players);expect(s.players.D!.presence).toBe('dead');expect(s.events.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='D')).toBe(true);const parent=structuredClone(s.windows!.at(-1)!),hand=s.players.C!.hand.length,draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C').length;expect(s.deck.slice(0,2)).toEqual(['a2-p01-r1c1','a2-p01-r1c2']);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.continuation.id});expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(s.players.C!.hand).toHaveLength(hand-1);expect(s.players.C!.open).toContain('a2-p01-r1c1');expect(s.players.C!.open).not.toContain('a2-p01-r1c2');expect(s.resolution).toEqual(expect.arrayContaining(['a2-p02-r2c3','a2-p08-r1c1']));s=closeWindow(s,[4]);s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('revival');expect(s.players.C!.hand).toHaveLength(hand-1);s=act(JSON.parse(JSON.stringify(s)),'D',{type:'CHOOSE_REVIVAL',revive:false});expect(s.players.C!.open).toEqual(expect.arrayContaining(['a2-p01-r1c1','a2-p01-r1c2']));expect(s.players.C!.hand).toHaveLength(hand);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C')).toHaveLength(draws+1);expect(s.players.D!.presence).toBe('dead');expect(s.deck).not.toContain('a2-p02-r2c3');expect(s.deck).not.toContain('a2-p08-r1c1');expect(s.windows!.at(-1)!.kind).toBe('declaration');expect(s.windows!.some(w=>w.id===parent.id)).toBe(true);for(let n=0;n<150&&s.windows!.at(-1)!.id!==parent.id;n++)s=pass(s);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);s=finish(JSON.parse(JSON.stringify(s)));expect(s.players.C!.damage).toBe(0);expect(discardIds(s).filter(id=>id==='a2-p02-r2c3')).toHaveLength(1);expect(discardIds(s).filter(id=>id==='a2-p08-r1c1')).toHaveLength(1);expect(s.resolution).toEqual([]);expect(s.phase).toBe('withdrawal');});

  it('S23 natural exhaustion draws 1 plus 2 discard with the real secret book still in resolution and deterministic replay',()=>{let s=makeR6Scenario('r6-s23',players);const first=s.deck[0]!,discards=[...discardIds(s)],hand=[...s.players.A!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='A').length;expect(s.deck).toHaveLength(1);expect(discards).toHaveLength(2);expect(s.resolution).toEqual(['a2-p03-r1c1']);expect(s.rolls!.at(-1)).toMatchObject({purpose:'extra-draw',faces:[3]});s=closeWindow(JSON.parse(JSON.stringify(s)));expect(s.windows!.at(-1)!.kind).toBe('reclaim');expect(s.players.A!.hand.slice(hand.length)).toEqual([first,discards[1],discards[0]]);expect(s.deck).toEqual([]);expect(discardIds(s)).toEqual([]);expect(s.resolution).toEqual(['a2-p03-r1c1']);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='A')).toHaveLength(draws+3);expect(s.players.A!.hand).not.toContain('a2-p03-r1c1');s=finish(s);expect(discardIds(s)).toEqual(['a2-p03-r1c1']);expect(s.resolution).toEqual([]);expect(s.phase).toBe('action');expect(s.lifecycle??[]).toEqual([]);s=act(s,'A',{type:'PASS_ACTION'});expect(s.phase).toBe('hand-adjustment');});

  it('S27 actual final two-person chanted destruction commits both deaths before the final all-dead draw',()=>{let s=makeR6Scenario('r6-s27',players);expect(s.players.C!.presence).toBe('dead');expect(s.players.D!.presence).toBe('dead');expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['C','D']);expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain('a2-p13-r2c3');expect(s.outcome).toBeUndefined();const a=s.players.A!.damage,b=s.players.B!.damage;s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p13-r2c3',targetIds:['B'],dedicated:false});for(let n=0;n<300&&s.windows?.at(-1)?.kind!=='death-gift';n++){expect(s.outcome).toBeUndefined();s=pass(s);}expect(s.players.A).toMatchObject({presence:'pending-death',damage:a+10});expect(s.players.B).toMatchObject({presence:'pending-death',damage:b+20});const batch=s.lifecycle!.find(t=>t.kind==='death-batch')!;expect(batch).toMatchObject({actorIds:['A','B']});expect(s.outcome).toBeUndefined();s=JSON.parse(JSON.stringify(s));for(let n=0;n<100&&s.players.A!.presence!=='dead';n++)s=pass(s);expect(s.players.A!.presence).toBe('dead');expect(s.players.B!.presence).toBe('pending-death');expect(s.outcome).toBeUndefined();for(const id of ['A','B','C','D'])expect(viewFor(s,id).outcome).toBeNull();s=finish(s);expect(Object.values(s.players).every(p=>p.presence==='dead')).toBe(true);expect(s.outcome).toMatchObject({kind:'draw',reason:'mutual-extinction',winnerIds:[],results:{A:'draw',B:'draw',C:'draw',D:'draw'}});expect(s.resolution).toEqual([]);expect(s.reclaimReservations).toEqual([]);expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['C','D','A','B']);expect(s.events.filter(e=>e.type==='GAME_COMPLETED')).toHaveLength(1);expect(discardIds(s).filter(id=>id==='a2-p13-r2c3')).toHaveLength(1);});

  it('S21 alternate hidden character has identical foreign projections and pass order until the actual hit reveals identity',()=>{
   let s=makeR6Scenario('r6-s21',players),control=makeR6Scenario('r6-s21-control',players);
   for(let n=0;n<300;n++){
    expect(s.players.B!.revealed).toBe(control.players.B!.revealed);
    if(s.players.B!.revealed)break;
    for(const id of ['A','C','D'])expect(viewFor(s,id)).toEqual(viewFor(control,id));
    expect(s.windows!.at(-1)).toEqual(control.windows!.at(-1));
    s=pass(s);control=pass(control);
   }
   expect(s.players.B!.revealed).toBe(true);expect(control.players.B!.revealed).toBe(true);
   s=finish(s);control=finish(control);
   expect(s.players.B!.damage).toBe(6);expect(control.players.B!.damage).toBe(6);
   for(const id of ['A','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1-ab01');
  });
});
