import {expect,it} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSharedReclaimScenario} from './fixtures/shared-reclaim-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),COURAGE='a2-p01-r3c3';
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
it.each(['a09','a31'] as const)('Shared %s hidden claimant and absent claimant keep every explicit public response identical',kind=>{let a=makeSharedReclaimScenario(kind==='a09'?'shared-a09-hidden':'shared-a31-hidden',players),b=makeSharedReclaimScenario(kind==='a09'?'shared-a09-none':'shared-a31-none',players);let slots=0;for(let n=0;n<300;n++){for(const actor of ['A','C','D'])expect(viewFor(a,actor)).toEqual(viewFor(b,actor));expect(a.revision).toBe(b.revision);expect(a.nextEventId).toBe(b.nextEventId);const w=a.windows?.at(-1);if(!w)break;if(w.kind==='reclaim')slots++;if(w.kind==='reclaim'&&w.participants[w.cursor]==='B'){expect(viewFor(a,'B').reclaim!.claims).toEqual([]);expect(viewFor(b,'B').reclaim!.claims).toEqual([]);}a=pass(JSON.parse(JSON.stringify(a)));b=pass(JSON.parse(JSON.stringify(b)));}expect(slots).toBeGreaterThanOrEqual(4);for(const actor of ['A','C','D'])expect(viewFor(a,actor)).toEqual(viewFor(b,actor));});
it.each(['take','beneficiary-decline','checker-decline','failed-check'] as const)('Shared A09 distinct checker B and beneficiary A: %s',choice=>{let s=makeSharedReclaimScenario(choice==='failed-check'?'shared-a09-fail':'shared-a09-hidden',players);s=pass(s);expect(viewFor(s,'B').reclaim!.pendingActorId).toBe('B');const window=structuredClone(s.windows!.at(-1));s=act(s,'B',{type:'REVEAL_CHARACTER'});expect(s.windows!.at(-1)).toEqual(window);let d=viewFor(s,'B').reclaim!;const printed=d.claims.find(c=>c.right==='printed')!;reject(s,'B',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:printed.claimId});if(choice==='checker-decline')s=finish(pass(s));else{s=act(s,'B',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:printed.claimId});expect(s.rolls!.at(-1)).toMatchObject({rollerId:'B',formula:'2d6',modifier:0,resume:{kind:'reclaim-check',decisionId:d.decisionId}});const rollCount=s.rolls!.length;reject(s,'B',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:printed.claimId});expect(s.rolls).toHaveLength(rollCount);s=until(s,'reclaim');if(choice==='failed-check'){expect(s.reclaimDecisions!.find(t=>t.id===d.decisionId)!.checkAttempted).toBe(true);expect(viewFor(s,'A').reclaim!.stage).not.toBe('beneficiary-choice');s=finish(s);}else{d=viewFor(s,'A').reclaim!;expect(d).toMatchObject({stage:'beneficiary-choice',pendingActorId:'A'});const claim=d.claims[0]!;reject(s,'B',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:claim.claimId});reject(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:claim.claimId});reject(s,'B',{type:'PASS'});if(choice==='take'){s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:claim.claimId});expect(s.reclaimReservations).toContain(COURAGE);expect(s.resolution).not.toContain(COURAGE);expect(s.players.A!.hand).not.toContain(COURAGE);}s=finish(s);}}expect(s.players.A!.hand.filter(id=>id===COURAGE)).toHaveLength(choice==='take'?1:0);expect(s.players.B!.hand).not.toContain(COURAGE);expect(s.discard.includes(COURAGE)).toBe(choice!=='take');for(const actor of ['A','B'])expect(s.players[actor]!.reclaimUsage?.['勇気']).toBeUndefined();});
it('Shared ordinary source preserves public transcripts for zero base extra and combined private budgets',()=>{let worlds=(['shared-budget-none','shared-budget-base','shared-budget-extra','shared-budget-both'] as const).map(name=>makeSharedReclaimScenario(name,players));expect(worlds.map(s=>viewFor(s,'A').reclaim!.claims.map(c=>c.right))).toEqual([[],['base'],['extra'],['base','extra']]);let passes=0;for(let n=0;n<300;n++){for(const other of worlds.slice(1)){for(const actor of ['B','C','D'])expect(viewFor(other,actor)).toEqual(viewFor(worlds[0]!,actor));expect(other.nextEventId).toBe(worlds[0]!.nextEventId);}const w=worlds[0]!.windows?.at(-1);if(!w)break;if(w.kind==='reclaim')passes++;worlds=worlds.map(s=>pass(JSON.parse(JSON.stringify(s))));}expect(passes).toBe(4);for(const s of worlds){expect(s.phase).toBe('withdrawal');expect(s.reclaimReservations).toEqual([]);}});
