import {expect,it} from 'vitest';
import {getCharacter} from '@madou/catalog';
import {gameStats,viewFor,transition,type GameState, discardIds } from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeConversionPhysicalScenario,conversionMode,type ConversionPhysicalScenario} from './fixtures/conversion-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1,1]){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s,dice);}throw Error('CONVERSION_LIMIT');}
function settle(s:GameState,dice=[1,1]){return until(s,s=>!s.windows?.length,dice);}
function command(name:ConversionPhysicalScenario){return {type:'PLAY_TURN_CARD',cardInstanceId:conversionMode(name).card,targetId:'B',mode:'ordinary'} as const;}
function profile(s:GameState){const p=viewFor(s,'B').self;return {faction:p.faction,objective:p.objective,currentObjective:p.currentObjective,protection:p.protection,defeatCondition:p.defeatCondition};}
function replaced(s:GameState,name:ConversionPhysicalScenario){const m=conversionMode(name);expect(profile(s)).toEqual({faction:m.faction,objective:(m.good?'EVIL':'GOOD')+'の全滅',currentObjective:{kind:'extinction',enemyFactions:[m.good?'EVIL':'GOOD']},protection:{characterIds:[m.protector]},defeatCondition:getCharacter(m.protector)!.name+'の死亡'});}
function reject(s:GameState,id:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each([
 ['conversion-good-fail',[3,3],5,false],['conversion-evil-fail',[3,3],5,false],['conversion-good-success',[2,3],5,true],['conversion-evil-success',[2,3],5,true],['conversion-good-success',[1,1],5,true],['conversion-evil-success',[1,1],5,true],['conversion-good-dedicated',[2,2],4,true],['conversion-evil-dedicated',[2,2],4,true],['conversion-good-dedicated',[2,3],4,false],['conversion-evil-dedicated',[2,3],4,false],['conversion-good-asfelt',[3,4],7,true],['conversion-evil-asfelt',[3,4],7,true],['conversion-good-asfelt',[4,4],7,false],['conversion-evil-asfelt',[4,4],7,false],['conversion-good-garwin',[3,4],7,true],['conversion-evil-garwin',[3,4],7,true],['conversion-good-garwin',[4,4],7,false],['conversion-evil-garwin',[4,4],7,false],['conversion-good-same',[6,6],5,false],['conversion-evil-same',[6,6],7,false],['conversion-good-fixed',[6,6],5,false],['conversion-evil-fixed',[6,6],5,false]
] as const)('%s actual target 2d6 %s freezes spirit threshold %s with resistance success %s and atomic allegiance replacement',(name,faces,threshold,success)=>{let s=makeConversionPhysicalScenario(name,players);const m=conversionMode(name),before=profile(s),target=structuredClone(s.players.B!),hand=[...s.players.A!.hand],deck=[...s.deck];expect(s.players.B!.revealed).toBe(true);expect(gameStats(s,'B').spirit).toBe(6);expect(viewFor(s,'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===m.card)!.targetIds).toContain('B');s=act(s,'A',command(name));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==m.card));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(m.card);expect(profile(s)).toEqual(before);s=until(s,s=>s.rolls?.at(-1)?.purpose==='faction-change');const id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)).toMatchObject({rollerId:'B',kind:'check',formula:'2d6',stage:'before-roll'});s=until(s,s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll',[...faces]);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({threshold,total:faces[0]+faces[1],faces:[...faces],success});for(const actor of s.seatOrder)expect(viewFor(s,actor).currentRoll!.threshold).toBe(threshold);expect(profile(s)).toEqual(before);s=settle(s);if(success||m.fixed)expect(profile(s)).toEqual(before);else replaced(s,name);expect(s.events.filter(e=>e.type==='FACTION_CHANGED'&&e.actorId==='B')).toHaveLength(success||m.fixed?0:1);for(const key of ['characterId','hand','open','attachments','followers','chants','damage','permanent'] as const)expect(s.players.B![key]).toEqual(target[key]);expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);expect(s.resolution).toEqual([]);expect(s.phase).toBe('hand-adjustment');reject(s,'A',command(name));});
it.each(['conversion-good-hidden','conversion-evil-hidden'] as const)('%s actual hidden target excluded until own public reveal while self other-seat timing and duplicate commands preserve every view',name=>{let s=makeConversionPhysicalScenario(name,players,{beforeStart:true});reject(s,'A',command(name));s=act(s,'A',{type:'START_TURN'});reject(s,'A',command(name));s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});expect(viewFor(s,'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===conversionMode(name).card)).toBeUndefined();reject(s,'A',command(name));reject(s,'A',{...command(name),targetId:'A'});s=settle(act(s,'B',{type:'REVEAL_CHARACTER'}));expect(viewFor(s,'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===conversionMode(name).card)!.targetIds).toEqual(['B']);reject(s,'B',command(name));reject(s,'A',{...command(name),targetId:'C'});reject(s,'A',{...command(name),mode:'astrology'});s=act(s,'A',command(name));reject(s,'A',command(name));s=settle(s,[6,6]);replaced(s,name);});
it.each(['conversion-good-fate','conversion-evil-fate'] as const)('%s actual Fate cancels paid physical conversion before target roll and preserves all allegiance fields',name=>{let s=makeConversionPhysicalScenario(name,players);const before=profile(s),m=conversionMode(name);s=act(s,'A',command(name));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(profile(s)).toEqual(before);expect(discardIds(s)).toContain(m.card);expect(s.rolls?.some(r=>r.purpose==='faction-change')??false).toBe(false);expect(s.phase).toBe('hand-adjustment');});
it.each(['conversion-good-forced','conversion-evil-forced','conversion-good-reroll','conversion-evil-reroll'] as const)('%s actual forced failure survives successful God reroll while ordinary reroll restores resistance and preserves allegiance',name=>{let s=makeConversionPhysicalScenario(name,players);const before=profile(s),forced=name.endsWith('-forced');s=act(s,'A',command(name));s=until(s,s=>s.rolls?.at(-1)?.purpose==='faction-change');const id=s.rolls!.at(-1)!.id;s=until(s,s=>s.rolls!.find(r=>r.id===id)!.stage==='after-roll',forced?[1,1]:[6,6]);s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');if(forced){s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});s=until(s,s=>s.windows?.at(-1)?.continuation.id===id&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');}s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=settle(s,[1,1]);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({generation:1,total:2,threshold:5,forcedFailure:forced,success:!forced});if(forced)replaced(s,name);else expect(profile(s)).toEqual(before);});
it.each(['conversion-good-decline','conversion-evil-decline'] as const)('%s actual decline preserves physical source and target allegiance',name=>{let s=makeConversionPhysicalScenario(name,players);const before=profile(s);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(conversionMode(name).card);expect(profile(s)).toEqual(before);});

it.each(['conversion-evil-protector-dead'] as const)('%s actual all-EVIL hidden deal remains live after prior lethal Bow then failed Charm immediately wanders and returns target cards',name=>{let s=makeConversionPhysicalScenario(name,players);const m=conversionMode(name),returned=[...s.players.B!.hand,...s.players.B!.followers.map(f=>f.cardInstanceId)];expect(s.initialFactions).toEqual(['EVIL','EVIL','EVIL','EVIL']);expect(s.outcome).toBeUndefined();expect(s.players.C!.presence).toBe('dead');expect(s.players.B!.presence??'active').toBe('active');expect(s.players.B!.followers).toHaveLength(1);expect(viewFor(s,'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===m.card)!.targetIds).toEqual(['B']);reject(s,'A',{...command(name),targetId:'C'});s=settle(act(s,'A',command(name)),[6,6]);replaced(s,name);expect(s.players.B!.presence).toBe('wandering');expect(s.players.B!.hand).toEqual([]);expect(s.players.B!.followers).toEqual([]);for(const id of returned)expect(s.deck).toContain(id);expect(s.events.findIndex(e=>e.type==='FACTION_CHANGED'&&e.actorId==='B')).toBeLessThan(s.events.findIndex(e=>e.type==='PLAYER_WANDERING'&&e.actorId==='B'));expect(discardIds(s)).toContain(m.card);expect(s.outcome).toBeUndefined();});
