import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState, discardIds } from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeCouragePhysicalScenario,courageMode,type CouragePhysicalScenario} from './fixtures/courage-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p01-r3c3';
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1,2]){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('COURAGE_WINDOW');}
function at(s:GameState,kind:string){return until(s,s=>s.windows?.at(-1)?.kind===kind);}
function priority(s:GameState,id:string){return until(s,s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]===id;});}
function settle(s:GameState,dice=[1,2]){return until(s,s=>!s.windows?.length,dice);}
function use(s:GameState,name:CouragePhysicalScenario){const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===courageMode(name).abilityId)!;expect(o).toBeDefined();return act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});}
function start(name:CouragePhysicalScenario,checkerSpirit?:number){let s=makeCouragePhysicalScenario(name,players,checkerSpirit===undefined?{}:{checkerSpirit});return use(at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false}),'normal-defense'),name);}
function option(s:GameState,id='D'){return viewFor(s,id).anytimeCardOptions.find(o=>o.cardInstanceId===card);}
function play(s:GameState,id='D'){s=until(s,s=>!!option(s,id));return act(s,id,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:option(s,id)!.targetEventId});}
function checker(s:GameState){return until(s,s=>viewFor(s,'C').reclaim?.cardInstanceId===card&&viewFor(s,'C').reclaim?.pendingActorId==='C');}
function request(s:GameState){const d=viewFor(s,'C').reclaim!;return act(s,'C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:d.claims.find(c=>c.action==='request-check')!.claimId});}
function beneficiary(s:GameState,id='D',dice=[1,2]){return until(s,s=>viewFor(s,id).reclaim?.stage==='beneficiary-choice',dice);}
function take(s:GameState,id='D'){const d=viewFor(s,id).reclaim!;return act(s,id,{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims[0]!.claimId});}
function nextA(s:GameState){for(let n=0;n<300;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('COURAGE_TURN_PHASE');}throw Error('COURAGE_TURN');}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['courage-dia','courage-fear','courage-same'] as const)('%s actual GOOD user cancels named ability and consenting public Lester reserves the card for its original user only',name=>{const owner=name==='courage-same'?'C':'D';let s=priority(start(name),owner);const event=option(s,owner)!.targetEventId,hand=s.players[owner]!.hand.length;reject(s,owner,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:'stale'});reject(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});s=play(s,owner);expect(s.players[owner]!.hand).toHaveLength(hand);s=checker(s);expect(s.abilities![event]!.canceled).toBe(true);expect(s.rolls?.filter(r=>r.purpose==='ability-check')??[]).toEqual([]);const d=viewFor(s,'C').reclaim!,claim=d.claims.find(c=>c.action==='request-check')!;expect(claim.action).toBe('request-check');reject(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:claim.claimId});reject(s,'C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:claim.claimId});s=request(s);expect(s.rolls!.at(-1)).toMatchObject({rollerId:'C',formula:'2d6',modifier:0,resume:{kind:'reclaim-check',decisionId:d.decisionId}});reject(s,'C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'request-check',claimId:claim.claimId});s=beneficiary(s,owner);expect(viewFor(s,owner).reclaim!.pendingActorId).toBe(owner);if(owner!=='C')expect(viewFor(s,'C').reclaim!.claims).toEqual([]);s=take(s,owner);expect(s.reclaimReservations).toContain(card);expect(s.players[owner]!.hand).not.toContain(card);expect(discardIds(s)).not.toContain(card);s=settle(s);expect(s.players[owner]!.hand).toHaveLength(hand+1);expect(s.players[owner]!.hand.filter(id=>id===card)).toHaveLength(1);if(owner!=='C')expect(s.players.C!.hand).not.toContain(card);expect(s.players.B!.damage).toBe(4);expect(s.reclaimReservations).not.toContain(card);expect(s.players[owner]!.reclaimUsage?.['勇気']).toBeUndefined();});
it.each(['courage-hidden','courage-check-decline','courage-stopped'] as const)('%s real unavailable or declining checker creates no roll and leaves the canceled ability canceled',name=>{let s=checker(play(start(name)));const prior=structuredClone(s.players.C!.statuses??[]),d=viewFor(s,'C').reclaim!;if(name!=='courage-check-decline')expect(d.claims).toEqual([]);s=act(s,'C',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'decline'});s=settle(s);expect(s.rolls?.filter(r=>r.resume.kind==='reclaim-check')??[]).toEqual([]);expect(s.players.C!.statuses??[]).toEqual(prior);expect(s.players.D!.hand).not.toContain(card);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);expect(s.players.B!.damage).toBe(4);});
it('actual hidden Lester can reveal in the unchanged check window and then consent to the original users return',()=>{let s=checker(play(start('courage-reveal')));expect(viewFor(s,'C').reclaim!.claims).toEqual([]);const window=structuredClone(s.windows!.at(-1));s=act(s,'C',{type:'REVEAL_CHARACTER'});expect(s.windows!.at(-1)).toEqual(window);s=settle(take(beneficiary(request(s))));expect(s.players.C!.revealed).toBe(true);expect(s.players.D!.hand).toContain(card);expect(s.players.C!.hand).not.toContain(card);});
it('actual successful Lester check does not force the beneficiary to reclaim',()=>{let s=beneficiary(request(checker(play(start('courage-user-decline')))));const d=viewFor(s,'D').reclaim!;s=settle(act(s,'D',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'decline'}));expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);expect(s.players.D!.hand).not.toContain(card);expect(s.reclaimReservations).not.toContain(card);expect(s.rolls!.filter(r=>r.resume.kind==='reclaim-check')).toHaveLength(1);});
it.each([[3,3,true],[3,4,false]] as const)('actual Lester spirit6 check faces %s %s returns iff success=%s',(first,second,success)=>{let s=request(checker(play(start('courage-dia',6))));s=until(s,s=>s.rolls?.some(r=>r.resume.kind==='reclaim-check'&&r.stage==='applied')===true,[first,second]);expect(s.rolls!.find(r=>r.resume.kind==='reclaim-check')!.success).toBe(success);if(success)s=take(s);s=settle(s);expect(s.players.D!.hand.includes(card)).toBe(success);expect(discardIds(s).includes(card)).toBe(!success);expect(s.rolls!.filter(r=>r.resume.kind==='reclaim-check')).toHaveLength(1);});
it.each(['courage-evil','courage-poem'] as const)('%s real faction or named ability exclusion offers no Courage and declining spends nothing',name=>{let s=priority(start(name),'D');expect(option(s)).toBeUndefined();const event=Object.values(s.abilities!)[0]!.id;reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});s=settle(s);expect(s.players.D!.hand).toContain(card);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.reclaimDecisions?.some(d=>d.source.kind==='courage-resolution')).not.toBe(true);});
it('actual Fate canceled Courage keeps payment and refill but has no printed return check',()=>{let s=play(start('courage-canceled'));const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=priority(s,'A');s=settle(act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}),[2,2]);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);expect(s.players.B!.damage).toBe(0);expect(s.players.D!.hand).toHaveLength(5);expect(s.reclaimDecisions?.some(d=>d.source.kind==='courage-resolution')).not.toBe(true);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
it('actual Blood immediate refill remains separate from the later physical Courage return',()=>{let s=start('courage-refill');const before=gameStats(s,'D');s=play(s);expect(s.players.D!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'D')).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});s=settle(take(beneficiary(request(checker(s)))));expect(s.players.D!.hand).toHaveLength(6);expect(s.players.D!.hand).toContain(card);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId==='a2-p01-r1c3')).toHaveLength(1);});
it('actual later separate attack permits both the mental ability and returned Courage with a new consenting check',()=>{let s=settle(take(beneficiary(request(checker(play(start('courage-later')))))));s=nextA(s);s=use(at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['B'],dedicated:false}),'normal-defense'),'courage-later');s=settle(take(beneficiary(request(checker(play(s))))));expect(s.players.B!.damage).toBe(8);expect(s.players.D!.hand.filter(id=>id===card)).toHaveLength(1);expect(s.rolls!.filter(r=>r.resume.kind==='reclaim-check')).toHaveLength(2);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(0);});
it('actual God reroll updates the single Lester check without granting a second attempt',()=>{let s=request(checker(play(start('courage-dia',6))));s=until(s,s=>s.windows?.at(-1)?.kind==='after-roll',[6,6]);const roll=s.rolls!.at(-1)!,id=roll.id;expect(roll.success).toBe(false);s=priority(s,'A');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=beneficiary(s);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({generation:1,faces:[1,2],success:true});s=settle(take(s));expect(s.players.D!.hand).toContain(card);expect(s.rolls!.filter(r=>r.resume.kind==='reclaim-check')).toHaveLength(1);});
it('actual optional Courage decline leaves the card and ordinary mental check unchanged',()=>{let s=priority(start('courage-dia'),'D');expect(option(s)).toBeDefined();s=settle(s);expect(s.players.D!.hand).toContain(card);expect(s.players.B!.damage).toBe(4);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.reclaimDecisions?.some(d=>d.source.kind==='courage-resolution')).not.toBe(true);});
it('actual already rolled mental declaration rejects late Courage without payment or return opportunity',()=>{let s=until(start('courage-dia'),s=>s.windows?.at(-1)?.kind==='after-roll',[2,2]);s=priority(s,'D');expect(option(s)).toBeUndefined();const event=Object.values(s.abilities!)[0]!.id;reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event});s=settle(s);expect(s.players.D!.hand).toContain(card);expect(s.players.A!.statuses?.some(t=>t.kind==='stopped')).toBe(true);});
