import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,finish,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeCursePhysicalScenario} from './fixtures/curse-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p13-r3c2',rows=['curse-ordinary','curse-dedicated'] as const;
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState){for(let n=0;n<100;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('CURSE_TURN');}throw Error('CURSE_TURN_LIMIT');}
function chant(s:GameState){s=act(s,'A',{type:'CHANT',cardInstanceId:card});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return nextOwn(s);}
function attack(dedicated:boolean){return {type:'ATTACK' as const,cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated};}
function claim(s:GameState){for(let n=0;n<300;n++){const d=viewFor(s,'A').reclaim;if(s.windows?.at(-1)?.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){expect(d.claims.map(c=>c.right)).toContain('base');return act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});}s=pass(s);}throw Error('CURSE_CLAIM');}
it.each(rows)('%s actual chant preserves printed effect and damage and only waives dedicated use checks',scenario=>{
 const dedicated=scenario==='curse-dedicated';for(const level of [6,7]){let s=makeCursePhysicalScenario(scenario,players,{level,follower:'none'});reject(s,'A',attack(dedicated));s=act(chant(s),'A',attack(dedicated));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:7,effectLevel:7,damage:14,attributes:['魔','精','黒','詠'],chant:true,noChecks:dedicated,target:dedicated?'all':'one',maaiProhibited:true});expect(f.checkSpecs).toHaveLength(dedicated?0:7-level);expect(f.fromChant).toBe(true);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([14,dedicated?14:0,0]);expect(s.players.A!.chants).toEqual([]);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);}
});
it.each(rows)('%s actual failed ordinary excess-level check contrasts with dedicated no-check damage',scenario=>{
 const dedicated=scenario==='curse-dedicated';let s=act(chant(makeCursePhysicalScenario(scenario,players,{level:6,follower:'none'})),'A',attack(dedicated));for(let n=0;n<300&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.purpose==='excess-level'&&r.stage==='before-roll'?[6,6]:[1,1]);}expect([s.players.B!.damage,s.players.C!.damage]).toEqual(dedicated?[14,14]:[0,0]);expect((s.rolls??[]).filter(r=>r.purpose==='excess-level').map(r=>r.success)).toEqual(dedicated?[]:[false]);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);
});
it.each(rows)('%s actual mental hit passes Metal without HP reduction while C Soldier independently absorbs one',scenario=>{
 const dedicated=scenario==='curse-dedicated';let s=makeCursePhysicalScenario(scenario,players);const guard=structuredClone(s.players.B!.followers);s=until(act(chant(s),'A',attack(dedicated)),'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]).toMatchObject({hits:[{hitIndex:0,outcome:'passed-through',hpReduction:0}]});s=finish(s);expect(s.players.B!.followers).toEqual(guard);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([14,dedicated?13:0]);
});
it.each([['curse-ordinary',0,'blocked',0],['curse-ordinary',1,'equal-destroyed',0],['curse-ordinary',2,'lower-destroyed',14],['curse-dedicated',0,'blocked',0],['curse-dedicated',1,'equal-destroyed',0],['curse-dedicated',2,'lower-destroyed',14]] as const)('%s actual black Guardian level8 with Prayer%s resolves %s and body%s',(scenario,bonus,outcome,damage)=>{
 const dedicated=scenario==='curse-dedicated';let s=act(chant(makeCursePhysicalScenario(scenario,players,{follower:'guardian'})),'A',{...attack(dedicated),targetIds:['B']});if(bonus){s=until(s,'effect-level');const id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}for(let n=0;n<150&&s.windows?.at(-1)?.kind!=='follower-start';n++)s=pass(s,Array(30).fill(bonus||1));s=closeWindow(s,Array(30).fill(bonus||1));for(let n=0;n<100&&!Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits.length;n++)s=pass(s,Array(30).fill(bonus||1));const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.levels).toEqual([8]);expect(f.hits[0]!.outcome).toBe(outcome);s=finish(s);expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(outcome==='blocked'?1:0);expect(s.players.C!.followers).toHaveLength(1);
});
it.each(rows)('%s actual maai and Evade are forbidden but Teleport protects only B',scenario=>{
 const dedicated=scenario==='curse-dedicated';let s=until(act(chant(makeCursePhysicalScenario(scenario,players)),'A',attack(dedicated)),'normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:true,evadeProhibited:true,counterProhibited:false});s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,dedicated?13:0]);expect(s.players.B!.followers).toHaveLength(1);
});
it.each(rows)('%s actual Fate cancel base reclaim and fresh chant allow later reuse without stale mode',scenario=>{
 const dedicated=scenario==='curse-dedicated';let s=act(chant(makeCursePhysicalScenario(scenario,players,{follower:'none'})),'A',attack(dedicated));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=pass(pass(s));s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(claim(s));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.A!.hand).toContain(card);s=nextOwn(s);reject(s,'A',attack(!dedicated));s=finish(act(chant(s),'A',attack(!dedicated)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([14,!dedicated?14:0]);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);
});
it.each(rows)('%s refuses foreign dedicated owner ordinary multiple targets and unsupported variant after actual chant',scenario=>{
 const s=chant(makeCursePhysicalScenario(scenario,players));reject(s,'A',{...attack(false),targetIds:['B','C']});reject(s,'A',{...attack(true),techniqueVariant:'two-hit'});const foreign=chant(makeCursePhysicalScenario(scenario,players,{owner:'聖騎士ランスロット'}));reject(foreign,'A',attack(true));
});
