import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDarkSaintPhysicalScenario,darkSaintPhysicalMode,type DarkSaintPhysicalScenario} from './fixtures/dark-saint-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['saint-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ROYAL_KNIGHTS_TURN');}throw Error('ROYAL_KNIGHTS_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r2c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}

const SAINT='a2-p21-r2c1';
it('actual attacking Dia may elect to ignore enemy Dark Saint without revealing the hidden physical follower',()=>{
 let s=ready(makeDarkSaintPhysicalScenario('saint-ignore',players),SAINT);s=until(incoming(s),'follower-entry-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);expect(viewFor(s,'B').legalChoices).toContain('CHOOSE_DARK_SAINT_IGNORE');s=act(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:true});expect(s.players.B!.revealed).toBe(true);s=finish(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:SAINT,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(SAINT);
});
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=darkSaintPhysicalMode(scenario);let s=makeDarkSaintPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(rows)('%s actual own-action placement reordering and forbidden voluntary removal maintain physical order and hidden input',scenario=>{
 const m=darkSaintPhysicalMode(scenario);let s=ready(makeDarkSaintPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1','a2-p23-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);expect(s.discard).not.toContain(m.card);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=darkSaintPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeDarkSaintPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=darkSaintPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeDarkSaintPhysicalScenario(scenario,players,{level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=darkSaintPhysicalMode(scenario);let s=until(incoming(ready(makeDarkSaintPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=darkSaintPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeDarkSaintPhysicalScenario(scenario,players,{owner:'魔聖母ディア'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});

function entry(s:GameState,actor='B'){s=until(s,'follower-entry-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!==actor)s=pass(s);return s;}
it.each([false,true])('actual Dia ignore choice=%s is private before use and cannot be repeated or chosen by another actor',ignore=>{
 let s=entry(incoming(ready(makeDarkSaintPhysicalScenario('saint-ignore',players),SAINT)));expect(JSON.stringify(viewFor(s,'C'))).not.toContain('CHOOSE_DARK_SAINT_IGNORE');expect(s.players.B!.revealed).toBe(false);reject(s,'A',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore});s=act(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore});expect(s.players.B!.revealed).toBe(ignore);reject(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore});s=finish(s);expect(s.players.A!.damage).toBe(ignore?4:0);expect(s.players.A!.followers[0]!.revealed).toBe(!ignore);
});
it('actual Dia defender cannot use attacking permission and owning the saint still does not permit voluntary removal',()=>{
 let s=ready(makeDarkSaintPhysicalScenario('saint-setup',players,{owner:'魔聖母ディア'}),SAINT);reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[]});s=until(incoming(s),'follower-entry-abilities');expect(viewFor(s,'A').legalChoices).not.toContain('CHOOSE_DARK_SAINT_IGNORE');reject(s,'A',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:true});s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers[0]!.revealed).toBe(true);
});
it('actual Dia choice is also available with another hidden follower and never bypasses that different card',()=>{
 let s=entry(incoming(ready(makeDarkSaintPhysicalScenario('saint-ignore',players,{card:'a2-p22-r1c1'}),'a2-p22-r1c1')));expect(viewFor(s,'B').legalChoices).toContain('CHOOSE_DARK_SAINT_IGNORE');expect(JSON.stringify(viewFor(s,'B'))).not.toContain('a2-p22-r1c1');s=finish(act(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:true}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);
});
it('actual rear Guardian cancels Dia card-specific ignore for the entire column after morale',()=>{
 let s=makeDarkSaintPhysicalScenario('saint-guard',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SAINT});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r3c3'});s=ready(s,SAINT,false);s=entry(incoming(s));s=finish(act(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:true}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([SAINT,'a2-p22-r3c3']);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual Dia ignore applies independently to all three Dwarf hits without HP2 reduction',()=>{
 let s=next(ready(makeDarkSaintPhysicalScenario('saint-ignore',players,{level:6}),SAINT));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=entry(act(s,'B',grant(s,'B','a2-p21-r2c3')));s=act(s,'B',{type:'CHOOSE_DARK_SAINT_IGNORE',ignore:true});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(['passed-through','passed-through','passed-through']);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.players.A!.followers[0]!.revealed).toBe(false);
});
it.each(['saint-magic5','saint-magic6','saint-magic7'] as const)('%s actual magic compares conditional6 and uses HP2 only above it',scenario=>{
 const m=darkSaintPhysicalMode(scenario);let s=next(ready(makeDarkSaintPhysicalScenario(scenario,players),SAINT));s=act(s,'B',{type:'ATTACK',cardInstanceId:m.magicLevel===5?'a2-p17-r2c2':'a2-p18-r1c3',targetIds:['A'],dedicated:false});if(m.magicLevel===7){s=until(s,'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p18-r1c3')!.id});}s=until(s,'follower-start');const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.hits[0]!.technique?.effectLevel??g.technique.effectLevel).toBe(m.magicLevel);expect(g.targets[0]!.followerDefense![0]!.levels).toEqual([6]);s=finish(s);expect(s.players.A!.damage).toBe(m.magicLevel===7?6:0);expect(s.players.A!.followers).toHaveLength(m.magicLevel===5?1:0);
});
it('actual mixed Dwarf6 and Winged magic7 group freezes physical5 versus magic6 and applies HP2 per hit',()=>{
 let s=next(ready(makeDarkSaintPhysicalScenario('saint-setup',players,{level:6,mixed:true}),SAINT));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));const o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;s=act(s,'B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:'a2-p21-r2c3',dedicated:false,targetIds:['A']},{cardInstanceId:'a2-p21-r1c3',dedicated:false,targetIds:['A','C','D']}]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense![0]!;expect(f.levels).toEqual([5,5,5,6]);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([22,12,12]);expect(s.discard.filter(id=>id===SAINT)).toHaveLength(1);
});
it('actual Alseil Mirror Seal forcibly removes nonremovable Dark Saint',()=>{
 let s=next(ready(makeDarkSaintPhysicalScenario('saint-destroy',players),SAINT));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p13-r1c2',targetIds:['A'],dedicated:true}),'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits[0]!.outcome).toBe('level-destroyed');s=finish(s);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===SAINT)).toHaveLength(1);
});
function saintAttack(s:GameState,army:boolean){return army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:SAINT,targetIds:['B']}:grant(s);}
it.each(['saint-army','saint-grant-hand','saint-grant-field'] as const)('%s actual explicit attack permission consumes even nonremovable placed source and retains magic5 checks',scenario=>{
 const m=darkSaintPhysicalMode(scenario);for(const magic of [4,5]){let s=ready(makeDarkSaintPhysicalScenario(scenario,players,{magic}),SAINT,m.initial);s=act(s,'A',saintAttack(s,m.army));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===SAINT)!;expect(a.checks).toHaveLength(5-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:5,effectLevel:5,damage:6,attributes:['遠','魔','精','黒'],noChecks:false,target:'one'});s=finish(s);expect(s.players.B!.damage).toBe(6);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===SAINT)).toHaveLength(1);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);}
});
it('actual hand-only Army refuses placed Dark Saint while far attack also reaches a near target',()=>{
 let s=ready(makeDarkSaintPhysicalScenario('saint-army',players),SAINT);reject(s,'A',saintAttack(s,true));s=ready(makeDarkSaintPhysicalScenario('saint-army',players),SAINT,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',saintAttack(s,true)));expect(s.players.B!.damage).toBe(6);
});
it('actual spirit attack passes physical Metal without its HP or revelation and spent Saint cannot defend a Mirror return',()=>{
 let s=makeDarkSaintPhysicalScenario('saint-army-spirit',players);s=act(s,'A',{type:'PASS_SETUP'});s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of ['B','C','D'])s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=finish(act(s,'A',saintAttack(s,true)));expect(s.players.B!.damage).toBe(6);expect(s.players.B!.followers[0]!.revealed).toBe(false);
 s=ready(makeDarkSaintPhysicalScenario('saint-army',players),SAINT,false);s=until(act(s,'A',saintAttack(s,true)),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([6,0]);expect(s.players.A!.followers).toEqual([]);
});
it.each(['parent','child','use','grant-hand','grant-field'] as const)('actual Dark Saint %s cancellation or failed use pays source once without return',mode=>{
 const army=!mode.startsWith('grant');let s=ready(makeDarkSaintPhysicalScenario(army?'saint-army':mode==='grant-hand'?'saint-grant-hand':'saint-grant-field',players,{magic:4}),SAINT,mode==='grant-field');s=act(s,'A',saintAttack(s,army));if(mode==='child')s=closeWindow(s);if(mode==='use')s=until(s,'before-roll');const a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='parent'?'a2-p05-r2c2':SAINT)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04'),roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',!army?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of army?[SAINT,'a2-p05-r2c2']:[SAINT])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});

it('actual hidden Saint versus Metal worlds offer identical attacker and outsider views at the same choice boundary',()=>{
 const states=[SAINT,'a2-p22-r1c1'].map(card=>entry(incoming(ready(makeDarkSaintPhysicalScenario('saint-ignore',players,{card}),card))));
 for(const id of ['B','C','D'])expect(viewFor(states[0]!,id)).toEqual(viewFor(states[1]!,id));
 for(const state of states){expect(state.players.B!.revealed).toBe(false);expect(JSON.stringify(viewFor(state,'B'))).not.toContain(SAINT);}
});
