import {expect,it} from 'vitest';
import {viewFor,transition,type GameState} from '../src/index.js';
import {act,closeWindow,finish,until} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDawnPhysicalScenario,dawnPhysicalScenarios} from './fixtures/dawn-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),dawn='a2-p01-r1c2',book='a2-p03-r1c1';
const zones=(s:GameState,id:string)=>{const p=s.players[id]!;return{hand:p.hand,followers:p.followers,chants:p.chants,attachments:p.attachments,damage:p.damage};};
it.each(['dawn-deaths','dawn-return','dawn-empty'] as const)('%s actual secret book OPEN shuffles the complete discard plus deck and excludes public source and all owned zones',scenario=>{let s=makeDawnPhysicalScenario(scenario,players);const source=scenario==='dawn-return'?'C':'A',discard=[...s.discard],pool=[...s.deck.filter(id=>id!==dawn),...discard],others=Object.fromEntries(s.seatOrder.filter(id=>id!==source).map(id=>[id,structuredClone(zones(s,id))]));if(scenario==='dawn-empty')expect(discard).toEqual([]);else expect(discard.length).toBeGreaterThan(0);s=act(s,source,{type:'PLAY_TURN_CARD',cardInstanceId:book});s=until(s,'after-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'extra-draw',faces:[1]});const hand=[...s.players[source]!.hand];expect(s.resolution).toContain(book);s=closeWindow(s);expect(s.players[source]!.open).toContain(dawn);expect(s.discard).toEqual([]);expect(s.resolution).toContain(book);const drawn=s.players[source]!.hand.filter(id=>!hand.includes(id));expect(drawn).toHaveLength(1);expect([...s.deck,...drawn].sort()).toEqual([...pool].sort());expect([...drawn,...s.deck]).not.toEqual(pool);expect(s.deck).not.toContain(book);expect(s.deck).not.toContain(dawn);for(const id of s.seatOrder.filter(id=>id!==source))expect(zones(s,id)).toEqual(others[id]);if(scenario==='dawn-return'){expect(s.players.B!.presence).toBe('active');expect(s.events.filter(e=>e.type==='PLAYER_RETURNED'&&e.actorId==='B')).toHaveLength(1);expect(s.windows!.some(w=>w.kind==='re-setup')).toBe(false);}if(scenario==='dawn-deaths')for(const id of ['B','C'])expect(s.players[id]!.presence).toBe('dead');expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===dawn)).toHaveLength(1);s=finish(s);expect(s.discard).toEqual([book]);expect(s.resolution).toEqual([]);expect(s.phase).toBe('action');expect(s.players[source]!.open.filter(id=>id===dawn)).toHaveLength(1);});
it('actual Dawn return is public before the resumed private card draw and does not recreate setup possessions',()=>{let s=makeDawnPhysicalScenario('dawn-return',players);expect(s.players.B!.presence).toBe('otherworld');expect(s.discard).toContain('a2-p14-r2c2');const previous=s.events.length,b=structuredClone(zones(s,'B'));s=finish(act(s,'C',{type:'PLAY_TURN_CARD',cardInstanceId:book}));const events=s.events.slice(previous),open=events.findIndex(e=>e.type==='OPEN'&&e.cardInstanceId===dawn),returned=events.findIndex(e=>e.type==='PLAYER_RETURNED'&&e.actorId==='B'),draw=events.findIndex(e=>e.type==='CARD_DRAWN'&&e.actorId==='C');expect(open).toBeGreaterThanOrEqual(0);expect(returned).toBeGreaterThan(open);expect(draw).toBeGreaterThan(returned);expect(zones(s,'B')).toEqual(b);for(const id of s.seatOrder){expect(viewFor(s,id).players.B!.presence).toBe('active');expect(viewFor(s,id).logs.some(e=>e.type==='PLAYER_RETURNED'&&e.actorId==='B')).toBe(true);}expect(s.events.filter(e=>e.type==='PLAYER_REVIVED')).toEqual([]);});
