import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,viewFor,type GameState} from '../src/index.js';
import {ownsAbility} from '../src/abilities/ownership.js';
import {act,ready,until,finish,closeWindow,pass} from './combat-helpers.js';
import {character,handCard} from './fixtures.js';
function priority(s:GameState,actor:string){for(let n=0;n<100;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('RITUAL_PRIORITY');}
function nextOwn(s:GameState,owner:string){for(let n=0;n<50;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(actor===owner)return s;s=act(s,actor,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error(`RITUAL_TURN_${s.phase}`);}throw Error('RITUAL_TURN_LIMIT');}
for(const subordinate of [false,true])for(const conspiracy of [false,true])it(`Actual Uonos ritual preserves identity boundaries with subordinate=${subordinate} and Arseil=${conspiracy}`,()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','占星術師のアルセイル');character(s,'C','魔聖母ディア');character(s,'D','餓狼ヨーツルム');s.players.A!.damage=4;handCard(s,'A','復活の儀式');s=act(s,'A',{type:'USE_REVIVAL_RITUAL'});expect(s.outcome).toBeUndefined();s=closeWindow(s);expect(s.players.A).toMatchObject({characterId:'c2-p07-r1c2',faction:'ヴァンミール',damage:0,abilityCharacterIds:['c2-p07-r1c2']});expect(gameStats(s,'A').endurance).toBe(25);expect(ownsAbility(s.players.A!,'c2-p05-r1c1-ab03')).toBe(false);expect(ownsAbility(s.players.A!,'c2-p07-r1c2-ab03')).toBe(true);expect(s.outcome).toBeUndefined();if(subordinate){s=closeWindow(act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'}));expect(s.outcome).toBeUndefined();}s=priority(s,'B');if(conspiracy){s=closeWindow(act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'}));expect(s.outcome).toBeUndefined();}s=finish(s);expect(s.players.C!.faction).toBe(subordinate?'ヴァンミール':'EVIL');expect(s.players.D!.faction).toBe(subordinate?'ヴァンミール':'EVIL');expect(s.players.B!.presence).toBe(conspiracy?'exited':'active');expect(s.individualResults?.B).toBe(conspiracy?'won':undefined);});
it('Actual ritual then two-target chanted sword defers Vanmil terminal outcome until simultaneous Cham gift finishes',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','大神官ジル');character(s,'C','小妖精のチャム');character(s,'D','魔導王ガイナス');s.players.A!.permanent={endurance:-10};s.players.A!.damage=1;for(const actor of ['B','C','D'])s.players[actor]!.permanent={endurance:100,warrior_level:20,magic_level:20,spirit:20};s.players.C!.damage=gameStats(s,'C').endurance-3;handCard(s,'A','復活の儀式');const gift=handCard(s,'C','香具羅'),attack=handCard(s,'D',getAction('a2-p10-r2c1')!.name);s.deck=[...s.deck.filter(id=>getAction(id)!.category!=='open'),...s.deck.filter(id=>getAction(id)!.category==='open')];s=finish(act(s,'A',{type:'USE_REVIVAL_RITUAL'}));expect(s.players.A!.damage).toBe(0);expect(gameStats(s,'A').endurance).toBe(15);s=nextOwn(s,'D');s=act(s,'D',{type:'CHANT',cardInstanceId:attack});s=nextOwn(s,'D');s=until(act(s,'D',{type:'ATTACK',cardInstanceId:attack,targetIds:['A','C'],dedicated:false}),'death-gift');expect(s.players.A!.presence).toBe('pending-death');expect(s.players.C!.presence).toBe('pending-death');expect(s.outcome).toBeUndefined();s=pass(s);expect(s.players.A!.presence).toBe('dead');expect(s.outcome).toBeUndefined();const option=viewFor(s,'C').lifecycleDecision!.chamGift!;expect(option.eligibleTargetIds).toEqual(['B','D']);s=until(act(s,'C',{type:'CHAM_DEATH_GIFT',decisionId:option.decisionId,cardInstanceId:gift,targetId:'D'}),'death-gift');expect(s.players.D!.hand).toContain(gift);expect(s.outcome).toBeUndefined();s=finish(s);expect(s.players.C!.presence).toBe('dead');expect(s.outcome).toMatchObject({reason:'vanmil-death',winnerIds:['B','C','D']});expect(s.players.D!.hand).toContain(gift);});
