import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {assignCharacter,takeCard} from './fixtures/scenario-tools.js';
import {makeDeathKnightPhysicalScenario,deathKnightPhysicalMode,type DeathKnightPhysicalScenario} from './fixtures/death-knight-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['death-knight-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DEATH_KNIGHT_TURN');}throw Error('DEATH_KNIGHT_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p22-r3c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=deathKnightPhysicalMode(scenario);let s=makeDeathKnightPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=deathKnightPhysicalMode(scenario);let s=ready(makeDeathKnightPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=deathKnightPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeDeathKnightPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=deathKnightPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeDeathKnightPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<=m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=deathKnightPhysicalMode(scenario);let s=until(incoming(ready(makeDeathKnightPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
const DEATH_KNIGHT='a2-p22-r3c2',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);return act(s,'B',grant(s,'B','a2-p21-r2c3'));}

it.each(['pass','fail'] as const)('actual Death Knight spirit6 minus2 morale %s shares one result across Dwarf8 hits with HP0',mode=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-higher',players,{spirit:6}),DEATH_KNIGHT);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-2,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,2]:[2,3]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:4,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual([0,0,0]);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.discard.filter(id=>id===DEATH_KNIGHT)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each([false,true])('actual Gad Death Knight defensive waiver=%s at spirit0 retains level7 HP0 revival7',selected=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-waive',players),DEATH_KNIGHT);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DEATH_KNIGHT,DEATH_KNIGHT]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[DEATH_KNIGHT]:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.levels).toEqual([7,7,7]);expect(f.descriptor).toMatchObject({hp:0,revivalLimit:7});s=finish(s);expect(s.players.A!.damage).toBe(selected?0:18);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(selected?[DEATH_KNIGHT]:[]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);
});
it.each(['front','rear'] as const)('actual Death Knight equal7 revival preserves %s position and rechecks only a later group',position=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-equal',players),DEATH_KNIGHT,true,true);if(position==='rear')s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',DEATH_KNIGHT]});s=until(dwarf(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerDefense!.filter(f=>f.source==='physical'&&f.cardInstanceId===DEATH_KNIGHT)).toHaveLength(1);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(position==='front'?[DEATH_KNIGHT,'a2-p22-r1c1']:[DEATH_KNIGHT]);expect(s.discard).not.toContain(DEATH_KNIGHT);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.players.A!.damage).toBe(0);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
});
it.each(['safe','over-first','over-last'] as const)('actual mixed Dia group %s forbids Death Knight revival when any destroying hit exceeds7',mode=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-equal',players,{level:mode==='safe'?7:8}),DEATH_KNIGHT);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));const o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!,ids=mode==='over-last'?['a2-p22-r1c3','a2-p21-r2c3']:['a2-p21-r2c3','a2-p22-r1c3'];s=until(act(s,'B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:ids.map(cardInstanceId=>({cardInstanceId,dedicated:false,targetIds:['A']}))}),'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits).toHaveLength(4);expect(f.revivalForbidden).toBe(mode!=='safe');s=finish(s);expect(s.players.A!.damage).toBe(mode==='safe'?0:18);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(mode==='safe'?[DEATH_KNIGHT]:[]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(['death-knight-white','death-knight-destroy'] as const)('%s actual explicit destruction prevents revival even at or below7 without HP or morale',scenario=>{
 const m=deathKnightPhysicalMode(scenario);let s=next(ready(makeDeathKnightPhysicalScenario(scenario,players),DEATH_KNIGHT));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.white?'a2-p14-r1c3':'a2-p13-r1c2',targetIds:['A'],dedicated:true}),'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.revivalForbidden).toBe(true);expect(f.hits[0]!.hpReduction).toBe(0);s=finish(s);expect(s.players.A!.damage).toBe(m.white?10:0);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===DEATH_KNIGHT)).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it('actual unreached Death Knight stays hidden without morale and foreign owner cannot choose Gad waiver',()=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-setup',players,{spirit:0}),DEATH_KNIGHT,true,true);s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',DEATH_KNIGHT]});s=finish(incoming(s));expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);s=until(dwarf(ready(makeDeathKnightPhysicalScenario('death-knight-setup',players),DEATH_KNIGHT)),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DEATH_KNIGHT]});
});
function knightAttack(s:GameState,scenario:DeathKnightPhysicalScenario,targets=['B','C','D']){return deathKnightPhysicalMode(scenario).army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:DEATH_KNIGHT,targetIds:targets}:{type:'ATTACK' as const,cardInstanceId:DEATH_KNIGHT,targetIds:targets,dedicated:true};}
it.each(['death-knight-army','death-knight-ded-hand','death-knight-ded-field'] as const)('%s actual Gad permission far warrior sword black6 damage8 retains all targets and extra maai',scenario=>{
 const m=deathKnightPhysicalMode(scenario);for(const warrior of [5,6]){let s=ready(makeDeathKnightPhysicalScenario(scenario,players,{warrior:m.dedicated?0:warrior,magic:warrior===5?20:0}),DEATH_KNIGHT,m.initial);for(const targets of [[],['A'],['B'],['B','C'],['B','B','C','D']])reject(s,'A',knightAttack(s,scenario,targets));s=act(s,'A',knightAttack(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===DEATH_KNIGHT)!;expect(a.checks).toHaveLength(m.dedicated?0:6-warrior);expect(a.technique).toMatchObject({range:'far',school:'warrior',useLevel:6,effectLevel:6,damage:8,attributes:['遠','戦','剣','黒'],noChecks:m.dedicated,hitCount:1,target:'all',mandatoryAll:true,maaiRequired:2});s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([8,8,8]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);for(const id of m.army?[DEATH_KNIGHT,ARMY]:[DEATH_KNIGHT])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it.each(['竜皇子アスフェルト','魔聖母ディア','獣使いのウパニシャット'] as const)('actual %s lacks direct Death Knight permission and human or beast grants do not include dead knight',owner=>{
 for(const placed of [false,true]){const s=ready(makeDeathKnightPhysicalScenario('death-knight-army',players,{owner}),DEATH_KNIGHT,placed);for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:DEATH_KNIGHT,targetIds:['B','C','D'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:DEATH_KNIGHT});expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===DEATH_KNIGHT)).toBe(false);}
});
it('actual Gad ordinary direct and placed Army reject while Army spirit0 still fails minus2 morale without revival',()=>{
 const q=ready(makeDeathKnightPhysicalScenario('death-knight-army',players),DEATH_KNIGHT);reject(q,'A',knightAttack(q,'death-knight-army'));reject(q,'A',{type:'ATTACK',cardInstanceId:DEATH_KNIGHT,targetIds:['B','C','D'],dedicated:false});let s=ready(makeDeathKnightPhysicalScenario('death-knight-army',players,{spirit:0}),DEATH_KNIGHT,false);s=finish(act(s,'A',knightAttack(s,'death-knight-army')));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);for(const id of [DEATH_KNIGHT,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it.each(['hand','field','parent','child','morale','use'] as const)('actual Death Knight %s cancellation or failure spends paid cards once and cannot trigger defensive revival',mode=>{
 const scenario=mode==='hand'?'death-knight-ded-hand':mode==='field'?'death-knight-ded-field':'death-knight-army',m=deathKnightPhysicalMode(scenario);let s=ready(makeDeathKnightPhysicalScenario(scenario,players,{warrior:5}),DEATH_KNIGHT,m.initial);s=act(s,'A',knightAttack(s,scenario));if(mode==='child')s=closeWindow(s);if(mode==='morale'||mode==='use'){s=until(s,'before-roll');if(mode==='use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='morale'?'follower-morale':'excess-level');}const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?ARMY:DEATH_KNIGHT))!,roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='morale'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.players.A!.followers).toEqual([]);for(const id of m.army?[DEATH_KNIGHT,ARMY]:[DEATH_KNIGHT])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it.each(['death-knight-army','death-knight-ded-hand','death-knight-ded-field'] as const)('%s F44 requires an atomic two-card maai payment before opening an attempt',scenario=>{
 const m=deathKnightPhysicalMode(scenario);let s=ready(makeDeathKnightPhysicalScenario(scenario,players),DEATH_KNIGHT,m.initial);s=until(act(s,'A',knightAttack(s,scenario)),'normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c2']});reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c1']});s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c3']});expect(s.players.B!.hand).not.toContain('a2-p07-r1c2');expect(s.players.B!.hand).not.toContain('a2-p07-r1c3');expect(Object.values(s.groups!)[0]!.maai!.submissions.B).toEqual(['a2-p07-r1c2','a2-p07-r1c3']);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,8,8]);for(const id of ['a2-p07-r1c2','a2-p07-r1c3'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});

it.each([false,true])('F44 one shared advance consumes the paid bundle and allows remaining single payment=%s',complete=>{
 let s=makeDeathKnightPhysicalScenario('death-knight-ded-hand',players);takeCard(s,'B','a2-p07-r2c1');s=ready(s,DEATH_KNIGHT,false);const distances=structuredClone(s.distances);
 s=until(act(s,'A',knightAttack(s,'death-knight-ded-hand')),'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.maaiBundleSize).toBe(2);
 s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c3']});
 expect(s.resolution).toEqual(expect.arrayContaining(['a2-p07-r1c2','a2-p07-r1c3']));s=closeWindow(s);
 expect(s.discard).toContain('a2-p07-r1c2');expect(s.resolution).toContain('a2-p07-r1c3');expect(s.windows!.at(-1)!.kind).toBe('reclaim');expect(Object.values(s.groups!)[0]!.targetCursor).toBe(0);
 s=until(s,'defense-advance');s=act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:'a2-p24-r1c3'});s=until(s,'defense-advance');s=pass(s);
 expect(s.windows!.at(-1)).toMatchObject({kind:'normal-defense',continuation:{targetId:'B'}});expect(viewFor(s,'B').currentAttack!.defenseRestrictions.maaiBundleSize).toBe(1);
 for(const id of ['a2-p07-r1c2','a2-p07-r1c3'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
 if(complete)s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r2c1'});s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([complete?0:8,8,8]);expect(s.distances).toEqual(distances);
});
it.each([false,true])('F44 elected flight cancellation=%s preserves both queued payments through declaration and reclaims',canceled=>{
 let s=makeDeathKnightPhysicalScenario('death-knight-ded-hand',players);assignCharacter(s,'B','有翼人のティア');s=ready(s,DEATH_KNIGHT,false);s=until(act(s,'A',knightAttack(s,'death-knight-ded-hand')),'normal-defense');
 s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c3'],abilityId:'c2-p02-r1c1-ab01'});expect(s.windows!.at(-1)!.kind).toBe('declaration');expect(s.resolution).toEqual(expect.arrayContaining(['a2-p07-r1c2','a2-p07-r1c3']));
 if(canceled){while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);const ability=Object.values(s.abilities!).find(f=>f.abilityId==='c2-p02-r1c1-ab01')!;s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability.id});}
 s=until(s,'defense-advance');s=act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:'a2-p24-r1c3'});s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([canceled?8:0,8,8]);for(const id of ['a2-p07-r1c2','a2-p07-r1c3'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.reclaimDecisions!.filter(d=>['a2-p07-r1c2','a2-p07-r1c3'].includes(d.cardInstanceId))).toHaveLength(2);expect(s.resolution).toEqual([]);
});
it('F44 attack surcharge never applies to approach distance payments and bundled distance payload rejects without payment',()=>{
 let s=ready(makeDeathKnightPhysicalScenario('death-knight-ded-hand',players),DEATH_KNIGHT,false);s=act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:'a2-p24-r1c3'});reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2',additionalCardInstanceIds:['a2-p07-r1c3']});s=finish(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));expect(s.players.B!.hand).toContain('a2-p07-r1c3');expect(s.distances.A!.B).toBe('far');expect(s.players.A!.hand).toContain(DEATH_KNIGHT);
});
