import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDeathSongPhysicalScenario,deathSongPhysicalMode,type DeathSongPhysicalScenario} from '../../../apps/worker/test/fixtures/death-song-physical-scenarios.js';
const CARD='a2-p17-r1c3',players=['A','B','C','D'].map(id=>({id,name:id})),rows=['death-song-ordinary','death-song-dedicated'] as const;
function attack(scenario:DeathSongPhysicalScenario){const m=deathSongPhysicalMode(scenario);return{type:'ATTACK' as const,cardInstanceId:CARD,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function next(s:GameState,chantB=false){for(let n=0;n<220;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id==='A'&&s.phase==='action')return s;else if(s.phase==='action'){if(id==='B'&&chantB){s=act(s,id,{type:'CHANT',cardInstanceId:'a2-p14-r2c3'});chantB=false;}else s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==CARD).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DEATH_SONG_TURN');}throw Error('DEATH_SONG_LIMIT');}
function prepare(s:GameState,chantB=false){s=act(s,'A',{type:'CHANT',cardInstanceId:CARD});expect(s.players.A!.chants).toContainEqual({cardInstanceId:CARD,revealed:false});return next(s,chantB);}
function settle(s:GameState,faces=[3,4]){for(let n=0;n<350&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.rollerId==='B'&&r.purpose==='hit-resistance'&&r.stage==='before-roll'?faces:Array(30).fill(1));}expect(s.windows??[]).toEqual([]);return s;}
it.each(rows)('%s actual CHANT full turns and paid near preserve profile magic6 one check versus7 zero or selected exemption',scenario=>{
 const m=deathSongPhysicalMode(scenario);for(const level of [6,7])for(const near of [false,true]){let s=makeDeathSongPhysicalScenario(scenario,players,{level,follower:'none'});reject(s,'A',attack(scenario));s=prepare(s);if(near)s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c2',targetId:'B'}));s=act(s,'A',attack(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect(f).toMatchObject({fromChant:true,technique:{school:'magic',range:'far',useLevel:7,effectLevel:m.effect,attributes:['魔','精','歌','詠'],chant:true,noChecks:m.dedicated,target:m.dedicated?'all':'one',followerIgnore:true,damageFormula:m.dedicated?'attacker-magic-x3':'2d6x2'}});expect(f.technique.counterProhibited??false).toBe(m.dedicated);expect(f.checkSpecs).toHaveLength(m.dedicated?0:7-level);s=settle(s);const damage=m.dedicated?level*3:4;expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([damage,m.dedicated?damage:0,0]);expect(s.players.A!.chants).toEqual([]);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);}
});
it.each(rows)('%s actual Metal Soldier and Water followers are ignored intact without HP subtraction',scenario=>{
 const m=deathSongPhysicalMode(scenario);let s=prepare(makeDeathSongPhysicalScenario(scenario,players));const b=structuredClone(s.players.B!.followers),c=structuredClone(s.players.C!.followers);s=settle(act(s,'A',attack(scenario)));expect(s.players.B!.damage).toBe(m.damage);expect(s.players.C!.damage).toBe(m.dedicated?m.damage:0);expect(s.players.B!.followers).toEqual(b);expect(s.players.C!.followers).toEqual(c);
});
it.each([[1,2],[6,6]] as const)('actual ordinary Death Song stores one 2d6x2 damage record for faces%s %s',(one,two)=>{
 let s=until(act(prepare(makeDeathSongPhysicalScenario('death-song-ordinary',players)),'A',attack('death-song-ordinary')),'damage');s=closeWindow(s,[one,two]);s=finish(s);expect(s.players.B!.damage).toBe((one+two)*2);expect(s.randomRolls).toEqual([expect.objectContaining({kind:'damage',formula:'2d6x2',faces:[one,two],total:(one+two)*2})]);
});
it.each([3,7,10])('actual dedicated Death Song caster magic%s fixes triple damage for all three targets without damage dice',level=>{
 let s=act(prepare(makeDeathSongPhysicalScenario('death-song-dedicated',players,{level})),'A',{...attack('death-song-dedicated'),targetIds:['B','C','D']});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([level*3,level*3,level*3]);expect(s.randomRolls??[]).toEqual([]);expect((s.rolls??[]).filter(r=>r.purpose==='excess-level')).toEqual([]);
});
it.each(rows)('%s actual Guardian7 cancels follower ignore at equal or lower with real Prayer',scenario=>{
 const m=deathSongPhysicalMode(scenario);for(const bonus of [0,1]){let s=act(prepare(makeDeathSongPhysicalScenario(scenario,players,{follower:'guardian'})),'A',{...attack(scenario),targetIds:['B']});if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id});}s=finish(s);expect(s.players.B!.followers).toEqual([]);expect(s.players.B!.damage).toBe(m.dedicated||bonus?m.damage:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual Teleport maai and rejected mental Evade keep defense target-local',scenario=>{
 const m=deathSongPhysicalMode(scenario);for(const defense of ['teleport','maai','evade']){let s=until(act(prepare(makeDeathSongPhysicalScenario(scenario,players)),'A',attack(scenario)),'normal-defense');if(defense==='evade')reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else s=defense==='maai'?act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}):act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});s=finish(s);expect(s.players.B!.damage).toBe(defense==='evade'?m.damage:0);expect(s.players.C!.damage).toBe(m.dedicated?m.damage:0);expect(s.players.B!.followers).toHaveLength(2);}
});
it.each(['a2-p11-r1c3','a2-p12-r3c2','a2-p14-r2c3'])('actual mirror or prior chanted God %s respects fixed mirror limits and selected counter prohibition',cardInstanceId=>{
 for(const scenario of ['death-song-ordinary','death-song-dedicated'] as const){const m=deathSongPhysicalMode(scenario);let s=until(act(prepare(makeDeathSongPhysicalScenario(scenario,players,{follower:'none',mirrors:true}),true),'A',attack(scenario)),'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.counterProhibited).toBe(m.dedicated);const rejected=m.dedicated||cardInstanceId!=='a2-p14-r2c3';if(rejected)reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId,dedicated:false});else s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId,dedicated:false});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(rejected?[0,m.damage,m.dedicated?m.damage:0]:[16,0,0]);}
});
it.each([[3,3],[3,4]] as const)('actual dedicated Gadyura own plus-zero resistance at%s %s is after normal defenses and does not affect C',(one,two)=>{
 let s=until(act(prepare(makeDeathSongPhysicalScenario('death-song-dedicated-resist',players,{spirit:6})),'A',attack('death-song-dedicated-resist')),'normal-defense');expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance')).toEqual([]);s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'hit-resistance',rollerId:'B',modifier:0,faces:[]});expect(s.players.B!.damage).toBe(0);expect(JSON.stringify(viewFor(s,'C').currentRoll)).not.toContain('c2-');s=settle(s,[one,two]);expect(s.rolls!.filter(r=>r.purpose==='hit-resistance')).toEqual([expect.objectContaining({rollerId:'B',modifier:0,threshold:6,success:two===3,faces:[one,two]})]);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([two===3?0:21,21]);expect(s.players.B!.followers).toHaveLength(2);
});
it('actual Gadyura fear attacker check remains separate from own dedicated Death Song resistance',()=>{
 let s=until(act(prepare(makeDeathSongPhysicalScenario('death-song-dedicated-resist',players,{spirit:6})),'A',attack('death-song-dedicated-resist')),'normal-defense');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p06-r1c1-ab01')!;expect(option).toBeDefined();s=act(s,'B',{type:'USE_ABILITY',abilityId:option.abilityId,targetEventId:option.targetEventId});s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({rollerId:'A',modifier:-1});s=closeWindow(s,[1,2]);s=settle(s,[3,4]);expect(s.players.B!.damage).toBe(21);expect(s.players.C!.damage).toBe(21);expect(s.rolls!.filter(r=>r.rollerId==='A')).toContainEqual(expect.objectContaining({modifier:-1,success:true,faces:[1,2]}));expect(s.rolls!.filter(r=>r.purpose==='hit-resistance')).toEqual([expect.objectContaining({rollerId:'B',modifier:0,success:false,faces:[3,4]})]);
});
it.each(rows)('%s actual use failure or Fate cancellation never reaches Gadyura resistance',scenario=>{
 const m=deathSongPhysicalMode(scenario);if(!m.dedicated){let s=until(act(prepare(makeDeathSongPhysicalScenario(scenario,players,{level:6,gad:true})),'A',attack(scenario)),'before-roll');s=finish(closeWindow(s,[6,6]));expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance')).toEqual([]);}let s=act(prepare(makeDeathSongPhysicalScenario(scenario,players,{gad:true})),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.B!.followers).toHaveLength(2);expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance')).toEqual([]);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);
});
it.each(rows)('%s actual owned alias base reclaim returns card but still requires reCHANT for later opposite mode',scenario=>{
 const m=deathSongPhysicalMode(scenario);let s=act(prepare(makeDeathSongPhysicalScenario(scenario,players)),'A',attack(scenario)),taken=false;for(let n=0;n<300&&s.windows?.length;n++){const r=viewFor(s,'A').reclaim;if(!taken&&s.windows!.at(-1)!.kind==='reclaim'&&r?.pendingActorId==='A'&&r.cardInstanceId===CARD){const base=r.claims.find(c=>c.right==='base');expect(base).toBeDefined();s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:r.decisionId,choice:'take',claimId:base!.claimId});taken=true;}else s=pass(s);}expect(taken).toBe(true);expect(s.players.A!.hand.filter(x=>x===CARD)).toHaveLength(1);expect(s.players.A!.reclaimUsage?.['死歌']?.baseSpent).toBe(true);expect(s.players.A!.reclaimUsage).not.toHaveProperty('死詩');s=next(s);reject(s,'A',{...attack(scenario),dedicated:!m.dedicated});s=prepare(s);s=finish(act(s,'A',{...attack(scenario),dedicated:!m.dedicated,targetIds:m.dedicated?['B']:['B','C','D']}));expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual(m.dedicated?[25,21,0]:[25,21,21]);expect(s.players.A!.chants).toEqual([]);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);
});
it.each(rows)('%s actual unchanted foreign dedication invalid and publicly friendly targets are refused before payment',scenario=>{
 const m=deathSongPhysicalMode(scenario);let s=makeDeathSongPhysicalScenario(scenario,players);reject(s,'A',attack(scenario));s=prepare(s);for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',{...attack(scenario),targetIds});if(!m.dedicated)reject(s,'A',{...attack(scenario),targetIds:['B','C']});s=act(s,'D',{type:'REVEAL_CHARACTER'});reject(s,'A',{...attack(scenario),targetIds:['D']});reject(s,'B',attack(scenario));s=prepare(makeDeathSongPhysicalScenario(scenario,players,{owner:'白魔術師シェリム'}));reject(s,'A',{...attack(scenario),dedicated:true});s=finish(act(s,'A',{...attack(scenario),dedicated:false,targetIds:['B']}));expect(s.players.B!.damage).toBe(4);
});
