import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState,type GameCommand} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDeathGiftPhysicalScenario,deathGiftMode,type DeathGiftPhysicalScenario} from '../../../apps/worker/test/fixtures/death-gift-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s);}throw Error('DEATH_GIFT_LIMIT');}
function giftWindow(s:GameState){return until(s,s=>s.windows?.at(-1)?.kind==='death-gift');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function command(name:DeathGiftPhysicalScenario):GameCommand{const m=deathGiftMode(name);return {type:'PLAY_DEATH_GIFT',cardInstanceId:m.card,giftCardInstanceId:m.gift,targetId:m.batch?'D':'C'};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['death-gift-evil','death-gift-good','death-gift-evil-batch','death-gift-good-batch','death-gift-evil-protection','death-gift-good-protection','death-gift-good-converted'] as const)('%s actual death gives exactly one private physical card without refill before disposal protection and outcome',name=>{
 let s=makeDeathGiftPhysicalScenario(name,players);const m=deathGiftMode(name),target=m.batch?'D':'C',hand=[...s.players.B!.hand],recipient=[...s.players[target]!.hand],deck=[...s.deck];expect(s.players.B!.presence).toBe('pending-death');expect(s.players.B!.damage).toBe(gameStats(s,'B').endurance);expect(s.players.B!.deathIdentity!.faction).toBe(m.evil?'EVIL':'GOOD');if(m.converted){expect(s.initialFactions![1]).toBe('EVIL');expect(s.events.some(e=>e.type==='FACTION_CHANGED'&&e.actorId==='B')).toBe(true);reject(s,'B',{...command(name),cardInstanceId:m.wrong});}expect(s.outcome).toBeUndefined();expect(viewFor(s,'B').legalChoices).toContain('PLAY_DEATH_GIFT');if(m.batch){const batch=s.lifecycle!.find(t=>t.kind==='death-batch');expect(batch).toMatchObject({actorIds:['B','C']});expect(viewFor(s,'B').lifecycleDecision!.eligibleTargetIds).toEqual(['A','D']);reject(s,'B',{...command(name),targetId:'C'});}
 s=act(s,'B',command(name));expect(s.players.B!.hand).toEqual(hand.filter(id=>id!==m.card));expect(s.resolution).toContain(m.card);expect(s.players.B!.hand).toContain(m.gift);expect(s.players[target]!.hand).toEqual(recipient);expect(s.deck).toEqual(deck);for(const id of ['A','C','D'])if(id!=='B')expect(JSON.stringify(viewFor(s,id))).not.toContain(m.gift);
 s=giftWindow(s);expect(s.players.B!.presence).toBe('pending-death');expect(s.players.B!.hand).toEqual(hand.filter(id=>id!==m.card&&id!==m.gift));expect(s.players[target]!.hand).toEqual([...recipient,m.gift]);expect(s.players[target]!.hand.length).toBeGreaterThan(gameStats(s,target).handLimit);expect(s.deck).toEqual(deck);expect(s.discard).toContain(m.card);expect(s.discard).not.toContain(m.gift);expect(s.outcome).toBeUndefined();expect(s.events.filter(e=>e.type==='PLAYER_DIED')).toEqual([]);
 for(const id of s.seatOrder){const v=viewFor(s,id),logs=v.logs.filter(e=>e.type==='CARD_GIFTED');expect(logs).toHaveLength(1);expect(logs[0]!.cardInstanceId).toBeUndefined();if(id==='B'||id===target)expect(v.privateLogs.some(e=>e.type==='CARD_GIFTED'&&e.cardInstanceId===m.gift)).toBe(true);else expect(JSON.stringify(v)).not.toContain(m.gift);}
 const residual=[...s.players.B!.hand];s=settle(s);expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.hand).toEqual([]);expect(s.discard).toEqual(expect.arrayContaining([m.card,...residual]));expect(s.resolution).toEqual([]);if(m.protection){expect(s.players.C!.presence).toBe('wandering');expect(s.players.C!.hand).toEqual([]);expect(s.deck).toContain(m.gift);}else expect(s.players[target]!.hand).toEqual([...recipient,m.gift]);const giftIndex=s.events.findIndex(e=>e.type==='CARD_GIFTED'),deathIndex=s.events.findIndex(e=>e.type==='PLAYER_DIED');expect(deathIndex).toBeGreaterThan(giftIndex);
});
it.each(['death-gift-evil-fate','death-gift-good-fate'] as const)('%s actual Fate discards printed source but selected gift remains until ordinary death disposal',name=>{let s=makeDeathGiftPhysicalScenario(name,players);const m=deathGiftMode(name),hand=[...s.players.B!.hand];s=act(s,'B',command(name));const action=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;s=until(s,s=>{const w=s.windows!.at(-1)!;return w.participants[w.cursor]==='D';});s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:action.id});s=giftWindow(s);expect(s.players.B!.hand).toEqual(hand.filter(id=>id!==m.card));expect(s.players.C!.hand).not.toContain(m.gift);expect(s.discard).toContain(m.card);expect(s.discard).not.toContain(m.gift);expect(s.events.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);reject(s,'B',command(name));s=settle(s);expect(s.discard).toContain(m.gift);expect(s.players.C!.hand).not.toContain(m.gift);});
it.each(['death-gift-evil-decline','death-gift-good-decline'] as const)('%s declining actual death window disposes both printed source and all untransferred hand cards',name=>{let s=makeDeathGiftPhysicalScenario(name,players);const hand=[...s.players.B!.hand];s=settle(s);expect(s.players.B!.presence).toBe('dead');expect(s.discard).toEqual(expect.arrayContaining(hand));expect(s.events.filter(e=>e.type==='CARD_GIFTED')).toEqual([]);reject(s,'B',command(name));});
it.each(['death-gift-good-ability-first','death-gift-good-printed-first','death-gift-evil-ability-first','death-gift-evil-printed-first'] as const)('S25 %s actual Cham and printed card have independent entitlements and cannot transfer the same card twice',name=>{let s=makeDeathGiftPhysicalScenario(name,players);const m=deathGiftMode(name),batch=s.windows!.at(-1)!.eventId,hand=[...s.players.B!.hand],deck=[...s.deck],ability:GameCommand={type:'CHAM_DEATH_GIFT',decisionId:batch,cardInstanceId:m.second,targetId:'D'};if(m.converted){expect(s.initialFactions![1]).toBe('GOOD');expect(s.players.B!.faction).toBe('EVIL');expect(s.players.B!.deathIdentity!.faction).toBe('EVIL');expect(s.events.some(e=>e.type==='FACTION_CHANGED'&&e.actorId==='B')).toBe(true);reject(s,'B',{...command(name),cardInstanceId:m.wrong});}s=giftWindow(act(s,'B',m.abilityFirst?ability:command(name)));if(m.abilityFirst){reject(s,'B',{...command(name),giftCardInstanceId:m.second});expect(viewFor(s,'B').legalChoices).toContain('PLAY_DEATH_GIFT');}else{reject(s,'B',{...ability,cardInstanceId:m.gift});expect(viewFor(s,'B').legalChoices).toContain('CHAM_DEATH_GIFT');}s=giftWindow(act(s,'B',m.abilityFirst?command(name):ability));expect(s.players.B!.presence).toBe('pending-death');expect(s.outcome).toBeUndefined();expect(s.players.C!.hand).toContain(m.gift);expect(s.players.D!.hand).toContain(m.second);expect(s.players.B!.hand).toEqual(hand.filter(id=>![m.card,m.gift,m.second].includes(id)));expect(s.deck).toEqual(deck);reject(s,'B',ability);s=settle(s);expect(s.events.filter(e=>e.type==='CARD_GIFTED'&&e.audience==='public')).toHaveLength(2);expect(s.discard).toContain(m.card);expect(s.discard).not.toContain(m.gift);expect(s.discard).not.toContain(m.second);});
it.each(['death-gift-evil','death-gift-good'] as const)('%s alive wrong faction self foreign card source itself and wrong actor declarations reject all four views',name=>{const ready=makeDeathGiftPhysicalScenario(name,players,true);reject(ready,'B',command(name));reject(ready,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:deathGiftMode(name).card,targetId:'C'});let s=makeDeathGiftPhysicalScenario(name,players);const m=deathGiftMode(name);reject(s,'B',{...command(name),cardInstanceId:m.wrong});reject(s,'B',{...command(name),giftCardInstanceId:m.card});reject(s,'B',{...command(name),giftCardInstanceId:s.players.C!.hand[0]});for(const targetId of ['B','missing'])reject(s,'B',{...command(name),targetId});reject(s,'C',command(name));s=act(s,'B',command(name));reject(s,'B',command(name));s=giftWindow(s);reject(s,'B',{...command(name),giftCardInstanceId:m.gift,targetId:'D'});});
it.each(['death-gift-evil','death-gift-good'] as const)('%s received excess card remains through turn start and is adjusted only at recipient normal turn end',name=>{let s=settle(act(makeDeathGiftPhysicalScenario(name,players),'B',command(name)));const m=deathGiftMode(name),received=[...s.players.C!.hand];expect(received).toHaveLength(6);s=act(s,'A',{type:'PASS_WITHDRAWAL'});s=settle(act(s,'A',{type:'END_TURN',discardIds:[]}));expect(s.seatOrder[s.turnSeat]).toBe('C');expect(s.players.C!.hand).toEqual(received);s=settle(act(s,'C',{type:'START_TURN'}));s=settle(act(s,'C',{type:'CHOOSE_DRAW',draw:false}));expect(s.players.C!.hand).toEqual(received);s=act(s,'C',{type:'PASS_ACTION'});if(s.phase==='withdrawal')s=act(s,'C',{type:'PASS_WITHDRAWAL'});reject(s,'C',{type:'END_TURN',discardIds:[]});s=settle(act(s,'C',{type:'END_TURN',discardIds:[m.gift]}));expect(s.players.C!.hand).toEqual(received.filter(id=>id!==m.gift));expect(s.discard).toContain(m.gift);});
it.each(['death-gift-evil-batch','death-gift-good-batch'] as const)('%s actual second death decision still excludes every batch member after first giver disposal',name=>{let s=makeDeathGiftPhysicalScenario(name,players);s=pass(s);expect(s.players.B!.presence).toBe('dead');expect(s.players.C!.presence).toBe('pending-death');expect(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]).toBe('C');expect(viewFor(s,'C').lifecycleDecision!.eligibleTargetIds).toEqual(['A','D']);expect(s.lifecycle!.find(t=>t.kind==='death-batch')).toMatchObject({actorIds:['B','C'],cursor:1});expect(s.outcome).toBeUndefined();});
