import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDevilPhysicalScenario,devilPhysicalMode,type DevilPhysicalScenario} from '../../../apps/worker/test/fixtures/devil-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['devil-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DEVIL_TURN');}throw Error('DEVIL_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p22-r1c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=devilPhysicalMode(scenario);let s=makeDevilPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=devilPhysicalMode(scenario);let s=ready(makeDevilPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=devilPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeDevilPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=devilPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeDevilPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=devilPhysicalMode(scenario);let s=until(incoming(ready(makeDevilPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
const DEVIL='a2-p22-r1c2',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Devil spirit6 unmodified morale %s applies once to every Dwarf7 hit',mode=>{
 let s=ready(makeDevilPhysicalScenario('devil-higher',players,{spirit:6}),DEVIL);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:0,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(mode==='pass'?4:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?6:18);expect(s.discard.filter(id=>id===DEVIL)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual surviving Devil checks each later group while an unreached hidden rear never checks',()=>{
 let s=ready(makeDevilPhysicalScenario('devil-setup',players),DEVIL);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeDevilPhysicalScenario('devil-setup',players,{spirit:0}),DEVIL,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',DEVIL]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([false,true])('actual explicit Uonos Devil waiver=%s at spirit0 preserves level6 HP4 and changes only morale',selected=>{
 let s=ready(makeDevilPhysicalScenario('devil-waive',players),DEVIL);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DEVIL,DEVIL]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[DEVIL]:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.levels).toEqual([6,6,6]);expect(f.descriptor.hp).toBe(4);s=finish(s);expect(s.players.A!.damage).toBe(selected?6:18);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);
});
it('actual foreign owner cannot select Uonos defensive Devil waiver',()=>{
 let s=ready(makeDevilPhysicalScenario('devil-setup',players,{owner:'竜皇子アスフェルト'}),DEVIL);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DEVIL]});
});
it.each(['devil-sky','devil-white'] as const)('%s actual sky ignore or black destruction remains effective despite selected Uonos waiver',scenario=>{
 const m=devilPhysicalMode(scenario);let s=next(ready(makeDevilPhysicalScenario(scenario,players),DEVIL));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p14-r1c2',targetIds:m.sky?['A','C']:['A'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DEVIL]});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense![0]!;expect(f.hits[0]!.outcome).toBe(m.sky?'passed-through':'attribute-destroyed');s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.sky?[12,12]:[6,0]);expect(s.players.A!.followers).toHaveLength(m.sky?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(0);if(m.sky)expect(s.players.A!.followers[0]!.revealed).toBe(false);else expect(s.discard.filter(id=>id===DEVIL)).toHaveLength(1);
});
it.each([false,true])('actual Uonos hand or placed=%s never gains an unprinted direct Devil attack permission',placed=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players),DEVIL,placed);for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:DEVIL,targetIds:['B'],dedicated});expect(viewFor(s,'A').followerAttackOptions.some(o=>o.cardInstanceId===DEVIL)).toBe(false);reject(s,'A',{type:'CHANT',cardInstanceId:DEVIL});
});
it('actual Dia human attack grant excludes Devil attributes even after approach',()=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players,{owner:'魔聖母ディア'}),DEVIL,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===DEVIL)).toBe(false);reject(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources:[{cardInstanceId:DEVIL,dedicated:false,targetIds:['B']}]});
});
it.each([5,6])('actual Uonos Army Devil uses far black magic6 damage8 with magic%i and retains ordinary morale',magic=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players,{magic,warrior:magic===5?20:0}),DEVIL,false);const cmd={type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:DEVIL,targetIds:['B']};for(const targetIds of [[],['A'],['B','B'],['B','C']])reject(s,'A',{...cmd,targetIds});s=act(s,'A',cmd);const a=Object.values(s.actions!).find(a=>a.cardInstanceId===DEVIL)!;expect(a.checks).toHaveLength(6-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:6,effectLevel:6,damage:8,attributes:['遠','魔','黒'],noChecks:false,hitCount:1,target:'one'});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([8,0]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);for(const id of [DEVIL,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it('actual Devil Army remains legal after approach but placed source and Fury black restriction reject',()=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players),DEVIL,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:DEVIL,targetIds:['B']}));expect(s.players.B!.damage).toBe(8);
 for(const placed of [false,true]){const q=ready(makeDevilPhysicalScenario('devil-army',players,{owner:placed?'邪祭ウーノス':'妖精王フューリー'}),DEVIL,placed);expect(viewFor(q,'A').allArmyOptions.some(o=>o.followerCardInstanceId===DEVIL)).toBe(false);reject(q,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:DEVIL,targetIds:['B']});}
});
it.each(['maai','mirror'] as const)('actual Devil Army accepts %s normal defense and consumes its source before reflection',mode=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players),DEVIL,false);s=until(act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:DEVIL,targetIds:['B']}),'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([mode==='mirror'?8:0,0]);for(const id of [DEVIL,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);
});
it.each(['parent','child','morale','use'] as const)('actual Devil Army %s cancellation or failure consumes both paid cards once',mode=>{
 let s=ready(makeDevilPhysicalScenario('devil-army',players,{magic:5}),DEVIL,false);s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:DEVIL,targetIds:['B']});if(mode==='child')s=closeWindow(s);if(mode==='morale'||mode==='use'){s=until(s,'before-roll');if(mode==='use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='morale'?'follower-morale':'excess-level');}const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?ARMY:DEVIL))!,roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='morale'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of [DEVIL,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
