import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDiaLifetimePhysicalScenario,diaLifetimePhysicalMode,type DiaLifetimePhysicalScenario} from './fixtures/dia-lifetime-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['soul-physical-ordinary','soul-physical-dedicated','heart-physical-ordinary','heart-physical-dedicated'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function next(s:GameState,target='A'){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id===target)return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p15-r2c3','a2-p15-r3c1','a2-p13-r3c1','a2-p12-r2c2'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DIA_TURN');}throw Error('DIA_TURN_LIMIT');}
function prepare(s:GameState,scenario:DiaLifetimePhysicalScenario){const m=diaLifetimePhysicalMode(scenario);if(m.heart){s=act(s,'A',{type:'CHANT',cardInstanceId:m.card});expect(s.players.A!.chants).toEqual([{cardInstanceId:m.card,revealed:false}]);return next(s);}if(!m.dedicated){s=finish(act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:'a2-p24-r1c2'}));expect(s.distances.A!.B).toBe('near');}return s;}
function attack(scenario:DiaLifetimePhysicalScenario){const m=diaLifetimePhysicalMode(scenario);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function finish(s:GameState,options:{success?:string[];kill?:string[];reclaim?:boolean}={}){let taken=false;for(let n=0;n<500&&s.windows?.length;n++){const w=s.windows!.at(-1)!,r=s.rolls?.at(-1),choice=viewFor(s,'A').lifetimeDecision,reclaim=viewFor(s,'A').reclaim;if(w.kind==='lifetime-effect-choice'){reject(s,'B',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'});s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:options.kill?.includes(choice!.targetId)?'apply':'decline'});}else if(w.kind==='re-setup')s=act(s,w.participants[w.cursor]!,{type:'PASS_SETUP'});else if(options.reclaim&&!taken&&w.kind==='reclaim'&&reclaim?.pendingActorId==='A'&&reclaim.cardInstanceId==='a2-p15-r2c3'){const base=reclaim.claims.find(c=>c.right==='base');expect(base).toBeDefined();s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:reclaim.decisionId,choice:'take',claimId:base!.claimId});taken=true;}else s=pass(s,Array(30).fill(r?.purpose==='status-resistance'&&r.stage==='before-roll'&&!options.success?.includes(r.rollerId)?6:1));}expect(s.windows??[]).toEqual([]);return s;}
it.each(rows)('%s actual wounded Dia preserves profile while only dedicated use checks are waived',scenario=>{
 const m=diaLifetimePhysicalMode(scenario);for(const level of [6,7]){let s=makeDiaLifetimePhysicalScenario(scenario,players,{level,follower:'none'});if(m.heart||!m.dedicated)reject(s,'A',attack(scenario));const before=gameStats(s,'B');s=act(prepare(s,scenario),'A',attack(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:!m.heart&&!m.dedicated?'near':'far',useLevel:7,effectLevel:m.dedicated?8:7,damage:null,attributes:m.heart?['魔','精','黒','詠']:['魔','精','黒'],chant:m.heart,noChecks:m.dedicated,followerIgnore:m.dedicated,target:m.dedicated?'all':'one',lifetimeHit:{kind:m.heart?'deadly-stop':'soul-drain',modifier:m.heart&&m.dedicated?-3:-1}});expect(f.checkSpecs).toHaveLength(m.dedicated?0:7-level);s=finish(s);expect(s.players.A!.damage).toBe(5);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.presence).toBe('active');if(m.heart)expect(s.players.B!.statuses![0]).toMatchObject({kind:'stopped',timing:'deadly-recovery',modifiers:[m.dedicated?-3:-1]});else expect(gameStats(s,'B')).toMatchObject({warrior_level:before.warrior_level-1,magic_level:before.magic_level-1,spirit:before.spirit-1});expect(s.rolls!.filter(r=>r.purpose==='status-resistance').map(r=>r.threshold)).toEqual(m.dedicated?(m.heart?[3,3]:[5,5]):[5]);expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);expect(s.phase).toBe('withdrawal');}
});
it.each(rows)('%s actual successful target resistance prevents drain stop death and self healing',scenario=>{
 let s=makeDiaLifetimePhysicalScenario(scenario,players,{follower:'none'});const b=gameStats(s,'B'),c=gameStats(s,'C');s=finish(act(prepare(s,scenario),'A',attack(scenario)),{success:['B','C'],kill:['B','C']});expect([s.players.A!.damage,s.players.B!.damage]).toEqual([5,0]);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.C!.statuses??[]).toEqual([]);expect(gameStats(s,'B')).toEqual(b);expect(gameStats(s,'C')).toEqual(c);expect(s.events.some(e=>e.type==='PLAYER_DIED')).toBe(false);
});
it.each(rows)('%s actual mental Metal pass and elected Water bypass retain physical followers',scenario=>{
 const m=diaLifetimePhysicalMode(scenario);let s=makeDiaLifetimePhysicalScenario(scenario,players);const b=structuredClone(s.players.B!.followers),c=structuredClone(s.players.C!.followers);s=finish(act(prepare(s,scenario),'A',attack(scenario)));expect(s.players.B!.followers).toEqual(b);expect(s.players.C!.followers).toEqual(c);expect(s.players.B!.statuses??[]).toHaveLength(1);expect(s.players.C!.statuses??[]).toHaveLength(m.dedicated?1:0);
});
it.each([['soul-physical-ordinary',0],['soul-physical-dedicated',0],['soul-physical-dedicated',1],['heart-physical-ordinary',0],['heart-physical-dedicated',0],['heart-physical-dedicated',1]] as const)('%s actual black Guardian cancels ignore and Prayer%s controls whether lifetime hit exists',(scenario,bonus)=>{
 const m=diaLifetimePhysicalMode(scenario);let s=act(prepare(makeDiaLifetimePhysicalScenario(scenario,players,{follower:'guardian'}),scenario),'A',{...attack(scenario),targetIds:['B']});if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id});}s=finish(s);expect(s.players.B!.followers).toHaveLength(m.dedicated?0:1);expect(s.players.B!.statuses??[]).toHaveLength(bonus?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(bonus?1:0);expect(s.players.C!.followers).toHaveLength(1);
});
it.each(rows)('%s actual failed ordinary use and Fate cancellation preserve every target without lifetime effects',scenario=>{
 const m=diaLifetimePhysicalMode(scenario);if(!m.dedicated){let s=act(prepare(makeDiaLifetimePhysicalScenario(scenario,players,{level:6}),scenario),'A',attack(scenario));s=finish(closeWindow(until(s,'before-roll'),[6,6]));expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.B!.followers).toHaveLength(1);expect(s.players.A!.damage).toBe(5);}let s=act(prepare(makeDiaLifetimePhysicalScenario(scenario,players),scenario),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}),{kill:['B','C']});expect(s.players.A!.damage).toBe(5);for(const target of ['B','C']){expect(s.players[target]!.statuses??[]).toEqual([]);expect(s.players[target]!.followers).toHaveLength(1);}expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual Teleport prevents only B effect while mental Evade is refused',scenario=>{
 const m=diaLifetimePhysicalMode(scenario);let s=until(act(prepare(makeDiaLifetimePhysicalScenario(scenario,players),scenario),'A',attack(scenario)),'normal-defense');reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}));expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.C!.statuses??[]).toHaveLength(m.dedicated?1:0);expect(s.players.B!.followers).toHaveLength(1);expect(s.players.A!.damage).toBe(5);
});
it.each(rows)('%s rejects unchanted or far ordinary and foreign dedicated invalid target modes',scenario=>{
 const m=diaLifetimePhysicalMode(scenario);let s=makeDiaLifetimePhysicalScenario(scenario,players);if(!m.heart)reject(s,'A',{type:'CHANT',cardInstanceId:m.card});else reject(s,'A',attack(scenario));s=prepare(s,scenario);reject(s,'A',{...attack(scenario),targetIds:['B','C'],dedicated:false});reject(s,'A',{...attack(scenario),targetIds:['A']});reject(s,'A',{...attack(scenario),targetIds:[]});reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:m.card,targetIds:['A'],dedicated:m.dedicated});const foreign=prepare(makeDiaLifetimePhysicalScenario(scenario,players,{owner:'邪祭ウーノス'}),scenario);reject(foreign,'A',{...attack(scenario),dedicated:true});
});
it.each(['B','C','both','none'])('actual Soul choice %s heals Dia only after selected deaths and never also drains killed targets',selection=>{
 const killed=selection==='both'?['B','C']:selection==='none'?[]:[selection];let s=act(prepare(makeDiaLifetimePhysicalScenario('soul-physical-dedicated',players),'soul-physical-dedicated'),'A',attack('soul-physical-dedicated'));let choices=0;for(let n=0;n<500&&s.windows?.length;n++){if(s.players.A!.damage===0)expect(s.events.some(e=>e.type==='PLAYER_DIED'&&killed.includes(e.actorId))).toBe(true);const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d){expect(s.players[d.targetId]!.presence).toBe('active');expect(s.players.A!.damage).toBe(5);s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:killed.includes(d.targetId)?'apply':'decline'});choices++;}else s=pass(s,Array(30).fill(r?.purpose==='status-resistance'&&r.stage==='before-roll'?6:1));}expect(s.windows??[]).toEqual([]);expect(choices).toBe(2);expect(s.players.A!.damage).toBe(killed.length?0:5);for(const id of ['B','C']){expect(s.players[id]!.presence).toBe(killed.includes(id)?'dead':'active');expect(s.players[id]!.statuses??[]).toHaveLength(killed.includes(id)?0:1);}expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(killed);expect(s.outcome).toBeUndefined();
});
it.each(['soul-physical-ordinary','soul-physical-dedicated'] as const)('%s actual reclaim reuse stacks drain at zero then actual death and resurrection remove it',scenario=>{
 let s=makeDiaLifetimePhysicalScenario(scenario,players,{follower:'none',targetStats:1,deathAndRevival:true});expect(gameStats(s,'B')).toMatchObject({warrior_level:1,magic_level:1,spirit:1});s=finish(act(prepare(s,scenario),'A',{...attack(scenario),targetIds:['B']}),{reclaim:true});expect(s.players.A!.hand).toContain('a2-p15-r2c3');expect(gameStats(s,'B')).toMatchObject({warrior_level:0,magic_level:0,spirit:0});s=next(s);s=finish(act(s,'A',{...attack(scenario),targetIds:['B']}));expect(gameStats(s,'B')).toMatchObject({warrior_level:0,magic_level:0,spirit:0});expect(s.players.B!.statuses).toHaveLength(2);expect(s.rolls!.filter(r=>r.purpose==='status-resistance').map(r=>r.threshold)).toEqual([0,-1]);s=next(s,'D');s=finish(act(s,'D',{type:'ATTACK',cardInstanceId:'a2-p12-r2c2',targetIds:['B'],dedicated:false}));expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.statuses).toEqual([]);s=next(s);s=next(act(s,'A',{type:'CHANT',cardInstanceId:'a2-p13-r3c1'}));s=finish(act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['B'],dedicated:false}));expect(s.players.B).toMatchObject({presence:'active',damage:0,statuses:[]});expect(gameStats(s,'B')).toMatchObject({warrior_level:1,magic_level:1,spirit:1});expect(s.players.B!.hand).toHaveLength(5);expect(discardIds(s).filter(x=>x==='a2-p15-r2c3')).toHaveLength(1);
});
it.each([['heart-physical-ordinary',true],['heart-physical-ordinary',false],['heart-physical-dedicated',true],['heart-physical-dedicated',false]] as const)('%s actual next-own recovery success=%s removes whole deadline or commits death before any draw',(scenario,success)=>{
 const m=diaLifetimePhysicalMode(scenario);let s=until(act(prepare(makeDiaLifetimePhysicalScenario(scenario,players),scenario),'A',attack(scenario)),'normal-defense');s=until(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}),'before-roll');s=finish(closeWindow(s,[6,6]));expect(s.players.B!.hand).toHaveLength(4);expect(s.players.B!.statuses![0]).toMatchObject({kind:'stopped',timing:'deadly-recovery',modifiers:[m.dedicated?-3:-1]});s=act(s,'A',{type:'PASS_WITHDRAWAL'});s=act(s,'A',{type:'END_TURN',discardIds:[]});expect(s.seatOrder[s.turnSeat]).toBe('B');expect((s.rolls??[]).filter(r=>r.purpose==='status-recovery')).toHaveLength(0);s=until(act(s,'B',{type:'START_TURN'}),'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',rollerId:'B',modifier:m.dedicated?-3:-1});s=finish(closeWindow(s,success?[1,1]:[6,6]));expect(s.rolls!.filter(r=>r.purpose==='status-recovery').at(-1)).toMatchObject({threshold:m.dedicated?3:5,success});expect(s.players.B!.presence).toBe(success?'active':'dead');expect(s.players.B!.statuses??[]).toHaveLength(success?0:1);if(!success)reject(s,'B',{type:'START_TURN'});expect(s.players.B!.hand).toHaveLength(success?5:0);expect(s.players.A!.damage).toBe(5);expect(s.players.C!.statuses??[]).toHaveLength(m.dedicated?1:0);if(success){expect(s.phase).toBe('draw');expect(s.seatOrder[s.turnSeat]).toBe('B');}else expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['B']);
});
