import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDinonPhysicalScenario,dinonCard,type DinonPhysicalScenario} from './fixtures/dinon-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s);}throw Error('DINON_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function command(targetId='B'){return {type:'PLAY_TURN_CARD',cardInstanceId:dinonCard,targetId,mode:'ordinary'} as const;}
function reject(s:GameState,id:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function rest(s:GameState,id:string){const {hand,...p}=s.players[id]!;return p;}
it.each(['dinon-hidden','dinon-public','dinon-self','dinon-source-only','dinon-target-empty','dinon-both-empty','dinon-unequal','dinon-overflow-source','dinon-overflow-target','dinon-zones'] as const)('%s actual physical source payment then atomic residual hand swap preserves other zones and private ownership',name=>{let s=makeDinonPhysicalScenario(name,players);const target=name==='dinon-self'?'A':'B',a=s.players.A!.hand.filter(id=>id!==dinonCard),originalB=[...s.players.B!.hand],b=target==='A'?a:originalB,deck=[...s.deck],other=structuredClone([s.players.C!,s.players.D!]),ar=rest(s,'A'),br=rest(s,'B');if(name==='dinon-zones'){expect(s.players.A!.open).toContain('a2-p01-r1c3');expect(s.players.A!.attachments).toContain('a2-p03-r3c1');expect(s.players.B!.attachments).toContain('a2-p03-r2c1');expect(s.players.B!.chants.map(x=>x.cardInstanceId)).toEqual(['a2-p13-r1c1']);expect(s.players.A!.followers).toHaveLength(1);expect(s.players.B!.followers).toHaveLength(1);}expect(viewFor(s,'A').turnChoiceCardOptions.find(o=>o.cardInstanceId===dinonCard)!.targetIds).toEqual(['A','B','C','D']);s=act(s,'A',command(target));expect(s.players.A!.hand).toEqual(a);expect(s.players.B!.hand).toEqual(originalB);expect(s.deck).toEqual(deck);expect(s.resolution).toContain(dinonCard);s=settle(s);expect(s.players.A!.hand).toEqual(b);expect(s.players[target]!.hand).toEqual(a);if(target==='A')expect(s.players.B!.hand).toEqual(originalB);expect(s.deck).toEqual(deck);expect(s.resolution).toEqual([]);expect(s.discard.filter(id=>id===dinonCard)).toHaveLength(1);expect(s.phase).toBe('hand-adjustment');expect(rest(s,'A')).toEqual(ar);expect(rest(s,'B')).toEqual(br);expect([s.players.C!,s.players.D!]).toEqual(other);expect(viewFor(s,'A').self.hand).toEqual(b);expect(viewFor(s,target).self.hand).toEqual(a);for(const id of ['C','D']){expect(viewFor(s,id).players.A).not.toHaveProperty('hand');expect(viewFor(s,id).players.B).not.toHaveProperty('hand');}reject(s,'A',command(target));});
it.each(['dinon-source-refill','dinon-target-refill'] as const)('%s actual Peace during declaration changes the residual hand snapshot used at resolution',name=>{let s=makeDinonPhysicalScenario(name,players);const owner=name==='dinon-source-refill'?'A':'B',recipient=owner==='A'?'B':'A';s=act(s,'A',command());const old=[...s.players[owner]!.hand];s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]===owner);const o=viewFor(s,owner).anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId===recipient)!;s=act(s,owner,{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r1c1',targetEventId:o.targetEventId,targetId:recipient});expect(s.players[owner]!.hand).not.toEqual(old);expect(s.players[owner]!.hand).toHaveLength(old.length);const a=[...s.players.A!.hand],b=[...s.players.B!.hand];s=settle(s);expect(s.players.A!.hand).toEqual(b);expect(s.players.B!.hand).toEqual(a);expect(s.players.A!.hand).not.toContain(dinonCard);expect(s.players.B!.hand).not.toContain(dinonCard);});
it('dinon-fate actual cancellation consumes source but never swaps or refills either hand',()=>{let s=makeDinonPhysicalScenario('dinon-fate',players);const a=s.players.A!.hand.filter(id=>id!==dinonCard),b=[...s.players.B!.hand];s=act(s,'A',command());const id=Object.values(s.actions!).find(a=>a.cardInstanceId===dinonCard)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.A!.hand).toEqual(a);expect(s.players.B!.hand).toEqual(b);expect(s.discard).toContain(dinonCard);expect(s.phase).toBe('hand-adjustment');});
it('dinon-hidden before START draw other seat astrology missing multiple targets and pending duplicates reject all state and views',()=>{let s=makeDinonPhysicalScenario('dinon-hidden',players,true);reject(s,'A',command());s=act(s,'A',{type:'START_TURN'});reject(s,'A',command());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'B',command());reject(s,'A',{...command(),mode:'astrology'});reject(s,'A',{...command(),targetId:'missing'});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:dinonCard,targetIds:['B','C'],mode:'ordinary'});s=act(s,'A',command());reject(s,'A',command());});
it('dinon-decline actual main pass keeps source and both complete hands',()=>{let s=makeDinonPhysicalScenario('dinon-decline',players);const a=[...s.players.A!.hand],b=[...s.players.B!.hand];s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toEqual(a);expect(s.players.B!.hand).toEqual(b);});
it.each(['dinon-overflow-source','dinon-overflow-target'] as const)('%s actual exchange preserves excess until the receiving player own END adjustment',name=>{let s=makeDinonPhysicalScenario(name,players);s=settle(act(s,'A',command()));const receiver=name==='dinon-overflow-source'?'A':'B';expect(s.players[receiver]!.hand).toHaveLength(8);if(receiver==='B'){s=settle(act(s,'A',{type:'END_TURN',discardIds:[]}));expect(s.players.B!.hand).toHaveLength(8);s=settle(act(s,'B',{type:'START_TURN'}));s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});expect(s.players.B!.hand).toHaveLength(8);s=act(s,'B',{type:'PASS_ACTION'});}reject(s,receiver,{type:'END_TURN',discardIds:[]});const drop=s.players[receiver]!.hand.slice(0,3);s=settle(act(s,receiver,{type:'END_TURN',discardIds:drop}));expect(s.players[receiver]!.hand).toHaveLength(gameStats(s,receiver).handLimit);for(const id of drop)expect(s.discard).toContain(id);});
