import {expect,it} from 'vitest';
import {actionCards} from '@madou/catalog';
import {viewFor,transition,type GameState,type GameCommand, discardIds } from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDispelPhysicalScenario,dispelMode,type DispelPhysicalScenario} from './fixtures/dispel-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p02-r3c1';
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s);}throw Error('DISPEL_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function command(name:DispelPhysicalScenario):GameCommand{const m=dispelMode(name);return {type:'ATTACK',cardInstanceId:actionCards.find(c=>c.id===m.attack||c.name===m.attack)!.id,targetIds:m.multi?['B','C']:['B'],dedicated:m.multi||m.cost,...(m.cost?{advanceCardInstanceIds:['a2-p24-r1c3']}:{}),...(name==='dispel-decline'?{}:{dispel:{cardInstanceId:card,targetId:m.target===2?'C':'B'}})};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['dispel-two','dispel-mixed','dispel-zero','dispel-empty','dispel-multi-b','dispel-multi-c','dispel-hand','dispel-cost'] as const)('%s actual Dispel destroys all placed golems only at chosen target before committed attack and without refill',name=>{let s=makeDispelPhysicalScenario(name,players);const m=dispelMode(name),target=m.target===2?'C':'B',other=target==='B'?'C':'B',original=structuredClone(s.players[target]!),untouched=structuredClone(s.players[other]!.followers),hand=s.players.A!.hand.length,deck=[...s.deck],destroyed=original.followers.filter(f=>['a2-p19-r2c3','a2-p20-r2c3','a2-p22-r1c1'].includes(f.cardInstanceId)),remaining=original.followers.filter(f=>!destroyed.includes(f));s=act(s,'A',command(name));const parent=Object.values(s.actions!).find(a=>a.kind==='attack')!,child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(parent.preAttackPending).toBe(child.id);expect(s.windows!.at(-1)!.continuation.id).toBe(child.id);expect(s.players.A!.hand).toHaveLength(hand-(m.multi?1:m.cost?3:2));expect(s.deck).toEqual(deck);expect(Object.keys(s.groups??{})).toHaveLength(0);expect(viewFor(s,'B').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2')).toBe(false);s=until(s,s=>!s.actions?.[child.id]);expect(s.players[target]!.followers).toEqual(remaining);expect(s.players[other]!.followers).toEqual(untouched);expect(s.players[target]!.hand).toEqual(original.hand);expect(discardIds(s)).toEqual(expect.arrayContaining([card,...destroyed.map(f=>f.cardInstanceId)]));expect(s.reclaimDecisions!.filter(d=>d.source.kind==='ordinary-disposition'&&d.source.trigger==='follower-died').map(d=>d.source.cardInstanceId)).toEqual(destroyed.map(f=>f.cardInstanceId));expect(s.deck).toEqual(deck);for(const id of s.seatOrder){const v=viewFor(s,id);expect(v.logs.filter(e=>e.type==='FOLLOWER_DESTROYED').map(e=>e.cardInstanceId)).toEqual(destroyed.map(f=>f.cardInstanceId));if(id!==target)for(const f of remaining)expect(JSON.stringify(v)).not.toContain(f.cardInstanceId);}if(name==='dispel-hand')for(const id of ['A','C','D'])for(const hidden of ['a2-p19-r2c3','a2-p20-r2c3'])expect(JSON.stringify(viewFor(s,id))).not.toContain(hidden);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(Object.values(s.groups!)).toHaveLength(1);expect(Object.values(s.groups!)[0]!.targets.map(t=>t.actorId)).toEqual(m.multi?['B','C']:['B']);if(m.cost)expect(discardIds(s)).toContain('a2-p24-r1c3');s=settle(s);expect(s.phase).toBe('withdrawal');expect(s.resolution).toEqual([]);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
it('actual Fate cancels Dispel child only without refund refill or destruction and attack still resolves',()=>{let s=makeDispelPhysicalScenario('dispel-fate',players),followers=structuredClone(s.players.B!.followers),hand=s.players.A!.hand.length;s=act(s,'A',command('dispel-fate'));const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(s.players.B!.followers).toEqual(followers);expect(s.players.A!.hand).toHaveLength(hand-2);expect(s.events.filter(e=>e.type==='FOLLOWER_DESTROYED')).toEqual([]);s=settle(s);expect(discardIds(s)).toContain(card);expect(s.phase).toBe('withdrawal');});
it.each(['dispel-parent-cancel','dispel-attack-fate'] as const)('%s actual later attack cancellation does not undo already resolved Dispel destruction',name=>{let s=makeDispelPhysicalScenario(name,players);s=act(s,'A',command(name));const parent=Object.values(s.actions!).find(a=>a.kind==='attack')!,child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>!s.actions?.[child.id]);expect(discardIds(s)).toContain('a2-p19-r2c3');if(name==='dispel-parent-cancel'){s=until(s,s=>viewFor(s,'B').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p02-r2c2'&&o.targetEventId===parent.id));s=act(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r2c2',targetEventId:parent.id});}else{s=until(s,s=>s.windows?.at(-1)?.kind==='declaration'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.id});}s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(1);expect(discardIds(s)).toContain('a2-p19-r2c3');expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
it('actual optional Dispel decline spends only attack and leaves all placed followers at declaration',()=>{let s=makeDispelPhysicalScenario('dispel-decline',players),followers=structuredClone(s.players.B!.followers),hand=s.players.A!.hand.length;s=act(s,'A',command('dispel-decline'));expect(s.players.A!.hand).toHaveLength(hand-1);expect(s.players.A!.hand).toContain(card);expect(s.players.B!.followers).toEqual(followers);expect(Object.values(s.actions!)).toHaveLength(1);s=settle(s);expect(s.players.A!.hand).toContain(card);});
it('actual defender cannot use Dispel as anytime or defense and retains its card',()=>{let s=makeDispelPhysicalScenario('dispel-defense',players);s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'A').anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:card,dedicated:false});reject(s,'A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:viewFor(s,'A').currentAttack!.actionId,targetId:'B'});s=settle(s);expect(s.players.A!.hand).toContain(card);expect(s.players.A!.damage).toBe(4);});
it('actual invalid unlocked self foreign or free-standing Dispel and changing pending attack targets reject atomically',()=>{let s=makeDispelPhysicalScenario('dispel-two',players),c=command('dispel-two');for(const targetId of ['A','C','missing'])reject(s,'A',{...c,dispel:{cardInstanceId:card,targetId}});reject(s,'C',c);reject(s,'A',{...c,cardInstanceId:card});reject(s,'A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:'free',targetId:'B'});s=act(s,'A',c);reject(s,'A',{...c,targetIds:['C'],dispel:{cardInstanceId:card,targetId:'C'}});reject(s,'A',{type:'PASS_ACTION'});s=settle(s);expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
