import { expect,it } from 'vitest';
import * as engine from '../src/index.js';
import { closeWindow, act,finish,pass,ready,until } from './combat-helpers.js';
import { character,entropy,handCard,handCards } from './fixtures.js';

function approach(){let s=ready();const [first,second]=handCards(s,['A','A'],'踏み込み／殴る');const maai=handCard(s,'B','間合い／休息');s=act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:first});s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:maai});s=act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:second});s=act(s,'B',{type:'PASS'});return {s,first,second,maai};}

it('persists a symmetric near distance and the winning physical advance marker',()=>{const {s,first,second,maai}=approach();expect(s.distances.A!.B).toBe('near');expect(s.distances.B!.A).toBe('near');expect(Object.values(s.distanceMarkers!)).toEqual([{a:'A',b:'B',ownerId:'A',cardInstanceId:second}]);expect(engine.viewFor(s,'C').distanceMarkers).toEqual([{a:'A',b:'B',ownerId:'A',cardInstanceId:second}]);expect(s.discard).toEqual(expect.arrayContaining([first,maai]));expect(s.resolution).not.toContain(second);expect(JSON.parse(JSON.stringify(s))).toEqual(s);});

it('keeps a failed approach far and spends both submitted physical cards',()=>{let s=ready();const advance=handCard(s,'A','踏み込み／殴る');const maai=handCard(s,'B','間合い／休息');s=act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:advance});s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:maai});s=act(s,'A',{type:'PASS'});expect(s.distances.A!.B).toBe('far');expect(s.distanceMarkers).toEqual({});expect(s.discard).toEqual(expect.arrayContaining([advance,maai]));});

it('accepts withdrawal, discards the persistent marker, and keeps failed withdrawal near',()=>{let {s,second}=approach();s.phase='withdrawal';const retreat=handCard(s,'A','間合い／休息');s=act(s,'A',{type:'WITHDRAW',targetId:'B',cardInstanceId:retreat});s=act(s,'B',{type:'PASS'});expect(s.distances.A!.B).toBe('far');expect(s.discard).toEqual(expect.arrayContaining([second,retreat]));expect(s.distanceMarkers).toEqual({});
  let failed=approach().s;failed.phase='withdrawal';const [maai,advance]=handCards(failed,['A','B'],'間合い／休息');const push=handCard(failed,'B','踏み込み／蹴る');void advance;failed=act(failed,'A',{type:'WITHDRAW',targetId:'B',cardInstanceId:maai});failed=act(failed,'B',{type:'PLAY_ADVANCE',cardInstanceId:push});failed=act(failed,'A',{type:'PASS'});expect(failed.distances.A!.B).toBe('near');expect(Object.keys(failed.distanceMarkers!)).toHaveLength(1);
});

it('collects all target maai before one attacker advance cancels one from each target',()=>{let s=ready();character(s,'A','侍大将のシン');const attack=handCard(s,'A','天地百撃斬');const [bMaai,cMaai]=handCards(s,['B','C'],'間合い／休息');const advance=handCard(s,'A','踏み込み／蹴る');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==attack);s.players.A!.chants.push({cardInstanceId:attack,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B','C'],dedicated:true},[1]);s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:bMaai});expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});s=act(s,'C',{type:'PLAY_MAAI',cardInstanceId:cMaai});expect(s.windows!.at(-1)!.kind).toBe('defense-advance');s=act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:advance});expect(s.windows!.at(-1)!.kind).toBe('normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'B'});expect(s.discard).toEqual(expect.arrayContaining([bMaai,cMaai,advance]));expect(JSON.parse(JSON.stringify(s))).toEqual(s);});

it('lets one shared hit evade every target when the attacker passes the collected maai',()=>{let s=ready();character(s,'A','侍大将のシン');const attack=handCard(s,'A','天地百撃斬');const [bMaai,cMaai]=handCards(s,['B','C'],'間合い／休息');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==attack);s.players.A!.chants.push({cardInstanceId:attack,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B','C'],dedicated:true},[1]);s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:bMaai});s=act(s,'C',{type:'PLAY_MAAI',cardInstanceId:cMaai});s=act(s,'A',{type:'PASS'});s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);});

it('scopes shared maai to one hit and opens fresh defenses for the next simultaneous hit',()=>{let s=ready();character(s,'A','侍大将のシン');const attack=handCard(s,'A','天地百撃斬');const [bMaai,cMaai]=handCards(s,['B','C'],'間合い／休息');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==attack);s.players.A!.chants.push({cardInstanceId:attack,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B','C'],dedicated:true});s=until(s,'damage');s=closeWindow(s,[2]);s=closeWindow(s);s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:bMaai});s=act(s,'C',{type:'PLAY_MAAI',cardInstanceId:cMaai});s=act(s,'A',{type:'PASS'});expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'B'});s=finish(s);expect(s.players.B!.damage).toBe(7);expect(s.players.C!.damage).toBe(7);});
