import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDragonKingPhysical,dragonKingCard as CARD,dragonKingMaai as MAAI,dragonKingMode} from './fixtures/dragon-king-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=Array(30).fill(1)){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s,dice);}throw Error('DRAGON_KING_LIMIT');}
function settle(s:GameState,dice=Array(30).fill(1)){return until(s,s=>!s.windows?.length,dice);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function end(s:GameState,id:string){if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});return settle(act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)}));}
it.each(['dragon-king-ordinary','dragon-king-owner-ordinary','dragon-king-dedicated','dragon-king-pair','dragon-king-all','dragon-king-near','dragon-king-same-faction','dragon-king-suppressed','dragon-king-silenced'] as const)('%s actual physical declaration preserves eight ten sword values and optional target subset',name=>{let s=makeDragonKingPhysical(name,players);const m=dragonKingMode(name),targets=m.targets.map(i=>s.seatOrder[i]!),hand=[...s.players.A!.hand],deck=[...s.deck],initialRolls=s.rolls?.length??0;expect(s.distances.A!.B).toBe(m.suffix==='near'?'near':'far');if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));if(!m.dedicated)reject(s,'A',cmd(false,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated,targets));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'far',useLevel:8,effectLevel:8,damage:10,attributes:['戦','剣'],target:m.dedicated?'all':'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});if(m.dedicated)expect(group(s).technique).toMatchObject({maaiRequired:2,randomExtraMaai:true,dragonKingHit:true});expect(group(s).targets.map(t=>t.actorId)).toEqual(targets);s=settle(s);for(const id of ['B','C','D']){expect(s.players[id]!.damage).toBe(targets.includes(id)?10:0);expect(s.players[id]!.skipTurns??0).toBe(m.dedicated&&targets.includes(id)?1:0);}expect((s.rolls??[]).slice(initialRolls).filter(r=>r.purpose==='excess-level')).toHaveLength(0);expect((s.rolls??[]).slice(initialRolls).filter(r=>r.purpose==='technique-value')).toHaveLength(m.dedicated?1:0);expect((s.rolls??[]).slice(initialRolls).filter(r=>r.purpose==='hit-resistance')).toHaveLength(m.dedicated?targets.length:0);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);});
it.each([1,2,3,4,5,6] as const)('actual shared numeric die %s sets one plus value for all selected targets without usage checks',face=>{let s=act(makeDragonKingPhysical('dragon-king-all',players,{spirit:0}),'A',cmd(true,['B','C','D']));expect(gameStats(s,'A')).toMatchObject({warrior_level:0,spirit:0});s=until(s,s=>s.rolls?.at(-1)?.purpose==='technique-value',[face]);const roll=s.rolls!.at(-1)!;expect(roll).toMatchObject({rollerId:'A',formula:'d6',faces:[face],total:face,stage:'after-roll'});s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll.id});s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.maaiRequired).toBe(1+face);s=settle(s);expect((s.rolls??[]).filter(r=>r.purpose==='technique-value')).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='excess-level')).toHaveLength(0);for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(10);});
it.each([[0,3,3,true],[12,3,4,false]] as const)('actual target spirit%s rolls %s plus %s against fixed six success=%s and always loses next turn',(spirit,x,y,success)=>{let s=act(makeDragonKingPhysical('dragon-king-pair',players,{targetSpirit:spirit}),'A',cmd(true,['B','C']));s=until(s,s=>s.rolls?.at(-1)?.purpose==='hit-resistance');expect(s.players.B!.skipTurns??0).toBe(0);expect(s.rolls!.at(-1)).toMatchObject({rollerId:'B',checkBase:'fixed',threshold:6,formula:'2d6'});s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({total:x+y,success,threshold:6});expect(viewFor(s,'B').currentRoll).toMatchObject({threshold:6,success});s=until(s,s=>s.rolls?.at(-1)?.rollerId==='C'&&s.rolls?.at(-1)?.purpose==='hit-resistance');s=closeWindow(s,success?[3,4]:[3,3]);s=settle(s);expect(s.players.B!.damage).toBe(success?10:30);expect(s.players.C!.damage).toBe(success?30:10);expect(s.players.B!.skipTurns).toBe(1);expect(s.players.C!.skipTurns).toBe(1);expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance')).toHaveLength(2);s=end(s,'A');for(const id of ['B','C']){const hand=[...s.players[id]!.hand],deck=[...s.deck],rolls=structuredClone(s.rolls),damage=s.players[id]!.damage;s=act(s,id,{type:'START_TURN'});expect(s.phase).toBe('turn-start');expect(s.players[id]!.hand).toEqual(hand);expect(s.deck).toEqual(deck);expect(s.rolls).toEqual(rolls);expect(s.players[id]!.damage).toBe(damage);expect(s.players[id]!.skipTurns).toBe(0);reject(s,id,{type:'CHOOSE_DRAW',draw:true});reject(s,id,{type:'END_TURN',discardIds:[]});}for(const id of ['D','A']){s=settle(act(s,id,{type:'START_TURN'}));s=act(s,id,{type:'CHOOSE_DRAW',draw:false});s=end(s,id);}s=act(s,'B',{type:'START_TURN'});expect(s.phase).toBe('draw');s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});expect(s.phase).toBe('action');});
it.each([[false,true,6],[true,true,6],[true,false,18]] as const)('actual Water follower HP precedes target multiplier dedicated=%s resistance=%s damage%s',(dedicated,success,damage)=>{let s=act(makeDragonKingPhysical(dedicated?'dragon-king-water':'dragon-king-water-ordinary',players),'A',cmd(dedicated));if(dedicated){s=until(s,s=>s.rolls?.at(-1)?.purpose==='hit-resistance');s=closeWindow(s,success?[3,3]:[3,4]);}s=settle(s);expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toEqual([]);expect(discardIds(s)).toContain('a2-p23-r1c1');expect(s.players.B!.skipTurns??0).toBe(dedicated?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);});
it.each([[1,2,true],[2,2,false],[3,4,true],[4,4,false]] as const)('actual Maai die%s paid%s fully avoids=%s and only reached target rolls',(face,paid,avoided)=>{let s=act(makeDragonKingPhysical('dragon-king-maai-full',players),'A',cmd(true,['B','C']));s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities',[face]);expect(group(s).technique.maaiRequired).toBe(1+face);s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');if(avoided)s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:MAAI[0],additionalCardInstanceIds:MAAI.slice(1,paid)});else{reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:MAAI[0],additionalCardInstanceIds:MAAI.slice(1,paid)});for(const id of MAAI.slice(0,paid)){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:id});}}s=settle(s);expect(s.players.B!.damage).toBe(avoided?0:10);expect(s.players.B!.skipTurns??0).toBe(avoided?0:1);expect(s.players.C!.damage).toBe(10);expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance').map(r=>r.rollerId)).toEqual(avoided?['C']:['B','C']);for(const id of MAAI.slice(0,paid))expect(discardIds(s).filter(c=>c===id)).toHaveLength(1);});
it.each(['dragon-king-maai-ordinary','dragon-king-evade-ordinary','dragon-king-evade-dedicated'] as const)('%s actual defense avoids damage and creates no hit resistance or turn loss',name=>{const m=dragonKingMode(name);let s=act(makeDragonKingPhysical(name,players),'A',cmd(m.dedicated));s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=settle(act(s,'B',m.suffix.startsWith('maai')?{type:'PLAY_MAAI',cardInstanceId:MAAI[0]}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.skipTurns??0).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='hit-resistance')).toHaveLength(0);});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior7 spirit6 actual shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeDragonKingPhysical('dragon-king-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?10:0);expect(s.players.B!.skipTurns??0).toBe(0);expect(s.rolls).toHaveLength(1);});
it('actual God rerolls the shared numeric die before defenses and keeps one saved identity',()=>{let s=act(makeDragonKingPhysical('dragon-king-reroll',players),'A',cmd(true,['B','C']));s=until(s,s=>s.rolls?.at(-1)?.purpose==='technique-value',[6]);const rollId=s.rolls!.at(-1)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:rollId});s=until(s,s=>s.rolls!.find(r=>r.id===rollId)?.generation===1,[2]);expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({faces:[2],total:2,generation:1});s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.maaiRequired).toBe(3);s=settle(s);expect((s.rolls??[]).filter(r=>r.purpose==='technique-value')).toHaveLength(1);expect(discardIds(s)).toContain('a2-p02-r1c3');});
it('actual Fate source cancellation precedes numeric die resistance and turn loss',()=>{let s=act(makeDragonKingPhysical('dragon-king-fate',players),'A',cmd(true));const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.skipTurns??0).toBe(0);expect(s.rolls??[]).toHaveLength(0);expect(discardIds(s).filter(c=>c===CARD)).toHaveLength(1);});
it('actual incoming Bow refuses attack-only sword as normal or dedicated defense',()=>{let s=makeDragonKingPhysical('dragon-king-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner malformed targets modes foreign actor and unused timing reject unpaid',()=>{const s=makeDragonKingPhysical('dragon-king-wrong-owner',players,{warrior:8});reject(s,'A',cmd(true));for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(10);let t=makeDragonKingPhysical('dragon-king-decline',players,{beforeStart:true});reject(t,'A',cmd());t=act(t,'A',{type:'START_TURN'});reject(t,'A',cmd());t=act(t,'A',{type:'CHOOSE_DRAW',draw:false});reject(t,'A',{type:'REST',cardInstanceIds:[CARD]});reject(t,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});t=act(t,'A',{type:'PASS_ACTION'});expect(t.players.A!.hand).toContain(CARD);t=makeDragonKingPhysical('dragon-king-stopped',players);expect(t.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(t.seatOrder[t.turnSeat]).not.toBe('A');reject(t,'A',cmd(true));});
