import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDragonCultPhysicalScenario,dragonCultPhysicalMode,type DragonCultPhysicalScenario} from '../../../apps/worker/test/fixtures/dragon-cult-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['cult-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('CULT_FOLK_TURN');}throw Error('CULT_FOLK_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r3c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=dragonCultPhysicalMode(scenario);let s=makeDragonCultPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=dragonCultPhysicalMode(scenario);let s=ready(makeDragonCultPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=dragonCultPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeDragonCultPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=dragonCultPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeDragonCultPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=dragonCultPhysicalMode(scenario);let s=until(incoming(ready(makeDragonCultPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=dragonCultPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeDragonCultPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const CULT='a2-p21-r3c1',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Dragon Cult spirit6 unmodified morale %s precedes all Dwarf6 hits and failure disables all defense',mode=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-higher',players,{spirit:6}),CULT);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',rollerId:'A',modifier:0,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual([0,0,0]);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.discard.filter(id=>id===CULT)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual Dragon Cult surviving ordinary source checks each later group and hidden unreached rear never checks',()=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-setup',players),CULT);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);expect(s.players.A!.damage).toBe(0);
 let q=ready(makeDragonCultPhysicalScenario('cult-setup',players,{spirit:0}),CULT,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',CULT]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([5,6,7])('actual explicit Uonos package freezes follower6 HP0 without morale against Dwarf%i triple hits',level=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-waive',players,{level}),CULT);s=until(dwarf(s),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toContainEqual({cardInstanceId:CULT});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[CULT]});s=until(s,'follower-start');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.levels).toEqual([6,6,6]);s=finish(s);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);expect(s.players.A!.damage).toBe(level===7?18:0);expect(s.players.A!.followers).toHaveLength(level===5?1:0);
});
it('actual Uonos omitted defense package keeps ordinary5 and morale while foreign or duplicate selections reject',()=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-waive',players),CULT);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[CULT,CULT]});s=finish(act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[]}));expect(s.players.A!.damage).toBe(18);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
 s=ready(makeDragonCultPhysicalScenario('cult-setup',players,{owner:'竜皇子アスフェルト'}),CULT);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[CULT]});
});
function priority(s:GameState,id:string){for(let n=0;n<20;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===id)return s;s=pass(s);}throw Error('CULT_PRIORITY');}
function white(s:GameState,level:number){s=next(s);s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p14-r1c3',targetIds:['A'],dedicated:level>=7});if(level===8){s=priority(until(s,'effect-level'),'B');const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p14-r1c3')!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}return s;}
it.each([false,true])('actual White Ring6 7 and Prayer8 use Dragon Cult white7 above dedicated6 when selected=%s',selected=>{
 for(const level of [6,7,8]){let s=ready(makeDragonCultPhysicalScenario('cult-white-lower',players,{spirit:selected?0:14}),CULT);s=until(white(s,level),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[CULT]:[]});s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerDefense![0]!.levels).toEqual([7]);expect(t.followerDefense![0]!.dedicated).toBe(selected);s=finish(s);expect(s.players.A!.damage).toBe(level===8?10:0);expect(s.players.A!.followers).toHaveLength(level===6?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);}
});
it.each([false,true])('actual drawn Blessing adds after the white7 fixed value with Uonos selected=%s',selected=>{
 let s=makeDragonCultPhysicalScenario('cult-white-equal',players,{blessing:true});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:CULT});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=finish(act(s,'A',{type:'CHOOSE_DRAW',draw:true}));expect(gameStats(s,'A').followerLevelBonus).toBe(1);s=until(white(s,7),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[CULT]:[]});s=until(s,'follower-start');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.levels).toEqual([8]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([CULT]);
});
it('actual white magic still requires ordinary morale when Uonos package is omitted',()=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-white-lower',players,{spirit:0}),CULT);s=finish(white(s,6));expect(s.players.A!.damage).toBe(10);expect(s.players.A!.followers).toEqual([]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
const attackRows=['cult-ded-hand','cult-ded-field','cult-grant-hand','cult-grant-field','cult-army'] as const;
function attackCommand(s:GameState,scenario:DragonCultPhysicalScenario,targets?:string[]){const m=dragonCultPhysicalMode(scenario),targetIds=targets??(m.dedicated?['B','C']:['B']);if(m.army)return{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:CULT,targetIds};if(m.grant){const o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:CULT,dedicated:false,targetIds}]};}return{type:'ATTACK' as const,cardInstanceId:CULT,targetIds,dedicated:true};}
it.each(attackRows)('%s actual far spirit black magic6 grants exact targets and shares one 2d6 roll with printed use rules',scenario=>{
 const m=dragonCultPhysicalMode(scenario);for(const magic of m.dedicated?[0,6]:[5,6]){let s=ready(makeDragonCultPhysicalScenario(scenario,players,{magic}),CULT,m.initial);for(const bad of [[],['A'],['B','B']])reject(s,'A',attackCommand(s,scenario,bad));if(!m.dedicated)reject(s,'A',attackCommand(s,scenario,['B','C']));s=act(s,'A',attackCommand(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===CULT)!;expect(a.checks).toHaveLength(m.dedicated?0:6-magic);expect(a.technique).toMatchObject({school:'magic',range:'far',useLevel:6,effectLevel:6,damageFormula:'2d6',noChecks:m.dedicated,attributes:['遠','魔','精','黒'],target:m.dedicated?'all':'one'});expect(a.technique.mandatoryAll??false).toBe(false);expect(a.technique.counterProhibited??false).toBe(false);s=until(s,'damage');s=closeWindow(s,[2,5]);expect(s.rolls!.at(-1)!).toMatchObject({purpose:'attack-damage',faces:[2,5],total:7});s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.actorId)).toEqual(m.dedicated?['B','C']:['B']);expect(g.targets.map(t=>t.hits[0]!.damage)).toEqual(m.dedicated?[7,7]:[7]);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([7,m.dedicated?7:0,0]);expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===CULT)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it.each(['one','all'] as const)('actual dedicated Dragon Cult accepts nonempty arbitrary target subset %s without requiring everyone',mode=>{
 const targets=mode==='one'?['B']:['D','B','C'];
 let s=ready(makeDragonCultPhysicalScenario('cult-ded-hand',players),CULT,false);s=finish(act(s,'A',attackCommand(s,'cult-ded-hand',[...targets])));for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe((targets as readonly string[]).includes(id)?2:0);
});
it('actual Dragon Cult far attack remains legal after approach while Army cannot use a placed source',()=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-ded-hand',players),CULT,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',attackCommand(s,'cult-ded-hand')));expect(['B','C'].map(id=>s.players[id]!.damage)).toEqual([2,2]);s=ready(makeDragonCultPhysicalScenario('cult-army',players),CULT);reject(s,'A',attackCommand(s,'cult-army'));expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===CULT)).toBe(false);
});
it.each(['maai','mirror'] as const)('actual Dragon Cult local %s preserves other target damage and reflection reuses original dice',mode=>{
 let s=ready(makeDragonCultPhysicalScenario('cult-ded-hand',players),CULT,false);s=until(act(s,'A',attackCommand(s,'cult-ded-hand')),'damage');s=closeWindow(s,[2,5]);s=until(s,'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});s=finish(s);expect(['A','B','C','D'].map(id=>s.players[id]!.damage)).toEqual([mode==='mirror'?7:0,0,7,0]);expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.discard.filter(id=>id===CULT)).toHaveLength(1);
});
it('actual Dragon Cult spirit attack passes through physical Metal level6 HP5 without revealing it',()=>{
 let s=makeDragonCultPhysicalScenario('cult-ded-hand',players,{metal:true});s=act(s,'A',{type:'PASS_SETUP'});s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=finish(act(s,'A',attackCommand(s,'cult-ded-hand')));expect(s.players.B!.damage).toBe(2);expect(s.players.B!.followers).toContainEqual(expect.objectContaining({cardInstanceId:'a2-p22-r1c1',revealed:false}));
});
it.each(['hand','field','army-parent','army-child','army-morale','army-use','grant-use','grant'] as const)('actual Dragon Cult %s canceled source or failed roll is consumed once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'cult-army':mode.startsWith('grant')?'cult-grant-field':mode==='field'?'cult-ded-field':'cult-ded-hand';let s=ready(makeDragonCultPhysicalScenario(scenario,players,{magic:5}),CULT,mode==='field'||mode.startsWith('grant'));s=act(s,'A',attackCommand(s,scenario));if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='army-use'||mode==='grant-use'){s=until(s,'before-roll');if(mode==='army-use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:CULT)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');s=priority(s,'D');s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'||mode==='army-use'||mode==='grant-use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.players.A!.followers).toEqual([]);for(const id of army?[CULT,ARMY]:[CULT])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
