import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDragonSpearScenario} from './fixtures/dragon-spear-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p11-r1c1';
const rows=[['dragon-ordinary',false,false,10],['dragon-dedicated',false,true,15],['dragon-chant-ordinary',true,false,10],['dragon-chant-dedicated',true,true,30]] as const;
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState){for(let n=0;n<100;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DRAGON_TURN');}throw Error('DRAGON_TURN_LIMIT');}
function chant(s:GameState){s=act(s,'A',{type:'CHANT',cardInstanceId:card,dedicated:true});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);expect(s.players.A!.hand).not.toContain(card);for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return nextOwn(s);}
function attack(dedicated:boolean){return {type:'ATTACK' as const,cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated};}
function claim(s:GameState){for(let n=0;n<300;n++){const d=viewFor(s,'A').reclaim;if(s.windows?.at(-1)?.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){expect(d.claims.map(c=>c.right)).toContain('base');return act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});}s=pass(s);}throw Error('DRAGON_CLAIM');}
it.each(rows)('%s actual chant=%s elected=%s produces damage%s with exact physical profile and use checks',(scenario,chanted,dedicated,damage)=>{
 for(const level of [5,6]){let s=makeDragonSpearScenario(scenario,players,{level});if(chanted)s=chant(s);s=act(s,'A',attack(dedicated));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(f.technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:dedicated?7:6,damage:dedicated?15:10,attributes:['戦','槍'],destroyAllFollowers:true,chant:false,noChecks:dedicated,target:dedicated?'all':'one'});expect(f.fromChant??false).toBe(chanted);expect(f.checkSpecs).toHaveLength(dedicated?0:6-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([damage,dedicated?damage:0,0]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);expect(s.rolls?.filter(r=>r.purpose==='excess-level').length??0).toBe(dedicated?0:6-level);}
});
it.each(rows)('%s actual chant=%s elected=%s Fate cancels damage%s and paid physical source cannot reuse chant',(scenario,chanted,dedicated,_damage)=>{
 let s=makeDragonSpearScenario(scenario,players);if(chanted)s=chant(s);s=act(s,'A',attack(dedicated));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=pass(s);s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(claim(s));expect(s.players.A!.chants).toEqual([]);expect(s.players.A!.hand.filter(id=>id===card)).toHaveLength(1);expect(s.players.A!.reclaimUsage?.['竜殺天空槍']?.baseSpent).toBe(true);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);s=nextOwn(s);s=finish(act(s,'A',attack(true)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([15,15]);expect(s.players.A!.chants).toEqual([]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
it('Successful actual optional chant disposes and reclaims one source then later unchanted reuse has no double',()=>{
 let s=chant(makeDragonSpearScenario('dragon-chant-dedicated',players));s=finish(claim(act(s,'A',attack(true))));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([30,30]);expect(s.players.A!.chants).toEqual([]);expect(s.players.A!.hand.filter(id=>id===card)).toHaveLength(1);s=nextOwn(s);expect(s.players.C!.revealed).toBe(true);expect(s.players.C!.faction).toBe(s.players.A!.faction);reject(s,'A',attack(true));s=finish(act(s,'A',{...attack(true),targetIds:['B']}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([45,30]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
it.each([false,true] as const)('Dragon dedicated=%s destroys the actually placed Water Dragon before its high-level defense',dedicated=>{
 let s=makeDragonSpearScenario('dragon-ordinary',players,{followers:true});const guards=['B','C'].map(id=>s.players[id]!.followers[0]!.cardInstanceId);s=act(s,'A',attack(dedicated));s=until(s,'follower-start');s=closeWindow(s);const target=Object.values(s.groups!)[0]!.targets[0]!;expect(target.followerDefense![0]!.hits[0]!.outcome).toBe('level-destroyed');s=finish(s);expect(s.players.B!.followers).toEqual([]);expect(s.players.B!.damage).toBe(dedicated?15:10);if(dedicated){expect(s.players.C!.followers).toEqual([]);expect(s.players.C!.damage).toBe(15);expect(s.discard).toEqual(expect.arrayContaining(guards));}else expect(s.players.C!.followers).toHaveLength(1);
});
it('Actual dedicated two-target Dragon permits one target to evade while preserving the other target damage and follower destruction',()=>{
 let s=until(act(makeDragonSpearScenario('dragon-dedicated',players,{followers:true}),'A',attack(true)),'normal-defense');const guard=s.players.B!.followers[0]!;s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,15]);expect(s.players.B!.followers).toEqual([guard]);expect(s.players.C!.followers).toEqual([]);
});
it('Dragon optional chant requires elected Lancaster and ordinary attack rejects multiple targets without payment',()=>{
 const s=makeDragonSpearScenario('dragon-ordinary',players);reject(s,'A',{type:'CHANT',cardInstanceId:card});reject(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:false});const foreign=makeDragonSpearScenario('dragon-dedicated',players,{owner:'侍大将のシン'});reject(foreign,'A',{type:'CHANT',cardInstanceId:card,dedicated:true});reject(foreign,'A',attack(true));
});
