import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeDwarfPhysicalScenario,dwarfPhysicalMode,type DwarfPhysicalScenario} from './fixtures/dwarf-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['dwarf-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p20-r3c1','a2-p05-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('DWARF_TURN');}throw Error('DWARF_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r2c3',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=dwarfPhysicalMode(scenario);let s=makeDwarfPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=dwarfPhysicalMode(scenario);let s=ready(makeDwarfPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=dwarfPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeDwarfPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=dwarfPhysicalMode(scenario);let s=until(incoming(ready(makeDwarfPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=dwarfPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeDwarfPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const DWARF='a2-p21-r2c3',GRIFFIN='a2-p20-r3c1',ARMY='a2-p05-r2c2',BLACK='a2-p20-r1c2';
function priority(s:GameState,id:string){for(let n=0;n<20;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===id)return s;s=pass(s);}throw Error('DWARF_PRIORITY');}
function griffin(s:GameState,boost=false){s=next(s);s=act(s,'B',{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:['A'],dedicated:true});if(boost){s=priority(until(s,'effect-level'),'B');const id=Object.values(s.actions!).find(a=>a.cardInstanceId===GRIFFIN)!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}return s;}
function dwarfAttack(s:GameState,scenario:DwarfPhysicalScenario){const m=dwarfPhysicalMode(scenario);return m.army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:DWARF,targetIds:['B']}:m.grant?grant(s):{type:'ATTACK' as const,cardInstanceId:DWARF,targetIds:['B'],dedicated:true};}
it.each([false,true])('actual Griffin with Prayer=%s compares Dwarf5 and applies HP6 separately to two damage8 hits',boost=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-equal',players),DWARF);s=until(griffin(s,boost),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits.map(h=>[h.technique!.effectLevel,h.damage])).toEqual(Array(2).fill([boost?6:5,8]));expect(f.levels).toEqual([5,5]);expect(f.descriptor).toMatchObject({level:5,hp:6,attributes:['人','小','地']});s=until(s,'hit');const resolved=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(resolved.hits.map(h=>h.hpReduction)).toEqual(boost?[6,6]:[0,0]);s=finish(s);expect(s.players.A!.damage).toBe(boost?4:0);expect(s.discard.filter(id=>id===DWARF)).toHaveLength(1);
});
it.each(['pass','fail'] as const)('actual Dwarf spirit6 minus2 morale %s decides all reached Griffin6 hits once',mode=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-higher',players,{spirit:6}),DWARF);s=until(griffin(s,true),'before-roll');while(s.rolls!.at(-1)!.purpose!=='follower-morale'){s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-2,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,2]:[2,3]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:4,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(2).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(2).fill(mode==='pass'?6:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?4:16);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);expect(s.discard.filter(id=>id===DWARF)).toHaveLength(1);
});
it('actual Dwarf rechecks surviving later groups and hidden rear behind Metal never rolls morale',()=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-setup',players),DWARF);s=finish(incoming(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=finish(griffin(next(s,'B')));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeDwarfPhysicalScenario('dwarf-setup',players,{spirit:0}),DWARF,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',DWARF]});q=finish(griffin(q,true));expect(q.players.A!.damage).toBe(0);expect(q.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:DWARF,revealed:false}));expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([false,true])('actual explicit Ramba package=%s waives morale at spirit0 without changing Dwarf5 HP6',selected=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-waive',players),DWARF);s=until(griffin(s,true),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DWARF,DWARF]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[DWARF]:[]});s=until(s,'follower-start');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.levels).toEqual([5,5]);s=finish(s);expect(s.players.A!.damage).toBe(selected?4:16);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);
});
it('actual foreign owner cannot select the Dwarf Ramba defensive package',()=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-equal',players,{owner:'竜皇子アスフェルト'}),DWARF);s=until(griffin(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[DWARF]});
});
it.each(['dwarf-ded-hand','dwarf-ded-field','dwarf-grant-hand','dwarf-grant-field','dwarf-army'] as const)('%s actual far warrior axe freezes current warrior level with checks retained and three damage6 hits at one target',scenario=>{
 const m=dwarfPhysicalMode(scenario);for(const warrior of [0,3,4,5,8]){let s=ready(makeDwarfPhysicalScenario(scenario,players,{warrior}),DWARF,m.initial);s=act(s,'A',dwarfAttack(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===DWARF)!;expect(a.checks).toEqual([]);expect(a.technique).toMatchObject({range:'far',school:'warrior',useLevel:warrior,effectLevel:warrior,damage:6,attributes:['遠','戦','斧'],noChecks:false,hitCount:3,target:'one'});s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>[t.actorId,t.hits.length])).toEqual([['B',3]]);expect(g.targets[0]!.hits.map(h=>[(h.technique??g.technique).effectLevel,h.damage])).toEqual(Array(3).fill([warrior,6]));s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([18,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===DWARF)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it.each([3,4,5])('actual Dwarf warrior%s hits Black Knights4 HP5 three times without lumping damage',warrior=>{
 let s=makeDwarfPhysicalScenario('dwarf-ded-hand',players,{warrior});s=act(s,'A',{type:'PASS_SETUP'});s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:BLACK});for(const id of ['B','C','D'])s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(act(s,'A',dwarfAttack(s,'dwarf-ded-hand')),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerDefense![0]!.levels).toEqual([4,4,4]);s=finish(s);expect(s.players.B!.damage).toBe(warrior>4?3:0);expect(s.players.B!.followers).toHaveLength(warrior<4?1:0);expect(s.discard.filter(id=>id===BLACK)).toHaveLength(warrior<4?0:1);
});
it.each(['maai','mirror'] as const)('actual Dwarf first-hit %s still permits remaining two independent follower defenses',mode=>{
 let s=makeDwarfPhysicalScenario('dwarf-ded-hand',players);s=act(s,'A',{type:'PASS_SETUP'});s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:BLACK});for(const id of ['B','C','D'])s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(act(s,'A',dwarfAttack(s,'dwarf-ded-hand')),'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,2]);expect(s.discard.filter(id=>id===DWARF)).toHaveLength(1);expect(s.discard.filter(id=>id===BLACK)).toHaveLength(1);
});
it.each(['dwarf-ded-hand','dwarf-grant-hand','dwarf-army'] as const)('%s rejects empty self duplicate or split targets and remains legal after actual approach',scenario=>{
 let s=ready(makeDwarfPhysicalScenario(scenario,players),DWARF,false);for(const targetIds of [[],['A'],['B','B'],['B','C']]){const command=dwarfAttack(s,scenario);reject(s,'A',command.type==='USE_FOLLOWER_ATTACK'?{...command,sources:command.sources.map(source=>({...source,targetIds}))}:{...command,targetIds});}s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',dwarfAttack(s,scenario)));expect(s.players.B!.damage).toBe(18);
});
it('actual Army cannot pay a placed Dwarf without its distinct hand permission',()=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-army',players),DWARF);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===DWARF)).toBe(false);reject(s,'A',dwarfAttack(s,'dwarf-army'));
});
it.each(['hand','field','army-parent','army-child','army-morale','grant'] as const)('actual Dwarf %s cancellation or morale failure consumes every paid source once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'dwarf-army':mode==='grant'?'dwarf-grant-field':mode==='field'?'dwarf-ded-field':'dwarf-ded-hand';let s=ready(makeDwarfPhysicalScenario(scenario,players),DWARF,mode==='field'||mode==='grant');s=act(s,'A',dwarfAttack(s,scenario));if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'){s=until(s,'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-2});}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:DWARF)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');s=priority(s,'D');s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of army?[DWARF,ARMY]:[DWARF])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it('actual Peace replacement draw opens Blood after Dwarf declaration but keeps all three hits at the saved warrior level',()=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-ded-hand',players,{warrior:4,blood:true}),DWARF,false);expect(gameStats(s,'A').warrior_level).toBe(4);s=act(s,'A',dwarfAttack(s,'dwarf-ded-hand'));const actionId=Object.values(s.actions!).find(a=>a.cardInstanceId===DWARF)!.id;s=priority(s,'A');const o=viewFor(s,'A').anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p02-r1c1'&&o.targetId==='B')!;expect(o).toBeDefined();s=act(s,'A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:o.cardInstanceId,targetEventId:o.targetEventId,targetId:o.targetId!});s=until(s,'normal-defense');expect(s.players.A!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'A').warrior_level).toBe(5);expect(s.actions![actionId]!.technique).toMatchObject({useLevel:4,effectLevel:4});const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.hits.map(h=>(h.technique??g.technique).effectLevel)).toEqual([4,4,4]);s=finish(s);expect(s.players.B!.damage).toBe(18);expect(s.discard.filter(id=>id===DWARF)).toHaveLength(1);
});
it('actual Prayer adds after Dwarf warrior declaration while saved use4 and each independent damage6 remain unchanged',()=>{
 let s=ready(makeDwarfPhysicalScenario('dwarf-ded-hand',players,{warrior:4,prayer:true}),DWARF,false);s=priority(until(act(s,'A',dwarfAttack(s,'dwarf-ded-hand')),'effect-level'),'A');const id=Object.values(s.actions!).find(a=>a.cardInstanceId===DWARF)!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});s=until(s,'normal-defense');expect(gameStats(s,'A').warrior_level).toBe(4);const g=Object.values(s.groups!)[0]!;expect(g.technique).toMatchObject({useLevel:4,effectLevel:5,damage:6,hitCount:3});expect(s.actions![id]!.checks).toEqual([]);s=finish(s);expect(s.players.B!.damage).toBe(18);
});
