import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeFactionCastlesPhysicalScenario,factionCastlesPhysicalMode,type FactionCastlesPhysicalScenario} from '../../../apps/worker/test/fixtures/faction-castles-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['alkemia-setup','gainas-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('FACTION_CASTLES_TURN');}throw Error('FACTION_CASTLES_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p20-r3c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);let s=makeFactionCastlesPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);let s=ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeFactionCastlesPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);let s=until(incoming(ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual incompatible owner may hold the castle but neither setup nor own action can place it',scenario=>{
 const m=factionCastlesPhysicalMode(scenario),owner=m.good?'魔聖母ディア':'白魔術師シェリム';let s=makeFactionCastlesPhysicalScenario(scenario,players,{owner});expect(s.players.A!.hand).toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=ready(s,m.card,false);reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});expect(s.players.A!.hand).toContain(m.card);expect(s.discard).not.toContain(m.card);
});
it.each(rows)('%s actual castle without attack bottom refuses Army even with both cards in hand and refuses dedicated attack or chant',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);for(const initial of [false,true]){const s=ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card,initial);expect(s.players.A!.hand).toContain('a2-p05-r2c2');if(!initial)expect(s.players.A!.hand).toContain(m.card);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===m.card)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});
it.each(['alkemia-convert','gainas-convert'] as const)('%s actual public conversion immediately reveals and discards the incompatible castle but keeps an unplaced castle in hand',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card,initial);s=act(s,'A',{type:'REVEAL_CHARACTER'});s=next(s);s=act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceId:m.conversion,targetId:'A',mode:'ordinary'});s=until(s,'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'faction-change',rollerId:'A',modifier:-1});expect(s.players.A!.faction).toBe(m.faction);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(initial?[m.card]:[]);s=finish(s);expect(s.players.A!.faction).toBe(m.good?'EVIL':'GOOD');expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(initial?1:0);if(!initial){expect(s.players.A!.hand).toContain(m.card);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else{expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard).toContain(m.card);for(const id of s.seatOrder)expect(viewFor(s,id).discardCount).toBe(s.discard.length);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.players.A!.damage).toBe(4);}}
});
it.each(['alkemia-convert','gainas-convert'] as const)('%s actual canceled conversion preserves castle and faction without leaking the physical source',scenario=>{
 const m=factionCastlesPhysicalMode(scenario);let s=ready(makeFactionCastlesPhysicalScenario(scenario,players),m.card);s=act(s,'A',{type:'REVEAL_CHARACTER'});s=next(s);s=act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceId:m.conversion,targetId:'A',mode:'ordinary'});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===m.conversion)!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.A!.faction).toBe(m.faction);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);expect(s.discard.filter(id=>id===m.conversion)).toHaveLength(1);expect(s.discard).not.toContain(m.card);
});
it.each([false,true])('actual Alseil explicit Gainas Castle level6 choice=%s compares each Dwarf hit without changing HP5',dedicated=>{
 for(const level of [5,6,7]){let s=ready(makeFactionCastlesPhysicalScenario('gainas-dedicated',players,{level}),'a2-p20-r3c3');s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=until(act(s,'B',grant(s,'B','a2-p21-r2c3')),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toContainEqual({cardInstanceId:'a2-p20-r3c3'});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:dedicated?['a2-p20-r3c3']:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.levels).toEqual(Array(3).fill(dedicated?6:5));expect(f.descriptor.hp).toBe(5);s=finish(s);expect(s.players.A!.damage).toBe(level>(dedicated?6:5)?3:0);expect(s.players.A!.followers).toHaveLength(level<(dedicated?6:5)?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);}
});
it('actual foreign Evil owner cannot select Alseil castle level6 and Alseil loses placement after real conversion',()=>{
 let s=ready(makeFactionCastlesPhysicalScenario('gainas-setup',players,{owner:'黒騎士ガーウィン'}),'a2-p20-r3c3');s=until(incoming(s),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toEqual([]);reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:['a2-p20-r3c3']});s=finish(s);expect(s.players.A!.followers).toHaveLength(1);
 let q=ready(makeFactionCastlesPhysicalScenario('gainas-convert',players),'a2-p20-r3c3',false);q=act(q,'A',{type:'REVEAL_CHARACTER'});q=next(q);q=finish(act(q,'B',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r1c1',targetId:'A',mode:'ordinary'}));q=next(q,'A');expect(q.players.A!.faction).toBe('GOOD');expect(q.players.A!.hand).toContain('a2-p20-r3c3');reject(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p20-r3c3']});
});
