import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeFemaleGuardPhysicalScenario,femaleGuardPhysicalMode,type FemaleGuardPhysicalScenario} from '../../../apps/worker/test/fixtures/female-guard-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['female-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('FEMALE_GUARD_TURN');}throw Error('FEMALE_GUARD_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r2c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);let s=makeFemaleGuardPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);let s=ready(makeFemaleGuardPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeFemaleGuardPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeFemaleGuardPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);let s=until(incoming(ready(makeFemaleGuardPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeFemaleGuardPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const FEMALE='a2-p21-r2c2',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Female Guard spirit6 morale %s applies one group result and HP4 to each reached Dwarf6 hit',mode=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-higher',players,{spirit:6}),FEMALE);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:0,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(mode==='pass'?4:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?6:18);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);
});
it('actual surviving Female Guard rechecks each later group while unreached hidden rear never checks',()=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-setup',players),FEMALE);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeFemaleGuardPhysicalScenario('female-setup',players,{spirit:0}),FEMALE,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',FEMALE]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([false,true])('actual explicit Arnes physical package=%s waives morale at spirit0 but leaves printed5 HP4 unchanged',selected=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-waive',players),FEMALE);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[FEMALE,FEMALE]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[FEMALE]:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');expect(f.levels).toEqual([5,5,5]);s=finish(s);expect(s.players.A!.damage).toBe(selected?6:18);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);
});
it.each(['female-ignore','female-ignore-decline','female-sky','female-sky-decline'] as const)('%s actual Arnes selection cancels whole-column generic or sky-attribute ignore only for its owner',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);let s=makeFemaleGuardPhysicalScenario(scenario,players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.front});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:FEMALE});s=next(ready(s,FEMALE,false));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p21-r1c1',targetIds:['A','C'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:m.special?[FEMALE]:[]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!;expect(t.followerIgnoreCancelled??false).toBe(m.special);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===FEMALE)!.dedicated).toBe(m.special);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.sky?[m.special?5:8,12]:[m.special?0:5,5]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.sky?1:0);if(m.ignore){expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.front,FEMALE]);expect(s.players.A!.followers[1]!.revealed).toBe(m.special);}else{expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.special?[]:[m.front]);}
});
it('actual foreign owner cannot select Female Guard package and actual explicit destruction remains effective against Arnes package',()=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-setup',players,{owner:'竜皇子アスフェルト'}),FEMALE);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[FEMALE]});
 s=next(ready(makeFemaleGuardPhysicalScenario('female-destroy',players),FEMALE));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p13-r1c2',targetIds:['A'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[FEMALE]});s=until(s,'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits[0]!.outcome).toBe('level-destroyed');s=finish(s);expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);expect(s.players.A!.damage).toBe(0);
});
it('actual Lester human invalidation disables physical Female Guard cancellation so Wight Army bypasses both it and front Metal',()=>{
 let s=makeFemaleGuardPhysicalScenario('female-invalid',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:FEMALE});s=next(ready(s,FEMALE,false));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=until(act(s,'B',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:'a2-p21-r1c1',targetIds:['A']}),'attack-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c1-ab02')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,abilityEffectIds:['human-invalidation']});s=until(s,'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[FEMALE]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerIgnoreCancelled??false).toBe(false);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===FEMALE)!.ineffective).toBe(true);s=finish(s);expect(s.players.A!.damage).toBe(5);expect(s.players.A!.followers.every(f=>!f.revealed)).toBe(true);
});
it.each([false,true])('actual Arnes virtual guard=%s remains distinct from physical Female Guard HP4 and one physical discard',virtual=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-waive',players),FEMALE);s=until(dwarf(s),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[FEMALE]});if(virtual){s=until(s,'follower-entry-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='A')s=pass(s);const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c2-ab02')!;s=act(s,'A',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});}s=until(s,'follower-start');const fs=Object.values(s.groups!)[0]!.targets[0]!.followerDefense!;expect(fs.map(f=>f.source)).toEqual(virtual?['virtual','physical']:['physical']);expect(fs.filter(f=>f.source==='physical')).toHaveLength(1);s=finish(s);expect(s.players.A!.damage).toBe(virtual?3:6);expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);
});
function femaleAttack(s:GameState,scenario:FemaleGuardPhysicalScenario){const m=femaleGuardPhysicalMode(scenario);return m.army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:FEMALE,targetIds:['B']}:m.grant?grant(s):{type:'ATTACK' as const,cardInstanceId:FEMALE,targetIds:['B'],dedicated:true};}
it.each(['female-ded-hand','female-ded-field','female-grant-hand','female-grant-field','female-army'] as const)('%s actual far magic bow4damage6 uses magic not warrior for checks with explicit permission and single target',scenario=>{
 const m=femaleGuardPhysicalMode(scenario);for(const magic of [3,4]){let s=ready(makeFemaleGuardPhysicalScenario(scenario,players,{magic,warrior:magic===4?0:20}),FEMALE,m.initial);if(m.dedicated)reject(s,'A',{type:'ATTACK',cardInstanceId:FEMALE,targetIds:['B','C'],dedicated:true});s=act(s,'A',femaleAttack(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===FEMALE)!;expect(a.checks).toHaveLength(4-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:4,effectLevel:4,damage:6,attributes:['遠','魔','弓'],noChecks:false,hitCount:1,target:'one'});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([6,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it('actual Female Guard far attack remains legal after approach and Army cannot pay a placed source',()=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-ded-hand',players),FEMALE,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',femaleAttack(s,'female-ded-hand')));expect(s.players.B!.damage).toBe(6);s=ready(makeFemaleGuardPhysicalScenario('female-army',players),FEMALE);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===FEMALE)).toBe(false);reject(s,'A',femaleAttack(s,'female-army'));
});
it.each(['maai','mirror'] as const)('actual Female Guard magic bow is defendable by %s and spent physical source never returns',mode=>{
 let s=ready(makeFemaleGuardPhysicalScenario('female-ded-hand',players),FEMALE,false);s=until(act(s,'A',femaleAttack(s,'female-ded-hand')),'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([mode==='mirror'?6:0,0]);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===FEMALE)).toHaveLength(1);
});
it.each(['hand','field','army-parent','army-child','army-morale','army-use','use','grant'] as const)('actual Female Guard %s cancellation or failed roll consumes paid source once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'female-army':mode==='grant'?'female-grant-field':mode==='field'?'female-ded-field':'female-ded-hand';let s=ready(makeFemaleGuardPhysicalScenario(scenario,players,{magic:3}),FEMALE,mode==='field'||mode==='grant');s=act(s,'A',femaleAttack(s,scenario));if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='army-use'||mode==='use'){s=until(s,'before-roll');if(mode==='army-use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:FEMALE)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'||mode==='army-use'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of army?[FEMALE,ARMY]:[FEMALE])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
