import {describe,it,expect} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
const ARNES='c2-p03-r2c2-ab02',LESTER='c2-p03-r2c1-ab02',TIA='c2-p02-r1c1-ab02';
function priority(s:GameState,id:string){for(let n=0;n<30;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===id)return s;s=pass(s);}throw Error('PRIORITY');}
function use(s:GameState,actor:string,id:string,extra:Record<string,unknown>={}){s=priority(s,actor);const o=viewFor(s,actor).abilityOptions.find(o=>o.abilityId===id);expect(o).toBeDefined();return act(s,actor,{type:'USE_ABILITY',abilityId:id,targetEventId:o!.targetEventId,...extra});}
function placed(s:GameState,actor:string,name:string){const id=handCard(s,actor,name);s.players[actor]!.hand=s.players[actor]!.hand.filter(x=>x!==id);s.players[actor]!.followers.push({cardInstanceId:id,revealed:false});return id;}
function attack(s:GameState,name='衝破',targets=['B'],dedicated=false){const id=handCard(s,'A',name);return act(s,'A',{type:'ATTACK',cardInstanceId:id,targetIds:targets,dedicated});}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as any,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
function arnes(){const s=ready();character(s,'B','黒妖精のアーネス');return s;}
function target(s:GameState){return Object.values(s.groups!)[0]!.targets[0]!;}
describe('Task7m follower entry',()=>{
 it('opens public pre-snapshot entry after normal defense even without followers or eligible private options',()=>{let s=until(attack(ready()),'normal-defense');s=act(s,'B',{type:'START_FOLLOWERS'});expect(s.windows!.at(-1)).toMatchObject({kind:'follower-entry-abilities',participants:['A','B','C','D']});expect(target(s).followerSnapshot).toBeNull();expect(viewFor(s,'A').followerEntry).toMatchObject({targetId:'B',reason:'before-follower-snapshot'});reject(s,'B',{type:'START_FOLLOWERS'});s=finish(s);});
 it('declines Arnes by default and generates no physical or virtual source',()=>{let s=until(attack(arnes()),'follower-start');expect(target(s).followerDefense).toEqual([]);s=finish(s);});
 it('accepts hidden Arnes with no cost and freezes exact Lv4 HP1 morale-free virtual source before two physical slots',()=>{let s=arnes();placed(s,'B','兵士');placed(s,'B','ウッドゴーレム');s=until(attack(s),'follower-entry-abilities');s=use(s,'B',ARNES);expect(JSON.stringify(viewFor(s,'A'))).not.toContain('c2-p03-r2c2');expect(viewFor(s,'A').currentAction).toMatchObject({label:'特殊能力'});s=closeWindow(s);s=until(s,'follower-start');expect(target(s).followerDefense![0]).toMatchObject({source:'virtual',position:-1,levels:[4],descriptor:{level:4,hp:1,attributes:['人','女'],moraleRequired:false,cancelIgnore:true}});expect(target(s).followerSnapshot).toHaveLength(2);expect(viewFor(s,'A').virtualFollowerDefense).toHaveLength(1);expect(s.players.B!.revealed).toBe(false);s=finish(s);});
 it('Lester spirit branch retains warrior school and existing attributes',()=>{let s=arnes();character(s,'A','吟遊詩人のレスター');s=until(attack(s,'踏み込み／弓'),'attack-abilities');s=use(s,'A',LESTER,{abilityEffectIds:['spirit-conversion']});s=closeWindow(s);s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect((g.targets[0]!.hits[0]!.technique??g.technique)).toMatchObject({school:'warrior',attributes:expect.arrayContaining(['精'])});expect(viewFor(s,'A').currentAction).toMatchObject({technique:{school:'warrior',attributes:expect.arrayContaining(['精'])}});s=finish(s);});
 it('Tia entry consumes only advance hand cost without refund, replacement draw or distance change',()=>{let s=ready();character(s,'A','有翼人のティア');s=act(s,'A',{type:'REVEAL_CHARACTER'});placed(s,'B','兵士');const cost=handCard(s,'A','踏み込み／殴る');const maai=handCard(s,'A','間合い／休息');s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');const hand=s.players.A!.hand.length,distances=structuredClone(s.distances);const option=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===TIA)!;expect(option).toBeDefined();expect(option.costCardInstanceIds).toContain(cost);expect(option.costCardInstanceIds).not.toContain(maai);reject(s,'A',{type:'USE_ABILITY',abilityId:TIA,targetEventId:option.targetEventId,costCardInstanceId:maai});s=use(s,'A',TIA,{costCardInstanceId:cost});expect(s.players.A!.hand).toHaveLength(hand-1);expect(s.discard).toContain(cost);expect(s.distances).toEqual(distances);s=finish(s);expect(s.players.B!.followers).toHaveLength(1);});
});

function cancelAbility(s:GameState,by:string,card:string){s=priority(s,by);s=act(s,by,{type:'PLAY_REACTION',cardInstanceId:card,mode:'cancel-ability',targetAbilityId:viewFor(s,by).reactionTargetAbilityId!});s=closeWindow(s);return closeWindow(s);}
function disabled(s:GameState,actor:string,kind:'stopped'|'ability-disabled'){s.players[actor]!.statuses=[{id:'restriction',kind,modifiers:[0],nextCheck:0}];}
function illusion(s:GameState,effects:string[],name='気斬'){character(s,'A','吟遊詩人のレスター');s=until(attack(s,name),'attack-abilities');s=use(s,'A',LESTER,{abilityEffectIds:effects});return closeWindow(s);}
function diaDwarves(s:GameState){character(s,'A','魔聖母ディア');s.players.A!.permanent={warrior_level:6};s.players.B!.permanent={endurance:100};s.distances.A!.B='near';s.distances.B!.A='near';const card=handCard(s,'A','小人族');const o=viewFor(s,'A').followerBundleOptions[0]!;return act(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:['B']}]});}

describe('Task7m virtual guard lifetime and restrictions',()=>{
 it.each([false,true])('same one guard reduces all actual Dia Dwarf hits by HP1 with Blessing=%s',blessing=>{let s=arnes();if(blessing){const id=handCard(s,'B','祝福');s.players.B!.hand=s.players.B!.hand.filter(x=>x!==id);s.players.B!.open.push(id);}s=until(diaDwarves(s),'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');const source=target(s).followerDefense![0]!;expect(source.levels).toEqual(Array(3).fill(blessing?5:4));const frozenId=source.source==='virtual'?source.sourceId:'';s=closeWindow(s);expect(target(s).followerDefense![0]).toMatchObject({sourceId:frozenId,hits:[{hitIndex:0,outcome:'lower-destroyed',hpReduction:1},{hitIndex:1,outcome:'lower-destroyed',hpReduction:1},{hitIndex:2,outcome:'lower-destroyed',hpReduction:1}]});expect(target(s).hits.map(h=>h.damage)).toEqual([5,5,5]);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);expect(s.discard).not.toContain(frozenId);s=finish(s);expect(s.players.B!.damage).toBe(15);expect(viewFor(s,'A').virtualFollowerDefense).toEqual([]);expect(s.players.B!.followers).toEqual([]);});
 it('guard cancellation keeps event attempt spent and parent context through child reaction',()=>{let s=arnes();const fate=handCard(s,'C','命運凶変');s=until(attack(s),'follower-entry-abilities');s=use(s,'B',ARNES);const f=Object.values(s.abilities!)[0]!;const entry=viewFor(s,'C').followerEntry;expect(entry).toMatchObject({targetId:'B'});s=priority(s,'C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:f.id});expect(viewFor(s,'C').followerEntry).toEqual(entry);s=closeWindow(s);s=closeWindow(s);s=priority(s,'B');expect(viewFor(s,'B').abilityOptions).not.toContainEqual(expect.objectContaining({abilityId:ARNES}));reject(s,'B',{type:'USE_ABILITY',abilityId:ARNES,targetEventId:f.eventId});s=until(s,'follower-start');expect(target(s).followerDefense).toEqual([]);s=finish(s);});
 it.each(['stopped','ability-disabled'] as const)('guard has no option/activation while %s and rechecks before snapshot',kind=>{let s=arnes();s=until(attack(s),'follower-entry-abilities');s=priority(s,'B');const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===ARNES)!;const blocked=structuredClone(s);disabled(blocked,'B',kind);expect(viewFor(blocked,'B').abilityOptions).toEqual([]);reject(blocked,'B',{type:'USE_ABILITY',abilityId:ARNES,targetEventId:o.targetEventId});s=use(s,'B',ARNES);s=closeWindow(s);disabled(s,'B',kind);s=until(s,'follower-start');expect(target(s).followerDefense).toEqual([]);s=finish(s);});
 it('a frozen guard continues after later disable and never appears in physical attack/transfer inventories',()=>{let s=until(attack(arnes(),'魔衝破'),'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');const guard=viewFor(s,'B').virtualFollowerDefense[0]!;disabled(s,'B','ability-disabled');const v=viewFor(s,'B');for(const options of [v.followerAttackOptions,v.followerPlacementOptions,v.additionalAttackOptions,v.followerBundleOptions,v.self.hand,v.self.followers])expect(JSON.stringify(options)).not.toContain(guard.sourceId);s=closeWindow(s);expect(target(s).hits[0]!.damage).toBe(6);expect(target(s).followerDefense![0]!.hits[0]!.hpReduction).toBe(1);s=finish(s);});
 it('actual reflected child group can generate a fresh Arnes guard and parent snapshot never reopens entry',()=>{let s=ready();character(s,'A','黒妖精のアーネス');character(s,'B','リーア姫');placed(s,'B','王立騎士団');s=until(attack(s,'踏み込み／弓'),'normal-defense');const royal=s.players.B!.followers[0]!.cardInstanceId;s=act(s,'B',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[royal]});s=until(s,'follower-start');s=closeWindow(s);expect(Object.values(s.groups!)).toHaveLength(2);s=until(s,'follower-entry-abilities');expect(viewFor(s,'A').followerEntry).toMatchObject({targetId:'A',attackerId:'B'});s=use(s,'A',ARNES);s=closeWindow(s);s=until(s,'follower-start');expect(viewFor(s,'A').virtualFollowerDefense).toHaveLength(1);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.B!.damage).toBe(0);});
});

describe('Task7m independent Lester branches',()=>{
 it('no qualifying source offers only human invalidation and suppression; malformed, stale and unowned use is atomic',()=>{let s=arnes();character(s,'A','吟遊詩人のレスター');s=until(attack(s,'気斬'),'attack-abilities');const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===LESTER)!;expect(o.effectOptions!.map(e=>e.id)).toEqual(['human-invalidation','arnes-suppression']);const base={type:'USE_ABILITY',abilityId:LESTER,targetEventId:o.targetEventId};for(const patch of [{},{abilityEffectIds:[]},{abilityEffectIds:['spirit-conversion']},{abilityEffectIds:['human-invalidation','human-invalidation']},{abilityEffectIds:['other']},{abilityEffectIds:['arnes-suppression'],targetEventId:'stale'},{abilityEffectIds:['arnes-suppression'],abilityId:ARNES},{abilityEffectIds:['human-invalidation'],costCardInstanceId:s.players.A!.hand[0]},{abilityEffectIds:['human-invalidation'],conceal:false}])reject(s,'A',{...base,...patch});s=finish(s);});
 it('physical human invalidation suppresses its own column ignore cancellation and does not reveal, morale, destroy or revive it',()=>{let s=arnes();const human=placed(s,'B','親衛隊'),front=placed(s,'B','ウッドゴーレム');s.players.B!.followers.reverse();s=illusion(s,['human-invalidation']);s=until(s,'follower-start');expect(target(s).followerDefense!.find(d=>d.source==='physical'&&d.cardInstanceId===human)).toMatchObject({ineffective:true});s=closeWindow(s);expect(target(s).followerIgnoreCancelled).not.toBe(true);expect(target(s).followerDefense!.flatMap(d=>d.hits).every(h=>h.outcome==='passed-through')).toBe(true);s=finish(s);expect(s.players.B!.followers).toEqual([{cardInstanceId:front,revealed:false},{cardInstanceId:human,revealed:false}]);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);expect(s.discard).not.toContain(human);expect(s.players.B!.damage).toBe(8);});
 it.each([false,true])('suppression resolves from public Arnes identity at snapshot (revealed=%s), never erases physical women guard',revealed=>{let s=arnes();const physical=placed(s,'B','女性親衛隊');s=illusion(s,['arnes-suppression']);s=until(s,'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);if(revealed)s=act(s,'B',{type:'REVEAL_CHARACTER'});s=until(s,'follower-start');expect(target(s).followerDefense!.filter(d=>d.source==='virtual')).toHaveLength(revealed?0:1);expect(target(s).followerSnapshot).toEqual([physical]);s=closeWindow(s);expect(target(s).followerIgnoreCancelled).toBe(revealed?undefined:true);if(revealed)expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toContain(physical);s=finish(s);});
 it('hidden guard cancellation protection cannot revive an invalid physical human',()=>{let s=arnes();const human=placed(s,'B','親衛隊');s=illusion(s,['human-invalidation','arnes-suppression']);s=until(s,'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');s=closeWindow(s);expect(target(s).followerIgnoreCancelled).toBe(true);expect(target(s).hits[0]!.damage).toBe(7);expect(target(s).followerDefense!.find(d=>d.source==='physical')).toMatchObject({ineffective:true,hits:[{hitIndex:0,outcome:'passed-through',hpReduction:0}]});s=finish(s);expect(s.players.B!.followers).toEqual([{cardInstanceId:human,revealed:false}]);});
 it('conversion retains exact original warrior values and attributes, deduplicates spirit, and passes Wood Golem',()=>{let s=arnes();character(s,'A','吟遊詩人のレスター');placed(s,'B','ウッドゴーレム');s=until(attack(s,'踏み込み／弓'),'attack-abilities');const original=structuredClone(Object.values(s.groups!)[0]!.technique);s=use(s,'A',LESTER,{abilityEffectIds:['spirit-conversion']});s=closeWindow(s);s=until(s,'normal-defense');expect(target(s).hits[0]!.technique).toEqual({...original,attributes:[...original.attributes,'精']});s=finish(s);expect(s.players.B!.damage).toBe(4);expect(s.players.B!.followers).toHaveLength(1);
  let q=arnes();character(q,'A','吟遊詩人のレスター');q.players.A!.permanent={magic_level:1};q=until(attack(q,'気斬'),'attack-abilities');q=use(q,'A',LESTER,{abilityEffectIds:['spirit-conversion']});q=closeWindow(q);expect(target(q).hits[0]!.technique!.attributes.filter(a=>a==='精')).toHaveLength(1);q=finish(q);
 });
 it.each(['stopped','ability-disabled'] as const)('Lester %s before entry suppresses new follower modifiers',kind=>{let s=arnes();placed(s,'B','親衛隊');s=illusion(s,['human-invalidation','arnes-suppression']);s=until(s,'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);disabled(s,'A',kind);s=act(s,'B',{type:'REVEAL_CHARACTER'});s=until(s,'follower-start');expect(target(s).physicalHumansInvalid).toBe(false);expect(target(s).followerDefense!.filter(d=>d.source==='virtual')).toHaveLength(1);s=finish(s);});
 it('one cancellation frame cancels the whole selected set without undoing remaining attack',()=>{let s=arnes();character(s,'A','吟遊詩人のレスター');const human=placed(s,'B','兵士');const fate=handCard(s,'B','命運凶変');s=until(attack(s,'踏み込み／弓'),'attack-abilities');const original=structuredClone(Object.values(s.groups!)[0]!.technique);s=use(s,'A',LESTER,{abilityEffectIds:['spirit-conversion','human-invalidation','arnes-suppression']});expect(Object.values(s.abilities!)).toHaveLength(1);s=cancelAbility(s,'B',fate);expect(Object.values(s.groups!)[0]!.illusion).toBeUndefined();expect(target(s).hits[0]!.technique??Object.values(s.groups!)[0]!.technique).toEqual(original);s=finish(s);expect(s.discard).toContain(human);});
 it('later public reveal cannot retroactively suppress a fixed hidden guard',()=>{let s=arnes();s=illusion(s,['arnes-suppression']);s=until(s,'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');const frozen=structuredClone(target(s).followerDefense);s=act(s,'B',{type:'REVEAL_CHARACTER'});expect(target(s).followerDefense).toEqual(frozen);s=closeWindow(s);expect(target(s).hits[0]!.damage).toBe(7);s=finish(s);});
});

describe('Task7m Tia surprise scope and cancellation',()=>{
 it('hidden Tia explicitly reveals first; no-follower entry has no cost option',()=>{let s=ready();character(s,'A','有翼人のティア');const cost=handCard(s,'A','踏み込み／殴る');placed(s,'B','兵士');s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');expect(viewFor(s,'A').abilityOptions).not.toContainEqual(expect.objectContaining({abilityId:TIA}));s=act(s,'A',{type:'REVEAL_CHARACTER'});expect(viewFor(s,'A').abilityOptions).toContainEqual(expect.objectContaining({abilityId:TIA,costCardInstanceIds:expect.arrayContaining([cost])}));s=finish(s);
 let q=ready();character(q,'A','有翼人のティア');handCard(q,'A','踏み込み／殴る');q=act(q,'A',{type:'REVEAL_CHARACTER'});q=until(attack(q,'風矢',['B'],true),'follower-entry-abilities');expect(viewFor(q,'A').abilityOptions).not.toContainEqual(expect.objectContaining({abilityId:TIA}));q=finish(q);
 });
 it('selected virtual-only guard enables Tia on restarted entry and protects the whole column from ignore',()=>{let s=arnes();character(s,'A','有翼人のティア');const cost=handCard(s,'A','踏み込み／殴る');s=act(s,'A',{type:'REVEAL_CHARACTER'});s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');expect(viewFor(s,'A').abilityOptions).toEqual([]);s=use(s,'B',ARNES);s=closeWindow(s);expect(viewFor(s,'A').followerEntry).toMatchObject({virtualGuardSelected:true});s=use(s,'A',TIA,{costCardInstanceId:cost});s=closeWindow(s);s=until(s,'follower-start');expect(target(s).frozenAbilityIgnore).toBe(true);s=closeWindow(s);expect(target(s).followerIgnoreCancelled).toBe(true);expect(target(s).hits[0]!.damage).toBe(6);s=finish(s);});
 it('distinct target entries need distinct costs and never leak ignore to another target',()=>{let s=ready();character(s,'A','有翼人のティア');s=act(s,'A',{type:'REVEAL_CHARACTER'});const b=placed(s,'B','兵士'),c=placed(s,'C','傭兵');const costs=[handCard(s,'A','踏み込み／殴る'),handCard(s,'A','踏み込み／弓')];s=until(attack(s,'風矢',['B','C'],true),'follower-entry-abilities');const first=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===TIA)!;s=use(s,'A',TIA,{costCardInstanceId:costs[0]});s=closeWindow(s);s=until(s,'follower-start');expect(Object.values(s.groups!)[0]!.targets[1]!.surpriseActorId).toBeUndefined();s=closeWindow(s);s=until(s,'follower-entry-abilities');const second=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===TIA)!;expect(second.targetEventId).not.toBe(first.targetEventId);reject(s,'A',{type:'USE_ABILITY',abilityId:TIA,targetEventId:first.targetEventId,costCardInstanceId:costs[1]});s=use(s,'A',TIA,{costCardInstanceId:costs[1]});s=finish(s);expect(s.discard).toEqual(expect.arrayContaining(costs));expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toContain(b);expect(s.players.C!.followers.map(f=>f.cardInstanceId)).toContain(c);expect(s.players.B!.damage).toBe(7);expect(s.players.C!.damage).toBe(7);});
 it('cancelled surprise spends cost and attempt, retains combat phase and snapshot defense',()=>{let s=ready();character(s,'A','有翼人のティア');s=act(s,'A',{type:'REVEAL_CHARACTER'});placed(s,'B','城');const cost=handCard(s,'A','踏み込み／殴る'),fate=handCard(s,'B','命運凶変');s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');s=use(s,'A',TIA,{costCardInstanceId:cost});s=cancelAbility(s,'B',fate);expect(s.phase).toBe('combat');expect(s.discard).toContain(cost);expect(viewFor(s,'A').abilityOptions).not.toContainEqual(expect.objectContaining({abilityId:TIA}));s=finish(s);expect(s.players.B!.damage).toBe(2);});
 it.each(['stopped','ability-disabled'] as const)('Tia %s before snapshot disables accepted modifier without refund',kind=>{let s=ready();character(s,'A','有翼人のティア');s=act(s,'A',{type:'REVEAL_CHARACTER'});placed(s,'B','城');const cost=handCard(s,'A','踏み込み／殴る');s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');s=use(s,'A',TIA,{costCardInstanceId:cost});s=closeWindow(s);disabled(s,'A',kind);s=until(s,'follower-start');expect(target(s).frozenAbilityIgnore).toBe(false);expect(s.discard).toContain(cost);s=finish(s);expect(s.players.B!.damage).toBe(2);});
});

describe('Task7m actual additional coverage',()=>{
 it('Tia surprise fixes all three actual residual hits and remains fixed after source disable',()=>{let s=ready();character(s,'A','有翼人のティア');s.players.B!.permanent={endurance:100};s=act(s,'A',{type:'REVEAL_CHARACTER'});const follower=placed(s,'B','兵士');const cost=handCard(s,'A','踏み込み／殴る'),source=handCard(s,'A','天地百撃斬');s.players.A!.hand=s.players.A!.hand.filter(x=>x!==source);s.players.A!.chants.push({cardInstanceId:source,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:source,targetIds:['B'],dedicated:false});s=until(s,'damage');s=closeWindow(s,[3]);s=until(s,'follower-entry-abilities');expect(target(s).hits).toHaveLength(3);s=use(s,'A',TIA,{costCardInstanceId:cost});s=closeWindow(s);s=until(s,'follower-start');disabled(s,'A','ability-disabled');s=closeWindow(s);expect(target(s).hits.map(h=>h.damage)).toEqual([7,7,7]);expect(target(s).followerDefense![0]!.hits.map(h=>h.outcome)).toEqual(['passed-through','passed-through','passed-through']);s=finish(s);expect(s.players.B!.damage).toBe(21);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toContain(follower);});
 it('physical rear cancelIgnore protects Tia target whole column with one saved morale',()=>{let s=ready();character(s,'A','有翼人のティア');s=act(s,'A',{type:'REVEAL_CHARACTER'});placed(s,'B','砦');placed(s,'B','親衛隊');const cost=handCard(s,'A','踏み込み／殴る');s=until(attack(s,'風矢',['B'],true),'follower-entry-abilities');s=use(s,'A',TIA,{costCardInstanceId:cost});s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);});
 it('guard regenerates with distinct identity only in a genuinely later attack after actual intervening turns',()=>{let s=arnes();s=until(attack(s,'魔衝破'),'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');const first=viewFor(s,'B').virtualFollowerDefense[0]!.sourceId;s=finish(s);expect(viewFor(s,'A').virtualFollowerDefense).toEqual([]);
  for(let i=0;i<4;i++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});s=act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(viewFor(s,actor).self.stats.handLimit)});const next=s.seatOrder[s.turnSeat]!;s=act(s,next,{type:'START_TURN'});s=finish(s);s=act(s,next,{type:'CHOOSE_DRAW',draw:false});}
  expect(s.seatOrder[s.turnSeat]).toBe('A');s=until(attack(s,'衝破'),'follower-entry-abilities');s=use(s,'B',ARNES);s=closeWindow(s);s=until(s,'follower-start');expect(viewFor(s,'B').virtualFollowerDefense[0]!.sourceId).not.toBe(first);s=finish(s);expect(s.players.B!.damage).toBe(6);
 });
 it('accepted guard source disabled while its declaration is pending never applies',()=>{let s=until(attack(arnes()),'follower-entry-abilities');s=use(s,'B',ARNES);disabled(s,'B','ability-disabled');s=closeWindow(s);s=until(s,'follower-start');expect(target(s).followerDefense).toEqual([]);s=finish(s);});
 it('suppression-only choices never disclose an unknown non-Arnes target and remain a no-op',()=>{let s=ready();character(s,'A','吟遊詩人のレスター');s=until(attack(s,'踏み込み／弓'),'attack-abilities');const options=viewFor(s,'A').abilityOptions;const altered=structuredClone(s);character(altered,'B','黒妖精のアーネス');expect(viewFor(altered,'A').abilityOptions).toEqual(options);s=use(s,'A',LESTER,{abilityEffectIds:['arnes-suppression']});s=closeWindow(s);s=until(s,'follower-start');expect(target(s).followerDefense).toEqual([]);s=finish(s);expect(s.players.B!.damage).toBe(4);});
 it('selection qualification freezes current magic at acceptance but compares printed use Lv independently of effect Lv',()=>{let s=arnes();character(s,'A','吟遊詩人のレスター');const prayer=handCard(s,'A','必勝の祈り');s=until(attack(s,'魔衝破'),'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:viewFor(s,'A').reactionTargetActionId!});s=until(s,'attack-abilities');const g=Object.values(s.groups!)[0]!;expect(g.technique.useLevel).toBe(5);expect(g.technique.effectLevel).toBe(6);s=use(s,'A',LESTER,{abilityEffectIds:['spirit-conversion']});s.players.A!.permanent={magic_level:-5};s=closeWindow(s);expect(target(s).hits[0]!.technique!.attributes).toContain('精');s=finish(s);});
});
