import {expect,it} from 'vitest';
import {viewFor,transition,type GameState} from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow,passReclaims} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
import {damagePreview} from '../src/abilities/action-modifiers.js';
const FURY='c2-p02-r1c2-ab03';
function priority(s:GameState,actor='A'){for(let i=0;i<30;i++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('FURY_PRIORITY');}
function prepared(name='踏み込み／弓'){let s=ready();character(s,'A','妖精王フューリー');for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20};const card=handCard(s,'A',name);handCard(s,'B','命運凶変');handCard(s,'B','神性介入');return {s,card};}
function source(){const {s,card}=prepared();return until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'effect-level');}
function main(s:GameState){return Object.values(s.actions!).find(a=>a.kind==='attack')!;}
function use(s:GameState){s=priority(s);const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===FURY);expect(o).toBeDefined();return act(s,'A',{type:'USE_ABILITY',abilityId:FURY,targetEventId:o!.targetEventId});}
it('Fury bow freezes independent effect two and damage five without changing use level',()=>{
 let s=source();const base=structuredClone(main(s).technique);s=use(s);s=closeWindow(s);expect(s.rolls!.at(-1)).toMatchObject({purpose:'ability-value',formula:'d6',stage:'before-roll'});s=closeWindow(s,[2]);const effectId=s.rolls!.at(-1)!.id;s=closeWindow(s);s=until(s,'damage');expect(main(s).technique.effectLevel).toBe(base.effectLevel+2);expect(main(s).technique.useLevel).toBe(base.useLevel);s=closeWindow(s);s=closeWindow(s,[5]);const damageId=s.rolls!.at(-1)!.id;expect(damageId).not.toBe(effectId);s=until(s,'attack-abilities');expect(main(s).technique.damage).toBe(base.damage!+5);expect(s.rolls!.find(r=>r.id===effectId)!.faces).toEqual([2]);expect(s.rolls!.find(r=>r.id===damageId)!.faces).toEqual([5]);s=finish(s);expect(s.players.B!.damage).toBe(base.damage!+5);
});
function effect(s:GameState){s=closeWindow(use(s));s=closeWindow(s,[2]);return closeWindow(s);}
function damaged(s:GameState){s=until(s,'damage');s=closeWindow(s);s=closeWindow(s,[5]);return until(s,'attack-abilities');}
function reroll(s:GameState,faces:number[]){const id=s.rolls!.at(-1)!.id;s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=closeWindow(s,faces);return passReclaims(s);}
it('Fury decline and cancellation roll neither optional die',()=>{
 for(const cancel of [false,true]){let s=source();const base=structuredClone(main(s).technique);if(cancel){s=use(s);s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});s=closeWindow(s);s=closeWindow(s);}s=until(s,'attack-abilities');expect(main(s).technique).toMatchObject({effectLevel:base.effectLevel,damage:base.damage,useLevel:base.useLevel});expect(s.rolls?.filter(r=>r.purpose==='ability-value')??[]).toHaveLength(0);if(cancel)expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===FURY)).toBe(false);}
});
it('Fury non-bow never offers numerical modifier',()=>{const {s,card}=prepared('黒翼飛翔剣');const next=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'effect-level');expect(viewFor(next,'A').abilityOptions.some(o=>o.abilityId===FURY)).toBe(false);});
it('Fury effect reroll does not alter independent damage roll',()=>{let s=closeWindow(use(source()));s=closeWindow(s,[2]);const id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)).not.toHaveProperty('threshold');s=priority(s,'B');const snapshot=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(snapshot);s=reroll(s,[6]);s=damaged(s);expect(main(s).technique).toMatchObject({effectLevel:9,damage:9,useLevel:3});expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[6],attempts:[{faces:[2]},{faces:[6]}]});expect(s.rolls!.filter(r=>r.purpose==='ability-value').map(r=>r.total)).toEqual([6,5]);});
it('Fury damage reroll preserves already frozen effect',()=>{let s=until(effect(source()),'damage');s=closeWindow(s);s=closeWindow(s,[5]);const id=s.rolls!.at(-1)!.id;s=reroll(s,[1]);s=until(s,'attack-abilities');expect(main(s).technique).toMatchObject({effectLevel:5,damage:5,useLevel:3});expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[1],attempts:[{faces:[5]},{faces:[1]}]});expect(s.rolls!.filter(r=>r.purpose==='ability-value').map(r=>r.total)).toEqual([2,1]);});
function ban(s:GameState){s=priority(s,'B');const id='c2-p07-r1c2-ab03',o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===id)!;expect(o).toBeDefined();return closeWindow(act(s,'B',{type:'USE_ABILITY',abilityId:id,targetEventId:o.targetEventId,targetIds:['A']}));}
function suppressible(){const {s,card}=prepared();character(s,'B','破壊神ヴァンミール');s.players.B!.revealed=true;return until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'effect-level');}
it('Fury suppressed before effect freeze loses both live additions',()=>{let s=effect(suppressible());s=ban(s);s=until(s,'attack-abilities');expect(main(s).technique).toMatchObject({effectLevel:3,damage:4});expect(s.rolls!.filter(r=>r.purpose==='ability-value')).toHaveLength(1);});
it('Fury suppressed after effect freeze preserves effect and omits unfrozen damage',()=>{let s=until(effect(suppressible()),'damage');s=ban(s);s=until(s,'attack-abilities');expect(main(s).technique).toMatchObject({effectLevel:5,damage:4});expect(s.rolls!.filter(r=>r.purpose==='ability-value')).toHaveLength(1);});
it('Fury one bow declaration shares saved numbers across targets and hits',()=>{let {s,card}=prepared('光流弓');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true}),'effect-level');s=damaged(effect(s));const g=Object.values(s.groups!)[0]!;expect(g.technique).toMatchObject({effectLevel:8,damage:15});expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual([[15],[15]]);expect(s.rolls!.filter(r=>r.purpose==='ability-value')).toHaveLength(2);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([15,15]);});
// Structural fixed-copy exclusion; no legal warrior-bow reflection route is asserted.
it('Fury reflection does not declare new numeric bonuses',()=>{let s=source();main(s).fixedReceivedEffect=true;expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===FURY)).toBe(false);});
it('Fury automatic follower origin does not offer the character numerical package (structural exclusion)',()=>{let s=source();main(s).followerOrigin={cardInstanceId:main(s).cardInstanceId!,parentGroupId:'structural',targetId:'B',hitIndex:0};expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===FURY)).toBe(false);});
// Structural null arithmetic; canonical bow profiles have numerical damage.
it('Fury null damage remains null',()=>{let s=damaged(effect(source()));const a=main(s);a.technique.damage=null;a.modifiers!.damageBase=null;a.modifiers!.damageFrozen=false;expect(damagePreview(s,a)).toBeNull();});
it('Fury extra owned return and two bow dice complete one printed ability',()=>{let s=damaged(effect(source()));const card=main(s).cardInstanceId;s=until(s,'reclaim');s=priority(s);const d=viewFor(s,'A').reclaim!,c=d.claims.find(c=>c.right==='extra')!;expect(c).toBeDefined();s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:c.claimId});s=finish(s);expect(s.players.A!.hand).toContain(card);expect(s.players.A!.reclaimUsage?.['踏み込み／弓']).toMatchObject({baseSpent:false,extraSpentByAbility:[FURY]});expect(s.rolls!.filter(r=>r.purpose==='ability-value').map(r=>r.total)).toEqual([2,5]);});

it('Fury source-specific bundle modifier never spills into another source',()=>{
 let s=ready();character(s,'A','魔聖母ディア');s.players.A!.abilityCharacterIds=['c2-p02-r1c2']; // Structural ownership fixture; no canonical Dia/Fury inheritance is asserted.
 s.players.A!.permanent={spirit:20,endurance:100};s.distances.A!.B=s.distances.B!.A='near';const fairy=handCard(s,'A','妖精族'),soldier=handCard(s,'A','兵士');
 s=act(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources:[{cardInstanceId:fairy,dedicated:false,targetIds:['B']},{cardInstanceId:soldier,dedicated:false,targetIds:['B']}]});
 s=closeWindow(s);s=closeWindow(s,[4]);s=closeWindow(s);s=until(s,'effect-level');s=effect(s);s=until(s,'damage');s=closeWindow(s,[2]);s=closeWindow(s);s=closeWindow(s,[5]);s=until(s,'attack-abilities');
 const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.hits.map(h=>[h.technique!.useLevel,h.technique!.effectLevel,h.damage])).toEqual([[7,9,11],[1,1,1]]);expect(s.rolls!.filter(r=>r.purpose==='ability-value').map(r=>r.total)).toEqual([2,5]);
});
