import {expect,it} from 'vitest';
import {transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeGatePhysicalScenario,GATE,type GatePhysicalScenario} from './fixtures/gate-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function command(s:GameState,targetPosition=0,destinationPosition=0){return {type:'PLAY_TURN_TECHNIQUE' as const,cardInstanceId:GATE,targetIds:['B'],dedicated:false,followerTransfer:{targetPosition,destinationPosition,...(s.players.A!.followers.length===2?{replacementCardInstanceId:s.players.A!.followers[1]!.cardInstanceId}:{})}};}
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each([4,5])('actual Magic Gate magic%s retains use5 checks without chant attack damage or extra dash attribute',level=>{let s=makeGatePhysicalScenario('gate-physical-empty',players,{level});reject(s,'A',{type:'CHANT',cardInstanceId:GATE});reject(s,'A',{type:'ATTACK',cardInstanceId:GATE,targetIds:['B'],dedicated:false});const original=structuredClone(s.players.B!.followers);s=act(s,'A',command(s));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===GATE)!;expect(f.technique).toMatchObject({school:'magic',range:'none',useLevel:5,effectLevel:5,damage:null,attributes:['魔'],chant:false,noChecks:false,turnEffect:'magic-gate'});expect(f.checkSpecs).toHaveLength(5-level);expect(f.followerTransfer).toMatchObject({donorId:'B',cardInstanceId:original[0]!.cardInstanceId,destinationPosition:0});s=finish(s);expect(s.players.A!.followers).toEqual([original[0]]);expect(s.players.B!.followers).toEqual([original[1]]);expect(s.players.B!.damage).toBe(0);expect(discardIds(s).filter(id=>id===GATE)).toHaveLength(1);expect(s.phase).toBe('hand-adjustment');});
it.each([['gate-physical-empty',0,0],['gate-physical-empty',1,0],['gate-physical-spare',0,0],['gate-physical-spare',1,1],['gate-physical-full',0,0],['gate-physical-full',0,1],['gate-physical-full',1,0],['gate-physical-full',1,1]] as const)('%s actual donor position%s moves exactly once into destination%s preserving relative order',(scenario,targetPosition,destinationPosition)=>{
 let s=makeGatePhysicalScenario(scenario,players);const donor=structuredClone(s.players.B!.followers),own=structuredClone(s.players.A!.followers),c=command(s,targetPosition,destinationPosition),replacement=c.followerTransfer.replacementCardInstanceId;expect(viewFor(s,'A').magicGateTargets).toEqual([{actorId:'B',positions:[0,1]}]);s=act(s,'A',c);expect(s.players.B!.followers).toEqual(donor);if(replacement){expect(discardIds(s)).toContain(replacement);expect(s.players.A!.followers).toEqual([own[0]]);}const windows:string[]=[];while(s.windows?.length){windows.push(s.windows.at(-1)!.kind);s=pass(s);}expect(windows).not.toContain('normal-defense');expect(windows).not.toContain('follower-consent');const expected=own.filter(f=>f.cardInstanceId!==replacement);expected.splice(destinationPosition,0,donor[targetPosition]!);expect(s.players.A!.followers).toEqual(expected);expect(s.players.B!.followers).toEqual(donor.filter((_,i)=>i!==targetPosition));expect(viewFor(s,'C').players.B!.followers).toEqual([{position:0,face:'back'}]);expect(s.players.B!.hand).toHaveLength(5);expect(s.players.A!.hand).not.toContain(donor[targetPosition]!.cardInstanceId);expect(discardIds(s).filter(id=>id===GATE)).toHaveLength(1);
});
it.each(['gate-physical-full','gate-physical-incompatible'] as const)('%s actual accepted hidden transfer uses no identity oracle and pays even when placement is impossible',scenario=>{
 let s=makeGatePhysicalScenario(scenario,players),other=makeGatePhysicalScenario(scenario==='gate-physical-full'?'gate-physical-incompatible':'gate-physical-full',players);expect(viewFor(s,'A').magicGateTargets).toEqual(viewFor(other,'A').magicGateTargets);const donor=structuredClone(s.players.B!.followers),replacement=s.players.A!.followers[1]!.cardInstanceId,target=donor[0]!.cardInstanceId;expect(JSON.stringify(viewFor(s,'A'))).not.toContain(target);s=act(s,'A',command(s));expect(JSON.stringify(viewFor(s,'A'))).not.toContain(target);s=finish(s);expect(discardIds(s)).toEqual(expect.arrayContaining([GATE,replacement]));if(scenario==='gate-physical-incompatible'){expect(s.players.A!.followers).toHaveLength(1);expect(s.players.B!.followers).toEqual(donor);for(const id of ['A','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(target);}else{expect(s.players.A!.followers[0]).toEqual(donor[0]);expect(s.players.B!.followers).toEqual([donor[1]]);expect(viewFor(s,'C').players.A!.followers).toEqual([{position:0,face:'back'},{position:1,face:'back'}]);}
});
it.each(['cancel','failure'])('actual full Gate %s keeps paid replacement discarded and donor followers unmoved',route=>{
 let s=makeGatePhysicalScenario('gate-physical-full',players,{level:route==='failure'?4:5});const donor=structuredClone(s.players.B!.followers),own=structuredClone(s.players.A!.followers);s=act(s,'A',command(s));expect(discardIds(s)).toContain(own[1]!.cardInstanceId);if(route==='failure')s=closeWindow(until(s,'before-roll'),[6,6]);else{const id=Object.values(s.actions!).find(a=>a.cardInstanceId===GATE)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}s=finish(s);expect(s.players.A!.followers).toEqual([own[0]]);expect(s.players.B!.followers).toEqual(donor);expect(discardIds(s)).toEqual(expect.arrayContaining([GATE,own[1]!.cardInstanceId]));
});
it('actual forced Gate transfer can take donor nonremovable Dark Saint without donor consent',()=>{let s=makeGatePhysicalScenario('gate-physical-empty',players,{donorSaint:true});const donor=structuredClone(s.players.B!.followers);s=finish(act(s,'A',command(s)));expect(s.players.A!.followers).toEqual([donor[0]]);expect(s.players.B!.followers).toEqual([donor[1]]);expect(viewFor(s,'A').followerPlacementOptions.removableCardInstanceIds).not.toContain(donor[0]!.cardInstanceId);});
it.each(['gate-physical-empty','gate-physical-full'] as const)('%s rejects invalid source zones targets positions and replacement costs without payment',scenario=>{
 const s=makeGatePhysicalScenario(scenario,players),c=command(s);reject(s,'A',{...c,dedicated:true});reject(s,'B',c);for(const targetIds of [[],['A'],['C'],['B','C'],['missing']])reject(s,'A',{...c,targetIds});for(const targetPosition of [-1,2,999])reject(s,'A',{...c,followerTransfer:{...c.followerTransfer,targetPosition}});for(const destinationPosition of [-1,2,999])reject(s,'A',{...c,followerTransfer:{...c.followerTransfer,destinationPosition}});for(const cardInstanceId of [s.players.C!.hand.find(id=>id==='a2-p22-r1c1')!,s.deck[0]!,GATE])reject(s,'A',{...c,followerTransfer:{...c.followerTransfer,cardInstanceId}});if(scenario==='gate-physical-full'){reject(s,'A',{...c,followerTransfer:{targetPosition:0,destinationPosition:0}});reject(s,'A',{...c,followerTransfer:{...c.followerTransfer,replacementCardInstanceId:s.players.A!.followers[0]!.cardInstanceId}});}else reject(s,'A',{...c,followerTransfer:{...c.followerTransfer,replacementCardInstanceId:s.players.A!.hand[0]!}});expect(viewFor(s,'A').magicGateTargets).not.toContainEqual(expect.objectContaining({actorId:'C'}));
});
