import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,closeWindow,finish,pass,until} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeGodsBloodPhysicalScenario,type GodsBloodPhysicalScenario} from './fixtures/gods-blood-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),blood='a2-p01-r1c3',book='a2-p03-r1c1',stats=['warrior_level','magic_level','spirit'] as const;
function ready(name:GodsBloodPhysicalScenario){let s=makeGodsBloodPhysicalScenario(name,players);for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});expect(s.phase).toBe('draw');expect(s.players.A!.open).not.toContain(blood);return s;}
function acquire(s:GameState,bookDraw=false){s=act(s,'A',{type:'CHOOSE_DRAW',draw:!bookDraw});return bookDraw?finish(act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:book})):s;}
function nextB(s:GameState){if(s.phase==='action')s=act(s,'A',{type:'PASS_ACTION'});if(s.phase==='withdrawal')s=act(s,'A',{type:'PASS_WITHDRAWAL'});s=finish(act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.filter(id=>id!==book).slice(0,Math.max(0,s.players.A!.hand.length-gameStats(s,'A').handLimit))}));s=act(s,'B',{type:'START_TURN'});return act(s,'B',{type:'CHOOSE_DRAW',draw:false});}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each([false,true])('actual Gods Blood OPEN through secret book %s raises exactly three owner stats without permanent growth or identity publication',bookDraw=>{let s=ready(bookDraw?'blood-book':'blood-draw');const before=gameStats(s,'A'),others=Object.fromEntries(['B','C','D'].map(id=>[id,gameStats(s,id)])),permanent=structuredClone(s.players.A!.permanent),hand=s.players.A!.hand.length;s=acquire(s,bookDraw);expect(gameStats(s,'A')).toEqual({...before,warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});expect(s.players.A!.permanent).toEqual(permanent);expect(s.players.A!.hand).toHaveLength(hand+(bookDraw?0:1));expect(s.players.A!.hand).not.toContain(blood);expect(s.players.A!.attachments).not.toContain(blood);expect(s.players.A!.revealed).toBe(false);for(const id of ['B','C','D']){expect(gameStats(s,id)).toEqual(others[id]);expect(viewFor(s,id).players.A!.open).toContain(blood);}expect(viewFor(s,'A').self.stats).toEqual(gameStats(s,'A'));expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===blood)).toHaveLength(1);reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:blood});s=nextB(s);expect(gameStats(s,'A')).toMatchObject({warrior_level:3,magic_level:6,spirit:7});});
it('actual opponent Wish moves the one public Blood bonus to the new owner with no repeated OPEN or permanent conversion',()=>{let s=ready('blood-transfer');const a=gameStats(s,'A'),b=gameStats(s,'B'),permanent=Object.fromEntries(s.seatOrder.map(id=>[id,structuredClone(s.players[id]!.permanent)]));s=nextB(acquire(s));s=until(act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c2',mode:'wish'}),'wish');const decision=viewFor(s,'B').wish!;for(const id of ['A','C','D'])expect(viewFor(s,id).wish).toBeNull();reject(s,'A',{type:'CHOOSE_WISH',decisionId:decision.decisionId,source:{kind:'public',cardInstanceId:blood}});s=finish(act(JSON.parse(JSON.stringify(s)),'B',{type:'CHOOSE_WISH',decisionId:decision.decisionId,source:{kind:'public',cardInstanceId:blood}}));expect(gameStats(s,'A')).toEqual(a);expect(gameStats(s,'B')).toEqual({...b,warrior_level:b.warrior_level+1,magic_level:b.magic_level+1,spirit:b.spirit+1});expect(s.players.A!.open).not.toContain(blood);expect(s.players.B!.open).toContain(blood);expect(s.players.B!.hand).not.toContain(blood);for(const id of s.seatOrder)expect(s.players[id]!.permanent).toEqual(permanent[id]);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===blood)).toHaveLength(1);expect(s.discard).not.toContain(blood);});
it('actual lethal Bow discards Blood once and immediately removes all three bonuses without reducing independent training',()=>{let s=ready('blood-death');const before=gameStats(s,'A'),permanent=structuredClone(s.players.A!.permanent);s=nextB(acquire(s));s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['A'],dedicated:false}));expect(s.events.filter(e=>e.type==='PLAYER_DIED'&&e.actorId==='A')).toHaveLength(1);expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.open).not.toContain(blood);expect(s.discard.filter(id=>id===blood)).toHaveLength(1);expect(gameStats(s,'A')).toEqual(before);expect(s.players.A!.permanent).toEqual(permanent);expect(s.outcome).toBeUndefined();});
it.each([['blood-warrior',false],['blood-warrior',true],['blood-magic',false],['blood-magic',true],['blood-spirit',false],['blood-spirit',true]] as const)('%s actual use boundary with Blood=%s uses current warrior magic and spirit', (scenario,draw)=>{let s=ready(scenario);s=act(s,'A',{type:'CHOOSE_DRAW',draw});const card=scenario==='blood-magic'?'a2-p18-r1c3':'a2-p24-r1c2';s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});if(scenario!=='blood-spirit'&&draw){s=until(s,'normal-defense');expect((s.rolls??[]).filter(r=>r.purpose==='excess-level')).toHaveLength(0);s=finish(s);expect(s.players.B!.damage).toBe(scenario==='blood-magic'?8:4);}else{s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',checkBase:'spirit'});s=closeWindow(s,[3,4]);expect(s.rolls!.at(-1)!.threshold).toBe(draw?7:6);expect(s.rolls!.at(-1)!.success).toBe(draw);s=finish(closeWindow(s));expect(s.players.B!.damage).toBe(draw?4:0);}expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
