import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeGriffinPhysicalScenario,griffinPhysicalMode,type GriffinPhysicalScenario} from './fixtures/griffin-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['griffin-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('GRIFFIN_TURN');}throw Error('GRIFFIN_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p20-r3c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=griffinPhysicalMode(scenario);let s=makeGriffinPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=griffinPhysicalMode(scenario);let s=ready(makeGriffinPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=griffinPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeGriffinPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=griffinPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeGriffinPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=griffinPhysicalMode(scenario);let s=until(incoming(ready(makeGriffinPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=griffinPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeGriffinPhysicalScenario(scenario,players,{owner:'魔聖母ディア'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});
const GRIFFIN='a2-p20-r3c1',ARMY='a2-p05-r2c2',UPA='c2-p05-r1c2-ab02';
function bundle(s:GameState,card=GRIFFIN){const o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId===UPA)!;expect(o).toBeDefined();return {type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:['B']}]};}
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual reached Griffin morale %s rolls spirit once for all three higher Dwarf hits with no HP on failure',mode=>{
 let s=ready(makeGriffinPhysicalScenario('griffin-morale-pass',players,{spirit:6}),GRIFFIN);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',rollerId:'A',modifier:0,formula:'2d6'});expect(s.players.A!.damage).toBe(0);s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(f.levels).toEqual([5,5,5]);expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(mode==='pass'?3:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?9:18);expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual Griffin does not roll before reaching its position but surviving non-Upa Griffin rolls anew for the next group',()=>{
 let s=ready(makeGriffinPhysicalScenario('griffin-morale-pass',players,{level:4,spirit:6}),GRIFFIN);s=finish(dwarf(s));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.players.A!.damage).toBe(0);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeGriffinPhysicalScenario('griffin-morale-pass',players,{owner:'竜皇子アスフェルト',spirit:0}),GRIFFIN,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',GRIFFIN]});q=finish(incoming(q));expect((q.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(q.players.A!.followers[1]!.revealed).toBe(false);
});
it('actual explicitly selected Upanishat at spirit zero waives Griffin morale for all higher hits without waiving its HP defense',()=>{
 let s=ready(makeGriffinPhysicalScenario('griffin-morale-pass',players,{owner:'獣使いのウパニシャット',spirit:0}),GRIFFIN);s=until(dwarf(s),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toContainEqual({cardInstanceId:GRIFFIN});s=finish(act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GRIFFIN]}));expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(s.players.A!.damage).toBe(9);expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);
});
it.each(['griffin-ded-hand','griffin-ded-field'] as const)('%s actual Upa dedicated permission at warrior zero fixes all selected targets to two separate damage8 hits without use checks',scenario=>{
 const m=griffinPhysicalMode(scenario);for(const targets of [['B'],['C'],['D'],['B','C'],['B','D'],['C','D'],['B','C','D']]){let s=ready(makeGriffinPhysicalScenario(scenario,players,{warrior:0}),GRIFFIN,m.initial);for(const bad of [[],['A'],['B','B'],['missing']])reject(s,'A',{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:bad,dedicated:true});s=act(s,'A',{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:targets,dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GRIFFIN)!;expect(a.checks).toEqual([]);expect(a.technique).toMatchObject({range:'far',school:'warrior',useLevel:5,effectLevel:5,damage:8,hitCount:2,attributes:['遠','戦','格'],noChecks:true,target:'all'});expect(a.technique.counterProhibited??false).toBe(false);expect(s.resolution).toContain(GRIFFIN);expect(s.players.A!.followers).toEqual([]);s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.actorId)).toEqual(targets);for(const t of g.targets)expect(t.hits.map(h=>h.damage)).toEqual([8,8]);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual(['B','C','D'].map(id=>targets.includes(id)?16:0));expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(GRIFFIN);}
});
it.each([false,true])('actual Griffin each-hit defense and HP applies independently with first-hit maai=%s',maai=>{
 let s=makeGriffinPhysicalScenario('griffin-ded-maai',players);s=act(s,'A',{type:'PASS_SETUP'});s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p20-r1c2'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(act(s,'A',{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:['B','C'],dedicated:true}),'normal-defense');if(maai)s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='B')!,f=t.followerDefense![0]!;expect(t.hits.map(h=>h.damage)).toEqual(maai?[8,3]:[3,3]);expect(f.hits.map(h=>h.hpReduction)).toEqual(maai?[5]:[5,5]);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([maai?3:6,16]);expect(discardIds(s).filter(id=>id==='a2-p20-r1c2')).toHaveLength(1);expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);
});
it.each(['griffin-grant-hand','griffin-grant-field'] as const)('%s actual Upa beast grant uses ordinary single-target two-hit bottom with use checks retained',scenario=>{
 const m=griffinPhysicalMode(scenario);let s=ready(makeGriffinPhysicalScenario(scenario,players,{warrior:4}),GRIFFIN,m.initial);s=act(s,'A',bundle(s));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GRIFFIN)!;expect(a.checks).toHaveLength(1);expect(a.technique).toMatchObject({range:'far',useLevel:5,effectLevel:5,damage:8,hitCount:2,target:'one',noChecks:false});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([16,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);
});
it.each([4,5])('actual non-Upa Army uses hand ordinary Griffin with morale plus ownwarrior%i checks and paid near approach remains legal',warrior=>{
 for(const near of [false,true]){let s=ready(makeGriffinPhysicalScenario('griffin-army',players,{warrior}),GRIFFIN,false);if(near)s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:GRIFFIN,targetIds:['B']});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GRIFFIN)!;expect(a.checks).toHaveLength(5-warrior);expect(a.technique).toMatchObject({range:'far',school:'warrior',useLevel:5,effectLevel:5,damage:8,hitCount:2,target:'one',noChecks:false,attributes:['遠','戦','格']});s=finish(s);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);expect(s.players.B!.damage).toBe(16);for(const id of [GRIFFIN,ARMY])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);}
 let s=ready(makeGriffinPhysicalScenario('griffin-army',players),GRIFFIN);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===GRIFFIN)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:GRIFFIN,targetIds:['B']});
});
it.each(['hand','field','army-parent','army-child','army-morale','army-use','grant'] as const)('actual Griffin %s cancellation or failed check disposes physical source exactly once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'griffin-army':mode==='field'?'griffin-ded-field':mode==='grant'?'griffin-grant-hand':'griffin-ded-hand';let s=ready(makeGriffinPhysicalScenario(scenario,players,{warrior:4}),GRIFFIN,mode==='field');s=act(s,'A',army?{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:GRIFFIN,targetIds:['B']}:mode==='grant'?bundle(s):{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:['B','C'],dedicated:true});if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='army-use'){s=until(s,'before-roll');if(mode==='army-use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:GRIFFIN)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId===UPA);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'||mode==='army-use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(GRIFFIN);for(const id of army?[GRIFFIN,ARMY]:[GRIFFIN])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);
});
it('actual Mirror cancels only one Griffin hit while the same target still receives the other hit',()=>{
 let s=ready(makeGriffinPhysicalScenario('griffin-ded-hand',players),GRIFFIN,false);s=until(act(s,'A',{type:'ATTACK',cardInstanceId:GRIFFIN,targetIds:['B','C'],dedicated:true}),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}));expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,8,16]);expect(discardIds(s).filter(id=>id===GRIFFIN)).toHaveLength(1);
});
