import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {assignCharacter,takeCard} from './fixtures/scenario-tools.js';
import {makeGuardianPhysicalScenario,guardianPhysicalMode,type GuardianPhysicalScenario} from './fixtures/guardian-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['guardian-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('GUARDIAN_TURN');}throw Error('GUARDIAN_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p22-r3c3',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=guardianPhysicalMode(scenario);let s=makeGuardianPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=guardianPhysicalMode(scenario);let s=ready(makeGuardianPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=guardianPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeGuardianPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=guardianPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeGuardianPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=guardianPhysicalMode(scenario);let s=until(incoming(ready(makeGuardianPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
const GUARD='a2-p22-r3c3',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Guardian spirit6 minus1 morale %s shares one result across Dwarf8 hits with HP0',mode=>{
 let s=ready(makeGuardianPhysicalScenario('guardian-higher',players,{spirit:6}),GUARD);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-1,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,3]:[3,3]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:5,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual([0,0,0]);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual surviving Guardian checks again only for a later group and unreached rear stays hidden',()=>{
 let s=ready(makeGuardianPhysicalScenario('guardian-setup',players),GUARD);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeGuardianPhysicalScenario('guardian-setup',players,{spirit:0}),GUARD,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',GUARD]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([false,true])('actual Lia defensive waiver=%s preserves Guardian7 HP0 against Dwarf7',selected=>{
 let s=until(dwarf(ready(makeGuardianPhysicalScenario('guardian-waive',players),GUARD)),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD,GUARD]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[GUARD]:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.levels).toEqual([7,7,7]);expect(f.descriptor.hp).toBe(0);s=finish(s);expect(s.players.A!.damage).toBe(selected?0:18);expect(s.players.A!.followers).toEqual([]);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toHaveLength(selected?0:1);
});
it.each(['guardian-ignore','guardian-ignore-decline','guardian-sky','guardian-sky-decline'] as const)('%s ordinary Guardian protects its whole column from generic or attribute ignore only after morale',scenario=>{
 const m=guardianPhysicalMode(scenario);let s=makeGuardianPhysicalScenario(scenario,players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.front});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=next(ready(s,GUARD,false));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p21-r1c1',targetIds:['A','C'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!;expect(t.followerIgnoreCancelled??false).toBe(!m.fail);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===GUARD)!.dedicated).toBe(false);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.sky?[m.fail?12:0,12]:[m.fail?5:0,5]);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toHaveLength(m.sky&&!m.fail?2:1);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.ignore?m.fail?[m.front]:[m.front,GUARD]:m.fail?[m.front]:[]);if(!m.fail&&m.ignore)expect(s.players.A!.followers[1]!.revealed).toBe(true);
});
it('actual front Guardian cancels sky ignore for the following Griffin and equal7 blocks without HP',()=>{
 let s=makeGuardianPhysicalScenario('guardian-sky',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p20-r3c1'});s=next(ready(s,GUARD,false));s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r1c3',targetIds:['A','C'],dedicated:true}));expect([s.players.A!.damage,s.players.C!.damage]).toEqual([0,12]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p20-r3c1']);expect(s.players.A!.followers[0]!.revealed).toBe(false);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual foreign waiver rejects and Alseil explicit destruction bypasses Lia Guardian ignore cancellation',()=>{
 let s=until(dwarf(ready(makeGuardianPhysicalScenario('guardian-setup',players),GUARD)),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD]});s=next(ready(makeGuardianPhysicalScenario('guardian-destroy',players),GUARD));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p13-r1c2',targetIds:['A'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD]});s=finish(s);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect(s.players.A!.damage).toBe(0);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toHaveLength(0);
});
it('actual Lester human invalidation does not disable white sky Guardian ordinary cancellation',()=>{
 let s=makeGuardianPhysicalScenario('guardian-invalid',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=next(ready(s,GUARD,false));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=until(act(s,'B',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:'a2-p21-r1c1',targetIds:['A']}),'attack-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c1-ab02')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,abilityEffectIds:['human-invalidation']});s=until(s,'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerIgnoreCancelled).toBe(true);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===GUARD)!.ineffective??false).toBe(false);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',GUARD]);
});
function guardianAttack(s:GameState,scenario:GuardianPhysicalScenario,targets=['B','C','D']){return guardianPhysicalMode(scenario).army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:GUARD,targetIds:targets}:{type:'ATTACK' as const,cardInstanceId:GUARD,targetIds:targets,dedicated:true};}
it.each(['guardian-army','guardian-ded-hand','guardian-ded-field'] as const)('%s actual Lia far magic white7 damage10 permission requires all targets and prohibits maai',scenario=>{
 const m=guardianPhysicalMode(scenario);for(const magic of [6,7]){let s=ready(makeGuardianPhysicalScenario(scenario,players,{magic:m.dedicated?0:magic,warrior:magic===6?20:0}),GUARD,m.initial);for(const targets of [[],['A'],['B'],['B','C'],['B','B','C','D']])reject(s,'A',guardianAttack(s,scenario,targets));s=act(s,'A',guardianAttack(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GUARD)!;expect(a.checks).toHaveLength(m.dedicated?0:7-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:7,effectLevel:7,damage:10,attributes:['遠','魔','白'],noChecks:m.dedicated,target:'all',mandatoryAll:true,maaiProhibited:true});s=until(s,'normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([10,10,10]);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toHaveLength(m.army?1:0);for(const id of m.army?[GUARD,ARMY]:[GUARD])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
});
it.each(['竜皇子アスフェルト','魔聖母ディア','獣使いのウパニシャット'] as const)('actual %s cannot directly attack or human beast grant Guardian white sky',owner=>{
 for(const placed of [false,true]){const s=ready(makeGuardianPhysicalScenario('guardian-army',players,{owner}),GUARD,placed);for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:['B','C','D'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:GUARD});expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===GUARD)).toBe(false);}
});
it('actual Lia Army still has minus1 morale and placed Army or ordinary direct permission rejects',()=>{
 const q=ready(makeGuardianPhysicalScenario('guardian-army',players),GUARD);reject(q,'A',guardianAttack(q,'guardian-army'));reject(q,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:['B','C','D'],dedicated:false});let s=ready(makeGuardianPhysicalScenario('guardian-army',players,{spirit:0}),GUARD,false);s=finish(act(s,'A',guardianAttack(s,'guardian-army')));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.rolls!.find(r=>r.purpose==='follower-morale')!).toMatchObject({modifier:-1,success:false});for(const id of [GUARD,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it.each(['hand','field','parent','child','morale','use'] as const)('actual Guardian %s cancellation or failure consumes each source once without returning follower',mode=>{
 const scenario=mode==='hand'?'guardian-ded-hand':mode==='field'?'guardian-ded-field':'guardian-army',m=guardianPhysicalMode(scenario);let s=ready(makeGuardianPhysicalScenario(scenario,players,{magic:6}),GUARD,m.initial);s=act(s,'A',guardianAttack(s,scenario));if(mode==='child')s=closeWindow(s);if(mode==='morale'||mode==='use'){s=until(s,'before-roll');if(mode==='use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='morale'?'follower-morale':'excess-level');}const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?ARMY:GUARD))!,roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='morale'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.players.A!.followers).toEqual([]);for(const id of m.army?[GUARD,ARMY]:[GUARD])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it.each([7,8,9])('actual ordinary Nightmare plus Prayer reaches black magic%s against Guardian8',level=>{
 let s=next(ready(makeGuardianPhysicalScenario('guardian-black',players),GUARD));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r2c2',targetIds:['A'],dedicated:false}),'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const action=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p15-r2c2')!;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:action.id});for(let n=0;n<150&&s.windows!.at(-1)?.kind!=='follower-start';n++)s=pass(s,Array(30).fill(level-6));expect(s.windows!.at(-1)!.kind).toBe('follower-start');const g=Object.values(s.groups!)[0]!,f=g.targets[0]!.followerDefense![0]!;expect(g.technique).toMatchObject({school:'magic',effectLevel:level,attributes:['魔','精','黒']});expect(f.levels).toEqual([8]);expect(f.descriptor.hp).toBe(0);s=until(s,'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerIgnoreCancelled).toBe(true);s=finish(s);expect(s.players.A!.damage).toBe(level>8?2:0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(level<8?[GUARD]:[]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual black magic6 morale failure cannot use Guardian8 cancellation or HP',()=>{
 let s=next(ready(makeGuardianPhysicalScenario('guardian-black-fail',players),GUARD));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r2c2',targetIds:['A'],dedicated:false}),'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerIgnoreCancelled??false).toBe(false);s=finish(s);expect(s.players.A!.damage).toBe(2);expect(s.players.A!.followers).toEqual([]);expect(s.rolls!.find(r=>r.purpose==='follower-morale')!.success).toBe(false);
});
it.each(['black-warrior','nonblack-magic'] as const)('actual %s does not receive Guardian black-magic8 defense',mode=>{
 let s=makeGuardianPhysicalScenario('guardian-black',players);assignCharacter(s,'B',mode==='black-warrior'?'不死王ガドューラ':'白魔術師シェリム');const card=mode==='black-warrior'?'a2-p22-r3c2':'a2-p14-r1c3';takeCard(s,'B',card);s=next(ready(s,GUARD));s=act(s,'B',{type:'ATTACK',cardInstanceId:card,targetIds:mode==='black-warrior'?['A','C','D']:['A'],dedicated:true});if(mode==='black-warrior'){s=until(s,'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const action=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:action.id});}s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense![0]!;expect(f.levels).toEqual([7]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);
});
it.each(['evade','mirror'] as const)('actual Guardian no-maai attack still allows %s and ordinary approach withdrawal',mode=>{
 let s=makeGuardianPhysicalScenario('guardian-ded-hand',players,{defender:mode==='mirror'?'聖騎士ランスロット':'黒騎士ガーウィン'});if(mode==='evade')takeCard(s,'B','a2-p05-r3c1');s=ready(s,GUARD,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));expect(s.distances.A!.B).toBe('near');s=until(act(s,'A',guardianAttack(s,'guardian-ded-hand')),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:mode==='mirror'?'a2-p11-r1c3':'a2-p05-r3c1',dedicated:mode==='mirror'}));expect(['A','B','C','D'].map(id=>s.players[id]!.damage)).toEqual([mode==='mirror'?10:0,0,10,10]);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);s=finish(act(s,'A',{type:'WITHDRAW',cardInstanceId:'a2-p07-r1c1',targetId:'B'}));expect(s.distances.A!.B).toBe('far');expect(s.distances.B!.A).toBe('far');
});
