import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,finish,pass,until,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeHajaPhysicalScenario,type HajaPhysicalScenario} from '../../../apps/worker/test/fixtures/haja-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),haja='a2-p01-r2c2',ice='a2-p13-r1c1',rift='a2-p14-r2c2',mekai='a2-p13-r2c3',book='a2-p03-r1c1';
function ready(name:HajaPhysicalScenario,drawOpen=true){let s=makeHajaPhysicalScenario(name,players,drawOpen);s=readySetup(s);s=act(s,'A',{type:'START_TURN'});expect(s.players.A!.hand).toHaveLength(5);return s;}
function step(s:GameState){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)return pass(s);if(s.phase==='action')return act(s,id,{type:'PASS_ACTION'});if(s.phase==='withdrawal')return act(s,id,{type:'PASS_WITHDRAWAL'});if(s.phase==='hand-adjustment')return act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});if(s.phase==='turn-start')return act(s,id,{type:'START_TURN'});if(s.phase==='draw')return act(s,id,{type:'CHOOSE_DRAW',draw:false});throw Error('HAJA_PHASE');}
function next(s:GameState,id='A',phase='action'){for(let n=0;n<200;n++){if(!s.windows?.length&&s.seatOrder[s.turnSeat]===id&&s.phase===phase)return s;s=step(s);}throw Error('HAJA_TURN');}
function twoChants(name:HajaPhysicalScenario='haja-chants'){let s=act(ready(name),'A',{type:'CHOOSE_DRAW',draw:true});s=act(s,'A',{type:'CHANT',cardInstanceId:ice});s=next(s);s=act(s,'A',{type:'CHANT',cardInstanceId:rift});return next(s,'B');}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function steal(s:GameState){s=until(act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c2',mode:'wish'}),'wish');return act(s,'B',{type:'CHOOSE_WISH',decisionId:viewFor(s,'B').wish!.decisionId,source:{kind:'public',cardInstanceId:haja}});}
it.each([false,true])('actual Haja OPEN through secretbook=%s changes only hand and chant limits for its current owner',bookDraw=>{let s=ready(bookDraw?'haja-book':'haja-draw');const before=gameStats(s,'A'),others=Object.fromEntries(['B','C','D'].map(id=>[id,gameStats(s,id)]));s=act(s,'A',{type:'CHOOSE_DRAW',draw:!bookDraw});if(bookDraw)s=finish(act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:book}));expect(gameStats(s,'A')).toEqual({...before,handLimit:6,chantLimit:2});expect(s.players.A!.hand).toHaveLength(bookDraw?5:6);expect(s.players.A!.hand).not.toContain(haja);expect(s.players.A!.revealed).toBe(false);for(const id of ['B','C','D']){expect(gameStats(s,id)).toEqual(others[id]);expect(viewFor(s,id).players.A!.open).toContain(haja);}s=next(act(s,'A',{type:'PASS_ACTION'}),'B');expect(s.players.A!.hand).toHaveLength(6);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===haja)).toHaveLength(1);});
it.each([false,true])('actual hand adjustment with Haja=%s retains its exact limit and rejects one excess card without disposal',hasHaja=>{let s=act(ready('haja-draw',hasHaja),'A',{type:'CHOOSE_DRAW',draw:true});if(hasHaja){s=next(act(s,'A',{type:'PASS_ACTION'}),'A','draw');s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});}const limit=hasHaja?6:5;expect(s.players.A!.hand).toHaveLength(limit+1);s=act(s,'A',{type:'PASS_ACTION'});reject(s,'A',{type:'END_TURN',discardIds:[]});const drop=s.players.A!.hand[0]!;s=finish(act(s,'A',{type:'END_TURN',discardIds:[drop]}));expect(s.players.A!.hand).toHaveLength(limit);expect(s.discard.filter(id=>id===drop)).toHaveLength(1);expect(s.seatOrder[s.turnSeat]).toBe('B');});
it.each([false,true])('actual sequential chant capacity with Haja=%s rejects the first excess and preserves private cards',hasHaja=>{let s=act(ready('haja-chants',hasHaja),'A',{type:'CHOOSE_DRAW',draw:hasHaja});s=act(s,'A',{type:'CHANT',cardInstanceId:ice});s=next(s);if(hasHaja){s=act(s,'A',{type:'CHANT',cardInstanceId:rift});s=next(s);}reject(s,'A',{type:'CHANT',cardInstanceId:hasHaja?mekai:rift});expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toEqual(hasHaja?[ice,rift]:[ice]);for(const id of ['B','C','D']){expect(viewFor(s,id).players.A!.chantCount).toBe(hasHaja?2:1);expect(viewFor(s,id).players.A!.chants.every(c=>c.face==='back')).toBe(true);}if(hasHaja){s=finish(act(s,'A',{type:'ATTACK',cardInstanceId:ice,targetIds:['B'],dedicated:false}));expect(s.players.B!.damage).toBe(7);expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toEqual([rift]);s=next(s);s=act(s,'A',{type:'CHANT',cardInstanceId:mekai});expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toEqual([rift,mekai]);}});
it.each([ice,rift])('actual Wish loss privately discards chant %s but retains six hand cards until the owners next hand adjustment',drop=>{let s=twoChants('haja-transfer');const hand=[...s.players.A!.hand];expect(hand).toHaveLength(6);s=steal(s);expect(gameStats(s,'A')).toMatchObject({handLimit:5,chantLimit:1});expect(gameStats(s,'B')).toMatchObject({handLimit:6,chantLimit:2});expect(s.players.A!.hand).toEqual(hand);const d=viewFor(s,'A').wishCapacity!;expect(d).toMatchObject({followerCount:0,chantCount:1,chantIds:[ice,rift]});for(const id of ['B','C','D'])expect(viewFor(s,id).wishCapacity).toBeNull();for(const [actor,chantIds] of [['B',[drop]],['A',[]],['A',[mekai]],['A',[ice,rift]]] as const)reject(s,actor,{type:'CHOOSE_WISH_CAPACITY',decisionId:d.decisionId,followerIds:[],chantIds:[...chantIds]});s=finish(act(JSON.parse(JSON.stringify(s)),'A',{type:'CHOOSE_WISH_CAPACITY',decisionId:d.decisionId,followerIds:[],chantIds:[drop]}));expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toEqual([ice,rift].filter(id=>id!==drop));expect(s.discard.filter(id=>id===drop)).toHaveLength(1);expect(s.players.A!.hand).toEqual(hand);s=next(s);expect(s.players.A!.hand).toEqual(hand);s=act(s,'A',{type:'PASS_ACTION'});reject(s,'A',{type:'END_TURN',discardIds:[]});s=finish(act(s,'A',{type:'END_TURN',discardIds:[hand[0]!]}));expect(s.players.A!.hand).toHaveLength(5);expect(s.players.B!.open).toContain(haja);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===haja)).toHaveLength(1);});
it('actual reacquisition of public Haja restores capacities but never recreates the discarded chant',()=>{let s=steal(twoChants('haja-return'));s=finish(act(s,'A',{type:'CHOOSE_WISH_CAPACITY',decisionId:viewFor(s,'A').wishCapacity!.decisionId,followerIds:[],chantIds:[ice]}));s=next(s);s=until(act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c3',mode:'wish'}),'wish');s=finish(act(s,'A',{type:'CHOOSE_WISH',decisionId:viewFor(s,'A').wish!.decisionId,source:{kind:'public',cardInstanceId:haja}}));expect(gameStats(s,'A')).toMatchObject({handLimit:6,chantLimit:2});expect(gameStats(s,'B')).toMatchObject({handLimit:5,chantLimit:1});expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toEqual([rift]);expect(s.discard.filter(id=>id===ice)).toHaveLength(1);expect(s.players.A!.open).toContain(haja);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId===haja)).toHaveLength(1);});
it('actual lethal Bow disposes Haja and both real chants without offering a dead owner capacity adjustment',()=>{let s=twoChants('haja-death');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['A'],dedicated:false}));expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.hand).toEqual([]);expect(s.players.A!.chants).toEqual([]);expect(s.players.A!.open).toEqual([]);expect(gameStats(s,'A')).toMatchObject({handLimit:5,chantLimit:1});for(const id of [haja,ice,rift])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.windows??[]).toEqual([]);expect(s.outcome).toBeUndefined();});
