import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until,passReclaims} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeHeavyFireScenario,heavyFireMode,type HeavyFireScenario} from '../../../apps/worker/test/fixtures/heavy-fire-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const rows=['fire-stream-ordinary','fire-stream-dedicated','raging-fire-ordinary','raging-fire-dedicated','raging-fire-chanted-dedicated'] as const;
function command(scenario:HeavyFireScenario){const m=heavyFireMode(scenario);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function prepared(scenario:HeavyFireScenario,options:Parameters<typeof makeHeavyFireScenario>[2]={}){const s=makeHeavyFireScenario(scenario,players,options),m=heavyFireMode(scenario);return m.chanted?chant(s,m.card):s;}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState,card:string){for(let n=0;n<100;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ANNIHILATION_TURN');}throw Error('ANNIHILATION_TURN_LIMIT');}
function chant(s:GameState,card:string){s=act(s,'A',{type:'CHANT',cardInstanceId:card});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return nextOwn(s,card);}
function claim(s:GameState,card:string){for(let n=0;n<300;n++){const d=viewFor(s,'A').reclaim;if(s.windows?.at(-1)?.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){expect(d.claims.map(c=>c.right)).toContain('base');return act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});}s=pass(s);}throw Error('ANNIHILATION_CLAIM');}
it.each(rows)('%s actual printed magic profile and use-level boundary with real chant or elected waiver',scenario=>{
 const m=heavyFireMode(scenario);for(const level of [m.use-1,m.use]){let s=act(prepared(scenario,{level}),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.use,effectLevel:m.effect,damage:m.damage,attributes:m.stream?['魔','炎']:['魔','炎','詠'],chant:!m.stream&&!m.dedicated,noChecks:m.dedicated,target:m.dedicated?'all':'one',maaiRequired:2});expect(f.fromChant??false).toBe(m.chanted);expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.damage,m.dedicated?m.damage:0,0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);}
});
it.each(rows)('%s actual per-target maai needs two different physical cards and rejects reusing the first',scenario=>{
 const m=heavyFireMode(scenario);for(const count of [1,2]){let s=until(act(prepared(scenario),'A',command(scenario)),'normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});if(count===2)s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([count===2?0:m.damage,m.dedicated?m.damage:0]);expect(s.discard).toContain('a2-p07-r1c1');expect(s.players.B!.hand.includes('a2-p07-r1c2')).toBe(count===1);}
});
it.each(rows)('%s actual Fate cancellation returns once and later reuse reapplies ordinary chant conditions',scenario=>{
 const m=heavyFireMode(scenario);let s=act(prepared(scenario),'A',command(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=pass(s);s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(claim(s,m.card));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.A!.chants).toEqual([]);expect(s.players.A!.hand.filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.reclaimUsage?.[m.name]?.baseSpent).toBe(true);s=nextOwn(s,m.card);if(!m.stream&&!m.dedicated){reject(s,'A',command(scenario));s=chant(s,m.card);}s=finish(act(s,'A',command(scenario)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage,m.dedicated?m.damage:0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual Evade prevents only its target while Soldier HP still reduces unavoided damage',scenario=>{
 const m=heavyFireMode(scenario);let s=until(act(prepared(scenario),'A',command(scenario)),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,m.dedicated?m.damage:0]);s=prepared(scenario,{follower:true});const guard=s.players.B!.followers[0]!.cardInstanceId;s=finish(act(s,'A',command(scenario)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage-1,m.dedicated?m.damage:0]);expect(s.discard.filter(id=>id===guard)).toHaveLength(1);
});
it.each(['fire-stream-dedicated','raging-fire-dedicated'] as const)('%s refuses foreign dedicated owner ordinary multiple targets and unsupported variant',scenario=>{
 const s=makeHeavyFireScenario(scenario,players),foreign=makeHeavyFireScenario(scenario,players,{owner:'侍大将のシン'});reject(foreign,'A',command(scenario));reject(s,'A',{...command(scenario),dedicated:false});reject(s,'A',{...command(scenario),techniqueVariant:'two-hit'});
});
it('Heavy fire stream refuses unprinted chant while raging ordinary requires real chant even at sufficient magic level',()=>{
 const stream=makeHeavyFireScenario('fire-stream-ordinary',players);reject(stream,'A',{type:'CHANT',cardInstanceId:'a2-p15-r3c3'});const raging=makeHeavyFireScenario('raging-fire-ordinary',players);reject(raging,'A',command('raging-fire-ordinary'));const s=chant(raging,'a2-p16-r1c3');reject(s,'A',{...command('raging-fire-ordinary'),targetIds:['B','C']});
});
