import {passReclaims} from './combat-helpers.js';
import {expect,it} from 'vitest';
import {transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,ready,until,finish,closeWindow} from './combat-helpers.js';
import {character,handCard,handCards,entropy} from './fixtures.js';
function setup(owner='獣使いのウパニシャット'){const s=ready();character(s,'A',owner);for(const id of ['B','C','D']){s.players[id]!.revealed=false;s.distances.A![id]='near';s.distances[id]!.A='near';}return s;}
function source(s:GameState,name:string,placed=false,actor='A'){const id=handCard(s,actor,name);if(placed){s.players[actor]!.hand=s.players[actor]!.hand.filter(x=>x!==id);s.players[actor]!.followers.push({cardInstanceId:id,revealed:false});}return id;}
function command(s:GameState,sources:{cardInstanceId:string;dedicated:boolean;targetIds:string[]}[]){return {type:'USE_FOLLOWER_ATTACK',abilityId:s.players.A!.characterId==='c2-p05-r1c2'?'c2-p05-r1c2-ab02':'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources} as const;}
it.each([
 ['獣使いのウパニシャット','グリフォン','地竜','炎竜','兵士','c2-p05-r1c2-ab02'],
 ['魔聖母ディア','兵士','小人族','竜王教団','グリフォン','c2-p06-r1c2-ab04'],
] as const)('%s selects three matching hand/placed sources without morale',(owner,first,second,third,excluded,abilityId)=>{
 let s=setup(owner);const a=source(s,first),b=source(s,second,true),c=source(s,third),wrong=source(s,excluded);
 const selected=[{cardInstanceId:a,dedicated:false,targetIds:['B']},{cardInstanceId:b,dedicated:false,targetIds:owner==='獣使いのウパニシャット'?['B','C','D']:['B']},{cardInstanceId:c,dedicated:false,targetIds:owner==='獣使いのウパニシャット'?['B','C','D']:['C']}];
 const before=JSON.stringify(s);expect(transition(s,{actorId:'A',command:command(s,[...selected,{cardInstanceId:wrong,dedicated:false,targetIds:['B']}])},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);
 expect(command(s,selected).abilityId).toBe(abilityId);s=act(s,'A',command(s,selected));expect(s.resolution).toEqual(expect.arrayContaining([a,b,c]));expect(s.players.A!.hand).not.toContain(a);expect(s.players.A!.hand).not.toContain(c);expect(s.players.A!.followers).toEqual([]);
 expect(s.players.A!.hand).toContain(wrong);s=finish(s);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(discardIds(s)).toEqual(expect.arrayContaining([a,b,c]));expect(s.resolution).toEqual([]);
});
it('actual Upa reserves hand Griffin and placed Earth Dragon before cancellable grant and resolves distinct techniques in one group',()=>{
 let s=setup();const griffin=source(s,'グリフォン');const earth=source(s,'地竜',true);
 expect((viewFor(s,'A') as any).followerBundleOptions).toEqual(expect.arrayContaining([expect.objectContaining({abilityId:'c2-p05-r1c2-ab02'})]));
 s=act(s,'A',command(s,[{cardInstanceId:griffin,dedicated:false,targetIds:['B']},{cardInstanceId:earth,dedicated:false,targetIds:['B','C','D']}]));
 expect(s.resolution).toEqual(expect.arrayContaining([griffin,earth]));expect(s.players.A!.followers).toEqual([]);expect(viewFor(s,'A').currentAction).toMatchObject({source:'ability'});
 s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(Object.keys(s.groups!)).toHaveLength(1);expect(g.targets.map(t=>t.hits.map(h=>[h.index,h.technique?.effectLevel,h.damage]))).toEqual([[[0,5,8],[1,5,8],[2,6,8]],[[2,6,8]],[[2,6,8]]]);
 s=finish(s);expect(s.players.B!.damage).toBe(24);expect(s.players.C!.damage).toBe(8);expect(discardIds(s)).toEqual(expect.arrayContaining([griffin,earth]));expect(s.resolution).toEqual([]);
});
it('actual Dia normal Dwarf snapshots its own warrior and magic is an independent source',()=>{
 let s=setup('魔聖母ディア');const dwarf=source(s,'小人族',true);const cult=source(s,'竜王教団');s=act(s,'A',command(s,[{cardInstanceId:dwarf,dedicated:false,targetIds:['B']},{cardInstanceId:cult,dedicated:false,targetIds:['C']}]));s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.hits.length)).toEqual([3,1]);expect(g.targets[0]!.hits[0]!.technique).toMatchObject({useLevel:0,effectLevel:0,noChecks:false});expect(g.targets[1]!.hits[0]!.technique).toMatchObject({damage:2,noChecks:false});s=finish(s);expect(s.resolution).toEqual([]);
});
it('grant cancellation spends entire bundle and consumes action',()=>{let s=setup();const id=source(s,'グリフォン',true);const other=source(s,'炎竜');const cancel=handCard(s,'A','命運凶変');s=act(s,'A',command(s,[{cardInstanceId:id,dedicated:false,targetIds:['B']},{cardInstanceId:other,dedicated:false,targetIds:['B','C','D']}]));const ability=Object.values(s.abilities!)[0]!;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:cancel,mode:'cancel-ability',targetAbilityId:ability.id});s=finish(s);expect(discardIds(s)).toEqual(expect.arrayContaining([id,other]));expect(s.players.B!.damage).toBe(0);expect(s.phase).toBe('withdrawal');expect(s.resolution).toEqual([]);});
it('a canceled constituent leaves later selected techniques intact',()=>{let s=setup();const id=source(s,'グリフォン');const other=source(s,'炎竜');const cancel=handCard(s,'A','命運凶変');s=act(s,'A',command(s,[{cardInstanceId:id,dedicated:false,targetIds:['B']},{cardInstanceId:other,dedicated:false,targetIds:['B','C','D']}]));s=closeWindow(s);const a=Object.values(s.actions!).find(a=>a.cardInstanceId===id)!;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:cancel,mode:'cancel',targetActionId:a.id});s=until(s,'normal-defense');expect(Object.values(s.groups!)[0]!.targets[0]!.hits).toHaveLength(1);s=finish(s);expect(s.players.B!.damage).toBe(12);expect(discardIds(s)).toEqual(expect.arrayContaining([id,other]));});
it('Water stop uses actual Water source and expires on source seat arrival even when that seat is inactive',()=>{let s=setup();const water=source(s,'水竜');const griffin=source(s,'グリフォン');s=finish(act(s,'A',command(s,[{cardInstanceId:griffin,dedicated:false,targetIds:['B']},{cardInstanceId:water,dedicated:false,targetIds:['B','C','D']}])));expect(s.players.C!.statuses).toEqual(expect.arrayContaining([expect.objectContaining({kind:'stopped',timing:'source-turn',sourceActorId:'A',sourceCardInstanceId:water})]));s.players.C!.statuses!.push({id:'other',kind:'stopped',timing:'fixed-turns',remainingTurns:2});s.players.A!.presence='otherworld';s.turnSeat=3;s.phase='hand-adjustment';s=act(s,'D',{type:'END_TURN',discardIds:s.players.D!.hand.slice(5)});expect(s.turnSeat).toBe(2);expect(s.players.C!.statuses!.map(x=>x.id)).toEqual(['other']);expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toEqual([]);});
it('Dia Fairy rolls use level before excess checks and independent damage afterwards',()=>{let s=setup('魔聖母ディア');const fairy=source(s,'妖精族');s=act(s,'A',command(s,[{cardInstanceId:fairy,dedicated:false,targetIds:['B']}]));s=closeWindow(s);s=closeWindow(s,[4]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'technique-value',kind:'numeric',faces:[4]});s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(Object.values(s.actions!)[0]!.technique).toMatchObject({useLevel:7,effectLevel:7,noChecks:false});s=until(s,'damage');s=closeWindow(s,[2]);s=until(s,'normal-defense');const a=Object.values(s.actions!)[0]!;expect(a.technique).toMatchObject({useLevel:7,effectLevel:7,damage:6});expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(7);s=finish(s);});
const bottoms=[['兵士',1,1,1],['オーク',2,3,1],['辺境警備隊',2,2,1],['傭兵',3,4,1],['黒騎士団',4,5,1],['聖騎士団',4,4,1],['王立騎士団',4,5,1],['有翼族',7,12,1],['闇の聖女',5,6,1],['女性親衛隊',4,6,1],['小人族',0,6,3],['竜王教団',6,2,1],['女神官のシャリア',5,6,1],['妖精族',4,5,1],['親衛隊',6,8,1],['グリフォン',5,8,2],['炎竜',6,12,1],['地竜',6,8,1],['飛竜',6,9,1],['水竜',6,5,1]] as const;
it.each(bottoms)('actual ordinary %s bottom is usable without another character dedication',(name,level,damage,hits)=>{let s=setup(['グリフォン','炎竜','地竜','飛竜','水竜'].includes(name)?'獣使いのウパニシャット':'魔聖母ディア');const id=source(s,name,true);const all=['有翼族','炎竜','地竜','飛竜','水竜'].includes(name);s=act(s,'A',command(s,[{cardInstanceId:id,dedicated:false,targetIds:all?['B','C','D']:['B']}]));s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.hits).toHaveLength(hits);expect(g.targets[0]!.hits[0]!.technique).toMatchObject({useLevel:level,effectLevel:level,damage,noChecks:false});expect(g.targets.map(t=>t.actorId)).toEqual(all?['B','C','D']:['B']);s=finish(s);expect(s.resolution).toEqual([]);expect(discardIds(s)).toContain(id);});
it('only explicitly elected Upa Griffin dedication grants selected all and use-check waiver',()=>{for(const dedicated of [false,true]){let s=setup();s.players.A!.permanent={warrior_level:-5};const id=source(s,'グリフォン');const targets=dedicated?['B','C']:['B'];expect((viewFor(s,'A') as any).followerBundleOptions[0].sources.filter((o:any)=>o.cardInstanceId===id).map((o:any)=>[o.dedicated,o.targetMode])).toEqual([[false,'one'],[true,'selected-all']]);s=act(s,'A',command(s,[{cardInstanceId:id,dedicated,targetIds:targets}]));const a=Object.values(s.actions!)[0]!;expect(a.technique.noChecks).toBe(dedicated);expect(a.checks.length===0).toBe(dedicated);s=finish(s);}});
it('per-source normal defense and public stats follow later Wyvern, skipping absent targets',()=>{let s=setup();const griffin=source(s,'グリフォン');const wyvern=source(s,'飛竜');const evade=handCard(s,'B','見切る');s=act(s,'A',command(s,[{cardInstanceId:griffin,dedicated:false,targetIds:['C']},{cardInstanceId:wyvern,dedicated:false,targetIds:['B','C','D']}]));s=until(s,'normal-defense');expect(viewFor(s,'A').currentAttack).toMatchObject({hitIndex:0,targetId:'C',technique:{effectLevel:5}});s=closeWindow(s);s=closeWindow(s);expect(viewFor(s,'A').currentAttack).toMatchObject({hitIndex:2,targetId:'B',technique:{effectLevel:6},defenseRestrictions:{evadeProhibited:true}});expect(viewFor(s,'A').currentAction).toMatchObject({cardInstanceId:wyvern,technique:{effectLevel:6,damage:9}});expect((viewFor(s,'A') as any).followerBundle.currentSourceIndex).toBe(1);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:evade,dedicated:false}},entropy())).toMatchObject({ok:false,code:'ILLEGAL_DEFENSE'});s=finish(s);});
it('current incoming effect rejects mirror against later high Winged source rather than earlier Soldier',()=>{let s=setup('魔聖母ディア');const soldier=source(s,'兵士');const winged=source(s,'有翼族');const mirror=handCard(s,'B','ミラーシールド');s=until(act(s,'A',command(s,[{cardInstanceId:soldier,dedicated:false,targetIds:['B']},{cardInstanceId:winged,dedicated:false,targetIds:['B','C','D']}])),'normal-defense');expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy()).ok).toBe(true);s=closeWindow(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy())).toMatchObject({ok:false,code:'ILLEGAL_DEFENSE'});s=finish(s);});
it('one follower morale and per-source HP persist even across mixed revivable and overcap destruction',()=>{let s=setup('魔聖母ディア');const knight=source(s,'黒騎士団');const priest=source(s,'女神官のシャリア');const skeleton=source(s,'スケルトン',true,'B');s=until(act(s,'A',command(s,[{cardInstanceId:knight,dedicated:false,targetIds:['B']},{cardInstanceId:priest,dedicated:false,targetIds:['B']}])),'follower-start');const g=Object.values(s.groups!)[0]!;expect(g.targets[0]!.followerDefense).toHaveLength(1);s=finish(s);expect(s.players.B!.damage).toBe(3);expect(discardIds(s)).toContain(skeleton);expect(s.players.B!.followers).toEqual([]);});
it('Royal reflects each actual low source with its own immutable provenance and resumes snapshot',()=>{let s=setup('魔聖母ディア');s.players.A!.permanent={endurance:100};const soldier=source(s,'兵士',true);const knight=source(s,'黒騎士団');const royal=source(s,'王立騎士団',true,'B');s=until(act(s,'A',command(s,[{cardInstanceId:soldier,dedicated:false,targetIds:['B']},{cardInstanceId:knight,dedicated:false,targetIds:['B']}])),'follower-start');s=closeWindow(s);s=closeWindow(s);s=closeWindow(s);const child=Object.values(s.groups!).find(g=>g.attackerId==='B')!;expect(child.sourceCardInstanceIds).toEqual([soldier]);expect(s.actions![child.actionId]).toMatchObject({effectSourceCardInstanceId:soldier});s=finish(s);expect(s.players.A!.damage).toBe(6);expect(s.players.B!.damage).toBe(0);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toContain(royal);});
it('independent numeric sources share exact saved whole rolls only inside their own constituent',()=>{let s=setup('魔聖母ディア');const cult=source(s,'竜王教団');const winged=source(s,'有翼族');s=act(s,'A',command(s,[{cardInstanceId:cult,dedicated:false,targetIds:['B']},{cardInstanceId:winged,dedicated:false,targetIds:['B','C','D']}]));s=until(s,'damage');s=closeWindow(s,[2,3]);s=closeWindow(s);s=until(s,'damage');s=closeWindow(s,[5,6]);s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.hits.map(h=>h.damage))).toEqual([[5,21],[21],[21]]);expect(g.sourceDamageRollIds).toHaveLength(2);expect(g.targets[0]!.hits.map(h=>h.damageRollId)).toEqual(g.sourceDamageRollIds);s=finish(s);});
it('forged ability/source/targets and inactive grants reject before any cost',()=>{const s=setup();const id=source(s,'グリフォン');const missing=source(s,'ゴブリン');const base=command(s,[{cardInstanceId:id,dedicated:false,targetIds:['B']}]);for(const extra of [{sources:[]},{sources:[...base.sources,...base.sources]},{sources:[{...base.sources[0],cardInstanceId:missing}]},{sources:[{...base.sources[0],cardInstanceId:'a2-p18-r3c3'}]},{sources:[{...base.sources[0],targetIds:['B','C']}]},{abilityId:'c2-p06-r1c2-ab04'},{targetEventId:'stale'},{grant:true}]){const before=JSON.stringify(s);expect(transition(s,{actorId:'A',command:{...base,...extra}} as any,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}for(const kind of ['stopped','ability-disabled'] as const){const blocked=structuredClone(s);blocked.players.A!.statuses=[{id:'block',kind,modifiers:[0],nextCheck:0}];expect(transition(blocked,{actorId:'A',command:base} as any,entropy()).ok).toBe(false);expect((viewFor(blocked,'A') as any).followerBundleOptions).toEqual([]);}expect(transition(s,{actorId:'A',command:{type:'USE_ABILITY',abilityId:base.abilityId,targetEventId:base.targetEventId}},entropy()).ok).toBe(false);});
it('one failed use check drops only its source and later selected magic still attacks',()=>{let s=setup('魔聖母ディア');const knight=source(s,'黒騎士団',true);const cult=source(s,'竜王教団');s=act(s,'A',command(s,[{cardInstanceId:knight,dedicated:false,targetIds:['B']},{cardInstanceId:cult,dedicated:false,targetIds:['B']}]));s=until(s,'before-roll');s=closeWindow(s,[6,6]);s=closeWindow(s);expect((viewFor(s,'A') as any).followerBundle.sources[0].stage).toBe('failed');s=until(s,'normal-defense');expect(Object.values(s.groups!)[0]!.sourceCardInstanceIds).toEqual([cult]);s=finish(s);expect(s.players.B!.damage).toBe(2);expect(discardIds(s)).toEqual(expect.arrayContaining([knight,cult]));expect(Object.keys(s.actions!)).toEqual([]);});
it.each(['stopped','ability-disabled','owner'] as const)('grant invalidated by %s spends all costs and leaves no pending source',reason=>{let s=setup();const id=source(s,'グリフォン',true);s=act(s,'A',command(s,[{cardInstanceId:id,dedicated:false,targetIds:['B']}]));if(reason==='owner')character(s,'A','侍大将のシン');else s.players.A!.statuses=[{id:'disable',kind:reason,modifiers:[0],nextCheck:0}];s=finish(s);expect(discardIds(s)).toContain(id);expect(s.players.B!.damage).toBe(0);expect(Object.keys(s.actions!)).toEqual([]);expect(Object.keys(s.abilities!)).toEqual([]);expect(s.phase).toBe('withdrawal');});
it('all failed constituents proceed to withdrawal without producing a group',()=>{let s=setup('魔聖母ディア');const knight=source(s,'黒騎士団');s=act(s,'A',command(s,[{cardInstanceId:knight,dedicated:false,targetIds:['B']}]));s=until(s,'before-roll');s=closeWindow(s,[6,6]);s=finish(s);expect(discardIds(s)).toContain(knight);expect(s.phase).toBe('withdrawal');expect(Object.keys(s.groups??{})).toEqual([]);expect(Object.keys(s.followerBundles??{})).toEqual([]);});
it('Earth destroys reached non-sky Flying follower before HP and Sky ship nullifies only its own Earth hit',()=>{let s=setup();const earth=source(s,'地竜');const fire=source(s,'炎竜');const imp=source(s,'小悪魔',true,'B');const ship=source(s,'歌う船',true,'C');s=finish(act(s,'A',command(s,[{cardInstanceId:earth,dedicated:false,targetIds:['B','C','D']},{cardInstanceId:fire,dedicated:false,targetIds:['B','C','D']}])));expect(discardIds(s)).toContain(imp);expect(s.players.B!.damage).toBe(20);expect(s.players.C!.damage).toBe(10);expect(discardIds(s)).toContain(ship);});
it('normal mirror reflects later Water with original card and reflector clock, then resumes exact parent slot',()=>{let s=setup();s.players.A!.permanent={endurance:100};s.players.C!.permanent={endurance:100};const griffin=source(s,'グリフォン',true);const water=source(s,'水竜');const mirror=handCard(s,'B','ミラーシールド');s=until(act(s,'A',command(s,[{cardInstanceId:griffin,dedicated:false,targetIds:['C']},{cardInstanceId:water,dedicated:false,targetIds:['B','C','D']}])),'normal-defense');s=closeWindow(s);s=closeWindow(s);s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false});for(let n=0;Object.keys(s.groups!).length<2&&n<40;n++)s=closeWindow(s);const child=Object.values(s.groups!).find(g=>g.attackerId==='B')!;expect(s.actions![child.actionId]).toMatchObject({effectSourceCardInstanceId:water,technique:{damage:5}});expect(child.sourceCardInstanceIds).toEqual([water]);expect(s.players.A!.followers).toEqual([]);s=finish(s);expect(s.players.A!.statuses).toEqual(expect.arrayContaining([expect.objectContaining({timing:'source-turn',sourceActorId:'B',sourceCardInstanceId:water})]));expect(s.players.C!.damage).toBe(21);expect(s.players.D!.damage).toBe(5);expect(s.resolution).toEqual([]);});
it('incoming-effect parry reads later independent warrior level',()=>{let s=setup('魔聖母ディア');const cult=source(s,'竜王教団');const knight=source(s,'黒騎士団');const parry=handCard(s,'B','受け流し');s=until(act(s,'A',command(s,[{cardInstanceId:cult,dedicated:false,targetIds:['B']},{cardInstanceId:knight,dedicated:false,targetIds:['B']}])),'normal-defense');expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:parry,dedicated:false}},entropy())).toMatchObject({ok:false,code:'ILLEGAL_DEFENSE'});s=closeWindow(s);s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:parry,dedicated:false});expect(Object.values(s.actions!).find(a=>a.cardInstanceId===parry)!.technique).toMatchObject({useLevel:4,effectLevel:4});s=finish(s);expect(s.players.B!.damage).toBe(2);});
it('one advance cancels same-source target maai only, leaving later sources a new exchange',()=>{let s=setup();const fire=source(s,'炎竜');const water=source(s,'水竜');const [first,second]=handCards(s,['B','C'],'間合い／休息');const advance=handCard(s,'A','踏み込み／殴る');s=until(act(s,'A',command(s,[{cardInstanceId:fire,dedicated:false,targetIds:['B','C','D']},{cardInstanceId:water,dedicated:false,targetIds:['B','C','D']}])),'normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:first}));s=passReclaims(act(s,'C',{type:'PLAY_MAAI',cardInstanceId:second}));s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('defense-advance');s=passReclaims(act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:advance}));s=closeWindow(s);s=closeWindow(s);s=until(s,'normal-defense');expect(viewFor(s,'A').currentAttack!.hitIndex).toBe(1);const g=Object.values(s.groups!)[0]!;expect(g.maai!.advances).toEqual([]);expect(g.targets[0]!.hits[0]!.defended).toBe(false);s=finish(s);});
it('all target damage is committed together with per-hit source provenance after final target results',()=>{let s=setup('魔聖母ディア');const soldier=source(s,'兵士');const cult=source(s,'竜王教団');s.players.B!.damage=viewFor(s,'B').self.stats.endurance-1;s.players.C!.damage=viewFor(s,'C').self.stats.endurance-1;s=until(act(s,'A',command(s,[{cardInstanceId:soldier,dedicated:false,targetIds:['B']},{cardInstanceId:cult,dedicated:false,targetIds:['C']}])),'normal-defense');s=until(s,'hit');expect(s.players.B!.presence??'active').toBe('active');expect(s.players.C!.presence??'active').toBe('active');s=until(s,'death-gift');const batch=s.lifecycle!.find(t=>t.kind==='death-batch')!;expect(batch).toMatchObject({intents:expect.arrayContaining([expect.objectContaining({sourceCardInstanceId:soldier,damage:1,targetId:'B'}),expect.objectContaining({sourceCardInstanceId:cult,damage:2,targetId:'C'})])});});
it('post-follower hit window projects the actual warrior constituent after preceding magic',()=>{let s=setup('魔聖母ディア');const cult=source(s,'竜王教団');const soldier=source(s,'兵士');s=until(act(s,'A',command(s,[{cardInstanceId:cult,dedicated:false,targetIds:['B']},{cardInstanceId:soldier,dedicated:false,targetIds:['B']}])),'hit-abilities');expect(viewFor(s,'A').currentAction).toMatchObject({cardInstanceId:soldier,technique:{effectLevel:1}});expect(viewFor(s,'A').currentAttack).toMatchObject({hitIndex:1,technique:{effectLevel:1}});expect((viewFor(s,'A') as any).followerBundle.currentSourceIndex).toBe(1);s=finish(s);});
it('range, mandatory completeness, silence and forged dedication fail atomic validation with one otherwise legal source',()=>{for(const owner of ['獣使いのウパニシャット','魔聖母ディア']){const s=setup(owner);const first=source(s,owner==='魔聖母ディア'?'兵士':'グリフォン');const magic=source(s,owner==='魔聖母ディア'?'有翼族':'飛竜',true);const sources=[{cardInstanceId:first,dedicated:false,targetIds:['B']},{cardInstanceId:magic,dedicated:false,targetIds:['B','C','D']}];for(const targetIds of [['B'],['A','B','C','D']])expect(transition(s,{actorId:'A',command:command(s,[sources[0]!,{...sources[1]!,targetIds}])} as any,entropy()).ok).toBe(false);expect(transition(s,{actorId:'A',command:command(s,[sources[0]!,{...sources[1]!,dedicated:true}])} as any,entropy()).ok).toBe(false);s.players.A!.statuses=[{id:'silence',kind:'silenced',modifiers:[0],nextCheck:0}];const before=JSON.stringify(s);expect(transition(s,{actorId:'A',command:command(s,sources)} as any,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);if(owner==='魔聖母ディア'){s.players.A!.statuses=[];s.distances.A!.B='far';expect(transition(s,{actorId:'A',command:command(s,sources)} as any,entropy()).ok).toBe(false);}}});
it('private source options and unchosen identities stay private; spent bundle has no hidden ability identifiers',()=>{let s=setup();const selected=source(s,'グリフォン',true);const unchosen=source(s,'炎竜');expect((viewFor(s,'B') as any).followerBundleOptions).toEqual([]);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(unchosen);s=act(s,'A',command(s,[{cardInstanceId:selected,dedicated:false,targetIds:['B']}]));const other=viewFor(s,'B');expect(other.currentAction).toMatchObject({source:'ability',label:'特殊能力'});expect(JSON.stringify(other)).not.toContain('c2-p05-r1c2');expect((other as any).followerBundle).toMatchObject({sources:[{cardInstanceId:selected,sourceZone:'followers',dedicated:false,stage:'reserved'}]});expect(JSON.stringify(other)).not.toContain(unchosen);s=finish(s);expect((viewFor(s,'A') as any).followerBundle).toBe(null);expect(s.windows).toEqual([]);expect(s.resolution).toEqual([]);expect(Object.keys(s.followerBundles!)).toEqual([]);});
it.each(['active','otherworld','dead'] as const)('Water expiry at %s source seat retains unrelated stops and never asks recovery',presence=>{let s=setup();s.players.B!.permanent={endurance:100};s.players.C!.permanent={endurance:100};const water=source(s,'水竜');s=finish(act(s,'A',command(s,[{cardInstanceId:water,dedicated:false,targetIds:['B','C','D']}])));s.players.A!.presence=presence;s.players.C!.statuses!.push({id:'unrelated',kind:'stopped',modifiers:[-1],nextCheck:0});s.turnSeat=3;s.phase='hand-adjustment';s=act(s,'D',{type:'END_TURN',discardIds:s.players.D!.hand.slice(5)});expect(s.players.C!.statuses).toEqual([expect.objectContaining({id:'unrelated'})]);expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toEqual([]);});
it('legalChoices exposes bundle command exactly when private validated bundle options exist',()=>{const s=setup();source(s,'地竜');expect(viewFor(s,'A').legalChoices).toContain('USE_FOLLOWER_ATTACK');expect(viewFor(s,'B').legalChoices).not.toContain('USE_FOLLOWER_ATTACK');s.players.A!.statuses=[{id:'silence',kind:'silenced',modifiers:[0],nextCheck:0}];expect(viewFor(s,'A').legalChoices).not.toContain('USE_FOLLOWER_ATTACK');});
it('dedicated Lia prayer reservation returns at bundle event completion without a stale paid-source continuation',()=>{let s=setup();character(s,'C','リーア姫');const id=source(s,'グリフォン');const prayer=handCard(s,'C','必勝の祈り');s=until(act(s,'A',command(s,[{cardInstanceId:id,dedicated:false,targetIds:['B']}])),'effect-level');s=act(s,'A',{type:'PASS'});s=act(s,'B',{type:'PASS'});const action=Object.values(s.actions!)[0]!;s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:action.id,dedicated:true});s=finish(s);expect(s.reclaimReservations).toEqual([]);expect(s.players.C!.hand).toContain(prayer);expect(Object.keys(s.actions!)).toEqual([]);});
it('actual Sherim White Light counter child resumes later constituent without settling its parent damage early',()=>{let s=setup('魔聖母ディア');character(s,'B','白魔術師シェリム');s.players.A!.permanent={endurance:100};const soldier=source(s,'兵士');const knight=source(s,'黒騎士団');const counter=handCard(s,'B','白光');s=until(act(s,'A',command(s,[{cardInstanceId:soldier,dedicated:false,targetIds:['B']},{cardInstanceId:knight,dedicated:false,targetIds:['B']}])),'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:true});for(let n=0;Object.keys(s.groups!).length<2&&n<40;n++)s=passReclaims(closeWindow(s));const parent=Object.values(s.groups!).find(g=>g.attackerId==='A')!;expect(parent.targets[0]!.hits.map(h=>h.defended)).toEqual([true,false]);expect(s.players.B!.damage).toBe(0);for(let n=0;Object.keys(s.groups!).length>1&&n<50;n++)s=passReclaims(closeWindow(s));expect(s.windows!.at(-1)!.kind).toBe('lifecycle-boundary');expect(s.players.B!.damage).toBe(0);s=until(s,'normal-defense');expect(viewFor(s,'B').currentAttack).toMatchObject({hitIndex:1,targetId:'B',technique:{effectLevel:4}});expect(s.players.A!.damage).toBe(6);s=finish(s);expect(s.players.B!.damage).toBe(5);expect(s.resolution).toEqual([]);});

it.each([
 ['竜王教団','兵士',6,1,true],
 ['親衛隊','兵士',6,1,true],
 ['兵士','親衛隊',1,6,false],
 ['兵士','竜王教団',1,6,false],
] as const)('Beast dynamic parry co-source uses actual later %s → %s school and level', (firstName,lastName,firstLevel,currentLevel,allowed)=>{
 let s=setup('魔聖母ディア');character(s,'B','獣使いのウパニシャット');
 s.players.B!.permanent={warrior_level:2-viewFor(s,'B').self.stats.warrior_level};
 expect(viewFor(s,'B').self.stats.warrior_level).toBe(2);
 const first=source(s,firstName);const last=source(s,lastName);
 const beast=handCard(s,'B','獣王剣');const parry=handCard(s,'B','受け流し');
 s=until(act(s,'A',command(s,[{cardInstanceId:first,dedicated:false,targetIds:['B']},{cardInstanceId:last,dedicated:false,targetIds:['B']}])),'normal-defense');
 s=closeWindow(s);
 const parent=Object.values(s.groups!)[0]!;
 expect(parent.technique.effectLevel).toBe(firstLevel);
 expect(viewFor(s,'B').currentAttack).toMatchObject({hitIndex:1,technique:{effectLevel:currentLevel}});
 const option=viewFor(s,'B').combinationOptions.find(o=>o.cardInstanceId===beast);
 expect(option?.coSources.some(c=>c.cardInstanceId===parry&&c.dedicated===false)??false).toBe(allowed);
 const defense={type:'PLAY_DEFENSE' as const,cardInstanceId:beast,dedicated:true,coSource:{cardInstanceId:parry,dedicated:false}};
 if(allowed){
  expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:parry,dedicated:false}},entropy()).ok).toBe(true);
  s=act(s,'B',defense);
  const action=Object.values(s.actions!).find(a=>a.cardInstanceId===beast)!;
  expect(action.technique).toMatchObject({useLevel:6,effectLevel:6,damage:10});
  expect(action.coSource!.technique).toMatchObject({useLevel:currentLevel,effectLevel:currentLevel});
  expect(s.resolution).toEqual(expect.arrayContaining([beast,parry]));
 }else{
  const before=JSON.stringify(s);
  expect(transition(s,{actorId:'B',command:defense},entropy())).toMatchObject({ok:false});
  expect(JSON.stringify(s)).toBe(before);
  expect(s.players.B!.hand).toEqual(expect.arrayContaining([beast,parry]));
 }
 s=finish(s);expect(s.resolution).toEqual([]);
 if(allowed)expect(discardIds(s)).toEqual(expect.arrayContaining([beast,parry]));
});

const B4_BUNDLES = [
 ['獣使いのウパニシャット','グリフォン','地竜','c2-p05-r1c2-ab02'],
 ['魔聖母ディア','兵士','竜王教団','c2-p06-r1c2-ab04'],
] as const;
it.each(B4_BUNDLES)('%s %s %s %s freezes ordered hand and placed declarations before parent cancellation',(owner,first,second,abilityId)=>{
 let s=setup(owner);const a=source(s,first),b=source(s,second,true),cancel=handCard(s,'A','命運凶変');
 const choices=[{cardInstanceId:b,dedicated:false,targetIds:owner==='魔聖母ディア'?['C']:['B','C','D']},{cardInstanceId:a,dedicated:owner!=='魔聖母ディア',targetIds:['B']}];
 s=act(s,'A',command(s,choices));
 const bundle=Object.values(s.followerBundles!)[0]!;expect(bundle.abilityId).toBe(abilityId);
 expect(bundle.actionIds.map(id=>{const a=s.actions![id]!;return {cardInstanceId:a.cardInstanceId,dedicated:a.followerDedicated,targetIds:a.targetIds,sourceZone:a.sourceZone};})).toEqual(choices.map((c,i)=>({...c,sourceZone:i===0?'followers':'hand'})));
 expect(s.resolution).toEqual(expect.arrayContaining([a,b]));expect(s.players.A!.hand).not.toContain(a);expect(s.players.A!.followers).toEqual([]);
 s=JSON.parse(JSON.stringify(s));const ability=Object.values(s.abilities!)[0]!;
 s=finish(act(s,'A',{type:'PLAY_REACTION',cardInstanceId:cancel,mode:'cancel-ability',targetAbilityId:ability.id}));
 for(const id of [a,b])expect(discardIds(s).filter(c=>c===id)).toHaveLength(1);
 for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(0);
 expect(s.phase).toBe('withdrawal');expect(s.turnSeat).toBe(0);expect(s.resolution).toEqual([]);expect(s.followerBundles).toEqual({});
});
it.each(B4_BUNDLES)('%s %s %s %s child cancellation preserves the later source',(owner,first,second,_abilityId)=>{
 let s=setup(owner);const a=source(s,first),b=source(s,second,true),cancel=handCard(s,'A','命運凶変');
 const choices=[{cardInstanceId:a,dedicated:false,targetIds:['B']},{cardInstanceId:b,dedicated:false,targetIds:owner==='魔聖母ディア'?['B']:['B','C','D']}];
 s=closeWindow(act(s,'A',command(s,choices)));
 const child=Object.values(s.actions!).find(c=>c.cardInstanceId===a)!;
 s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:cancel,mode:'cancel',targetActionId:child.id});
 s=until(s,'normal-defense');const groups=Object.values(s.groups!);expect(groups).toHaveLength(1);
 expect(groups[0]!.targets[0]!.hits).toHaveLength(1);
 expect(groups[0]!.targets[0]!.hits[0]!.damage).toBe(owner==='魔聖母ディア'?2:8);
 s=finish(s);expect(s.players.B!.damage).toBe(owner==='魔聖母ディア'?2:8);
 for(const id of [a,b])expect(discardIds(s).filter(c=>c===id)).toHaveLength(1);
 expect(s.resolution).toEqual([]);expect(s.phase).toBe('withdrawal');
});
it.each(B4_BUNDLES)('%s %s %s %s morale waiver retains failed use check and later source',(owner,first,second,_abilityId)=>{
 let s=setup(owner);s.players.A!.permanent={warrior_level:-10};
 const a=source(s,first),b=source(s,second,true);
 s=act(s,'A',command(s,[{cardInstanceId:a,dedicated:false,targetIds:['B']},{cardInstanceId:b,dedicated:false,targetIds:owner==='魔聖母ディア'?['B']:['B','C','D']}]));
 const child=Object.values(s.actions!).find(c=>c.cardInstanceId===a)!;
 expect(child.technique.noChecks).toBe(false);expect(child.checks.length).toBeGreaterThan(0);
 s=until(s,'before-roll');s=closeWindow(s,[6,6]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',rollerId:'A',success:false});
 s=finish(s);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toEqual([]);
 expect(s.players.B!.damage).toBe(owner==='魔聖母ディア'?2:8);
 for(const id of [a,b])expect(discardIds(s).filter(c=>c===id)).toHaveLength(1);
 expect(s.phase).toBe('withdrawal');expect(s.resolution).toEqual([]);
});
it.each(B4_BUNDLES)('%s %s %s %s keeps independent values in one defense group',(owner,first,second,_abilityId)=>{
 let s=setup(owner);s.players.B!.permanent={endurance:100};const a=source(s,first),b=source(s,second,true);
 s=until(act(s,'A',command(s,[{cardInstanceId:a,dedicated:false,targetIds:['B']},{cardInstanceId:b,dedicated:false,targetIds:owner==='魔聖母ディア'?['B']:['B','C','D']}])),'normal-defense');
 const groups=Object.values(s.groups!);expect(groups).toHaveLength(1);
 const hits=groups[0]!.targets.find(t=>t.actorId==='B')!.hits;
 expect(hits.map(h=>[h.technique!.useLevel,h.technique!.effectLevel,h.damage])).toEqual(owner==='魔聖母ディア'?[[1,1,1],[6,6,2]]:[[5,5,8],[5,5,8],[6,6,8]]);
 s=finish(s);expect(s.players.B!.damage).toBe(owner==='魔聖母ディア'?3:24);
 expect(s.groups).toEqual({});expect(s.resolution).toEqual([]);
});
it.each(['獣使いのウパニシャット','魔聖母ディア'] as const)('%s shared advance stops at the next source hit index',owner=>{
 let s=setup(owner);for(const p of Object.values(s.players))p.permanent={endurance:100};
 const firstSource=source(s,owner==='魔聖母ディア'?'有翼族':'炎竜'),lastSource=source(s,owner==='魔聖母ディア'?'竜王教団':'水竜');
 const [first,second,later]=handCards(s,['B','C','B'],'間合い／休息');const advance=handCard(s,'A','踏み込み／殴る');
 s=until(act(s,'A',command(s,[{cardInstanceId:firstSource,dedicated:false,targetIds:['B','C','D']},{cardInstanceId:lastSource,dedicated:false,targetIds:owner==='魔聖母ディア'?['B']:['B','C','D']}])),'normal-defense');
 s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:first}));s=passReclaims(act(s,'C',{type:'PLAY_MAAI',cardInstanceId:second}));s=closeWindow(s);
 expect(s.windows!.at(-1)!.kind).toBe('defense-advance');s=passReclaims(act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:advance}));
 s=closeWindow(s);s=closeWindow(s);s=until(s,'normal-defense');expect(viewFor(s,'A').currentAttack).toMatchObject({hitIndex:1,targetId:'B'});
 const group=Object.values(s.groups!)[0]!;expect(group.maai!.advances).toEqual([]);
 for(const id of ['B','C'])expect(group.targets.find(t=>t.actorId===id)!.hits[0]!.defended).toBe(false);
 s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:later}));s=finish(s);
 expect(s.players.B!.damage).toBe(12); // The later source's maai is not canceled by the earlier advance.
 for(const id of [first,second,later,advance])expect(discardIds(s).filter(c=>c===id)).toHaveLength(1);
 expect(s.phase).toBe('withdrawal');expect(s.resolution).toEqual([]);
});
it.each(['獣使いのウパニシャット','魔聖母ディア'] as const)('%s shares one target follower snapshot and morale across source hits',owner=>{
 let s=setup(owner);s.players.B!.permanent={endurance:100};
 const first=source(s,owner==='魔聖母ディア'?'黒騎士団':'グリフォン'),second=source(s,owner==='魔聖母ディア'?'女神官のシャリア':'地竜');
 const follower=source(s,'女性親衛隊',true,'B');
 s=until(act(s,'A',command(s,[{cardInstanceId:first,dedicated:false,targetIds:['B']},{cardInstanceId:second,dedicated:false,targetIds:owner==='魔聖母ディア'?['B']:['B','C','D']}])),'follower-start');
 const groupId=Object.values(s.groups!)[0]!.id;
 expect(s.groups![groupId]!.targets[0]!.followerSnapshot).toEqual([follower]);
 s=until(s,'hit');const target=s.groups![groupId]!.targets[0]!;
 expect(target.followerSnapshot).toEqual([follower]);expect(target.followerDefense).toHaveLength(1);
 const defense=target.followerDefense![0]!;expect(defense.source).toBe('physical');if(defense.source!=='physical')throw Error('EXPECTED_PHYSICAL');expect(defense.cardInstanceId).toBe(follower);
 expect(defense.levels).toHaveLength(owner==='魔聖母ディア'?2:3);
 expect(defense.hits.map(h=>h.hitIndex)).toEqual(owner==='魔聖母ディア'?[0,1]:[0,1,2]);
 expect(s.rolls!.filter(r=>r.purpose==='follower-morale'&&r.rollerId==='B')).toHaveLength(1);
 s=finish(s);expect(s.players.B!.followers).toEqual([]);expect(discardIds(s).filter(c=>c===follower)).toHaveLength(1);
 expect(s.resolution).toEqual([]);
});
