import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeHundredSlashPhysical,hundredSlashCard as CARD,hundredSlashMode,type HundredSlashScenario} from '../../../apps/worker/test/fixtures/hundred-slash-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function until(s:GameState,done:(s:GameState)=>boolean,count=3){for(let n=0;n<900;n++){if(done(s))return s;s=pass(s,s.windows?.at(-1)?.kind==='damage'?[count]:Array(100).fill(1));}throw Error('HUNDRED_SLASH_LIMIT');}
function settle(s:GameState,count=3){return until(s,s=>!s.windows?.length,count);}
function command(name:HundredSlashScenario){const m=hundredSlashMode(name);return {type:'ATTACK',cardInstanceId:CARD,targetIds:m.targets.map(i=>players[i]!.id),dedicated:m.dedicated};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['hundred-slash-ordinary','hundred-slash-owner-ordinary','hundred-slash-dedicated','hundred-slash-pair','hundred-slash-all','hundred-slash-near','hundred-slash-suppressed','hundred-slash-silenced'] as const)('%s real chant and intervening turns preserve seven per shared three hits and optional Shin package',name=>{
 let s=makeHundredSlashPhysical(name,players);const m=hundredSlashMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],prior=s.rolls?.length??0;
 expect(s.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);
 s=act(s,'A',command(name));expect(source(s).fromChant).toBe(true);expect(source(s).technique).toMatchObject({useLevel:7,effectLevel:7,damage:7,range:'far',attributes:['戦','剣','詠'],chant:true,counter:false,hitCount:'d6',noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(s.players.A!.hand).toEqual(hand);expect(s.deck).toEqual(deck);
 s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).targets.map(t=>t.hits.map(h=>h.damage))).toEqual(m.targets.map(()=>[7,7,7]));expect((s.rolls??[]).filter(r=>r.purpose==='attack-hit-count')).toHaveLength(1);
 s=settle(s);for(const [i,p] of players.entries())expect(s.players[p.id]!.damage).toBe(m.targets.includes(i)?21:0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);expect(s.rolls!.length-prior).toBe(m.owner?1:2);
});
it.each([['hundred-slash-ordinary',1],['hundred-slash-ordinary',6],['hundred-slash-pair',1],['hundred-slash-pair',6]] as const)('%s actual shared d6 boundary %s fixes same count for every selected target',(name,count)=>{let s=until(act(makeHundredSlashPhysical(name,players),'A',command(name)),s=>s.windows?.at(-1)?.kind==='attack-abilities',count);const roll=s.rolls!.find(r=>r.purpose==='attack-hit-count')!;expect(roll).toMatchObject({faces:[count],total:count});expect(group(s).targets.map(t=>t.hits.length)).toEqual(hundredSlashMode(name).targets.map(()=>count));s=settle(s,count);expect(s.players.B!.damage).toBe(count*7);expect(s.players.C!.damage).toBe(name==='hundred-slash-pair'?count*7:0);expect((s.rolls??[]).filter(r=>r.purpose==='attack-hit-count')).toHaveLength(1);});
it.each([[2,2,true],[2,3,false]] as const)('non-Shin actual activation spirit minus two boundary %s plus %s success=%s precedes use',(a,b,success)=>{let s=act(makeHundredSlashPhysical('hundred-slash-low',players),'A',command('hundred-slash-low'));expect(source(s).checkSpecs?.map(c=>c.purpose)).toEqual(['activation','excess-level']);s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[a,b]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'activation',threshold:4,total:a+b,success});s=settle(s);expect(s.players.B!.damage).toBe(success?21:0);expect(s.rolls!.map(r=>r.purpose)).toEqual(success?['activation','excess-level','attack-hit-count']:['activation']);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);});
it('actual non-Shin successful precheck can still fail later use before any hit-count roll',()=>{let s=act(makeHundredSlashPhysical('hundred-slash-low',players),'A',command('hundred-slash-low'));s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[2,2]);s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll'&&s.rolls!.at(-1)!.purpose==='excess-level');s=closeWindow(s,[3,4]);expect(s.rolls!.at(-1)).toMatchObject({threshold:6,total:7,success:false});s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.rolls!.map(r=>r.purpose)).toEqual(['activation','excess-level']);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual Shin ordinary usage omits only foreign precheck while dedicated warrior zero has no use checks',()=>{let s=act(makeHundredSlashPhysical('hundred-slash-owner-low',players),'A',command('hundred-slash-owner-low'));expect(source(s).checkSpecs?.map(c=>c.purpose)).toEqual(['excess-level']);s=settle(s);expect(s.players.B!.damage).toBe(21);s=makeHundredSlashPhysical('hundred-slash-dedicated',players,{spirit:0});expect(gameStats(s,'A').warrior_level).toBe(0);s=act(s,'A',command('hundred-slash-dedicated'));expect(source(s).checkSpecs).toEqual([]);s=settle(s);expect(s.rolls!.map(r=>r.purpose)).toEqual(['attack-hit-count']);expect(s.players.B!.damage).toBe(21);});
it.each(['hundred-slash-fate-before','hundred-slash-fate-after'] as const)('%s actual Fate cancels unpaid checks or fails the next use after successful precheck',name=>{let s=act(makeHundredSlashPhysical(name,players),'A',command(name));const id=source(s).id,after=name.endsWith('after');if(after){s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[2,2]);s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll'&&s.rolls!.at(-1)!.purpose==='excess-level');}s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',after?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:s.rolls!.at(-1)!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='attack-hit-count')).toHaveLength(0);if(after){expect(s.rolls!.find(r=>r.purpose==='activation')!.success).toBe(true);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',forcedFailure:true,success:false});}expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it.each([['hundred-slash-water',0],['hundred-slash-metal',6],['hundred-slash-fort',15]] as const)('%s actual follower snapshot applies HP to all three hits and disposes once for %s',(name,damage)=>{let s=settle(act(makeHundredSlashPhysical(name,players),'A',command(name)));expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(0);expect(s.discard.filter(id=>id===hundredSlashMode(name).follower)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(name==='hundred-slash-water'?1:0);});
it.each(['hundred-slash-maai-one','hundred-slash-maai-three','hundred-slash-parry','hundred-slash-evade'] as const)('%s real defenses cover paid individual hits without protecting other targets',name=>{let s=until(act(makeHundredSlashPhysical(name,players),'A',command(name)),s=>s.windows?.at(-1)?.kind==='normal-defense');const ids=name.endsWith('three')?['a2-p06-r1c3','a2-p06-r2c1','a2-p06-r2c2']:[name.endsWith('parry')?'a2-p12-r1c3':name.endsWith('evade')?'a2-p05-r3c1':'a2-p06-r1c3'];for(const id of ids){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'B').activeWindow?.pendingActorId==='B');s=act(s,'B',name.includes('maai')?{type:'PLAY_MAAI',cardInstanceId:id}:{type:'PLAY_DEFENSE',cardInstanceId:id,dedicated:false});}s=settle(s);expect(s.players.B!.damage).toBe((3-ids.length)*7);expect(s.players.C!.damage).toBe(21);for(const id of ids)expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it.each(['hundred-slash-mental-lester','hundred-slash-mental-dia','hundred-slash-mental-gad'] as const)('%s one actual received mental defense check cancels B three hits only',name=>{let s=until(act(makeHundredSlashPhysical(name,players),'A',command(name)),s=>s.windows?.at(-1)?.kind==='normal-defense');const ability=hundredSlashMode(name).ability!,option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===ability)!;expect(option).toBeDefined();s=act(s,'B',{type:'USE_ABILITY',abilityId:ability,targetEventId:option.targetEventId});s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[2,3]);s=settle(s);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(21);expect(s.players.A!.statuses??[]).toEqual([]);});
it.each(['hundred-slash-unprepared-ordinary','hundred-slash-unprepared-dedicated'] as const)('%s printed chant is required before source can attack',name=>{const s=makeHundredSlashPhysical(name,players);reject(s,'A',command(name));expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner invalid targets actors timing and optional decline reject without spending chant',()=>{let s=makeHundredSlashPhysical('hundred-slash-wrong-owner',players);reject(s,'A',command('hundred-slash-wrong-owner'));s=makeHundredSlashPhysical('hundred-slash-owner-ordinary',players);reject(s,'A',{...command('hundred-slash-owner-ordinary'),targetIds:['B','C']});s=makeHundredSlashPhysical('hundred-slash-same-faction',players);reject(s,'A',{...command('hundred-slash-same-faction'),targetIds:['C']});for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',{...command('hundred-slash-same-faction'),targetIds});reject(s,'B',command('hundred-slash-same-faction'));s=makeHundredSlashPhysical('hundred-slash-decline',players);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
it('actual incoming Bow does not permit attack-only chanted sword as counter',()=>{let s=makeHundredSlashPhysical('hundred-slash-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain(CARD);});
it('actual Hypnosis skip leaves the unprepared sword unspent',()=>{const s=makeHundredSlashPhysical('hundred-slash-stopped',players);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',command('hundred-slash-stopped'));expect(s.players.A!.hand).toContain(CARD);});

it.each(['hundred-slash-chant-ordinary','hundred-slash-chant-dedicated'] as const)('%s explicit preparation pays only sword and disallows immediate attack',name=>{let s=makeHundredSlashPhysical(name,players);const m=hundredSlashMode(name),hand=[...s.players.A!.hand];s=act(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);expect(s.phase).toBe('hand-adjustment');reject(s,'A',command(name));for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);});
