import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until,passReclaims} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeIceMagicScenario as makeFixture,iceMagicMode,type IceMagicScenario} from '../../../apps/worker/test/fixtures/ice-magic-scenarios.js';
function makeIceMagicScenario(scenario:Parameters<typeof makeFixture>[0],ps:Parameters<typeof makeFixture>[1],options:Parameters<typeof makeFixture>[2]={}){return makeFixture(scenario,ps,{guard:'none',...options});}
const players=['A','B','C','D'].map(id=>({id,name:id}));
const rows=['ice-arrow-ordinary','ice-arrow-dedicated','ice-stream-ordinary','ice-stream-dedicated'] as const;
function command(name:IceMagicScenario){const m=iceMagicMode(name);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function reject(s:GameState,actorId:string,command:unknown,code?:string){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id)),r=transition(s,{actorId,command} as never,entropy());expect(r.ok).toBe(false);if(code)expect(r).toMatchObject({code});expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState,card:string){for(let n=0;n<100;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ANNIHILATION_TURN');}throw Error('ANNIHILATION_TURN_LIMIT');}
function claim(s:GameState,card:string){for(let n=0;n<300;n++){const d=viewFor(s,'A').reclaim;if(s.windows?.at(-1)?.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){expect(d.claims.map(c=>c.right)).toContain('base');return act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});}s=pass(s);}throw Error('ANNIHILATION_CLAIM');}
it.each(rows)('%s actual printed magic profile and use-level boundary distinguish ordinary and dedicated without chant',scenario=>{
 const m=iceMagicMode(scenario);for(const level of [m.use-1,m.use]){let s=act(makeIceMagicScenario(scenario,players,{level}),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.use,effectLevel:m.effect,damage:m.damage,attributes:['魔','水'],chant:false,noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(f.technique.maaiRequired??1).toBe(m.maai);expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.damage,m.dedicated?m.damage:0,0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);}
});
it.each(rows)('%s actual maai needs the printed number of different cards and defends only its target',scenario=>{
 const m=iceMagicMode(scenario);for(const count of [1,2]){let s=until(act(makeIceMagicScenario(scenario,players),'A',command(scenario)),'normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});if(m.maai===2&&count===2)s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([count>=m.maai?0:m.damage,m.dedicated?m.damage:0]);expect(s.players.B!.hand.includes('a2-p07-r1c2')).toBe(m.maai===1||count===1);}
});
it.each(rows)('%s actual Evade defends only B without changing dedicated C damage',scenario=>{
 const m=iceMagicMode(scenario);let s=until(act(makeIceMagicScenario(scenario,players),'A',command(scenario)),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,m.dedicated?m.damage:0]);expect(s.discard).toContain('a2-p05-r3c1');
});
it.each(rows)('%s actual Fate cancels then base reclaim and later real turn reuse preserve elected values',scenario=>{
 const m=iceMagicMode(scenario);let s=act(makeIceMagicScenario(scenario,players),'A',command(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=pass(s);s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(claim(s,m.card));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.A!.hand.filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.reclaimUsage?.[m.name]?.baseSpent).toBe(true);s=nextOwn(s,m.card);s=finish(act(s,'A',command(scenario)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage,m.dedicated?m.damage:0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual initial Soldier HP still reduces ice damage and disposes once',scenario=>{
 const m=iceMagicMode(scenario);let s=makeIceMagicScenario(scenario,players,{guard:'soldier'});const guard=s.players.B!.followers[0]!.cardInstanceId;s=finish(act(s,'A',command(scenario)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage-1,m.dedicated?m.damage:0]);expect(s.discard.filter(id=>id===guard)).toHaveLength(1);expect(s.players.B!.followers).toEqual([]);
});
it.each(rows)('%s cannot use magic after actual Silence and real subsequent turns',scenario=>{
 const s=makeIceMagicScenario(scenario,players,{silenced:true});expect(s.rolls!.some(r=>r.faces.join(',')==='6,6'&&r.success===false)).toBe(true);reject(s,'A',command(scenario),'SILENCED');
});
it.each(['ice-arrow-dedicated','ice-stream-dedicated'] as const)('%s refuses foreign dedicated owner, ordinary multi-target and invented chant or variant',scenario=>{
 const s=makeIceMagicScenario(scenario,players),foreign=makeIceMagicScenario(scenario,players,{owner:'侍大将のシン'});reject(foreign,'A',command(scenario),'UNSUPPORTED_CARD');reject(s,'A',{...command(scenario),dedicated:false});reject(s,'A',{type:'CHANT',cardInstanceId:iceMagicMode(scenario).card});reject(s,'A',{...command(scenario),techniqueVariant:'two-hit'});
});

it.each([
 ['water',true,0,6,true],['water',false,0,0,false],['water','pass',0,0,false],['water-blessed',true,0,0,true],['water-blessed',true,1,6,true],['water-blessed',true,2,6,true],
] as const)('Ice Stream actual %s choice%s Prayer%s gives B%s surviving=%s while C independently declines',(guard,choice,bonus,damage,survives)=>{
 let s=makeIceMagicScenario('ice-stream-dedicated',players,{guard});const first=s.players.B!.followers[0]!.cardInstanceId,second=s.players.C!.followers[0]!.cardInstanceId;s=act(s,'A',command('ice-stream-dedicated'));const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p12-r2c3')!.id;if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});}for(let n=0;n<250&&s.windows?.at(-1)?.kind!=='follower-bypass-choice';n++)s=pass(s,[bonus||1]);expect(s.windows?.at(-1)?.kind).toBe('follower-bypass-choice');expect(viewFor(s,'A').currentAttack?.targetId).toBe('B');expect(s.actions![id]!.technique.effectLevel).toBe(7+bonus);reject(s,'B',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true});s=choice==='pass'?pass(s):act(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:choice});reject(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true});s=until(s,'follower-bypass-choice');expect(viewFor(s,'A').currentAttack?.targetId).toBe('C');s=act(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:false});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([damage,5]);expect(s.players.B!.followers.some(f=>f.cardInstanceId===first)).toBe(survives);expect(s.discard).toContain(second);if(damage===6)expect(s.players.B!.followers[0]!.revealed).toBe(false);
});
it.each(['maai','evade'] as const)('Ice Stream actual %s prevents B hit and its bypass choice while C retains its own choice',defense=>{
 let s=makeIceMagicScenario('ice-stream-dedicated',players,{guard:'water'});const first=s.players.B!.followers[0]!.cardInstanceId;s=until(act(s,'A',command('ice-stream-dedicated')),'normal-defense');if(defense==='evade')s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else for(const cardInstanceId of ['a2-p07-r1c1','a2-p07-r1c2'])s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId}));const offered:string[]=[];for(let n=0;n<300&&s.windows?.length;n++){if(s.windows.at(-1)!.kind==='follower-bypass-choice'){offered.push(viewFor(s,'A').currentAttack!.targetId!);s=act(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:false});}else s=pass(s);}expect(offered).toEqual(['C']);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,5]);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual([first]);
});
it('Ice Stream successful bypass expires after actual base reclaim and later re-use can decline it',()=>{
 let s=makeIceMagicScenario('ice-stream-dedicated',players,{guard:'water',defender:'侍大将のシン'});const card='a2-p12-r2c3',guard=s.players.B!.followers[0]!.cardInstanceId;s=until(act(s,'A',{...command('ice-stream-dedicated'),targetIds:['B']}),'follower-bypass-choice');s=act(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true});s=finish(claim(s,card));expect(s.players.B!.damage).toBe(6);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual([guard]);s=nextOwn(s,card);s=until(act(s,'A',{...command('ice-stream-dedicated'),targetIds:['B']}),'follower-bypass-choice');s=act(s,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:false});s=finish(s);expect(s.players.B!.damage).toBe(6);expect(s.players.B!.followers).toEqual([]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
