import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,finish,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeKeilPhysicalScenario,keilMode,type KeilPhysicalScenario} from './fixtures/keil-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p01-r3c1',dice=[3,...Array(60).fill(1)];
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('KEIL_WINDOW');}
function at(s:GameState,kind:string){return until(s,s=>s.windows?.at(-1)?.kind===kind);}
function priority(s:GameState,id:string){return until(s,s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]===id;});}
function start(name:KeilPhysicalScenario){const m=keilMode(name);return act(makeKeilPhysicalScenario(name,players),'A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:m.multi?['B','C']:['B'],dedicated:false});}
function option(s:GameState,id='D'){return viewFor(s,id).anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId==='B');}
function play(s:GameState,id='D'){s=until(s,s=>!!option(s,id));return act(s,id,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:option(s,id)!.targetEventId,targetId:'B'});}
function next(s:GameState,target:string,phase='action'){for(let n=0;n<300;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(!w&&id===target&&s.phase===phase)return s;if(w)s=pass(s);else if(s.phase==='action'){if(id===target)return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('KEIL_TURN_PHASE');}throw Error('KEIL_TURN');}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['keil-lancelot','keil-lia','keil-multi','keil-self'] as const)('%s actual public target protection cancels every remaining hit only for selected recipient',name=>{let s=at(start(name),'attack-abilities');const m=keilMode(name),owner=m.owner===1?'B':'D',before=gameStats(s,'B'),permanent=s.players.B!.permanent!.spirit!,other=gameStats(s,'D'),g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.hits.length)).toEqual(m.multi?[1,1]:[3]);expect(s.events.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='B')).toBe(true);s=priority(s,owner);const event=g.actionId,hand=s.players[owner]!.hand.length;reject(s,owner,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event,targetId:'C'});reject(s,'C',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event,targetId:'B'});s=play(s,owner);expect(s.players[owner]!.hand).toHaveLength(hand);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,m.multi?15:0,0]);expect(gameStats(s,'B').spirit).toBe(before.spirit+(name==='keil-lia'?0:1));expect(s.players.B!.permanent!.spirit).toBe(permanent+(name==='keil-lia'?0:1));if(owner==='D')expect(gameStats(s,'D')).toEqual(other);expect(s.discard.filter(id=>id===card)).toHaveLength(1);expect(Object.values(s.groups??{}).some(g=>g.substituteOrigin)).toBe(false);reject(s,owner,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event,targetId:'B'});});
it.each(['keil-lancelot','keil-lia','keil-multi'] as const)('%s actual pre-group protection persists through generated hits without protecting other targets',name=>{let s=start(name);const before=gameStats(s,'B').spirit;s=finish(play(s));expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,name==='keil-multi'?15:0,0]);expect(gameStats(s,'B').spirit).toBe(before+(name==='keil-lia'?0:1));});
it.each(['keil-hidden','keil-unrelated'] as const)('%s refuses hidden or unrelated target and declining leaves physical card and growth untouched',name=>{let s=priority(at(start(name),'attack-abilities'),'D');const before=gameStats(s,'B').spirit,hand=[...s.players.D!.hand],event=Object.values(s.groups!)[0]!.actionId;expect(option(s)).toBeUndefined();reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event,targetId:'B'});s=finish(s);expect(s.players.B!.damage).toBe(21);expect(s.players.D!.hand).toEqual(hand);expect(gameStats(s,'B').spirit).toBe(before);});
it('actual hidden Lancelot reveal during the same attack enables protection without leaking a prior candidate',()=>{let s=priority(at(start('keil-hidden'),'attack-abilities'),'D');expect(option(s)).toBeUndefined();s=act(s,'B',{type:'REVEAL_CHARACTER'});s=finish(play(s));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.permanent!.spirit).toBe(21);});
it('actual earlier target stays committed while later protected target loses all hits and gains growth once',()=>{let s=act(makeKeilPhysicalScenario('keil-multi',players),'A',{type:'ATTACK',cardInstanceId:'a2-p10-r2c1',targetIds:['C','B'],dedicated:false});s=until(s,s=>{const w=s.windows?.at(-1),g=Object.values(s.groups??{})[0];return w?.kind==='hit'&&w.continuation.kind==='group'&&w.continuation.targetId==='B'&&g?.targets[0]?.pendingDamage===15;});s=finish(play(s));expect(s.players.C!.damage).toBe(15);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.permanent!.spirit).toBe(21);});
it.each(['keil-follower','keil-third'] as const)('%s actual follower receiving excludes defender but permits a third party without transferring damage',name=>{let s=at(start(name),'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerStarted).toBe(true);if(name==='keil-follower'){s=priority(s,'B');expect(option(s,'B')).toBeUndefined();s=finish(s);expect(s.players.B!.damage).toBe(12);expect(s.players.B!.hand).toContain(card);expect(s.players.B!.permanent!.spirit).toBe(20);}else{s=finish(play(s));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.permanent!.spirit).toBe(21);}expect(s.players.D!.damage).toBe(0);expect(s.discard.filter(id=>id==='a2-p20-r3c1')).toHaveLength(1);});
it('actual Fate cancellation preserves Keil payment and refill but prevents protection and permanent growth',()=>{let s=at(start('keil-canceled'),'attack-abilities');const hand=s.players.D!.hand.length;s=play(s);const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=priority(s,'A');s=finish(act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}));expect(s.players.B!.damage).toBe(21);expect(s.players.B!.permanent!.spirit).toBe(20);expect(s.players.D!.hand).toHaveLength(hand);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual immediate Blood OPEN refill belongs to card user while Keil permanent growth belongs to protected Lancelot',()=>{let s=at(start('keil-refill'),'attack-abilities');const before=gameStats(s,'D');s=play(s);expect(s.players.D!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'D')).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});s=finish(s);expect(s.players.B!.permanent!.spirit).toBe(21);expect(s.players.D!.permanent!.spirit).toBe(20);expect(s.players.B!.damage).toBe(0);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId==='a2-p01-r1c3')).toHaveLength(1);});
it('actual later Wish acquisition permits another declaration to add independent permanent growth',()=>{let s=finish(play(at(start('keil-growth'),'attack-abilities')));const event=s.events.length;s=next(s,'D','draw');s=finish(act(s,'D',{type:'CHOOSE_DRAW',draw:true}));expect(s.players.D!.open).toContain('a2-p01-r1c2');expect(s.players.B!.permanent!.spirit).toBe(21);s=at(act(s,'D',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c2',mode:'wish'}),'wish');s=finish(act(s,'D',{type:'CHOOSE_WISH',decisionId:viewFor(s,'D').wish!.decisionId,source:{kind:'deck',cardName:'聖騎士団長ケイルベイツ'}}));expect(s.players.D!.hand).toContain(card);s=next(s,'A');s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false});s=finish(play(s));expect(s.players.B!.permanent!.spirit).toBe(22);expect(s.players.B!.damage).toBe(0);expect(s.discard.filter(id=>id===card)).toHaveLength(1);expect(s.events.slice(event).some(e=>e.type==='WISH_ACQUIRED'&&e.cardInstanceId===card)).toBe(true);});
it('actual Lancelot transformation keeps Keil independent permanent growth and public second identity',()=>{let s=finish(play(at(start('keil-transform'),'attack-abilities')));const before=s.players.B!.permanent!.spirit;s=finish(act(s,'C',{type:'REVEAL_CHARACTER'}));s=finish(act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'}));expect(s.players.B!.characterId).toBe('c2-p07-r1c1');expect(s.players.B!.permanent!.spirit).toBe(before);expect(s.events.some(e=>e.type==='CHARACTER_TRANSFORMED'&&e.actorId==='B')).toBe(true);});
it('actual lethal later Bow and dedicated Resurrection preserve Keil growth across death and rebuild',()=>{let s=finish(play(at(start('keil-revive'),'attack-abilities')));s=next(s,'A');s=finish(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false}));expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.permanent!.spirit).toBe(21);s=next(s,'D');s=act(s,'D',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['B'],dedicated:true,convertTargetIds:[]});s=at(s,'re-setup');expect(s.players.B).toMatchObject({presence:'active',damage:0,revealed:true,characterId:'c2-p02-r2c2'});expect(s.players.B!.permanent!.spirit).toBe(21);s=finish(act(s,'B',{type:'PASS_SETUP'}));expect(s.events.filter(e=>e.type==='PLAYER_REVIVED'&&e.actorId==='B')).toHaveLength(1);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});

it.each(['before-declaration','after-declaration'] as const)('%s actual Lancelot transformation remains an eligible named protection target with one growth',(stage)=>{let s=makeKeilPhysicalScenario('keil-transform',players);s=finish(act(s,'C',{type:'REVEAL_CHARACTER'}));if(stage==='before-declaration')s=finish(act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'}));s=at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p10-r1c3',targetIds:['B'],dedicated:false}),'attack-abilities');s=play(s);if(stage==='after-declaration'){s=priority(s,'B');s=act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'});}s=finish(s);expect(s.players.B!.characterId).toBe('c2-p07-r1c1');expect(s.players.B!.damage).toBe(0);expect(s.players.B!.permanent!.spirit).toBe(21);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
