import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeKiBurstPhysical,kiBurstCard as CARD,kiBurstMode} from '../../../apps/worker/test/fixtures/ki-burst-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),GAD='c2-p06-r1c1-ab02',PEACE='a2-p02-r1c1';
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s);}throw Error('KI_BURST_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['ki-burst-ordinary','ki-burst-owner-ordinary','ki-burst-dedicated','ki-burst-same-faction','ki-burst-suppressed','ki-burst-silenced'] as const)('%s actual approached physical strike preserves four spirit double two Maai and optional Gil mode',name=>{let s=makeKiBurstPhysical(name,players);const m=kiBurstMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],rolls=s.rolls?.length??0;expect(s.distances.A!.B).toBe('near');expect(gameStats(s,'A').spirit).toBe(6);expect(gameStats(s,'B').spirit).toBe(11);if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='damage');expect(source(s).technique.damage).toBeNull();s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'near',useLevel:4,effectLevel:4,damage:12,damageFormula:'attacker-spirit-x2',attributes:['戦','格','精','白'],maaiRequired:2,target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(group(s).technique.characterImmunityExceptions??[]).toEqual(m.dedicated?[{characterName:'不死王ガドューラ',immunity:'spirit-techniques'}]:[]);s=settle(s);expect(s.players.B!.damage).toBe(12);expect(s.players.C!.damage).toBe(0);expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);});
it.each([[false,0],[false,1],[false,12],[true,0],[true,1],[true,12]] as const)('actual caster spirit boundary dedicated=%s spirit%s produces numeric double without target spirit leakage',(dedicated,spirit)=>{let s=makeKiBurstPhysical(dedicated?'ki-burst-dedicated':'ki-burst-ordinary',players,{spirit});expect(gameStats(s,'A').warrior_level).toBe(dedicated?0:4);s=until(act(s,'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(spirit*2);expect(group(s).targets[0]!.hits[0]!.damage).toBe(spirit*2);s=settle(s);expect(s.players.B!.damage).toBe(spirit*2);expect(s.rolls??[]).toHaveLength(0);});
it.each(['ki-burst-before-dedicated','ki-burst-after-dedicated','ki-burst-target-before-dedicated','ki-burst-target-after-dedicated'] as const)('%s actual Peace changes source or target spirit across saved pre-defense damage boundary',name=>{let s=makeKiBurstPhysical(name,players);const m=kiBurstMode(name),target=m.target?'B':'A',raised=12+(s.players[target]!.permanent!.spirit??0);s=act(s,'A',cmd(true));s=until(s,s=>s.windows?.at(-1)?.kind===(m.after?'attack-abilities':'damage'));const window=s.windows!.at(-1)!.id;if(m.after)expect(group(s).targets[0]!.hits[0]!.damage).toBe(12);else expect(source(s).technique.damage).toBeNull();s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');const option=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===PEACE&&o.targetId===target)!;expect(option).toBeDefined();s=act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:PEACE,targetEventId:option.targetEventId,targetId:target});s=until(s,s=>s.windows?.at(-1)?.id===window);expect(gameStats(s,target).spirit).toBe(raised);const fixed=(m.after||m.target?6:raised)*2;if(!m.after)s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).targets[0]!.hits[0]!.damage).toBe(fixed);s=settle(s);expect(s.players.B!.damage).toBe(fixed);expect(s.discard.filter(id=>id===PEACE)).toHaveLength(1);});
it.each(['ki-burst-gad-ordinary','ki-burst-gad-decline','ki-burst-gad-dedicated','ki-burst-gad-maai','ki-burst-gad-water'] as const)('%s actual Gadyura Dead election is excluded only by dedicated exception while ordinary defenses remain',name=>{let s=makeKiBurstPhysical(name,players);const m=kiBurstMode(name);s=until(act(s,'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');const option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===GAD);expect(!!option).toBe(!m.dedicated);if(m.dedicated)reject(s,'B',{type:'USE_ABILITY',abilityId:GAD,targetEventId:s.windows!.at(-1)!.eventId});else if(m.suffix==='gad-ordinary'){s=act(s,'B',{type:'USE_ABILITY',abilityId:GAD,targetEventId:option!.targetEventId});expect(Object.values(s.abilities??{}).filter(a=>a.abilityId===GAD)).toHaveLength(1);}if(m.suffix==='gad-maai')s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3',additionalCardInstanceIds:['a2-p06-r2c1']});s=settle(s);expect(s.players.B!.damage).toBe(['gad-ordinary','gad-maai','gad-water'].includes(m.suffix)?0:12);if(m.follower)expect(s.players.B!.followers[0]!.cardInstanceId).toBe(m.follower);expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);});
it.each([['ki-burst-water',0,true],['ki-burst-equal',0,false],['ki-burst-lower',10,false]] as const)('%s actual follower level boundary yields%s and survives=%s without follower bypass',(name,damage,survives)=>{let s=settle(act(makeKiBurstPhysical(name,players),'A',cmd(true)));expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(survives?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(name==='ki-burst-water'?1:0);if(!survives)expect(s.discard).toContain(kiBurstMode(name).follower);});
it.each(['ki-burst-maai-one-ordinary','ki-burst-maai-two-ordinary','ki-burst-maai-one-dedicated','ki-burst-maai-two-dedicated'] as const)('%s actual one or two physical Maai preserves shared extra-one requirement in both modes',name=>{const m=kiBurstMode(name),two=m.suffix.includes('-two-');let s=until(act(makeKiBurstPhysical(name,players),'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(two){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r2c1'});}s=settle(s);expect(s.players.B!.damage).toBe(two?0:12);expect(s.discard.filter(id=>id==='a2-p06-r1c3')).toHaveLength(1);if(two)expect(s.discard.filter(id=>id==='a2-p06-r2c1')).toHaveLength(1);expect(s.distances.A!.B).toBe('near');});
it.each([false,true] as const)('actual mental attribute rejects Evade in both selected modes dedicated=%s',dedicated=>{let s=until(act(makeKiBurstPhysical(dedicated?'ki-burst-evade-dedicated':'ki-burst-evade-ordinary',players),'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=settle(s);expect(s.players.B!.damage).toBe(12);expect(s.players.B!.hand).toContain('a2-p05-r3c1');});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior3 spirit6 actual shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeKiBurstPhysical('ki-burst-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?12:0);expect(s.rolls).toHaveLength(1);});
it.each([false,true] as const)('actual far target rejects until real approach enables near strike dedicated=%s',dedicated=>{let s=makeKiBurstPhysical('ki-burst-far',players,{warrior:4});reject(s,'A',cmd(dedicated));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(dedicated)));expect(s.players.B!.damage).toBe(12);});
it('actual Fate source cancellation spends source once before spirit value or hit',()=>{let s=act(makeKiBurstPhysical('ki-burst-fate',players),'A',cmd(true));const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId}));expect(s.players.B!.damage).toBe(0);expect(s.rolls??[]).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual incoming Bow refuses normal and dedicated attack-only strike',()=>{let s=makeKiBurstPhysical('ki-burst-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual mandatory white prohibition applies to Gadyura source before payment',()=>{const s=makeKiBurstPhysical('ki-burst-white-prohibited',players);for(const dedicated of [false,true])reject(s,'A',cmd(dedicated));expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner malformed targets foreign actor unused timing and stopped turn reject unpaid',()=>{const s=makeKiBurstPhysical('ki-burst-wrong-owner',players,{warrior:4});reject(s,'A',cmd(true));for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(12);let t=makeKiBurstPhysical('ki-burst-decline',players,{beforeStart:true});reject(t,'A',cmd());t=act(t,'A',{type:'START_TURN'});reject(t,'A',cmd());t=act(t,'A',{type:'CHOOSE_DRAW',draw:false});reject(t,'A',{type:'REST',cardInstanceIds:[CARD]});reject(t,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});t=act(t,'A',{type:'PASS_ACTION'});expect(t.players.A!.hand).toContain(CARD);t=makeKiBurstPhysical('ki-burst-stopped',players);expect(t.seatOrder[t.turnSeat]).not.toBe('A');reject(t,'A',cmd(true));expect(t.players.A!.hand).toContain(CARD);});
