import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeKiSlashPhysical,kiSlashCard as CARD,kiSlashMode} from './fixtures/ki-slash-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),PEACE='a2-p02-r1c1';
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<600;n++){if(done(s))return s;s=pass(s);}throw Error('KI_SLASH_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['ki-slash-ordinary','ki-slash-guard','ki-slash-owner-ordinary','ki-slash-dedicated','ki-slash-near','ki-slash-same-faction','ki-slash-suppressed','ki-slash-silenced'] as const)('%s actual physical attack freezes caster spirit and both modes ignore placed followers without revealing them',name=>{
 let s=makeKiSlashPhysical(name,players);const m=kiSlashMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],followers=structuredClone(s.players.B!.followers),rolls=s.rolls?.length??0;expect(gameStats(s,'A').spirit).toBe(6);expect(gameStats(s,'B').spirit).toBe(11);if(name==='ki-slash-suppressed')expect(s.players.A!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);if(name==='ki-slash-silenced')expect(s.players.A!.statuses?.some(x=>x.kind==='silenced')).toBe(true);if(name==='ki-slash-near')expect(s.distances.A!.B).toBe('near');if(name==='ki-slash-same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});
 s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='damage');expect(source(s).technique.damage).toBeNull();s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:m.dedicated?7:6,damage:m.dedicated?12:6,damageFormula:m.dedicated?'attacker-spirit-x2':'attacker-spirit',attributes:['戦','剣','精','忍'],chant:false,counter:false,noChecks:m.dedicated,followerIgnore:true,target:'one'});expect(group(s).targets[0]!.hits[0]!.damage).toBe(m.dedicated?12:6);s=settle(s);expect(s.players.B!.damage).toBe(m.dedicated?12:6);expect(s.players.B!.followers).toEqual(followers);expect(s.players.C!.damage).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);expect(s.phase).toBe('withdrawal');reject(s,'A',cmd(m.dedicated));
});
it.each(['ki-slash-before-ordinary','ki-slash-after-ordinary','ki-slash-before-dedicated','ki-slash-after-dedicated','ki-slash-target-before-ordinary','ki-slash-target-after-ordinary','ki-slash-target-before-dedicated','ki-slash-target-after-dedicated'] as const)('%s actual third-party Peace changes source or target spirit across the saved pre-defense damage boundary',name=>{
 let s=makeKiSlashPhysical(name,players);const m=kiSlashMode(name),target=m.target?'B':'A',raised=12+(s.players[target]!.permanent!.spirit??0),mult=m.dedicated?2:1;s=act(s,'A',cmd(m.dedicated));s=until(s,s=>s.windows?.at(-1)?.kind===(m.after?'attack-abilities':'damage'));const window=s.windows!.at(-1)!.id;if(m.after)expect(group(s).targets[0]!.hits[0]!.damage).toBe(6*mult);else expect(source(s).technique.damage).toBeNull();s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');const option=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===PEACE&&o.targetId===target)!;expect(option).toBeDefined();const dHand=s.players.D!.hand.length;s=act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:PEACE,targetEventId:option.targetEventId,targetId:target});s=until(s,s=>s.windows?.at(-1)?.id===window);expect(gameStats(s,target).spirit).toBe(raised);expect(s.players.D!.hand).toHaveLength(dHand);expect(s.discard.filter(id=>id===PEACE)).toHaveLength(1);const fixed=(m.after||m.target?6:raised)*mult;if(!m.after){expect(source(s).technique.damage).toBeNull();s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');}expect(source(s).valuesPrepared).toBe(true);expect(group(s).targets[0]!.hits[0]!.damage).toBe(fixed);s=settle(s);expect(s.players.B!.damage).toBe(fixed);expect(s.players.A!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);
});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior5 actual spirit6 shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeKiSlashPhysical('ki-slash-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?6:0);expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(1);});
it.each([false,true] as const)('actual spirit zero produces numeric zero rather than absent damage dedicated=%s',dedicated=>{let s=makeKiSlashPhysical(dedicated?'ki-slash-dedicated':'ki-slash-guard',players,{spirit:0,warrior:dedicated?0:6});s=until(act(s,'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(0);expect(group(s).targets[0]!.hits[0]!.damage).toBe(0);s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.rolls?.length??0).toBe(0);});
it.each(['ki-slash-maai','ki-slash-evade'] as const)('%s actual Maai avoids the spirit hit but mental attribute refuses Evade without changing state',name=>{let s=makeKiSlashPhysical(name,players);const followers=structuredClone(s.players.B!.followers);s=until(act(s,'A',cmd(true)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:false,evadeProhibited:true,counterProhibited:false});if(name==='ki-slash-maai')s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});else{reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});expect(s.players.B!.hand).toContain('a2-p05-r3c1');}s=settle(s);expect(s.players.B!.damage).toBe(name==='ki-slash-maai'?0:12);expect(s.players.B!.followers).toEqual(followers);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual Fate cancellation spends the selected spirit source once without a roll hit or follower exposure',()=>{let s=act(makeKiSlashPhysical('ki-slash-fate',players),'A',cmd(true));const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetActionId:id});s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.rolls?.length??0).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual wrong owner malformed targets and modes reject unchanged while ordinary use remains legal',()=>{let s=makeKiSlashPhysical('ki-slash-wrong-owner',players);reject(s,'A',cmd(true));for(const ids of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,ids));reject(s,'B',cmd());reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});s=settle(act(s,'A',cmd()));expect(s.players.B!.damage).toBe(6);});
it('actual stopped recovery failure skips source owner and declining the own action preserves the attack-only card',()=>{let s=makeKiSlashPhysical('ki-slash-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd());reject(s,'A',cmd(true));s=makeKiSlashPhysical('ki-slash-decline',players,{beforeStart:true});reject(s,'A',cmd());s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
