import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeKnightOrdersPhysicalScenario,knightOrdersPhysicalMode,type KnightOrdersPhysicalScenario} from '../../../apps/worker/test/fixtures/knight-orders-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['black-knights-setup','holy-knights-setup'] as const,grantRows=['black-knights-ded-hand','black-knights-ded-field','holy-knights-ded-hand','holy-knights-ded-field'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('KNIGHT_ORDERS_TURN');}throw Error('KNIGHT_ORDERS_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p20-r1c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);let s=makeKnightOrdersPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);let s=ready(makeKnightOrdersPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);let s=until(incoming(ready(makeKnightOrdersPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players,{owner:'魔聖母ディア'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});
it.each(grantRows)('%s actual named owner hand or field permission preserves use4 checks and selected attack values',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const warrior of [3,4]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players,{warrior}),m.card,m.initial);reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true});s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const targets of [[],['A'],['B','C'],['B','B'],['missing']])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:targets,dedicated:true});s=act(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(a.checks).toHaveLength(4-warrior);expect(a.technique.noChecks).toBe(false);expect(a.technique.useLevel).toBe(4);expect(s.resolution).toContain(m.card);expect(s.players.A!.followers).toEqual([]);s=until(s,'normal-defense');expect(viewFor(s,'B').currentAction!.technique).toMatchObject({range:'near',school:'warrior',useLevel:4,effectLevel:m.black?5:4,damage:m.black?10:4,attributes:m.attackAttributes});s=finish(s);expect(s.players.B!.damage).toBe(m.black?10:4);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);}
});
it.each(grantRows)('%s actual dedicated Fate cancellation and failed use keep paid knight out of defense column',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const failure of [false,true]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players,{warrior:3}),m.card,m.initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;if(failure)s=until(s,'before-roll');const roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',failure?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(m.card);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);expect(s.resolution).toEqual([]);}
});
it.each(['black-knights-army','holy-knights-army'] as const)('%s actual Army hand-only ordinary bottom retains checks without named owner upgrades',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);for(const warrior of [3,4]){let s=ready(makeKnightOrdersPhysicalScenario(scenario,players,{warrior}),m.card,false);const c={type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']};reject(s,'A',c);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',c);expect(Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.checks).toHaveLength(4-warrior);s=until(s,'normal-defense');expect(viewFor(s,'B').currentAction!.technique).toMatchObject({range:'near',useLevel:4,effectLevel:4,damage:m.attackDamage,attributes:m.attackAttributes});s=finish(s);expect(s.players.B!.damage).toBe(m.attackDamage);for(const id of [m.card,'a2-p05-r2c2'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
 let s=ready(makeKnightOrdersPhysicalScenario(scenario,players),m.card);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===m.card)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});
});
it('actual Garwin Sword Master addition precedes Black Knights doubling and Prayer only adds effect level',()=>{
 for(const prayer of [false,true]){let s=ready(makeKnightOrdersPhysicalScenario('black-knights-sword',players,{warrior:4}),'a2-p20-r1c2',false);s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p20-r1c2',targetIds:['B'],dedicated:true,declarationAbilityIds:['c2-p05-r2c1-ab03']});s=until(s,'effect-level');if(prayer){const a=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r1c2')!;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:a.id});s=closeWindow(s,[3]);}s=until(s,'normal-defense');expect(viewFor(s,'B').currentAction!.technique).toMatchObject({range:'far',useLevel:4,effectLevel:prayer?9:6,damage:14});s=finish(s);expect(s.players.B!.damage).toBe(14);expect(s.discard.filter(x=>x==='a2-p20-r1c2')).toHaveLength(1);}
});
it('actual inherited Lancelot2 uses Holy Knights from hand and field with unchanged use checks and white sword',()=>{
 for(const initial of [false,true]){let s=ready(makeKnightOrdersPhysicalScenario('holy-knights-inherited',players,{warrior:3}),'a2-p20-r1c3',initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p20-r1c3',targetIds:['B'],dedicated:true});expect(Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r1c3')!.checks).toHaveLength(1);s=until(s,'normal-defense');expect(viewFor(s,'B').currentAction!.technique).toMatchObject({useLevel:4,effectLevel:4,damage:4,attributes:['近','戦','剣','白']});s=finish(s);expect(s.players.B!.damage).toBe(4);expect(s.discard.filter(x=>x==='a2-p20-r1c3')).toHaveLength(1);}
});
it.each(['black-knights-ded-hand','holy-knights-ded-hand'] as const)('%s actual Mirror remains legal and cancels knight attack without refund',scenario=>{
 const m=knightOrdersPhysicalMode(scenario);let s=ready(makeKnightOrdersPhysicalScenario(scenario,players),m.card,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=until(act(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true}),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
