import {expect,it} from 'vitest';
import {gameStats,transition,type GameState} from '../src/index.js';
import {act,ready,until,finish,pass} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
const PRAYER='a2-p05-r2c3';
function priority(s:GameState,actor:string){for(let n=0;n<100;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('PRAYER_PRIORITY');}
function setup(){let s=ready();character(s,'B','リーア姫');character(s,'C','魔導王ガイナス');character(s,'D','黒騎士ガーウィン');for(const p of Object.values(s.players))p.permanent={endurance:100,warrior_level:20,spirit:20};const first=handCard(s,'A','踏み込み／弓'),second=handCard(s,'D','黒翼飛翔剣');handCard(s,'B','必勝の祈り');s=priority(until(act(s,'A',{type:'ATTACK',cardInstanceId:first,targetIds:['C'],dedicated:false}),'effect-level'),'B');return {s,second};}
function prayer(s:GameState,dedicated:boolean){const w=s.windows!.at(-1)!,action=s.actions![w.continuation.id]!;return act(s,'B',{type:'PLAY_REACTION',cardInstanceId:PRAYER,mode:'effect-plus',targetActionId:action.id,dedicated});}
function nextOwn(s:GameState,owner:string){for(let n=0;n<40;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(actor===owner)return s;s=act(s,actor,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.filter(id=>id!==PRAYER).slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error(`PRAYER_TURN_${s.phase}`);}throw Error('PRAYER_TURN_LIMIT');}
it('Dedicated Lia prayer is inaccessible within one real event, then legally used and returned in a later real turn event',()=>{let {s,second}=setup();const firstAction=s.actions![s.windows!.at(-1)!.continuation.id]!,firstEvent=firstAction.eventId;s=prayer(s,true);for(let n=0;n<150&&!s.reclaimReservations.includes(PRAYER);n++)s=pass(s);expect(s.reclaimReservations).toContain(PRAYER);expect(s.players.B!.hand).not.toContain(PRAYER);expect(s.reclaim![PRAYER]).toMatchObject({ownerId:'B',eventId:firstEvent});s=priority(until(s,'effect-level'),'B');const before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_REACTION',cardInstanceId:PRAYER,mode:'effect-plus',targetActionId:firstAction.id,dedicated:true}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=finish(s);expect(s.players.B!.hand.filter(id=>id===PRAYER)).toHaveLength(1);s=nextOwn(s,'D');s=priority(until(act(s,'D',{type:'ATTACK',cardInstanceId:second,targetIds:['A'],dedicated:false}),'effect-level'),'B');const secondEvent=s.actions![s.windows!.at(-1)!.continuation.id]!.eventId;expect(secondEvent).not.toBe(firstEvent);s=finish(prayer(s,true));expect(s.players.B!.hand.filter(id=>id===PRAYER)).toHaveLength(1);expect(s.used).toContain(`${firstEvent}:B:${PRAYER}`);expect(s.used).toContain(`${secondEvent}:B:${PRAYER}`);expect(s.reclaimReservations).toEqual([]);});
it('Lia ordinary prayer on her own attack does not receive the dedicated physical return',()=>{let s=ready();character(s,'A','リーア姫');for(const p of Object.values(s.players))p.permanent={endurance:100,warrior_level:20};const attack=handCard(s,'A','踏み込み／弓');handCard(s,'A','必勝の祈り');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false}),'effect-level');const action=s.actions![s.windows!.at(-1)!.continuation.id]!;s=finish(act(s,'A',{type:'PLAY_REACTION',cardInstanceId:PRAYER,mode:'effect-plus',targetActionId:action.id,dedicated:false}));expect(s.discard).toContain(PRAYER);expect(s.players.A!.hand).not.toContain(PRAYER);expect(s.reclaimReservations).toEqual([]);});
it('Ordinary prayer cannot modify another actor attack',()=>{const {s}=setup(),before=JSON.stringify(s),action=s.actions![s.windows!.at(-1)!.continuation.id]!;expect(transition(s,{actorId:'B',command:{type:'PLAY_REACTION',cardInstanceId:PRAYER,mode:'effect-plus',targetActionId:action.id,dedicated:false}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);});
