import {describe,it,expect} from 'vitest';
import {transition,viewFor,derivedStats,allCardInstanceIds,type GameState, discardIds, moveToDiscard } from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow,passReclaims} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
function card(s:GameState,id:string,chant=false){for(const p of Object.values(s.players)){p.hand=p.hand.filter(x=>x!==id);p.chants=p.chants.filter(x=>x.cardInstanceId!==id);p.open=p.open.filter(x=>x!==id);}s.deck=s.deck.filter(x=>x!==id);s.discard = s.discard.filter(entry => entry.cardInstanceId !== id);if(chant)s.players.A!.chants.push({cardInstanceId:id,revealed:false});else s.players.A!.hand.push(id);return id;}
function cast(s:GameState,id:string,dedicated=false,targets=['B']){return act(s,'A',{type:'ATTACK',cardInstanceId:id,targetIds:targets,dedicated});}
function resistance(s:GameState,dice=[6,6]){s=until(s,'hit');s=closeWindow(s);s=until(s,'before-roll');s=closeWindow(s,dice);return closeWindow(s);}
function pick(s:GameState,choice:'apply'|'decline'){return act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice},[3]);}
function heal(s:GameState,id:string,dedicated=false,targets=['A'],convertTargetIds?:string[]){return act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:id,targetIds:targets,dedicated,...(convertTargetIds?{convertTargetIds}:{})});}
describe('Task7g lifetime attacks',()=>{
 it('Gadyura chooses instant-death resistance explicitly, retains chant and ordinary damage',()=>{let s=ready();character(s,'A','不死王ガドューラ');const id=card(s,'a2-p09-r3c1',true);s=cast(s,id,true);s=until(s,'lifetime-effect-choice');expect(viewFor(s,'A').lifetimeDecision?.kind).toBe('instant-death');expect(viewFor(s,'B').lifetimeDecision).toBeNull();s=pick(s,'apply');s=closeWindow(s,[6,6]);s=closeWindow(s);s=finish(s);expect(s.players.B!.presence).toBe('dead');});
 it('petrification attaches its death cause to the same damage batch',()=>{let s=ready();const id=card(s,'a2-p18-r2c1',true);s=cast(s,id);s=resistance(s);expect(s.lifecycle?.find(t=>t.kind==='death-batch')).toMatchObject({intents:[{targetId:'B',damage:5,instantDeath:true,cause:'petrification'}]});s=finish(s);expect(s.players.B!.presence).toBe('dead');});
 it('soul drain lowers all future stats, cumulatively, without changing permanent history',()=>{let s=ready();character(s,'A','魔聖母ディア');const id=card(s,'a2-p15-r2c3');const before=derivedStats(s.players.B!);s=cast(s,id,true);s=resistance(s);s=pick(s,'decline');s=finish(s);expect(derivedStats(s.players.B!)).toMatchObject({warrior_level:before.warrior_level-1,magic_level:before.magic_level-1,spirit:before.spirit-1});expect(s.players.B!.permanent).toBeUndefined();});
 it('deadly stop fails only on its next actual recovery and dies with source attribution',()=>{let s=ready();character(s,'A','魔聖母ディア');const id=card(s,'a2-p15-r3c1',true);s=cast(s,id,true);s=finish(resistance(s));expect(viewFor(s,'B').players.B!.statuses[0]).toMatchObject({timing:'deadly-recovery',recoveryModifier:-3});s.turnSeat=1;s.phase='turn-start';s=act(s,'B',{type:'START_TURN'});s=closeWindow(s,[6,6]);s=closeWindow(s);s=finish(s);expect(s.players.B!.presence).toBe('dead');});
 it('Uonos fixed stop uses one shared saved d6 and decrements each stopped recipient turn',()=>{let s=ready();character(s,'A','邪祭ウーノス');const id=card(s,'a2-p13-r3c3',true);s=cast(s,id,true,['B','C']);s=until(s,'lifetime-effect-choice');s=pick(s,'apply');s=closeWindow(s,[3]);s=until(s,'lifetime-effect-choice');s=pick(s,'apply');s=finish(s);expect(s.rolls!.filter(r=>r.purpose==='stop-duration')).toHaveLength(1);for(const who of ['B','C'])expect(viewFor(s,'A').players[who]!.statuses[0]).toMatchObject({timing:'fixed-turns',remainingTurns:3});s.turnSeat=1;s.phase='turn-start';s=act(s,'B',{type:'START_TURN'});expect(s.turnSeat).toBe(2);expect(viewFor(s,'A').players.B!.statuses[0]).toMatchObject({remainingTurns:2});expect(viewFor(s,'A').players.C!.statuses[0]).toMatchObject({remainingTurns:3});});
 it('裂界 sends a hit target away with possessions then actual Dawn returns it',()=>{let s=ready();character(s,'A','白魔術師シェリム');const id=card(s,'a2-p14-r2c2',true);const hand=[...s.players.B!.hand];s=cast(s,id,true);s=until(s,'lifetime-effect-choice');s=pick(s,'apply');s=closeWindow(s,[6,6]);s=finish(closeWindow(s));expect(s.players.B).toMatchObject({presence:'otherworld',hand});card(s,'a2-p01-r1c2');s.players.A!.hand=s.players.A!.hand.filter(x=>x!=='a2-p01-r1c2');s.deck.unshift('a2-p01-r1c2');s.phase='draw';s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});expect(s.players.B).toMatchObject({presence:'active',hand});});
 it('滅界 retains its independent follower destruction and self cost after cancellation',()=>{let s=ready();const id=card(s,'a2-p13-r2c3',true);const follower=handCard(s,'A','兵士');s.players.A!.hand=s.players.A!.hand.filter(x=>x!==follower);s.players.A!.followers=[{cardInstanceId:follower,revealed:false}];const fate=handCard(s,'A','命運凶変');s=cast(s,id);const action=s.windows!.at(-1)!.continuation.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:action});s=finish(s);expect(s.players.A!.damage).toBe(10);expect(s.players.A!.followers).toEqual([]);expect(discardIds(s)).toContain(follower);});
});
describe('Task7g true turn techniques',()=>{
 for(const id of ['a2-p12-r2c1','a2-p14-r3c1','a2-p14-r3c2'])it(`${id} checks then heals only self`,()=>{let s=ready();s.players.A!.damage=5;card(s,id);s=heal(s,id);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.phase).toBe('hand-adjustment');expect(discardIds(s)).toContain(id);expect(allCardInstanceIds(s)).toHaveLength(220);});
 it('Jill dedicated targets exactly one other near person and does not heal self',()=>{let s=ready();character(s,'A','大神官ジル');s.players.A!.damage=3;s.players.B!.damage=4;s.distances.A!.B='near';s.distances.B!.A='near';const id=card(s,'a2-p14-r3c1');s=finish(heal(s,id,true,['B']));expect(s.players.A!.damage).toBe(3);expect(s.players.B!.damage).toBe(0);});
 it('Uonos revives selected dead targets and copies current source objective references',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','大神官ジル');s.players.B!.presence='dead';for(const __discarded of [...s.players.B!.hand])moveToDiscard(s,__discarded,{faceUp:true});s.players.B!.hand=[];s.players.A!.protection={characterIds:[]};s.players.A!.currentObjective={kind:'extinction',enemyFactions:['ヴァンミール']};const id=card(s,'a2-p13-r3c1');s=heal(s,id,true,['B'],['B']);s=until(s,'re-setup');expect(s.players.B).toMatchObject({presence:'active',damage:0,faction:'EVIL',currentObjective:{kind:'extinction',enemyFactions:['ヴァンミール']},protection:{characterIds:[]}});s=act(s,'B',{type:'PASS_SETUP'});expect(s.phase).toBe('hand-adjustment');});
});
function rejectUnchanged(s:GameState,actorId:string,command:unknown,code:string){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as any,entropy())).toEqual({ok:false,code});expect(JSON.stringify(s)).toBe(before);}
function near(s:GameState,a='A',b='B'){s.distances[a]![b]='near';s.distances[b]![a]='near';}
function nextAction(s:GameState){s.phase='action';s.turnSeat=0;return s;}
function failedCheck(s:GameState){s=until(s,'before-roll');s=closeWindow(s,[6,6]);return closeWindow(s);}
function top(s:GameState,id:string){card(s,id);s.players.A!.hand=s.players.A!.hand.filter(x=>x!==id);s.deck.unshift(id);}
function dead(s:GameState,id:string){const p=s.players[id]!;for(const __discarded of [...p.hand,...p.followers.map(x=>x.cardInstanceId),...p.chants.map(x=>x.cardInstanceId),...p.open,...p.attachments])moveToDiscard(s,__discarded,{faceUp:true});p.hand=[];p.followers=[];p.chants=[];p.open=[];p.attachments=[];p.presence='dead';p.revealed=true;}
function canceled(s:GameState,id:string){const action=s.windows!.at(-1)!.continuation.id;const who=s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!;handCard(s,who,'命運凶変');s=act(s,who,{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:action});return finish(s);}
describe('Task7g accepted casts and invalid inputs',()=>{
 for(const [id,name] of [['a2-p09-r3c1','不死王ガドューラ'],['a2-p13-r2c3','破壊神ヴァンミール'],['a2-p13-r3c3','邪祭ウーノス'],['a2-p14-r2c2','白魔術師シェリム'],['a2-p15-r3c1','魔聖母ディア']] as const)it(`${id} dedicated retains mandatory chant and rejects unpaid unchanted casts`,()=>{let s=ready();character(s,'A',name);card(s,id);rejectUnchanged(s,'A',{type:'ATTACK',cardInstanceId:id,targetIds:['B'],dedicated:true},'CHANT_REQUIRED');s=act(s,'A',{type:'CHANT',cardInstanceId:id,dedicated:true});expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain(id);});
 it('ordinary 死刻鎌 deals 8 with no instant-death choice; dedicated can decline explicitly',()=>{for(const dedicated of [false,true]){let s=ready();character(s,'A','不死王ガドューラ');const id=card(s,'a2-p09-r3c1',true);s=cast(s,id,dedicated);if(dedicated){s=until(s,'lifetime-effect-choice');rejectUnchanged(s,'B',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'},'NOT_PRIORITY');s=pick(s,'decline');}s=finish(s);expect(s.players.B!.damage).toBe(8);expect(s.rolls?.some(r=>r.purpose==='status-resistance')??false).toBe(false);}});
 it('blocked 石化 has neither damage nor resistance, while resisted 石化 still deals five',()=>{let s=ready();card(s,'a2-p18-r2c1',true);const teleport=handCard(s,'B','転移');s=cast(s,'a2-p18-r2c1');s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false});s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.rolls?.some(r=>r.purpose==='status-resistance')??false).toBe(false);s=nextAction(s);card(s,'a2-p18-r2c1',true);s=finish(resistance(cast(s,'a2-p18-r2c1'),[1,1]));expect(s.players.B!.damage).toBe(5);});
 for(const id of ['a2-p12-r2c1','a2-p14-r3c1','a2-p14-r3c2'])it(`${id} rejects wrong target before cost and loses paid card on cancellation/check failure`,()=>{let s=ready();character(s,'A','侍大将のシン');card(s,id);s.players.A!.permanent={warrior_level:-6,magic_level:-6};s.players.A!.damage=4;rejectUnchanged(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:id,targetIds:['B'],dedicated:false},'INVALID_TARGET');s=finish(failedCheck(heal(s,id)));expect(s.players.A!.damage).toBe(4);expect(discardIds(s)).toContain(id);expect(s.phase).toBe('hand-adjustment');s=nextAction(s);card(s,id);s=canceled(heal(s,id),id);expect(s.players.A!.damage).toBe(4);expect(discardIds(s)).toContain(id);expect(s.phase).toBe('hand-adjustment');});
 it('silence distinguishes warrior healing from spell healing without waiving Jill checks',()=>{let s=ready();character(s,'A','大神官ジル');s.players.A!.damage=4;s.players.A!.statuses=[{id:'silence',kind:'silenced',modifiers:[0],nextCheck:0}];card(s,'a2-p14-r3c1');rejectUnchanged(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p14-r3c1',targetIds:['A'],dedicated:false},'SILENCED');card(s,'a2-p12-r2c1');s=finish(heal(s,'a2-p12-r2c1'));expect(s.players.A!.damage).toBe(0);s=nextAction(s);s.players.A!.statuses=[];s.players.A!.permanent={magic_level:-5};near(s);s=heal(s,'a2-p14-r3c1',true,['B']);s=until(s,'before-roll');expect(s.rolls!.at(-1)!.purpose).toBe('excess-level');});
 it('Jill resolution invalidation consumes the card without retargeting self',()=>{let s=ready();character(s,'A','大神官ジル');near(s);s.players.A!.damage=4;s.players.B!.damage=4;card(s,'a2-p14-r3c2');s=heal(s,'a2-p14-r3c2',true,['B']);s.distances.A!.B='far';s.distances.B!.A='far';s=finish(s);expect(s.players.A!.damage).toBe(4);expect(s.players.B!.damage).toBe(4);expect(discardIds(s)).toContain('a2-p14-r3c2');});
 it('滅界 invalid declaration has no cost, failed check costs exactly ten, Vanmil omits only damage',()=>{let s=ready();card(s,'a2-p13-r2c3',true);rejectUnchanged(s,'A',{type:'ATTACK',cardInstanceId:'a2-p13-r2c3',targetIds:['A'],dedicated:false},'INVALID_TARGET');s=finish(failedCheck(cast(s,'a2-p13-r2c3')));expect(s.players.A!.damage).toBe(10);s=nextAction(s);character(s,'A','破壊神ヴァンミール');s.players.A!.damage=4;s.players.A!.permanent={magic_level:-3};card(s,'a2-p13-r2c3',true);const follower=handCard(s,'A','兵士');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==follower);s.players.A!.followers=[{cardInstanceId:follower,revealed:false}];s=finish(failedCheck(cast(s,'a2-p13-r2c3',true)));expect(s.players.A!.damage).toBe(4);expect(s.players.A!.followers).toEqual([]);});
 it('滅界 target20 and own10 commit as one simultaneous death batch with no premature winner',()=>{let s=ready();character(s,'A','大神官ジル');s.players.A!.damage=9;card(s,'a2-p13-r2c3',true);s=until(cast(s,'a2-p13-r2c3'),'death-gift');expect(s.outcome).toBeUndefined();expect(s.players.A!.presence).toBe('pending-death');expect(s.players.B!.presence).toBe('pending-death');expect(s.lifecycle!.find(t=>t.kind==='death-batch')).toMatchObject({actorIds:['A','B'],intents:[{targetId:'B',damage:20},{targetId:'A',damage:10,cause:'self-damage'}]});s=finish(s);expect(s.resolution).toEqual([]);});
 it('滅界 defense restriction rejects maai, evade, and negate before their cards are paid',()=>{let s=ready();card(s,'a2-p13-r2c3',true);const maai=card(s,'a2-p06-r3c1');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==maai);s.players.B!.hand.push(maai);const evade=card(s,'a2-p05-r3c1');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==evade);s.players.B!.hand.push(evade);const negate=card(s,'a2-p18-r2c2');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==negate);s.players.B!.hand.push(negate);s=until(cast(s,'a2-p13-r2c3'),'normal-defense');rejectUnchanged(s,'B',{type:'PLAY_MAAI',cardInstanceId:maai},'ILLEGAL_DEFENSE');for(const id of [evade,negate])rejectUnchanged(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:id,dedicated:false},'ILLEGAL_DEFENSE');});
 it('ordinary 封獄死霊陣 rejects GOOD and destroys low followers without offering duration',()=>{let s=ready();card(s,'a2-p13-r3c3',true);rejectUnchanged(s,'A',{type:'ATTACK',cardInstanceId:'a2-p13-r3c3',targetIds:['B'],dedicated:false},'UNSUPPORTED_CARD');character(s,'A','邪祭ウーノス');const follower=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==follower);s.players.B!.followers=[{cardInstanceId:follower,revealed:false}];s=finish(cast(s,'a2-p13-r3c3'));expect(s.players.B!.followers).toEqual([]);expect(s.players.B!.damage).toBe(10);expect(s.players.B!.statuses??[]).toEqual([]);});
});
describe('Task7g persistent timing and future stats',()=>{
 it('soul drain changes future derived stats at its failed hit before the next target, while frozen action values remain',()=>{let s=ready();character(s,'A','魔聖母ディア');card(s,'a2-p15-r2c3');const before=derivedStats(s.players.B!).spirit;s=cast(s,'a2-p15-r2c3',true,['B','C']);s=resistance(s);const action=Object.values(s.actions!)[0]!;const frozen=JSON.stringify(action.technique);s=pick(s,'decline');expect(s.windows!.at(-1)?.kind).toBe('follower-entry-abilities');expect(derivedStats(s.players.B!).spirit).toBe(before-1);expect(JSON.stringify(s.actions![action.id]!.technique)).toBe(frozen);});
 it('ordinary soul drain is near, keeps followers, accumulates to zero, and survives Lancelot transformation',()=>{let s=ready();character(s,'A','魔聖母ディア');character(s,'B','聖騎士ランスロット');card(s,'a2-p15-r2c3');rejectUnchanged(s,'A',{type:'ATTACK',cardInstanceId:'a2-p15-r2c3',targetIds:['B'],dedicated:false},'OUT_OF_RANGE');near(s);s=finish(resistance(cast(s,'a2-p15-r2c3')));s=nextAction(s);card(s,'a2-p15-r2c3');s=finish(resistance(cast(s,'a2-p15-r2c3')));expect(s.players.B!.statuses?.filter(t=>t.kind==='stat-drain')).toHaveLength(2);character(s,'D','リーア姫');s=act(s,'D',{type:'REVEAL_CHARACTER'});s=finish(s);s=act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'});s=closeWindow(s);expect(derivedStats(s.players.B!).warrior_level).toBe(4);expect(s.players.B!.statuses?.filter(t=>t.kind==='stat-drain')).toHaveLength(2);s.players.B!.permanent={warrior_level:-20,magic_level:-20,spirit:-20};expect(derivedStats(s.players.B!)).toMatchObject({warrior_level:0,magic_level:0,spirit:0});});
 it('Dia full heal waits for actual death disposal; successful resistance or declining death grants no healing',()=>{for(const mode of ['apply','decline','resist'] as const){let s=ready();character(s,'A','魔聖母ディア');s.players.A!.damage=5;card(s,'a2-p15-r2c3');s=resistance(cast(s,'a2-p15-r2c3',true),mode==='resist'?[1,1]:[6,6]);if(mode!=='resist')s=pick(s,mode);expect(s.players.A!.damage).toBe(5);s=finish(s);expect(s.players.A!.damage).toBe(mode==='apply'?0:5);expect(s.players.B!.statuses?.some(t=>t.kind==='stat-drain')??false).toBe(mode==='decline');}});
 it('shared fixed-duration result accepts a whole-roll reroll, later targets reuse it',()=>{let s=ready();character(s,'A','邪祭ウーノス');card(s,'a2-p13-r3c3',true);const god=handCard(s,'A','神性介入');s=until(cast(s,'a2-p13-r3c3',true,['B','C']),'lifetime-effect-choice');s=pick(s,'apply');const rollId=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.faces).toEqual([3]);s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:rollId});s=closeWindow(s,[5]);s=until(s,'lifetime-effect-choice');s=pick(s,'apply');s=finish(s);expect(s.rolls!.find(r=>r.id===rollId)!.attempts.map(a=>a.faces)).toEqual([[3],[5]]);expect(viewFor(s,'A').players.B!.statuses[0]).toMatchObject({remainingTurns:5});expect(viewFor(s,'A').players.C!.statuses[0]).toMatchObject({remainingTurns:5});});
 it('whole-turn skip decrements independent fixed counters but postpones deadly recovery exactly once',()=>{let s=ready();character(s,'A','魔聖母ディア');card(s,'a2-p15-r3c1',true);s=finish(resistance(cast(s,'a2-p15-r3c1',true)));s.players.B!.statuses!.push({id:'fixed1',kind:'stopped',timing:'fixed-turns',remainingTurns:1},{id:'fixed2',kind:'stopped',timing:'fixed-turns',remainingTurns:2});s.players.B!.skipTurns=1;s.turnSeat=1;s.phase='turn-start';s=act(s,'B',{type:'START_TURN'});expect(s.players.B!.statuses!.map(t=>t.id)).not.toContain('fixed1');expect(viewFor(s,'B').players.B!.statuses).toContainEqual({kind:'stopped',timing:'fixed-turns',remainingTurns:1});expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toHaveLength(0);s.turnSeat=1;s.phase='turn-start';s=act(s,'B',{type:'START_TURN'});s=closeWindow(s,[1,1]);s=closeWindow(s);expect(s.players.B!.statuses).toEqual([]);expect(s.turnSeat).toBe(2);});
 it('removing the linked deadly stop also removes its lethal deadline; ordinary modifier remains minus one',()=>{let s=ready();card(s,'a2-p15-r3c1',true);s=finish(resistance(cast(s,'a2-p15-r3c1')));expect(viewFor(s,'B').players.B!.statuses[0]).toMatchObject({timing:'deadly-recovery',recoveryModifier:-1});s.players.B!.statuses=[];s.turnSeat=1;s.phase='turn-start';s=act(s,'B',{type:'START_TURN'});expect(s.phase).toBe('draw');expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toHaveLength(0);});
 it('actual 裂界 keeps possessions and living enemies, yet actual protector death sends its away follower wandering',()=>{let s=ready();character(s,'A','白魔術師シェリム');character(s,'B','侍大将のシン');character(s,'C','リーア姫');s.players.C!.permanent={spirit:-4};character(s,'D','魔導王ガイナス');card(s,'a2-p14-r2c2',true);s=cast(s,'a2-p14-r2c2',true);s=until(s,'lifetime-effect-choice');s=pick(s,'decline');s=closeWindow(s,[6,6]);s=finish(closeWindow(s));expect(s.players.B!.presence).toBe('otherworld');s=nextAction(s);character(s,'A','邪祭ウーノス');card(s,'a2-p18-r2c1',true);s=finish(resistance(cast(s,'a2-p18-r2c1',false,['C'])));expect(s.players.C!.presence).toBe('dead');expect(s.players.B!.presence).toBe('wandering');expect(s.players.B!.hand).toEqual([]);});
});
describe('Task7g resurrection and settlement edges',()=>{
 it('ordinary resurrection requires chant and checks, consumes failures, and resurrects petrification without restoring drain/history',()=>{let s=ready();character(s,'A','邪祭ウーノス');s.players.B!.statuses=[{id:'drain',kind:'stat-drain',timing:'until-death',amount:2}];s.used=['once-game'];s.players.B!.permanent={spirit:1};card(s,'a2-p18-r2c1',true);s=finish(resistance(cast(s,'a2-p18-r2c1')));expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.statuses).toEqual([]);s=nextAction(s);card(s,'a2-p13-r3c1');rejectUnchanged(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['B'],dedicated:false},'CHANT_REQUIRED');s=act(s,'A',{type:'CHANT',cardInstanceId:'a2-p13-r3c1'});s=nextAction(s);s=finish(failedCheck(heal(s,'a2-p13-r3c1',false,['B'])));expect(s.players.B!.presence).toBe('dead');expect(discardIds(s)).toContain('a2-p13-r3c1');s=nextAction(s);card(s,'a2-p13-r3c1',true);s=until(heal(s,'a2-p13-r3c1',false,['B']),'re-setup');expect(s.players.B).toMatchObject({presence:'active',damage:0,statuses:[],permanent:{spirit:1}});s=act(s,'B',{type:'PASS_SETUP'});expect(s.used).toContain('once-game');expect(s.phase).toBe('hand-adjustment');});
 it('resurrection conversion rejects every fixed character even same faction, permits exactly fifteen flexible and conditional Dia/Yotsurumu',()=>{const flexible=['大神官ジル','小妖精のチャム','有翼人のティア','早駆けのランカスター','小人のランバ','吟遊詩人のレスター','黒妖精のアーネス','凍気のアイエル','竜皇子アスフェルト','占星術師のアルセイル','忍びのイダ','邪祭ウーノス','獣使いのウパニシャット','黒騎士ガーウィン','爆炎のフレイアード'];for(const name of flexible){let s=ready();character(s,'A','邪祭ウーノス');character(s,'B',name);dead(s,'B');card(s,'a2-p13-r3c1');s=heal(s,'a2-p13-r3c1',true,['B'],['B']);expect(s.resolution).toContain('a2-p13-r3c1');}for(const name of ['白魔術師シェリム','侍大将のシン','妖精王フューリー','聖騎士ランスロット','リーア姫','聖騎士ランスロット2','魔導王ガイナス','不死王ガドューラ','破壊神ヴァンミール']){const s=ready();character(s,'A','邪祭ウーノス');character(s,'B',name);dead(s,'B');card(s,'a2-p13-r3c1');rejectUnchanged(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['B'],dedicated:true,convertTargetIds:['B']},'INVALID_TARGET');}for(const name of ['魔聖母ディア','餓狼ヨーツルム'])for(const faction of ['GOOD','EVIL','ヴァンミール'] as const){let s=ready();character(s,'A','邪祭ウーノス');s.players.A!.faction=faction;character(s,'B',name);dead(s,'B');card(s,'a2-p13-r3c1');const command={type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['B'],dedicated:true,convertTargetIds:['B']};if(faction==='GOOD')rejectUnchanged(s,'A',command,'INVALID_TARGET');else s=act(s,'A',command);}});
 it('dedicated resurrection is an explicit dead subset, retains nonconverted allegiance, and waits for every re-setup',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','大神官ジル');character(s,'C','魔導王ガイナス');dead(s,'B');dead(s,'C');card(s,'a2-p13-r3c1');s=until(heal(s,'a2-p13-r3c1',true,['B','C']),'re-setup');expect(s.players.B!.faction).toBe('GOOD');expect(s.players.C!.presence).toBe('dead');s=act(s,'B',{type:'PASS_SETUP'});expect(s.players.C!.presence).toBe('active');s=act(s,'C',{type:'PASS_SETUP'});expect(s.phase).toBe('hand-adjustment');expect(s.rolls?.length??0).toBe(0);});
 it('dedicated resurrection copies current resolved allegiance and removes old protection; invalidated targets never retarget',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','大神官ジル');dead(s,'B');card(s,'a2-p13-r3c1');s=heal(s,'a2-p13-r3c1',true,['B'],['B']);s.players.A!.faction='GOOD';s.players.A!.currentObjective={kind:'extinction',enemyFactions:['ヴァンミール']};s.players.A!.protection={characterIds:[]};s=until(s,'re-setup');expect(s.players.B).toMatchObject({faction:'GOOD',currentObjective:{enemyFactions:['ヴァンミール']},protection:{characterIds:[]}});s=act(s,'B',{type:'PASS_SETUP'});s=ready();character(s,'A','邪祭ウーノス');dead(s,'B');card(s,'a2-p13-r3c1');s=heal(s,'a2-p13-r3c1',true,['B']);s.players.B!.presence='active';s.players.B!.damage=4;s=finish(s);expect(s.players.B!.damage).toBe(4);expect(discardIds(s)).toContain('a2-p13-r3c1');});
 it('actual resurrection returns protected wanderers before resuming the exact suspended hand adjustment',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','リーア姫');character(s,'C','侍大将のシン');character(s,'D','魔導王ガイナス');dead(s,'B');dead(s,'C');s.players.C!.presence='wandering';s.players.C!.damage=2;card(s,'a2-p13-r3c1');s=until(heal(s,'a2-p13-r3c1',true,['B']),'re-setup');s=act(s,'B',{type:'PASS_SETUP'});expect(s.windows!.at(-1)!.kind).toBe('re-setup');expect(s.players.C).toMatchObject({presence:'active',damage:2});s=act(s,'C',{type:'PASS_SETUP'});expect(s.turnSeat).toBe(0);expect(s.phase).toBe('hand-adjustment');});
 it('Vanmil dedicated destruction omits the self-damage intent while still destroying its followers',()=>{let s=ready();character(s,'A','破壊神ヴァンミール');card(s,'a2-p13-r2c3',true);s=until(cast(s,'a2-p13-r2c3',true),'death-gift');const batch=s.lifecycle!.find(t=>t.kind==='death-batch')!;expect(batch).toMatchObject({intents:[{targetId:'B',damage:20}]});if(batch.kind==='death-batch')expect(batch.intents).toHaveLength(1);});
 it('Dia cannot heal herself out of a simultaneous pending death',()=>{let s=ready();character(s,'A','魔聖母ディア');card(s,'a2-p15-r2c3');s=resistance(cast(s,'a2-p15-r2c3',true));s.players.A!.damage=derivedStats(s.players.A!).endurance;s=pick(s,'apply');expect(s.players.A!.presence).toBe('pending-death');expect(s.players.B!.presence).toBe('pending-death');s=finish(s);expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.damage).toBeGreaterThan(0);});
});
it('Dia healing depends on actual committed death even if that victim is revived by a nested later death gift',()=>{let s=ready();character(s,'A','魔聖母ディア');character(s,'B','大神官ジル');character(s,'C','魔導王ガイナス');s.players.A!.damage=5;card(s,'a2-p15-r2c3');const gift=handCard(s,'C','「これで勝ったと思うなよ」');const transferable=handCard(s,'C','香具羅');const fate=handCard(s,'A','命運凶変');s=resistance(cast(s,'a2-p15-r2c3',true));s.players.C!.damage=derivedStats(s.players.C!).endurance;s=pick(s,'apply');s=pass(s);expect(s.players.B!.presence).toBe('dead');expect(s.windows!.at(-1)!.participants).toEqual(['C']);top(s,'a2-p01-r1c1');s=act(s,'C',{type:'PLAY_DEATH_GIFT',cardInstanceId:gift,giftCardInstanceId:transferable,targetId:'D'});const giftAction=s.windows!.at(-1)!.continuation.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='A')s=pass(s);s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:giftAction});s=closeWindow(s,[1]);s=closeWindow(s);s=act(s,'B',{type:'CHOOSE_REVIVAL',revive:true});s=act(s,'B',{type:'PASS_SETUP'});s=finish(s);expect(s.players.B!.presence).toBe('active');expect(s.players.C!.presence).toBe('dead');expect(s.players.A!.damage).toBe(0);});
it('actual Dawn returns all 裂界 targets in current-turn order before its body without new setup or clearing independent status',()=>{let s=ready();character(s,'A','白魔術師シェリム');character(s,'D','魔導王ガイナス');card(s,'a2-p14-r2c2',true);s=until(cast(s,'a2-p14-r2c2',true,['B','D']),'lifetime-effect-choice');s=pick(s,'decline');s=closeWindow(s,[6,6]);s=closeWindow(s);s=until(s,'lifetime-effect-choice');s=pick(s,'decline');s=closeWindow(s,[6,6]);s=finish(closeWindow(s));expect(s.players.B!.presence).toBe('otherworld');expect(s.players.D!.presence).toBe('otherworld');const bhand=[...s.players.B!.hand],dhand=[...s.players.D!.hand];s.players.B!.statuses=[{id:'independent',kind:'silenced',modifiers:[0],nextCheck:1}];top(s,'a2-p01-r1c2');s.turnSeat=2;s.phase='draw';s=act(s,'C',{type:'CHOOSE_DRAW',draw:true});expect(s.events.filter(e=>e.type==='PLAYER_RETURNED').map(e=>e.actorId)).toEqual(['D','B']);expect(s.players.B!.hand).toEqual(bhand);expect(s.players.D!.hand).toEqual(dhand);expect(s.players.B!.statuses).toHaveLength(1);expect(s.windows??[]).toEqual([]);expect(s.phase).toBe('action');});
it('ordinary 裂界 accepts three targets with effect7 damage8 and target-local unmodified spirit checks',()=>{let s=ready();character(s,'A','白魔術師シェリム');character(s,'C','魔導王ガイナス');character(s,'D','不死王ガドューラ');card(s,'a2-p14-r2c2',true);s=cast(s,'a2-p14-r2c2',false,['B','C','D']);s=resistance(s,[1,1]);expect(s.rolls!.at(-1)!.modifier).toBe(0);s=resistance(s,[6,6]);s=finish(s);expect(s.players.B!.presence).toBe('active');expect(s.players.C!.presence).toBe('otherworld');expect(s.players.B!.damage).toBe(8);expect(s.players.C!.damage).toBe(8);expect(s.rolls!.filter(r=>r.purpose==='status-resistance')).toHaveLength(3);});
it('whole-roll Fate failure survives reroll on Gadyura resistance and still commits ordinary8 with instantdeath',()=>{let s=ready();character(s,'A','不死王ガドューラ');card(s,'a2-p09-r3c1',true);const fate=handCard(s,'A','命運凶変'),god=handCard(s,'C','神性介入');s=until(cast(s,'a2-p09-r3c1',true),'lifetime-effect-choice');s=pick(s,'apply');s=closeWindow(s,[1,1]);const rollId=s.rolls!.at(-1)!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:rollId});s=passReclaims(closeWindow(s));while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='C')s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:rollId});s=closeWindow(s,[1,1]);s=until(s,'death-gift');expect(s.players.B!.damage).toBe(8);expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({forcedFailure:true,success:false,faces:[1,1]});s=finish(s);expect(s.players.B!.presence).toBe('dead');});
it('a canceled nested counter to 滅界 preserves the parent cost and finishes all reservations',()=>{let s=ready();character(s,'A','破壊神ヴァンミール');character(s,'B','早駆けのランカスター');card(s,'a2-p13-r2c3',true);const counter=handCard(s,'B','閃光槍');const fate=handCard(s,'C','命運凶変');s=until(cast(s,'a2-p13-r2c3'),'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:true});const action=s.windows!.at(-1)!.continuation.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='C')s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:action});s=finish(s);expect(s.players.A!.damage).toBe(10);expect(s.players.B!.damage).toBe(20);expect(s.players.B!.presence).toBe('dead');expect(s.resolution).toEqual([]);expect(s.reclaimReservations).toEqual([]);expect(Object.values(s.actions??{})).toEqual([]);});
it('public 滅界 defense restrictions expose only its permitted printed methods',()=>{let s=ready();card(s,'a2-p13-r2c3',true);s=until(cast(s,'a2-p13-r2c3'),'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toEqual({maaiProhibited:true,evadeProhibited:true,counterProhibited:false,limitedDefenses:['teleport','counter']});});
const attackModes=[
 ['a2-p09-r3c1','不死王ガドューラ',false,7,7,8,'warrior',true,false,'far'],['a2-p09-r3c1','不死王ガドューラ',true,7,7,8,'warrior',true,true,'far'],
 ['a2-p13-r2c3','破壊神ヴァンミール',false,10,10,20,'magic',true,false,'far'],['a2-p13-r2c3','破壊神ヴァンミール',true,10,10,20,'magic',true,false,'far'],
 ['a2-p13-r3c3','邪祭ウーノス',false,8,8,10,'magic',true,false,'far'],['a2-p13-r3c3','邪祭ウーノス',true,8,8,10,'magic',true,true,'far'],
 ['a2-p14-r2c2','白魔術師シェリム',false,7,7,8,'magic',true,false,'far'],['a2-p14-r2c2','白魔術師シェリム',true,7,8,12,'magic',true,true,'far'],
 ['a2-p15-r2c3','魔聖母ディア',false,7,7,null,'magic',false,false,'near'],['a2-p15-r2c3','魔聖母ディア',true,7,8,null,'magic',false,true,'far'],
 ['a2-p15-r3c1','魔聖母ディア',false,7,7,null,'magic',true,false,'far'],['a2-p15-r3c1','魔聖母ディア',true,7,8,null,'magic',true,true,'far'],
 ['a2-p18-r2c1','邪祭ウーノス',false,7,7,5,'magic',true,false,'far'],
] as const;
it.each(attackModes)('source mode %s %s dedicated=%s declares exact printed values then consumes the physical card',(id,name,dedicated,useLevel,effectLevel,damage,school,chant,noChecks,range)=>{let s=ready();character(s,'A',name);card(s,id,chant);near(s);s=cast(s,id,dedicated);expect(Object.values(s.actions!)[0]!.technique).toMatchObject({useLevel,effectLevel,damage,school,chant,noChecks,range});s=finish(s);expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(allCardInstanceIds(s)).toHaveLength(220);expect(new Set(allCardInstanceIds(s)).size).toBe(220);});
it('petrification retains durable cause and accepted source-event identity after the death batch is gone',()=>{let s=ready();character(s,'A','邪祭ウーノス');card(s,'a2-p18-r2c1',true);s=cast(s,'a2-p18-r2c1');const eventId=Object.values(s.actions!)[0]!.eventId;s=finish(resistance(s));expect(s.lifecycle??[]).toEqual([]);expect(viewFor(s,'C').logs.find(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toMatchObject({death:{cause:'petrification',eventId,sourceActorId:'A',sourceCardInstanceId:'a2-p18-r2c1'}});});
