import {describe,it,expect} from 'vitest';
import {allCardInstanceIds,transition,viewFor,derivedStats,type GameState, discardIds, moveToDiscard } from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow,passReclaims,readySetup} from './combat-helpers.js';
import {character,handCard,entropy,freshGame} from './fixtures.js';
function attackLethal(){let s=ready();character(s,'A','侍大将のシン');character(s,'B','黒騎士ガーウィン');s.players.B!.damage=derivedStats(s.players.B!).endurance-1;const id=handCard(s,'A','衝破');s=act(s,'A',{type:'ATTACK',cardInstanceId:id,targetIds:['B'],dedicated:false});return s;}
function takeTop(s:GameState,id:string){for(const p of Object.values(s.players)){p.hand=p.hand.filter(x=>x!==id);p.open=p.open.filter(x=>x!==id);}s.deck=s.deck.filter(x=>x!==id);s.discard = s.discard.filter(entry => entry.cardInstanceId !== id);s.deck.unshift(id);}
describe('shared lifecycle',()=>{
 it('real lethal attack opens a public death gift before disposal and survives JSON',()=>{let s=attackLethal();for(let i=0;i<150&&s.windows?.at(-1)?.kind!=='death-gift';i++){if(!s.windows?.length)break;s=pass(s);}expect(s.players.B!.presence).toBe('pending-death');expect(s.windows?.at(-1)?.kind).toBe('death-gift');s=pass(s);expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.hand).toEqual([]);expect(viewFor(s,'A').players.B).toMatchObject({presence:'dead'});});
 it('FuSen interrupts actual draw with a fixed threshold d6 check then resumes setup',()=>{let s=ready();s.phase='draw';s.players.B!.presence='dead';takeTop(s,'a2-p01-r1c1');const before=s.players.A!.hand.length;s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});expect(s.windows?.at(-1)?.kind).toBe('before-roll');s=closeWindow(s,[4]);expect(s.rolls?.at(-1)).toMatchObject({threshold:4,faces:[4],success:true});s=closeWindow(s);expect(s.windows?.at(-1)?.kind).toBe('revival');s=act(s,'B',{type:'CHOOSE_REVIVAL',revive:true});expect(s.players.B).toMatchObject({presence:'active',damage:0,revealed:true});expect(s.windows?.at(-1)?.kind).toBe('re-setup');s=act(s,'B',{type:'PASS_SETUP'});expect(s.players.A!.hand.length).toBe(before+1);expect(s.phase).toBe('action');});
 it('initial character contracts distinguish absent protection from dead actors',()=>{const s=freshGame();expect(s.players.A).toHaveProperty('currentObjective');expect(s.players.A).toHaveProperty('protection');});
 it('stable faction victory is persisted and rejects subsequent gameplay',()=>{let s=ready();character(s,'A','リーア姫');for(const id of ['B','C','D'])s.players[id]!.presence='dead';s=act(s,'A',{type:'PASS_ACTION'});expect(viewFor(s,'A').outcome).toMatchObject({kind:'victory',winnerIds:['A']});const before=JSON.stringify(s);expect(transition(s,{actorId:'A',command:{type:'END_TURN',discardIds:[]} },entropy())).toEqual({ok:false,code:'GAME_COMPLETE'});expect(JSON.stringify(s)).toBe(before);});
});
describe('explicit gift and identity transitions',()=>{
 it('death gift pays the gift card once and transfers a distinct private card without refill',()=>{let s=attackLethal();const gift=handCard(s,'B','「これで勝ったと思うなよ」');const card=handCard(s,'B','香具羅');s=until(s,'death-gift');const hand=s.players.B!.hand.length;s=act(s,'B',{type:'PLAY_DEATH_GIFT',cardInstanceId:gift,giftCardInstanceId:card,targetId:'C'});expect(s.windows?.at(-1)?.kind).toBe('declaration');expect(s.players.B!.hand.length).toBe(hand-1);s=closeWindow(s);expect(s.players.C!.hand).toContain(card);expect(viewFor(s,'A').logs.filter(log=>log.type==='CARD_GIFTED').some(log=>log.cardInstanceId===card)).toBe(false);expect(viewFor(s,'C').privateLogs.some(log=>log.type==='CARD_GIFTED'&&log.cardInstanceId===card)).toBe(true);s=finish(s);expect(discardIds(s)).toContain(gift);});
 it('a canceled gift keeps its intended card until death disposal',()=>{let s=attackLethal();const gift=handCard(s,'B','「これで勝ったと思うなよ」');const card=handCard(s,'B','香具羅');const fate=handCard(s,'C','命運凶変');s=until(s,'death-gift');s=act(s,'B',{type:'PLAY_DEATH_GIFT',cardInstanceId:gift,giftCardInstanceId:card,targetId:'C'});const action=s.windows!.at(-1)!.continuation.id;s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:action});s=closeWindow(s);s=closeWindow(s);expect(s.players.B!.hand).toContain(card);expect(s.players.C!.hand).not.toContain(card);s=finish(s);expect(discardIds(s)).toContain(card);});
 it('S28 Lancelot transformation retains damage4 use history and old abilities',()=>{let s=ready();character(s,'A','聖騎士ランスロット');character(s,'C','リーア姫');s.players.A!.damage=4;s.used=['once-history'];s=act(s,'C',{type:'REVEAL_CHARACTER'});expect(viewFor(s,'A').lifecycleAbilities).toContain('lancelot-transform');s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'});s=closeWindow(s);expect(s.players.A).toMatchObject({characterId:'c2-p07-r1c1',damage:4,abilityCharacterIds:['c2-p02-r2c2','c2-p07-r1c1']});expect(s.used).toContain('once-history');});
 it('S28 actual Uonos ritual heals damage4 to0 without inherited abilities and permits Vanmil choices',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','占星術師のアルセイル');character(s,'C','魔聖母ディア');character(s,'D','餓狼ヨーツルム');s.players.A!.damage=4;handCard(s,'A','復活の儀式');s=act(s,'A',{type:'USE_REVIVAL_RITUAL'});expect(s.windows?.at(-1)?.kind).toBe('declaration');s=closeWindow(s);expect(s.players.A).toMatchObject({characterId:'c2-p07-r1c2',faction:'ヴァンミール',damage:0,revealed:true,abilityCharacterIds:['c2-p07-r1c2']});expect(derivedStats(s.players.A!).endurance).toBe(25);s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'});s=closeWindow(s);expect(s.players.C!.faction).toBe('ヴァンミール');s=pass(s);s=act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'});s=closeWindow(s);expect(s.players.B!.presence).toBe('exited');expect(viewFor(s,'B').individualResults).toEqual({B:'won'});});
 it('Dia ritual transfer is card-specific, does not reveal/refill and bypasses ability-disabled',()=>{let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','魔聖母ディア');s.players.A!.revealed=true;s.players.B!.statuses=[{id:'disable',kind:'ability-disabled',modifiers:[0],nextCheck:0}];const ritual=handCard(s,'B','復活の儀式');const count=s.players.B!.hand.length;s=act(s,'B',{type:'TRANSFER_RITUAL',targetId:'A'});expect(s.players.A!.hand).toContain(ritual);expect(s.players.B!.hand.length).toBe(count-1);expect(s.players.B!.revealed).toBe(false);expect(s.windows?.length??0).toBe(0);});
});
describe('lifecycle invariants and saved continuations',()=>{
 it('commits all simultaneous victims before the first death window and forbids cross gifts',()=>{let s=ready();character(s,'A','忍びのイダ');character(s,'B','黒騎士ガーウィン');character(s,'C','魔導王ガイナス');s.players.B!.damage=15;s.players.C!.damage=19;const attack=handCard(s,'A','手裏剣');const gift=handCard(s,'B','「これで勝ったと思うなよ」');const transferable=handCard(s,'B','香具羅');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B','C'],dedicated:true});s=until(s,'hit');s=closeWindow(s);expect(s.players.B!.damage).toBe(15);expect(s.players.C!.damage).toBe(19);s=until(s,'death-gift');expect(s.players.B!.presence).toBe('pending-death');expect(s.players.C!.presence).toBe('pending-death');expect(transition(s,{actorId:'B',command:{type:'PLAY_DEATH_GIFT',cardInstanceId:gift,giftCardInstanceId:transferable,targetId:'C'}},entropy())).toEqual({ok:false,code:'INVALID_TARGET'});expect(viewFor(s,'B').lifecycleDecision!.eligibleTargetIds).not.toContain('C');expect(allCardInstanceIds(s)).toHaveLength(220);});
 it('death disposes all owned zones and distance markers owned by the other endpoint once',()=>{let s=attackLethal();const follower=handCard(s,'B','兵士');const chant=handCard(s,'B','氷狼乱舞陣');const attachment=handCard(s,'B','香具羅');const open=handCard(s,'B','祝福');const marker=handCard(s,'A','踏み込み／弓');for(const id of [follower,chant,attachment,open])s.players.B!.hand=s.players.B!.hand.filter(x=>x!==id);s.players.A!.hand=s.players.A!.hand.filter(x=>x!==marker);s.players.B!.followers=[{cardInstanceId:follower,revealed:false}];s.players.B!.chants=[{cardInstanceId:chant,revealed:false}];s.players.B!.attachments=[attachment];s.players.B!.open=[...s.players.B!.open,open];s.distanceMarkers={'A:B':{a:'A',b:'B',ownerId:'A',cardInstanceId:marker}};s.distances.A!.B='near';s.distances.B!.A='near';s=until(s,'death-gift');s=pass(s);for(const id of [follower,chant,attachment,open,marker])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(s.distances.A!.B).toBe('far');expect(s.distanceMarkers).toEqual({});expect(allCardInstanceIds(s)).toHaveLength(220);});
 it('FuSen force-failure survives a later whole-d6 reroll and never uses spirit',()=>{let s=ready();s.phase='draw';s.players.B!.presence='dead';s.players.B!.revealed=true;takeTop(s,'a2-p01-r1c1');const fate=handCard(s,'A','命運凶変');const god=handCard(s,'C','神性介入');s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});s=closeWindow(s,[1]);const rollId=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.threshold).toBe(4);s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:rollId});s=closeWindow(s);s=passReclaims(s);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='C')s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:rollId});s=closeWindow(s,[2]);s=finish(s);expect(s.players.B!.presence).toBe('dead');expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({forcedFailure:true,faces:[2],success:false,attempts:[{faces:[1]},{faces:[2]}]});});
 it('reaction refill opens FuSen before the child declaration and resumes the exact parent',()=>{let s=ready();s.players.D!.presence='dead';const attack=handCard(s,'A','衝破');const fate=handCard(s,'A','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});const parent=s.windows!.at(-1)!.continuation.id;takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:parent});expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(viewFor(s,'A').lifecycleDecision).toBeNull();expect(s.resolution).toContain(fate);s=closeWindow(s,[4]);s=closeWindow(s);s=act(s,'D',{type:'CHOOSE_REVIVAL',revive:false});expect(s.windows!.at(-1)!.kind).toBe('declaration');expect(s.actions![parent]).toBeDefined();s=finish(s);expect(discardIds(s)).toContain(fate);expect(discardIds(s)).toContain(attack);expect(allCardInstanceIds(s)).toHaveLength(220);});
 it('Dawn returns otherworld with independent stop intact and excludes OPEN and reservations',()=>{let s=ready();s.phase='draw';s.players.B!.presence='otherworld';s.players.B!.statuses=[{id:'stop',kind:'stopped',modifiers:[0],nextCheck:1}];const before=[...s.players.B!.hand];const reservation=handCard(s,'C','香具羅');s.players.C!.hand=s.players.C!.hand.filter(id=>id!==reservation);s.reclaimReservations.push(reservation);takeTop(s,'a2-p01-r1c2');s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});expect(s.players.B).toMatchObject({presence:'active',hand:before,statuses:[{id:'stop'}]});expect(s.players.A!.open).toContain('a2-p01-r1c2');expect(s.deck).not.toContain(reservation);expect(s.reclaimReservations).toContain(reservation);});
 it('multiple named protection uses any assigned death and replacement removes old protection',()=>{let s=ready();character(s,'A','妖精王フューリー');character(s,'B','白魔術師シェリム');character(s,'C','魔導王ガイナス');character(s,'D','リーア姫');s.players.B!.presence='dead';s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.presence).toBe('wandering');expect(s.players.D!.presence).toBe('active');expect(s.players.A!.hand).toEqual([]);});
 it('a surviving third faction does not silently rewrite printed GOOD extinction objective',()=>{let s=ready();character(s,'A','リーア姫');character(s,'B','破壊神ヴァンミール');character(s,'C','魔導王ガイナス');character(s,'D','黒騎士ガーウィン');s.players.C!.presence='dead';s.players.D!.presence='dead';s=act(s,'A',{type:'PASS_ACTION'});expect(s.outcome?.winnerIds).toEqual(['A']);});
 it('a dead Vanmil awards non-Vanmil dead/wandering actors and preserves earlier personal winners',()=>{let s=ready();character(s,'A','破壊神ヴァンミール');character(s,'B','魔導王ガイナス');s.players.A!.damage=25;s.players.B!.presence='dead';s.players.C!.presence='wandering';s.players.D!.presence='exited';s.individualResults={D:'won'};s=act(s,'A',{type:'PASS_ACTION'});s=finish(s);expect(s.outcome?.reason).toBe('vanmil-death');expect(s.outcome?.winnerIds.sort()).toEqual(['B','C','D']);});
});
it('any-time refill finishes revival before computing the child declaration responders',()=>{let s=ready();s.players.D!.presence='dead';const attack=handCard(s,'A','衝破');const fate=handCard(s,'A','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});const parent=s.windows!.at(-1)!.continuation.id;takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:parent});s=closeWindow(s,[1]);s=closeWindow(s);s=act(s,'D',{type:'CHOOSE_REVIVAL',revive:true});s=act(s,'D',{type:'PASS_SETUP'});expect(s.windows!.at(-1)!.kind).toBe('declaration');expect(s.windows!.at(-1)!.participants).toContain('D');});
it('ritual is a root turn-action declaration whose first responder is the current turn seat',()=>{let s=ready();character(s,'A','邪祭ウーノス');handCard(s,'A','復活の儀式');s=act(s,'A',{type:'USE_REVIVAL_RITUAL'});expect(s.windows!.at(-1)!.participants).toEqual(['A','B','C','D']);});
it('source protection replacement clears stale defeat conditions and obeys mandatory fixed allegiance',async()=>{const {replaceAllegiance,factionObjective}=await import('../src/index.js');let s=ready();character(s,'A','大神官ジル');character(s,'B','リーア姫');character(s,'C','魔導王ガイナス');character(s,'D','魔聖母ディア');s.players.B!.presence='dead';expect(replaceAllegiance(s.players.A!,'EVIL',factionObjective('EVIL'),{characterIds:['c2-p05-r2c2']})).toBe(true);expect(replaceAllegiance(s.players.D!,'GOOD',factionObjective('GOOD'),{characterIds:[]})).toBe(false);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.presence).toBe('active');expect(s.players.A!.protection!.characterIds).toEqual(['c2-p05-r2c2']);});
it('optional transformations are suppressed while fixed allegiance and Vanmil death remain mandatory',()=>{let s=ready();character(s,'A','聖騎士ランスロット');character(s,'D','リーア姫');s.players.A!.statuses=[{id:'disable',kind:'ability-disabled',modifiers:[0],nextCheck:1}];s=act(s,'D',{type:'REVEAL_CHARACTER'});expect(viewFor(s,'A').lifecycleAbilities).toEqual([]);expect(transition(s,{actorId:'A',command:{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'}},entropy())).toEqual({ok:false,code:'ABILITY_DISABLED'});});
it('living otherworld participants can satisfy their printed objective while still counting as living enemies',()=>{let s=ready();character(s,'A','黒騎士ガーウィン');character(s,'B','リーア姫');character(s,'C','魔導王ガイナス');character(s,'D','侍大将のシン');s.players.B!.presence='otherworld';s.players.D!.presence='dead';s.players.C!.presence='dead';s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.presence).toBe('wandering');expect(s.outcome?.winnerIds).toEqual(['B']);});
it('protector revival returns a wanderer through initial setup and nested Dawn before the interrupted draw',()=>{let s=ready();character(s,'A','魔導王ガイナス');character(s,'B','リーア姫');character(s,'C','侍大将のシン');character(s,'D','黒騎士ガーウィン');for(const id of ['B','C']){for(const __discarded of [...s.players[id]!.hand])moveToDiscard(s,__discarded,{faceUp:true});s.players[id]!.hand=[];}s.players.B!.presence='dead';s.players.C!.presence='wandering';s.players.C!.damage=2;s.used=['history'];s.phase='draw';takeTop(s,'a2-p01-r1c2');takeTop(s,'a2-p01-r1c1');const handBefore=s.players.A!.hand.length;s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});s=closeWindow(s,[3]);s=closeWindow(s);s=act(s,'B',{type:'CHOOSE_REVIVAL',revive:true});expect(s.players.B!.open).toContain('a2-p01-r1c2');expect(s.players.B!.hand).toHaveLength(5);expect(s.players.A!.hand.length).toBe(handBefore);s=act(s,'B',{type:'PASS_SETUP'});expect(s.windows!.at(-1)!.kind).toBe('re-setup');expect(s.players.C!.presence).toBe('active');expect(s.players.A!.hand.length).toBe(handBefore);expect(s.players.C!.damage).toBe(2);expect(s.players.C!.hand).toHaveLength(5);s=act(s,'C',{type:'PASS_SETUP'});expect(s.players.A!.hand.length).toBe(handBefore+1);expect(s.phase).toBe('action');expect(s.used).toContain('history');expect(allCardInstanceIds(s)).toHaveLength(220);});
it('a maximum-endurance reduction and explicit instant death use the same irreversible shared settlement',async()=>{const {settleDamage}=await import('../src/index.js');let s=ready();s.players.B!.damage=15;s.players.B!.permanent={endurance:-1};settleDamage(s,[{targetId:'C',damage:0,instantDeath:true,cause:'instant-death',sourceActorId:'A',eventId:'accepted-event'}],1000);expect(s.players.B!.presence).toBe('pending-death');expect(s.players.C!.presence).toBe('pending-death');expect(s.lifecycle!.at(-1)).toMatchObject({kind:'death-batch',actorIds:['B','C'],intents:[{eventId:'accepted-event',cause:'instant-death'}]});});
it('turn-end OPEN keeps the ending turn seat until every revival decision and refill is complete',()=>{let s=ready();s.phase='hand-adjustment';s.players.B!.presence='dead';s.deck.push(s.players.A!.hand.pop()!);takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'END_TURN',discardIds:[]});expect(s.turnSeat).toBe(0);expect(s.phase).toBe('hand-adjustment');expect(s.windows!.at(-1)!.participants[0]).toBe('A');s=closeWindow(s,[6]);s=closeWindow(s);expect(s.turnSeat).toBe(2);expect(s.phase).toBe('turn-start');});
it('simultaneous mutual extinction converges through every public gift pass without an undefined actor',()=>{let s=ready();for(const p of Object.values(s.players))p.damage=derivedStats(p).endurance;s=act(s,'A',{type:'PASS_ACTION'});expect(s.windows!.at(-1)!.participants).toEqual(['A']);for(const id of ['A','B','C','D']){expect(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]).toBe(id);s=pass(s);}expect(s.outcome).toMatchObject({kind:'draw',reason:'mutual-extinction',winnerIds:[]});expect(viewFor(s,'A').activeWindow).toBeNull();expect(viewFor(s,'A').legalChoices).toEqual([]);expect(allCardInstanceIds(s)).toHaveLength(220);});
it('a lethal reflected child settles death and resumes the already accepted parent attack',()=>{let s=ready();character(s,'A','白魔術師シェリム');character(s,'B','聖騎士ランスロット');s.players.A!.damage=11;const attack=handCard(s,'A','白光');const mirror=handCard(s,'B','ミラーシールド');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:true});s=until(s,'death-gift');expect(s.players.A!.presence).toBe('pending-death');const batch=s.lifecycle!.find(task=>task.kind==='death-batch');expect(batch).toMatchObject({intents:[{sourceActorId:'B',sourceCardInstanceId:attack,cause:'attack'}]});s=finish(s);expect(s.players.A!.presence).toBe('dead');expect(Object.keys(s.actions??{})).toEqual([]);expect(Object.keys(s.groups??{})).toEqual([]);expect(s.players.B!.damage).toBe(0);expect(s.resolution).toEqual([]);expect(allCardInstanceIds(s)).toHaveLength(220);});
it('recovery refill pauses on FuSen and resumes draw phase with its recovery result saved once',()=>{let s=ready();s.phase='turn-start';s.players.A!.statuses=[{id:'stop',kind:'stopped',modifiers:[0],nextCheck:1}];s.players.B!.presence='dead';s.deck.push(s.players.A!.hand.pop()!);takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'START_TURN'});s=closeWindow(s,[1,1]);s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(s.rolls![0]!.stage).toBe('applied');expect(s.players.A!.statuses).toEqual([]);s=closeWindow(s,[6]);s=closeWindow(s);expect(s.phase).toBe('draw');expect(s.turnSeat).toBe(0);expect(s.players.A!.hand).toHaveLength(5);expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toHaveLength(1);});
it('potion reservation and result survive a reaction refill OPEN without paying or rolling twice',()=>{let s=ready();s.players.A!.damage=4;s.players.D!.presence='dead';const potion=handCard(s,'A','回復の薬');const god=handCard(s,'A','神性介入');s=act(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[potion]},[2]);s=closeWindow(s,[2]);const potionRoll=s.rolls!.at(-1)!.id;takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:potionRoll});expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(s.resolution).toContain(potion);s=closeWindow(s,[6]);s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('declaration');s=closeWindow(s,[5]);s=passReclaims(s);s=closeWindow(s);s=passReclaims(s);expect(s.players.A!.damage).toBe(0);expect(discardIds(s).filter(id=>id===potion)).toHaveLength(1);expect(s.rolls!.find(r=>r.id===potionRoll)!.attempts.map(a=>a.faces)).toEqual([[2],[5]]);expect(s.players.A!.presence).toBe('wandering');expect(s.phase).toBe('turn-start');});
it('stable victory does not draw an unopened future FuSen to delay the ending',()=>{let s=ready();character(s,'A','リーア姫');for(const id of ['B','C','D'])s.players[id]!.presence='dead';takeTop(s,'a2-p01-r1c1');const deck=[...s.deck];s=act(s,'A',{type:'PASS_ACTION'});expect(s.outcome?.winnerIds).toEqual(['A']);expect(s.deck).toEqual(deck);});
it('an initially all-same faction deal waits for every public identity before ending',()=>{let s=ready();for(const [id,name] of [['A','白魔術師シェリム'],['B','大神官ジル'],['C','侍大将のシン'],['D','小妖精のチャム']])character(s,id!,name!);s.initialFactions=['GOOD','GOOD','GOOD','GOOD'];s=act(s,'A',{type:'PASS_ACTION'});expect(s.outcome).toBeUndefined();for(const id of ['A','B','C']){s=act(s,id,{type:'REVEAL_CHARACTER'});expect(s.outcome).toBeUndefined();}s=act(s,'D',{type:'REVEAL_CHARACTER'});expect(s.outcome?.winnerIds).toEqual(['A','B','C','D']);});
it('fully revealed same-faction setup does not finalize until every initial follower choice passes',()=>{let s=freshGame();for(const [id,name] of [['A','白魔術師シェリム'],['B','大神官ジル'],['C','侍大将のシン'],['D','小妖精のチャム']]){character(s,id!,name!);s.players[id!]!.revealed=true;}s.initialFactions=['GOOD','GOOD','GOOD','GOOD'];for(const id of ['A','B','C']){s=act(s,id,{type:'PASS_SETUP'});expect(s.outcome).toBeUndefined();}s=act(s,'D',{type:'PASS_SETUP'});expect(s.outcome?.winnerIds).toEqual(['A','B','C','D']);});
it('re-setup follower placement refills to initial five and preserves once-game history',()=>{let s=ready();character(s,'B','魔導王ガイナス');s.phase='draw';s.players.B!.presence='dead';for(const __discarded of [...s.players.B!.hand])moveToDiscard(s,__discarded,{faceUp:true});s.players.B!.hand=[];takeTop(s,'a2-p01-r1c1');s=act(s,'A',{type:'CHOOSE_DRAW',draw:true});s=closeWindow(s,[1]);s=closeWindow(s);s=act(s,'B',{type:'CHOOSE_REVIVAL',revive:true});const follower=handCard(s,'B','兵士');while(s.players.B!.hand.length>5){const index=s.players.B!.hand.findIndex(id=>id!==follower);s.deck.push(s.players.B!.hand.splice(index,1)[0]!);}s.used=['retained'];s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:follower});expect(s.players.B!.followers).toEqual([{cardInstanceId:follower,revealed:false,placedById:'B',placedLifeId:s.players.B!.lifeId}]);expect(s.players.B!.hand).toHaveLength(5);expect(s.windows!.at(-1)!.kind).toBe('re-setup');expect(s.used).toEqual(['retained']);});

function opposingOtherworld(){const s=ready();character(s,'A','小妖精のチャム');character(s,'B','リーア姫');character(s,'C','魔導王ガイナス');character(s,'D','黒騎士ガーウィン');s.players.B!.presence='otherworld';s.players.C!.presence='otherworld';s.players.A!.damage=derivedStats(s.players.A!).endurance;s.players.D!.damage=derivedStats(s.players.D!).endurance;return s;}
describe('outcomes and stalemate settlement',()=>{
 it('R1 settles the last active deaths into stalemate without changing living presence or fishing draws',()=>{
  let s=opposingOtherworld();takeTop(s,'a2-p01-r1c1');const deck=[...s.deck];s=act(s,'A',{type:'PASS_ACTION'});expect(s.outcome).toBeUndefined();s=pass(s);expect(s.outcome).toBeUndefined();s=pass(s);
  expect(s.outcome).toEqual({kind:'draw',reason:'stalemate',winnerIds:[],results:{A:'draw',B:'draw',C:'draw',D:'draw'}});
  expect(s.players.B!.presence).toBe('otherworld');expect(s.players.C!.presence).toBe('otherworld');expect(s.players.A!.presence).toBe('dead');expect(s.players.D!.presence).toBe('dead');expect(s.deck).toEqual(deck);expect(allCardInstanceIds(s)).toHaveLength(220);
  for(const id of s.seatOrder){expect(viewFor(s,id).legalChoices).toEqual([]);expect(viewFor(s,id).outcome).toEqual(s.outcome);expect(transition(JSON.parse(JSON.stringify(s)),{actorId:id,command:{type:'START_TURN'}},entropy())).toEqual({ok:false,code:'GAME_COMPLETE'});}
 });
 it('R1 preserves prior individual victory while the remaining match draws',()=>{
  let s=opposingOtherworld();s.individualResults={D:'won'};s.players.D!.presence='exited';s=act(s,'A',{type:'PASS_ACTION'});s=pass(s);
  expect(s.outcome).toEqual({kind:'draw',reason:'stalemate',winnerIds:['D'],results:{A:'draw',B:'draw',C:'draw',D:'won'}});expect(s.individualResults).toEqual({D:'won'});expect(s.players.D!.presence).toBe('exited');
 });
 it('R1 ordinary otherworld winners are resolved before considering stalemate',()=>{
  let s=opposingOtherworld();character(s,'C','大神官ジル');s=act(s,'A',{type:'PASS_ACTION'});s=pass(s);s=pass(s);expect(s.outcome).toMatchObject({kind:'victory',reason:'objectives',winnerIds:['B','C']});
 });
 it('R1 active stopped actors still have a recovery turn and cannot force a stalemate',()=>{
  let s=opposingOtherworld();s.players.D!.damage=0;s.players.D!.statuses=[{id:'stop',kind:'stopped',modifiers:[0],nextCheck:1}];s=act(s,'A',{type:'PASS_ACTION'});s=pass(s);expect(s.outcome).toBeUndefined();expect(s.turnSeat).toBe(3);expect(viewFor(s,'D').legalChoices).toContain('START_TURN');s=act(s,'D',{type:'START_TURN'});expect(s.windows!.at(-1)!.kind).toBe('before-roll');
 });
 it('R2 excludes a revived same-batch victim at projection, acceptance and accepted-action resolution',()=>{
  let s=ready();character(s,'A','小妖精のチャム');character(s,'B','魔導王ガイナス');character(s,'C','リーア姫');character(s,'D','魔聖母ディア');
  const evil=handCard(s,'B','「これで勝ったと思うなよ」');const giftB=handCard(s,'B','香具羅');const good=handCard(s,'C','「姫を頼む」');const giftC=handCard(s,'C','魔導書');const fate=handCard(s,'D','命運凶変');
  for(const id of ['A','B','C'])s.players[id]!.damage=derivedStats(s.players[id]!).endurance;
  s=act(s,'A',{type:'PASS_ACTION'});s=pass(s);s=act(s,'B',{type:'PLAY_DEATH_GIFT',cardInstanceId:evil,giftCardInstanceId:giftB,targetId:'D'});
  takeTop(s,'a2-p01-r1c1');const actionId=s.windows!.at(-1)!.continuation.id;s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:actionId});s=closeWindow(s,[1]);s=closeWindow(s);s=act(s,'A',{type:'CHOOSE_REVIVAL',revive:true});s=act(s,'A',{type:'PASS_SETUP'});s=passReclaims(s);s=closeWindow(s);s=passReclaims(s);s=closeWindow(s);s=passReclaims(s);s=pass(s);
  expect(s.players.A!.presence).toBe('active');expect(s.lifecycle!.find(t=>t.kind==='death-batch')).toMatchObject({actorIds:['A','B','C'],cursor:2});expect(viewFor(s,'C').lifecycleDecision!.eligibleTargetIds).toEqual(['D']);
  const before=JSON.stringify(s);const input={actorId:'C',command:{type:'PLAY_DEATH_GIFT',cardInstanceId:good,giftCardInstanceId:giftC,targetId:'A'}} as const;expect(transition(s,input,entropy())).toEqual({ok:false,code:'INVALID_TARGET'});expect(transition(JSON.parse(before),input,entropy())).toEqual({ok:false,code:'INVALID_TARGET'});expect(JSON.stringify(s)).toBe(before);expect(s.players.C!.hand).toContain(good);expect(s.players.C!.hand).toContain(giftC);
  // Restore an already accepted historical frame (before this fix) to verify resolution also fails closed.
  s=act(s,'C',{type:'PLAY_DEATH_GIFT',cardInstanceId:good,giftCardInstanceId:giftC,targetId:'D'});const action=s.actions![s.windows!.at(-1)!.continuation.id]!;if(action.lifecycleEffect?.kind!=='gift')throw Error('NOT_GIFT');action.lifecycleEffect.targetId='A';action.targetIds=['A'];s=closeWindow(s);s=passReclaims(s);expect(s.players.A!.hand).not.toContain(giftC);expect(s.players.C!.hand).toContain(giftC);expect(discardIds(s)).toContain(good);expect(allCardInstanceIds(s)).toHaveLength(220);
 });
});
