import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeLightKingPhysical,lightKingCard as CARD,lightKingMode} from '../../../apps/worker/test/fixtures/light-king-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice:number[]=[3,4]){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s,s.windows?.at(-1)?.kind==='damage'||s.rolls?.at(-1)?.purpose==='attack-damage'||s.rolls?.at(-1)?.stage==='after-roll'?dice:[1,1]);}throw Error('LIGHT_KING_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['light-king-ordinary','light-king-owner-ordinary','light-king-owner-dedicated','light-king-precheck-fail','light-king-usage-fail','light-king-evil','light-king-low-effect','light-king-root','light-king-decline','light-king-group','light-king-group-multi','light-king-group-self','light-king-group-fail','light-king-group-fate','light-king-group-no-maai-ignore','light-king-group-counter-prohibited','light-king-return-water','light-king-return-maai','light-king-return-evade','light-king-reroll'] as const)('%s actual Light King defense or whole-group substitution preserves source and return rules',name=>{
 let s=makeLightKingPhysical(name,players);const m=lightKingMode(name),hand=[...s.players.C!.hand];if(m.suffix==='root'){for(const dedicated of [false,true]){reject(s,'C',{type:'ATTACK',cardInstanceId:CARD,targetIds:['A'],dedicated});reject(s,'C',{type:'CHANT',cardInstanceId:CARD,dedicated});}return;}const normal={type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:m.dedicated};
 if(m.suffix==='evil'||m.suffix==='low-effect'){reject(s,'C',normal);expect(s.players.C!.hand).toEqual(hand);return;}if(m.suffix==='decline'){s=settle(s);expect(s.players.C!.damage).toBe(4);expect(s.players.C!.hand).toEqual(hand);return;}
 const original=Object.values(s.groups!)[0]!;if(m.prohibited){expect(viewFor(s,'C').groupDefenseOptions).toEqual([]);reject(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId:original.id,dedicated:true});return;}
 if(m.group){const option=viewFor(s,'C').groupDefenseOptions[0]!;expect(option).toBeDefined();s=act(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId:original.id,dedicated:true});const action=source(s);expect(action.substitution!.hits).toHaveLength(m.multi?6:2);expect(action.substitution!.hits.every(h=>h.targetId!=='C')).toBe(true);}else s=act(s,'C',normal);
 expect(s.players.C!.hand).toEqual(hand.filter(id=>id!==CARD));expect(source(s).technique).toMatchObject({school:'magic',range:'none',useLevel:6,effectLevel:6,attributes:['魔','白','反'],damageFormula:'d6-product-min10',counter:true,noChecks:m.dedicated});
 if(m.suffix==='group-fate'){const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
 if(m.suffix==='precheck-fail'||m.suffix==='usage-fail'||m.suffix==='group-fail'){s=until(s,s=>s.rolls?.at(-1)?.stage==='before-roll');if(m.suffix==='usage-fail'){expect(s.rolls!.at(-1)).toMatchObject({purpose:'activation',modifier:-2});s=closeWindow(s,[2,2]);s=until(s,s=>s.rolls?.at(-1)?.purpose==='excess-level'&&s.rolls.at(-1)?.stage==='before-roll');s=closeWindow(s,[3,4]);}else{s=closeWindow(s,m.group?[2,2]:[2,3]);}s=settle(s);expect(s.players.C!.damage).toBe(m.group?0:4);if(m.group){expect(s.players.B!.damage).toBe(15);expect(s.players.D!.damage).toBe(15);}expect(s.players.A!.damage).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 if(m.suffix==='reroll'){s=until(s,s=>s.rolls?.at(-1)?.formula==='d6-product-min10'&&s.rolls.at(-1)?.stage==='after-roll',[2,3]);const id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.total).toBe(10);s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=until(s,s=>s.rolls!.find(r=>r.id===id)?.generation===1,[3,4]);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[3,4],total:12,generation:1});}
 if(m.group&&m.suffix!=='group-fate'){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'A').activeWindow?.pendingActorId==='A');const g=Object.values(s.groups!).find(g=>g.attackerId==='C')!;expect(g.targets.map(t=>t.actorId)).toEqual(['A']);expect(g.targets[0]!.hits).toHaveLength(1);expect(g.technique.followerIgnore).toBe(false);expect(g.technique.damage).toBe(12);if(m.suffix==='return-maai')s=act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(m.suffix==='return-evade')s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 s=settle(s);const cancelled=m.suffix==='group-fate';expect(s.players.A!.damage).toBe(m.group&&!cancelled&&!m.nightmare&&!m.suffix.startsWith('return')?12:0);expect(s.players.B!.damage).toBe(cancelled?15:0);expect(s.players.D!.damage).toBe(cancelled?15:0);expect(s.players.C!.damage).toBe(m.suffix==='group-self'?15:0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);if(m.suffix==='return-water'||m.nightmare)expect(s.players.A!.followers).toHaveLength(1);
});
it.each([[[1,1],10],[[2,5],10],[[3,4],12],[[6,6],36]] as const)('actual independent two dice product with minimum10 faces%s total%s',(faces,total)=>{let s=makeLightKingPhysical('light-king-group',players);const groupId=Object.values(s.groups!)[0]!.id;s=act(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId,dedicated:true});s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'A').activeWindow?.pendingActorId==='A',[...faces]);expect(Object.values(s.groups!).find(g=>g.attackerId==='C')!.technique.damage).toBe(total);expect(s.rolls!.find(r=>r.formula==='d6-product-min10')).toMatchObject({faces:[...faces],total});s=settle(s);expect(s.players.A!.damage).toBe(total);});
it.each([3,6,9] as const)('actual current spirit%s supplies ordinary Lia use and effect level including equality with incoming Bow',spirit=>{let s=makeLightKingPhysical('light-king-owner-ordinary',players,{spirit});s=act(s,'C',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});expect(source(s).technique).toMatchObject({useLevel:spirit,effectLevel:spirit});s=settle(s);expect(s.players.C!.damage).toBe(0);expect(s.players.A!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.kind==='check')).toHaveLength(0);});
it.each([[[1,2],true],[[2,2],false]] as const)('actual group substitution spirit6 minus3 boundary faces%s success=%s',(faces,success)=>{let s=makeLightKingPhysical('light-king-group',players);const groupId=Object.values(s.groups!)[0]!.id;s=act(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId,dedicated:true});s=until(s,s=>s.rolls?.at(-1)?.stage==='before-roll');s=closeWindow(s,[...faces]);expect(s.rolls!.at(-1)).toMatchObject({modifier:-3,threshold:3,success});s=settle(s);expect(s.players.B!.damage).toBe(success?0:15);expect(s.players.D!.damage).toBe(success?0:15);expect(s.players.A!.damage).toBe(success?12:0);});
it('actual follower-started target is excluded from later frozen substitution while remaining other hit is erased',()=>{let s=makeLightKingPhysical('light-king-group',players);const groupId=Object.values(s.groups!)[0]!.id;s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&viewFor(s,'B').activeWindow?.pendingActorId==='B');s=act(s,'B',{type:'START_FOLLOWERS'});s=until(s,s=>s.windows?.at(-1)?.kind==='hit'&&viewFor(s,'C').activeWindow?.pendingActorId==='C');expect(viewFor(s,'C').groupDefenseOptions[0]!.targetIds).toEqual(['D']);s=act(s,'C',{type:'PLAY_GROUP_DEFENSE',cardInstanceId:CARD,groupId,dedicated:true});expect(source(s).substitution!.hits).toEqual([{targetId:'D',hitIndex:0}]);s=settle(s);expect(s.players.B!.damage).toBe(15);expect(s.players.D!.damage).toBe(0);expect(s.players.A!.damage).toBe(12);});
