import {expect,it} from 'vitest';
import {canUseCharacterAbility,gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeMadKingPhysicalScenario} from './fixtures/mad-king-physical-scenarios.js';
const CARD='a2-p17-r3c1',players=['A','B','C','D'].map(id=>({id,name:id})),attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:false};
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function settle(s:GameState,faces=[6,6]){for(let n=0;n<350&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)&&r.stage==='before-roll'?faces:Array(30).fill(1));}expect(s.windows??[]).toEqual([]);return s;}
function next(s:GameState,target='B',phase='action'){for(let n=0;n<220;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase===phase)return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p15-r3c2','a2-p05-r2c3',CARD].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('MAD_KING_TURN');}throw Error('MAD_KING_LIMIT');}
function incoming(level=5,none=false){let s=makeMadKingPhysicalScenario('mad-king-counter',players,{level,none,spirit:6});s=next(act(s,'A',{type:'PASS_ACTION'}));return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r3c2',targetIds:['A'],dedicated:false});}
function cancel(s:GameState){const id=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);return act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}
it.each([4,5])('actual Mad King profile magic%s far and real paid near no CHANT checks and normal five',level=>{
 for(const near of [false,true]){let s=makeMadKingPhysicalScenario('mad-king-attack',players,{level,none:true,spirit:6});reject(s,'A',{type:'CHANT',cardInstanceId:CARD});if(near)s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c2',targetId:'B'}));expect(s.distances.A!.B).toBe(near?'near':'far');s=act(s,'A',attack);const f=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:5,effectLevel:5,damage:5,attributes:['魔','精','黒','反'],chant:false,noChecks:false,counter:true,defense:'counter',onHitResistance:{modifiers:[-2,-1,0],statusKind:'stopped'}});expect(f.checkSpecs).toHaveLength(5-level);s=settle(s,[2,2]);expect(s.players.B!.damage).toBe(5);expect(s.players.B!.statuses??[]).toEqual([]);expect([s.players.A!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,0,0]);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);}
});
it.each([[2,2],[2,3]] as const)('actual Mad King initial minus2 %s %s with Metal mental pass and Soldier HP1 preserves damage four',(one,two)=>{
 const s=settle(act(makeMadKingPhysicalScenario('mad-king-attack',players,{spirit:6}),'A',attack),[one,two]);expect(s.players.B!.damage).toBe(4);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.players.B!.statuses??[]).toEqual(two===2?[]:[expect.objectContaining({kind:'stopped',modifiers:[-2,-1,0],nextCheck:1,sourceActorId:'A',sourceCardInstanceId:CARD,targetId:'B'})]);expect(s.rolls!.find(r=>r.purpose==='status-resistance')).toMatchObject({rollerId:'B',modifier:-2,threshold:4,faces:[one,two],success:two===2});expect(s.players.C!.followers).toHaveLength(1);expect(s.players.C!.statuses??[]).toEqual([]);
});
it.each([0,3,4])('actual black Mad King versus Guardian8 with Prayer%s resolves above equal lower',bonus=>{
 let s=act(makeMadKingPhysicalScenario('mad-king-attack',players,{guardian:true,spirit:6}),'A',attack);if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id});while(s.windows?.at(-1)?.kind!=='normal-defense')s=pass(s,Array(30).fill(bonus));expect(s.rolls!.find(r=>r.purpose==='prayer-addition')!.faces).toEqual([bonus]);}s=settle(s);expect(s.players.B!.followers).toHaveLength(bonus===0?1:0);expect(s.players.B!.damage).toBe(bonus===4?5:0);expect(s.players.B!.statuses??[]).toHaveLength(bonus===4?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(bonus===4?1:0);
});
it.each(['teleport','maai','evade'])('actual Mad King %s defense distinguishes mental Evade prohibition',defense=>{
 let s=until(act(makeMadKingPhysicalScenario('mad-king-attack',players,{spirit:6}),'A',attack),'normal-defense');if(defense==='evade')reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});else s=defense==='maai'?act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}):act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});s=settle(s);expect(s.players.B!.damage).toBe(defense==='evade'?4:0);expect(s.players.B!.followers).toHaveLength(defense==='evade'?1:2);expect(s.players.B!.statuses??[]).toHaveLength(defense==='evade'?1:0);
});
it.each([4,5])('actual Mad King counter magic%s targets incoming attacker and retains own use checks and stop',level=>{
 let s=until(incoming(level),'normal-defense');s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});const f=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect(f).toMatchObject({targetIds:['B'],technique:{effectLevel:5,damage:5,chant:false}});expect(f.checkSpecs).toHaveLength(5-level);s=settle(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,4,0]);expect(s.players.B!.statuses![0]).toMatchObject({kind:'stopped',sourceActorId:'A',sourceCardInstanceId:CARD});expect(s.players.B!.followers).toHaveLength(1);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);
});
it.each([1,2])('actual incoming Prayer%s reaches equal or higher than counter5 with no return stop',bonus=>{
 let s=until(incoming(5,true),'effect-level');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p15-r3c2')!.id});while(s.windows?.at(-1)?.kind!=='normal-defense')s=pass(s,Array(30).fill(bonus));expect(viewFor(s,'A').currentAttack!.technique.effectLevel).toBe(4+bonus);if(bonus===2)reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});else s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});s=settle(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([bonus===2?5:0,0]);expect(s.players.A!.hand.includes(CARD)).toBe(bonus===2);expect(s.players.B!.statuses??[]).toEqual([]);
});
it.each(['attack','counter'])('actual Mad King %s failed use and Fate preserve incoming semantics without stop',mode=>{
 for(const failed of [false,true]){let s=mode==='counter'?act(until(incoming(failed?4:5),'normal-defense'),'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false}):act(makeMadKingPhysicalScenario('mad-king-attack',players,{level:failed?4:5}),'A',attack);s=failed?finish(closeWindow(until(s,'before-roll'),[6,6])):finish(cancel(s));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([mode==='counter'?5:0,0]);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.B!.statuses??[]).toEqual([]);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toEqual([]);expect(s.discard.filter(x=>x===CARD)).toHaveLength(1);}
});
it.each([1,2,3])('actual Mad King recovery succeeds on attempt%s with minus1 then repeated zero and skipped failed turns',successAt=>{
 let s=settle(act(makeMadKingPhysicalScenario('mad-king-attack',players,{spirit:6}),'A',attack)),id=s.players.B!.statuses![0]!.id;expect(s.players.B!.damage).toBe(4);for(let i=1;i<=successAt;i++){s=next(s,'B','turn-start');const hand=structuredClone(s.players.B!.hand);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({rollerId:'B',purpose:'status-recovery',modifier:i===1?-1:0});s=settle(s,i===successAt?(i===1?[2,3]:[3,3]):[6,6]);if(i<successAt){expect(s.players.B!.statuses![0]).toMatchObject({id,kind:'stopped',nextCheck:i+1});expect(s.phase).toBe('turn-start');expect(s.seatOrder[s.turnSeat]).toBe('C');expect(s.players.B!.hand).toEqual(hand);expect(canUseCharacterAbility(s.players.B!,s)).toBe(false);reject(s,'B',{type:'CHOOSE_DRAW',draw:false});}else{expect(s.players.B!.statuses).toEqual([]);expect(s.phase).toBe('draw');expect(s.seatOrder[s.turnSeat]).toBe('B');expect(canUseCharacterAbility(s.players.B!,s)).toBe(true);s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});expect(s.phase).toBe('action');}expect(s.players.B!.damage).toBe(4);}expect(s.rolls!.filter(r=>r.purpose==='status-recovery').map(r=>({modifier:r.modifier,threshold:r.threshold,success:r.success}))).toEqual(Array.from({length:successAt},(_,i)=>({modifier:i===0?-1:0,threshold:i===0?5:6,success:i===successAt-1})));
});
it('actual Mad King unprinted modes malformed and revealed friendly targets refuse without payment',()=>{
 let s=makeMadKingPhysicalScenario('mad-king-attack',players);reject(s,'A',{...attack,dedicated:true});reject(s,'A',{type:'CHANT',cardInstanceId:CARD});for(const targetIds of [[],['A'],['B','B'],['B','C'],['missing']])reject(s,'A',{...attack,targetIds});s=act(s,'D',{type:'REVEAL_CHARACTER'});reject(s,'A',{...attack,targetIds:['D']});reject(s,'B',attack);reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:CARD,targetIds:['B'],dedicated:false});
});
