import { expect, it } from 'vitest';
import { transition, viewFor, type GameState, discardIds, moveToDiscard } from '../src/index.js';
import { act, ready, finish, pass } from './combat-helpers.js';
import { character, handCard, entropy } from './fixtures.js';
function place(s: GameState, owner: string, name: string, revealed = false) { const id = handCard(s, owner, name); s.players[owner]!.hand = s.players[owner]!.hand.filter(x => x !== id); s.players[owner]!.followers.push({ cardInstanceId: id, revealed }); return id; }
function setup(name = '兵士', revealed = false) { const s = ready(); character(s, 'A', '白魔術師シェリム'); const follower = place(s, 'B', name, revealed); const gate = handCard(s, 'A', '魔招門'); return { s, follower, gate }; }
function command(gate: string, targetPosition = 0, destinationPosition = 0, replacementCardInstanceId?: string) { return { type: 'PLAY_TURN_TECHNIQUE' as const, cardInstanceId: gate, targetIds: ['B'], dedicated: false, followerTransfer: { targetPosition, destinationPosition, ...(replacementCardInstanceId ? { replacementCardInstanceId } : {}) } }; }
it('hidden incompatible castle has identical recipient candidates and acceptance to an ordinary hidden follower; paid failure does not reveal identity', () => {
    const castle = setup('ガイナス城');
    const soldier = setup();
    expect(viewFor(castle.s, 'A').magicGateTargets).toEqual(viewFor(soldier.s, 'A').magicGateTargets);
    let s = act(castle.s, 'A', command(castle.gate));
    expect(JSON.stringify(viewFor(s, 'A'))).not.toContain(castle.follower);
    s = finish(s);
    expect(discardIds(s)).toContain(castle.gate);
    expect(s.players.A!.followers).toEqual([]);
    expect(s.players.B!.followers).toContainEqual({ cardInstanceId: castle.follower, revealed: false });
    expect(JSON.stringify(viewFor(s, 'A'))).not.toContain(castle.follower);
});
it('revealed incompatible castle is rejected before Gate or replacement cost', () => { const { s, gate } = setup('ガイナス城', true); const replacement = place(s, 'A', '兵士'); place(s, 'A', '市民'); const before = JSON.stringify(s); expect(viewFor(s, 'A').magicGateTargets).toEqual([]); expect(transition(s, { actorId: 'A', command: command(gate, 0, 0, replacement) }, entropy())).toEqual({ ok: false, code: 'INVALID_TARGET' }); expect(JSON.stringify(s)).toBe(before); });
it('successful Gate replaces a chosen removable source and preserves relative order, donor rear compacts', () => { let { s, follower, gate } = setup(); const donorRear = place(s, 'B', 'ゴブリン'); const keep = place(s, 'A', '闇の聖女'); const replacement = place(s, 'A', '市民'); s = act(s, 'A', command(gate, 0, 0, replacement)); expect(discardIds(s)).toContain(replacement); expect(s.players.A!.followers.map(f => f.cardInstanceId)).toEqual([keep]); s = finish(s); expect(s.players.A!.followers.map(f => f.cardInstanceId)).toEqual([follower, keep]); expect(viewFor(s, 'C').players.B!.followers).toEqual([{ position: 0, face: 'back' }]); expect(s.players.B!.followers[0]!.cardInstanceId).toBe(donorRear); });
it('Gate cancellation preserves both accepted costs and never transfers', () => { let { s, follower, gate } = setup(); const keep = place(s, 'A', '闇の聖女'); const replacement = place(s, 'A', '市民'); const cancel = handCard(s, 'C', '命運凶変'); s = act(s, 'A', command(gate, 0, 1, replacement)); s = pass(s); s = pass(s); const action = Object.keys(s.actions!)[0]!; s = act(s, 'C', { type: 'PLAY_REACTION', cardInstanceId: cancel, mode: 'cancel', targetActionId: action }); s = finish(s); expect(discardIds(s)).toEqual(expect.arrayContaining([gate, replacement])); expect(s.players.A!.followers.map(f => f.cardInstanceId)).toEqual([keep]); expect(s.players.B!.followers[0]!.cardInstanceId).toBe(follower); });
it('Gate cannot sacrifice F31, add an unnecessary replacement, target self, or exceed destination or source bounds', () => { const { s, gate } = setup(); const saint = place(s, 'A', '闇の聖女'); place(s, 'A', '市民'); for (const c of [command(gate, 0, 0, saint), command(gate, 3, 0), command(gate, 0, 4), { ...command(gate), targetIds: ['A'] }]) {
    const before = JSON.stringify(s);
    expect(transition(s, { actorId: 'A', command: c }, entropy()).ok).toBe(false);
    expect(JSON.stringify(s)).toBe(before);
} const spare = setup(); const one = place(spare.s, 'A', '市民'); expect(transition(spare.s, { actorId: 'A', command: command(spare.gate, 0, 0, one) }, entropy()).ok).toBe(false); });
it('Gate uses public positions above two when effective capacities permit', () => { let { s, gate } = setup(); const blessing = handCard(s, 'A', '祝福'); s.players.A!.hand = s.players.A!.hand.filter(id => id !== blessing); s.players.A!.open.push(blessing); place(s, 'B', '市民'); const third = place(s, 'B', 'ゴブリン'); const first = place(s, 'A', '闇の聖女'); const second = place(s, 'A', 'オーク'); expect(viewFor(s, 'A').magicGateTargets).toEqual([{ actorId: 'B', positions: [0, 1, 2] }]); s = finish(act(s, 'A', command(gate, 2, 1))); expect(s.players.A!.followers.map(f => f.cardInstanceId)).toEqual([first, third, second]); });
it('bound moved follower is not retargeted to its former public position', () => { let { s, follower, gate } = setup(); const rear = place(s, 'B', '市民'); s = act(s, 'A', command(gate)); s.players.B!.followers = s.players.B!.followers.filter(f => f.cardInstanceId !== follower); moveToDiscard(s,follower,{faceUp:true}); s = finish(s); expect(s.players.A!.followers).toEqual([]); expect(s.players.B!.followers[0]!.cardInstanceId).toBe(rear); expect(discardIds(s)).toContain(gate); });
it('revealing the reserved hidden target during interruption does not change its binding', () => { let { s, follower, gate } = setup(); s = act(s, 'A', command(gate)); s.players.B!.followers[0]!.revealed = true; s = finish(s); expect(s.players.A!.followers).toEqual([{ cardInstanceId: follower, revealed: true }]); });
it('Gate follows ordinary excess-level checks and retains cost on check failure', () => { let { s, gate } = setup(); s.players.A!.permanent = { magic_level: -20 }; s = act(s, 'A', command(gate)); while (s.windows?.length)
    s = pass(s, [6, 6]); expect(discardIds(s)).toContain(gate); expect(s.players.A!.followers).toEqual([]); expect(s.rolls!.some(r => r.purpose === 'excess-level' && !r.success)).toBe(true); });
it('own placement options include eligible replacement hand cards at capacity and exclude F31 removals', () => { const { s } = setup(); const f = place(s, 'A', '闇の聖女'); const removable = place(s, 'A', '市民'); const good = handCard(s, 'A', 'アルケミア城'); const bad = handCard(s, 'A', 'ガイナス城'); const options = viewFor(s, 'A').followerPlacementOptions; expect(options.placeableCardInstanceIds).toContain(good); expect(options.placeableCardInstanceIds).not.toContain(bad); expect(options.removableCardInstanceIds).toEqual([removable]); expect(options.removableCardInstanceIds).not.toContain(f); });
it('forced Gate transfer can move donor F31 despite its voluntary-removal restriction',()=>{let {s,follower,gate}=setup('闇の聖女');s=finish(act(s,'A',command(gate)));expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([follower]);expect(s.players.B!.followers).toEqual([]);});
