import { expect, it } from 'vitest';
import * as engine from '../src/index.js';
import { closeWindow, act, finish, pass, ready, until, readySetup } from './combat-helpers.js';
import { character, entropy, handCard } from './fixtures.js';

type MagicCase = readonly [id:string,name:string,owner:string|null,damage:number|'magic-x2'|'d6x2',chant:boolean];
const ordinary:readonly MagicCase[]=[
  ['a2-p12-r2c2','氷矢','凍気のアイエル',4,false],['a2-p12-r2c3','凍流','凍気のアイエル',4,false],
  ['a2-p13-r1c1','氷狼乱舞陣','凍気のアイエル',7,true],['a2-p13-r3c2','呪殺','邪祭ウーノス',14,true],
  ['a2-p14-r1c1','疫病','不死王ガドューラ',12,false],['a2-p14-r1c2','白光','白魔術師シェリム',6,false],
  ['a2-p14-r1c3','白輪','白魔術師シェリム',10,false],['a2-p14-r2c1','天舞','白魔術師シェリム',10,true],
  ['a2-p14-r2c3','神罰','大神官ジル',16,true],['a2-p14-r3c3','風矢','有翼人のティア',4,false],
  ['a2-p15-r1c1','魔風','有翼人のティア',4,false],['a2-p15-r1c2','雷走','有翼人のティア',7,false],
  ['a2-p15-r1c3','裂風','有翼人のティア',7,false],['a2-p15-r2c1','撃雷','有翼人のティア',12,true],
  ['a2-p15-r3c2','炎矢','爆炎のフレイアード',5,false],['a2-p15-r3c3','炎流','爆炎のフレイアード',5,false],
  ['a2-p16-r1c1','炎舞','爆炎のフレイアード',5,false],['a2-p16-r1c2','爆炎','爆炎のフレイアード',10,false],
  ['a2-p16-r1c3','烈火','爆炎のフレイアード',15,true],['a2-p16-r2c1','妖獣','餓狼ヨーツルム',5,false],
  ['a2-p16-r2c2','餓狼','餓狼ヨーツルム','magic-x2',false],['a2-p16-r2c3','地槍','小人のランバ',6,false],
  ['a2-p16-r3c2','地流','小人のランバ',4,false],['a2-p17-r1c2','呪歌','吟遊詩人のレスター','d6x2',false],
  ['a2-p17-r2c1','衝破',null,5,false],['a2-p17-r2c2','魔衝破',null,7,false],
  ['a2-p18-r1c2','紋竜破',null,15,true],['a2-p18-r1c3','地裂',null,8,false],
];

function prepare(entry:MagicCase,dedicated=false){let state=ready();if(entry[2])character(state,'A',entry[2]);const card=handCard(state,'A',entry[1]);if(entry[4]&&!(dedicated&&(entry[1]==='氷狼乱舞陣'||entry[1]==='烈火'))){state.players.A!.hand=state.players.A!.hand.filter(id=>id!==card);state.players.A!.chants=[{cardInstanceId:card,revealed:false}];}if(entry[1]==='紋竜破')state.distances.A!.B=state.distances.B!.A='near';return{state,card};}

it.each(ordinary)('resolves and consumes Task 7c ordinary %s %s',(...entry)=>{let{state,card}=prepare(entry);state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});state=finish(state);const expected=entry[3]==='magic-x2'?10:entry[3]==='d6x2'?2:entry[3];expect(state.players.B!.damage).toBe(expected);expect(state.discard.filter(id=>id===card)).toHaveLength(1);});

const dedicated=[
  ['氷矢','凍気のアイエル',6],['凍流','凍気のアイエル',6],['氷狼乱舞陣','凍気のアイエル',14],['呪殺','邪祭ウーノス',14],
  ['疫病','不死王ガドューラ',12],['白光','白魔術師シェリム',6],['白輪','白魔術師シェリム',10],['天舞','白魔術師シェリム',15],
  ['神罰','大神官ジル',20],['神罰','邪祭ウーノス',20],['風矢','有翼人のティア',7],['魔風','有翼人のティア',7],
  ['雷走','有翼人のティア',10],['裂風','有翼人のティア',12],['撃雷','有翼人のティア',18],['炎矢','爆炎のフレイアード',8],
  ['炎流','爆炎のフレイアード',8],['炎舞','爆炎のフレイアード',8],['爆炎','爆炎のフレイアード',13],['烈火','爆炎のフレイアード',18],
  ['妖獣','餓狼ヨーツルム',7],['餓狼','餓狼ヨーツルム',10],['地槍','小人のランバ',9],['地流','小人のランバ',7],['呪歌','吟遊詩人のレスター',4],
] as const;
it.each(dedicated)('applies selected Task 7c dedicated %s for %s',(name,owner,damage)=>{const base=ordinary.find(x=>x[1]===name)!;let{state,card}=prepare([base[0],name,owner,base[3],base[4]],true);state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true});state=finish(state);expect(state.players.B!.damage).toBe(damage);});

it.each(dedicated.map(([name])=>name))('rejects wrong-owner dedicated %s before cost',name=>{const state=ready();const card=handCard(state,'A',name);const before=JSON.stringify(state);expect(engine.transition(state,{actorId:'A',command:{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true}},entropy())).toEqual({ok:false,code:'UNSUPPORTED_CARD'});expect(JSON.stringify(state)).toBe(before);});

it.each(['衝破','魔衝破','紋竜破','地裂'])('rejects unprinted dedicated %s before cost',name=>{const state=ready();const card=handCard(state,'A',name);const before=JSON.stringify(state);expect(engine.transition(state,{actorId:'A',command:{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true}},entropy())).toEqual({ok:false,code:'UNSUPPORTED_CARD'});expect(JSON.stringify(state)).toBe(before);});

it('persists an explicit target-local 凍流 follower bypass choice and defaults PASS to normal',()=>{let state=ready();character(state,'A','凍気のアイエル');const card=handCard(state,'A','凍流');const low=handCard(state,'B','ゴブリン');const other=handCard(state,'C','兵士');state.players.B!.hand=state.players.B!.hand.filter(id=>id!==low);state.players.C!.hand=state.players.C!.hand.filter(id=>id!==other);state.players.B!.followers=[{cardInstanceId:low,revealed:false}];state.players.C!.followers=[{cardInstanceId:other,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true});state=until(state,'follower-bypass-choice');expect(engine.viewFor(state,'A').legalChoices).toContain('CHOOSE_FOLLOWER_BYPASS');state=act(JSON.parse(JSON.stringify(state)),'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true});state=until(state,'follower-bypass-choice');state=pass(state);state=finish(state);expect(state.players.B!.followers).toEqual([{cardInstanceId:low,revealed:false}]);expect(state.players.B!.damage).toBe(6);expect(state.players.C!.followers).toEqual([]);expect(state.players.C!.damage).toBe(5);});

it('bypasses only 凍流 followers at or below final effect level',()=>{let state=ready();character(state,'A','凍気のアイエル');const card=handCard(state,'A','凍流');const low=handCard(state,'B','ゴブリン');const high=handCard(state,'B','水竜');const blessing=handCard(state,'B','祝福');state.players.B!.hand=state.players.B!.hand.filter(id=>id!==low&&id!==high&&id!==blessing);state.players.B!.open=[blessing];state.players.B!.followers=[{cardInstanceId:low,revealed:false},{cardInstanceId:high,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:true});state=until(state,'follower-bypass-choice');state=act(state,'A',{type:'CHOOSE_FOLLOWER_BYPASS',ignore:true});state=finish(state);expect(state.players.B!.followers).toEqual([{cardInstanceId:low,revealed:false},{cardInstanceId:high,revealed:true}]);expect(state.players.B!.damage).toBe(0);});

it('keeps maai, evade, and counter prohibitions distinct and rejects each before cost',()=>{const rejected=(attackName:string,defenseName:string)=>{let state=ready();if(attackName==='呪歌')character(state,'A','吟遊詩人のレスター');if(defenseName==='神罰')character(state,'B','大神官ジル');const attack=handCard(state,'A',attackName);const defense=handCard(state,'B',defenseName);if(attackName==='呪殺'||attackName==='紋竜破'){state.players.A!.hand=state.players.A!.hand.filter(id=>id!==attack);state.players.A!.chants=[{cardInstanceId:attack,revealed:false}];}if(defenseName==='神罰'){state.players.B!.hand=state.players.B!.hand.filter(id=>id!==defense);state.players.B!.chants=[{cardInstanceId:defense,revealed:false}];}if(attackName==='紋竜破')state.distances.A!.B=state.distances.B!.A='near';state=act(state,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:attackName==='呪歌'});state=until(state,'normal-defense');const before=JSON.stringify(state);const command=defenseName==='間合い／休息'?{type:'PLAY_MAAI',cardInstanceId:defense}:{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false};expect(engine.transition(state,{actorId:'B',command} as engine.GameInput,entropy())).toEqual({ok:false,code:'ILLEGAL_DEFENSE'});expect(JSON.stringify(state)).toBe(before);};rejected('呪殺','間合い／休息');rejected('魔風','見切る');rejected('呪歌','神罰');rejected('呪歌','ミラーシールド');rejected('紋竜破','神罰');});

it('projects effective public defense restrictions without hidden follower qualifiers',()=>{let state=ready();character(state,'A','吟遊詩人のレスター');const song=handCard(state,'A','呪歌');state=act(state,'A',{type:'ATTACK',cardInstanceId:song,targetIds:['B'],dedicated:true});state=until(state,'normal-defense');expect(engine.viewFor(state,'B').currentAttack!.defenseRestrictions).toEqual({maaiProhibited:false,evadeProhibited:true,counterProhibited:true});expect(engine.viewFor(state,'B').legalChoices).toContain('PLAY_MAAI');state=ready();const curse=handCard(state,'A','呪殺');state.players.A!.hand=state.players.A!.hand.filter(id=>id!==curse);state.players.A!.chants=[{cardInstanceId:curse,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:curse,targetIds:['B'],dedicated:false});state=until(state,'normal-defense');expect(engine.viewFor(state,'B').currentAttack!.defenseRestrictions.maaiProhibited).toBe(true);expect(engine.viewFor(state,'B').legalChoices).not.toContain('PLAY_MAAI');});

it('allows maai against dedicated 呪歌 while its independent counter prohibition remains active',()=>{let state=ready();character(state,'A','吟遊詩人のレスター');const song=handCard(state,'A','呪歌');const maai=handCard(state,'B','間合い／休息');state=act(state,'A',{type:'ATTACK',cardInstanceId:song,targetIds:['B'],dedicated:true});state=until(state,'normal-defense');state=act(state,'B',{type:'PLAY_MAAI',cardInstanceId:maai});expect(state.players.B!.hand).not.toContain(maai);expect(state.resolution).toContain(maai);expect(state.discard).not.toContain(maai);expect(state.windows!.at(-1)!.kind).toBe('reclaim');state=until(state,'defense-advance');expect(state.windows!.at(-1)!.kind).toBe('defense-advance');state=finish(state);expect(state.players.B!.damage).toBe(0);expect(state.resolution).not.toContain(maai);expect(state.discard.filter(id=>id===maai)).toHaveLength(1);});

it.each([['白光','白魔術師シェリム',true,6],['神罰','大神官ジル',false,16],['神罰','邪祭ウーノス',true,20]] as const)('resolves magic counter %s for %s',(name,owner,dedicatedMode,damage)=>{let state=ready();character(state,'B',owner);const attack=handCard(state,'A','破砕剣');const counter=handCard(state,'B',name);if(name==='神罰'){state.players.B!.hand=state.players.B!.hand.filter(id=>id!==counter);state.players.B!.chants=[{cardInstanceId:counter,revealed:false}];}state=act(state,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});state=until(state,'normal-defense');state=act(state,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:dedicatedMode});state=finish(state);expect(state.players.B!.damage).toBe(0);expect(state.players.A!.damage).toBe(damage);});

it('applies attribute bypass and exempt follower destruction while preserving front reach',()=>{let state=ready();character(state,'A','有翼人のティア');const wind=handCard(state,'A','裂風');const flying=handCard(state,'B','有翼族');const rear=handCard(state,'B','兵士');state.players.B!.hand=state.players.B!.hand.filter(id=>id!==flying&&id!==rear);state.players.B!.followers=[{cardInstanceId:flying,revealed:false},{cardInstanceId:rear,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:wind,targetIds:['B'],dedicated:false});state=finish(state);expect(state.players.B!.followers).toEqual([{cardInstanceId:flying,revealed:false}]);expect(state.players.B!.damage).toBe(6);
  state=ready();character(state,'A','有翼人のティア');const thunder=handCard(state,'A','撃雷');const building=handCard(state,'B','砦');const human=handCard(state,'B','兵士');state.players.A!.hand=state.players.A!.hand.filter(id=>id!==thunder);state.players.A!.chants=[{cardInstanceId:thunder,revealed:false}];state.players.B!.hand=state.players.B!.hand.filter(id=>id!==building&&id!==human);state.players.B!.followers=[{cardInstanceId:building,revealed:false},{cardInstanceId:human,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:thunder,targetIds:['B'],dedicated:true});state=finish(state);expect(state.players.B!.followers).toEqual([]);expect(state.players.B!.damage).toBe(16);});

it('destroys eligible 疫病 followers but applies normal HP to exempt dead followers before Gadyura immunity',()=>{let state=ready();character(state,'A','白魔術師シェリム');character(state,'B','不死王ガドューラ');const plague=handCard(state,'A','疫病');const human=handCard(state,'B','兵士');const dead=handCard(state,'B','スケルトン');state.players.B!.hand=state.players.B!.hand.filter(id=>id!==human&&id!==dead);state.players.B!.followers=[{cardInstanceId:human,revealed:false},{cardInstanceId:dead,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:plague,targetIds:['B'],dedicated:false});state=until(state,'follower-start');state=pass(state);const target=Object.values(state.groups!)[0]!.targets[0]!;expect(target.followerResults).toEqual([{cardInstanceId:human,morale:null,outcome:'level-destroyed',hpReduction:0},{cardInstanceId:dead,morale:null,outcome:'lower-destroyed',hpReduction:4}]);expect(target.hits[0]!.damage).toBe(8);state=finish(state);expect(state.players.B!.followers).toEqual([]);expect(state.players.B!.damage).toBe(0);expect(state.players.B!.revealed).toBe(false);});

it('allows 撃雷 ordinary up to four and dedicated any legal nonempty subset, rejecting ally and over-limit pre-cost',()=>{let state=ready();character(state,'A','有翼人のティア');let card=handCard(state,'A','撃雷');state.players.A!.hand=state.players.A!.hand.filter(id=>id!==card);state.players.A!.chants=[{cardInstanceId:card,revealed:false}];const before=JSON.stringify(state);expect(engine.transition(state,{actorId:'A',command:{type:'ATTACK',cardInstanceId:card,targetIds:['B','C','D','X','Y'],dedicated:false}},entropy())).toEqual({ok:false,code:'INVALID_TARGET'});expect(JSON.stringify(state)).toBe(before);state.players.C!.revealed=true;state.players.C!.faction=state.players.A!.faction;expect(engine.transition(state,{actorId:'A',command:{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true}},entropy())).toEqual({ok:false,code:'INVALID_TARGET'});state.players.C!.revealed=false;state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','D'],dedicated:true});state=finish(state);expect([state.players.B!.damage,state.players.C!.damage,state.players.D!.damage]).toEqual([18,0,18]);});

it('resolves ordinary 撃雷 against four selected targets without requiring all players',()=>{let state=engine.createGame(['A','B','C','D','E'].map(id=>({id,name:id})),entropy(),{startingSeat:0});state=readySetup(state);state=act(state,'A',{type:'START_TURN'});state=act(state,'A',{type:'CHOOSE_DRAW',draw:false});character(state,'A','有翼人のティア');const card=handCard(state,'A','撃雷');state.players.A!.hand=state.players.A!.hand.filter(id=>id!==card);state.players.A!.chants=[{cardInstanceId:card,revealed:false}];state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C','D','E'],dedicated:false});state=finish(state);expect(['B','C','D','E'].map(id=>state.players[id]!.damage)).toEqual([12,12,12,12]);});

it('retains the white-use restriction for direct magic before card cost',()=>{const state=ready();character(state,'A','不死王ガドューラ');const card=handCard(state,'A','白光');const before=JSON.stringify(state);expect(engine.transition(state,{actorId:'A',command:{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}},entropy())).toEqual({ok:false,code:'UNSUPPORTED_CARD'});expect(JSON.stringify(state)).toBe(before);});

it.each([[false,'d6x2',2],[true,'d6x4',4]] as const)('stores one exact shared 呪歌 damage roll for dedicated=%s',(dedicatedMode,formula,total)=>{let state=ready();character(state,'A','吟遊詩人のレスター');const card=handCard(state,'A','呪歌');const targetIds=dedicatedMode?['B','C']:['B'];state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds,dedicated:dedicatedMode});const action=Object.values(state.actions!)[0]!;state=until(state,'damage');while(state.windows!.at(-1)!.cursor<state.windows!.at(-1)!.participants.length-1)state=pass(state);state=pass(state,[1]);state=closeWindow(state);const record=state.randomRolls!.at(-1)!;expect(record).toEqual({id:`roll-${action.id}-damage`,eventId:action.eventId,actionId:action.id,kind:'damage',formula,faces:[1],modifier:dedicatedMode?4:2,total});state=finish(state);expect(targetIds.map(id=>state.players[id]!.damage)).toEqual(targetIds.map(()=>total));expect(state.randomRolls!.at(-1)).toEqual(record);});

it('retains the ordinary 呪歌 roll identity through a legal reflection and cleanup',()=>{let state=ready();character(state,'A','吟遊詩人のレスター');const song=handCard(state,'A','呪歌');const ice=handCard(state,'B','氷鏡');state=act(state,'A',{type:'ATTACK',cardInstanceId:song,targetIds:['B'],dedicated:false});state=until(state,'damage');while(state.windows!.at(-1)!.cursor<state.windows!.at(-1)!.participants.length-1)state=pass(state);state=pass(state,[3]);state=closeWindow(state);const original=Object.values(state.groups!)[0]!;const roll=state.randomRolls![0]!;expect(original.damageRollId).toBe(roll.id);expect(original.targets[0]!.hits[0]!.damageRollId).toBe(roll.id);state=until(state,'normal-defense');state=act(state,'B',{type:'PLAY_DEFENSE',cardInstanceId:ice,dedicated:false});while(Object.keys(state.groups!).length<2)state=pass(state);const reflected=Object.values(state.groups!).find(group=>group.id!==original.id)!;expect(state.randomRolls).toEqual([roll]);expect(reflected.damageRollId).toBe(roll.id);expect(reflected.targets[0]!.hits[0]!.damageRollId).toBe(roll.id);expect(JSON.parse(JSON.stringify(state))).toEqual(state);state=finish(state);expect(state.players.A!.damage).toBe(6);expect(state.groups).toEqual({});expect(state.randomRolls).toEqual([roll]);expect(JSON.parse(JSON.stringify(state))).toEqual(state);});

it('freezes 餓狼 from effective caster magic level at the damage boundary',()=>{let state=ready();character(state,'A','餓狼ヨーツルム');const card=handCard(state,'A','餓狼');state=act(state,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B','C'],dedicated:true});state=until(state,'damage');while(state.windows!.at(-1)!.cursor<state.windows!.at(-1)!.participants.length-1)state=pass(state);state=pass(state);expect(Object.values(state.groups!)[0]!.targets.map(t=>t.hits[0]!.damage)).toEqual([10,10]);character(state,'A','大神官ジル');state=finish(state);expect([state.players.B!.damage,state.players.C!.damage]).toEqual([10,10]);});
