import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,until,finish,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeMekaiPhysicalScenario,type MekaiPhysicalScenario} from '../../../apps/worker/test/fixtures/mekai-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p13-r2c3',rows=['mekai-ordinary','mekai-dedicated'] as const;
function command(scenario:MekaiPhysicalScenario){return {type:'ATTACK' as const,cardInstanceId:card,targetIds:['B'],dedicated:scenario==='mekai-dedicated'};}
function nextA(s:GameState){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('MEKAI_PHASE');}throw Error('MEKAI_TURNS');}
function chant(s:GameState){s=act(s,'A',{type:'CHANT',cardInstanceId:card});return nextA(s);}
function reject(s:GameState,id:string,c:unknown,code?:string){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id)),r=transition(s,{actorId:id,command:c} as never,entropy());expect(r.ok).toBe(false);if(code)expect(r).toMatchObject({code});expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(rows)('%s actual ritual and chant retain printed profile and use checks while destroying both follower columns',scenario=>{
 for(const level of [9,10]){let s=makeMekaiPhysicalScenario(scenario,players,{level});expect(s.players.A!.characterId).toBe('c2-p07-r1c2');expect(s.events.some(e=>e.type==='CHARACTER_TRANSFORMED'&&e.actorId==='A')).toBe(true);expect(gameStats(s,'A').magic_level).toBe(level);const guards=[...s.players.A!.followers,...s.players.B!.followers].map(f=>f.cardInstanceId);reject(s,'A',command(scenario),'CHANT_REQUIRED');s=act(chant(s),'A',command(scenario));const action=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(action.technique).toMatchObject({school:'magic',range:'far',useLevel:10,effectLevel:10,damage:20,attributes:['魔','詠'],chant:true,noChecks:false,limitedDefenses:['teleport','counter'],destroyAllFollowers:true,selfCost:{damage:scenario==='mekai-dedicated'?0:10,destroyFollowers:true}});expect(action.checkSpecs).toHaveLength(10-level);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toHaveLength(2);s=until(s,'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense!.flatMap(d=>d.hits.map(h=>h.outcome))).toEqual(['level-destroyed','level-destroyed']);s=finish(s);expect(s.seatOrder.map(id=>s.players[id]!.damage)).toEqual([scenario==='mekai-dedicated'?0:10,20,0,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual([]);for(const id of [...guards,card])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
});
it.each(rows)('%s actual failed use check retains only self cost and preserves target followers',scenario=>{
 let s=act(chant(makeMekaiPhysicalScenario(scenario,players,{level:9})),'A',command(scenario));const own=s.players.A!.followers.map(f=>f.cardInstanceId),target=structuredClone(s.players.B!.followers);s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',rollerId:'A'});s=finish(closeWindow(s,[6,6]));expect(s.rolls!.at(-1)!.success).toBe(false);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([scenario==='mekai-dedicated'?0:10,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual(target);for(const id of [...own,card])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it.each(rows)('%s actual Fate cancellation retains registered self cost exactly once',scenario=>{
 let s=act(chant(makeMekaiPhysicalScenario(scenario,players)),'A',command(scenario));const target=structuredClone(s.players.B!.followers),id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=pass(pass(s));s=finish(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([scenario==='mekai-dedicated'?0:10,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual(target);expect(s.discard.filter(x=>x===card)).toHaveLength(1);expect(s.resolution).toEqual([]);
});
it.each(rows)('%s actual successful Teleport preserves target column without removing the self cost',scenario=>{
 let s=until(act(chant(makeMekaiPhysicalScenario(scenario,players)),'A',command(scenario)),'normal-defense');const target=structuredClone(s.players.B!.followers);s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}));expect(s.rolls!.find(r=>r.purpose==='teleport')!.success).toBe(true);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([scenario==='mekai-dedicated'?0:10,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual(target);
});
it.each(rows)('%s actual Lancaster counter cancels parent twenty but self cost remains alongside returned seven',scenario=>{
 let s=until(act(chant(makeMekaiPhysicalScenario(scenario,players,{defense:'counter'})),'A',command(scenario)),'normal-defense');const target=structuredClone(s.players.B!.followers);s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p10-r3c3',dedicated:true}));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([scenario==='mekai-dedicated'?7:17,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual(target);expect(s.discard.filter(x=>x===card)).toHaveLength(1);
});
it.each(rows)('%s actual Lamba magic half is an allowed ability defense while followers still die',scenario=>{
 let s=until(act(chant(makeMekaiPhysicalScenario(scenario,players,{defense:'ability'})),'A',command(scenario)),'normal-defense');const abilityId='c2-p03-r1c1-ab02',option=viewFor(s,'B').abilityOptions.find(o=>o.abilityId===abilityId)!;expect(option).toBeDefined();s=finish(act(s,'B',{type:'USE_ABILITY',abilityId,targetEventId:option.targetEventId}));expect([s.players.A!.damage,s.players.B!.damage]).toEqual([scenario==='mekai-dedicated'?0:10,10]);expect(s.players.B!.followers).toEqual([]);expect(s.players.A!.followers).toEqual([]);
});
it.each(rows)('%s actual restricted defense and invalid cast refuse without payment or self damage',scenario=>{
 let s=chant(makeMekaiPhysicalScenario(scenario,players,{defense:'forbidden'}));reject(s,'A',{...command(scenario),targetIds:['A']});reject(s,'A',{...command(scenario),targetIds:['B','C']});expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toHaveLength(2);s=until(act(s,'A',command(scenario)),'normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'},'ILLEGAL_DEFENSE');reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false},'ILLEGAL_DEFENSE');expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toMatchObject({limitedDefenses:['teleport','counter'],maaiProhibited:true,evadeProhibited:true});const foreign=chant(makeMekaiPhysicalScenario(scenario,players,{foreign:true}));reject(foreign,'A',{...command(scenario),dedicated:true});
});
it('ordinary actual lethal twenty and self ten enter one simultaneous batch before any winner',()=>{
 let s=act(chant(makeMekaiPhysicalScenario('mekai-ordinary',players,{fatal:true,foreign:true})),'A',command('mekai-ordinary'));s=until(s,'death-gift');expect(s.outcome).toBeUndefined();expect([s.players.A!.presence,s.players.B!.presence]).toEqual(['pending-death','pending-death']);const batch=s.lifecycle!.find(t=>t.kind==='death-batch')!;expect(batch).toMatchObject({actorIds:['A','B'],intents:[expect.objectContaining({targetId:'B',damage:20}),expect.objectContaining({targetId:'A',damage:10,cause:'self-damage'})]});expect(s.players.A!.followers).toEqual([]);expect(s.players.B!.followers).toEqual([]);s=finish(s);expect([s.players.A!.presence,s.players.B!.presence]).toEqual(['dead','dead']);expect(s.resolution).toEqual([]);expect(s.outcome).toBeUndefined();
});
