import {expect,it,describe} from 'vitest';
import {transition,viewFor,type GameState,gameStats,allCardInstanceIds,type GameCommand} from '../src/index.js';
import {act,finish,pass,until,ready,passReclaims,closeWindow} from './combat-helpers.js';
import {entropy,handCard} from './fixtures.js';
import {makeR6RollScenario} from './fixtures/r6-roll-scenarios.js';
import {getAction} from '@madou/catalog';
import {makeR6DefenseScenario} from './fixtures/r6-defense-scenarios.js';
import {assignCharacter,takeCard,trimHand} from './fixtures/scenario-tools.js';
import {makeCanonicalDefense} from './fixtures/canonical-defense-scenarios.js';
import {resolveFollowerSnapshot,freezeFollowerSnapshot} from '../src/combat/followers.js';
import {makeR6MaaiScenario} from './fixtures/r6-maai-scenarios.js';
import {makeR6BoundaryScenario} from './fixtures/r6-boundary-scenarios.js';
import {makeKiSlashPhysical,kiSlashCard} from './fixtures/ki-slash-physical-scenarios.js';
import {makeScenarioS18} from './fixtures/scenario-s18.js';
import {makeR6WanderingScenario,s26Entropy} from './fixtures/r6-wandering-scenario.js';
import {makeR6OtherworldScenario} from './fixtures/r6-otherworld-scenario.js';

describe('S01 to S05 rolls and replacements',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  function until(s:GameState,done:(s:GameState)=>boolean,dice=[4,4]){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('S01_05_WINDOW');}
  it('S01 S02 S05 D first is rejected at C priority then C force-fail resets the parent and D rerolls successful-valued faces without clearing failure',()=>{let s=makeR6RollScenario(players,true);const parent=structuredClone(s.windows!.at(-1)!),id=s.rolls!.at(-1)!.id;expect(parent).toMatchObject({cursor:2,passed:['A','B']});expect(s.rolls!.at(-1)).toMatchObject({faces:[2,3],success:true,threshold:9});const god={type:'PLAY_REACTION' as const,cardInstanceId:'a2-p02-r1c3',mode:'reroll' as const,targetRollId:id},before=JSON.stringify(s);expect(transition(s,{actorId:'D',command:god},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});s=until(s,s=>s.windows?.at(-1)?.id===parent.id);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[2,3],forcedFailure:true,success:false});s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',god);s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[4,4],total:8,threshold:9,forcedFailure:true,success:false,generation:1});expect(s.rolls!.at(-1)!.attempts.map(a=>a.faces)).toEqual([[2,3],[4,4]]);s=finish(JSON.parse(JSON.stringify(s)));expect(s.players.B!.statuses).toHaveLength(1);expect(s.players.B!.damage).toBe(5);});
  it('S03 B accepted God retains its paid replacement and used event after C Fate cancels it without a reroll or action refund',()=>{let s=makeR6RollScenario(players),parent=s.windows!.at(-1)!.id,id=s.rolls!.at(-1)!.id,hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});expect(s.players.B!.hand).toHaveLength(hand.length);expect(s.players.B!.hand).not.toContain('a2-p02-r1c3');const replacement=s.players.B!.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);const child=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;expect(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]).toBe('C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});s=until(s,s=>s.windows?.at(-1)?.id===parent,[]);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[2,3],generation:0});expect(s.rolls!.at(-1)!.attempts).toHaveLength(1);expect(s.players.B!.hand).toContain(replacement);expect(s.used!.some(key=>key.endsWith(':B:a2-p02-r1c3'))).toBe(true);expect(s.discard).toEqual(expect.arrayContaining(['a2-p02-r1c3','a2-p02-r2c3']));expect(s.turnSeat).toBe(0);s=finish(s);expect(s.phase).toBe('withdrawal');expect(s.players.B!.hand).toContain(replacement);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);});
  it('S04 actual whole 2d6 reroll replaces 2,3 with 4,4 and keeps one stable roll identity and double result after JSON save',()=>{let s=makeR6RollScenario(players),id=s.rolls!.at(-1)!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);const roll=structuredClone(s.rolls!.at(-1)!);expect(roll).toMatchObject({id,faces:[4,4],total:8,success:true,generation:1});expect(roll.attempts.map(a=>a.faces)).toEqual([[2,3],[4,4]]);s=finish(JSON.parse(JSON.stringify(s)));expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[4,4],attempts:roll.attempts});expect(viewFor(s,'B').recentRolls.find(r=>r.rollId===id)).toMatchObject({faces:[4,4]});expect(s.players.B!.statuses??[]).toEqual([]);});

  it('S02 actual C reroll canceled by D resets the A B passed parent without changing its roll',()=>{
   let s=makeR6RollScenario(players,true,true);const parent=structuredClone(s.windows!.at(-1)!),roll=structuredClone(s.rolls!.at(-1)!);
   expect(parent).toMatchObject({cursor:2,passed:['A','B']});
   s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:roll.id});
   const child=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;
   s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});
   s=until(s,s=>s.windows?.at(-1)?.id===parent.id,[]);
   expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);
   expect(s.rolls!.at(-1)).toEqual(roll);expect(s.discard).toEqual(expect.arrayContaining(['a2-p02-r1c3','a2-p02-r2c3']));
   s=pass(s,[]);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:1,passed:['A']});
  });
});

describe('S06 to S10 defenses',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  const card=(s:GameState,name:string)=>s.players.B!.hand.find(id=>getAction(id)!.name===name)!;
  const main=(s:GameState)=>Object.values(s.actions!).find(a=>a.kind==='attack')!;
  function rejected(s:GameState,actorId:string,command:Parameters<typeof transition>[1]['command']){const before=JSON.stringify(s);expect(transition(s,{actorId,command},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
  it('S06 actual level6 is frozen at normal defense and late Shin Spirit spends no hand ability attempt or roll',()=>{let s=makeR6DefenseScenario(players,'s06');const a=main(s),abilityId='c2-p01-r2c1-ab03',hand=[...s.players.A!.hand],used=[...s.used!],rolls=structuredClone(s.rolls);expect(a.technique.effectLevel).toBe(6);expect(a.modifiers!.effectFrozen).toBe(true);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===abilityId)).toBe(false);rejected(s,'A',{type:'USE_ABILITY',abilityId,targetEventId:a.eventId});expect(s.players.A!.hand).toEqual(hand);expect(s.used).toEqual(used);expect(s.rolls).toEqual(rolls);s=finish(s);expect(s.players.B!.damage).toBe(5);});
  it('S08 real failed teleport cannot retry but a different actual counter is accepted before followers and returns damage',()=>{let s=makeR6DefenseScenario(players,'s08');const teleport=s.discard.find(id=>getAction(id)!.name==='転移')!,counter=card(s,'閃光槍');expect(teleport).toBeDefined();expect(s.rolls!.some(r=>r.faces.join(',')==='6,6'&&r.success===false)).toBe(true);rejected(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false});s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});s=finish(s);expect(s.players.A!.damage).toBe(5);expect(s.players.B!.damage).toBe(0);expect(s.discard).toEqual(expect.arrayContaining([teleport,counter]));expect(s.groups).toEqual({});});
  it('S09 actual Asfelt level6 sword meets checked Garwin level6 counter and cancels only B hit with C intact',()=>{let s=makeR6DefenseScenario(players,'s09');expect(main(s).technique.effectLevel).toBe(6);const counter=card(s,'妖撃破山剣');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false,declarationAbilityIds:['c2-p05-r2c1-ab03']});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique.defense).toBe('counter');expect(defense.checks.length).toBeGreaterThan(0);s=until(s,'damage');expect(s.actions![defense.id]!.technique.effectLevel).toBe(6);s=until(s,'normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});const group=Object.values(s.groups!)[0]!;expect(group.targets[0]!.hits[0]!.defended).toBe(true);expect(group.technique.effectLevel).toBe(6);expect(group.targets[1]!.hits[0]).toMatchObject({damage:12,defended:false});expect(Object.values(s.groups!).some(g=>g.attackerId==='B')).toBe(false);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,12]);});
  it('S10 actual far level5 attack and near counter plus real prayer2 freeze at level7 and block without returned damage',()=>{let s=makeR6DefenseScenario(players,'s10');expect(s.distances.A!.B).toBe('far');expect(main(s).technique.effectLevel).toBe(5);const counter=card(s,'妖撃破山剣'),prayer=card(s,'必勝の祈り');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});s=until(s,'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const id=Object.values(s.actions!).find(a=>a.kind==='defense')!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:id});for(let n=0;n<300;n++){if(s.windows!.at(-1)?.kind==='damage'&&s.windows!.at(-1)!.continuation.id===id)break;s=pass(s,[2]);}expect(s.actions![id]!.technique).toMatchObject({effectLevel:7,range:'near'});expect(s.actions![id]!.modifiers!.effectFrozen).toBe(true);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,0]);expect(s.distances.A!.B).toBe('far');expect(s.groups).toEqual({});expect(s.discard).toEqual(expect.arrayContaining([counter,prayer]));});

  it('Actual Asfelt level6 two-target sword meets checked level6 parry and cancels only B hit with C intact',()=>{let s=makeR6DefenseScenario(players,'s09-parry');expect(main(s).technique.effectLevel).toBe(6);const counter=card(s,'受け流し');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique.effectLevel).toBe(6);expect(defense.checks.length).toBeGreaterThan(0);s=until(s,'normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});const group=Object.values(s.groups!)[0]!;expect(group.targets[0]!.hits[0]!.defended).toBe(true);expect(group.technique.effectLevel).toBe(6);expect(group.targets[1]!.hits[0]).toMatchObject({damage:12,defended:false});expect(Object.values(s.groups!).some(g=>g.attackerId==='B')).toBe(false);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,12]);});
});

describe('S07 prayer reservation',()=>{
  function rejected(s:GameState,command:Parameters<typeof transition>[1]['command']){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:'B',command},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
  it('S07 actual Lia prayer reserves once rejects same-action reuse and returns for a later independent attack',()=>{
   let s=ready();assignCharacter(s,'A','侍大将のシン');assignCharacter(s,'B','リーア姫');assignCharacter(s,'C','黒騎士ガーウィン');
   for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20,warrior_level:20};
   const first=takeCard(s,'A','a2-p24-r1c2'),second=takeCard(s,'B','a2-p24-r1c3'),prayer=takeCard(s,'B','a2-p05-r2c3');trimHand(s,'A',first);trimHand(s,'B',second,prayer);
   s=until(act(s,'A',{type:'ATTACK',cardInstanceId:first,targetIds:['C'],dedicated:false}),'effect-level');
   while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);
   const action=Object.values(s.actions!).find(a=>a.cardInstanceId===first)!;
   const command={type:'PLAY_REACTION' as const,cardInstanceId:prayer,mode:'effect-plus' as const,targetActionId:action.id,dedicated:true};
   s=act(s,'B',command);
   for(let n=0;!s.reclaimReservations.includes(prayer)&&n<100;n++)s=pass(s);
   expect(s.reclaimReservations).toContain(prayer);expect(s.players.B!.hand).not.toContain(prayer);rejected(s,command);
   s=finish(s);expect(s.players.B!.hand.filter(id=>id===prayer)).toHaveLength(1);expect(s.reclaimReservations).not.toContain(prayer);rejected(s,command);
   s=act(s,'A',{type:'PASS_WITHDRAWAL'});s=finish(act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(gameStats(s,'A').handLimit)}));
   s=act(s,'B',{type:'START_TURN'});s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});
   s=until(act(s,'B',{type:'ATTACK',cardInstanceId:second,targetIds:['C'],dedicated:false}),'effect-level');
   while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);
   const later=Object.values(s.actions!).find(a=>a.cardInstanceId===second)!;expect(later.eventId).not.toBe(action.eventId);
   s=act(s,'B',{...command,targetActionId:later.id});
   for(let n=0;!s.reclaimReservations.includes(prayer)&&n<100;n++)s=pass(s);
   expect(s.reclaimReservations).toContain(prayer);s=finish(s);expect(s.players.B!.hand.filter(id=>id===prayer)).toHaveLength(1);expect(s.discard).not.toContain(prayer);
  });
});

describe('S09 and S10 canonical defenses',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  it('S09 Ramba dedicated Death Axe6 versus Shin checked parry6 cancels B and keeps C damage10',()=>{
   let s=makeCanonicalDefense(players,'S09');const incoming=Object.values(s.actions!).find(a=>a.kind==='attack')!;expect(incoming.technique).toMatchObject({effectLevel:6,damage:10,noChecks:true});
   s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p12-r1c3',dedicated:false});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique.effectLevel).toBe(6);expect(defense.checks).toHaveLength(1);
   s=until(s,'normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});const group=Object.values(s.groups!)[0]!;expect(group.targets[0]!.hits[0]!.defended).toBe(true);expect(group.targets[1]!.hits[0]).toMatchObject({defended:false,damage:10});
   s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,10]);
  });
  it('S10 Arnes ordinary Black Bow5 versus Lancelot dedicated sword6 plus real prayer1 blocks at far without return',()=>{
   let s=makeCanonicalDefense(players,'S10');expect(s.distances.A!.B).toBe('far');expect(Object.values(s.actions!).find(a=>a.kind==='attack')!.technique.effectLevel).toBe(5);
   s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c2',dedicated:true});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique).toMatchObject({effectLevel:6,counterNoChecks:true,range:'near'});
   expect(defense.checks).toHaveLength(0);s=until(s,'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);
   s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:defense.id});
   for(let n=0;!(s.windows?.at(-1)?.kind==='damage'&&s.windows.at(-1)!.continuation.id===defense.id)&&n<300;n++)s=pass(s,[1]);
   expect(s.actions![defense.id]!.technique.effectLevel).toBe(7);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,0]);expect(s.distances.A!.B).toBe('far');
  });
});

describe('S11 to S13 maai and multi-hit',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  const card=(s:GameState,owner:string,name:string)=>s.players[owner]!.hand.find(id=>getAction(id)!.name===name)!;
  it('S11 actual chanted one-hit two-target sword shares one advance against both maai and preserves pair distances through final damage',()=>{let s=makeR6MaaiScenario(players),distances=structuredClone(s.distances);const bm=card(s,'B','間合い／休息'),cm=card(s,'C','間合い／休息'),advance=card(s,'A','踏み込み／蹴る');expect(Object.values(s.groups!)[0]!.hitIndices).toEqual([0]);s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:bm}));s=passReclaims(act(s,'C',{type:'PLAY_MAAI',cardInstanceId:cm}));expect(s.windows!.at(-1)!.kind).toBe('defense-advance');s=passReclaims(act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:advance}));expect(s.windows!.at(-1)).toMatchObject({kind:'normal-defense',continuation:{targetId:'B'}});expect(s.distances).toEqual(distances);for(const id of [bm,cm,advance])expect(s.discard.filter(x=>x===id)).toHaveLength(1);s=finish(s);expect(s.distances).toEqual(distances);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([7,7]);expect(s.phase).toBe('withdrawal');});
  it('S12 actual chanted three-hit sword one maai evades only the first hit and retains exactly two live hits',()=>{let s=makeR6MaaiScenario(players,true);const maai=card(s,'B','間合い／休息');expect(Object.values(s.groups!)[0]!.hitIndices).toEqual([0,1,2]);s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:maai}));s=act(s,'A',{type:'PASS'});const target=Object.values(s.groups!)[0]!.targets[0]!;expect(target.hits.map(h=>h.defended)).toEqual([true,false,false]);expect(s.windows!.at(-1)).toMatchObject({kind:'normal-defense',continuation:{targetId:'B'}});expect(Object.values(s.groups!)[0]!.hitCursor).toBe(1);s=finish(s);expect(s.players.B!.damage).toBe(14);expect(s.discard.filter(id=>id===maai)).toHaveLength(1);expect(s.phase).toBe('withdrawal');});
  it('S13 abstract Lv5 damage6 three-hit resolver with front Lv3 HP2 yields four each and destroys one physical follower once',()=>{
   let s=ready();for(const p of Object.values(s.players))p.permanent={endurance:100};const attack=handCard(s,'A','踏み込み／弓'),soldier=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==soldier);s.players.B!.followers=[{cardInstanceId:soldier,revealed:false}];s=until(act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false}),'follower-start');
   // Explicit abstract arithmetic boundary: these numbers are not claimed as printed Soldier/bow effects.
   const g=Object.values(s.groups!)[0]!,t=g.targets[0]!;g.technique={...g.technique,effectLevel:5,damage:6};g.hitIndices=[0,1,2];t.hits=[0,1,2].map(index=>({index,damage:6,defended:false,hit:false,lineage:[]}));delete t.followerDefense;freezeFollowerSnapshot(s,g,t);const source=t.followerDefense![0]!;source.descriptor={...source.descriptor,level:3,hp:2,moraleRequired:false};source.levels=[3,3,3];const restored=JSON.parse(JSON.stringify(s)) as GameState,rg=restored.groups![g.id]!,rt=rg.targets[0]!;
   expect(resolveFollowerSnapshot(s,g,t,()=>{throw Error('S13_UNEXPECTED_MORALE');})).toBe(true);expect(resolveFollowerSnapshot(restored,rg,rt,()=>{throw Error('S13_UNEXPECTED_MORALE');})).toBe(true);expect(restored).toEqual(s);expect(t.hits.map(h=>h.damage)).toEqual([4,4,4]);expect(source.hits.map(h=>h.hpReduction)).toEqual([2,2,2]);expect(t.followerDestroyed).toEqual([soldier]);expect(s.resolution.filter(id=>id===soldier)).toHaveLength(1);const settled=JSON.stringify(s);expect(resolveFollowerSnapshot(s,g,t,()=>1)).toBe(true);expect(JSON.stringify(s)).toBe(settled);expect(new Set(allCardInstanceIds(s)).size).toBe(220);s=finish(s);expect(s.players.B!.damage).toBe(12);expect(s.players.B!.followers).toEqual([]);expect(s.discard.filter(id=>id===soldier)).toHaveLength(1);
  });
  it('S12 second and third actual Hundred Slash hits open separate normal defenses after first-hit maai',()=>{
   let s=makeR6MaaiScenario(players,true);const maai=card(s,'B','間合い／休息');
   s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:maai}));s=act(s,'A',{type:'PASS'});
   const second=s.windows!.at(-1)!;expect(second.kind).toBe('normal-defense');expect(Object.values(s.groups!)[0]!.hitCursor).toBe(1);
   s=act(s,'B',{type:'PASS'});s=until(s,'normal-defense');
   const third=s.windows!.at(-1)!;expect(third.id).not.toBe(second.id);expect(third.continuation).toMatchObject({targetId:'B'});expect(Object.values(s.groups!)[0]!.hitCursor).toBe(2);
   s=finish(s);expect(s.players.B!.damage).toBe(14);expect(s.discard.filter(id=>id===maai)).toHaveLength(1);
  });
});

describe('S14 to S17 boundaries',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  const card=(s:GameState,owner:string,name:string)=>s.players[owner]!.hand.find(id=>getAction(id)!.name===name)!;
  function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s);}throw Error('S14_17_TEST_WINDOW');}
  it('S14 actual initial follower entry closes owned normal defense but preserves C actual God intervention on its morale roll',()=>{let s=makeR6BoundaryScenario(players);const defense=card(s,'B','見切る'),before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false}},entropy())).toEqual({ok:false,code:'DEFENSE_WINDOW_CLOSED'});expect(JSON.stringify(s)).toBe(before);s=until(s,s=>s.windows?.at(-1)?.kind==='after-roll'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');const roll=s.rolls!.at(-1)!;expect(roll.purpose).toBe('follower-morale');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:card(s,'C','神性介入'),mode:'reroll',targetRollId:roll.id});s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);expect(s.rolls!.at(-1)!.id).toBe(roll.id);s=finish(s);expect(s.players.B!.hand).toContain(defense);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(1);});
  it('S17 real X Y reflection lineage refuses spent X and permits unused teleport without fabricating a physical recovery',()=>{let s=makeR6BoundaryScenario(players,true);const g=Object.values(s.groups!)[2]!,mirror=s.resolution.find(id=>getAction(id)!.name==='ミラーシールド')!,ice=s.resolution.find(id=>getAction(id)!.name==='氷鏡')!,teleport=card(s,'B','転移');expect(g.targets[0]!.hits[0]!.lineage).toEqual([mirror,ice]);const before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);
   // Separate structural challenge isolates the lineage guard with X available; it is not a reclaim producer.
   const challenge=structuredClone(s);challenge.resolution=challenge.resolution.filter(id=>id!==mirror);challenge.players.B!.hand.push(mirror);const saved=JSON.stringify(challenge);expect(transition(challenge,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy())).toEqual({ok:false,code:'ALREADY_USED'});expect(JSON.stringify(challenge)).toBe(saved);
   s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false});s=finish(s);expect(s.groups).toEqual({});expect(s.windows).toEqual([]);expect(s.players.A!.statuses??[]).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);for(const id of [mirror,ice,teleport])expect(s.discard.filter(x=>x===id)).toHaveLength(1);});
});

describe('S15 allied reveal',()=>{
  it.each(['before','after'] as const)('S15 real allied characters reveal %s follower start changes only the permitted target suppression',timing=>{
   let s=ready();assignCharacter(s,'A','侍大将のシン');assignCharacter(s,'B','大神官ジル');for(const p of Object.values(s.players))p.permanent={endurance:100,spirit:20,warrior_level:20};
   const card=takeCard(s,'A','a2-p24-r1c2');trimHand(s,'A',card);s=act(s,'A',{type:'REVEAL_CHARACTER'});expect(s.players.B!.revealed).toBe(false);expect(s.players.A!.faction).toBe(s.players.B!.faction);
   s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'normal-defense');
   if(timing==='after')s=until(act(s,'B',{type:'START_FOLLOWERS'}),'follower-start');
   s=act(s,'B',{type:'REVEAL_CHARACTER'});s=finish(s);expect(s.players.B!.damage).toBe(timing==='before'?0:4);expect(s.players.B!.revealed).toBe(true);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
  });
});

describe('S16 zero-spirit hit',()=>{
  it('S16 actual zero-spirit Ki Slash numeric zero hit reveals the hidden target without adding damage',()=>{
   const players=['A','B','C','D'].map(id=>({id,name:id}));let s=makeKiSlashPhysical('ki-slash-ordinary',players,{spirit:0,warrior:6});expect(s.players.B!.revealed).toBe(false);
   s=until(act(s,'A',{type:'ATTACK',cardInstanceId:kiSlashCard,targetIds:['B'],dedicated:false}),'attack-abilities');const g=Object.values(s.groups!)[0]!;expect(g.technique.damage).toBe(0);expect(g.targets[0]!.hits[0]!.damage).toBe(0);
   s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.revealed).toBe(true);expect(s.discard.filter(id=>id===kiSlashCard)).toHaveLength(1);
  });
});

describe('S18 chanted three-hit sword',()=>{
  it('S18 actual chanted two-target three-hit sword uses one Lester resistance and cancels only B three hits',()=>{let s=makeScenarioS18(['A','B','C','D'].map(id=>({id,name:id})));const faction=s.players.A!.faction;const groupId=s.windows!.at(-1)!.continuation.id;expect(s.groups![groupId]!.targets.map(t=>({actor:t.actorId,hits:t.hits.length}))).toEqual([{actor:'B',hits:3},{actor:'C',hits:3}]);const countRoll=s.rolls!.find(r=>r.formula==='d6'&&r.faces[0]===3)!;expect(countRoll).toBeDefined();const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c1-ab01')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({rollerId:'A',purpose:'ability-check',faces:[]});s=closeWindow(JSON.parse(JSON.stringify(s)),[2,3]);s=closeWindow(s);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(s.rolls!.at(-1)).toMatchObject({success:false,faces:[2,3]});expect(s.players.A!.statuses??[]).toEqual([]);expect(s.players.A!.faction).toBe(faction);for(let n=0;n<200;n++){const w=s.windows!.at(-1)!;if(w.kind==='normal-defense'&&w.continuation.kind==='group'&&w.continuation.targetId==='C')break;s=pass(s);}s=JSON.parse(JSON.stringify(s));expect(s.groups![groupId]!.targets.find(t=>t.actorId==='B')!.hits.map(h=>h.defended)).toEqual([true,true,true]);expect(s.groups![groupId]!.targets.find(t=>t.actorId==='C')!.hits.map(h=>h.defended)).toEqual([false,false,false]);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,21]);expect(s.players.A!.statuses??[]).toEqual([]);expect(s.players.A!.faction).toBe(faction);expect(s.rolls!.find(r=>r.id===countRoll.id)!.faces).toEqual([3]);expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);});
});

describe('S26 protected death and resurrection',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  function act(s:GameState,actorId:string,command:GameCommand){const input={actorId,command},r=transition(s,input,s26Entropy());expect(r).toEqual(transition(JSON.parse(JSON.stringify(s)),input,s26Entropy()));if(!r.ok)throw Error(r.code);const ids=allCardInstanceIds(r.state);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);return r.state;}
  function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;const w=s.windows!.at(-1)!;s=act(s,w.participants[w.cursor]!,{type:'PASS'});}throw Error('S26_WINDOW');}
  function nextOwn(s:GameState){for(let n=0;n<40;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'&&actor==='A')return act(act(s,'A',{type:'START_TURN'}),'A',{type:'CHOOSE_DRAW',draw:false});if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=until(act(s,actor,{type:'END_TURN',discardIds:[]}),s=>!s.windows?.length);else throw Error('S26_TURN');}throw Error('S26_TURN_LIMIT');}
  it('S26 actual protected death returns wandering cards to deck and resurrection replaces initial hands and followers before the suspended turn',()=>{let s=makeR6WanderingScenario(players);const b=s.players.B!,c=s.players.C!,oldHand=[...b.hand],oldFollower=b.followers[0]!.cardInstanceId,deadHand=[...c.hand],life=b.lifeId;expect(getAction(oldFollower)!.name).toBe('兵士');expect(b.protection!.characterIds).toContain(c.characterId);
   s=until(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p07-r3c3',targetIds:['C'],dedicated:false}),s=>!s.windows?.length);expect(s.players.C!.presence).toBe('dead');expect(s.players.B).toMatchObject({presence:'wandering',hand:[],followers:[],damage:2});expect(s.outcome).toBeUndefined();for(const id of [...oldHand,oldFollower]){expect(s.deck).toContain(id);expect(s.discard).not.toContain(id);}for(const id of deadHand){expect(s.discard).toContain(id);expect(s.deck).not.toContain(id);}const saved=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'START_TURN'}},s26Entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);expect(viewFor(s,'B').legalChoices).not.toContain('ATTACK');
   s=nextOwn(JSON.parse(saved));s=until(act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['C'],dedicated:true}),s=>s.windows?.at(-1)?.kind==='re-setup');expect(s.players.C).toMatchObject({presence:'active',damage:0,followers:[]});expect(s.players.C!.hand).toHaveLength(5);expect(s.players.C!.hand.every(id=>!deadHand.includes(id))).toBe(true);expect(s.players.B!.presence).toBe('wandering');expect(s.outcome).toBeUndefined();s=act(JSON.parse(JSON.stringify(s)),'C',{type:'PASS_SETUP'});expect(s.windows!.at(-1)).toMatchObject({kind:'re-setup',participants:['B']});expect(s.players.B).toMatchObject({presence:'active',damage:2,followers:[]});expect(s.players.B!.lifeId).toBe(life);expect(s.players.B!.hand).toHaveLength(5);expect(s.players.B!.hand.every(id=>!oldHand.includes(id)&&id!==oldFollower)).toBe(true);const newFollower=s.players.B!.hand.find(id=>getAction(id)!.name==='小人族')!;expect(newFollower).toBeDefined();expect(newFollower).not.toBe(oldFollower);s=act(JSON.parse(JSON.stringify(s)),'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:newFollower});expect(s.players.B!.followers).toEqual([{cardInstanceId:newFollower,revealed:false,placedById:'B',placedLifeId:life??'initial-life:B'}]);expect(s.players.B!.hand).toHaveLength(5);s=until(act(s,'B',{type:'PASS_SETUP'}),s=>!s.windows?.length);expect(s.phase).toBe('hand-adjustment');expect(s.turnSeat).toBe(0);expect(s.outcome).toBeUndefined();expect(s.events.filter(e=>['PLAYER_DIED','PLAYER_WANDERING','PLAYER_REVIVED','PLAYER_RETURNED'].includes(e.type)).map(e=>[e.type,e.actorId])).toEqual([['PLAYER_DIED','C'],['PLAYER_WANDERING','B'],['PLAYER_REVIVED','C'],['PLAYER_RETURNED','B']]);expect(s.rolls?.filter(r=>r.purpose==='revival')??[]).toEqual([]);expect(s.discard.filter(id=>id==='a2-p13-r3c1')).toHaveLength(1);});
});

describe('S30 rift and returning possessions',()=>{
  const players=['A','B','C','D'].map(id=>({id,name:id}));
  function nextC(s:GameState){for(let n=0;n<60;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'&&actor==='C')return s;if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.filter(id=>!['a2-p04-r3c3','a2-p02-r1c2'].includes(id)).slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else throw Error('S30_TURN');}throw Error('S30_TURN_LIMIT');}
  function reject(s:GameState,actorId:string,command:GameCommand){const saved=JSON.stringify(s),views=players.map(p=>viewFor(s,p.id));expect(transition(s,{actorId,command},entropy())).toEqual({ok:false,code:'INVALID_TARGET'});expect(JSON.stringify(s)).toBe(saved);expect(players.map(p=>viewFor(s,p.id))).toEqual(views);}
  it('S30 actual rift excludes away possessions from both physical wishes and Revelation until actual acquired Dawn returns the same owner',()=>{let s=makeR6OtherworldScenario(players);const b=structuredClone(s.players.B!),possessions={hand:b.hand,followers:b.followers,chants:b.chants,attachments:b.attachments,open:b.open};expect(b.presence).toBe('otherworld');expect(b.followers).toHaveLength(1);expect(b.chants).toHaveLength(1);expect(b.attachments).toHaveLength(1);expect(b.damage).toBe(12);expect(s.rolls!.find(r=>r.purpose==='status-resistance')).toMatchObject({faces:[6,6],success:false});expect(s.discard.filter(id=>id==='a2-p14-r2c2')).toHaveLength(1);
   for(const wish of ['a2-p04-r3c2','a2-p04-r3c3'] as const){const options=viewFor(s,'D').anytimeCardOptions.filter(o=>o.cardInstanceId==='a2-p02-r1c2');expect(options.length).toBeGreaterThan(0);expect(options.some(o=>o.targetId==='B')).toBe(false);reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:'a2-p02-r1c2',targetId:'B',targetEventId:options[0]!.targetEventId});s=until(act(s,'C',{type:'PLAY_TURN_CARD',cardInstanceId:wish,mode:'wish'}),'wish');const d=viewFor(s,'C').wish!;expect(d.handOwners.some(o=>o.ownerId==='B')).toBe(false);expect(d.publicSources.some(o=>o.ownerId==='B')).toBe(false);for(const source of [{kind:'hand' as const,ownerId:'B'},...b.attachments.map(cardInstanceId=>({kind:'public' as const,cardInstanceId})),...b.chants.map(c=>({kind:'public' as const,cardInstanceId:c.cardInstanceId}))])reject(s,'C',{type:'CHOOSE_WISH',decisionId:d.decisionId,source});expect(s.players.B).toMatchObject(possessions);expect(s.inspections??[]).toEqual([]);s=finish(act(JSON.parse(JSON.stringify(s)),'C',{type:'CHOOSE_WISH',decisionId:d.decisionId,source:wish==='a2-p04-r3c2'?{kind:'hand',ownerId:'A'}:{kind:'deck',cardName:getAction('a2-p01-r1c2')!.name}}));if(wish==='a2-p04-r3c2'){expect(s.players.B!.presence).toBe('otherworld');s=nextC(s);}}
   expect(s.players.B).toMatchObject({...possessions,presence:'active',damage:12});expect(s.players.B!.lifeId).toBe(b.lifeId);expect(s.players.C!.open).toContain('a2-p01-r1c2');expect(s.events.filter(e=>e.type==='PLAYER_RETURNED'&&e.actorId==='B')).toHaveLength(1);expect(s.events.filter(e=>e.type==='PLAYER_REVIVED'&&e.actorId==='B')).toEqual([]);expect(s.events.filter(e=>e.type==='WISH_ACQUIRED'&&e.actorId==='C'&&e.audience==='public')).toHaveLength(2);expect(s.players.D!.hand).toContain('a2-p02-r1c2');expect(s.phase).toBe('hand-adjustment');expect(s.outcome).toBeUndefined();});
});
