import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makePalaceGuardPhysicalScenario,palaceGuardPhysicalMode,type PalaceGuardPhysicalScenario} from '../../../apps/worker/test/fixtures/palace-guard-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['guard-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PALACE_GUARD_TURN');}throw Error('PALACE_GUARD_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p22-r1c3',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);let s=makePalaceGuardPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);let s=ready(makePalaceGuardPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makePalaceGuardPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makePalaceGuardPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);let s=until(incoming(ready(makePalaceGuardPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makePalaceGuardPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const GUARD='a2-p22-r1c3',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Palace Guard spirit6 morale %s applies one group result and HP4 to each reached Dwarf7 hit',mode=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-higher',players,{spirit:6}),GUARD);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-2,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,2]:[2,3]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:4,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(mode==='pass'?4:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?6:18);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);
});
it('actual surviving Palace Guard rechecks each later group while unreached hidden rear never checks',()=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-setup',players),GUARD);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makePalaceGuardPhysicalScenario('guard-setup',players,{spirit:0}),GUARD,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',GUARD]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([false,true])('actual explicit Lia physical package=%s waives morale at spirit0 but leaves printed6 HP4 unchanged',selected=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-waive',players),GUARD);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD,GUARD]});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[GUARD]:[]});s=until(s,'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');expect(f.levels).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(selected?6:18);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);
});
it.each(['guard-ignore','guard-ignore-decline','guard-sky','guard-sky-decline'] as const)('%s actual ordinary Palace Guard morale controls whole-column generic or sky-attribute ignore only for its owner',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);let s=makePalaceGuardPhysicalScenario(scenario,players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.front});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=next(ready(s,GUARD,false));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p21-r1c1',targetIds:['A','C'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:m.special?[GUARD]:[]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!;expect(t.followerIgnoreCancelled??false).toBe(!m.fail);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===GUARD)!.dedicated).toBe(m.special);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.sky?[m.fail?12:5,12]:[m.fail?5:0,5]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.sky&&!m.fail?2:1);if(m.ignore){expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.fail?[m.front]:[m.front,GUARD]);if(!m.fail)expect(s.players.A!.followers[1]!.revealed).toBe(true);}else{expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.fail?[m.front]:[]);}
});
it('actual foreign owner cannot select Palace Guard package and actual explicit destruction remains effective against Lia package',()=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-setup',players,{owner:'竜皇子アスフェルト'}),GUARD);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD]});
 s=next(ready(makePalaceGuardPhysicalScenario('guard-destroy',players),GUARD));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p13-r1c2',targetIds:['A'],dedicated:true}),'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD]});s=until(s,'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits[0]!.outcome).toBe('level-destroyed');s=finish(s);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect(s.players.A!.damage).toBe(0);
});
it('actual Lester human invalidation disables physical Palace Guard cancellation so Wight Army bypasses both it and front Metal',()=>{
 let s=makePalaceGuardPhysicalScenario('guard-invalid',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=next(ready(s,GUARD,false));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=until(act(s,'B',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:'a2-p21-r1c1',targetIds:['A']}),'attack-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p03-r2c1-ab02')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,abilityEffectIds:['human-invalidation']});s=until(s,'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[GUARD]});s=until(s,'hit');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerIgnoreCancelled??false).toBe(false);expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===GUARD)!.ineffective).toBe(true);s=finish(s);expect(s.players.A!.damage).toBe(5);expect(s.players.A!.followers.every(f=>!f.revealed)).toBe(true);
});
function guardAttack(s:GameState,scenario:PalaceGuardPhysicalScenario){const m=palaceGuardPhysicalMode(scenario);return m.army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:GUARD,targetIds:['B']}:m.grant?grant(s):{type:'ATTACK' as const,cardInstanceId:GUARD,targetIds:['B'],dedicated:true};}

function approach(s:GameState,target='B',card='a2-p24-r1c3'){return finish(act(s,'A',{type:'APPROACH',cardInstanceId:card,targetId:target}));}
it.each(['guard-ded-hand','guard-ded-field','guard-grant-hand','guard-grant-field','guard-army'] as const)('%s actual near white sword6 damage8 permission uses warrior checks except explicit Lia dedication',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);for(const warrior of [5,6]){let s=ready(makePalaceGuardPhysicalScenario(scenario,players,{warrior:m.dedicated?0:warrior,magic:warrior===5?20:0}),GUARD,m.initial);if(!m.grant)reject(s,'A',guardAttack(s,scenario));else expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===GUARD)).toBe(false);s=approach(s);const command=guardAttack(s,scenario);for(const targetIds of [[],['A'],['B','B'],['B','C']])reject(s,'A',command.type==='USE_FOLLOWER_ATTACK'?{...command,sources:command.sources.map(source=>({...source,targetIds}))}:{...command,targetIds});s=act(s,'A',command);const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GUARD)!;expect(a.checks).toHaveLength(m.dedicated?0:6-warrior);expect(a.technique).toMatchObject({range:'near',school:'warrior',useLevel:6,effectLevel:6,damage:8,attributes:['近','戦','剣','白'],noChecks:m.dedicated,hitCount:1,target:m.dedicated?'all':'one'});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([8,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it.each(['guard-ded-hand','guard-ded-field'] as const)('%s actual Lia chooses any nonempty subset after three real approaches with no checks at warrior0',scenario=>{
 const m=palaceGuardPhysicalMode(scenario);for(const targets of [['B'],['C'],['D'],['B','C'],['B','D'],['C','D'],['B','C','D']]){let s=ready(makePalaceGuardPhysicalScenario(scenario,players,{warrior:0,multi:true}),GUARD,m.initial);s=approach(s);s=approach(s,'C','a2-p24-r2c2');s=approach(s,'D','a2-p24-r2c3');s=act(s,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:targets,dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===GUARD)!;expect(a.checks).toEqual([]);expect(a.technique).toMatchObject({noChecks:true,target:'all',range:'near'});expect(a.technique.mandatoryAll??false).toBe(false);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual(['B','C','D'].map(id=>targets.includes(id)?8:0));expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale'||r.purpose==='excess-level')).toEqual([]);}
});
it('actual Palace Guard ordinary direct or foreign dedicated attack and CHANT reject and Army cannot spend placed source',()=>{
 for(const placed of [false,true]){let s=ready(makePalaceGuardPhysicalScenario('guard-army',players),GUARD,placed);s=approach(s);for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:GUARD});if(placed)reject(s,'A',guardAttack(s,'guard-army'));}
 let s=ready(makePalaceGuardPhysicalScenario('guard-ded-hand',players),GUARD,false);s=approach(s);reject(s,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:['B'],dedicated:false});
});
it.each(['maai','mirror','ded-mirror'] as const)('actual Palace Guard sword6 accepts %s and preserves local defense on selected targets',mode=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-ded-hand',players,{multi:true,...(mode==='ded-mirror'?{defender:'聖騎士ランスロット'}:{})}),GUARD,false);s=approach(s);s=approach(s,'C','a2-p24-r2c2');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:GUARD,targetIds:['B','C'],dedicated:true}),'normal-defense');if(mode==='maai')s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});else if(mode==='mirror')reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});else s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:true});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,mode==='mirror'?8:0,8]);expect(s.discard.filter(id=>id===GUARD)).toHaveLength(1);
});
it.each(['hand','field','army-parent','army-child','army-morale','army-use','grant'] as const)('actual Palace Guard %s cancellation or failure consumes physical costs once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'guard-army':mode==='grant'?'guard-grant-field':mode==='field'?'guard-ded-field':'guard-ded-hand';let s=ready(makePalaceGuardPhysicalScenario(scenario,players,{warrior:5}),GUARD,mode==='field'||mode==='grant');s=approach(s);s=act(s,'A',guardAttack(s,scenario));if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='army-use'){s=until(s,'before-roll');if(mode==='army-use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:GUARD)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'||mode==='army-use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of army?[GUARD,ARMY]:[GUARD])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});

it('actual Lia Army still rolls ordinary minus2 morale and cannot use its defensive waiver while attacking',()=>{
 let s=ready(makePalaceGuardPhysicalScenario('guard-army',players,{owner:'リーア姫',spirit:0}),GUARD,false);s=approach(s);s=until(act(s,'A',guardAttack(s,'guard-army')),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:-2});s=finish(s);expect(s.players.B!.damage).toBe(0);for(const id of [GUARD,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it('actual front Palace Guard protects following sky Griffin from Tia attribute ignore with ordinary morale',()=>{
 let s=makePalaceGuardPhysicalScenario('guard-sky',players);s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:GUARD});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p20-r3c1'});s=next(ready(s,GUARD,false));s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r1c3',targetIds:['A','C'],dedicated:true}));expect([s.players.A!.damage,s.players.C!.damage]).toEqual([5,12]);expect(s.players.A!.followers).toEqual([]);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
});
