import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {character,entropy} from './fixtures.js';
import {makePeacePhysicalScenario,type PeacePhysicalScenario} from './fixtures/peace-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p02-r1c1';
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1,2]){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('PEACE_WINDOW');}
function at(s:GameState,kind:string){return until(s,s=>s.windows?.at(-1)?.kind===kind);}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function option(s:GameState,target='B'){return viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===target);}
function play(s:GameState,target='B'){if(s.windows?.length)s=until(s,s=>!!option(s,target));return act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:option(s,target)!.targetEventId,targetId:target});}
function next(s:GameState,target:string,phase='action'){for(let n=0;n<300;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(!w&&id===target&&s.phase===phase)return s;if(w)s=pass(s);else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PEACE_TURN_PHASE');}throw Error('PEACE_TURN');}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each([-3,0,2])('actual Peace substitutes base12 then retains signed permanent addition %s until target main action completes',addition=>{let s=makePeacePhysicalScenario('peace-next',players,{spiritAddition:addition});const base=gameStats(s,'B'),other=gameStats(s,'D'),hand=s.players.D!.hand.length;s=settle(play(s));expect(gameStats(s,'B')).toEqual({...base,spirit:12+addition});expect(gameStats(s,'D')).toEqual(other);expect(s.players.B!.revealed).toBe(false);expect(s.players.D!.hand).toHaveLength(hand);for(const id of s.seatOrder)expect(viewFor(s,id).peaceExpiries).toEqual([{targetId:'B',timing:'next-own-action'}]);s=next(s,'B');expect(gameStats(s,'B').spirit).toBe(12+addition);s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r2c2',targetIds:['A'],dedicated:false});expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'B',timing:'current-action'}]);expect(gameStats(s,'B').spirit).toBe(12+addition);s=settle(s);expect(gameStats(s,'B')).toEqual(base);expect(s.players.A!.damage).toBe(4);expect(viewFor(s,'C').peaceExpiries).toEqual([]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it.each(['peace-pass','peace-chant','peace-book'] as const)('%s actual target pass chant or secretbook has the specified main-action boundary',name=>{let s=makePeacePhysicalScenario(name,players),base=gameStats(s,'B').spirit;s=next(settle(play(s)),'B');if(name==='peace-book'){s=settle(act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r1c1'}));expect(s.phase).toBe('action');expect(gameStats(s,'B').spirit).toBe(14);s=act(s,'B',{type:'PASS_ACTION'});}else s=name==='peace-pass'?act(s,'B',{type:'PASS_ACTION'}):act(s,'B',{type:'CHANT',cardInstanceId:'a2-p13-r1c1'});expect(gameStats(s,'B').spirit).toBe(base);expect(viewFor(s,'D').peaceExpiries).toEqual([]);});
it('actual Blood acquired after Peace adds above12 and remains after replacement expires',()=>{let s=makePeacePhysicalScenario('peace-blood',players),base=gameStats(s,'B').spirit;s=next(settle(play(s)),'B','draw');s=settle(act(s,'B',{type:'CHOOSE_DRAW',draw:true}));expect(s.players.B!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'B').spirit).toBe(15);s=act(s,'B',{type:'PASS_ACTION'});expect(gameStats(s,'B').spirit).toBe(base+1);expect(s.players.B!.open).toContain('a2-p01-r1c3');});
it('actual active own ability gets current-action expiry and loses Peace when that ability completes',()=>{let s=makePeacePhysicalScenario('peace-own-ability',players),base=gameStats(s,'A').spirit;const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p04-r2c2-ab04')!;s=act(s,'A',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,costCardInstanceId:'a2-p07-r1c1'});s=play(s,'A');const peace=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>!s.actions?.[peace.id]);expect(gameStats(s,'A').spirit).toBe(14);expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'A',timing:'current-action'}]);s=settle(s);expect(gameStats(s,'A').spirit).toBe(base);expect(viewFor(s,'C').peaceExpiries).toEqual([]);});
it.each(['peace-current','peace-counter'] as const)('%s actual running attack and generated counter retain replacement until their whole chain ends',name=>{let s=makePeacePhysicalScenario(name,players),base=gameStats(s,'A').spirit;s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false});s=at(play(s,'A'),'normal-defense');expect(gameStats(s,'A').spirit).toBe(14);expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'A',timing:'current-action'}]);if(name==='peace-counter'){s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p10-r3c3',dedicated:false});s=until(s,s=>Object.keys(s.groups??{}).length===2);expect(gameStats(s,'A').spirit).toBe(14);expect(viewFor(s,'D').peaceExpiries).toEqual([{targetId:'A',timing:'current-action'}]);}s=settle(s);expect(s.players.A!.damage).toBe(name==='peace-counter'?5:0);expect(s.players.B!.damage).toBe(name==='peace-counter'?0:4);expect(gameStats(s,'A').spirit).toBe(base);expect(viewFor(s,'C').peaceExpiries).toEqual([]);});
it.each(['peace-before-roll','peace-frozen'] as const)('%s actual excess-level check freezes the appropriate pre or post Peace spirit',name=>{let s=makePeacePhysicalScenario(name,players),base=gameStats(s,'A').spirit;s=at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p12-r2c2',targetIds:['B'],dedicated:false}),name==='peace-before-roll'?'before-roll':'after-roll');const id=s.rolls!.at(-1)!.id,threshold=s.rolls!.at(-1)!.threshold;s=play(s,'A');s=until(s,s=>!!s.actions&&Object.values(s.actions).every(a=>a.cardInstanceId!==card));expect(gameStats(s,'A').spirit).toBe(14);if(name==='peace-frozen')expect(s.rolls!.find(r=>r.id===id)!.threshold).toBe(threshold);s=settle(s);expect(s.rolls!.find(r=>r.id===id)!.threshold).toBe(name==='peace-before-roll'?14:base);expect(gameStats(s,'A').spirit).toBe(base);});
it('actual defensive mental ability binds Peace to the enclosing attack rather than a later own turn',()=>{let s=makePeacePhysicalScenario('peace-defense-ability',players),base=gameStats(s,'B').spirit;s=at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false}),'normal-defense');const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab01')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});s=play(s);s=until(s,s=>Object.values(s.actions??{}).every(a=>a.cardInstanceId!==card));expect(gameStats(s,'B').spirit).toBe(14);expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'B',timing:'current-action'}]);s=settle(s);expect(gameStats(s,'B').spirit).toBe(base);expect(viewFor(s,'C').peaceExpiries).toEqual([]);});
it('actual passive attack recipient keeps next-own-action Peace after incoming damage and loses it on its own pass',()=>{let s=makePeacePhysicalScenario('peace-receiving',players),base=gameStats(s,'B').spirit;s=at(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['B'],dedicated:false}),'attack-abilities');s=settle(play(s));expect(s.players.B!.damage).toBe(4);expect(gameStats(s,'B').spirit).toBe(14);expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'B',timing:'next-own-action'}]);s=next(s,'B');s=act(s,'B',{type:'PASS_ACTION'});expect(gameStats(s,'B').spirit).toBe(base);});
it('actual Dawn and Wish recover the same Peace for repeated base12 without adding twelve twice',()=>{let s=makePeacePhysicalScenario('peace-repeated',players),base=gameStats(s,'B').spirit;s=settle(play(s));expect(gameStats(s,'B').spirit).toBe(14);s=settle(act(s,'D',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p03-r1c1'}));expect(s.players.D!.open).toContain('a2-p01-r1c2');if(!s.players.D!.hand.includes(card)){s=at(act(s,'D',{type:'PLAY_TURN_CARD',cardInstanceId:'a2-p04-r3c2',mode:'wish'}),'wish');s=settle(act(s,'D',{type:'CHOOSE_WISH',decisionId:viewFor(s,'D').wish!.decisionId,source:{kind:'deck',cardName:'この世界に愛と平和を'}}));}s=settle(play(s));expect(gameStats(s,'B').spirit).toBe(14);expect(s.players.B!.spiritReplacements!.every(r=>r.base===12)).toBe(true);expect(s.discard.filter(id=>id===card)).toHaveLength(1);s=next(s,'B');s=act(s,'B',{type:'PASS_ACTION'});expect(gameStats(s,'B').spirit).toBe(base);expect(viewFor(s,'C').peaceExpiries).toEqual([]);});
it('actual Fate canceled Peace preserves immediate refill and original action phase without replacement or expiry',()=>{let s=makePeacePhysicalScenario('peace-canceled',players),base=gameStats(s,'B'),hand=s.players.D!.hand.length;s=play(s);const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');s=settle(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}));expect(gameStats(s,'B')).toEqual(base);expect(s.players.D!.hand).toHaveLength(hand);expect(s.phase).toBe('action');expect(viewFor(s,'C').peaceExpiries).toEqual([]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual EVIL owner cannot use Peace and leaving its card unplayed changes nothing',()=>{let s=makePeacePhysicalScenario('peace-evil',players);expect(option(s)).toBeUndefined();reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:`idle-${s.turnNumber??0}-${s.revision}-${s.phase}`,targetId:'B'});const before=gameStats(s,'B');s=next(s,'B');expect(s.players.D!.hand).toContain(card);expect(gameStats(s,'B')).toEqual(before);});
it('actual self foreign stale and malformed Peace choices reject unchanged full state and views',()=>{const s=makePeacePhysicalScenario('peace-next',players),event=option(s)!.targetEventId;for(const [actorId,targetId,targetEventId] of [['D','D',event],['C','B',event],['D','B','stale'],['D','missing',event]] as const)reject(s,actorId,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId,targetId});reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:event,targetId:'B',groupId:'foreign'});expect(s.players.D!.hand).toContain(card);});
it('actual optional Peace decline preserves its card and unmodified target through the target action',()=>{let s=makePeacePhysicalScenario('peace-pass',players),base=gameStats(s,'B');expect(option(s)).toBeDefined();s=next(s,'B');s=act(s,'B',{type:'PASS_ACTION'});expect(gameStats(s,'B')).toEqual(base);expect(s.players.D!.hand).toContain(card);expect(viewFor(s,'C').peaceExpiries).toEqual([]);});

it('actual Peace expires after the next own virtual blade attack',()=>{
 let s=makePeacePhysicalScenario('peace-next',players);
 character(s,'B','凍気のアイエル');s.players.B!.revealed=true;
 s.distances.A!.B=s.distances.B!.A='near';
 const base=gameStats(s,'B').spirit;
 s=next(settle(play(s)),'B');
 expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'B',timing:'next-own-action'}]);
 s=act(s,'B',{type:'DECLARE_VIRTUAL_BLADE',abilityId:'c2-p04-r1c1-ab02',targetIds:['A']});
 expect(viewFor(s,'C').peaceExpiries).toEqual([{targetId:'B',timing:'current-action'}]);
 expect(gameStats(s,'B').spirit).toBe(14);
 s=settle(s);
 expect(s.phase).toBe('withdrawal');
 expect(gameStats(s,'B').spirit).toBe(base);
 expect(viewFor(s,'C').peaceExpiries).toEqual([]);
 expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
