import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makePetrifyPhysicalScenario,PETRIFY,REVIVE} from './fixtures/petrify-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),attack={type:'ATTACK' as const,cardInstanceId:PETRIFY,targetIds:['B'],dedicated:false};
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function next(s:GameState){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>![PETRIFY,REVIVE].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PETRIFY_TURN');}throw Error('PETRIFY_TURN_LIMIT');}
function prepare(s:GameState,card=PETRIFY){s=act(s,'A',{type:'CHANT',cardInstanceId:card});expect(s.players.A!.chants).toContainEqual({cardInstanceId:card,revealed:false});return next(s);}
function finish(s:GameState,success=false){for(let n=0;n<500&&s.windows?.length;n++){const w=s.windows!.at(-1)!,r=s.rolls?.at(-1);expect(viewFor(s,'A').lifetimeDecision).toBeNull();if(w.kind==='re-setup')s=act(s,w.participants[w.cursor]!,{type:'PASS_SETUP'});else s=pass(s,Array(30).fill(r?.purpose==='status-resistance'&&r.stage==='before-roll'&&!success?6:1));}expect(s.windows??[]).toEqual([]);return s;}
it.each([6,7])('actual Petrify magic%s requires real chant and printed use7 checks before distinct damage and spirit resistance',level=>{
 let s=makePetrifyPhysicalScenario('petrify-physical',players,{level});reject(s,'A',attack);s=act(prepare(s),'A',attack);const f=Object.values(s.actions!).find(a=>a.cardInstanceId===PETRIFY)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:7,effectLevel:7,damage:5,attributes:['魔','地','詠'],chant:true,noChecks:false,followerIgnore:false,target:'one',lifetimeHit:{kind:'petrification',modifier:0}});expect(f.checkSpecs).toHaveLength(7-level);s=finish(s,true);expect(s.players.B).toMatchObject({presence:'active',damage:5});expect(s.rolls!.filter(r=>r.purpose==='status-resistance')).toMatchObject([{rollerId:'B',modifier:0,threshold:6,success:true}]);expect(s.discard.filter(id=>id===PETRIFY)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);
});
it.each([5,100])('actual Petrify target endurance%s stores one damage and stone death batch and a durable cause',endurance=>{
 let s=act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{endurance})),'A',attack);const eventId=Object.values(s.actions!).find(a=>a.cardInstanceId===PETRIFY)!.eventId;s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-resistance',rollerId:'B',modifier:0});expect(s.players.B).toMatchObject({presence:'active',damage:0});s=closeWindow(s,[6,6]);expect(s.players.B).toMatchObject({presence:'active',damage:0});s=closeWindow(s);expect(s.lifecycle?.find(t=>t.kind==='death-batch')).toMatchObject({intents:[{targetId:'B',damage:5,instantDeath:true,cause:'petrification'}]});s=finish(s);expect(s.players.B!.presence).toBe('dead');expect(s.players.B!.hand).toEqual([]);expect(s.events.filter(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toHaveLength(1);expect(viewFor(s,'C').logs.find(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toMatchObject({death:{cause:'petrification',eventId,sourceActorId:'A',sourceCardInstanceId:PETRIFY}});expect(s.outcome).toBeUndefined();
});
it.each([false,true])('actual Metal absorbs all numeric damage but Petrify resistance success=%s still controls stone death',success=>{
 const s=finish(act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{follower:'metal'})),'A',attack),success);expect(s.players.B!.followers).toEqual([]);expect(s.rolls!.filter(r=>r.purpose==='status-resistance')).toMatchObject([{rollerId:'B',threshold:6,success}]);expect(s.players.B!.presence).toBe(success?'active':'dead');if(success)expect(s.players.B!.damage).toBe(0);else expect(s.events.find(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toMatchObject({death:{cause:'petrification'}});
});
it.each(['earth','guardian'] as const)('actual %s follower stops body hit and therefore suppresses Petrify resistance',follower=>{const s=finish(act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{follower})),'A',attack));expect(s.players.B).toMatchObject({presence:'active',damage:0});expect(s.players.B!.followers).toHaveLength(follower==='earth'?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);});
it('actual Prayer raises Petrify above Guardian and exposes target to stone check',()=>{let s=until(act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{follower:'guardian'})),'A',attack),'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===PETRIFY)!.id});s=finish(s);expect(s.players.B!.followers).toEqual([]);expect(s.players.B!.presence).toBe('dead');expect(s.rolls!.filter(r=>r.purpose==='status-resistance')).toHaveLength(1);});
it.each(['teleport','evade','cancel','use-failure'])('actual Petrify %s prevents body and mandatory hit check',route=>{
 let s=act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{level:route==='use-failure'?6:7})),'A',attack);if(route==='use-failure')s=closeWindow(until(s,'before-roll'),[6,6]);else if(route==='cancel'){const id=Object.values(s.actions!).find(a=>a.cardInstanceId===PETRIFY)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else{s=until(s,'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:route==='teleport'?'a2-p06-r1c1':'a2-p05-r3c1',dedicated:false});}s=finish(s);expect(s.players.B).toMatchObject({presence:'active',damage:0});expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);expect(s.discard.filter(id=>id===PETRIFY)).toHaveLength(1);
});
it('actual stone death remains eligible for ordinary real chanted Resurrection and a fresh five card setup',()=>{
 let s=finish(act(prepare(makePetrifyPhysicalScenario('petrify-physical',players,{follower:'metal'})),'A',attack));const dead=structuredClone(s.players.B!),deathEvent=s.events.find(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')!;expect(dead.presence).toBe('dead');s=next(s);reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:REVIVE,targetIds:['B'],dedicated:false});s=prepare(s,REVIVE);s=act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:REVIVE,targetIds:['B'],dedicated:false});expect(Object.values(s.actions!).find(a=>a.cardInstanceId===REVIVE)!.checkSpecs).toHaveLength(3);s=finish(s);expect(s.players.B).toMatchObject({presence:'active',characterId:dead.characterId,damage:0,statuses:[],followers:[],chants:[]});expect(s.players.B!.hand).toHaveLength(5);expect(s.events.find(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toEqual(deathEvent);expect(s.discard).toContain(REVIVE);expect(s.discard).toContain(PETRIFY);expect(s.phase).toBe('hand-adjustment');
});
it('Petrify rejects dedicated multi self duplicate wrong actor and turn technique forms unchanged',()=>{const s=prepare(makePetrifyPhysicalScenario('petrify-physical',players));reject(s,'A',{...attack,dedicated:true});for(const targetIds of [[],['A'],['B','C'],['B','B'],['missing']])reject(s,'A',{...attack,targetIds});reject(s,'B',attack);reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:PETRIFY,targetIds:['B'],dedicated:false});});
