import {expect,it} from 'vitest';
import {transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makePlaguePhysicalScenario,PLAGUE,type PlaguePhysicalScenario} from './fixtures/plague-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['plague-physical-ordinary','plague-physical-dedicated'] as const;
function attack(scenario:PlaguePhysicalScenario){const dedicated=scenario.includes('dedicated');return {type:'ATTACK' as const,cardInstanceId:PLAGUE,targetIds:dedicated?['B','C','D']:['B'],dedicated};}
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(rows)('%s actual hand use preserves black magic5 damage12 fixed destruction and selected check waiver',scenario=>{
 const dedicated=scenario.includes('dedicated');for(const level of [4,5]){let s=makePlaguePhysicalScenario(scenario,players,{level});reject(s,'A',{type:'CHANT',cardInstanceId:PLAGUE});s=act(s,'A',attack(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===PLAGUE)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:5,effectLevel:5,damage:12,attributes:['魔','黒'],chant:false,noChecks:dedicated,evadeProhibited:true,destroyFollowersAtOrBelow:6,destroyFollowerExemptAttributes:['死'],personalImmunityCharacterNames:['不死王ガドューラ'],target:dedicated?'all':'one'});expect(f.checkSpecs).toHaveLength(dedicated?0:5-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([12,dedicated?8:0,dedicated?12:0]);expect(s.players.B!.followers).toEqual([]);expect(s.players.C!.followers).toHaveLength(dedicated?0:1);expect(discardIds(s).filter(id=>id===PLAGUE)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);}
});
it.each(rows)('%s actual fixed6 destroys Metal6 and Soldier2 without HP reduction while dead Skeleton uses normal HP4',scenario=>{
 let s=until(act(makePlaguePhysicalScenario(scenario,players),'A',attack(scenario)),'follower-start');s=closeWindow(s);const b=Object.values(s.groups!).find(g=>g.technique.destroyFollowersAtOrBelow===6)!.targets[0]!;expect(b.followerResults).toMatchObject([{outcome:'level-destroyed',hpReduction:0},{outcome:'level-destroyed',hpReduction:0}]);expect(b.hits[0]!.damage).toBe(12);s=finish(s);expect(s.players.B!.damage).toBe(12);if(scenario.includes('dedicated'))expect(s.players.C!.damage).toBe(8);else expect(s.players.C!.followers).toHaveLength(1);
});
it.each([['plague-physical-ordinary',0],['plague-physical-ordinary',2],['plague-physical-dedicated',0],['plague-physical-dedicated',2]] as const)('%s actual Water7 with Prayer%s proves destruction cutoff stays six independently of effect level',(scenario,bonus)=>{
 let s=act(makePlaguePhysicalScenario(scenario,players,{follower:'water'}),'A',{...attack(scenario),targetIds:['B']});if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===PLAGUE)!.id});while(s.windows?.length)s=pass(s,Array(30).fill(bonus));expect(s.rolls!.find(r=>r.purpose==='prayer-addition')!.faces).toEqual([bonus]);}s=finish(s);expect(s.players.B).toMatchObject({presence:'active',damage:0});expect(s.players.B!.followers).toHaveLength(bonus?0:1);expect(s.players.C!.followers).toHaveLength(1);
});
it.each(rows)('%s actual dead Wight5 is exempt from fixed destruction and still blocks at equal effect',scenario=>{let s=finish(act(makePlaguePhysicalScenario(scenario,players,{follower:'wight'}),'A',{...attack(scenario),targetIds:['B']}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.presence).toBe('active');expect(s.players.C!.followers).toHaveLength(1);});
it.each([false,true])('actual Gadyura revealed=%s ignores only personal effect after both eligible followers are destroyed',revealed=>{
 let s=makePlaguePhysicalScenario('plague-physical-immunity',players);if(revealed)s=act(s,'B',{type:'REVEAL_CHARACTER'});const hand=[...s.players.B!.hand],id=s.players.B!.characterId;s=finish(act(s,'A',attack('plague-physical-immunity')));expect(s.players.B).toMatchObject({presence:'active',damage:0,characterId:id,hand,revealed});expect(s.players.B!.followers).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.C!.followers).toHaveLength(1);expect(discardIds(s).filter(x=>x===PLAGUE)).toHaveLength(1);
});
it('actual dedicated Plague reflected by God Realm still destroys source follower but Gadyura takes no personal effect',()=>{
 let s=until(act(makePlaguePhysicalScenario('plague-physical-dedicated-reflection',players),'A',attack('plague-physical-dedicated-reflection')),'normal-defense');const own=s.players.A!.followers[0]!.cardInstanceId;s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p17-r3c2',dedicated:false}));expect(s.players.A).toMatchObject({presence:'active',damage:0,followers:[]});expect(discardIds(s)).toContain(own);expect(s.players.B).toMatchObject({presence:'active',damage:0});expect(s.players.B!.followers).toHaveLength(2);expect([s.players.C!.damage,s.players.D!.damage]).toEqual([8,12]);expect(discardIds(s).filter(id=>id===PLAGUE)).toHaveLength(1);
});
it.each(rows)('%s actual Evade refusal Teleport and Fate preserve the applicable target followers',scenario=>{
 let s=until(act(makePlaguePhysicalScenario(scenario,players),'A',attack(scenario)),'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}));expect(s.players.B).toMatchObject({presence:'active',damage:0});expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.damage).toBe(scenario.includes('dedicated')?8:0);
 s=act(makePlaguePhysicalScenario(scenario,players),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===PLAGUE)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,0,0]);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.followers).toHaveLength(1);expect(discardIds(s).filter(x=>x===PLAGUE)).toHaveLength(1);
});
it('actual ordinary Plague failed use spends source but never destroys followers',()=>{let s=until(act(makePlaguePhysicalScenario('plague-physical-ordinary',players,{level:4}),'A',attack('plague-physical-ordinary')),'before-roll');s=finish(closeWindow(s,[6,6]));expect(s.players.B).toMatchObject({presence:'active',damage:0});expect(s.players.B!.followers).toHaveLength(2);expect(discardIds(s).filter(id=>id===PLAGUE)).toHaveLength(1);});
it.each(rows)('%s ordinary multi foreign dedicated and invalid attack forms reject unchanged',scenario=>{const s=makePlaguePhysicalScenario(scenario,players);reject(s,'A',{...attack(scenario),dedicated:false,targetIds:['B','C']});for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',{...attack(scenario),targetIds});reject(s,'B',attack(scenario));reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:PLAGUE,targetIds:['B'],dedicated:false});reject(makePlaguePhysicalScenario(scenario,players,{foreign:true}),'A',{...attack(scenario),dedicated:true});});
