import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makePlantBindPhysical,plantBindCard as CARD,plantBindMode} from './fixtures/plant-bind-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,resistance:number[]=[6,6],damage:number[]=[3,3]){for(let n=0;n<900;n++){if(done(s))return s;const r=s.rolls?.at(-1);s=pass(s,s.windows?.at(-1)?.kind==='damage'||r?.purpose==='attack-damage'?damage:r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)?resistance:[1,1]);}throw Error('PLANT_BIND_LIMIT');}
function settle(s:GameState,faces:number[]=[6,6]){return until(s,s=>!s.windows?.length,faces);}
function nextB(s:GameState){for(let n=0;n<350;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='turn-start'){if(id==='B')return s;s=act(s,id,{type:'START_TURN'});}else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(gameStats(s,id).handLimit)});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PLANT_BIND_PHASE');}throw Error('PLANT_BIND_TURN_LIMIT');}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['plant-bind-ordinary', 'plant-bind-owner-ordinary', 'plant-bind-low', 'plant-bind-dedicated', 'plant-bind-pair', 'plant-bind-all', 'plant-bind-near', 'plant-bind-same-faction', 'plant-bind-water', 'plant-bind-metal', 'plant-bind-lower', 'plant-bind-maai-ordinary', 'plant-bind-maai-dedicated', 'plant-bind-evade-ordinary', 'plant-bind-evade-dedicated', 'plant-bind-fate', 'plant-bind-suppressed', 'plant-bind-silenced', 'plant-bind-stopped', 'plant-bind-wrong-owner', 'plant-bind-decline', 'plant-bind-noncounter', 'plant-bind-recovery-ordinary', 'plant-bind-recovery-dedicated', 'plant-bind-resist-success-ordinary', 'plant-bind-resist-success-dedicated'] as const)('%s actual earth bind applies no damage and advances recovery modifiers',name=>{
 let s=makePlantBindPhysical(name,players);const m=plantBindMode(name),hand=[...s.players.A!.hand],attack=cmd(m.dedicated,m.targets.map(i=>players[i]!.id));
 if(['stopped','wrong-owner','silenced'].includes(m.suffix)){reject(s,'A',attack);return;}if(m.decline){s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);return;}if(m.suffix==='noncounter'){for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',attack);expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(source(s).technique).toMatchObject({school:'magic',range:'far',useLevel:4,effectLevel:4,damage:null,attributes:['魔','地'],chant:false,counter:false,noChecks:m.dedicated,target:m.dedicated?'all':'one',onHitResistance:{modifiers:[-3,-2,-1,0],statusKind:'stopped'}});
 if(m.cancel){const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.statuses??[]).toEqual([]);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).targets.map(t=>t.hits[0]!.damage)).toEqual(m.targets.map(()=>null));if(m.maai||m.evade){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',m.maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}
 const blocked=m.maai||m.evade||m.suffix==='water'||m.suffix==='metal';s=settle(s,m.success?[1,1]:[6,6]);expect(s.seatOrder.map(id=>s.players[id]!.damage)).toEqual([0,0,0,0]);expect(s.players.B!.statuses??[]).toHaveLength(blocked||m.success?0:1);if(!blocked&&!m.success)expect(s.players.B!.statuses![0]).toMatchObject({kind:'stopped',modifiers:[-3,-2,-1,0],nextCheck:1,sourceCardInstanceId:CARD});const resistance=s.rolls?.find(r=>r.purpose==='status-resistance'&&r.rollerId==='B');if(blocked)expect(resistance).toBeUndefined();else expect(resistance).toMatchObject({modifier:-3,success:m.success});if(m.follower)expect(s.players.B!.followers).toHaveLength(m.suffix==='lower'?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='attack-damage')).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);for(const id of ['C','D'])expect(s.players[id]!.statuses??[]).toEqual([]);
 if(m.recovery){const id=s.players.B!.statuses![0]!.id;for(const [modifier,faces,success] of [[-2,[6,6],false],[-1,[6,6],false],[0,[6,6],false],[0,[3,3],true]] as const){s=act(nextB(s),'B',{type:'START_TURN'});s=until(s,s=>s.rolls?.at(-1)?.purpose==='status-recovery'&&s.rolls.at(-1)?.stage==='before-roll');expect(s.rolls!.at(-1)!.modifier).toBe(modifier);s=closeWindow(s,[...faces]);s=settle(s);expect(s.players.B!.statuses??[]).toHaveLength(success?0:1);if(!success)expect(s.players.B!.statuses![0]!.id).toBe(id);else expect(s.phase).toBe('draw');expect(s.players.B!.damage).toBe(0);}}
});
it.each([[false,[1,2],true],[false,[2,2],false],[true,[1,2],true],[true,[2,2],false]] as const)('actual initial minus3 spirit6 boundary dedicated=%s faces%s success=%s',(dedicated,faces,success)=>{let s=settle(act(makePlantBindPhysical(dedicated?'plant-bind-dedicated':'plant-bind-ordinary',players),'A',cmd(dedicated)),[...faces]);expect(s.rolls!.find(r=>r.purpose==='status-resistance')).toMatchObject({threshold:3,success});expect(s.players.B!.statuses??[]).toHaveLength(success?0:1);});
it.each([[3,3,true],[3,4,false]] as const)('actual ordinary magic3 use shortage %s plus %s success=%s before resistance',(x,y,success)=>{let s=act(makePlantBindPhysical('plant-bind-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);s=settle(s);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(success?1:0);expect(s.players.B!.damage).toBe(0);});
it('actual invalid ordinary extra targets owner actor and empty dedicated selection preserve state and views',()=>{const s=makePlantBindPhysical('plant-bind-ordinary',players);for(const targetIds of [[],['A'],['B','B'],['B','C'],['missing']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());reject(s,'A',cmd(true));const d=makePlantBindPhysical('plant-bind-dedicated',players);reject(d,'A',cmd(true,[]));});
