import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makePrisonPhysicalScenario} from '../../../apps/worker/test/fixtures/prison-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p13-r3c3',rows=['prison-ordinary','prison-dedicated'] as const;
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState){for(let n=0;n<150;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('PRISON_TURN');}throw Error('PRISON_TURN_LIMIT');}
function chant(s:GameState){s=act(s,'A',{type:'CHANT',cardInstanceId:card});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return nextOwn(s);}
function attack(dedicated:boolean){return {type:'ATTACK' as const,cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated};}
function finish(s:GameState,apply:string[]=[],duration=3){for(let n=0;n<400&&s.windows?.length;n++){if(s.windows!.at(-1)!.kind==='lifetime-effect-choice'){const target=viewFor(s,'A').lifetimeDecision!.targetId;reject(s,'B',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'});s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:apply.includes(target)?'apply':'decline'},Array(30).fill(duration));}else s=pass(s);}expect(s.windows??[]).toEqual([]);return s;}
it.each(rows)('%s real chant keeps printed restrictions and only dedicated activation checks are waived',scenario=>{
 const dedicated=scenario==='prison-dedicated';for(const level of [7,8]){let s=makePrisonPhysicalScenario(scenario,players,{level});reject(s,'A',attack(dedicated));s=act(chant(s),'A',attack(dedicated));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:8,effectLevel:8,damage:10,attributes:['魔','黒','詠'],chant:true,noChecks:dedicated,target:dedicated?'all':'one',maaiProhibited:true,prohibitedFactions:['GOOD'],destroyFollowersAtOrBelowEffectLevel:true});expect(f.checkSpecs).toHaveLength(dedicated?0:8-level);expect(f.fromChant).toBe(true);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([10,dedicated?10:0,0]);expect(s.players.B!.followers).toEqual([]);expect(s.players.C!.followers).toHaveLength(dedicated?0:1);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.rolls?.some(r=>r.purpose==='stop-duration')??false).toBe(false);expect(s.discard.filter(id=>id===card)).toHaveLength(1);}
});
it.each(rows)('%s actual failed ordinary use consumes source without destruction or stopping',scenario=>{
 const dedicated=scenario==='prison-dedicated';let s=act(chant(makePrisonPhysicalScenario(scenario,players,{level:7})),'A',attack(dedicated));if(!dedicated){s=until(s,'before-roll');s=closeWindow(s,[6,6]);}s=finish(s,['B','C']);expect([s.players.B!.damage,s.players.C!.damage]).toEqual(dedicated?[10,10]:[0,0]);expect(s.players.B!.followers).toHaveLength(dedicated?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='excess-level').map(r=>r.success)).toEqual(dedicated?[]:[false]);expect(s.players.B!.statuses??[]).toHaveLength(dedicated?1:0);
});
it.each([['prison-ordinary',-1,0],['prison-ordinary',0,10],['prison-ordinary',1,10],['prison-dedicated',-1,0],['prison-dedicated',0,10],['prison-dedicated',1,10]] as const)('%s actual boundary%s using drawn Blessing or Prayer against Guardian yields body%s',(scenario,bonus,damage)=>{
 let s=act(chant(makePrisonPhysicalScenario(scenario,players,{follower:'guardian',blessing:bonus<0})),'A',{...attack(scenario==='prison-dedicated'),targetIds:['B']});if(bonus>0){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id});}s=finish(s,['B']);expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(damage?0:1);expect(s.players.C!.followers).toHaveLength(1);expect(s.players.B!.statuses??[]).toHaveLength(damage&&scenario==='prison-dedicated'?1:0);
});
it.each(['both','B','C','none'])('actual dedicated optional stop selects %s and shares one saved duration only for chosen hits',selection=>{
 const apply=selection==='both'?['B','C']:selection==='none'?[]:[selection];
 let s=finish(act(chant(makePrisonPhysicalScenario('prison-dedicated',players)),'A',attack(true)),apply);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([10,10]);expect((s.rolls??[]).filter(r=>r.purpose==='stop-duration')).toHaveLength(apply.length?1:0);for(const id of ['B','C']){const statuses=s.players[id]!.statuses??[];expect(statuses).toHaveLength(apply.includes(id)?1:0);if(apply.includes(id))expect(statuses[0]).toMatchObject({kind:'stopped',timing:'fixed-turns',remainingTurns:3});}expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);
});
it('actual shared three-turn stop decrements only each recipient and expires after its third skipped turn',()=>{
 let s=finish(act(chant(makePrisonPhysicalScenario('prison-dedicated',players)),'A',attack(true)),['B','C']);const hands=Object.fromEntries(['B','C'].map(id=>[id,[...s.players[id]!.hand]]));for(let round=1;round<=3;round++){s=act(s,'A',{type:s.phase==='action'?'PASS_ACTION':'PASS_WITHDRAWAL'} as never);s=nextOwn(s);for(const id of ['B','C']){expect(s.players[id]!.hand).toEqual(hands[id]);const statuses=s.players[id]!.statuses??[];expect(statuses).toHaveLength(round===3?0:1);if(round<3)expect(statuses[0]).toMatchObject({remainingTurns:3-round});}expect(s.rolls!.filter(r=>r.purpose==='status-recovery')).toHaveLength(0);}s=act(s,'A',{type:'PASS_ACTION'});for(let n=0;n<100&&!(s.phase==='draw'&&s.seatOrder[s.turnSeat]==='B');n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:[]});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else throw Error('PRISON_RELEASE');}expect(s.seatOrder[s.turnSeat]).toBe('B');expect(s.phase).toBe('draw');
});
it.each(rows)('%s actual maai refusal and Teleport success prevent only the defended hit and stop',scenario=>{
 const dedicated=scenario==='prison-dedicated';let s=until(act(chant(makePrisonPhysicalScenario(scenario,players)),'A',attack(dedicated)),'normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});expect(viewFor(s,'B').currentAttack!.defenseRestrictions).toMatchObject({maaiProhibited:true,evadeProhibited:false});s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}),['B','C']);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,dedicated?10:0]);expect(s.players.B!.followers).toHaveLength(1);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.C!.statuses??[]).toHaveLength(dedicated?1:0);
});
it.each(rows)('%s actual Fate cancels damage follower destruction and optional lifetime decision',scenario=>{
 let s=act(chant(makePrisonPhysicalScenario(scenario,players)),'A',attack(scenario==='prison-dedicated'));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=pass(pass(s));s=finish(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}),['B','C']);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.B!.followers).toHaveLength(1);expect(s.players.C!.followers).toHaveLength(1);expect(s.rolls?.some(r=>r.purpose==='stop-duration')??false).toBe(false);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
it.each(rows)('%s refuses actual GOOD Uonos use despite dedication and rejects foreign or multiple ordinary targets',scenario=>{
 const s=makePrisonPhysicalScenario(scenario,players,{sourceGood:true});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);expect(s.players.A!.faction).toBe('GOOD');reject(s,'A',attack(false));reject(s,'A',attack(true));const foreign=chant(makePrisonPhysicalScenario(scenario,players,{owner:'不死王ガドューラ'}));reject(foreign,'A',attack(true));const normal=chant(makePrisonPhysicalScenario(scenario,players));reject(normal,'A',{...attack(false),targetIds:['B','C']});
});
