import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {transition,viewFor} from '../src/index.js';
import {act,finish,pass,until} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeReclaimScenario} from './fixtures/reclaim-scenarios.js';
it('R6 actual cancellation refills once then ordinary recovery reserves the same paid Fate until parent completion',()=>{
 let s=makeReclaimScenario('reclaim-owned',['A','B','C','D'].map(id=>({id,name:id})));const heal=s.players.A!.hand.find(id=>getAction(id)!.name==='封傷')!,fate='a2-p02-r2c3',hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;
 s=act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:heal,targetIds:['A'],dedicated:false});s=pass(s);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:viewFor(s,'B').reactionTargetActionId!});expect(s.players.B!.hand).toHaveLength(hand.length);const replacement=s.players.B!.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();expect(replacement).not.toBe(fate);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);s=until(s,'reclaim');const d=viewFor(s,'B').reclaim!,take={type:'CHOOSE_RECLAIM' as const,decisionId:d.decisionId,choice:'take' as const,claimId:d.claims[0]!.claimId};s=act(s,'B',take);expect(s.reclaimReservations).toContain(fate);expect(s.resolution).not.toContain(fate);expect(s.deck).not.toContain(fate);expect(s.discard).not.toContain(fate);for(const p of Object.values(s.players))expect(p.hand).not.toContain(fate);const saved=JSON.stringify(s);expect(transition(s,{actorId:'B',command:take},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);s=finish(JSON.parse(saved));expect(s.players.B!.hand.filter(id=>id===fate)).toHaveLength(1);expect(s.players.B!.hand).toContain(replacement);expect(s.players.B!.hand).toHaveLength(hand.length+1);expect(s.players.A!.damage).toBe(2);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.reclaimReservations).toEqual([]);expect(s.players.B!.reclaimUsage?.['命運凶変']?.baseSpent).toBe(true);
});
