import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeR6CombinedSuppressionScenario} from '../../../apps/worker/test/fixtures/r6-combined-suppression-scenario.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<400;n++){if(done(s))return s;s=pass(s);}throw Error('COMBINED_SUPPRESSION_TEST_WINDOW');}
function nextOwn(s:GameState,owner:string){for(let n=0;n<60;n++){const id=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(id===owner)return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!=='a2-p13-r3c1').slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))}));else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error(`COMBINED_SUPPRESSION_TEST_TURN_${s.phase}`);}throw Error('COMBINED_SUPPRESSION_TEST_TURN_LIMIT');}
it('R6 actual Spirit freezes6 then Vanmil ban persists through actual death revival and rejects the new-life modifier without changing the old frozen value',()=>{
 let s=makeR6CombinedSuppressionScenario(players);const id=Object.keys(s.actions!)[0]!,life=s.players.A!.lifeId,spirit=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p01-r2c1-ab03')!;s=act(s,'A',{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:spirit.targetEventId});s=until(s,s=>s.windows?.at(-1)?.kind==='damage'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');expect(s.actions![id]!.technique.effectLevel).toBe(6);expect(s.actions![id]!.modifiers!.effectFrozen).toBe(true);const ban=viewFor(s,'C').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=act(s,'C',{type:'USE_ABILITY',abilityId:ban.abilityId,targetEventId:ban.targetEventId,targetIds:['A']});s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values(s.groups!)[0]!.technique.effectLevel).toBe(6);const designation=structuredClone(s.suppressionDesignations);s=finish(s);expect(s.players.B!.damage).toBe(7);s=nextOwn(s,'B');const lethal=s.players.B!.hand.find(id=>getAction(id)!.name==='踏み込み／弓')!;s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:lethal,targetIds:['A'],dedicated:false}));expect(s.players.A!.presence).toBe('dead');expect(s.outcome).toBeUndefined();s=nextOwn(s,'D');s=until(act(s,'D',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['A'],dedicated:true}),s=>s.windows?.at(-1)?.kind==='re-setup');expect(s.players.A!.presence).toBe('active');expect(s.players.A!.damage).toBe(0);expect(s.players.A!.lifeId).not.toBe(life);expect(s.suppressionDesignations).toEqual(designation);s=finish(act(s,'A',{type:'PASS_SETUP'}));s=nextOwn(s,'A');const next=s.players.A!.hand.find(id=>getAction(id)!.name==='手裏剣')!;expect(next).toBeDefined();s=until(act(s,'A',{type:'ATTACK',cardInstanceId:next,targetIds:['C'],dedicated:false}),s=>s.windows?.at(-1)?.kind==='effect-level');expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===spirit.abilityId)).toBe(false);const before=JSON.stringify(s),action=Object.values(s.actions!).find(a=>a.kind==='attack')!;expect(transition(s,{actorId:'A',command:{type:'USE_ABILITY',abilityId:spirit.abilityId,targetEventId:action.eventId}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(Object.values(s.groups!)[0]!.technique.effectLevel).toBe(4);s=finish(s);expect(s.players.B!.damage).toBe(7);expect(s.players.C!.damage).toBe(5);expect(s.suppressionDesignations).toEqual(designation);
});
it('R6 browser revived prefix follows the same actual death and revival commands',()=>{const s=makeR6CombinedSuppressionScenario(players,true);expect(s.players.A!.damage).toBe(0);expect(s.events.filter(e=>e.type==='PLAYER_DIED'&&e.actorId==='A')).toHaveLength(1);expect(s.suppressionDesignations!.map(x=>x.targetId)).toEqual(['A']);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId==='c2-p01-r2c1-ab03')).toBe(false);});
