import {expect,it} from 'vitest';
import {gameStats,viewFor,type GameState} from '../src/index.js';
import {act,finish,closeWindow,pass} from './combat-helpers.js';
import {makeR6Scenario} from './fixtures/r6-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function nextStart(s:GameState){for(let n=0;n<50;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'){if(actor==='B')return s;s=act(s,actor,{type:'START_TURN'});}else if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error('S20_TURN');}throw Error('S20_TURN_LIMIT');}
it('S20 physical ordinary poem advances the same stop from initial minus3 failure through minus2 failure and minus1 success with refill and normal draw',()=>{let s=makeR6Scenario('r6-s20-hit',players);expect(s.players.B!.hand).toHaveLength(4);expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-resistance',modifier:-3,faces:[]});s=finish(closeWindow(closeWindow(s,[3,4])));expect(s.players.B!.damage).toBe(5);const id=s.players.B!.statuses![0]!.id;expect(s.players.B!.statuses![0]).toMatchObject({sourceCardInstanceId:'a2-p17-r1c1',modifiers:[-3,-2,-1],nextCheck:1});s=nextStart(s);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:-2,faces:[]});s=finish(closeWindow(closeWindow(JSON.parse(JSON.stringify(s)),[3,4])));expect(s.players.B!.statuses![0]).toMatchObject({id,nextCheck:2});expect(s.players.B!.hand).toHaveLength(4);expect(s.turnSeat).toBe(2);s=nextStart(s);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:-1,faces:[]});const draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;s=finish(closeWindow(closeWindow(JSON.parse(JSON.stringify(s)),[2,3])));expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.hand).toHaveLength(5);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.phase).toBe('draw');s=act(s,'B',{type:'CHOOSE_DRAW',draw:true});expect(s.players.B!.hand).toHaveLength(6);expect(s.phase).toBe('action');s=act(s,'B',{type:'PASS_ACTION'});s=finish(act(s,'B',{type:'END_TURN',discardIds:[s.players.B!.hand[0]!]}));expect(s.turnSeat).toBe(2);expect(s.rolls!.filter(r=>r.purpose==='status-resistance'||r.purpose==='status-recovery').map(r=>({modifier:r.modifier,success:r.success}))).toEqual([{modifier:-3,success:false},{modifier:-2,success:false},{modifier:-1,success:true}]);});
// S21 secrecy ends at mandatory G15 hit publication, as the current R6 plan requires.
it('S21 actual White Light5 damage6 keeps unused Shelim ability private until mandatory G15 hit publication',()=>{let s=makeR6Scenario('r6-s21',players);expect(viewFor(s,'B').abilityOptions.some(o=>o.abilityId==='c2-p01-r1c1-ab01')).toBe(true);expect(viewFor(s,'B').currentAttack!.technique).toMatchObject({effectLevel:5,damage:6});const privateCheck=()=>{for(const id of ['A','C','D']){expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1');expect(viewFor(s,id).abilityOptions.some(o=>o.abilityId==='c2-p01-r1c1-ab01')).toBe(false);}};privateCheck();s=pass(JSON.parse(JSON.stringify(s)));privateCheck();expect(s.players.B!.revealed).toBe(false);s=finish(s);expect(s.players.B!.revealed).toBe(true);for(const id of ['A','C','D']){expect(viewFor(s,id).logs.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='B'&&e.characterId==='c2-p01-r1c1')).toBe(true);expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1-ab01');}expect(s.players.B!.damage).toBe(6);expect(s.phase).toBe('withdrawal');});

it('S22 two OPEN share one actual reaction refill and resume the original parent generation after saved FuSen choice',()=>{let s=makeR6Scenario('r6-s22',players);expect(s.players.D!.presence).toBe('dead');expect(s.events.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='D')).toBe(true);const parent=structuredClone(s.windows!.at(-1)!),hand=s.players.C!.hand.length,draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C').length;expect(s.deck.slice(0,2)).toEqual(['a2-p01-r1c1','a2-p01-r1c2']);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.continuation.id});expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(s.players.C!.hand).toHaveLength(hand-1);expect(s.players.C!.open).toContain('a2-p01-r1c1');expect(s.players.C!.open).not.toContain('a2-p01-r1c2');expect(s.resolution).toEqual(expect.arrayContaining(['a2-p02-r2c3','a2-p08-r1c1']));s=closeWindow(s,[4]);s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('revival');expect(s.players.C!.hand).toHaveLength(hand-1);s=act(JSON.parse(JSON.stringify(s)),'D',{type:'CHOOSE_REVIVAL',revive:false});expect(s.players.C!.open).toEqual(expect.arrayContaining(['a2-p01-r1c1','a2-p01-r1c2']));expect(s.players.C!.hand).toHaveLength(hand);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='C')).toHaveLength(draws+1);expect(s.players.D!.presence).toBe('dead');expect(s.deck).not.toContain('a2-p02-r2c3');expect(s.deck).not.toContain('a2-p08-r1c1');expect(s.windows!.at(-1)!.kind).toBe('declaration');expect(s.windows!.some(w=>w.id===parent.id)).toBe(true);for(let n=0;n<150&&s.windows!.at(-1)!.id!==parent.id;n++)s=pass(s);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);s=finish(JSON.parse(JSON.stringify(s)));expect(s.players.C!.damage).toBe(0);expect(s.discard.filter(id=>id==='a2-p02-r2c3')).toHaveLength(1);expect(s.discard.filter(id=>id==='a2-p08-r1c1')).toHaveLength(1);expect(s.resolution).toEqual([]);expect(s.phase).toBe('withdrawal');});

it('S23 natural exhaustion draws 1 plus 2 discard with the real secret book still in resolution and deterministic replay',()=>{let s=makeR6Scenario('r6-s23',players);const first=s.deck[0]!,discards=[...s.discard],hand=[...s.players.A!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='A').length;expect(s.deck).toHaveLength(1);expect(discards).toHaveLength(2);expect(s.resolution).toEqual(['a2-p03-r1c1']);expect(s.rolls!.at(-1)).toMatchObject({purpose:'extra-draw',faces:[3]});s=closeWindow(JSON.parse(JSON.stringify(s)));expect(s.windows!.at(-1)!.kind).toBe('reclaim');expect(s.players.A!.hand.slice(hand.length)).toEqual([first,discards[1],discards[0]]);expect(s.deck).toEqual([]);expect(s.discard).toEqual([]);expect(s.resolution).toEqual(['a2-p03-r1c1']);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='A')).toHaveLength(draws+3);expect(s.players.A!.hand).not.toContain('a2-p03-r1c1');s=finish(s);expect(s.discard).toEqual(['a2-p03-r1c1']);expect(s.resolution).toEqual([]);expect(s.phase).toBe('action');expect(s.lifecycle??[]).toEqual([]);s=act(s,'A',{type:'PASS_ACTION'});expect(s.phase).toBe('hand-adjustment');});

it('S27 actual final two-person chanted destruction commits both deaths before the final all-dead draw',()=>{let s=makeR6Scenario('r6-s27',players);expect(s.players.C!.presence).toBe('dead');expect(s.players.D!.presence).toBe('dead');expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['C','D']);expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain('a2-p13-r2c3');expect(s.outcome).toBeUndefined();const a=s.players.A!.damage,b=s.players.B!.damage;s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p13-r2c3',targetIds:['B'],dedicated:false});for(let n=0;n<300&&s.windows?.at(-1)?.kind!=='death-gift';n++){expect(s.outcome).toBeUndefined();s=pass(s);}expect(s.players.A).toMatchObject({presence:'pending-death',damage:a+10});expect(s.players.B).toMatchObject({presence:'pending-death',damage:b+20});const batch=s.lifecycle!.find(t=>t.kind==='death-batch')!;expect(batch).toMatchObject({actorIds:['A','B']});expect(s.outcome).toBeUndefined();s=JSON.parse(JSON.stringify(s));for(let n=0;n<100&&s.players.A!.presence!=='dead';n++)s=pass(s);expect(s.players.A!.presence).toBe('dead');expect(s.players.B!.presence).toBe('pending-death');expect(s.outcome).toBeUndefined();for(const id of ['A','B','C','D'])expect(viewFor(s,id).outcome).toBeNull();s=finish(s);expect(Object.values(s.players).every(p=>p.presence==='dead')).toBe(true);expect(s.outcome).toMatchObject({kind:'draw',reason:'mutual-extinction',winnerIds:[],results:{A:'draw',B:'draw',C:'draw',D:'draw'}});expect(s.resolution).toEqual([]);expect(s.reclaimReservations).toEqual([]);expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['C','D','A','B']);expect(s.events.filter(e=>e.type==='GAME_COMPLETED')).toHaveLength(1);expect(s.discard.filter(id=>id==='a2-p13-r2c3')).toHaveLength(1);});

it('S21 alternate hidden character has identical foreign projections and pass order until the actual hit reveals identity',()=>{
 let s=makeR6Scenario('r6-s21',players),control=makeR6Scenario('r6-s21-control',players);
 for(let n=0;n<300;n++){
  expect(s.players.B!.revealed).toBe(control.players.B!.revealed);
  if(s.players.B!.revealed)break;
  for(const id of ['A','C','D'])expect(viewFor(s,id)).toEqual(viewFor(control,id));
  expect(s.windows!.at(-1)).toEqual(control.windows!.at(-1));
  s=pass(s);control=pass(control);
 }
 expect(s.players.B!.revealed).toBe(true);expect(control.players.B!.revealed).toBe(true);
 s=finish(s);control=finish(control);
 expect(s.players.B!.damage).toBe(6);expect(control.players.B!.damage).toBe(6);
 for(const id of ['A','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain('c2-p01-r1c1-ab01');
});
