import {expect,it} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until,closeWindow,passReclaims} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeRambaAxesScenario,rambaAxeMode,type RambaAxesScenario} from './fixtures/ramba-axes-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const rows=['axe-strike-ordinary','axe-strike-dedicated','axe-mighty-ordinary','axe-mighty-dedicated','axe-death-ordinary','axe-death-dedicated'] as const;
function command(name:RambaAxesScenario){const m=rambaAxeMode(name);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.far&&m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(rows)('%s exact physical profile retains printed values and actual insufficient-level checks only in ordinary mode',scenario=>{
 const m=rambaAxeMode(scenario);for(const level of [m.use-1,m.use]){let s=act(makeRambaAxesScenario(scenario,players,{level,guard:'none'}),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'warrior',range:m.far?'far':'near',useLevel:m.use,effectLevel:m.use,damage:m.damage,attributes:['戦','斧'],chant:false,noChecks:m.dedicated,target:m.far&&m.dedicated?'all':'one'});expect(f.technique.destroyFollowersAtOrBelow).toBe(m.dedicated?m.limit:undefined);expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.damage,m.far&&m.dedicated?m.damage:0,0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);}
});
it.each(rows)('%s ordinary and dedicated differ at the actual printed follower threshold',scenario=>{
 const m=rambaAxeMode(scenario);let s=makeRambaAxesScenario(scenario,players);const guard=s.players.B!.followers[0]!.cardInstanceId;s=until(act(s,'A',command(scenario)),'follower-start');s=closeWindow(s);const target=Object.values(s.groups!).find(g=>g.attackerId==='A')!.targets[0]!;expect(target.followerDefense![0]!.levels[0]).toBe(m.limit);if(m.dedicated)expect(target.followerDefense![0]!.hits[0]!.outcome).toBe('level-destroyed');s=finish(s);expect(s.players.B!.damage).toBe(m.dedicated?m.damage:0);expect(s.players.B!.followers.some(f=>f.cardInstanceId===guard)).toBe(!m.dedicated);expect(s.discard.filter(id=>id===guard)).toHaveLength(m.dedicated?1:0);if(!m.dedicated&&m.limit===5)expect(s.players.A!.damage).toBe(m.damage);
});
it.each(['axe-strike-dedicated','axe-mighty-dedicated','axe-death-dedicated'] as const)('%s leaves the actual follower one above its fixed limit alive',scenario=>{
 const m=rambaAxeMode(scenario);let s=makeRambaAxesScenario(scenario,players,{guard:'above'});const guard=s.players.B!.followers[0]!.cardInstanceId;s=until(act(s,'A',command(scenario)),'follower-start');s=closeWindow(s);expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.levels[0]).toBe(m.limit+1);s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers.some(f=>f.cardInstanceId===guard)).toBe(true);expect(s.discard).not.toContain(guard);
});
it.each(['axe-strike-dedicated','axe-mighty-dedicated','axe-death-dedicated'] as const)('%s actual Prayer2 raises effect level but not its fixed destruction limit',scenario=>{
 const m=rambaAxeMode(scenario);let s=act(makeRambaAxesScenario(scenario,players,{guard:'above'}),'A',command(scenario));s=until(s,'effect-level');const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});for(let n=0;n<300&&s.windows?.at(-1)?.kind!=='follower-start';n++)s=pass(s,[2]);expect(s.actions![id]!.technique).toMatchObject({effectLevel:m.use+2,destroyFollowersAtOrBelow:m.limit});s=closeWindow(s);for(let n=0;n<100&&!Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits[0];n++)s=pass(s);const snap=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(snap.levels[0]).toBe(m.limit+1);expect(snap.hits[0]!.outcome).toBe('equal-destroyed');s=finish(s);expect(s.players.B!.damage).toBe(0);
});
it.each(rows)('%s actual Fate cancels before follower destruction and spends only the attack source',scenario=>{
 const m=rambaAxeMode(scenario);let s=makeRambaAxesScenario(scenario,players);const guard=s.players.B!.followers[0]!;s=act(s,'A',command(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=pass(s);s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,0]);expect(s.players.B!.followers).toEqual([guard]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual per-target maai keeps one-card defense except the two-card Death Axe',scenario=>{
 const m=rambaAxeMode(scenario),required=m.far?2:1;for(const count of [1,2]){let s=until(act(makeRambaAxesScenario(scenario,players,{guard:'none'}),'A',command(scenario)),'normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});if(required===2&&count===2)s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([count>=required?0:m.damage,m.far&&m.dedicated?m.damage:0]);}
});
it.each(['axe-strike-dedicated','axe-mighty-dedicated','axe-death-dedicated'] as const)('%s rejects foreign dedicated owner and illegal ordinary multiple-target choice',scenario=>{
 const s=makeRambaAxesScenario(scenario,players),foreign=makeRambaAxesScenario(scenario,players,{owner:'侍大将のシン'});reject(foreign,'A',command(scenario));reject(s,'A',{...command(scenario),dedicated:false,targetIds:['B','C']});reject(s,'A',{...command(scenario),techniqueVariant:'two-hit'});
});
it.each(['axe-strike-dedicated','axe-mighty-dedicated'] as const)('%s far refusal is followed by actual approach and legal near damage',scenario=>{
 const m=rambaAxeMode(scenario);let s=makeRambaAxesScenario(scenario,players,{prepared:false,guard:'none'});reject(s,'A',command(scenario));s=finish(act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:'a2-p24-r1c2'}));s=finish(act(s,'A',command(scenario)));expect(s.players.B!.damage).toBe(m.damage);
});
