import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,finish,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeResurrectionPhysicalScenario,type ResurrectionPhysicalScenario} from './fixtures/resurrection-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p13-r3c1',rows=['resurrection-ordinary','resurrection-dedicated','resurrection-chanted-dedicated'] as const;
function command(scenario:ResurrectionPhysicalScenario,convert=false){const dedicated=scenario!=='resurrection-ordinary';return {type:'PLAY_TURN_TECHNIQUE' as const,cardInstanceId:card,targetIds:dedicated?['B','C']:['B'],dedicated,convertTargetIds:convert?['B']:[]};}
function nextA(s:GameState){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('RESURRECTION_TEST_PHASE');}throw Error('RESURRECTION_TEST_TURN');}
function prepare(s:GameState,scenario:ResurrectionPhysicalScenario){if(scenario==='resurrection-dedicated')return s;return nextA(act(s,'A',{type:'CHANT',cardInstanceId:card}));}
function settle(s:GameState){for(let n=0;n<400&&s.windows?.length;n++){const w=s.windows!.at(-1)!;s=w.kind==='re-setup'?act(s,w.participants[w.cursor]!,{type:'PASS_SETUP'}):pass(s);}expect(s.windows??[]).toEqual([]);return s;}
function reject(s:GameState,id:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(rows)('%s actual deaths and selected cast preserve profile then rebuild only the chosen players',scenario=>{
 for(const level of [9,10]){let s=makeResurrectionPhysicalScenario(scenario,players,{level});expect([s.players.B!.presence,s.players.C!.presence]).toEqual(['dead','dead']);expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(['B','C']);expect(discardIds(s)).toContain('a2-p03-r3c1');expect(s.players.B!.attachments).toEqual([]);const identity=s.players.B!.characterId,faction=s.players.B!.faction,objective=structuredClone(s.players.B!.currentObjective);if(scenario==='resurrection-ordinary')reject(s,'A',command(scenario));s=act(prepare(s,scenario),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(f.technique).toMatchObject({school:'magic',range:'none',useLevel:10,effectLevel:10,damage:null,attributes:['魔','詠'],chant:scenario==='resurrection-ordinary',noChecks:scenario!=='resurrection-ordinary',target:scenario==='resurrection-ordinary'?'one':'all',turnEffect:'revive'});expect(f.checkSpecs).toHaveLength(scenario==='resurrection-ordinary'?10-level:0);s=until(s,'re-setup');expect(s.outcome).toBeUndefined();expect(s.players.B).toMatchObject({presence:'active',revealed:true,damage:0,characterId:identity,faction,currentObjective:objective});expect(s.players.B!.hand).toHaveLength(5);expect(s.players.B!.hand).not.toContain('a2-p03-r3c1');expect(s.players.B!.attachments).toEqual([]);expect(s.players.B!.followers).toEqual([]);s=settle(s);expect(s.players.C!.presence).toBe(scenario==='resurrection-ordinary'?'dead':'active');expect(s.phase).toBe('hand-adjustment');expect(s.seatOrder[s.turnSeat]).toBe('A');expect(discardIds(s).filter(x=>x===card)).toHaveLength(1);}
});
it.each(rows)('%s actual Fate cancels resurrection before any re-setup or allegiance change',scenario=>{
 let s=act(prepare(makeResurrectionPhysicalScenario(scenario,players),scenario),'A',command(scenario,scenario!=='resurrection-ordinary'));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.B!.presence,s.players.C!.presence]).toEqual(['dead','dead']);expect(s.players.B!.faction).toBe('GOOD');expect(discardIds(s).filter(x=>x===card)).toHaveLength(1);expect(s.phase).toBe('hand-adjustment');
});
it('ordinary actual failed excess-level check leaves both truly dead targets unchanged',()=>{
 let s=act(prepare(makeResurrectionPhysicalScenario('resurrection-ordinary',players,{level:9}),'resurrection-ordinary'),'A',command('resurrection-ordinary'));s=until(s,'before-roll');s=settle(closeWindow(s,[6,6]));expect(s.rolls!.find(r=>r.purpose==='excess-level')!.success).toBe(false);expect([s.players.B!.presence,s.players.C!.presence]).toEqual(['dead','dead']);expect(discardIds(s).filter(x=>x===card)).toHaveLength(1);
});
it.each(['大神官ジル','小妖精のチャム','有翼人のティア','早駆けのランカスター','小人のランバ','吟遊詩人のレスター','黒妖精のアーネス','凍気のアイエル','竜皇子アスフェルト','占星術師のアルセイル','忍びのイダ','獣使いのウパニシャット','黒騎士ガーウィン','爆炎のフレイアード','魔聖母ディア','餓狼ヨーツルム'])('%s actual initial-character death permits optional Uonos conversion and exact objective package',victim=>{
 let s=makeResurrectionPhysicalScenario('resurrection-dedicated',players,{victim});const source=structuredClone(s.players.A!);s=settle(act(s,'A',command('resurrection-dedicated',true)));expect(s.players.B).toMatchObject({presence:'active',damage:0,revealed:true,faction:source.faction,currentObjective:source.currentObjective,protection:source.protection,objective:source.objective});expect(s.players.B!.attachments).toEqual([]);expect(s.players.B!.hand).toHaveLength(5);expect(s.players.C!.faction).toBe('GOOD');expect(s.players.C!.presence).toBe('active');
});
it.each(['白魔術師シェリム','侍大将のシン','妖精王フューリー','聖騎士ランスロット','魔導王ガイナス','不死王ガドューラ'])('%s actual fixed-character death rejects conversion but ordinary allegiance revival remains legal',victim=>{
 let s=makeResurrectionPhysicalScenario('resurrection-dedicated',players,{victim});const faction=s.players.B!.faction;reject(s,'A',command('resurrection-dedicated',true));s=settle(act(s,'A',command('resurrection-dedicated')));expect(s.players.B).toMatchObject({presence:'active',faction,damage:0});
});
it.each(rows)('%s refuses living empty foreign ordinary-multiple and invalid conversion targets',scenario=>{
 let s=prepare(makeResurrectionPhysicalScenario(scenario,players),scenario);reject(s,'A',{...command(scenario),targetIds:['D']});reject(s,'A',{...command(scenario),targetIds:[]});reject(s,'A',{...command(scenario),targetIds:['B'],convertTargetIds:['C']});reject(s,'A',{...command(scenario),targetIds:['B','C'],dedicated:false});reject(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['D'],dedicated:scenario!=='resurrection-ordinary'});const foreign=prepare(makeResurrectionPhysicalScenario(scenario,players,{owner:'聖騎士ランスロット'}),scenario);reject(foreign,'A',{...command(scenario),dedicated:true});
});

it.each(['魔聖母ディア','餓狼ヨーツルム'])('%s actual GOOD conversion of Uonos forbids conditional target conversion but permits revival',victim=>{
 let s=makeResurrectionPhysicalScenario('resurrection-dedicated',players,{victim,sourceFaction:'GOOD'});expect(s.players.A).toMatchObject({faction:'GOOD',protection:{characterIds:['c2-p03-r1c2']}});expect(s.events.some(e=>e.type==='FACTION_CHANGED'&&e.actorId==='A')).toBe(true);reject(s,'A',command('resurrection-dedicated',true));s=settle(act(s,'A',command('resurrection-dedicated')));expect(s.players.B).toMatchObject({presence:'active',faction:'EVIL',damage:0});
});
it('actual current GOOD objective replaces a flexible target old protection with the source references',()=>{
 let s=makeResurrectionPhysicalScenario('resurrection-dedicated',players,{victim:'凍気のアイエル',sourceFaction:'GOOD'});const source=structuredClone(s.players.A!);expect(s.players.B!.protection).not.toEqual(source.protection);s=settle(act(s,'A',command('resurrection-dedicated',true)));expect(s.players.B).toMatchObject({presence:'active',faction:'GOOD',currentObjective:source.currentObjective,objective:source.objective,protection:source.protection});
});
it('actual Lia death ends the protected initial world before resurrection can be declared',()=>{
 const s=makeResurrectionPhysicalScenario('resurrection-dedicated',players,{victim:'リーア姫',terminal:true});expect(s.players.B!.presence).toBe('dead');expect(s.outcome).toBeDefined();expect(s.players.C!.presence).toBe('wandering');expect(s.players.D!.presence).toBe('wandering');reject(s,'A',command('resurrection-dedicated',true));expect(transition(s,{actorId:'A',command:command('resurrection-dedicated')},entropy())).toMatchObject({ok:false,code:'GAME_COMPLETE'});
});
