import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeRevelationPhysicalScenario,revelationTarget,type RevelationPhysicalScenario} from '../../../apps/worker/test/fixtures/revelation-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p02-r1c2';
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s);}throw Error('REVELATION_WINDOW');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function play(s:GameState,target='B'){if(s.windows?.length)s=until(s,s=>viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId===target));const o=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId===target)!;return act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:target});}
function next(s:GameState,target:string,phase='action'){for(let n=0;n<300;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(!w&&id===target&&s.phase===phase)return s;if(w)s=pass(s);else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('REVELATION_PHASE');}throw Error('REVELATION_TURN');}
function snapshot(s:GameState,id:string){const p=s.players[id]!;return (['hand','followers','chants'] as const).flatMap<{zone:'hand'|'followers'|'chants';position:number;cardInstanceId:string}>(zone=>zone==='hand'?p.hand.map((cardInstanceId,position)=>({zone,position,cardInstanceId})):p[zone].map((c,position)=>({zone,position,cardInstanceId:c.cardInstanceId})));}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['revelation-zones','revelation-self','revelation-hand','revelation-combat','revelation-history','revelation-pass','revelation-evil'] as const)('%s actual Revelation snapshots all present zones privately and preserves positions faces and cards after acknowledgement',name=>{
 let s=makeRevelationPhysicalScenario(name,players);const target=players[revelationTarget(name)]!.id,hand=s.players.D!.hand.length;
 if(name==='revelation-combat')s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['C'],dedicated:false});
 s=play(s,target);expect(s.players.D!.hand).toHaveLength(hand);const original=structuredClone(s.players[target]!),expected=snapshot(s,target),publics=s.seatOrder.map(id=>viewFor(s,id).players[target]);s=until(s,s=>!!viewFor(s,'D').inspection);const d=viewFor(s,'D').inspection!;expect(d).toMatchObject({actorId:'D',targetId:target,zone:'all',cards:expected,choices:['finish'],discardMode:'none'});expect(d).not.toHaveProperty('characterId');expect(s.seatOrder.map(id=>viewFor(s,id).players[target])).toEqual(publics);
 for(const id of ['A','B','C']){const v=viewFor(s,id);expect(v.inspection).toBeNull();expect(v.inspectionHistory).toEqual([]);if(id!==target)for(const c of expected)expect(JSON.stringify(v)).not.toContain(c.cardInstanceId);}
 expect(viewFor(s,target).self.hand).toEqual(original.hand);expect(s.events.filter(e=>e.audience==='public').some(e=>expected.some(c=>JSON.stringify(e).includes(c.cardInstanceId)))).toBe(false);
 const history=structuredClone(viewFor(s,'D').inspectionHistory);expect(history).toEqual([d]);s=name==='revelation-pass'?act(s,'D',{type:'PASS'}):act(s,'D',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});s=settle(s);expect(s.players[target]).toEqual(original);expect(viewFor(s,'D').inspection).toBeNull();expect(viewFor(s,'D').inspectionHistory).toEqual(history);expect(s.discard.filter(id=>id===card)).toHaveLength(1);expect(s.resolution).toEqual([]);
 if(name==='revelation-combat'){expect(s.players.C!.damage).toBe(4);expect(s.players.A!.hand).not.toContain('a2-p24-r1c2');}
 if(name==='revelation-history'){s=next(s,'B','draw');const before=[...s.players.B!.hand];s=settle(act(s,'B',{type:'CHOOSE_DRAW',draw:true}));const fresh=s.players.B!.hand.filter(id=>!before.includes(id));expect(fresh).toHaveLength(1);expect(viewFor(s,'D').inspectionHistory).toEqual(history);expect(JSON.stringify(viewFor(s,'D'))).not.toContain(fresh[0]);expect(s.players.B!.followers).toEqual(original.followers);expect(s.players.B!.chants).toEqual(original.chants);}
});
it('actual Fate cancellation of Revelation retains refill but no inspection or history',()=>{let s=makeRevelationPhysicalScenario('revelation-canceled',players),original=structuredClone(s.players.B!),hand=s.players.D!.hand.length;s=play(s);const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='C');s=settle(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}));expect(s.players.B).toEqual(original);expect(s.players.D!.hand).toHaveLength(hand);expect(s.phase).toBe('action');for(const id of s.seatOrder){expect(viewFor(s,id).inspection).toBeNull();expect(viewFor(s,id).inspectionHistory).toEqual([]);}expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual Rift otherworld target with real possessions is excluded from Revelation without card cost',()=>{const s=makeRevelationPhysicalScenario('revelation-otherworld',players);expect(s.players.B!.presence).toBe('otherworld');expect(s.players.B!.followers.length).toBeGreaterThan(0);expect(s.players.B!.chants.length).toBeGreaterThan(0);expect(viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId==='B')).toBe(false);const o=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===card)!;expect(o).toBeDefined();reject(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:'B'});expect(s.players.D!.hand).toContain(card);});
it('actual Revelation rejects foreign stale malformed targeting and discard or reorder inspection choices unchanged',()=>{let s=makeRevelationPhysicalScenario('revelation-zones',players);const o=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId==='B')!;for(const [id,targetId,targetEventId] of [['C','B',o.targetEventId],['D','B','stale'],['D','missing',o.targetEventId]])reject(s,id!,{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId,targetId});s=until(play(s),s=>!!viewFor(s,'D').inspection);const d=viewFor(s,'D').inspection!;for(const id of ['A','B','C'])reject(s,id,{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});for(const choice of ['discard-one','discard-all','reorder'])reject(s,'D',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice,cardInstanceId:d.cards[0]!.cardInstanceId});reject(s,'D',{type:'CHOOSE_INSPECTION',decisionId:'stale',choice:'finish'});s=settle(act(s,'D',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'}));reject(s,'D',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});});
it('actual optional Revelation decline leaves the hidden zones untouched and no history',()=>{let s=makeRevelationPhysicalScenario('revelation-zones',players),original=structuredClone(s.players.B!);expect(viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId===card)).toBe(true);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.B).toEqual(original);expect(s.players.D!.hand).toContain(card);expect(viewFor(s,'D').inspectionHistory).toEqual([]);});
