import {expect,it} from 'vitest';
import {getCharacter} from '@madou/catalog';
import {viewFor,transition,gameStats,type GameState, discardIds } from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeRitualPhysicalScenario,ritualCard} from './fixtures/ritual-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s);}throw Error('RITUAL_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
const use={type:'USE_REVIVAL_RITUAL'} as const,gift={type:'TRANSFER_RITUAL',targetId:'A'} as const;
it.each(['ritual-basic','ritual-subordinates','ritual-conspiracy','ritual-both'] as const)('%s actual Uonos main becomes public full-health Vanmil and preserves real prior possessions and use history before optional seat-ordered reactions',name=>{
 let s=makeRitualPhysicalScenario(name,players);const before=structuredClone(s.players.A!),used=[...s.used!],distances=structuredClone(s.distances),deck=[...s.deck],rolls=s.rolls?.length??0;
 expect(before.damage).toBe(3);expect(before.attachments).toContain('a2-p03-r3c1');expect(before.followers.map(f=>f.cardInstanceId)).toContain('a2-p21-r2c2');expect(used.some(k=>k.includes('c2-p05-r1c1-ab01'))).toBe(true);
 s=act(s,'A',use);expect(s.players.A!.hand).toEqual(before.hand.filter(id=>id!==ritualCard));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(ritualCard);expect(s.players.A!.characterId).toBe('c2-p05-r1c1');expect(s.windows!.at(-1)!.participants[0]).toBe('A');reject(s,'A',use);
 s=until(s,s=>s.windows?.at(-1)?.kind==='lifecycle-boundary');const boundary=s.windows!.at(-1)!;expect(boundary.participants[boundary.cursor]).toBe('A');expect(s.players.A).toMatchObject({characterId:'c2-p07-r1c2',revealed:true,damage:0,faction:'ヴァンミール',objective:getCharacter('c2-p07-r1c2')!.objective,abilityCharacterIds:['c2-p07-r1c2']});expect(gameStats(s,'A').endurance).toBe(25);expect(s.players.A!.protection).toEqual({characterIds:[]});
 for(const key of ['followers','attachments','open','chants','permanent'] as const)expect(s.players.A![key]).toEqual(before[key]);expect(s.distances).toEqual(distances);expect(s.used).toEqual(expect.arrayContaining(used));expect(s.rolls?.length??0).toBe(rolls);expect(s.outcome).toBeUndefined();expect(s.players.B!.faction).toBe('EVIL');expect(s.players.D!.faction).toBe('EVIL');
 for(const actor of s.seatOrder)expect(viewFor(s,actor).players.A).toMatchObject({characterId:'c2-p07-r1c2',revealed:true});expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId.startsWith('c2-p05-r1c1'))).toBe(false);reject(s,'C',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'});
 const sub=name==='ritual-subordinates'||name==='ritual-both',conspiracy=name==='ritual-conspiracy'||name==='ritual-both';
 if(sub){s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'});s=until(s,s=>s.windows?.at(-1)?.id===boundary.id);expect(viewFor(s,'A').lifecycleAbilities).not.toContain('vanmil-subordinates');}
 s=until(s,s=>s.windows?.at(-1)?.participants[s.windows.at(-1)!.cursor]==='C');expect(s.outcome).toBeUndefined();expect(viewFor(s,'C').lifecycleAbilities).toContain('arseil-conspiracy');
 if(conspiracy)s=act(s,'C',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'});s=settle(s);
 for(const id of ['B','D']){expect(s.players[id]!.faction).toBe(sub?'ヴァンミール':'EVIL');if(sub)expect(s.players[id]!.protection).toEqual({characterIds:['c2-p07-r1c2']});}
 expect(s.players.C!.presence).toBe(conspiracy?'exited':'active');expect(s.individualResults?.C).toBe(conspiracy?'won':undefined);expect(discardIds(s).filter(id=>id===ritualCard)).toHaveLength(1);expect(s.resolution).toEqual([]);expect(s.phase).toBe('hand-adjustment');expect(s.outcome).toBeUndefined();expect(s.players.A!.hand).toEqual(before.hand.filter(id=>id!==ritualCard));
});
it('ritual-fate actual cancel consumes the physical source and main without transformation or awakening boundary',()=>{let s=makeRitualPhysicalScenario('ritual-fate',players);const before=structuredClone(s.players.A!);s=act(s,'A',use);const id=Object.values(s.actions!).find(a=>a.cardInstanceId===ritualCard)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetActionId:id});s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.A).toEqual({...before,hand:before.hand.filter(id=>id!==ritualCard)});expect(discardIds(s)).toContain(ritualCard);expect(s.phase).toBe('hand-adjustment');expect(viewFor(s,'A').lifecycleAbilities).not.toContain('vanmil-subordinates');});
it('ritual-decline actual setup start draw other-seat and already-spent-main refuse unchanged state and all views',()=>{let s=makeRitualPhysicalScenario('ritual-decline',players,true);reject(s,'A',use);s=act(s,'A',{type:'START_TURN'});reject(s,'A',use);s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'B',use);s=act(s,'A',{type:'PASS_ACTION'});reject(s,'A',use);expect(s.players.A!.hand).toContain(ritualCard);});
it('ritual-wrong-owner actual non-Uonos owner cannot use and non-Dia owner cannot give even after public recipient reveal',()=>{let s=makeRitualPhysicalScenario('ritual-wrong-owner',players);s=settle(act(s,'A',{type:'REVEAL_CHARACTER'}));reject(s,'C',gift);reject(s,'A',use);s=settle(act(s,'A',{type:'PASS_ACTION'}));s=act(s,'A',{type:'END_TURN',discardIds:[]});s=act(s,'B',{type:'START_TURN'});s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});s=act(s,'B',{type:'PASS_ACTION'});s=act(s,'B',{type:'END_TURN',discardIds:[]});s=act(s,'C',{type:'START_TURN'});s=act(s,'C',{type:'CHOOSE_DRAW',draw:false});reject(s,'C',use);expect(s.players.C!.hand).toContain(ritualCard);});
it.each(['ritual-gift-hidden','ritual-gift-public','ritual-gift-start','ritual-gift-draw','ritual-gift-end','ritual-gift-window','ritual-gift-suppressed'] as const)('%s actual Dia hand transfer is atomic private physical movement with no reveal refill consumption or cancelable action',name=>{
 let s=makeRitualPhysicalScenario(name,players);const before=structuredClone(s),a=[...s.players.A!.hand],b=[...s.players.B!.hand];if(name==='ritual-gift-suppressed')expect(s.players.B!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);
 expect(viewFor(s,'B').legalChoices).toContain('TRANSFER_RITUAL');reject(s,'B',{...gift,targetId:'B'});reject(s,'B',{...gift,targetId:'C'});reject(s,'B',{...gift,targetId:'missing'});s=act(s,'B',gift);
 expect(s.players.A!.hand).toEqual([...a,ritualCard]);expect(s.players.B!.hand).toEqual(b.filter(id=>id!==ritualCard));expect(s.players.B!.revealed).toBe(before.players.B!.revealed);expect(s.players.A!.characterId).toBe('c2-p05-r1c1');expect(s.deck).toEqual(before.deck);expect(discardIds(s)).toEqual(discardIds(before));expect(s.resolution).toEqual(before.resolution);expect(s.actions).toEqual(before.actions);expect(s.windows?.map(w=>w.id)).toEqual(before.windows?.map(w=>w.id));expect(s.phase).toBe(before.phase);
 const events=s.events.slice(before.events.length).filter(e=>e.type==='CARD_GIFTED');expect(events).toHaveLength(3);expect(events.find(e=>e.audience==='public')).not.toHaveProperty('cardInstanceId');for(const actor of ['A','B'])expect(events.find(e=>typeof e.audience==='object'&&e.audience.playerId===actor)).toHaveProperty('cardInstanceId',ritualCard);
 reject(s,'B',gift);for(const mode of ['cancel','cancel-ability'])reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode,targetActionId:'ritual-transfer'});
 if(name==='ritual-gift-window'){expect(s.windows!.at(-1)!.eventId).toBe(before.windows!.at(-1)!.eventId);s=settle(s);}if(s.phase==='action'){s=settle(act(s,'A',use));expect(s.players.A!.characterId).toBe('c2-p07-r1c2');expect(discardIds(s).filter(id=>id===ritualCard)).toHaveLength(1);}
});
it.each(['ritual-gift-stopped','ritual-gift-hidden-target','ritual-gift-dead-target'] as const)('%s actual stopped giver or hidden dead recipient prevents transfer and retains the hand card in every view',name=>{let s=makeRitualPhysicalScenario(name,players);if(name==='ritual-gift-stopped')expect(s.players.B!.statuses?.some(x=>x.kind==='stopped')).toBe(true);else if(name==='ritual-gift-dead-target'){expect(s.players.A!.presence).toBe('dead');expect(s.players.A!.revealed).toBe(true);}else expect(s.players.A!.revealed).toBe(false);reject(s,'B',gift);expect(s.players.B!.hand).toContain(ritualCard);if(name==='ritual-gift-hidden-target'){s=settle(act(s,'A',{type:'REVEAL_CHARACTER'}));s=act(s,'B',gift);expect(s.players.A!.hand).toContain(ritualCard);}});
it('ritual-gift-window actual pending responder owns priority and an unrelated seat cannot transfer early',()=>{let s=makeRitualPhysicalScenario('ritual-gift-hidden',players);const option=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p05-r1c1-ab01')!;s=act(s,'A',{type:'USE_ABILITY',abilityId:option.abilityId,targetEventId:option.targetEventId,targetId:'C'});const w=s.windows!.at(-1)!;if(w.participants[w.cursor]==='B')s=pass(s);reject(s,'B',gift);});
