import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeRoyalKnightsPhysicalScenario,royalKnightsPhysicalMode,type RoyalKnightsPhysicalScenario} from './fixtures/royal-knights-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['royal-knights-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ROYAL_KNIGHTS_TURN');}throw Error('ROYAL_KNIGHTS_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r1c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);let s=makeRoyalKnightsPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);let s=ready(makeRoyalKnightsPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeRoyalKnightsPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeRoyalKnightsPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.B!.damage).toBe(level===4?18:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);let s=until(incoming(ready(makeRoyalKnightsPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeRoyalKnightsPhysicalScenario(scenario,players,{owner:'魔聖母ディア'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});

const ROYAL='a2-p21-r1c2',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
function reflected(s:GameState){for(let n=0;n<150;n++){const a=Object.values(s.actions??{}).find(a=>a.kind==='follower-reflection');if(a&&s.windows?.at(-1)?.kind==='normal-defense')return s;s=pass(s);}throw Error('NO_ROYAL_REFLECTION');}
it.each(['pass','fail'] as const)('actual Royal Knights morale %s at spirit6 precedes every reflected Dwarf4 hit and rolls only once',mode=>{
 let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-setup',players,{spirit:6}),ROYAL);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',rollerId:'A',modifier:0,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual(mode==='pass'?[0,18]:[18,0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(mode==='pass'?[ROYAL]:[]);expect(s.discard.filter(id=>id===ROYAL)).toHaveLength(mode==='pass'?0:1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual Royal Knights explicit Lia waiver permits reflection at spirit zero while omitted and foreign selections do not',()=>{
 for(const selected of [false,true]){let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-waive',players),ROYAL);s=until(dwarf(s),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toContainEqual({cardInstanceId:ROYAL});reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[ROYAL,ROYAL]});s=finish(act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:selected?[ROYAL]:[]}));expect([s.players.A!.damage,s.players.B!.damage]).toEqual(selected?[0,18]:[18,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(selected?0:1);}
 let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-setup',players,{owner:'竜皇子アスフェルト'}),ROYAL);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[ROYAL]});
});
it.each([false,true])('actual Royal Knights reflected hit preserves fixed technique and lineage grants original attacker new maai=%s defense without paying source',maai=>{
 let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-setup',players),ROYAL);s=reflected(incoming(s));const a=Object.values(s.actions!).find(a=>a.kind==='follower-reflection')!;expect(a).toMatchObject({actorId:'A',targetIds:['B'],cardInstanceId:ROYAL,checks:[],fixedReceivedEffect:true,lineage:[ROYAL],technique:{range:'far',school:'warrior',useLevel:3,effectLevel:3,damage:4}});expect(s.resolution).not.toContain(ROYAL);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:ROYAL,revealed:true}));if(maai)s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,maai?0:4]);expect(s.discard).not.toContain(ROYAL);
});
it('actual Royal Knights unreached rear remains hidden without morale and surviving source checks anew next group',()=>{
 let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-setup',players),ROYAL);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,22]);
 let q=ready(makeRoyalKnightsPhysicalScenario('royal-knights-setup',players,{spirit:0}),ROYAL,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',ROYAL]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each(['royal-knights-counterban','royal-knights-ignore'] as const)('%s actual selected Gadyura attack reflects only reached local hit even with counter prohibition',scenario=>{
 const m=royalKnightsPhysicalMode(scenario),card=m.counterban?'a2-p19-r2c1':'a2-p21-r1c1';let s=next(ready(makeRoyalKnightsPhysicalScenario(scenario,players),ROYAL));s=act(s,'B',{type:'ATTACK',cardInstanceId:card,targetIds:['A','C'],dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;expect(a.technique).toMatchObject(m.counterban?{counterProhibited:true,effectLevel:2,damage:2}:{followerIgnore:true,effectLevel:4,damage:5});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual(m.counterban?[0,2,2]:[5,0,5]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.counterban?1:0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:ROYAL,revealed:m.counterban}));expect(s.discard).not.toContain(ROYAL);
});
it.each(['royal-knights-ded-hand','royal-knights-ded-field','royal-knights-grant-hand','royal-knights-grant-field','royal-knights-army'] as const)('%s actual allowed ordinary or Lia bottom is near warrior sword4damage5 single target with use checks retained',scenario=>{
 const m=royalKnightsPhysicalMode(scenario);for(const warrior of [3,4]){let s=ready(makeRoyalKnightsPhysicalScenario(scenario,players,{warrior}),ROYAL,m.initial);const command=()=>m.army?{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:ROYAL,targetIds:['B']}:m.grant?grant(s):{type:'ATTACK',cardInstanceId:ROYAL,targetIds:['B'],dedicated:true};if(m.grant)expect(viewFor(s,'A').followerBundleOptions).toEqual([]);else reject(s,'A',command());s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));if(m.dedicated)reject(s,'A',{type:'ATTACK',cardInstanceId:ROYAL,targetIds:['B','C'],dedicated:true});s=act(s,'A',command());const a=Object.values(s.actions!).find(a=>a.cardInstanceId===ROYAL)!;expect(a.checks).toHaveLength(4-warrior);expect(a.technique).toMatchObject({range:'near',school:'warrior',useLevel:4,effectLevel:4,damage:5,hitCount:1,attributes:['近','戦','剣'],target:'one',noChecks:false});expect(a.technique.counterProhibited??false).toBe(false);expect(s.resolution).toContain(ROYAL);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([5,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===ROYAL)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it('actual Royal Knights placed source cannot be paid through hand-only Army',()=>{let s=ready(makeRoyalKnightsPhysicalScenario('royal-knights-army',players),ROYAL);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===ROYAL)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:ROYAL,targetIds:['B']});});
it.each(['hand','field','army-parent','army-child','army-morale','use'] as const)('actual Royal Knights %s cancellation or failed roll discards paid source once without returning it',mode=>{
 const army=mode.startsWith('army');let s=ready(makeRoyalKnightsPhysicalScenario(army?'royal-knights-army':mode==='field'?'royal-knights-ded-field':'royal-knights-ded-hand',players,{warrior:3}),ROYAL,mode==='field');s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',army?{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:ROYAL,targetIds:['B']}:{type:'ATTACK',cardInstanceId:ROYAL,targetIds:['B'],dedicated:true});if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='use'){s=until(s,'before-roll');expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:ROYAL))!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='army-morale'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(ROYAL);for(const id of army?[ROYAL,ARMY]:[ROYAL])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});

it.each([[4,false],[5,false],[4,true]] as const)('actual Royal Knights reflects magic%i with returning Mirror=%s and same physical source cannot reflect twice in one lineage', (level,mirror)=>{
 let s=makeRoyalKnightsPhysicalScenario('royal-knights-setup',players);
 // These are initial deal conditions, before any accepted command or placement.
 const card=level===4?'a2-p17-r2c1':'a2-p17-r2c2',old='a2-p07-r1c2';
 for(const p of Object.values(s.players))p.hand=p.hand.filter(id=>id!==card);
 s.deck=s.deck.filter(id=>id!==card);s.discard=s.discard.filter(id=>id!==card);
 s.players.B!.hand=s.players.B!.hand.filter(id=>id!==old);s.deck.push(old);s.players.B!.hand.push(card);
 const cursors:Record<string,number>={};s.events=s.events.flatMap(e=>{if(e.type!=='CARD_DRAWN')return[e];const i=cursors[e.actorId]??0;cursors[e.actorId]=i+1;const id=s.players[e.actorId]!.hand[i];return id?[{...e,cardInstanceId:id}]:[];});
 s=next(ready(s,ROYAL));s=act(s,'B',{type:'ATTACK',cardInstanceId:card,targetIds:['A'],dedicated:false});
 const reflectedIds=new Set<string>();let returned=false;
 for(let n=0;n<300&&s.windows?.length;n++){
  for(const a of Object.values(s.actions??{}))if(a.kind==='follower-reflection'){reflectedIds.add(a.id);expect(a.lineage).toEqual([ROYAL]);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:4,effectLevel:4,damage:5});expect(a.checks).toEqual([]);}
  const current=viewFor(s,'B').currentAction,w=s.windows!.at(-1)!;
  if(mirror&&!returned&&current?.kind==='follower-reflection'&&w.kind==='normal-defense'){s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});returned=true;}else s=pass(s);
 }
 expect(s.windows??[]).toEqual([]);expect(reflectedIds.size).toBe(level===4?1:0);expect(returned).toBe(mirror);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,level===4&&!mirror?5:0]);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(level===4?[ROYAL]:[]);expect(s.discard.filter(id=>id===ROYAL)).toHaveLength(level===4?0:1);expect(s.discard.filter(id=>id===card)).toHaveLength(1);
});
