import {getAction} from '@madou/catalog';
import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,ready,finish,pass,until,closeWindow} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
const LOVE='c2-p05-r1c2-ab05';
function setup(){const s=ready();character(s,'B','黒妖精のアーネス');character(s,'C','獣使いのウパニシャット');character(s,'D','破壊神ヴァンミール');s.players.D!.revealed=true;for(const p of Object.values(s.players))p.permanent={endurance:100};handCard(s,'D','命運凶変');for(const name of ['閃光槍','見切る','間合い／休息'])handCard(s,'C',name);return s;}
function aura(s:GameState,enabled=true){const v=viewFor(s,'C').sadLove!;return act(s,'C',{type:'USE_ABILITY',abilityId:LOVE,mode:'aura',enabled,targetEventId:v.targetEventId!});}
function incoming(lethal=false){let s=setup();s.players.B!.revealed=true;if(lethal)s.players.C!.damage=gameStats(s,'C').endurance-1;const card=handCard(s,'A','手裏剣');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'attack-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='C')s=pass(s);return s;}
function substitute(s:GameState){const o=viewFor(s,'C').sadLove!.substitutions[0]!;expect(o).toBeDefined();return act(s,'C',{type:'USE_ABILITY',abilityId:LOVE,mode:'substitute',...o});}
it('Sad love explicit aura waits for public Arnes and turns off independently',()=>{let s=setup();const spirit=gameStats(s,'C').spirit;expect(viewFor(s,'C').sadLove!.auraEnabled).toBe(false);s=finish(aura(s));expect(gameStats(s,'C').spirit).toBe(spirit);s=act(s,'B',{type:'REVEAL_CHARACTER'});expect(gameStats(s,'C').spirit).toBe(spirit+1);s=aura(s,false);expect(gameStats(s,'C').spirit).toBe(spirit);expect(viewFor(s,'C').sadLove!.substitutionSpent).toBe(false);});
it('Sad love actual substitution redirects one hit into Upa with no physical payment',()=>{let s=incoming();const hand=[...s.players.C!.hand];s=finish(substitute(s));expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(5);expect(s.players.C!.hand).toEqual(hand);expect(viewFor(s,'C').sadLove!.substitutionSpent).toBe(true);});
it('Sad love grants Arnes permanent spirit only after the attributable actual death',()=>{let s=incoming(true);const spirit=gameStats(s,'B').spirit;s=until(substitute(s),'death-gift');expect(gameStats(s,'B').spirit).toBe(spirit);s=finish(s);expect(s.players.C!.presence).toBe('dead');expect(gameStats(s,'B').spirit).toBe(spirit+1);expect(s.players.B!.sadLoveRewardIds).toHaveLength(1);});
function priority(s:GameState,actor='D'){for(let n=0;n<80;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('LOVE_PRIORITY');}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
function cancel(s:GameState){s=priority(s);return act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:viewFor(s,'D').reactionTargetAbilityId!});}
it('Declining sad love leaves the original target and spends neither aura nor substitution',()=>{const s=finish(incoming());expect(s.players.B!.damage).toBe(5);expect(s.players.C!.damage).toBe(0);expect(viewFor(s,'C').sadLove).toMatchObject({auraEnabled:false,substitutionSpent:false});});
it('Canceled substitution spends the once-game attempt and leaves the hit with Arnes',()=>{
 let s=incoming();const o=viewFor(s,'C').sadLove!.substitutions[0]!;s=cancel(substitute(s));s=until(s,'attack-abilities');s=priority(s,'C');expect(viewFor(s,'C').sadLove!.substitutions).toEqual([]);reject(s,'C',{type:'USE_ABILITY',abilityId:LOVE,mode:'substitute',...o});s=finish(s);expect(s.players.B!.damage).toBe(5);expect(s.players.C!.damage).toBe(0);
});
it('Canceled aura adds nothing and leaves the independent substitution attempt unused',()=>{let s=setup();s.players.B!.revealed=true;const spirit=gameStats(s,'C').spirit;s=finish(cancel(aura(s)));expect(gameStats(s,'C').spirit).toBe(spirit);expect(viewFor(s,'C').sadLove).toMatchObject({auraEnabled:false,canActivate:false,substitutionSpent:false});});
it('Substitution rejects wrong target, wrong hit, foreign actor and late finalized source immutably',()=>{
 let s=incoming();const o=viewFor(s,'C').sadLove!.substitutions[0]!,command={type:'USE_ABILITY',abilityId:LOVE,mode:'substitute',...o};for(const changed of [{targetId:'A'},{groupId:'g-missing'},{hitIndex:5},{targetEventId:'a-missing'}])reject(s,'C',{...command,...changed});reject(s,'B',command);s=finish(s);reject(s,'C',command);expect(s.players.C!.sadLoveSubstitutionSpent).toBeUndefined();
});
it('Substitution retains A13 restrictions and permits a real hand counter',()=>{
 let s=until(substitute(incoming()),'normal-defense');const hand=s.players.C!.hand;for(const command of [{type:'PLAY_DEFENSE',cardInstanceId:handCardId(s,'見切る'),dedicated:false},{type:'PLAY_MAAI',cardInstanceId:handCardId(s,'間合い／休息')},{type:'START_FOLLOWERS'}])reject(s,'C',command);expect(viewFor(s,'C').legalChoices).not.toContain('START_FOLLOWERS');expect(viewFor(s,'C').sadLove!.substitutions).toEqual([]);
 const spirit=gameStats(s,'C').spirit;s=closeWindow(aura(s));expect(gameStats(s,'C').spirit).toBe(spirit+1);
 s=finish(act(s,'C',{type:'PLAY_DEFENSE',cardInstanceId:handCardId(s,'閃光槍'),dedicated:false}));expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([5,0,0]);
});
function handCardId(s:GameState,name:string){return s.players.C!.hand.find(id=>getAction(id)!.name===name)!;}
it('Actual Vanmil ban before substitution resolution spends the attempt without redirection',()=>{let s=priority(substitute(incoming()));const o=viewFor(s,'D').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=finish(act(s,'D',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,targetIds:['C']}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([5,0]);expect(viewFor(s,'C').sadLove!.substitutionSpent).toBe(true);});
it('Aura can be disabled while actually suppressed without erasing its attempt history',()=>{
 let s=setup();s.players.B!.revealed=true;const base=gameStats(s,'C').spirit;s=finish(aura(s));const card=handCard(s,'A','手裏剣');s=priority(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}));const o=viewFor(s,'D').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=closeWindow(act(s,'D',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,targetIds:['C']}));s=priority(s,'C');expect(gameStats(s,'C').spirit).toBe(base);expect(viewFor(s,'C').sadLove).toMatchObject({auraEnabled:true,canActivate:false,canDeactivate:true});s=aura(s,false);expect(s.players.C!.sadLoveAura).toBeUndefined();
});
it('Unused sad love details are projected only to the owning seat',()=>{const s=incoming();expect(viewFor(s,'C').sadLove!.substitutions).toHaveLength(1);for(const id of ['A','B','D']){expect(viewFor(s,id).sadLove).toBeNull();expect(JSON.stringify(viewFor(s,id))).not.toContain(LOVE);}});
it('The aura public-Arnes condition is not added to the separate actual substitution',()=>{let s=setup();const card=handCard(s,'A','手裏剣');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}),'attack-abilities');s=priority(s,'C');s=finish(substitute(s));expect(s.players.B!.revealed).toBe(false);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,5]);});
it('The saved aura resumes after actual Vanmil suppression and actual Lia blessing',()=>{
 let s=setup();character(s,'A','リーア姫');s.players.A!.revealed=true;s.players.B!.revealed=true;const base=gameStats(s,'C').spirit;s=finish(aura(s));const card=handCard(s,'A','手裏剣');s=priority(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false}));const ban=viewFor(s,'D').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=closeWindow(act(s,'D',{type:'USE_ABILITY',abilityId:ban.abilityId,targetEventId:ban.targetEventId,targetIds:['C']}));expect(gameStats(s,'C').spirit).toBe(base);expect(s.players.C!.sadLoveAura).toBeDefined();s=priority(s,'A');const blessing=viewFor(s,'A').abilityOptions.find(o=>o.abilityId==='c2-p03-r1c2-ab04')!;expect(blessing).toBeDefined();s=finish(act(s,'A',{type:'USE_ABILITY',abilityId:blessing.abilityId,targetEventId:blessing.targetEventId,targetId:'C'}));expect(gameStats(s,'C').spirit).toBe(base+1);expect(viewFor(s,'C').sadLove!.auraEnabled).toBe(true);
});
it('Saved aura pauses during temporary absence and returns with its selection (structural presence boundary)',()=>{
 let s=setup();s.players.B!.revealed=true;const base=gameStats(s,'C').spirit;s=finish(aura(s));for(const presence of ['wandering','otherworld'] as const){s.players.C!.presence=presence;expect(gameStats(s,'C').spirit).toBe(base);expect(viewFor(s,'C').sadLove).toMatchObject({auraEnabled:true,canActivate:false,canDeactivate:false});s.players.C!.presence='active';expect(gameStats(s,'C').spirit).toBe(base+1);}
});
it('A real ban after redirection cannot revoke the saved death reward for suppressed Arnes',()=>{
 let s=until(substitute(incoming(true)),'hit');const base=gameStats(s,'B').spirit;s=priority(s);const o=viewFor(s,'D').abilityOptions.find(o=>o.abilityId==='c2-p07-r1c2-ab03')!;s=finish(act(s,'D',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,targetIds:['B','C']}));expect(s.players.C!.presence).toBe('dead');expect(gameStats(s,'B').spirit).toBe(base+1);expect(s.players.B!.sadLoveRewardIds).toHaveLength(1);
});
it('An unrelated actual Upa death does not grant the substitution reward',()=>{let s=setup();s.players.C!.damage=gameStats(s,'C').endurance-1;const base=gameStats(s,'B').spirit,card=handCard(s,'A','手裏剣');s=finish(act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['C'],dedicated:false}));expect(s.players.C!.presence).toBe('dead');expect(gameStats(s,'B').spirit).toBe(base);expect(s.players.B!.sadLoveRewardIds).toBeUndefined();});
function nextOwn(s:GameState,owner:string){for(let n=0;n<40;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='action'){if(actor===owner)return s;s=act(s,actor,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=finish(act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.filter(id=>id!=='a2-p13-r3c1').slice(0,Math.max(0,s.players[actor]!.hand.length-gameStats(s,actor).handLimit))}));else if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else throw Error(`LOVE_TURN_${s.phase}`);}throw Error('LOVE_TURN_LIMIT');}
it('Actual two-target three-hit attack preserves the death reward through concurrent Arnes death and real revival',()=>{
 let s=setup();character(s,'D','邪祭ウーノス');s.players.B!.revealed=true;const sword=handCard(s,'A','天地百撃斬'),revive=handCard(s,'D',getAction('a2-p13-r3c1')!.name);s.players.B!.damage=gameStats(s,'B').endurance-1;s.players.C!.damage=gameStats(s,'C').endurance-1;const base=gameStats(s,'B').spirit;
 // Only the initial fixture arranges subsequent draws; all death and revival transitions below are real.
 s.deck=[...s.deck.filter(id=>getAction(id)!.category!=='open'),...s.deck.filter(id=>getAction(id)!.category==='open')];s=finish(aura(s));expect(gameStats(s,'C').spirit).toBeGreaterThan(0);s=act(s,'A',{type:'CHANT',cardInstanceId:sword});s=nextOwn(s,'A');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:sword,targetIds:['B','C'],dedicated:true}),'damage');s=closeWindow(s,[3]);s=until(s,'attack-abilities');s=priority(s,'C');expect(viewFor(s,'C').sadLove!.substitutions).toHaveLength(3);s=until(substitute(s),'death-gift');expect(s.players.B!.presence).toBe('pending-death');expect(s.players.C!.presence).toBe('pending-death');expect(s.players.C!.sadLoveAura).toBeUndefined();s=finish(s);expect([s.players.B!.presence,s.players.C!.presence]).toEqual(['dead','dead']);expect(gameStats(s,'B').spirit).toBe(base+1);const rewards=[...s.players.B!.sadLoveRewardIds!];expect(rewards).toHaveLength(1);
 s=nextOwn(s,'D');const rolls=s.rolls?.length??0;s=until(act(s,'D',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:revive,targetIds:['B','C'],dedicated:true}),'re-setup');expect(s.rolls?.length??0).toBe(rolls);expect(gameStats(s,'B').spirit).toBe(base+1);expect(s.players.B!.sadLoveRewardIds).toEqual(rewards);s=act(s,'B',{type:'PASS_SETUP'});s=finish(act(s,'C',{type:'PASS_SETUP'}));expect(gameStats(s,'B').spirit).toBe(base+1);expect(viewFor(s,'C').sadLove).toMatchObject({auraEnabled:false,substitutionSpent:true});
});
