import {expect,it} from 'vitest';
import {transition,type GameState} from '../src/index.js';
import {getAction} from '@madou/catalog';
import {act,finish,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeR6BoundaryScenario} from './fixtures/r6-boundary-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const card=(s:GameState,owner:string,name:string)=>s.players[owner]!.hand.find(id=>getAction(id)!.name===name)!;
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s);}throw Error('S14_17_TEST_WINDOW');}
it('S14 actual initial follower entry closes owned normal defense but preserves C actual God intervention on its morale roll',()=>{let s=makeR6BoundaryScenario(players);const defense=card(s,'B','見切る'),before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:defense,dedicated:false}},entropy())).toEqual({ok:false,code:'DEFENSE_WINDOW_CLOSED'});expect(JSON.stringify(s)).toBe(before);s=until(s,s=>s.windows?.at(-1)?.kind==='after-roll'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='C');const roll=s.rolls!.at(-1)!;expect(roll.purpose).toBe('follower-morale');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:card(s,'C','神性介入'),mode:'reroll',targetRollId:roll.id});s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);expect(s.rolls!.at(-1)!.id).toBe(roll.id);s=finish(s);expect(s.players.B!.hand).toContain(defense);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(1);});
it('S17 real X Y reflection lineage refuses spent X and permits unused teleport without fabricating a physical recovery',()=>{let s=makeR6BoundaryScenario(players,true);const g=Object.values(s.groups!)[2]!,mirror=s.resolution.find(id=>getAction(id)!.name==='ミラーシールド')!,ice=s.resolution.find(id=>getAction(id)!.name==='氷鏡')!,teleport=card(s,'B','転移');expect(g.targets[0]!.hits[0]!.lineage).toEqual([mirror,ice]);const before=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);
 // Separate structural challenge isolates the lineage guard with X available; it is not a reclaim producer.
 const challenge=structuredClone(s);challenge.resolution=challenge.resolution.filter(id=>id!==mirror);challenge.players.B!.hand.push(mirror);const saved=JSON.stringify(challenge);expect(transition(challenge,{actorId:'B',command:{type:'PLAY_DEFENSE',cardInstanceId:mirror,dedicated:false}},entropy())).toEqual({ok:false,code:'ALREADY_USED'});expect(JSON.stringify(challenge)).toBe(saved);
 s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false});s=finish(s);expect(s.groups).toEqual({});expect(s.windows).toEqual([]);expect(s.players.A!.statuses??[]).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);for(const id of [mirror,ice,teleport])expect(s.discard.filter(x=>x===id)).toHaveLength(1);});
