import {expect,it} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {getAction} from '@madou/catalog';
import {act,finish,pass,until} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeR6DefenseScenario} from './fixtures/r6-defense-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const card=(s:GameState,name:string)=>s.players.B!.hand.find(id=>getAction(id)!.name===name)!;
const main=(s:GameState)=>Object.values(s.actions!).find(a=>a.kind==='attack')!;
function rejected(s:GameState,actorId:string,command:Parameters<typeof transition>[1]['command']){const before=JSON.stringify(s);expect(transition(s,{actorId,command},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
it('S06 actual level6 is frozen at normal defense and late Shin Spirit spends no hand ability attempt or roll',()=>{let s=makeR6DefenseScenario(players,'s06');const a=main(s),abilityId='c2-p01-r2c1-ab03',hand=[...s.players.A!.hand],used=[...s.used!],rolls=structuredClone(s.rolls);expect(a.technique.effectLevel).toBe(6);expect(a.modifiers!.effectFrozen).toBe(true);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===abilityId)).toBe(false);rejected(s,'A',{type:'USE_ABILITY',abilityId,targetEventId:a.eventId});expect(s.players.A!.hand).toEqual(hand);expect(s.used).toEqual(used);expect(s.rolls).toEqual(rolls);s=finish(s);expect(s.players.B!.damage).toBe(5);});
it('S08 real failed teleport cannot retry but a different actual counter is accepted before followers and returns damage',()=>{let s=makeR6DefenseScenario(players,'s08');const teleport=s.discard.find(id=>getAction(id)!.name==='転移')!,counter=card(s,'閃光槍');expect(teleport).toBeDefined();expect(s.rolls!.some(r=>r.faces.join(',')==='6,6'&&r.success===false)).toBe(true);rejected(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:teleport,dedicated:false});s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});s=finish(s);expect(s.players.A!.damage).toBe(5);expect(s.players.B!.damage).toBe(0);expect(s.discard).toEqual(expect.arrayContaining([teleport,counter]));expect(s.groups).toEqual({});});
it('S09 actual Asfelt level6 sword meets checked Garwin level6 counter and cancels only B hit with C intact',()=>{let s=makeR6DefenseScenario(players,'s09');expect(main(s).technique.effectLevel).toBe(6);const counter=card(s,'妖撃破山剣');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false,declarationAbilityIds:['c2-p05-r2c1-ab03']});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique.defense).toBe('counter');expect(defense.checks.length).toBeGreaterThan(0);s=until(s,'damage');expect(s.actions![defense.id]!.technique.effectLevel).toBe(6);s=until(s,'normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});const group=Object.values(s.groups!)[0]!;expect(group.targets[0]!.hits[0]!.defended).toBe(true);expect(group.technique.effectLevel).toBe(6);expect(group.targets[1]!.hits[0]).toMatchObject({damage:12,defended:false});expect(Object.values(s.groups!).some(g=>g.attackerId==='B')).toBe(false);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,12]);});
it('S10 actual far level5 attack and near counter plus real prayer2 freeze at level7 and block without returned damage',()=>{let s=makeR6DefenseScenario(players,'s10');expect(s.distances.A!.B).toBe('far');expect(main(s).technique.effectLevel).toBe(5);const counter=card(s,'妖撃破山剣'),prayer=card(s,'必勝の祈り');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});s=until(s,'effect-level');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const id=Object.values(s.actions!).find(a=>a.kind==='defense')!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:prayer,mode:'effect-plus',targetActionId:id});for(let n=0;n<300;n++){if(s.windows!.at(-1)?.kind==='damage'&&s.windows!.at(-1)!.continuation.id===id)break;s=pass(s,[2]);}expect(s.actions![id]!.technique).toMatchObject({effectLevel:7,range:'near'});expect(s.actions![id]!.modifiers!.effectFrozen).toBe(true);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,0]);expect(s.distances.A!.B).toBe('far');expect(s.groups).toEqual({});expect(s.discard).toEqual(expect.arrayContaining([counter,prayer]));});

it('Actual Asfelt level6 two-target sword meets checked level6 parry and cancels only B hit with C intact',()=>{let s=makeR6DefenseScenario(players,'s09-parry');expect(main(s).technique.effectLevel).toBe(6);const counter=card(s,'受け流し');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:false});const defense=Object.values(s.actions!).find(a=>a.kind==='defense')!;expect(defense.technique.effectLevel).toBe(6);expect(defense.checks.length).toBeGreaterThan(0);s=until(s,'normal-defense');expect(s.windows!.at(-1)!.continuation).toMatchObject({targetId:'C'});const group=Object.values(s.groups!)[0]!;expect(group.targets[0]!.hits[0]!.defended).toBe(true);expect(group.technique.effectLevel).toBe(6);expect(group.targets[1]!.hits[0]).toMatchObject({damage:12,defended:false});expect(Object.values(s.groups!).some(g=>g.attackerId==='B')).toBe(false);s=finish(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([0,0,12]);});
