import {expect,it} from 'vitest';
import {transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeR6RollScenario} from './fixtures/r6-roll-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=[4,4]){for(let n=0;n<300;n++){if(done(s))return s;s=pass(s,dice);}throw Error('S01_05_WINDOW');}
it('S01 S02 S05 D first is rejected at C priority then C force-fail resets the parent and D rerolls successful-valued faces without clearing failure',()=>{let s=makeR6RollScenario(players,true);const parent=structuredClone(s.windows!.at(-1)!),id=s.rolls!.at(-1)!.id;expect(parent).toMatchObject({cursor:2,passed:['A','B']});expect(s.rolls!.at(-1)).toMatchObject({faces:[2,3],success:true,threshold:9});const god={type:'PLAY_REACTION' as const,cardInstanceId:'a2-p02-r1c3',mode:'reroll' as const,targetRollId:id},before=JSON.stringify(s);expect(transition(s,{actorId:'D',command:god},entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});s=until(s,s=>s.windows?.at(-1)?.id===parent.id);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[2,3],forcedFailure:true,success:false});s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',god);s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[4,4],total:8,threshold:9,forcedFailure:true,success:false,generation:1});expect(s.rolls!.at(-1)!.attempts.map(a=>a.faces)).toEqual([[2,3],[4,4]]);s=finish(JSON.parse(JSON.stringify(s)));expect(s.players.B!.statuses).toHaveLength(1);expect(s.players.B!.damage).toBe(5);});
it('S03 B accepted God retains its paid replacement and used event after C Fate cancels it without a reroll or action refund',()=>{let s=makeR6RollScenario(players),parent=s.windows!.at(-1)!.id,id=s.rolls!.at(-1)!.id,hand=[...s.players.B!.hand],draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});expect(s.players.B!.hand).toHaveLength(hand.length);expect(s.players.B!.hand).not.toContain('a2-p02-r1c3');const replacement=s.players.B!.hand.find(id=>!hand.includes(id))!;expect(replacement).toBeDefined();expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);const child=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;expect(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]).toBe('C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});s=until(s,s=>s.windows?.at(-1)?.id===parent,[]);expect(s.rolls!.at(-1)).toMatchObject({id,faces:[2,3],generation:0});expect(s.rolls!.at(-1)!.attempts).toHaveLength(1);expect(s.players.B!.hand).toContain(replacement);expect(s.used!.some(key=>key.endsWith(':B:a2-p02-r1c3'))).toBe(true);expect(s.discard).toEqual(expect.arrayContaining(['a2-p02-r1c3','a2-p02-r2c3']));expect(s.turnSeat).toBe(0);s=finish(s);expect(s.phase).toBe('withdrawal');expect(s.players.B!.hand).toContain(replacement);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);});
it('S04 actual whole 2d6 reroll replaces 2,3 with 4,4 and keeps one stable roll identity and double result after JSON save',()=>{let s=makeR6RollScenario(players),id=s.rolls!.at(-1)!.id;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=until(s,s=>s.rolls!.at(-1)!.attempts.length===2);const roll=structuredClone(s.rolls!.at(-1)!);expect(roll).toMatchObject({id,faces:[4,4],total:8,success:true,generation:1});expect(roll.attempts.map(a=>a.faces)).toEqual([[2,3],[4,4]]);s=finish(JSON.parse(JSON.stringify(s)));expect(s.rolls!.find(r=>r.id===id)).toMatchObject({faces:[4,4],attempts:roll.attempts});expect(viewFor(s,'B').recentRolls.find(r=>r.rollId===id)).toMatchObject({faces:[4,4]});expect(s.players.B!.statuses??[]).toEqual([]);});

it('S02 actual C reroll canceled by D resets the A B passed parent without changing its roll',()=>{
 let s=makeR6RollScenario(players,true,true);const parent=structuredClone(s.windows!.at(-1)!),roll=structuredClone(s.rolls!.at(-1)!);
 expect(parent).toMatchObject({cursor:2,passed:['A','B']});
 s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:roll.id});
 const child=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p02-r1c3')!;
 s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});
 s=until(s,s=>s.windows?.at(-1)?.id===parent.id,[]);
 expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:0,passed:[]});expect(s.windows!.at(-1)!.revision).toBeGreaterThan(parent.revision);
 expect(s.rolls!.at(-1)).toEqual(roll);expect(s.discard).toEqual(expect.arrayContaining(['a2-p02-r1c3','a2-p02-r2c3']));
 s=pass(s,[]);expect(s.windows!.at(-1)).toMatchObject({id:parent.id,cursor:1,passed:['A']});
});
