import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {allCardInstanceIds,transition,viewFor,type GameCommand,type GameState} from '../src/index.js';
import {makeR6WanderingScenario,s26Entropy} from './fixtures/r6-wandering-scenario.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function act(s:GameState,actorId:string,command:GameCommand){const input={actorId,command},r=transition(s,input,s26Entropy());expect(r).toEqual(transition(JSON.parse(JSON.stringify(s)),input,s26Entropy()));if(!r.ok)throw Error(r.code);const ids=allCardInstanceIds(r.state);expect(ids).toHaveLength(220);expect(new Set(ids).size).toBe(220);return r.state;}
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<300;n++){if(done(s))return s;const w=s.windows!.at(-1)!;s=act(s,w.participants[w.cursor]!,{type:'PASS'});}throw Error('S26_WINDOW');}
function nextOwn(s:GameState){for(let n=0;n<40;n++){const actor=s.seatOrder[s.turnSeat]!;if(s.phase==='turn-start'&&actor==='A')return act(act(s,'A',{type:'START_TURN'}),'A',{type:'CHOOSE_DRAW',draw:false});if(s.phase==='turn-start')s=act(s,actor,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});else if(s.phase==='action')s=act(s,actor,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,actor,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=until(act(s,actor,{type:'END_TURN',discardIds:[]}),s=>!s.windows?.length);else throw Error('S26_TURN');}throw Error('S26_TURN_LIMIT');}
it('S26 actual protected death returns wandering cards to deck and resurrection replaces initial hands and followers before the suspended turn',()=>{let s=makeR6WanderingScenario(players);const b=s.players.B!,c=s.players.C!,oldHand=[...b.hand],oldFollower=b.followers[0]!.cardInstanceId,deadHand=[...c.hand],life=b.lifeId;expect(getAction(oldFollower)!.name).toBe('兵士');expect(b.protection!.characterIds).toContain(c.characterId);
 s=until(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p07-r3c3',targetIds:['C'],dedicated:false}),s=>!s.windows?.length);expect(s.players.C!.presence).toBe('dead');expect(s.players.B).toMatchObject({presence:'wandering',hand:[],followers:[],damage:2});expect(s.outcome).toBeUndefined();for(const id of [...oldHand,oldFollower]){expect(s.deck).toContain(id);expect(s.discard).not.toContain(id);}for(const id of deadHand){expect(s.discard).toContain(id);expect(s.deck).not.toContain(id);}const saved=JSON.stringify(s);expect(transition(s,{actorId:'B',command:{type:'START_TURN'}},s26Entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(saved);expect(viewFor(s,'B').legalChoices).not.toContain('ATTACK');
 s=nextOwn(JSON.parse(saved));s=until(act(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:'a2-p13-r3c1',targetIds:['C'],dedicated:true}),s=>s.windows?.at(-1)?.kind==='re-setup');expect(s.players.C).toMatchObject({presence:'active',damage:0,followers:[]});expect(s.players.C!.hand).toHaveLength(5);expect(s.players.C!.hand.every(id=>!deadHand.includes(id))).toBe(true);expect(s.players.B!.presence).toBe('wandering');expect(s.outcome).toBeUndefined();s=act(JSON.parse(JSON.stringify(s)),'C',{type:'PASS_SETUP'});expect(s.windows!.at(-1)).toMatchObject({kind:'re-setup',participants:['B']});expect(s.players.B).toMatchObject({presence:'active',damage:2,followers:[]});expect(s.players.B!.lifeId).toBe(life);expect(s.players.B!.hand).toHaveLength(5);expect(s.players.B!.hand.every(id=>!oldHand.includes(id)&&id!==oldFollower)).toBe(true);const newFollower=s.players.B!.hand.find(id=>getAction(id)!.name==='小人族')!;expect(newFollower).toBeDefined();expect(newFollower).not.toBe(oldFollower);s=act(JSON.parse(JSON.stringify(s)),'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:newFollower});expect(s.players.B!.followers).toEqual([{cardInstanceId:newFollower,revealed:false,placedById:'B',placedLifeId:life??'initial-life:B'}]);expect(s.players.B!.hand).toHaveLength(5);s=until(act(s,'B',{type:'PASS_SETUP'}),s=>!s.windows?.length);expect(s.phase).toBe('hand-adjustment');expect(s.turnSeat).toBe(0);expect(s.outcome).toBeUndefined();expect(s.events.filter(e=>['PLAYER_DIED','PLAYER_WANDERING','PLAYER_REVIVED','PLAYER_RETURNED'].includes(e.type)).map(e=>[e.type,e.actorId])).toEqual([['PLAYER_DIED','C'],['PLAYER_WANDERING','B'],['PLAYER_REVIVED','C'],['PLAYER_RETURNED','B']]);expect(s.rolls?.filter(r=>r.purpose==='revival')??[]).toEqual([]);expect(s.discard.filter(id=>id==='a2-p13-r3c1')).toHaveLength(1);});
