import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeScythePhysicalScenario,SCYTHE,type ScythePhysicalScenario} from './fixtures/scythe-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['scythe-physical-ordinary','scythe-physical-dedicated'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function next(s:GameState){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==SCYTHE).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SCYTHE_TURN');}throw Error('SCYTHE_TURN_LIMIT');}
function prepare(s:GameState){s=act(s,'A',{type:'CHANT',cardInstanceId:SCYTHE});expect(s.players.A!.chants).toEqual([{cardInstanceId:SCYTHE,revealed:false}]);return next(s);}
function attack(scenario:ScythePhysicalScenario){const dedicated=scenario.includes('dedicated');return {type:'ATTACK' as const,cardInstanceId:SCYTHE,targetIds:dedicated?['B','C']:['B'],dedicated};}
function finish(s:GameState,options:{request?:string[];success?:string[];reclaim?:boolean}={}){let taken=false;for(let n=0;n<500&&s.windows?.length;n++){const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d){expect(d.kind).toBe('instant-death');expect(viewFor(s,'B').lifetimeDecision).toBeNull();reject(s,'B',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'});s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:options.request?.includes(d.targetId)?'apply':'decline'});}else if(options.reclaim&&!taken&&s.windows!.at(-1)!.kind==='reclaim'&&viewFor(s,'A').reclaim?.pendingActorId==='A'&&viewFor(s,'A').reclaim?.cardInstanceId===SCYTHE){const reclaim=viewFor(s,'A').reclaim!,base=reclaim.claims.find(c=>c.right==='base');expect(base).toBeDefined();s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:reclaim.decisionId,choice:'take',claimId:base!.claimId});taken=true;reject(s,'A',{type:'ATTACK',cardInstanceId:SCYTHE,targetIds:['B'],dedicated:true});}else s=pass(s,Array(30).fill(r?.purpose==='status-resistance'&&r.stage==='before-roll'&&!options.success?.includes(r.rollerId)?6:1));}expect(s.windows??[]).toEqual([]);return s;}
it.each(rows)('%s actual chant retains warrior scythe profile and ordinary use7 checks versus elected waiver',scenario=>{
 const dedicated=scenario.includes('dedicated');for(const level of [6,7]){let s=makeScythePhysicalScenario(scenario,players,{level,follower:'none'});reject(s,'A',attack(scenario));s=act(prepare(s),'A',{...attack(scenario),targetIds:dedicated?['B','C','D']:['B']});const f=Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!;expect(f.technique).toMatchObject({school:'warrior',range:'far',useLevel:7,effectLevel:7,damage:8,attributes:['戦','鎌','詠'],chant:true,noChecks:dedicated,followerIgnore:false,evadeProhibited:true,target:dedicated?'all':'one'});expect(f.checkSpecs).toHaveLength(dedicated?0:7-level);if(dedicated)expect(f.technique.lifetimeHit).toEqual({kind:'instant-death',modifier:-2,optional:true});else expect(f.technique.lifetimeHit).toBeUndefined();s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([8,dedicated?8:0,dedicated?8:0]);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);expect(s.discard.filter(id=>id===SCYTHE)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);}
});
it.each(rows)('%s actual Metal and Soldier reduce body damage and do not become ignored by elected death effect',scenario=>{
 let s=finish(act(prepare(makeScythePhysicalScenario(scenario,players)),'A',attack(scenario)));expect(s.players.B).toMatchObject({presence:'active',damage:3});expect(s.players.B!.followers).toEqual([]);expect(s.players.C!.damage).toBe(scenario.includes('dedicated')?7:0);expect(s.players.C!.followers).toHaveLength(scenario.includes('dedicated')?0:1);
});
it.each(['B','C','both','none'])('actual Scythe target request %s persists pending instant death until every hit has been evaluated',selection=>{
 const request=selection==='both'?['B','C']:selection==='none'?[]:[selection];let s=act(prepare(makeScythePhysicalScenario('scythe-physical-dedicated',players)),'A',attack('scythe-physical-dedicated'));const choices:string[]=[];for(let n=0;n<500&&s.windows?.length;n++){const d=viewFor(s,'A').lifetimeDecision,r=s.rolls?.at(-1);if(d){expect(s.players.B!.presence).toBe('active');expect(s.players.C!.presence).toBe('active');expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);if(d.targetId==='C'&&request.includes('B'))expect(Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='B')!.pendingInstantDeath).toBe('instant-death');expect(s.events.filter(e=>e.type==='PLAYER_DIED')).toEqual([]);choices.push(d.targetId);s=act(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:request.includes(d.targetId)?'apply':'decline'});reject(s,'A',{type:'CHOOSE_LIFETIME_EFFECT',choice:'apply'});}else s=pass(s,Array(30).fill(r?.purpose==='status-resistance'&&r.stage==='before-roll'?6:1));}expect(s.windows??[]).toEqual([]);expect(choices).toEqual(['B','C']);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance').map(r=>[r.rollerId,r.modifier,r.threshold,r.success])).toEqual(request.map(id=>[id,-2,4,false]));for(const id of ['B','C'])expect(s.players[id]!.presence).toBe(request.includes(id)?'dead':'active');expect(s.events.filter(e=>e.type==='PLAYER_DIED').map(e=>e.actorId)).toEqual(request);expect(s.players.D!.presence).toBe('active');expect(s.outcome).toBeUndefined();expect(s.discard.filter(id=>id===SCYTHE)).toHaveLength(1);
});
it.each(['B','C','both'])('actual Scythe requested resistance succeeds for %s and leaves ordinary body damage',selection=>{
 const success=selection==='both'?['B','C']:[selection];const s=finish(act(prepare(makeScythePhysicalScenario('scythe-physical-dedicated',players)),'A',attack('scythe-physical-dedicated')),{request:['B','C'],success});for(const id of ['B','C']){expect(s.players[id]!.presence).toBe(success.includes(id)?'active':'dead');if(success.includes(id))expect(s.players[id]!.damage).toBe(id==='B'?3:7);}expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance').map(r=>[r.rollerId,r.threshold,r.success])).toEqual(['B','C'].map(id=>[id,4,success.includes(id)]));
});
it.each([['scythe-physical-ordinary',0],['scythe-physical-ordinary',1],['scythe-physical-dedicated',0],['scythe-physical-dedicated',1]] as const)('%s actual Guardian equal or Prayer%s lower determines whether optional death can be requested',(scenario,bonus)=>{
 let s=act(prepare(makeScythePhysicalScenario(scenario,players,{follower:'guardian'})),'A',{...attack(scenario),targetIds:['B']});if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!.id});}s=finish(s,{request:['B']});const death=!!bonus&&scenario.includes('dedicated');expect(s.players.B!.presence).toBe(death?'dead':'active');if(!death)expect(s.players.B!.damage).toBe(bonus?8:0);expect(s.players.B!.followers).toEqual([]);expect(s.players.C!.followers).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(death?1:0);
});
it.each(rows)('%s actual Evade refusal and Teleport prevent only B hit and optional resistance',scenario=>{
 let s=until(act(prepare(makeScythePhysicalScenario(scenario,players)),'A',attack(scenario)),'normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false}),{request:['B','C']});expect(s.players.B).toMatchObject({damage:0,presence:'active'});expect(s.players.B!.followers).toHaveLength(1);expect(s.players.C!.presence).toBe(scenario.includes('dedicated')?'dead':'active');expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance').map(r=>r.rollerId)).toEqual(scenario.includes('dedicated')?['C']:[]);
});
it.each(rows)('%s actual failed ordinary use and Fate cancel all body and instant death effects',scenario=>{
 if(!scenario.includes('dedicated')){let s=until(act(prepare(makeScythePhysicalScenario(scenario,players,{level:6})),'A',attack(scenario)),'before-roll');s=finish(closeWindow(s,[6,6]),{request:['B']});expect(s.players.B).toMatchObject({damage:0,presence:'active'});expect(s.players.B!.followers).toHaveLength(1);}
 let s=act(prepare(makeScythePhysicalScenario(scenario,players)),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}),{request:['B','C']});for(const target of ['B','C']){expect(s.players[target]).toMatchObject({damage:0,presence:'active'});expect(s.players[target]!.followers).toHaveLength(1);}expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);expect(s.discard.filter(x=>x===SCYTHE)).toHaveLength(1);
});
it.each(rows)('%s rejects foreign dedication ordinary multiple targets and invalid actor or turn form unchanged',scenario=>{
 let s=prepare(makeScythePhysicalScenario(scenario,players));reject(s,'A',{...attack(scenario),dedicated:false,targetIds:['B','C']});for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',{...attack(scenario),targetIds});reject(s,'B',attack(scenario));reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:SCYTHE,targetIds:['B'],dedicated:true});s=prepare(makeScythePhysicalScenario(scenario,players,{foreign:true}));reject(s,'A',{...attack(scenario),dedicated:true});
});
it.each(rows)('%s actual base reclaim reserves source and later real chant permits a newly chosen use mode',scenario=>{
 const firstDedicated=scenario.includes('dedicated'),second=firstDedicated?'scythe-physical-ordinary':'scythe-physical-dedicated';let s=act(prepare(makeScythePhysicalScenario(scenario,players,{follower:'none'})),'A',attack(scenario));expect(Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!.technique.noChecks).toBe(firstDedicated);s=finish(s,{reclaim:true});expect(s.players.A!.hand).toContain(SCYTHE);expect(s.discard).not.toContain(SCYTHE);s=next(s);reject(s,'A',attack(second));s=prepare(s);s=act(s,'A',attack(second));expect(Object.values(s.actions!).find(a=>a.cardInstanceId===SCYTHE)!.technique.noChecks).toBe(!firstDedicated);s=finish(s);expect(s.players.B!.damage).toBe(16);expect(s.players.C!.damage).toBe(8);expect(s.discard.filter(id=>id===SCYTHE)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(SCYTHE);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(0);
});
