import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSecretBookPhysicalScenario,bookMode} from '../../../apps/worker/test/fixtures/secret-book-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p03-r1c1',command={type:'PLAY_TURN_CARD',cardInstanceId:card} as const;
function until(s:GameState,done:(s:GameState)=>boolean,face=1){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s,[face,face]);}throw Error('BOOK_LIMIT');}
function settle(s:GameState,face=1){return until(s,s=>!s.windows?.length,face);}
function reject(s:GameState,id:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each([1,2,3,4,5,6])('actual Secret Book d6 face %s draws exactly that many privately without an immediate refill or consuming main action',face=>{let s=makeSecretBookPhysicalScenario('book-one',players);const hand=[...s.players.A!.hand],deck=[...s.deck];s=act(s,'A',command);expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==card));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(card);s=until(s,s=>s.rolls?.at(-1)?.purpose==='extra-draw',face);const r=s.rolls!.at(-1)!;expect(r).toMatchObject({kind:'numeric',formula:'d6',faces:[face],total:face,stage:'after-roll',generation:0});expect(s.players.A!.hand).toHaveLength(hand.length-1);expect(s.windows!.at(-1)!.kind).toBe('after-roll');s=settle(s,face);expect(s.players.A!.hand).toEqual([...hand.filter(id=>id!==card),...deck.slice(0,face)]);expect(s.deck).toEqual(deck.slice(face));expect(s.phase).toBe('action');expect(s.discard).toContain(card);expect(s.resolution).toEqual([]);for(const id of ['B','C','D'])for(const draw of deck.slice(0,face))expect(JSON.stringify(viewFor(s,id))).not.toContain(draw);expect(viewFor(s,'A').privateLogs.filter(e=>e.type==='CARD_DRAWN').slice(-face).map(e=>e.cardInstanceId)).toEqual(deck.slice(0,face));reject(s,'A',command);s=act(s,'A',{type:'PASS_ACTION'});const extra=Math.max(0,s.players.A!.hand.length-gameStats(s,'A').handLimit);if(extra)reject(s,'A',{type:'END_TURN',discardIds:[]});s=settle(act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(-extra||s.players.A!.hand.length)}));expect(s.players.A!.hand.length).toBeLessThanOrEqual(gameStats(s,'A').handLimit);});
it.each(['book-main-attack','book-main-chant','book-draw','book-recovery'] as const)('%s actual turn producer remains available after successful additional draw',name=>{let s=makeSecretBookPhysicalScenario(name,players);const m=bookMode(name),count=s.players.A!.hand.length;if(m.recovery){expect(count).toBe(5);expect(s.discard).toContain('a2-p06-r1c1');expect(viewFor(s,'A').privateLogs.some(e=>e.type==='CARD_DRAWN')).toBe(true);expect(s.rolls?.some(r=>r.purpose==='status-recovery'&&r.success)).toBe(true);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(false);}if(m.draw)expect(count).toBe(6);s=settle(act(s,'A',command),3);expect(s.players.A!.hand).toHaveLength(count+2);expect(s.phase).toBe('action');if(name==='book-main-chant'){s=act(s,'A',{type:'CHANT',cardInstanceId:m.chant});expect(s.players.A!.chants.map(c=>c.cardInstanceId)).toContain(m.chant);}else{s=settle(act(s,'A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:['B'],dedicated:false}));expect(s.players.B!.damage).toBe(4);expect(s.phase).toBe('withdrawal');}});
it('actual OPEN FuSen with a previously killed recipient suspends Secret Book count before sequential Blood Haja and replacements',()=>{let s=makeSecretBookPhysicalScenario('book-opens',players);expect(s.players.B!.presence).toBe('dead');const count=s.players.A!.hand.length,ordinary=s.deck.filter(id=>getAction(id)!.category!=='open').slice(0,3);s=act(s,'A',command);s=until(s,s=>s.rolls?.at(-1)?.purpose==='extra-draw',3);const id=s.rolls!.at(-1)!.id;s=until(s,s=>s.windows?.at(-1)?.kind==='revival',1);expect(s.players.A!.hand).toHaveLength(count-1);expect(s.resolution).toContain(card);expect(s.players.A!.open).toContain('a2-p01-r1c1');expect(s.players.A!.open).not.toContain('a2-p01-r1c3');expect(s.lifecycle?.some(t=>t.kind==='draw'&&t.actorId==='A'&&t.target===count+2)).toBe(true);s=act(JSON.parse(JSON.stringify(s)),'B',{type:'CHOOSE_REVIVAL',revive:false});s=settle(s);expect(s.players.A!.open).toEqual(expect.arrayContaining(['a2-p01-r1c1','a2-p01-r1c3','a2-p01-r2c2']));expect(s.players.A!.hand.slice(-3)).toEqual(ordinary);expect(s.players.A!.hand).toHaveLength(count+2);expect(s.rolls!.filter(r=>r.purpose==='extra-draw').map(r=>r.id)).toEqual([id]);expect(s.phase).toBe('action');expect(s.resolution).toEqual([]);});
it('actual Fate cancels Secret Book before any numeric roll or extra draw and preserves main action',()=>{let s=makeSecretBookPhysicalScenario('book-fate',players),hand=[...s.players.A!.hand];s=act(s,'A',command);const target=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:target}));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==card));expect(s.rolls?.some(r=>r.purpose==='extra-draw')??false).toBe(false);expect(s.discard).toContain(card);expect(s.phase).toBe('action');expect(s.earlyTurnBook?.closed).toBe(true);});
it('actual numeric reroll uses only final d6 generation for extra draws and cannot be forced failed as a check',()=>{let s=makeSecretBookPhysicalScenario('book-reroll',players),hand=s.players.A!.hand.length;s=act(s,'A',command);s=until(s,s=>s.rolls?.at(-1)?.purpose==='extra-draw',1);const id=s.rolls!.at(-1)!.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:id});s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=settle(s,6);expect(s.rolls!.find(r=>r.id===id)).toMatchObject({generation:1,total:6,attempts:[{generation:0,faces:[1],total:1},{generation:1,faces:[6],total:6}]});expect(s.players.A!.hand).toHaveLength(hand+5);expect(s.phase).toBe('action');});
it('actual setup start draw pending action and other seat reject Secret Book before opening permission',()=>{let s=makeSecretBookPhysicalScenario('book-one',players,true);reject(s,'A',command);s=act(s,'A',{type:'START_TURN'});expect(s.phase).toBe('draw');reject(s,'A',command);s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'B',command);reject(s,'A',{...command,mode:'dedicated'});reject(s,'A',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card});s=act(s,'A',command);reject(s,'A',command);});
it('actual approach closes opening permission without using the ordinary action and decline retains the card',()=>{let s=makeSecretBookPhysicalScenario('book-late',players),m=bookMode('book-late');s=settle(act(s,'A',{type:'APPROACH',targetId:'B',cardInstanceId:m.advance}));expect(s.phase).toBe('action');expect(viewFor(s,'A').turnCardOptions.some(o=>o.cardInstanceId===card)).toBe(false);reject(s,'A',command);s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(card);});
it('actual unsuccessful Hypnosis recovery skips own turn and cannot use the held Secret Book',()=>{const s=makeSecretBookPhysicalScenario('book-recovery-fail',players);expect(s.rolls!.some(r=>r.purpose==='status-recovery'&&r.success===false)).toBe(true);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');expect(s.players.A!.hand).toContain(card);expect(s.players.A!.hand).toHaveLength(4);reject(s,'A',command);});
it('actual accepted FuSen revival consumes its own replacement draws before resuming the saved Secret Book count',()=>{let s=makeSecretBookPhysicalScenario('book-opens',players);const count=s.players.A!.hand.length;s=act(s,'A',command);s=until(s,s=>s.rolls?.at(-1)?.purpose==='extra-draw',3);s=until(s,s=>s.windows?.at(-1)?.kind==='revival');s=act(s,'B',{type:'CHOOSE_REVIVAL',revive:true});for(let n=0;n<300&&s.windows?.length;n++){const w=s.windows.at(-1)!;s=w.kind==='re-setup'?act(s,'B',{type:'PASS_SETUP'}):pass(s);}expect(s.windows??[]).toEqual([]);expect(s.players.B!.presence).toBe('active');expect(s.players.B!.damage).toBe(0);expect(s.players.B!.hand).toHaveLength(5);expect(s.players.B!.open).toEqual(expect.arrayContaining(['a2-p01-r1c3','a2-p01-r2c2']));expect(s.players.A!.hand).toHaveLength(count+2);expect(s.players.A!.open).toContain('a2-p01-r1c1');expect(s.players.A!.open).not.toContain('a2-p01-r2c2');expect(s.rolls!.filter(r=>r.purpose==='extra-draw')).toHaveLength(1);expect(s.phase).toBe('action');expect(s.resolution).toEqual([]);});
