import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeShariaPhysicalScenario,shariaPhysicalMode,type ShariaPhysicalScenario} from '../../../apps/worker/test/fixtures/sharia-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['sharia-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SHARIA_TURN');}throw Error('SHARIA_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r3c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=shariaPhysicalMode(scenario);let s=makeShariaPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(0);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=shariaPhysicalMode(scenario);let s=ready(makeShariaPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=shariaPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeShariaPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=shariaPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeShariaPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=shariaPhysicalMode(scenario);let s=until(incoming(ready(makeShariaPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=shariaPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeShariaPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const SHARIA='a2-p21-r3c2',ARMY='a2-p05-r2c2';
function approach(s:GameState){return finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));}
function attackCommand(s:GameState,scenario:ShariaPhysicalScenario){const m=shariaPhysicalMode(scenario);return m.army?{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:SHARIA,targetIds:['B']}:m.grant?grant(s):{type:'ATTACK' as const,cardInstanceId:SHARIA,targetIds:['B'],dedicated:true};}
it('actual Sharia at spirit0 never rolls morale and applies HP4 separately to every Dwarf6 hit',()=>{
 let s=ready(makeShariaPhysicalScenario('sharia-higher',players),SHARIA);s=next(s);s=until(act(s,'B',grant(s,'B','a2-p21-r2c3')),'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.descriptor).toMatchObject({level:5,hp:4,moraleRequired:false,attributes:['人','僧','女']});expect(f.hits.map(h=>h.outcome)).toEqual(['lower-destroyed','lower-destroyed','lower-destroyed']);expect(f.hits.map(h=>h.hpReduction)).toEqual([4,4,4]);s=finish(s);expect(s.players.A!.damage).toBe(6);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(s.discard.filter(id=>id===SHARIA)).toHaveLength(1);
});
it('actual spirit Dark Saint5 attack still compares nongolem Sharia5 and equal-destroys without body damage',()=>{
 let s=ready(makeShariaPhysicalScenario('sharia-spirit',players),SHARIA);s=next(s);s=finish(act(s,'B',grant(s,'B','a2-p21-r2c1')));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(s.discard.filter(id=>id===SHARIA)).toHaveLength(1);
});
it('actual Jil has no unprinted dedicated Sharia defensive package',()=>{
 let s=until(incoming(ready(makeShariaPhysicalScenario('sharia-setup',players),SHARIA)),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions.some(o=>o.cardInstanceId===SHARIA)).toBe(false);reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[SHARIA]});s=finish(s);expect(s.players.A!.damage).toBe(0);
});
it.each(['sharia-ded-hand','sharia-ded-field','sharia-grant-hand','sharia-grant-field','sharia-army'] as const)('%s actual near warrior martial5 damage6 retains warrior checks with explicit single-target permission',scenario=>{
 const m=shariaPhysicalMode(scenario);for(const warrior of [4,5]){let s=ready(makeShariaPhysicalScenario(scenario,players,{warrior,magic:warrior===4?20:0}),SHARIA,m.initial);if(m.grant)expect(viewFor(s,'A').followerBundleOptions.some(o=>o.sources.some(source=>source.cardInstanceId===SHARIA))).toBe(false);else reject(s,'A',attackCommand(s,scenario));s=approach(s);const command=attackCommand(s,scenario);for(const targetIds of [[],['A'],['B','B'],['B','C']])reject(s,'A',command.type==='USE_FOLLOWER_ATTACK'?{...command,sources:command.sources.map(source=>({...source,targetIds}))}:{...command,targetIds});s=act(s,'A',command);const a=Object.values(s.actions!).find(a=>a.cardInstanceId===SHARIA)!;expect(a.checks).toHaveLength(5-warrior);expect(a.technique).toMatchObject({range:'near',school:'warrior',useLevel:5,effectLevel:5,damage:6,attributes:['近','戦','格'],noChecks:false,hitCount:1,target:'one'});s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([6,0]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);expect(s.discard.filter(id=>id===SHARIA)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it('actual Army cannot use Sharia from placement even after approach',()=>{
 let s=approach(ready(makeShariaPhysicalScenario('sharia-army',players),SHARIA));expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===SHARIA)).toBe(false);reject(s,'A',attackCommand(s,'sharia-army'));
});
it.each(['maai','mirror'] as const)('actual Sharia martial attack accepts %s normal defense and paid source never returns',mode=>{
 let s=approach(ready(makeShariaPhysicalScenario('sharia-ded-hand',players),SHARIA,false));s=until(act(s,'A',attackCommand(s,'sharia-ded-hand')),'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});s=finish(s);expect([s.players.A!.damage,s.players.B!.damage]).toEqual([0,0]);expect(s.discard.filter(id=>id===SHARIA)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);
});
it.each(['hand','field','army-parent','army-child','army-use','use','grant-use','grant'] as const)('actual Sharia %s cancellation or use failure consumes each paid source once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'sharia-army':mode.startsWith('grant')?'sharia-grant-field':mode==='field'?'sharia-ded-field':'sharia-ded-hand';let s=approach(ready(makeShariaPhysicalScenario(scenario,players,{warrior:4}),SHARIA,mode==='field'||mode.startsWith('grant')));s=act(s,'A',attackCommand(s,scenario));if(mode==='army-child')s=closeWindow(s);const failed=mode==='army-use'||mode==='use'||mode==='grant-use';if(failed){s=until(s,'before-roll');expect(s.rolls!.at(-1)!.purpose).toBe('excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:SHARIA)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:failed?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of army?[SHARIA,ARMY]:[SHARIA])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
