import {expect,it} from 'vitest';
import {transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeShockPhysicalScenario,shockPhysicalMode,type ShockPhysicalScenario} from './fixtures/shock-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['shock-small','shock-large','phantom-resist'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function attack(scenario:ShockPhysicalScenario){return{type:'ATTACK' as const,cardInstanceId:shockPhysicalMode(scenario).card,targetIds:['B'],dedicated:false};}
function settle(s:GameState,faces=[6,6]){for(let n=0;n<300&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.rollerId==='B'&&r.purpose==='status-resistance'&&r.stage==='before-roll'?faces:Array(30).fill(1));}expect(s.windows??[]).toEqual([]);return s;}
it.each(rows)('%s actual printed profile and under-level check at both actual far and paid near distances',scenario=>{
 const m=shockPhysicalMode(scenario);for(const near of [false,true])for(const level of [m.level-1,m.level]){let s=makeShockPhysicalScenario(scenario,players,{level,none:true,spirit:6});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});if(near)s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c2',targetId:'B'}));expect(s.distances.A!.B).toBe(near?'near':'far');s=act(s,'A',attack(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.level,effectLevel:m.level,damage:m.damage,attributes:m.phantom?['魔','精']:['魔'],chant:false,noChecks:false});expect(f.technique.followerIgnore??false).toBe(m.phantom);expect(f.technique.counterProhibited??false).toBe(false);expect(f.checkSpecs).toHaveLength(m.level-level);s=settle(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.phantom?10:m.damage,0,0]);expect(s.players.B!.statuses??[]).toEqual([]);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);}
});
it.each(['shock-small','shock-large'] as const)('%s actual Stone5 above equal and lower boundaries retain fixed damage minus real follower HP',scenario=>{
 const m=shockPhysicalMode(scenario);for(const bonus of [0,1,2]){let s=act(makeShockPhysicalScenario(scenario,players),'A',attack(scenario));if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id});while(s.windows?.at(-1)?.kind!=='normal-defense')s=pass(s,Array(30).fill(bonus));expect(s.rolls!.find(r=>r.purpose==='prayer-addition')!.faces).toEqual([bonus]);}s=finish(s);const ef=m.level+bonus;expect(s.players.B!.damage).toBe(ef>5?m.damage!-5:0);expect(s.players.B!.followers).toHaveLength(ef<5?2:ef===5?1:0);expect(s.players.C!.followers).toHaveLength(1);expect(s.players.C!.damage).toBe(0);expect(s.players.B!.statuses??[]).toEqual([]);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toEqual([]);}
});
it.each([[2,3],[3,3]] as const)('actual Phantom target minus1 boundary %s %s ignores Stone and rear without base damage addition',(one,two)=>{
 let s=makeShockPhysicalScenario('phantom-resist',players,{spirit:6});const followers=structuredClone(s.players.B!.followers);s=settle(act(s,'A',attack('phantom-resist')),[one,two]);expect(s.rolls!.find(r=>r.purpose==='status-resistance')).toMatchObject({rollerId:'B',modifier:-1,threshold:5,success:one===2,faces:[one,two]});expect(s.players.B!.damage).toBe(one===2?0:10);expect(s.players.B!.followers).toEqual(followers);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.C!.damage).toBe(0);expect(s.players.C!.followers).toHaveLength(1);
});
it.each([0,2,3])('actual Phantom Guardian7 cancels ignore and Prayer%s yields block equal or failed resistance ten',bonus=>{
 let s=act(makeShockPhysicalScenario('phantom-resist',players,{guardian:true,spirit:6}),'A',attack('phantom-resist'));if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p17-r2c3')!.id});while(s.windows?.at(-1)?.kind!=='normal-defense')s=pass(s,Array(30).fill(bonus));expect(s.rolls!.find(r=>r.purpose==='prayer-addition')!.faces).toEqual([bonus]);}s=settle(s);expect(s.players.B!.followers).toHaveLength(bonus===0?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(bonus===3?1:0);expect(s.players.B!.damage).toBe(bonus===3?10:0);
});
it.each(rows)('%s actual Teleport maai and ordinary-only Evade prevent target damage before followers or resistance',scenario=>{
 const m=shockPhysicalMode(scenario);for(const defense of ['teleport','evade','maai']){let s=until(act(makeShockPhysicalScenario(scenario,players,{none:true,spirit:6}),'A',attack(scenario)),'normal-defense');if(m.phantom&&defense==='evade'){reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=settle(s);expect(s.players.B!.damage).toBe(10);}else{s=settle(defense==='maai'?act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}):act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:defense==='evade'?'a2-p05-r3c1':'a2-p06-r1c1',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toEqual([]);}expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual failed use and Fate cancellation preserve real followers without hit resistance',scenario=>{
 const m=shockPhysicalMode(scenario);let s=until(act(makeShockPhysicalScenario(scenario,players,{level:m.level-1}),'A',attack(scenario)),'before-roll');s=finish(closeWindow(s,[6,6]));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toEqual([]);s=act(makeShockPhysicalScenario(scenario,players),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.followers).toHaveLength(1);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);expect(s.rolls??[]).toEqual([]);
});
it.each(rows)('%s rejects dedicated invalid targets foreign actor turn form and actual revealed ally without payment',scenario=>{
 const m=shockPhysicalMode(scenario);let s=makeShockPhysicalScenario(scenario,players);reject(s,'A',{...attack(scenario),dedicated:true});for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',{...attack(scenario),targetIds});s=act(s,'D',{type:'REVEAL_CHARACTER'});reject(s,'A',{...attack(scenario),targetIds:['D']});reject(s,'B',attack(scenario));reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:m.card,targetIds:['B'],dedicated:false});
});
