import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeShurikenPhysical,shurikenCard as CARD,shurikenChants as CHANTS,shurikenMode} from './fixtures/shuriken-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1]){for(let n=0;n<600;n++){if(done(s))return s;s=pass(s,dice);}throw Error('SHURIKEN_TEST_LIMIT');}
function finish(s:GameState,discard:(id:string)=>boolean=()=>false){let choices=0;for(let n=0;n<600&&s.windows?.length;n++){const w=s.windows.at(-1)!;if(w.kind==='on-hit-choice'){if(w.continuation.kind!=='group')throw Error('SHURIKEN_HIT_CONTINUATION');choices++;s=act(s,'A',{type:'DISCARD_HIT_CHANTS',discard:discard(w.continuation.targetId!)});}else s=pass(s);}expect(s.windows??[]).toEqual([]);return {s,choices};}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['shuriken-ordinary','shuriken-guard','shuriken-owner-ordinary','shuriken-dedicated','shuriken-subset','shuriken-all','shuriken-near','shuriken-suppressed','shuriken-silenced'] as const)('%s actual setup physical Shuriken ordinary four five versus elected Ida six d6x5 and real prepared target chants',name=>{
 let s=makeShurikenPhysical(name,players);const m=shurikenMode(name),targets=name==='shuriken-all'?['B','C','D']:m.dedicated&&!['shuriken-subset','shuriken-near'].includes(name)?['B','C']:['B'],hand=[...s.players.A!.hand],deck=[...s.deck],before=structuredClone(s.players),rolls=s.rolls?.length??0;if(m.guard){expect(s.players.B!.open).toContain('a2-p01-r2c2');expect(s.players.B!.chants.map(c=>c.cardInstanceId)).toEqual(CHANTS.slice(0,2));expect(s.players.C!.chants.map(c=>c.cardInstanceId)).toEqual([CHANTS[2]]);for(const id of CHANTS)expect(JSON.stringify(viewFor(s,'A'))).not.toContain(id);}if(name==='shuriken-subset')reject(s,'A',cmd(true,['D']));if(!m.dedicated)reject(s,'A',cmd(false,['B','C']));if(name==='shuriken-near')expect(s.distances.A!.B).toBe('near');if(name==='shuriken-suppressed')expect(s.players.A!.statuses?.some(x=>x.kind==='ability-disabled')).toBe(true);if(name==='shuriken-silenced')expect(s.players.A!.statuses?.some(x=>x.kind==='silenced')).toBe(true);reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});
 s=act(s,'A',cmd(m.dedicated,targets));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);expect(s.resolution).toContain(CARD);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');const g=Object.values(s.groups!).at(-1)!;expect(g.technique).toMatchObject({school:'warrior',range:'far',useLevel:4,effectLevel:m.dedicated?6:4,damage:5,attributes:['戦','忍','反'],chant:false,noChecks:m.dedicated,followerIgnore:m.dedicated,counter:true,defense:'counter'});expect(g.targets.map(t=>t.actorId)).toEqual(targets);expect(s.rolls?.length??0).toBe(rolls+(m.dedicated?1:0));if(m.dedicated)expect(s.rolls!.at(-1)).toMatchObject({purpose:'attack-damage',kind:'numeric',formula:'d6x5',total:5});const result=finish(s,()=>true);s=result.s;expect(result.choices).toBe(m.dedicated?targets.filter(id=>id==='B'||id==='C').length:0);
 for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(targets.includes(id)&&(!m.guard||m.dedicated)?5:0);if(m.dedicated){expect(s.players.B!.followers).toEqual(before.B!.followers);expect(s.players.C!.followers).toEqual(before.C!.followers);for(const id of ['B','C']){expect(s.players[id]!.chants).toEqual(targets.includes(id)?[]:before[id]!.chants);for(const ch of before[id]!.chants)expect(discardIds(s).includes(ch.cardInstanceId)).toBe(targets.includes(id));}}else if(m.guard){expect(s.players.B!.followers[0]!.revealed).toBe(true);expect(s.players.B!.chants).toEqual(before.B!.chants);}expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);expect(s.phase).toBe('withdrawal');reject(s,'A',cmd(m.dedicated,targets));
});
it.each([1,2,3,4,5,6])('dedicated actual numeric die%s yields exactly five times its face once for every selected target and cannot be forced to fail',face=>{let s=makeShurikenPhysical('shuriken-all',players,{warrior:0,spirit:0});expect(gameStats(s,'A')).toMatchObject({warrior_level:0,spirit:0});s=until(act(s,'A',cmd(true,['B','C','D'])),s=>s.windows?.at(-1)?.kind==='after-roll',[face]);const roll=s.rolls!.at(-1)!;expect(roll).toMatchObject({purpose:'attack-damage',kind:'numeric',formula:'d6x5'});s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');reject(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll.id});s=closeWindow(s,[face]);expect(s.rolls!.at(-1)).toMatchObject({total:face*5,faces:[face]});s=finish(s).s;expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([face*5,face*5,face*5]);expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(0);});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior3 needs one actual spirit6 check roll%s plus%s success%s',(x,y,success)=>{let s=makeShurikenPhysical('shuriken-low',players);s=until(act(s,'A',cmd()),s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=finish(s).s;expect(s.players.B!.damage).toBe(success?5:0);expect(s.rolls!.filter(r=>r.purpose==='excess-level')).toHaveLength(1);expect(discardIds(s)).toContain(CARD);});
it.each(['shuriken-keep','shuriken-mixed'] as const)('%s actual target-by-target optional all-chant disposal keeps independent choices and rejects partial payloads unchanged',name=>{let s=makeShurikenPhysical(name,players);const before=structuredClone(s.players);reject(s,'A',{type:'DISCARD_HIT_CHANTS',discard:true});s=until(act(s,'A',cmd(true,['B','C'])),s=>s.windows?.at(-1)?.kind==='on-hit-choice');expect(s.windows!.at(-1)!.continuation).toMatchObject({kind:'group',targetId:'B'});expect(s.players.B!.chants).toEqual(before.B!.chants);for(const id of CHANTS)expect(JSON.stringify(viewFor(s,'A'))).not.toContain(id);reject(s,'B',{type:'DISCARD_HIT_CHANTS',discard:true});reject(s,'A',{type:'DISCARD_HIT_CHANTS',discard:true,cardInstanceIds:[CHANTS[0]]});reject(s,'A',{type:'DISCARD_HIT_CHANTS',discard:true,targetId:'C'});s=act(s,'A',{type:'DISCARD_HIT_CHANTS',discard:name==='shuriken-mixed'});reject(s,'A',{type:'DISCARD_HIT_CHANTS',discard:true});s=until(s,s=>s.windows?.at(-1)?.kind==='on-hit-choice');expect(s.windows!.at(-1)!.continuation).toMatchObject({kind:'group',targetId:'C'});s=finish(s).s;expect(s.players.B!.chants).toEqual(name==='shuriken-mixed'?[]:before.B!.chants);expect(s.players.C!.chants).toEqual(before.C!.chants);expect(s.players.B!.damage).toBe(5);expect(s.players.C!.damage).toBe(5);});
it.each(['shuriken-maai','shuriken-evade'] as const)('%s actual defended target keeps two chants and hidden Metal while the other target may discard its real chant',name=>{let s=makeShurikenPhysical(name,players);const before=structuredClone(s.players);s=until(act(s,'A',cmd(true,['B','C'])),s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',name==='shuriken-maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});const result=finish(s,()=>true);s=result.s;expect(result.choices).toBe(1);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.chants).toEqual(before.B!.chants);expect(s.players.B!.followers).toEqual(before.B!.followers);expect(s.players.C!.damage).toBe(5);expect(s.players.C!.chants).toEqual([]);});
it('fate actual declaration cancellation consumes Shuriken once without numeric damage roll or any hit choice',()=>{let s=makeShurikenPhysical('shuriken-fate',players);const before=structuredClone(s.players);s=act(s,'A',cmd(true,['B','C']));const id=s.windows!.at(-1)!.continuation.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');const done=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}),()=>true);expect(done.choices).toBe(0);s=done.s;expect(s.players.B).toEqual(before.B);expect(s.players.C).toEqual(before.C);expect(s.rolls?.length??0).toBe(0);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);});
it.each(['shuriken-counter-ordinary','shuriken-counter-equal','shuriken-counter-dedicated'] as const)('%s actual incoming attack can be countered with printed level comparison and dedicated returned hit has its own chant choice',name=>{let s=makeShurikenPhysical(name,players);const m=shurikenMode(name),hand=[...s.players.A!.hand];expect(viewFor(s,'A').currentAttack!.attackerId).toBe('B');s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:m.dedicated});expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));const done=finish(s,()=>true);s=done.s;expect(s.players.A!.damage).toBe(0);expect(s.players.B!.damage).toBe(name==='shuriken-counter-equal'?0:5);expect(done.choices).toBe(m.dedicated?1:0);if(m.dedicated){expect(s.players.B!.chants).toEqual([]);expect(s.players.B!.followers[0]!.revealed).toBe(false);}expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);});
it('actual higher incoming warrior5 rejects ordinary Shuriken4 before payment but elected Ida6 can return it and discard actual prepared chants',()=>{let s=makeShurikenPhysical('shuriken-counter-dedicated',players,{warrior:4,incoming:'a2-p08-r1c1'});reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:false});s=finish(act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true}),()=>true).s;expect(s.players.A!.damage).toBe(0);expect(s.players.B!.damage).toBe(5);expect(s.players.B!.chants).toEqual([]);});
it('actual Fate cancels the dedicated counter declaration and resumes incoming damage while preserving target chants',()=>{let s=makeShurikenPhysical('shuriken-counter-dedicated',players);const before=structuredClone(s.players.B!.chants);s=act(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated:true});const id=s.windows!.at(-1)!.continuation.id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id})).s;expect(s.players.A!.damage).toBe(4);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.chants).toEqual(before);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);});
it('wrong owner malformed targets wrong phase mode and actual stopped recovery cannot forge Shuriken while declining preserves source',()=>{let s=makeShurikenPhysical('shuriken-wrong-owner',players,{warrior:4});reject(s,'A',cmd(true));for(const ids of [[],['A'],['B','B'],['missing']])reject(s,'A',cmd(false,ids));reject(s,'B',cmd(false));s=finish(act(s,'A',cmd())).s;expect(discardIds(s)).toContain(CARD);s=makeShurikenPhysical('shuriken-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd(false));reject(s,'A',cmd(true));s=makeShurikenPhysical('shuriken-decline',players,{beforeStart:true});reject(s,'A',cmd());s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
