import {getAction} from '@madou/catalog';
import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSilencePhysicalScenario} from './fixtures/silence-physical-scenarios.js';
const CARD='a2-p18-r1c1',CHANT='a2-p14-r2c3',players=['A','B','C','D'].map(id=>({id,name:id})),attack={type:'ATTACK' as const,cardInstanceId:CARD,targetIds:['B'],dedicated:false};
function reject(s:GameState,actorId:string,command:unknown,code?:string){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id)),r=transition(s,{actorId,command} as never,entropy());expect(r.ok).toBe(false);if(code)expect(r).toMatchObject({code});expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function settle(s:GameState,faces=[6,6]){for(let n=0;n<400&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)&&r.stage==='before-roll'?faces:Array(30).fill(1));}expect(s.windows??[]).toEqual([]);return s;}
function next(s:GameState,target='B',phase='action'){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w){s=settle(s);continue;}if(id===target&&s.phase===phase)return s;if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>![CARD,CHANT,'a2-p15-r3c2','a2-p05-r2c3','a2-p12-r2c2','a2-p12-r3c2','a2-p14-r2c1','a2-p07-r3c3','a2-p02-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SILENCE_TURN');}throw Error('SILENCE_LIMIT');}
function prepared(s:GameState){s=next(act(s,'A',{type:'PASS_ACTION'}));s=act(s,'B',{type:'CHANT',cardInstanceId:CHANT});return next(s,'A');}
it.each([5,6])('actual Silence magic%s use boundary and initial minus2 success bypass both real followers without damage',level=>{
 let s=makeSilencePhysicalScenario('silence-physical-resist',players,{level,spirit:6});const followers=structuredClone(s.players.B!.followers);reject(s,'A',{type:'CHANT',cardInstanceId:CARD});s=act(s,'A',attack);const f=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:6,effectLevel:6,damage:null,attributes:['魔','精'],followerIgnore:true,chant:false,onHitStatus:{kind:'silenced',modifiers:[-2,-1]}});expect(f.checkSpecs).toHaveLength(6-level);s=settle(s,[2,2]);expect(s.rolls!.find(r=>r.purpose==='status-resistance')).toMatchObject({rollerId:'B',modifier:-2,threshold:4,success:true,faces:[2,2]});expect(s.players.B!.damage).toBe(0);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.B!.followers).toEqual(followers);expect(discardIds(s).filter(x=>x===CARD)).toHaveLength(1);
});
it.each([[2,2],[2,3]] as const)('actual initial resistance %s,%s uses minus2 and only failure creates source-owned silence',(one,two)=>{
 const s=settle(act(makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6}),'A',attack),[one,two]);expect(s.players.B!.statuses??[]).toEqual(two===2?[]:[expect.objectContaining({kind:'silenced',modifiers:[-2,-1],nextCheck:1,sourceActorId:'A',sourceCardInstanceId:CARD,targetId:'B'})]);expect(s.players.B!.damage).toBe(0);
});
it.each([0,1,2])('actual Guardian7 cancels follower ignore and Prayer%s distinguishes below equal and hit',bonus=>{
 let s=act(makeSilencePhysicalScenario('silence-physical-resist',players,{guardian:true,spirit:6}),'A',attack);if(bonus){s=until(s,'effect-level');s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id});while(s.windows?.at(-1)?.kind!=='normal-defense')s=pass(s,Array(30).fill(bonus));expect(s.rolls!.find(r=>r.purpose==='prayer-addition')!.faces).toEqual([bonus]);}s=settle(s);expect(s.players.B!.followers).toHaveLength(bonus===0?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toHaveLength(bonus===2?1:0);expect((s.players.B!.statuses??[]).length).toBe(bonus===2?1:0);expect(s.players.B!.damage).toBe(0);
});
it('actual use failure and Fate cancellation leave target free of resistance or status',()=>{
 let s=until(act(makeSilencePhysicalScenario('silence-physical-resist',players,{level:5}),'A',attack),'before-roll');s=finish(closeWindow(s,[6,6]));expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance')).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);s=act(makeSilencePhysicalScenario('silence-physical-cancel',players),'A',attack);const id=Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.rolls??[]).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.players.B!.followers).toHaveLength(2);expect(discardIds(s).filter(x=>x===CARD)).toHaveLength(1);
});
it('actual failed recovery keeps magic attack new CHANT and existing CHANT prohibited while warrior attack remains legal',()=>{
 let s=settle(act(prepared(makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6,kit:'forms'})),'A',attack));s=next(s);const chants=structuredClone(s.players.B!.chants);expect(chants).toContainEqual({cardInstanceId:CHANT,revealed:false});for(const cardInstanceId of ['a2-p12-r2c2',CHANT])reject(s,'B',{type:'ATTACK',cardInstanceId,targetIds:['A'],dedicated:false},'SILENCED');reject(s,'B',{type:'CHANT',cardInstanceId:'a2-p14-r2c1'},'SILENCED');expect(s.players.B!.chants).toEqual(chants);s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p07-r3c3',targetIds:['A'],dedicated:false}));expect(s.players.A!.damage).toBe(10);expect(s.players.B!.statuses!.some(x=>x.kind==='silenced')).toBe(true);expect(s.players.B!.chants).toEqual(chants);
});
it('actual silence rejects magic follower attack and magic defense or chanted counter but preserves passive followers',()=>{
 const initial=makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6,cult:true}),legal=next(act(initial,'A',{type:'PASS_ACTION'}));expect(finish(act(legal,'B',{type:'ATTACK',cardInstanceId:'a2-p21-r3c1',targetIds:['A'],dedicated:true})).players.A!.damage).toBe(2);let s=settle(act(prepared(initial),'A',attack));s=next(s);reject(s,'B',{type:'ATTACK',cardInstanceId:'a2-p21-r3c1',targetIds:['A'],dedicated:true},'SILENCED');s=next(act(s,'B',{type:'PASS_ACTION'}),'A');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p15-r3c2',targetIds:['B'],dedicated:false}),'normal-defense');for(const cardInstanceId of ['a2-p12-r3c2',CHANT])reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId,dedicated:false},'SILENCED');s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.B!.chants).toContainEqual({cardInstanceId:CHANT,revealed:false});
});
it('actual repeated own-turn recovery uses minus1 until success and retains original chants and zero damage',()=>{
 let s=settle(act(prepared(makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6})),'A',attack));const status=s.players.B!.statuses![0]!,chants=structuredClone(s.players.B!.chants);for(const faces of [[6,6],[2,3]]){s=next(s,'B','turn-start');s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',rollerId:'B',modifier:-1,faces:[]});s=settle(s,faces);expect(s.phase).toBe('draw');expect(s.players.B!.damage).toBe(0);expect(s.players.B!.chants).toEqual(chants);if(faces[0]===6){expect(s.players.B!.statuses![0]).toMatchObject({id:status.id,nextCheck:2});s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});s=act(s,'B',{type:'PASS_ACTION'});}else expect(s.players.B!.statuses).toEqual([]);}expect(s.rolls!.filter(r=>r.purpose==='status-recovery').map(r=>({modifier:r.modifier,threshold:r.threshold,success:r.success}))).toEqual([{modifier:-1,threshold:5,success:false},{modifier:-1,threshold:5,success:true}]);s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:CHANT,targetIds:['A'],dedicated:false}));expect(s.players.A!.damage).toBe(16);expect(s.players.B!.chants).toEqual([]);
});
it('actual Fire Arrow damage then Silence and potion healing recovers HP without removing silence',()=>{
 let s=finish(act(makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6,kit:'heal'}),'A',{type:'ATTACK',cardInstanceId:'a2-p15-r3c2',targetIds:['B'],dedicated:false}));expect(s.players.B!.damage).toBe(5);s=next(s,'A');s=settle(act(s,'A',attack));s=next(s);expect(s.players.B!.damage).toBe(5);const status=structuredClone(s.players.B!.statuses),potion=s.players.B!.hand.find(id=>getAction(id)!.name==='回復の薬')!;s=act(s,'B',{type:'PLAY_TURN_CARD',cardInstanceIds:[potion]});while(s.windows?.length)s=pass(s,Array(30).fill(6));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.statuses).toEqual(status);expect(discardIds(s)).toContain(potion);
});
it('actual Silence refuses dedication multi self empty duplicate foreign actor and turn-technique without payment',()=>{
 const s=makeSilencePhysicalScenario('silence-physical-resist',players);reject(s,'A',{...attack,dedicated:true});for(const targetIds of [[],['A'],['B','C'],['B','B'],['missing']])reject(s,'A',{...attack,targetIds});reject(s,'B',attack);reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:CARD,targetIds:['B'],dedicated:false});
});
it('actual revealed Aiel approaches and can use Ice Blade before Silence but loses only that magic use while silenced',()=>{
 let s=next(act(makeSilencePhysicalScenario('silence-physical-resist',players,{spirit:6,kit:'virtual'}),'A',{type:'PASS_ACTION'}));s=act(s,'B',{type:'REVEAL_CHARACTER'});s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r1c2',targetId:'A'}));expect(s.distances.B!.A).toBe('near');expect(s.phase).toBe('action');const command={type:'DECLARE_VIRTUAL_BLADE',abilityId:'c2-p04-r1c1-ab02',targetIds:['A']};expect(viewFor(s,'B').virtualBladeOptions.map(o=>o.abilityId)).toContain('c2-p04-r1c1-ab02');expect(finish(act(s,'B',command)).players.A!.damage).toBe(3);const stats=gameStats(s,'B');s=next(act(s,'B',{type:'PASS_ACTION'}),'A');s=settle(act(s,'A',attack));s=next(s);expect(gameStats(s,'B')).toEqual(stats);expect(s.players.B!.revealed).toBe(true);expect(s.distances.B!.A).toBe('near');expect(viewFor(s,'B').virtualBladeOptions).toEqual([]);reject(s,'B',command,'ABILITY_DISABLED');
});
