import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSingingShipPhysicalScenario,singingShipPhysicalMode,type SingingShipPhysicalScenario} from './fixtures/singing-ship-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['ship-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SINGING_SHIP_TURN');}throw Error('SINGING_SHIP_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p20-r2c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=singingShipPhysicalMode(scenario);let s=makeSingingShipPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=singingShipPhysicalMode(scenario);let s=ready(makeSingingShipPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=singingShipPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeSingingShipPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=singingShipPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeSingingShipPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=singingShipPhysicalMode(scenario);let s=until(incoming(ready(makeSingingShipPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=singingShipPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeSingingShipPhysicalScenario(scenario,players,{owner:'魔聖母ディア'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});
it.each(['ship-earth','ship-earth-rear','ship-earth-ignore'] as const)('%s actual Earth Spear reaches only its local ship and paid Tia surprise disables nullification',scenario=>{
 const m=singingShipPhysicalMode(scenario);let s=ready(makeSingingShipPhysicalScenario(scenario,players),m.card,true,m.rear);if(m.rear)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=next(s);if(m.ignore)s=act(s,'B',{type:'REVEAL_CHARACTER'});s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p16-r2c3',targetIds:m.rear||m.ignore?['A']:['A','C'],dedicated:!m.rear&&!m.ignore});if(m.ignore){s=until(s,'follower-entry-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r1c1-ab02')!;expect(o.costCardInstanceIds).toContain('a2-p24-r2c1');s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,costCardInstanceId:'a2-p24-r2c1'});}
 s=until(s,'follower-start');const g=Object.values(s.groups!)[0]!,t=g.targets.find(t=>t.actorId==='A')!;expect(g.technique).toMatchObject({school:'magic',attributes:expect.arrayContaining(['地']),effectLevel:4,damage:m.rear||m.ignore?6:9});expect(t.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===m.card)!.descriptor).toMatchObject({earthMagicNullify:true,level:4,hp:2});s=until(s,'hit');const done=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===m.card)!;expect(done.hits.map(h=>h.outcome)).toEqual(m.rear?[]:m.ignore?['passed-through']:['earth-nullified']);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.ignore?[6,0]:m.rear?[0,0]:[0,9]);expect(s.players.A!.followers.some(f=>f.cardInstanceId===m.card)).toBe(true);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);if(m.rear||m.ignore)expect(s.players.A!.followers.find(f=>f.cardInstanceId===m.card)!.revealed).toBe(false);if(m.ignore)expect(discardIds(s).filter(id=>id==='a2-p24-r2c1')).toHaveLength(1);
});
const dedicatedRows=['ship-ded-hand','ship-ded-field'] as const;
it.each(dedicatedRows)('%s actual Asfelt hand or field magic attack waives checks at magic zero and accepts every nonempty selected subset',scenario=>{
 const m=singingShipPhysicalMode(scenario);for(const targets of [['B'],['C'],['D'],['B','C'],['B','D'],['C','D'],['B','C','D']]){let s=ready(makeSingingShipPhysicalScenario(scenario,players,{magic:0}),m.card,m.initial);for(const bad of [[],['A'],['B','B'],['missing']])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:bad,dedicated:true});s=act(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:targets,dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(a.checks).toEqual([]);expect(a.technique).toMatchObject({school:'magic',range:'far',useLevel:5,effectLevel:5,damageFormula:'2d6',noChecks:true,attributes:['遠','魔','科'],target:'all'});expect(a.technique.counterProhibited??false).toBe(false);expect(s.resolution).toContain(m.card);expect(s.players.A!.followers).toEqual([]);s=until(s,'damage');s=closeWindow(s,[2,5]);expect(s.rolls!.at(-1)!).toMatchObject({purpose:'attack-damage',faces:[2,5],total:7});s=until(s,'normal-defense');expect(viewFor(s,'B').currentAction!.technique!.damage).toBe(7);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual(['B','C','D'].map(id=>targets.includes(id)?7:0));expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(m.card);}
});
it.each(dedicatedRows)('%s actual dedicated Fate cancellation disposes paid source without returning it to followers',scenario=>{
 const m=singingShipPhysicalMode(scenario);let s=ready(makeSingingShipPhysicalScenario(scenario,players),m.card,m.initial);s=act(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B','C'],dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(m.card);
});
it('actual Army uses only hand ordinary ship magic5 two dice with checks below printed use level',()=>{
 for(const magic of [4,5]){let s=ready(makeSingingShipPhysicalScenario('ship-army',players,{magic}),'a2-p20-r2c1',false);s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c1',targetIds:['B']});const a=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r2c1')!;expect(a.checks).toHaveLength(5-magic);expect(a.technique).toMatchObject({school:'magic',range:'far',useLevel:5,effectLevel:5,damageFormula:'2d6',noChecks:false,attributes:['遠','魔','科'],target:'one'});s=until(s,'damage');s=closeWindow(s,[3,5]);expect(s.rolls!.at(-1)!).toMatchObject({purpose:'attack-damage',faces:[3,5],total:8});s=finish(s);expect(s.players.B!.damage).toBe(8);for(const id of ['a2-p20-r2c1','a2-p05-r2c2'])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);}
 let s=ready(makeSingingShipPhysicalScenario('ship-army',players),'a2-p20-r2c1');expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId==='a2-p20-r2c1')).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c1',targetIds:['B']});
});
it.each(['parent','child','use-failure'] as const)('actual Army ship %s cancellation spends both cards and does not return the follower',failure=>{
 let s=ready(makeSingingShipPhysicalScenario('ship-army',players,{magic:4}),'a2-p20-r2c1',false);s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c1',targetIds:['B']});if(failure==='child')s=closeWindow(s);if(failure==='use-failure')s=until(s,'before-roll');const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(failure==='parent'?'a2-p05-r2c2':'a2-p20-r2c1'))!,r=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',failure==='use-failure'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:r!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);for(const id of ['a2-p20-r2c1','a2-p05-r2c2'])expect(discardIds(s).filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);
});
it('actual ship dedicated attack remains counterable and maai only cancels its local selected target',()=>{
 for(const mode of ['mirror','maai']){let s=ready(makeSingingShipPhysicalScenario('ship-ded-hand',players),'a2-p20-r2c1',false);s=until(act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p20-r2c1',targetIds:['B','C'],dedicated:true}),'normal-defense');if(mode==='mirror')s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});else s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'});s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(2);expect(discardIds(s).filter(x=>x==='a2-p20-r2c1')).toHaveLength(1);}
});
it('actual paid approach also permits ship far magic at near distance without extra checks',()=>{
 let s=ready(makeSingingShipPhysicalScenario('ship-ded-hand',players,{magic:0}),'a2-p20-r2c1',false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',{type:'ATTACK',cardInstanceId:'a2-p20-r2c1',targetIds:['B'],dedicated:true});expect(Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r2c1')!.checks).toEqual([]);s=finish(s);expect(s.players.B!.damage).toBe(2);expect(discardIds(s).filter(id=>id==='a2-p20-r2c1')).toHaveLength(1);
});
