import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSkeletonPhysicalScenario} from './fixtures/skeleton-physical-scenarios.js';
const SK='a2-p19-r2c1',METAL='a2-p22-r1c1',ARMY='a2-p05-r2c2',DWARF='a2-p21-r2c3',SAINT='a2-p21-r2c1',KNIGHT='a2-p20-r1c2',players=['A','B','C','D'].map(id=>({id,name:id}));
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card=SK,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3','a2-p21-r2c1','a2-p20-r1c2','a2-p12-r1c1'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('ORC_FORT_TURN');}throw Error('ORC_FORT_LIMIT');}
function bundle(s:GameState,ids=[DWARF]){const o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;return act(s,'B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:ids.map(cardInstanceId=>({cardInstanceId,dedicated:false,targetIds:['A']}))});}
function approach(s:GameState,actor='B'){return finish(act(s,actor,{type:'APPROACH',cardInstanceId:actor==='B'?'a2-p24-r2c1':'a2-p24-r1c3',targetId:actor==='B'?'A':'B'}));}
function defense(level=4,rear=false){return approach(next(ready(makeSkeletonPhysicalScenario('skeleton-defense-revive',players,{level}),SK,true,rear)));}
it.each([false,true])('actual Skeleton placement initial=%s and own-action order removal preserve private physical source',initial=>{
 let s=makeSkeletonPhysicalScenario('skeleton-defense-revive',players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:SK});s=ready(s,SK,initial);if(!initial)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK,METAL]});
 expect(s.players.A!.followers[0]).toMatchObject({cardInstanceId:SK,revealed:false,placedById:'A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(SK);
 if(initial){reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK,SK]});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[SK,METAL]});}
 s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[METAL,SK]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([METAL,SK]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[METAL]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([METAL]);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);
});
it.each([2,3,4,5])('actual Dwarf three hits level%i freezes Skeleton3 HP4 and applies group-end revival threshold4',level=>{
 let s=until(bundle(defense(level)),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(f.descriptor).toMatchObject({level:3,hp:4,attributes:['死'],revivalLimit:4});expect(f.levels).toEqual([3,3,3]);expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=until(s,'hit');expect(t.hits).toHaveLength(3);const live=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(live.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(level>3?4:0));expect(live.revivalForbidden).toBe(level>4);s=finish(s);expect(s.players.A!.damage).toBe(level>3?6:0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(level>4?[]:[SK]);expect(s.discard.filter(x=>x===SK)).toHaveLength(level>4?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(['front','rear'])('actual Skeleton revival keeps original %s position and no same-group reentry before later Bow group',position=>{
 let s=ready(makeSkeletonPhysicalScenario('skeleton-defense-revive',players),SK,true,true);if(position==='rear')s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[METAL,SK]});s=until(bundle(approach(next(s))),'follower-start');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense!.filter(f=>f.source==='physical'&&f.cardInstanceId===SK)).toHaveLength(1);s=finish(s);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(position==='front'?[SK,METAL]:[METAL,SK]);expect(s.players.A!.damage).toBe(0);if(position==='rear')expect(s.players.A!.followers[1]!.revealed).toBe(false);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(position==='front'?[SK,METAL]:[METAL,SK]);expect(s.players.A!.damage).toBe(0);expect(s.discard).not.toContain(SK);
});
it.each(['safe','over-last','over-first'])('actual mixed Dia group %s determines Skeleton revival across every constituent',mode=>{
 const ids=mode==='safe'?[DWARF,KNIGHT]:mode==='over-last'?[DWARF,SAINT]:[SAINT,DWARF];let s=until(bundle(defense(),ids),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.hits).toHaveLength(4);expect(t.hits.map(h=>h.technique!.effectLevel)).toEqual(mode==='safe'?[4,4,4,4]:mode==='over-last'?[4,4,4,5]:[5,4,4,4]);s=until(s,'hit');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.hits.map(h=>h.hpReduction)).toEqual([4,4,4,4]);s=finish(s);expect(s.players.A!.damage).toBe(mode==='safe'?7:8);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(mode==='safe'?[SK]:[]);expect(s.discard.filter(x=>x===SK)).toHaveLength(mode==='safe'?0:1);
});
it('actual Mountain Breaker4 destroys dead Skeleton without HP or revival even within printed cap',()=>{
 let s=approach(next(ready(makeSkeletonPhysicalScenario('skeleton-defense-destroy',players))));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p12-r1c1',targetIds:['A'],dedicated:false}),'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits).toEqual([{hitIndex:0,outcome:'attribute-destroyed',hpReduction:0}]);expect(f.revivalForbidden).toBe(true);s=finish(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);
});
it('actual maai avoids Skeleton final defense and keeps hidden source',()=>{let s=next(ready(makeSkeletonPhysicalScenario('skeleton-defense-equal',players)));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:SK,revealed:false}));expect(s.players.A!.damage).toBe(0);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(SK);expect(s.discard).not.toContain(SK);});
it.each(['skeleton-attack-hand','skeleton-attack-field'] as const)('%s actual Gadyura far selected targets no checks retains warrior2 damage2 and spends once',scenario=>{
 for(const targets of [['B'],['C'],['B','C'],['B','C','D']]){let s=ready(makeSkeletonPhysicalScenario(scenario,players,{warrior:0}),SK,scenario.endsWith('field'));reject(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:targets,dedicated:false});reject(s,'A',{type:'CHANT',cardInstanceId:SK});s=act(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:targets,dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===SK)!;expect(a.checks).toEqual([]);expect(a.technique).toMatchObject({range:'far',useLevel:2,effectLevel:2,damage:2,noChecks:true,counterProhibited:true,chant:false,attributes:['遠','戦','棒']});expect(s.resolution).toContain(SK);expect(s.players.A!.followers).toEqual([]);s=finish(s);for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(targets.includes(id)?2:0);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(SK);}
});
it.each([1,2])('actual All Army uses ordinary Skeleton hand bottom with warrior%i and checks not dedicated waiver',warrior=>{
 let s=ready(makeSkeletonPhysicalScenario('skeleton-army',players,{warrior}),SK,false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:SK,targetIds:['B']});s=approach(s,'A');s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:SK,targetIds:['B']});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===SK)!;expect(a.checks).toHaveLength(2-warrior);expect(a.technique).toMatchObject({range:'near',useLevel:2,effectLevel:2,damage:2,noChecks:false,attributes:['近','戦','棒']});expect(a.technique.counterProhibited??false).toBe(false);expect(s.resolution).toEqual(expect.arrayContaining([SK,ARMY]));s=finish(s);expect(s.players.B!.damage).toBe(2);for(const id of [SK,ARMY])expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);
});
it('actual placed Skeleton is not eligible for hand-only All Army or Dia human permission',()=>{
 let s=ready(makeSkeletonPhysicalScenario('skeleton-attack-field',players,{owner:'魔聖母ディア'}));s=approach(s,'A');expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===SK)).toBe(false);expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===SK)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:SK,targetIds:['B']});reject(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber}-A-action`,sources:[{cardInstanceId:SK,dedicated:false,targetIds:['B']}]});reject(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B'],dedicated:true});
});
it.each([false,true])('actual ordinary versus dedicated Skeleton selected=%s changes Mirror counter legality',dedicated=>{
 let s=ready(makeSkeletonPhysicalScenario('skeleton-army',players),SK,false);if(!dedicated)s=approach(s,'A');s=until(act(s,'A',dedicated?{type:'ATTACK',cardInstanceId:SK,targetIds:['B'],dedicated:true}:{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:SK,targetIds:['B']}),'normal-defense');const c={type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false};if(dedicated)reject(s,'B',c);else s=act(s,'B',c);s=finish(s);expect(s.players.B!.damage).toBe(dedicated?2:0);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);
});
it.each(['skeleton-attack-hand','skeleton-attack-field'] as const)('%s actual Fate cancellation and malformed targets never revive spent attack source',scenario=>{
 let s=ready(makeSkeletonPhysicalScenario(scenario,players),SK,scenario.endsWith('field'));for(const targets of [[],['A'],['B','B'],['missing']])reject(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:targets,dedicated:true});s=act(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B','C'],dedicated:true});const a=Object.values(s.actions!).find(a=>a.cardInstanceId===SK)!;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(SK);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);
});
it('actual Gadyura Skeleton remains usable after paid near approach and maai protects only selected B',()=>{
 let s=approach(ready(makeSkeletonPhysicalScenario('skeleton-attack-maai',players,{warrior:0}),SK,false),'A');s=until(act(s,'A',{type:'ATTACK',cardInstanceId:SK,targetIds:['B','C'],dedicated:true}),'normal-defense');s=finish(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(2);expect(s.discard.filter(x=>x===SK)).toHaveLength(1);
});
it.each(['parent','child','use-failure'])('actual All Army %s failure pays both physical cards and does not revive Skeleton',mode=>{
 let s=approach(ready(makeSkeletonPhysicalScenario('skeleton-army',players,{warrior:1}),SK,false),'A');s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:ARMY,followerCardInstanceId:SK,targetIds:['B']});if(mode==='child')s=closeWindow(s);if(mode==='use-failure')s=until(s,'before-roll');const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?ARMY:SK))!;const roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='use-failure'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of [SK,ARMY]){expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(id);}expect(s.resolution).toEqual([]);
});

it.each([0,3])('structural destruction at hit%i prevents revival while every other saved hit keeps follower HP',index=>{
 let s=until(bundle(defense(),[DWARF,KNIGHT]),'follower-start');
 const t=Object.values(s.groups!)[0]!.targets[0]!;
 // Explicit mixed-effect resolver input, not a claim about the printed grant sources.
 const h=t.hits[index]!;
 h.technique={...structuredClone(h.technique!),destroyFollowerAttributes:['死']};
 s=JSON.parse(JSON.stringify(s)) as GameState;
 s=until(s,'hit');
 const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;
 expect(f.revivalForbidden).toBe(true);
 expect(f.hits.map(h=>h.hpReduction)).toEqual(Array.from({length:4},(_,i)=>i===index?0:4));
 expect(f.hits[index]!.outcome).toBe('attribute-destroyed');
 s=finish(JSON.parse(JSON.stringify(s)) as GameState);
 expect(s.players.A!.damage).toBe(11);
 expect(s.players.A!.followers).toEqual([]);
 expect(s.discard.filter(id=>id===SK)).toHaveLength(1);
});
