import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSlayingFistPhysical,slayingFistCard as CARD,slayingFistMode} from './fixtures/slaying-fist-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s);}throw Error('SLAYING_FIST_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['slaying-fist-ordinary','slaying-fist-owner-ordinary','slaying-fist-dedicated','slaying-fist-same-faction','slaying-fist-suppressed','slaying-fist-silenced'] as const)('%s actual approached physical strike preserves eight level fixed ten one Maai and optional Gil mode',name=>{let s=makeSlayingFistPhysical(name,players);const m=slayingFistMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],rolls=s.rolls?.length??0;expect(s.distances.A!.B).toBe('near');expect(gameStats(s,'A').spirit).toBe(6);expect(gameStats(s,'B').spirit).toBe(11);if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='damage');expect(source(s).technique.damage).toBe(10);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'near',useLevel:8,effectLevel:8,damage:10,attributes:['戦','格','白'],destroyFollowerAttributes:['黒','死'],target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(group(s).technique.maaiRequired??1).toBe(1);expect(group(s).technique.characterImmunityExceptions??[]).toEqual([]);expect(group(s).technique.characterDamageMultipliers??[]).toEqual(m.dedicated?[{characterNames:['不死王ガドューラ','魔聖母ディア'],multiplier:2}]:[]);s=settle(s);expect(s.players.B!.damage).toBe(10);expect(s.players.C!.damage).toBe(0);expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);});
it.each([[false,0],[false,1],[false,12],[true,0],[true,1],[true,12]] as const)('actual caster spirit boundary dedicated=%s spirit%s preserves fixed ten independent of either spirit',(dedicated,spirit)=>{let s=makeSlayingFistPhysical(dedicated?'slaying-fist-dedicated':'slaying-fist-ordinary',players,{spirit});expect(gameStats(s,'A').warrior_level).toBe(dedicated?0:8);s=until(act(s,'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(10);expect(group(s).targets[0]!.hits[0]!.damage).toBe(10);s=settle(s);expect(s.players.B!.damage).toBe(10);expect(s.rolls??[]).toHaveLength(0);});
it.each([['slaying-fist-water',6,false],['slaying-fist-metal',5,false],['slaying-fist-lower',8,false]] as const)('%s actual follower level boundary yields%s and survives=%s without follower bypass',(name,damage,survives)=>{let s=settle(act(makeSlayingFistPhysical(name,players),'A',cmd(true)));expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(survives?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(name==='slaying-fist-water'?1:0);if(!survives)expect(s.discard).toContain(slayingFistMode(name).follower);});
it.each(['slaying-fist-maai-one-ordinary','slaying-fist-maai-one-dedicated'] as const)('%s actual single physical Maai avoids both modes without extra cost',name=>{const m=slayingFistMode(name);let s=until(act(makeSlayingFistPhysical(name,players),'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');s=settle(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}));expect(s.players.B!.damage).toBe(0);expect(s.discard.filter(id=>id==='a2-p06-r1c3')).toHaveLength(1);expect(s.players.B!.hand).toContain('a2-p06-r2c1');expect(s.distances.A!.B).toBe('near');});
it.each([false,true] as const)('actual physical strike allows Evade in both selected modes dedicated=%s',dedicated=>{let s=until(act(makeSlayingFistPhysical(dedicated?'slaying-fist-evade-dedicated':'slaying-fist-evade-ordinary',players),'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);s=settle(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.discard.filter(id=>id==='a2-p05-r3c1')).toHaveLength(1);});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior7 spirit6 actual shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeSlayingFistPhysical('slaying-fist-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?10:0);expect(s.rolls).toHaveLength(1);});
it.each([false,true] as const)('actual far target rejects until real approach enables near strike dedicated=%s',dedicated=>{let s=makeSlayingFistPhysical('slaying-fist-far',players,{warrior:8});reject(s,'A',cmd(dedicated));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(dedicated)));expect(s.players.B!.damage).toBe(10);});
it('actual Fate source cancellation spends source once before spirit value or hit',()=>{let s=act(makeSlayingFistPhysical('slaying-fist-fate',players),'A',cmd(true));const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId}));expect(s.players.B!.damage).toBe(0);expect(s.rolls??[]).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual incoming Bow refuses normal and dedicated attack-only strike',()=>{let s=makeSlayingFistPhysical('slaying-fist-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner malformed targets foreign actor unused timing and stopped turn reject unpaid',()=>{const s=makeSlayingFistPhysical('slaying-fist-wrong-owner',players,{warrior:8});reject(s,'A',cmd(true));for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(10);let t=makeSlayingFistPhysical('slaying-fist-decline',players,{beforeStart:true});reject(t,'A',cmd());t=act(t,'A',{type:'START_TURN'});reject(t,'A',cmd());t=act(t,'A',{type:'CHOOSE_DRAW',draw:false});reject(t,'A',{type:'REST',cardInstanceIds:[CARD]});reject(t,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});t=act(t,'A',{type:'PASS_ACTION'});expect(t.players.A!.hand).toContain(CARD);t=makeSlayingFistPhysical('slaying-fist-stopped',players);expect(t.seatOrder[t.turnSeat]).not.toBe('A');reject(t,'A',cmd(true));expect(t.players.A!.hand).toContain(CARD);});
it.each(['slaying-fist-black-ordinary','slaying-fist-black-dedicated','slaying-fist-dead-ordinary','slaying-fist-dead-dedicated'] as const)('%s actual black or dead follower destruction precedes morale level and HP without reaching other player',name=>{let s=makeSlayingFistPhysical(name,players);const m=slayingFistMode(name),other=structuredClone(s.players.C!.followers);s=until(act(s,'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='follower-start');s=closeWindow(s);expect(group(s).targets[0]!.followerDefense![0]!.hits[0]).toMatchObject({outcome:'attribute-destroyed',hpReduction:0});expect(s.players.B!.followers).toHaveLength(0);expect(s.players.C!.followers).toEqual(other);s=settle(s);expect(s.players.B!.damage).toBe(10);expect(s.discard.filter(id=>id===m.follower)).toHaveLength(1);expect(s.rolls??[]).toHaveLength(0);expect(s.players.C!.followers).toEqual(other);});
it.each(['slaying-fist-black-maai','slaying-fist-dead-evade','slaying-fist-black-fate','slaying-fist-black-decline'] as const)('%s actual avoided cancelled or unused source leaves black and dead followers untouched',name=>{let s=makeSlayingFistPhysical(name,players);const m=slayingFistMode(name),followers=structuredClone(s.players.B!.followers),other=structuredClone(s.players.C!.followers);if(m.decline)s=act(s,'A',{type:'PASS_ACTION'});else{s=act(s,'A',cmd(m.dedicated));if(m.cancel){const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId});}else{s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',m.maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}s=settle(s);}expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toEqual(followers);expect(s.players.C!.followers).toEqual(other);expect(s.discard.filter(id=>id===CARD)).toHaveLength(m.decline?0:1);expect(s.players.A!.hand.includes(CARD)).toBe(m.decline);});
it('actual mandatory white prohibition rejects source Gadyura before payment',()=>{const s=makeSlayingFistPhysical('slaying-fist-white-prohibited',players);for(const dedicated of [false,true])reject(s,'A',cmd(dedicated));expect(s.players.A!.hand).toContain(CARD);});
it.each(['slaying-fist-gad-ordinary','slaying-fist-gad-dedicated','slaying-fist-dia-ordinary','slaying-fist-dia-dedicated','slaying-fist-gad-public','slaying-fist-dia-public','slaying-fist-gad-water','slaying-fist-dia-water','slaying-fist-gad-black','slaying-fist-dia-dead' ] as const)('%s actual named target multiplier fixes ten or twenty before follower HP without early identity reveal',name=>{let s=makeSlayingFistPhysical(name,players);const m=slayingFistMode(name),other=structuredClone(s.players.C!.followers);expect(s.players.B!.revealed).toBe(m.publicTarget);s=until(act(s,'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({effectLevel:8,damage:10});expect(group(s).targets[0]!.hits[0]!.damage).toBe(m.damage);expect(s.players.B!.revealed).toBe(m.publicTarget);if(!m.publicTarget)for(const id of ['A','C','D'])expect(viewFor(s,id).players.B!.characterId).toBeUndefined();s=settle(s);expect(s.players.B!.damage).toBe(m.damage-(m.water?4:0));expect(s.players.B!.revealed).toBe(true);expect(s.players.C!.damage).toBe(0);expect(s.players.C!.followers).toEqual(other);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);if(m.follower){expect(s.players.B!.followers).toHaveLength(0);expect(s.discard.filter(id=>id===m.follower)).toHaveLength(1);}expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.water?1:0);});
it.each(['slaying-fist-gad-maai','slaying-fist-dia-evade','slaying-fist-gad-fate','slaying-fist-dia-decline' ] as const)('%s actual named target avoidance cancellation or decline leaves identity hidden and deals zero',name=>{let s=makeSlayingFistPhysical(name,players);const m=slayingFistMode(name);if(m.decline)s=act(s,'A',{type:'PASS_ACTION'});else{s=act(s,'A',cmd(true));if(m.cancel){const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});}else{s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');expect(group(s).targets[0]!.hits[0]!.damage).toBe(20);s=act(s,'B',m.maai?{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}s=settle(s);}expect(s.players.B!.damage).toBe(0);expect(s.players.B!.revealed).toBe(false);for(const id of ['A','C','D'])expect(viewFor(s,id).players.B!.characterId).toBeUndefined();expect(s.discard.filter(id=>id===CARD)).toHaveLength(m.decline?0:1);expect(s.players.A!.hand.includes(CARD)).toBe(m.decline);});
