import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSmallAngelPhysicalScenario,smallAngelPhysicalMode,smallAngelPhysicalScenarios,type SmallAngelPhysicalScenario} from './fixtures/small-angel-physical-scenarios.js';
import {makeScenario} from './fixtures/game-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['small-angel-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('SMALL_ANGEL_TURN');}throw Error('SMALL_ANGEL_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p20-r2c2',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=smallAngelPhysicalMode(scenario);let s=makeSmallAngelPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=smallAngelPhysicalMode(scenario);let s=ready(makeSmallAngelPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=smallAngelPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeSmallAngelPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=smallAngelPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeSmallAngelPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=smallAngelPhysicalMode(scenario);let s=until(incoming(ready(makeSmallAngelPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual hand and field cannot invent direct attacks and Dia human grant excludes the nonhuman angel',scenario=>{
 const m=smallAngelPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeSmallAngelPhysicalScenario(scenario,players),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});{expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===m.card)).toBe(false);reject(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources:[{cardInstanceId:m.card,dedicated:false,targetIds:['B']}]});}}
});
it.each(['small-angel-magic4','small-angel-magic5','small-angel-magic6'] as const)('%s actual non-destroying magic uses Small Angel conditional5 with printed HP0',scenario=>{
 const m=smallAngelPhysicalMode(scenario);let s=next(ready(makeSmallAngelPhysicalScenario(scenario,players),m.card));const card=m.magicLevel===4?'a2-p17-r2c1':m.magicLevel===5?'a2-p17-r2c2':'a2-p18-r1c3';s=until(act(s,'B',{type:'ATTACK',cardInstanceId:card,targetIds:['A'],dedicated:false}),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.descriptor).toMatchObject({level:4,hp:0,attributes:['白','飛'],conditionalLevel:{kind:'magic',level:5}});expect(f.levels).toEqual([5]);s=finish(s);expect(s.players.A!.damage).toBe(m.magicLevel>5?8:0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.magicLevel<5?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.magicLevel<5?0:1);
});
it('actual mixed Dia group gives Small Angel physical4 and magic5 for each constituent without extra HP',()=>{
 let s=next(ready(makeSmallAngelPhysicalScenario('small-angel-mixed',players),'a2-p20-r2c2'));s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));const o=viewFor(s,'B').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;s=until(act(s,'B',{type:'USE_FOLLOWER_ATTACK',abilityId:o.abilityId,targetEventId:o.targetEventId,sources:['a2-p21-r2c3','a2-p21-r2c1'].map(cardInstanceId=>({cardInstanceId,dedicated:false,targetIds:['A']}))}),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.hits.map(h=>h.technique!.school)).toEqual(['warrior','warrior','warrior','magic']);expect(t.followerDefense![0]!.levels).toEqual([4,4,4,5]);s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(['lower-destroyed','lower-destroyed','lower-destroyed','equal-destroyed']);expect(f.hits.map(h=>h.hpReduction)).toEqual([0,0,0,0]);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.players.A!.followers).toEqual([]);expect(s.discard.filter(x=>x==='a2-p20-r2c2')).toHaveLength(1);
});
it.each([2,3])('actual Small Angel Army ordinary far magic3 damage4 uses own magic%i checks and also accepts real near approach',magic=>{
 for(const near of [false,true]){let s=ready(makeSmallAngelPhysicalScenario('small-angel-army',players,{magic}),'a2-p20-r2c2',false);if(near)s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c2',targetIds:['B']});const a=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p20-r2c2')!;expect(a.checks).toHaveLength(3-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:3,effectLevel:3,damage:4,attributes:['遠','魔','白'],noChecks:false});expect(s.resolution).toEqual(expect.arrayContaining(['a2-p20-r2c2','a2-p05-r2c2']));s=finish(s);expect(s.players.B!.damage).toBe(4);expect(s.players.A!.followers).toEqual([]);for(const id of ['a2-p20-r2c2','a2-p05-r2c2'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
});
it('actual placed Small Angel cannot use hand-only Army or invent dedication',()=>{
 const m=smallAngelPhysicalMode('small-angel-army');let s=ready(makeSmallAngelPhysicalScenario('small-angel-army',players),m.card);expect(s.players.A!.hand).toContain('a2-p05-r2c2');expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===m.card)).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:m.card,targetIds:['B']});reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated:true});
});
it.each(['parent','child','use-failure'])('actual Small Angel Army %s spends both cards without damage or returning follower',mode=>{
 let s=ready(makeSmallAngelPhysicalScenario('small-angel-army',players,{magic:2}),'a2-p20-r2c2',false);s=act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c2',targetIds:['B']});if(mode==='child')s=closeWindow(s);const parent=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?'a2-p05-r2c2':'a2-p20-r2c2'))!;if(mode==='use-failure')s=until(s,'before-roll');const roll=s.rolls?.at(-1);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode!=='use-failure'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:parent.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}));expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of ['a2-p20-r2c2','a2-p05-r2c2']){expect(s.discard.filter(x=>x===id)).toHaveLength(1);expect(s.players.A!.hand).not.toContain(id);}expect(s.resolution).toEqual([]);
});
it('actual Mirror reflects Small Angel Army magic after source payment so spent Small Angel cannot defend reflected hit',()=>{
 let s=ready(makeSmallAngelPhysicalScenario('small-angel-army-reflect',players),'a2-p20-r2c2',false);s=until(act(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c2',targetIds:['B']}),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}));expect(s.players.A!.damage).toBe(4);expect(s.players.B!.damage).toBe(0);expect(s.players.A!.followers).toEqual([]);for(const id of ['a2-p20-r2c2','a2-p05-r2c2'])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
it('actual Gadyura cannot attack through white Small Angel Army even with both physical cards in hand',()=>{
 const s=ready(makeSmallAngelPhysicalScenario('small-angel-army',players,{owner:'不死王ガドューラ'}),'a2-p20-r2c2',false);expect(s.players.A!.hand).toEqual(expect.arrayContaining(['a2-p05-r2c2','a2-p20-r2c2']));expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId==='a2-p20-r2c2')).toBe(false);reject(s,'A',{type:'PLAY_ALL_ARMY',cardInstanceId:'a2-p05-r2c2',followerCardInstanceId:'a2-p20-r2c2',targetIds:['B']});
});

it.each(smallAngelPhysicalScenarios)('%s scenario dispatch deals the Small Angel fixture', scenario => {
 const state=makeScenario(scenario,players);
 expect(state.players.A!.hand).toContain('a2-p20-r2c2');
 expect(state.players.A!.hand).not.toContain('a2-p22-r2c1');
});
