import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeStarBowPhysical,starBowCard as CARD,starBowMode,type StarBowScenario} from './fixtures/star-bow-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function until(s:GameState,done:(s:GameState)=>boolean,count=3){for(let n=0;n<900;n++){if(done(s))return s;s=pass(s,s.windows?.at(-1)?.kind==='damage'?[count]:Array(100).fill(1));}throw Error('STAR_BOW_LIMIT');}
function settle(s:GameState,count=3){return until(s,s=>!s.windows?.length,count);}
function command(name:StarBowScenario){const m=starBowMode(name);return {type:'ATTACK',cardInstanceId:CARD,targetIds:m.targets.map(i=>players[i]!.id),dedicated:m.dedicated};}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['star-bow-ordinary', 'star-bow-owner-ordinary', 'star-bow-low', 'star-bow-dedicated', 'star-bow-pair', 'star-bow-all', 'star-bow-near', 'star-bow-same-faction', 'star-bow-water-ordinary', 'star-bow-water-dedicated', 'star-bow-metal-ordinary', 'star-bow-metal-dedicated', 'star-bow-fort-ordinary', 'star-bow-fort-dedicated', 'star-bow-maai-one-ordinary', 'star-bow-maai-two-ordinary', 'star-bow-maai-one-dedicated', 'star-bow-maai-two-dedicated', 'star-bow-evade-ordinary', 'star-bow-evade-dedicated', 'star-bow-fate', 'star-bow-suppressed', 'star-bow-silenced', 'star-bow-stopped', 'star-bow-wrong-owner', 'star-bow-decline', 'star-bow-unprepared-ordinary', 'star-bow-unprepared-dedicated', 'star-bow-chant-ordinary', 'star-bow-chant-dedicated', 'star-bow-counter-ordinary', 'star-bow-counter-dedicated', 'star-bow-black-ordinary', 'star-bow-black-dedicated', 'star-bow-dead-ordinary', 'star-bow-dead-dedicated', 'star-bow-black-maai', 'star-bow-dead-fate', 'star-bow-white-prohibited', 'star-bow-water-blessed-ordinary', 'star-bow-water-blessed-dedicated'] as const)('%s actual chant and physical star bow retain restrictions and destruction union',name=>{
 let s=makeStarBowPhysical(name,players);const m=starBowMode(name),other=structuredClone(s.players.C!.followers);
 if(m.suffix==='stopped'){reject(s,'A',command(name));expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='decline'){s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='wrong-owner'||m.suffix==='white-prohibited'||m.suffix.startsWith('unprepared')){reject(s,'A',command(name));if(m.suffix==='white-prohibited')for(const dedicated of [false,true])reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated});return;}
 if(m.incoming){for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.chants.some(c=>c.cardInstanceId===CARD)).toBe(true);expect(discardIds(s)).not.toContain(CARD);return;}
 if(m.suffix.startsWith('chant-')){const hand=[...s.players.A!.hand];s=act(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));reject(s,'A',command(name));for(const id of ['B','C','D'])expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return;}
 if(m.suffix==='same-faction')reject(s,'A',{...command(name),targetIds:['C']});
 if(m.suffix.includes('blessed')){expect(s.players.B!.open).toContain('a2-p01-r2c1');expect(gameStats(s,'B').followerLevelBonus).toBe(1);}const hand=[...s.players.A!.hand],deck=[...s.deck];expect(s.players.A!.chants).toEqual([{cardInstanceId:CARD,revealed:false}]);s=act(s,'A',command(name));expect(s.players.A!.hand).toEqual(hand);expect(s.deck).toEqual(deck);expect(s.players.A!.chants).toEqual([]);expect(source(s).fromChant).toBe(true);
 if(m.cancel){const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);if(m.follower)expect(s.players.B!.followers[0]!.cardInstanceId).toBe(m.follower);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);return;}
 s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({range:'far',school:'warrior',useLevel:7,effectLevel:m.dedicated?8:7,damage:m.damage,attributes:['戦','弓','白','詠'],chant:true,counter:false,evadeProhibited:true,maaiRequired:2,noChecks:m.dedicated,target:m.dedicated?'all':'one',destroyFollowerAttributes:['黒','死']});expect(!!group(s).technique.destroyFollowersAtOrBelowEffectLevel).toBe(m.dedicated);expect(group(s).targets.map(t=>t.hits.map(h=>h.damage))).toEqual(m.targets.map(()=>[m.damage]));
 let damage=m.damage;if(m.maai||m.evade){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.evade){expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});}else{const count=m.suffix.includes('one')?1:2;for(const cardInstanceId of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId});}if(count===2)damage=0;}}
 if(m.follower&&damage){s=until(s,s=>s.windows?.at(-1)?.kind==='follower-start');s=closeWindow(s);const snapshot=group(s).targets[0]!.followerDefense![0]!;if(m.suffix.includes('blessed'))expect(snapshot.levels).toEqual([8]);const hit=snapshot.hits[0];if(m.black||m.dead)expect(hit).toMatchObject({outcome:'attribute-destroyed',hpReduction:0});else if(m.dedicated)expect(hit).toMatchObject({outcome:'level-destroyed',hpReduction:0});}
 s=settle(s);if(m.follower){if(damage===0){expect(s.players.B!.followers[0]!.cardInstanceId).toBe(m.follower);}else{if(!m.dedicated&&!m.black&&!m.dead)damage=m.water?0:m.metal?5:8;const survives=m.suffix==='water-blessed-ordinary';expect(s.players.B!.followers).toHaveLength(survives?1:0);expect(discardIds(s).filter(id=>id===m.follower)).toHaveLength(survives?0:1);}}
 expect(s.players.B!.damage).toBe(damage);expect(s.players.C!.followers).toEqual(other);for(const i of [2,3])expect(s.players[players[i]!.id]!.damage).toBe(m.targets.includes(i)?13:0);expect(s.players.A!.damage).toBe(0);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);expect((s.rolls??[]).filter(r=>['attack-hit-count','attack-damage'].includes(r.purpose))).toHaveLength(0);if(m.dedicated)expect((s.rolls??[]).filter(r=>['activation','excess-level','follower-morale'].includes(r.purpose))).toHaveLength(0);
});
it.each([[3,3,true],[3,4,false]] as const)('actual ordinary warrior6 spirit6 shortage %s plus %s success=%s consumes chant once',(x,y,success)=>{let s=act(makeStarBowPhysical('star-bow-low',players),'A',command('star-bow-low'));s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?10:0);expect(discardIds(s).filter(id=>id===CARD)).toHaveLength(1);});
it.each([['star-bow-ordinary',0],['star-bow-ordinary',12],['star-bow-dedicated',0],['star-bow-dedicated',12]] as const)('%s actual spirit%s fixed damage and optional use waiver',(name,spirit)=>{let s=makeStarBowPhysical(name,players,{spirit});expect(gameStats(s,'A').warrior_level).toBe(name.endsWith('dedicated')?0:7);s=settle(act(s,'A',command(name)));expect(s.players.B!.damage).toBe(name.endsWith('dedicated')?13:10);expect(s.rolls??[]).toHaveLength(0);});
it('actual ordinary rejects extra targets and all modes reject malformed owner actor timing without payment',()=>{const s=makeStarBowPhysical('star-bow-ordinary',players);for(const targetIds of [[],['A'],['B','B'],['B','C'],['missing']])reject(s,'A',{...command('star-bow-ordinary'),targetIds});reject(s,'B',command('star-bow-ordinary'));const t=makeStarBowPhysical('star-bow-dedicated',players);for(const targetIds of [[],['A'],['B','B'],['missing']])reject(t,'A',{...command('star-bow-dedicated'),targetIds});});
