import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,finish,pass,until,passReclaims} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeStormMagicScenario,stormMagicMode,type StormMagicScenario} from './fixtures/storm-magic-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const rows=['gale-ordinary','gale-dedicated','thunder-ordinary','thunder-dedicated'] as const;
function command(scenario:StormMagicScenario){const m=stormMagicMode(scenario);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function prepared(scenario:StormMagicScenario,options:Parameters<typeof makeStormMagicScenario>[2]={guard:'none'},ps=players){const s=makeStormMagicScenario(scenario,ps,{guard:'none',...options}),m=stormMagicMode(scenario);return m.chanted?chant(s,m.card):s;}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function nextOwn(s:GameState,card:string){for(let n=0;n<100;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>x!==card).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('STORM_TURN');}throw Error('STORM_TURN_LIMIT');}
function chant(s:GameState,card:string){s=act(s,'A',{type:'CHANT',cardInstanceId:card});expect(s.players.A!.chants).toEqual([{cardInstanceId:card,revealed:false}]);for(const id of s.seatOrder.filter(id=>id!=='A'))expect(viewFor(s,id).players.A!.chants).toEqual([{position:0,face:'back'}]);return nextOwn(s,card);}
function claim(s:GameState,card:string){for(let n=0;n<300;n++){const d=viewFor(s,'A').reclaim;if(s.windows?.at(-1)?.kind==='reclaim'&&d?.pendingActorId==='A'&&d.cardInstanceId===card){expect(d.claims.map(c=>c.right)).toContain('base');return act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:d.decisionId,choice:'take',claimId:d.claims.find(c=>c.right==='base')!.claimId});}s=pass(s);}throw Error('STORM_CLAIM');}
it.each(rows)('%s actual printed profile use boundary and mandatory Thunder chant persist in elected modes',scenario=>{
 const m=stormMagicMode(scenario);for(const level of [m.use-1,m.use]){let s=act(prepared(scenario,{level}),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.use,effectLevel:m.effect,damage:m.damage,attributes:m.gale?['魔','風']:['魔','風','詠'],chant:m.chanted,noChecks:m.dedicated,target:m.dedicated?'all':'one'});expect(f.technique.maaiRequired??1).toBe(m.maai);expect(f.fromChant??false).toBe(m.chanted);expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.damage,m.dedicated?m.damage:0,0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);}
});
it.each(rows)('%s actual printed maai cost and Evade affect only the defending target',scenario=>{
 const m=stormMagicMode(scenario);for(const count of [1,2]){let s=until(act(prepared(scenario),'A',command(scenario)),'normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'});if(m.maai===2&&count===2)s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([count>=m.maai?0:m.damage,m.dedicated?m.damage:0]);}let s=until(act(prepared(scenario),'A',command(scenario)),'normal-defense');s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,m.dedicated?m.damage:0]);
});
it.each(rows)('%s actual Fate base reclaim and later use require a fresh Thunder chant in both modes',scenario=>{
 const m=stormMagicMode(scenario);let s=act(prepared(scenario),'A',command(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=pass(s);s=pass(s);s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id});s=finish(claim(s,m.card));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.players.A!.hand.filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);expect(s.players.A!.reclaimUsage?.[m.name]?.baseSpent).toBe(true);s=nextOwn(s,m.card);if(m.chanted){reject(s,'A',command(scenario));s=chant(s,m.card);}s=finish(act(s,'A',command(scenario)));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage,m.dedicated?m.damage:0]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(['gale-ordinary','gale-dedicated'] as const)('%s ignores actual sky Water Dragon but processes the non-sky rear and building normally',scenario=>{
 const m=stormMagicMode(scenario);let s=prepared(scenario,{guard:'air-rear'});const [front,rear]=s.players.B!.followers.map(f=>f.cardInstanceId);s=finish(act(s,'A',command(scenario)));expect(s.players.B!.damage).toBe(m.damage-1);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual([front]);expect(s.discard).toContain(rear);expect(s.discard).not.toContain(front);s=prepared(scenario,{guard:'building-rear'});const ids=s.players.B!.followers.map(f=>f.cardInstanceId);s=finish(act(s,'A',command(scenario)));expect(s.players.B!.damage).toBe(m.damage-3);expect(s.players.B!.followers).toEqual([]);expect(s.discard).toEqual(expect.arrayContaining(ids));
});
it.each(['thunder-ordinary','thunder-dedicated'] as const)('%s actual building exemption retains Fort HP while nonbuilding Soldier and Water Dragon follow the elected destruction rule',scenario=>{
 const m=stormMagicMode(scenario);let s=prepared(scenario,{guard:'building-rear'});const ids=s.players.B!.followers.map(f=>f.cardInstanceId);s=finish(act(s,'A',command(scenario)));expect(s.players.B!.damage).toBe(m.damage-(m.dedicated?2:3));expect(s.players.B!.followers).toEqual([]);expect(s.discard).toEqual(expect.arrayContaining(ids));s=prepared(scenario,{guard:'water'});s=finish(act(s,'A',command(scenario)));expect(s.players.B!.damage).toBe(m.dedicated?18:0);expect(s.players.B!.followers).toEqual([]);
});
it.each(['thunder-ordinary','thunder-dedicated'] as const)('%s six actual players distinguish ordinary four-target cap from dedicated five legal targets',scenario=>{
 const ps=['A','B','C','D','E','F'].map(id=>({id,name:id})),m=stormMagicMode(scenario);let s=prepared(scenario,{},ps);const all=['B','C','D','E','F'];if(!m.dedicated)reject(s,'A',{...command(scenario),targetIds:all});reject(s,'A',{...command(scenario),targetIds:[]});const targets=m.dedicated?all:all.slice(0,4);s=finish(act(s,'A',{...command(scenario),targetIds:targets}));expect(all.map(id=>s.players[id]!.damage)).toEqual(m.dedicated?[18,18,18,18,18]:[12,12,12,12,0]);
});
it.each(rows)('%s refuses foreign dedicated owner unsupported variant and unprepared or unprinted chant source',scenario=>{
 const m=stormMagicMode(scenario),s=makeStormMagicScenario(scenario,players,{guard:'none'}),foreign=prepared(scenario,{owner:'侍大将のシン',guard:'none'});reject(foreign,'A',{...command(scenario),dedicated:true});reject(prepared(scenario),'A',{...command(scenario),techniqueVariant:'two-hit'});if(m.chanted)reject(s,'A',command(scenario));else{reject(s,'A',{type:'CHANT',cardInstanceId:m.card});if(!m.dedicated)reject(s,'A',{...command(scenario),targetIds:['B','C']});}
});
