import {expect,it} from 'vitest';
import {gameStats,viewFor,transition,type GameState} from '../src/index.js';
import {act,pass} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeSubstitutePhysicalScenario,substituteMode,type SubstitutePhysicalScenario} from '../../../apps/worker/test/fixtures/substitute-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),card='a2-p02-r2c1';
function until(s:GameState,done:(s:GameState)=>boolean,dice=[1,1]){for(let n=0;n<500;n++){if(done(s))return s;s=pass(s,dice);}throw Error('SUBSTITUTE_PHYSICAL_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function incoming(name:SubstitutePhysicalScenario){const m=substituteMode(name);let s=makeSubstitutePhysicalScenario(name,players);s=act(s,'A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:m.multi?['B','C']:['B'],dedicated:m.multi});s=until(s,s=>!!Object.keys(s.groups??{}).length,[3,1,1]);if(m.follower)s=until(s,s=>s.windows?.at(-1)?.kind==='hit');return until(s,s=>viewFor(s,'C').anytimeCardOptions.some(o=>o.cardInstanceId===card&&o.targetId==='B'&&o.hitIndex===m.hit));}
function take(s:GameState,hit=0){const o=viewFor(s,'C').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId==='B'&&o.hitIndex===hit)!;return act(s,'C',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:o.targetId,groupId:o.groupId,hitIndex:o.hitIndex});}
function receiver(s:GameState){return until(s,s=>s.windows?.at(-1)?.kind==='normal-defense'&&!!viewFor(s,'C').currentAttack?.substitution);}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['substitute-one','substitute-multi','substitute-followers','substitute-receiver-followers','substitute-near','substitute-refill'] as const)('%s actual single selected hit transfer preserves original hits and prior follower reductions',name=>{let s=incoming(name);const m=substituteMode(name),hand=s.players.C!.hand.length,stats=gameStats(s,'C'),original=Object.values(s.groups!)[0]!,damage=original.targets[0]!.hits[m.hit]!.damage,followers=structuredClone(s.players.C!.followers);if(m.multi)expect(original.targets.map(t=>t.hits.length)).toEqual([3,3]);s=receiver(take(s,m.hit));expect(s.players.C!.hand).toHaveLength(hand);expect(viewFor(s,'C').currentAttack!.substitution).toEqual({originalTargetId:'B',originalHitIndex:m.hit});expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);expect(s.players.C!.followers).toEqual(followers);if(name==='substitute-near'){expect(s.distances.A!.C).toBe('far');s=act(s,'C',{type:'REVEAL_CHARACTER'});}if(name==='substitute-refill'){expect(s.players.C!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'C').spirit).toBe(stats.spirit+1);}s=settle(s);expect(s.players.B!.damage).toBe(m.follower?4:m.multi?14:0);expect(s.players.C!.damage).toBe(m.receiver?8:m.follower?23:m.multi?28:damage);expect(s.discard.filter(id=>id===card)).toHaveLength(1);expect(s.resolution).toEqual([]);});
it.each(['substitute-one','substitute-teleport','substitute-receiver-followers','substitute-reaction'] as const)('%s actual receiver rejects ordinary defense maai followers and own reaction without payment',name=>{let s=incoming(name);const root=Object.values(s.actions!).find(a=>a.kind==='attack')!.id;s=receiver(take(s,substituteMode(name).hit));if(name==='substitute-reaction')expect(s.players.C!.hand).toContain('a2-p02-r2c3');const commandList=[{type:'PLAY_DEFENSE',cardInstanceId:name==='substitute-teleport'?'a2-p06-r1c1':'a2-p05-r3c1',dedicated:false},{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'},{type:'START_FOLLOWERS'},{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:root}];for(const command of commandList)reject(s,'C',command);expect(viewFor(s,'C').legalChoices).not.toContain('START_FOLLOWERS');expect(viewFor(s,'C').anytimeCardOptions).toEqual([]);expect(viewFor(s,'C').self.hand).toContain('a2-p10-r3c3');s=settle(s);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual substitute hand counter creates one returned hit against original attacker and no damage to either receiver',()=>{let s=receiver(take(incoming('substitute-counter')));s=act(s,'C',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p10-r3c3',dedicated:false});s=until(s,s=>Object.values(s.groups??{}).some(g=>g.attackerId==='C'));const g=Object.values(s.groups!).find(g=>g.attackerId==='C')!;expect(g.targets.map(t=>[t.actorId,t.hits.length])).toEqual([['A',1]]);s=settle(s);expect([s.players.A!.damage,s.players.B!.damage,s.players.C!.damage]).toEqual([5,0,0]);});
it.each(['substitute-mental','substitute-water'] as const)('%s actual receiver may choose its own mental defense or water immunity',name=>{let s=receiver(take(incoming(name)));const ability=substituteMode(name).ability!,o=viewFor(s,'C').abilityOptions.find(o=>o.abilityId===ability)!;expect(o).toBeDefined();s=act(s,'C',{type:'USE_ABILITY',abilityId:ability,targetEventId:o.targetEventId});s=settle(s);expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);});
it('actual third party Tragedy still cancels original attack while substitute response is restricted',()=>{let s=incoming('substitute-third'),root=Object.values(s.actions!).find(a=>a.kind==='attack')!.id;s=receiver(take(s));s=until(s,s=>viewFor(s,'D').anytimeCardOptions.some(o=>o.cardInstanceId==='a2-p01-r2c3'));const o=viewFor(s,'D').anytimeCardOptions.find(o=>o.cardInstanceId==='a2-p01-r2c3')!;expect(o.targetEventId).toBe(root);s=settle(act(s,'D',{type:'PLAY_ANYTIME_CARD',cardInstanceId:o.cardInstanceId,targetEventId:o.targetEventId}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);});
it('actual Fate canceled substitute preserves used event cost and refill but original hit remains',()=>{let s=incoming('substitute-canceled'),hand=s.players.C!.hand.length;const root=Object.values(s.actions!).find(a=>a.kind==='attack')!.id;s=take(s);const child=Object.values(s.actions!).find(a=>a.cardInstanceId===card)!;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id});s=until(s,s=>!s.actions?.[child.id]);expect(s.used).toContain(`${root}:C:${card}`);expect(s.players.C!.hand).toHaveLength(hand);s=settle(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([4,0]);expect(s.discard.filter(id=>id===card)).toHaveLength(1);});
it('actual SadLove cannot retransmit a substituted Arnes hit but may receive a different original Arnes hit',()=>{let s=receiver(take(incoming('substitute-chain'),1));s=until(s,s=>s.windows?.at(-1)?.kind==='hit'&&s.windows.at(-1)!.participants[s.windows.at(-1)!.cursor]==='D');const child=Object.values(s.groups!).find(g=>g.substituteOrigin)!,offers=viewFor(s,'D').sadLove!.substitutions;expect(offers).toHaveLength(3);expect(offers.every(o=>o.groupId!==child.id&&o.targetId==='C')).toBe(true);reject(s,'D',{type:'USE_ABILITY',abilityId:'c2-p05-r1c2-ab05',mode:'substitute',targetEventId:child.actionId,targetId:'C',groupId:child.id,hitIndex:0});const o=offers[0]!;s=act(s,'D',{type:'USE_ABILITY',abilityId:'c2-p05-r1c2-ab05',mode:'substitute',...o});s=settle(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([14,21,7]);expect(s.players.D!.sadLoveSubstitutionSpent).toBe(true);});
it('actual substitute optional decline and completed hit leave card unspent and reject stale transfer',()=>{let s=incoming('substitute-decline');const o=viewFor(s,'C').anytimeCardOptions.find(o=>o.cardInstanceId===card)!;s=settle(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([4,0]);expect(s.players.C!.hand).toContain(card);reject(s,'C',{type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:o.targetId,groupId:o.groupId,hitIndex:o.hitIndex});});
it('actual self foreign stale wrong group and wrong hit substitute commands reject unchanged state and all views',()=>{const s=incoming('substitute-multi'),o=viewFor(s,'C').anytimeCardOptions.find(o=>o.cardInstanceId===card&&o.targetId==='B')!,command={type:'PLAY_ANYTIME_CARD',cardInstanceId:card,targetEventId:o.targetEventId,targetId:o.targetId,groupId:o.groupId,hitIndex:o.hitIndex};for(const patch of [{targetId:'C'},{targetEventId:'stale'},{groupId:'missing'},{hitIndex:99}])reject(s,'C',{...command,...patch});reject(s,'D',command);});
