import {passReclaims} from './combat-helpers.js';
import {describe,it,expect} from 'vitest';
import {transition,viewFor,allCardInstanceIds,type GameState} from '../src/index.js';
import {act,ready,until,pass,finish,closeWindow} from './combat-helpers.js';
import {character,handCard,entropy} from './fixtures.js';
const IDA='c2-p04-r2c2';
function use(s:GameState,actorId:string,n:number,extra:Record<string,unknown>={}){const option=viewFor(s,actorId).abilityOptions.find(o=>o.abilityId===`${IDA}-ab0${n}`);expect(option).toBeDefined();return act(s,actorId,{type:'USE_ABILITY',abilityId:option!.abilityId,targetEventId:option!.targetEventId,...extra});}
function priority(s:GameState,id:string){for(let n=0;n<30;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===id)return s;s=pass(s);}throw Error('PRIORITY');}
function idaAttack(name='踏み込み／弓',targets=['B']){let s=ready();character(s,'A','忍びのイダ');const card=handCard(s,'A',name);s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:targets,dedicated:name==='手裏剣'});return s;}
function expectRejected(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as Parameters<typeof transition>[1],entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
describe('Task7h real optional abilities',()=>{
 it('accepts conceal/heal as an own action with exact physical maai cost, private declaration and no refill',()=>{let s=ready();character(s,'A','忍びのイダ');s.players.A!.damage=5;s.players.A!.revealed=true;const cost=handCard(s,'A','間合い／休息');const hand=s.players.A!.hand.length;s=use(s,'A',4,{costCardInstanceId:cost,conceal:true});expect(s.players.A!.damage).toBe(5);expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.hand).toHaveLength(hand-1);expect(s.resolution).toContain(cost);expect(s.discard).not.toContain(cost);s=passReclaims(s);expect(viewFor(s,'B').currentAction).toMatchObject({source:'ability'});s=finish(s);expect(s.players.A).toMatchObject({damage:3,revealed:false});expect(s.phase).toBe('hand-adjustment');expect(allCardInstanceIds(s)).toHaveLength(220);});
 it('concealed healing remains concealed and hides canonical ID from other views',()=>{let s=ready();character(s,'A','忍びのイダ');s.players.A!.damage=1;const cost=handCard(s,'A','間合い／休息');s=use(s,'A',4,{costCardInstanceId:cost});s=passReclaims(s);expect(viewFor(s,'A').currentAction).toMatchObject({abilityId:`${IDA}-ab04`,label:'隠行'});expect(viewFor(s,'B').currentAction).toMatchObject({label:'特殊能力'});expect(JSON.stringify(viewFor(s,'B'))).not.toContain(IDA);s=finish(s);expect(s.players.A).toMatchObject({damage:0,revealed:false});});
 it('cancellation retains action, cost and accepted use with exact opaque target',()=>{let s=ready();character(s,'A','忍びのイダ');s.players.A!.damage=4;const cost=handCard(s,'A','間合い／休息');const fate=handCard(s,'B','命運凶変');s=use(s,'A',4,{costCardInstanceId:cost,conceal:true});s=passReclaims(s);s=priority(s,'B');const target=viewFor(s,'B').reactionTargetAbilityId!;expectRejected(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:target});s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:target});s=finish(s);expect(s.players.A!.damage).toBe(4);expect(s.discard).toContain(cost);expect(s.phase).toBe('hand-adjustment');expectRejected(s,'A',{type:'USE_ABILITY',abilityId:`${IDA}-ab04`,targetEventId:target,costCardInstanceId:cost});});
 it('rejects forged IDs, event, foreign costs, suppressed and stopped uses before payment',()=>{let s=ready();character(s,'A','忍びのイダ');const cost=handCard(s,'A','間合い／休息');const option=viewFor(s,'A').abilityOptions.find(o=>o.abilityId.endsWith('ab04'))!;const base={type:'USE_ABILITY',abilityId:`${IDA}-ab04`,targetEventId:option.targetEventId,costCardInstanceId:cost};for(const patch of [{abilityId:'c2-p07-r1c2-ab05'},{targetEventId:'forged'},{costCardInstanceId:handCard(s,'B','間合い／休息')},{costCardInstanceId:handCard(s,'A','衝破')}])expectRejected(s,'A',{...base,...patch});for(const kind of ['ability-disabled','stopped'] as const){s.players.A!.statuses=[{id:kind,kind,modifiers:[0],nextCheck:0}];expect(viewFor(s,'A').abilityOptions).toEqual([]);expectRejected(s,'A',base);}});
 it('Lancelot accepted cancellation consumes once-game transformation attempt',()=>{let s=ready();character(s,'A','聖騎士ランスロット');character(s,'C','リーア姫');const fate=handCard(s,'B','命運凶変');s=act(s,'C',{type:'REVEAL_CHARACTER'});s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'});expect(s.players.A!.characterId).toBe('c2-p02-r2c2');s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});s=finish(s);expect(s.players.A!.characterId).toBe('c2-p02-r2c2');expect(viewFor(s,'A').lifecycleAbilities).not.toContain('lancelot-transform');});
 it('printed Arseil Fate response bypasses ability-disabled and is not another declaration',()=>{let s=ready();character(s,'C','占星術師のアルセイル');s.players.C!.revealed=true;s.players.C!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];const attack=handCard(s,'A','衝破');const fate=handCard(s,'B','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:viewFor(s,'B').reactionTargetActionId!});const id=viewFor(s,'C').reactionTargetActionId!;s=act(s,'C',{type:'CANCEL_REACTION',targetActionId:id});expect(viewFor(s,'C').reactionTargetAbilityId).toBeNull();expect(s.actions![id]!.canceled).toBe(true);});
 it('martial follower bypass is explicitly elected for this group only',()=>{let s=ready();character(s,'A','忍びのイダ');s.distances.A!.B='near';s.distances.B!.A='near';const card=handCard(s,'A','踏み込み／殴る');const follower=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==follower);s.players.B!.followers.push({cardInstanceId:follower,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'attack-abilities');s=use(s,'A',2);s=closeWindow(s);s=finish(s);expect(s.players.B!.followers.some(f=>f.cardInstanceId===follower)).toBe(true);expect(s.players.B!.damage).toBeGreaterThan(0);});
 it.each([[2,2,'dead'],[2,3,8],[1,6,4]])('numeric lethal faces %i/%i produce exact hit result %s', (a,b,result)=>{let s=idaAttack();s=until(s,'hit-abilities');s=use(s,'A',3);s=closeWindow(s,[a,b]);expect(s.rolls!.at(-1)).toMatchObject({kind:'numeric',formula:'2d6',faces:[a,b]});s=finish(s);if(result==='dead')expect(s.players.B!.presence).toBe('dead');else expect(s.players.B!.damage).toBe(result);expect(s.players.A!.damage).toBe(0);});
 it('Shadow checks self then enemy and grants optional real non-counter child attack',()=>{let s=ready();character(s,'B','忍びのイダ');s.distances.A!.B='near';s.distances.B!.A='near';const source=handCard(s,'A','衝破');const child=handCard(s,'B','踏み込み／殴る');s=act(s,'A',{type:'ATTACK',cardInstanceId:source,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=use(s,'B',1);s=closeWindow(s);expect(s.rolls!.at(-1)).toMatchObject({rollerId:'B',modifier:-2});s=closeWindow(s,[1,1]);s=closeWindow(s);expect(s.rolls!.at(-1)).toMatchObject({rollerId:'A',modifier:-2});s=closeWindow(s,[6,6]);s=closeWindow(s);expect(s.windows!.at(-1)!.kind).toBe('ability-attack');expectRejected(s,'B',{type:'APPROACH',targetId:'A',cardInstanceId:child});s=act(s,'B',{type:'ATTACK',cardInstanceId:child,targetIds:['A'],dedicated:false});s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.A!.damage).toBeGreaterThan(0);expect(s.discard).toContain(source);expect(s.discard).toContain(child);expect(s.phase).toBe('withdrawal');});
});

describe('Task7h saved attempts and live restrictions',()=>{
 it('Fate force-failure may be declared before the ability check and survives a whole reroll',()=>{
  let s=ready();character(s,'B','忍びのイダ');const card=handCard(s,'A','衝破');const fate=handCard(s,'A','命運凶変');const god=handCard(s,'C','神性介入');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=use(s,'B',1);s=passReclaims(closeWindow(s));const rollId=s.rolls!.at(-1)!.id;
  expect(viewFor(s,'A').reactionTargetRollId).toBe(rollId);s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:rollId});s=passReclaims(closeWindow(s));s=passReclaims(closeWindow(s,[1,1]));s=priority(s,'C');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:rollId});s=passReclaims(closeWindow(s,[2,2]));s=passReclaims(closeWindow(s));expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({forcedFailure:true,success:false,faces:[2,2]});expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(1);expect(viewFor(s,'B').abilityOptions).toEqual([]);s=finish(s);expect(s.players.B!.damage).toBeGreaterThan(0);
 });
 it('God replaces the complete numeric pair, rejects Fate numeric failure and cannot mint an attempt',()=>{
  let s=ready();character(s,'A','忍びのイダ');const card=handCard(s,'A','踏み込み／弓');const god=handCard(s,'B','神性介入');const fate=handCard(s,'A','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'hit-abilities');const parent=s.windows!.at(-1)!;s=use(s,'A',3);s=passReclaims(closeWindow(s,[2,2]));const rollId=s.rolls!.at(-1)!.id;expectRejected(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'force-fail',targetRollId:rollId});s=priority(s,'B');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:god,mode:'reroll',targetRollId:rollId});s=passReclaims(closeWindow(s,[1,6]));s=passReclaims(closeWindow(s));expect(s.windows!.at(-1)!.id).toBe(parent.id);expect(viewFor(s,'A').abilityOptions).toEqual([]);expect(s.rolls!.find(r=>r.id===rollId)).toMatchObject({faces:[1,6],attempts:[{faces:[2,2]},{faces:[1,6]}]});s=finish(s);expect(s.players.B!.damage).toBe(4);expect(s.players.B!.presence??'active').toBe('active');
 });
 it('actual declared multi-target hits save instant death while subsequent hit damage remains in the group',()=>{
  let s=idaAttack('手裏剣',['B','C']);s=until(s,'hit-abilities');s=use(s,'A',3);s=closeWindow(s,[3,3]);s=closeWindow(s);expect(s.players.B!.presence??'active').toBe('active');expect(s.players.B!.damage).toBe(0);s=closeWindow(s);s=until(s,'hit-abilities');s=use(s,'A',3);s=closeWindow(s,[4,5]);s=closeWindow(s);expect(s.players.C!.damage).toBe(0);s=until(s,'death-gift');const batch=s.lifecycle!.find(t=>t.kind==='death-batch');expect(batch).toMatchObject({intents:[{targetId:'B',instantDeath:true},{targetId:'C',damage:10}]});expect(s.players.C!.damage).toBe(10);s=finish(s);expect(s.players.B!.presence).toBe('dead');
 });
 it.each([false,true])('declined/canceled martial use keeps the normal follower (%s)',cancel=>{
  let s=ready();character(s,'A','忍びのイダ');s.distances.A!.B='near';s.distances.B!.A='near';const attack=handCard(s,'A','踏み込み／殴る');const follower=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==follower);s.players.B!.followers.push({cardInstanceId:follower,revealed:false});const fate=handCard(s,'B','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=until(s,'attack-abilities');if(cancel){s=use(s,'A',2);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});}s=finish(s);expect(s.players.B!.damage).toBe(0);
 });
 it('live suppression disables a declared continuous martial contribution without changing saved attack values',()=>{
  let s=ready();character(s,'A','忍びのイダ');s.distances.A!.B='near';s.distances.B!.A='near';const attack=handCard(s,'A','踏み込み／殴る');const follower=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==follower);s.players.B!.followers.push({cardInstanceId:follower,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=until(s,'attack-abilities');const saved=structuredClone(Object.values(s.groups!)[0]!.technique);s=use(s,'A',2);s=closeWindow(s);s.players.A!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];expect(Object.values(s.groups!)[0]!.technique).toEqual(saved);s=finish(s);expect(s.players.B!.damage).toBe(0);
 });
 it('a suppressed accepted heal pays its cost but revalidates before applying the effect',()=>{let s=ready();character(s,'A','忍びのイダ');s.players.A!.damage=4;s.players.A!.revealed=true;const cost=handCard(s,'A','間合い／休息');s=use(s,'A',4,{costCardInstanceId:cost,conceal:true});s.players.A!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s=finish(s);expect(s.players.A).toMatchObject({damage:4,revealed:true});expect(s.discard).toContain(cost);});
 it.each([[6,6,1],[1,1,2]])('Shadow failed own or successful enemy check grants no child (%i,%i)',(a,b,checks)=>{let s=ready();character(s,'B','忍びのイダ');const attack=handCard(s,'A','衝破');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=use(s,'B',1);s=closeWindow(s);s=closeWindow(s,[a,b]);s=closeWindow(s);if(checks===2){s=closeWindow(s,[1,1]);s=closeWindow(s);}expect(s.rolls!.filter(r=>r.purpose==='ability-check')).toHaveLength(checks);expect(s.windows!.at(-1)!.kind).toBe('normal-defense');expect(viewFor(s,'B').abilityOptions).toEqual([]);s=finish(s);expect(s.players.B!.damage).toBeGreaterThan(0);});
 it('all public participant windows are identical regardless of hidden ownership',()=>{let s=idaAttack();s=until(s,'attack-abilities');const other=structuredClone(s);character(other,'A','侍大将のシン');expect(viewFor(s,'B').activeWindow).toEqual(viewFor(other,'B').activeWindow);expect(viewFor(s,'B').abilityOptions).toEqual([]);s=until(s,'hit-abilities');const nonIda=structuredClone(s);character(nonIda,'A','侍大将のシン');expect(viewFor(s,'B').activeWindow).toEqual(viewFor(nonIda,'B').activeWindow);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(IDA);});
});

function awakened(){let s=ready();character(s,'A','邪祭ウーノス');character(s,'B','占星術師のアルセイル');character(s,'C','魔聖母ディア');character(s,'D','餓狼ヨーツルム');handCard(s,'A','復活の儀式');s=act(s,'A',{type:'USE_REVIVAL_RITUAL'});return closeWindow(s);}
function top(s:GameState,id:string){for(const p of Object.values(s.players)){p.hand=p.hand.filter(x=>x!==id);p.open=p.open.filter(x=>x!==id);}s.deck=s.deck.filter(x=>x!==id);s.discard=s.discard.filter(x=>x!==id);s.deck.unshift(id);}
describe('Task7h lifecycle cancellation and nested replay',()=>{
 it('subordinates declaration cancellation consumes this awakening event and retains prior allegiance',()=>{let s=awakened();const fate=handCard(s,'B','命運凶変');s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'});expect(s.players.C!.faction).toBe('EVIL');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});s=closeWindow(s);s=closeWindow(s);expect(viewFor(s,'A').lifecycleAbilities).not.toContain('vanmil-subordinates');expect(s.players.C!.faction).toBe('EVIL');expectRejected(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'vanmil-subordinates'});s=finish(s);});
 it('conspiracy cancellation consumes its boundary attempt, retaining actor and no personal victory',()=>{let s=awakened();const fate=handCard(s,'C','命運凶変');s=pass(s);s=act(s,'B',{type:'USE_LIFECYCLE_ABILITY',ability:'arseil-conspiracy'});const useId=viewFor(s,'C').reactionTargetAbilityId!;expect(JSON.stringify(viewFor(s,'C'))).not.toContain('c2-p04-r2c1');s=act(s,'C',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:useId});s=closeWindow(s);s=closeWindow(s);s=priority(s,'B');expect(viewFor(s,'B').lifecycleAbilities).not.toContain('arseil-conspiracy');expect(s.individualResults?.B).toBeUndefined();expect(s.players.B!.presence??'active').toBe('active');s=finish(s);});
 it('Arseil printed response cancels a Fate child and restores the original ability through OPEN refill',()=>{
  let s=ready();character(s,'A','忍びのイダ');character(s,'C','占星術師のアルセイル');s.players.C!.revealed=true;s.players.C!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s.players.D!.presence='dead';s.players.A!.damage=4;const cost=handCard(s,'A','間合い／休息');const fate=handCard(s,'B','命運凶変');s=use(s,'A',4,{costCardInstanceId:cost});s=passReclaims(s);s=priority(s,'B');const parent=s.windows!.at(-1)!;const abilityId=viewFor(s,'B').reactionTargetAbilityId!;top(s,'a2-p01-r1c1');s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:abilityId});expect(s.windows!.at(-1)!.kind).toBe('before-roll');expect(s.abilities![abilityId]!.eventId).toBe(parent.eventId);s=passReclaims(closeWindow(s,[1]));s=passReclaims(closeWindow(s));s=act(s,'D',{type:'CHOOSE_REVIVAL',revive:false});expect(s.windows!.at(-1)!.kind).toBe('declaration');const fateId=viewFor(s,'C').reactionTargetActionId!;expect(s.resolution).toContain(fate);
  expectRejected(s,'C',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel',targetActionId:fateId});expect(s.players.C!.hand).not.toContain(fate);expect(viewFor(s,'C').legalChoices).toContain('CANCEL_REACTION');s=act(s,'C',{type:'CANCEL_REACTION',targetActionId:fateId});expect(s.windows!.at(-1)!.continuation.id).toBe(fateId);expect(s.abilities![abilityId]!.canceled).toBe(false);s=passReclaims(closeWindow(s));expect(s.windows!.at(-1)!.id).toBe(parent.id);expect(s.windows!.at(-1)!.cursor).toBe(0);s=finish(s);expect(s.players.A!.damage).toBe(2);expect(s.discard).toContain(cost);expect(s.discard).toContain(fate);
 });
 it('live public Lia loss invalidates accepted transformation without refunding the game attempt',()=>{let s=ready();character(s,'A','聖騎士ランスロット');character(s,'C','リーア姫');s=act(s,'C',{type:'REVEAL_CHARACTER'});s=act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'});s.players.C!.revealed=false;s=finish(s);expect(s.players.A!.characterId).toBe('c2-p02-r2c2');s=act(s,'C',{type:'REVEAL_CHARACTER'});expect(viewFor(s,'A').lifecycleAbilities).not.toContain('lancelot-transform');});
 it('mandatory Vanmil end remains outside optional suppression/cancellation',()=>{let s=ready();character(s,'A','破壊神ヴァンミール');s.players.A!.statuses=[{id:'seal',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s.players.A!.damage=25;expect(viewFor(s,'A').abilityOptions.map(o=>o.abilityId)).not.toContain('c2-p07-r1c2-ab05');s=act(s,'A',{type:'PASS_ACTION'});s=finish(s);expect(s.outcome?.reason).toBe('vanmil-death');expect(s.outcome?.winnerIds).not.toContain('A');});
});

describe('Task7h independent hit budgets and child legality',()=>{
 it('normal multi-hit defense slots independently offer Shadow once per received hit',()=>{
  let s=ready();character(s,'A','侍大将のシン');character(s,'B','忍びのイダ');const attack=handCard(s,'A','天地百撃斬');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==attack);s.players.A!.chants.push({cardInstanceId:attack,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:true});s=until(s,'damage');s=closeWindow(s,[2]);s=closeWindow(s);s=until(s,'normal-defense');const first=viewFor(s,'B').abilityOptions.find(o=>o.abilityId.endsWith('ab01'))!.targetEventId;s=use(s,'B',1);s=closeWindow(s);s=closeWindow(s,[6,6]);s=closeWindow(s);expect(viewFor(s,'B').abilityOptions).toEqual([]);s=pass(s);expect(s.windows!.at(-1)!.kind).toBe('normal-defense');expect(viewFor(s,'B').abilityOptions.find(o=>o.abilityId.endsWith('ab01'))!.targetEventId).not.toBe(first);s=use(s,'B',1);s=closeWindow(s);s=closeWindow(s,[1,1]);s=closeWindow(s);s=closeWindow(s,[6,6]);s=closeWindow(s);s=pass(s);s=finish(s);expect(s.players.B!.damage).toBe(7);
 });
 it('each actual multi-hit grants one numeric attempt; cancellation never reallocates that right',()=>{
  let s=ready();character(s,'A','忍びのイダ');const card=handCard(s,'A','天地百撃斬');const fate=handCard(s,'B','命運凶変');s.players.A!.hand=s.players.A!.hand.filter(id=>id!==card);s.players.A!.chants.push({cardInstanceId:card,revealed:false});s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'damage');s=passReclaims(closeWindow(s,[2]));s=passReclaims(closeWindow(s));s=until(s,'hit-abilities');s=use(s,'A',3);s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'B').reactionTargetAbilityId!});s=passReclaims(closeWindow(s));s=passReclaims(closeWindow(s));expect(viewFor(s,'A').abilityOptions).toEqual([]);s=passReclaims(closeWindow(s));expect(s.windows!.at(-1)!.kind).toBe('hit-abilities');s=use(s,'A',3);s=passReclaims(closeWindow(s,[1,6]));s=passReclaims(closeWindow(s));const hits=Object.values(s.groups!)[0]!.targets[0]!.hits;expect(hits.map(h=>h.abilityBudget)).toEqual([{granted:1,accepted:1,closed:true},{granted:1,accepted:1,closed:false}]);s=finish(s);expect(s.players.B!.damage).toBe(14);
 });
 it('lethal numeric doubling applies after follower HP reduction and retains null damage',()=>{
  let s=idaAttack();const follower=handCard(s,'B','兵士');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==follower);s.players.B!.followers.push({cardInstanceId:follower,revealed:false});s=until(s,'hit-abilities');const group=Object.values(s.groups!)[0]!;const before=group.targets[0]!.hits[0]!.damage!;expect(before).toBeLessThan(4);s=use(s,'A',3);s=closeWindow(s,[2,3]);s=finish(s);expect(s.players.B!.damage).toBe(before*2);
  // Future no-damage warrior producers use the same persisted hit shape: do not coerce null to zero.
  s=idaAttack();s=until(s,'hit-abilities');Object.values(s.groups!)[0]!.targets[0]!.hits[0]!.damage=null;s=use(s,'A',3);s=closeWindow(s,[4,5]);s=closeWindow(s);expect(Object.values(s.groups!)[0]!.targets[0]!.hits[0]!.damage).toBeNull();s=finish(s);expect(s.players.B!.damage).toBe(0);
 });
 it('Shadow child obeys target, range, chant and real cost then can be declined without a free card',()=>{
  let s=ready();character(s,'B','忍びのイダ');const attack=handCard(s,'A','衝破');const near=handCard(s,'B','踏み込み／殴る');const chant=handCard(s,'B','天地百撃斬');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});s=until(s,'normal-defense');s=use(s,'B',1);s=closeWindow(s);s=closeWindow(s,[1,1]);s=closeWindow(s);s=closeWindow(s,[6,6]);s=closeWindow(s);const hand=[...s.players.B!.hand];for(const command of [{type:'ATTACK',cardInstanceId:near,targetIds:['C'],dedicated:false},{type:'ATTACK',cardInstanceId:near,targetIds:['A'],dedicated:false},{type:'ATTACK',cardInstanceId:chant,targetIds:['A'],dedicated:false},{type:'WITHDRAW',cardInstanceId:near,targetId:'A'}])expectRejected(s,'B',command);expect(s.players.B!.hand).toEqual(hand);s=pass(s);s=finish(s);expect(s.players.B!.damage).toBe(0);expect(s.players.B!.hand).toEqual(hand);
 });
});

it('explicit future total-two budget includes normal attempt and never creates a third on reset',()=>{let s=idaAttack();s=until(s,'hit-abilities');Object.values(s.groups!)[0]!.targets[0]!.hits[0]!.abilityBudget!.granted=2;s=use(s,'A',3);expect(Object.values(s.abilities!)[0]!.useOrdinal).toBe(1);s=closeWindow(s,[1,2]);s=closeWindow(s);s=use(s,'A',3);expect(Object.values(s.abilities!)[0]!.useOrdinal).toBe(2);s=closeWindow(s,[5,6]);s=closeWindow(s);expect(viewFor(s,'A').abilityOptions).toEqual([]);expect(Object.values(s.groups!)[0]!.targets[0]!.hits[0]!.abilityBudget).toEqual({granted:2,accepted:2,closed:false});s=finish(s);expect(s.players.B!.damage).toBe(16);});
it('ability cancellation never targets missing, canceled, or already rolled declarations',()=>{let s=ready();character(s,'A','忍びのイダ');const card=handCard(s,'A','踏み込み／弓');const fate=handCard(s,'B','命運凶変');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'hit-abilities');s=use(s,'A',3);const id=viewFor(s,'B').reactionTargetAbilityId!;expectRejected(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:'missing'});s=closeWindow(s,[1,6]);s=priority(s,'B');expect(viewFor(s,'B').reactionTargetAbilityId).toBeNull();expectRejected(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:id});s=finish(s);expect(s.players.B!.hand).toContain(fate);});

describe('Task7h review I1: reached target publication', () => {
  it('publishes a reached target before the first lethal choice and keeps it public during declaration and roll', () => {
    let state = idaAttack();
    const targetCharacterId = state.players.B!.characterId;
    expect(state.players.B!.revealed).toBe(false);
    state = until(state, 'hit-abilities');

    const expectPublicTarget = (current: GameState) => {
      const view = viewFor(current, 'A');
      expect(view.players.B).toMatchObject({ revealed: true, characterId: targetCharacterId });
      expect(view.logs.filter(log => log.type === 'CHARACTER_REVEALED' && log.actorId === 'B')).toEqual([
        expect.objectContaining({ characterId: targetCharacterId }),
      ]);
    };
    expectPublicTarget(state);
    state = use(state, 'A', 3);
    expect(state.windows!.at(-1)!.kind).toBe('declaration');
    expectPublicTarget(state);
    state = closeWindow(state, [1, 6]);
    expect(state.windows!.at(-1)!.kind).toBe('after-roll');
    expectPublicTarget(state);
    state = finish(state);
    expectPublicTarget(state);
  });

  it('does not reveal a target whose incoming hit was evaded', () => {
    let state = idaAttack();
    const maai = handCard(state, 'B', '間合い／休息');
    state = until(state, 'normal-defense');
    state = passReclaims(act(state, 'B', { type: 'PLAY_MAAI', cardInstanceId: maai }));
    state = finish(state);
    expect(viewFor(state, 'A').players.B).toMatchObject({ revealed: false });
    expect(viewFor(state, 'A').players.B).not.toHaveProperty('characterId');
    expect(viewFor(state, 'A').logs.some(log => log.type === 'CHARACTER_REVEALED' && log.actorId === 'B')).toBe(false);
  });

  it('does not reveal a target immune to the printed technique', () => {
    let state = ready();
    character(state, 'A', '忍びのイダ');
    character(state, 'B', '不死王ガドューラ');
    const card = handCard(state, 'A', '疫病');
    state = act(state, 'A', { type: 'ATTACK', cardInstanceId: card, targetIds: ['B'], dedicated: false });
    state = finish(state);
    expect(state.players.B!.damage).toBe(0);
    expect(viewFor(state, 'A').players.B).toMatchObject({ revealed: false });
    expect(viewFor(state, 'A').players.B).not.toHaveProperty('characterId');
    expect(viewFor(state, 'A').logs.some(log => log.type === 'CHARACTER_REVEALED' && log.actorId === 'B')).toBe(false);
  });
});
