import {expect,it} from 'vitest';
import {getAction} from '@madou/catalog';
import {gameStats,viewFor,transition,type GameState, discardIds } from '../src/index.js';
import {act,finish,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeTragedyPhysicalScenario,tragedyMode,type TragedyPhysicalScenario} from './fixtures/tragedy-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),tragedy='a2-p01-r2c3';
const dice=[3,...Array(60).fill(1)];
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<250;n++){if(done(s))return s;s=pass(s,dice);}throw Error('TRAGEDY_WINDOW');}
function start(name:TragedyPhysicalScenario){const m=tragedyMode(name);return act(makeTragedyPhysicalScenario(name,players),'A',{type:'ATTACK',cardInstanceId:m.attack,targetIds:m.multi?['B','C']:['B'],dedicated:false});}
function priority(s:GameState,id:string){return until(s,s=>{const w=s.windows?.at(-1);return !!w&&w.participants[w.cursor]===id;});}
function at(s:GameState,kind:string){return until(s,s=>s.windows?.at(-1)?.kind===kind);}
function option(s:GameState,id:string,event?:string){return viewFor(s,id).anytimeCardOptions.find(o=>o.cardInstanceId===tragedy&&(!event||o.targetEventId===event));}
function play(s:GameState,id='B',event?:string){s=until(s,s=>!!option(s,id,event));return act(s,id,{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:option(s,id,event)!.targetEventId});}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['tragedy-gainas','tragedy-dia','tragedy-multi'] as const)('%s actual revealed named attack loses all unresolved targets and hits while paying reaction once',name=>{let s=at(start(name),'attack-abilities');const m=tragedyMode(name),g=Object.values(s.groups!)[0]!,parent=g.actionId;expect(g.targets.map(t=>t.hits.length)).toEqual(m.multi?[1,1]:[3]);expect(s.events.some(e=>e.type==='CHARACTER_REVEALED'&&e.actorId==='A')).toBe(true);s=priority(s,'B');const size=s.players.B!.hand.length,draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;reject(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:'stale'});reject(s,'C',{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:parent});s=play(s);expect(s.players.B!.hand).toHaveLength(size);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);s=finish(s);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);for(const card of [tragedy,m.attack])expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);expect(s.resolution).toEqual([]);reject(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:parent});});
it.each(['tragedy-gainas','tragedy-dia'] as const)('%s actual pre-group declaration cancellation prevents all subsequent attack checks',name=>{let s=start(name);s=finish(play(s));expect(s.rolls??[]).toEqual([]);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(discardIds(s).filter(id=>id===tragedy)).toHaveLength(1);});
it.each(['tragedy-hidden','tragedy-unrelated'] as const)('%s never offers a response to hidden or unrelated attacker and declining preserves its card',name=>{let s=priority(at(start(name),'attack-abilities'),'B');const event=Object.values(s.groups!)[0]!.actionId,size=s.players.B!.hand.length;expect(option(s,'B')).toBeUndefined();reject(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:event});s=finish(s);expect(s.players.B!.damage).toBe(21);expect(s.players.B!.hand).toContain(tragedy);expect(s.players.B!.hand).toHaveLength(size);});
it('actual hidden Gainas reveal during the same attack makes the same event eligible',()=>{let s=priority(at(start('tragedy-hidden'),'attack-abilities'),'B');const event=Object.values(s.groups!)[0]!.actionId;expect(option(s,'B')).toBeUndefined();s=act(s,'A',{type:'REVEAL_CHARACTER'});s=finish(play(s,'B',event));expect(s.players.A!.revealed).toBe(true);expect(s.players.B!.damage).toBe(0);});
it.each(['tragedy-late','tragedy-late-death'] as const)('%s cancels remaining second target but retains the first targets committed damage and death',name=>{let s=start(name);const before=s.players.B!.damage;s=until(s,s=>{const g=Object.values(s.groups??{})[0],w=s.windows?.at(-1);return !!g&&g.targets[0]?.pendingDamage===15&&w?.kind==='hit'&&w.continuation.kind==='group'&&w.continuation.targetId==='C';});s=finish(play(s,'D'));expect(s.players.B!.damage).toBe(before+15);expect(s.players.C!.damage).toBe(0);expect(s.players.B!.presence).toBe(name==='tragedy-late-death'?'dead':'active');expect(s.events.filter(e=>e.type==='PLAYER_DIED'&&e.actorId==='B')).toHaveLength(name==='tragedy-late-death'?1:0);expect(discardIds(s).filter(id=>id===tragedy)).toHaveLength(1);});
it.each(['tragedy-follower','tragedy-third'] as const)('%s after actual follower start distinguishes defender refusal from third-party cancellation',name=>{let s=at(start(name),'hit');const g=Object.values(s.groups!)[0]!,event=g.actionId;expect(g.targets[0]!.followerStarted).toBe(true);if(name==='tragedy-follower'){s=priority(s,'B');expect(option(s,'B')).toBeUndefined();reject(s,'B',{type:'PLAY_ANYTIME_CARD',cardInstanceId:tragedy,targetEventId:event});s=finish(s);expect(s.players.B!.damage).toBe(12);expect(s.players.B!.hand).toContain(tragedy);}else{s=finish(play(s,'D',event));expect(s.players.B!.damage).toBe(0);expect(discardIds(s).filter(id=>id===tragedy)).toHaveLength(1);}expect(discardIds(s).filter(id=>id==='a2-p20-r3c1')).toHaveLength(1);});
it('actual generated counter survives cancellation of its named original attack',()=>{let s=at(start('tragedy-counter'),'normal-defense');const original=Object.values(s.groups!)[0]!.actionId,counter=s.players.B!.hand.find(id=>getAction(id)!.name==='閃光槍')!;s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:counter,dedicated:true});s=until(s,s=>Object.values(s.actions??{}).some(a=>a.kind==='attack'&&a.actorId==='B'));const child=Object.values(s.actions!).find(a=>a.kind==='attack'&&a.actorId==='B')!;expect(child.id).not.toBe(original);s=finish(play(s,'D',original));expect(s.players.A!.damage).toBe(7);expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);for(const card of [tragedy,counter])expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
it('actual Fate cancellation of Tragedy preserves refill and resumes the complete original attack',()=>{let s=at(start('tragedy-canceled'),'attack-abilities');const hand=s.players.B!.hand.length;s=play(s);const child=Object.values(s.actions!).find(a=>a.cardInstanceId===tragedy)!;s=priority(s,'A');s=finish(act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:child.id}));expect(s.players.B!.damage).toBe(21);expect(s.players.B!.hand).toHaveLength(hand);for(const card of [tragedy,'a2-p02-r2c3'])expect(discardIds(s).filter(id=>id===card)).toHaveLength(1);});
it('actual immediate Blood OPEN refill completes before the Tragedy child and cannot repeat the parent effect',()=>{let s=at(start('tragedy-refill'),'attack-abilities');const before=gameStats(s,'B');s=play(s);expect(s.players.B!.open).toContain('a2-p01-r1c3');expect(gameStats(s,'B')).toMatchObject({warrior_level:before.warrior_level+1,magic_level:before.magic_level+1,spirit:before.spirit+1});expect(s.windows!.at(-1)!.kind).toBe('declaration');s=finish(JSON.parse(JSON.stringify(s)));expect(s.players.B!.damage).toBe(0);expect(s.events.filter(e=>e.type==='OPEN'&&e.cardInstanceId==='a2-p01-r1c3')).toHaveLength(1);expect(discardIds(s).filter(id=>id===tragedy)).toHaveLength(1);});
