import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {getCharacter,getAction} from '@madou/catalog';
import {viewFor,transition,derivedStats,type GameState} from '../src/index.js';
import {ABILITIES} from '../src/abilities/frames.js';
import {act,ready,pass,closeWindow,finish,until} from './combat-helpers.js';
import {character,handCard,entropy,freshGame} from './fixtures.js';
const sources:{characterId:string;characterName:string;id:string;name:string;timing:string[];specification:string;activation:string}[]=JSON.parse(readFileSync(new URL('./fixtures/turn-information-sources.json',import.meta.url),'utf8'));
const CHAM='c2-p01-r2c2-ab03',LIA='c2-p03-r1c2-ab02',LESTER='c2-p03-r2c1-ab03',STAR='c2-p04-r2c1-ab02',SHADOW='c2-p04-r2c1-ab01',TRUE='c2-p04-r2c1-ab03',UONOS='c2-p05-r1c1-ab01',LANCA='c2-p02-r2c1-ab04';
function owner(name:string){const s=ready();character(s,'A',name);return s;}
function actualDraw(id:string){
 let s=freshGame();character(s,'A',id==='c2-p01-r2c2-ab02'?'小妖精のチャム':'聖騎士ランスロット');
 if(id==='c2-p07-r1c1-ab03')character(s,'B','リーア姫');
 for(const actor of s.seatOrder)s=act(s,actor,{type:'PASS_SETUP'});
 s=act(s,'A',{type:'START_TURN'});
 if(id==='c2-p01-r2c2-ab02')return s;
 s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=act(s,'B',{type:'REVEAL_CHARACTER'});
 s=finish(act(s,'A',{type:'USE_LIFECYCLE_ABILITY',ability:'lancelot-transform'}));
 expect(s.players.A!.characterId).toBe('c2-p07-r1c1');
 s=act(s,'A',{type:'PASS_ACTION'});s=act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(5)});
 for(const actor of ['B','C','D']){
  s=act(s,actor,{type:'START_TURN'});s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});
  s=act(s,actor,{type:'PASS_ACTION'});s=act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(5)});
 }
 return act(s,'A',{type:'START_TURN'});
}
function use(s:GameState,id:string,targetId?:string){const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id);expect(o).toBeDefined();return act(s,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:o!.targetEventId,...(targetId?{targetId}:{})});}
function inspect(s:GameState){return until(s,'private-inspection');}
function place(s:GameState,zone:'followers'|'chants',name:string){const id=handCard(s,'B',name);s.players.B!.hand=s.players.B!.hand.filter(x=>x!==id);s.players.B![zone].push({cardInstanceId:id,revealed:false});return id;}
function reject(s:GameState,actorId:string,command:unknown){const before=JSON.stringify(s);expect(transition(s,{actorId,command} as any,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}
describe('Task7x exact whole original packages',()=>{
 it.each(sources)('$name all source fields and registered package',(source)=>{const c=getCharacter(source.characterId)!;const a=c.abilities.find(a=>a.id===source.id)!;const {implementation,...printed}=a;expect({characterId:c.id,characterName:c.name,...printed}).toEqual(source);expect(ABILITIES).toHaveProperty(source.id);});
 it('Cham observes complete hidden followers privately, freezes and acknowledges without using main action',()=>{let s=owner('小妖精のチャム');const f=place(s,'followers','飛竜');s=inspect(use(s,CHAM,'B'));const d=viewFor(s,'A').inspection!;expect(d).toMatchObject({zone:'followers',targetId:'B',cards:[{position:0,cardInstanceId:f}],discardMode:'none',choices:['finish']});expect(viewFor(s,'B').inspection).toBeNull();expect(JSON.stringify(viewFor(s,'C'))).not.toContain(f);expect(s.players.B!.followers[0]!.revealed).toBe(false);reject(s,'B',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});reject(s,'A',{type:'PASS_ACTION'});s=act(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});expect(s.phase).toBe('action');expect(viewFor(s,'A').inspection).toBeNull();expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===CHAM)).toBe(false);reject(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'finish'});});
 it('Lia inspects nearby chants then discards all seen or none',()=>{for(const discard of [false,true]){let s=owner('リーア姫');s.distances.A!.B=s.distances.B!.A='near';const f=place(s,'chants','天地百撃斬');s=inspect(use(s,LIA,'B'));const d=viewFor(s,'A').inspection!;expect(d).toMatchObject({zone:'chants',targetId:'B',cards:[{position:0,cardInstanceId:f}],discardMode:'all'});expect(viewFor(s,'B').inspection).toBeNull();expect(viewFor(s,'C').inspection).toBeNull();s=act(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:discard?'discard-all':'finish'});expect(s.discard.includes(f)).toBe(discard);expect(s.players.B!.chants.length).toBe(discard?0:1);}});
 it.each([['吟遊詩人のレスター',LESTER,'character',-3],['占星術師のアルセイル',STAR,'hand',0]] as const)('%s checks before private snapshot',(name,id,zone,modifier)=>{let s=owner(name);s=use(s,id,'B');s=closeWindow(s);expect(viewFor(s,'A').currentRoll).toMatchObject({purpose:'ability-check',modifier});s=inspect(s);expect(viewFor(s,'A').inspection).toMatchObject({zone,targetId:'B'});expect(s.players.B!.revealed).toBe(false);const snapshot=viewFor(s,'A').inspection!;if(zone==='character')expect(snapshot.characterId).toBe(s.players.B!.characterId);else expect(snapshot.cards.map(c=>c.cardInstanceId)).toEqual(s.players.B!.hand);for(const actor of ['B','C','D'])expect(viewFor(s,actor).inspection).toBeNull();s=pass(s);expect(s.phase).toBe('action');});
 it('Lancaster discards all printed magic techniques, and consumes main action',()=>{let s=owner('早駆けのランカスター');handCard(s,'A','撃雷');const expected=s.players.A!.hand.filter(id=>{const c=getAction(id);return c?.category==='technique'&&c.stats?.school==='魔';});expect(expected.length).toBeGreaterThan(0);s=finish(use(s,LANCA));expect(s.phase).toBe('hand-adjustment');expect(s.discard).toEqual(expect.arrayContaining(expected));expect(s.players.A!.hand.some(id=>expected.includes(id))).toBe(false);});
 it.each([['凍気のアイエル','爆炎のフレイアード','c2-p04-r1c1-ab04'],['爆炎のフレイアード','凍気のアイエル','c2-p06-r2c1-ab04']])('%s swaps exact entire hands with public counterpart',(name,other,id)=>{let s=owner(name!);character(s,'B',other!);s.players.B!.revealed=true;const a=[...s.players.A!.hand],b=[...s.players.B!.hand];s=finish(use(s,id!,'B'));expect(s.players.A!.hand).toEqual(b);expect(s.players.B!.hand).toEqual(a);expect(s.phase).toBe('hand-adjustment');});
 it('Shadow uses pre-TruePower spirit and hides without erasing expiry',()=>{let s=owner('占星術師のアルセイル');s=finish(act(s,'A',{type:'REVEAL_CHARACTER',abilityId:TRUE}));expect(derivedStats(s.players.A!).spirit).toBe(12);s=use(s,SHADOW);s=closeWindow(s);s=closeWindow(s,[1,1]);expect(viewFor(s,'A').currentRoll!.threshold).toBe(5);s=finish(s);expect(s.players.A!.revealed).toBe(false);expect(derivedStats(s.players.A!).spirit).toBe(12);expect(viewFor(s,'A').spiritExpiry).toMatchObject({expiresOnActorId:'A',timing:'turn-end'});s=act(s,'A',{type:'PASS_ACTION'});s=act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(5)});expect(derivedStats(s.players.A!).spirit).toBe(6);});
 it('Uonos forces hidden Alseil public without granting voluntary TruePower',()=>{let s=owner('邪祭ウーノス');character(s,'B','占星術師のアルセイル');s=closeWindow(use(s,UONOS,'B'));expect(viewFor(s,'A').currentRoll).toMatchObject({purpose:'ability-check',modifier:-1});s=finish(s);expect(s.players.B!.revealed).toBe(true);expect(derivedStats(s.players.B!).spirit).toBe(6);expect(viewFor(s,'B').spiritExpiry).toBeNull();});
 it.each(['c2-p01-r2c2-ab02','c2-p07-r1c1-ab03'])('optional draw %s uses a single saved draw opportunity',id=>{let s=actualDraw(id);const before=s.players.A!.hand.length;expect(viewFor(s,'A').drawAbilityOptions).toContainEqual({abilityId:id,name:id.includes('p01')?'なになに':'成長'});s=finish(act(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:id}));expect(s.players.A!.hand).toHaveLength(before+2);expect(s.phase).toBe('action');});
});
function priority(s:GameState,actor='A'){for(let n=0;n<25;n++){const w=s.windows!.at(-1)!;if(w.participants[w.cursor]===actor)return s;s=pass(s);}throw Error('PRIORITY');}
function cancel(s:GameState,actor='B'){s=priority(s,actor);const fate=handCard(s,actor,'命運凶変');s=act(s,actor,{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,actor).reactionTargetAbilityId!});return finish(s);}
const turns=[['小妖精のチャム',CHAM,'B'],['リーア姫',LIA,'B'],['吟遊詩人のレスター',LESTER,'B'],['占星術師のアルセイル',STAR,'B'],['占星術師のアルセイル',SHADOW,null],['邪祭ウーノス',UONOS,'B'],['早駆けのランカスター',LANCA,null],['凍気のアイエル','c2-p04-r1c1-ab04','B'],['爆炎のフレイアード','c2-p06-r2c1-ab04','B']] as const;
function turnState(name:string,id:string){const s=owner(name);if(id===LIA)s.distances.A!.B=s.distances.B!.A='near';if(id===SHADOW)s.players.A!.revealed=true;if(id==='c2-p04-r1c1-ab04'||id==='c2-p06-r2c1-ab04'){character(s,'B',id==='c2-p04-r1c1-ab04'?'爆炎のフレイアード':'凍気のアイエル');s.players.B!.revealed=true;}return s;}
it.each(turns)('%s / %s cancellation consumes exactly accepted attempt/main action',(name,id,target)=>{let s=turnState(name,id);const before=[...s.players.A!.hand];s=cancel(use(s,id,target??undefined));expect(viewFor(s,'A').inspection).toBeNull();expect(s.players.A!.hand).toEqual(before);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===id)).toBe(false);expect(s.phase).toBe([LANCA,'c2-p04-r1c1-ab04','c2-p06-r2c1-ab04'].includes(id)?'hand-adjustment':'action');});
it.each(turns)('%s / %s ownership, own-turn, source availability and wrong/stale target are atomic',(name,id,target)=>{const s=turnState(name,id);const o=viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id)!;expect(o).toBeDefined();reject(s,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:'stale',...(target?{targetId:target}:{})});reject(s,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:o.targetEventId,targetId:'nobody'});reject(s,'B',{type:'USE_ABILITY',abilityId:id,targetEventId:o.targetEventId,...(target?{targetId:target}:{})});for(const bad of ['off-turn','stopped','disabled','dead','otherworld','setup','turn-start'] as const){const next=structuredClone(s);if(bad==='off-turn')next.turnSeat=1;else if(bad==='stopped'||bad==='disabled')next.players.A!.statuses=[{id:'fixture',kind:bad==='stopped'?'stopped':'ability-disabled',modifiers:[0],nextCheck:0}];else if(bad==='dead'||bad==='otherworld')next.players.A!.presence=bad;else next.phase=bad;expect(viewFor(next,'A').abilityOptions.some(o=>o.abilityId===id),bad).toBe(false);reject(next,'A',{type:'USE_ABILITY',abilityId:id,targetEventId:o.targetEventId,...(target?{targetId:target}:{})});}});
it.each([['吟遊詩人のレスター',LESTER,'B'],['占星術師のアルセイル',STAR,'B'],['占星術師のアルセイル',SHADOW,null],['邪祭ウーノス',UONOS,'B']] as const)('%s / %s final failed check does not resolve or refund',(name,id,target)=>{let s=turnState(name,id);const reveal=s.players.A!.revealed;s=closeWindow(use(s,id,target??undefined));s=closeWindow(s,[6,6]);expect(viewFor(s,'A').currentRoll!.success).toBe(false);s=finish(s);expect(viewFor(s,'A').inspection).toBeNull();expect(s.players.A!.revealed).toBe(reveal);expect(s.players.B!.revealed).toBe(false);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===id)).toBe(false);});
it.each([['吟遊詩人のレスター',LESTER,'B'],['占星術師のアルセイル',STAR,'B'],['占星術師のアルセイル',SHADOW,null],['邪祭ウーノス',UONOS,'B']] as const)('%s / %s saved Divine reroll and Fate force failure use final roll',(name,id,target)=>{for(const force of [false,true]){let s=turnState(name,id);s=closeWindow(use(s,id,target??undefined));s=closeWindow(s,[6,6]);s=priority(s,'B');const card=handCard(s,'B',force?'命運凶変':'神性介入');const rollId=viewFor(s,'B').reactionTargetRollId!;s=act(s,'B',{type:'PLAY_REACTION',cardInstanceId:card,mode:force?'force-fail':'reroll',targetRollId:rollId});s=closeWindow(s,[1,1]);s=closeWindow(s,[1,1]);const r=s.rolls!.find(r=>r.id===rollId)!;expect(r.success).toBe(!force);if(id===LESTER||id===STAR){if(force)s=finish(s);else s=inspect(s);expect(!!viewFor(s,'A').inspection).toBe(!force);}else {s=finish(s);expect(id===SHADOW?!s.players.A!.revealed:s.players.B!.revealed).toBe(!force);}}});
it('Astrology rejects unseen card, duplicate/foreign/stale decision and accepts exactly one seen discard',()=>{let s=inspect(use(owner('占星術師のアルセイル'),STAR,'B'));const d=viewFor(s,'A').inspection!,card=d.cards[0]!.cardInstanceId;reject(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'discard-one',cardInstanceId:s.deck[0]});reject(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'discard-all'});reject(s,'A',{type:'CHOOSE_INSPECTION',decisionId:'stale',choice:'finish'});const count=s.players.B!.hand.length;s=act(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'discard-one',cardInstanceId:card});expect(s.players.B!.hand).toHaveLength(count-1);expect(s.discard).toContain(card);reject(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'discard-one',cardInstanceId:card});});
it.each([false,true])('empty snapshots finish with source disabled=%s and no replacement-card disclosure',disabled=>{let s=owner('占星術師のアルセイル');s.deck.push(...s.players.B!.hand);s.players.B!.hand=[];s=inspect(use(s,STAR,'B'));expect(viewFor(s,'A').inspection!.cards).toEqual([]);expect(viewFor(s,'A').inspection!.choices).toEqual(['finish']);if(disabled)s.players.A!.statuses=[{id:'fixture',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s=pass(s);expect(viewFor(s,'A').inspection).toBeNull();expect(s.phase).toBe('action');});
it('snapshot survives legitimate voluntary reveal and mandatory Lia/LanceII child, preserving seen cards and parent phase',()=>{let s=owner('小妖精のチャム');character(s,'B','聖騎士ランスロット');character(s,'C','リーア姫');const f=place(s,'followers','飛竜');s=inspect(use(s,CHAM,'B'));const before=viewFor(s,'A').inspection!;s=act(s,'C',{type:'REVEAL_CHARACTER'});expect(viewFor(s,'A').inspection).toEqual(before);expect(s.windows!.at(-1)!.kind).toBe('lifecycle-boundary');s=priority(s,'B');const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r2c2-ab05')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});s=until(s,'private-inspection');expect(s.players.B!.characterId).toBe('c2-p07-r1c1');expect(viewFor(s,'A').inspection).toEqual(before);expect(s.players.B!.followers[0]!.cardInstanceId).toBe(f);s=pass(s);expect(s.phase).toBe('action');});
it('snapshot discards only original still-present cards after another card replaces its position',()=>{let s=owner('リーア姫');s.distances.A!.B=s.distances.B!.A='near';const old=place(s,'chants','天地百撃斬');s=inspect(use(s,LIA,'B'));const d=viewFor(s,'A').inspection!;s.players.B!.chants=[];s.discard.push(old);const replacement=place(s,'chants','撃雷');expect(viewFor(s,'A').inspection).toEqual(d);expect(JSON.stringify(viewFor(s,'A').inspection)).not.toContain(replacement);s=act(s,'A',{type:'CHOOSE_INSPECTION',decisionId:d.decisionId,choice:'discard-all'});expect(s.players.B!.chants[0]!.cardInstanceId).toBe(replacement);});
it.each(['death','disable','identity','public-target'] as const)('pending twin exchange revalidates %s and never refunds main action',change=>{let s=turnState('凍気のアイエル','c2-p04-r1c1-ab04');const a=[...s.players.A!.hand],b=[...s.players.B!.hand];s=use(s,'c2-p04-r1c1-ab04','B');if(change==='death'){s.players.B!.presence='dead';s.players.A!.protection={characterIds:[]};}else if(change==='disable')s.players.A!.statuses=[{id:'fixture',kind:'ability-disabled',modifiers:[0],nextCheck:0}];else if(change==='identity')character(s,'B','大神官ジル');else s.players.B!.revealed=false;s=finish(s);expect(s.players.A!.hand).toEqual(a);expect(s.players.B!.hand).toEqual(b);expect(s.phase).toBe('hand-adjustment');});
it.each(['empty','unequal','both-empty'])('whole twin hands allow %s without refill or OPEN',mode=>{let s=turnState('凍気のアイエル','c2-p04-r1c1-ab04');s.deck.push(...s.players.A!.hand);s.players.A!.hand=[];if(mode==='unequal')handCard(s,'A','撃雷');if(mode==='both-empty'){s.deck.push(...s.players.B!.hand);s.players.B!.hand=[];}const a=[...s.players.A!.hand],b=[...s.players.B!.hand],events=s.events.length;s=finish(use(s,'c2-p04-r1c1-ab04','B'));expect(s.players.A!.hand).toEqual(b);expect(s.players.B!.hand).toEqual(a);expect(s.events.slice(events).filter(e=>e.type==='CARD_DRAWN'||e.type==='OPEN')).toEqual([]);});
it('Lancaster empty discard still consumes main action',()=>{let s=owner('早駆けのランカスター');s.deck.push(...s.players.A!.hand);s.players.A!.hand=[];s=finish(use(s,LANCA));expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.hand).toEqual([]);});
it('Uonos actual forced Lia reveal retains actual LanceII mandatory producer and new Growth draw',()=>{let s=owner('邪祭ウーノス');character(s,'B','聖騎士ランスロット');character(s,'C','リーア姫');s=use(s,UONOS,'C');s=until(s,'lifecycle-boundary');s=priority(s,'B');const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r2c2-ab05')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId});s=finish(s);expect(s.players.B!.characterId).toBe('c2-p07-r1c1');s=act(s,'A',{type:'PASS_ACTION'});s=act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(5)});s=act(s,'B',{type:'START_TURN'});expect(viewFor(s,'B').drawAbilityOptions).toEqual([{abilityId:'c2-p07-r1c1-ab03',name:'成長'}]);const count=s.players.B!.hand.length;s=finish(act(s,'B',{type:'CHOOSE_DRAW',draw:true,abilityId:'c2-p07-r1c1-ab03'}));expect(s.players.B!.hand).toHaveLength(count+2);});
it.each(['c2-p01-r2c2-ab02','c2-p07-r1c1-ab03'])('%s decline, invalid selection and canceled replacement retain ordinary draw',id=>{let s=actualDraw(id);reject(s,'A',{type:'CHOOSE_DRAW',draw:false,abilityId:id});reject(s,'B',{type:'CHOOSE_DRAW',draw:true,abilityId:id});const count=s.players.A!.hand.length;const declined=act(s,'A',{type:'CHOOSE_DRAW',draw:false});expect(declined.players.A!.hand).toHaveLength(count);expect(declined.phase).toBe('action');s=cancel(act(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:id}));expect(s.players.A!.hand).toHaveLength(count+1);expect(s.phase).toBe('action');reject(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:id});});
it('draw replacement preserves OPEN refill without extra draw opportunity',()=>{let s=owner('小妖精のチャム');s.phase='draw';const open=handCard(s,'B','祝福');s.players.B!.hand=s.players.B!.hand.filter(id=>id!==open);s.deck.unshift(open);const count=s.players.A!.hand.length;s=finish(act(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:'c2-p01-r2c2-ab02'}));expect(s.players.A!.open).toContain(open);expect(s.players.A!.hand).toHaveLength(count+2);expect(s.phase).toBe('action');});
it('own turn extras use ordinary attack priority, return parent cursor, and never enter foreign private choices',()=>{let s=owner('小妖精のチャム');const attack=handCard(s,'A','踏み込み／弓');s=act(s,'A',{type:'ATTACK',cardInstanceId:attack,targetIds:['B'],dedicated:false});const parent=s.windows!.at(-1)!.id;s=inspect(use(s,CHAM,'B'));s=pass(s);expect(s.windows!.at(-1)!.id).toBe(parent);expect(s.windows!.at(-1)!.cursor).toBe(0);expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===CHAM)).toBe(false);s=finish(s);});
it('Lia excludes attack and far targets; hidden-target selection includes self while twins require actual public counterpart',()=>{const lia=owner('リーア姫');expect(viewFor(lia,'A').abilityOptions.some(o=>o.abilityId===LIA)).toBe(false);lia.distances.A!.B=lia.distances.B!.A='near';const card=handCard(lia,'A','踏み込み／弓');const attack=act(lia,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});expect(viewFor(attack,'A').abilityOptions.some(o=>o.abilityId===LIA)).toBe(false);for(const [name,id] of [['吟遊詩人のレスター',LESTER],['邪祭ウーノス',UONOS]]){const s=owner(name!);expect(viewFor(s,'A').abilityOptions.find(o=>o.abilityId===id)!.targetIds).toContain('A');}const twins=owner('凍気のアイエル');character(twins,'B','爆炎のフレイアード');expect(viewFor(twins,'A').abilityOptions.some(o=>o.abilityId==='c2-p04-r1c1-ab04')).toBe(false);});
it('selected draw actor self-Fate preserves existing reaction refill and only one ordinary draw after cancellation',()=>{let s=owner('小妖精のチャム');s.phase='draw';const fate=handCard(s,'A','命運凶変');const first=handCard(s,'C','撃雷'),second=handCard(s,'C','風矢');s.players.C!.hand=s.players.C!.hand.filter(id=>id!==first&&id!==second);s.deck.unshift(first,second);const count=s.players.A!.hand.length;s=act(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:'c2-p01-r2c2-ab02'});s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:viewFor(s,'A').reactionTargetAbilityId!});expect(s.players.A!.hand).toHaveLength(count);s=finish(s);expect(s.players.A!.hand).toHaveLength(count+1);expect(s.players.A!.hand).toEqual(expect.arrayContaining([first,second]));expect(s.discard).toContain(fate);});
it('structural pending hand-size change never expands the two-card draw into a refund',()=>{let s=owner('小妖精のチャム');s.phase='draw';s=act(s,'A',{type:'CHOOSE_DRAW',draw:true,abilityId:'c2-p01-r2c2-ab02'});const card=s.players.A!.hand.pop()!;s.discard.push(card);const count=s.players.A!.hand.length;s=finish(s);expect(s.players.A!.hand).toHaveLength(count+2);});
it('forced reveal during own attack preserves mandatory public allegiance defense cutoff',()=>{let s=owner('邪祭ウーノス');character(s,'B','黒騎士ガーウィン');const card=handCard(s,'A','風矢');s=act(s,'A',{type:'ATTACK',cardInstanceId:card,targetIds:['B'],dedicated:false});s=until(s,'attack-abilities');s=use(s,UONOS,'B');while(s.windows!.at(-1)!.kind!=='attack-abilities')s=pass(s);const g=Object.values(s.groups!)[0]!;expect(s.players.B!.revealed).toBe(true);expect(g.targets[0]!.hits.every(h=>h.defended)).toBe(true);s=finish(s);expect(s.players.B!.damage).toBe(0);});
it('Lancaster classifies normal printed magic on p18 whose catalogue stores school in attributes only',()=>{let s=owner('早駆けのランカスター');const ids=['沈黙','紋竜破','地裂','石化','結界'].map(name=>handCard(s,'A',name));s=finish(use(s,LANCA));expect(s.discard).toEqual(expect.arrayContaining(ids));});
it('exact source fixture contains all twelve unique abilities',()=>{expect(sources).toHaveLength(12);expect(new Set(sources.map(s=>s.id)).size).toBe(12);});
it('Uonos may force its own hidden card public and cannot authorize a voluntary-only foreign benefit',()=>{let s=owner('邪祭ウーノス');s=finish(use(s,UONOS,'A'));expect(s.players.A!.revealed).toBe(true);expect(viewFor(s,'A').revealAbilityOptions).toEqual([]);expect(s.events.at(-1)).toMatchObject({type:'CHARACTER_REVEALED',actorId:'A',characterId:'c2-p05-r1c1'});});
it('Cham preserves entire two-card follower order and face flags without publishing uninspected identity',()=>{let s=owner('小妖精のチャム');const f=place(s,'followers','飛竜'),g=place(s,'followers','兵士');const before=structuredClone(s.players.B!.followers);s=inspect(use(s,CHAM,'B'));expect(viewFor(s,'A').inspection!.cards).toEqual([{position:0,cardInstanceId:f},{position:1,cardInstanceId:g}]);expect(s.players.B!.followers).toEqual(before);for(const id of ['C','D']){const v=viewFor(s,id);expect(v.inspection).toBeNull();expect(v.players.B!.followers).toEqual([{position:0,face:'back'},{position:1,face:'back'}]);for(const hidden of [f,g,'PrivateInspection','sourceCharacterId','snapshot'])expect(JSON.stringify(v)).not.toContain(hidden);}s=pass(s);expect(s.players.B!.followers).toEqual(before);});
it.each([CHAM,STAR,LESTER,LIA])('inspection %s pre-resolution disable finishes without snapshot/deadlock',id=>{const name=id===CHAM?'小妖精のチャム':id===STAR?'占星術師のアルセイル':id===LESTER?'吟遊詩人のレスター':'リーア姫';let s=turnState(name,id);s=use(s,id,'B');s.players.A!.statuses=[{id:'fixture',kind:'ability-disabled',modifiers:[0],nextCheck:0}];s=finish(s);expect(viewFor(s,'A').inspection).toBeNull();expect(s.phase).toBe('action');});
it('own-turn inspection attempts do not reset after changing phase or JSON reconnect',()=>{let s=owner('小妖精のチャム');s=finish(use(s,CHAM,'B'));s=act(s,'A',{type:'PASS_ACTION'});expect(viewFor(JSON.parse(JSON.stringify(s)),'A').abilityOptions.some(o=>o.abilityId===CHAM)).toBe(false);s=act(s,'A',{type:'END_TURN',discardIds:s.players.A!.hand.slice(5)});for(const actor of ['B','C','D']){s=act(s,actor,{type:'START_TURN'});s=act(s,actor,{type:'CHOOSE_DRAW',draw:false});s=act(s,actor,{type:'PASS_ACTION'});s=act(s,actor,{type:'END_TURN',discardIds:s.players[actor]!.hand.slice(5)});}s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});expect(viewFor(s,'A').abilityOptions.some(o=>o.abilityId===CHAM)).toBe(true);});
it('late cancellation after entering a turn ability check rejects without spending Fate',()=>{let s=closeWindow(use(owner('占星術師のアルセイル'),STAR,'B'));s=priority(s,'B');const fate=handCard(s,'B','命運凶変');const id=Object.keys(s.abilities!)[0]!;reject(s,'B',{type:'PLAY_REACTION',cardInstanceId:fate,mode:'cancel-ability',targetAbilityId:id});expect(s.players.B!.hand).toContain(fate);});
