import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow,passReclaims} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeVoidSwordPhysical,voidSwordCard as CARD,voidSwordAdvances as ADV,voidSwordMode} from '../../../apps/worker/test/fixtures/void-sword-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s);}throw Error('VOID_SWORD_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B'],costs?:readonly string[]){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated,...(costs?{advanceCardInstanceIds:[...costs]}:{})};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['void-sword-ordinary','void-sword-guard','void-sword-owner-ordinary','void-sword-dedicated','void-sword-pair','void-sword-all','void-sword-cost-one','void-sword-cost-two','void-sword-cost-four','void-sword-near','void-sword-same-faction','void-sword-suppressed','void-sword-silenced'] as const)('%s actual physical declaration fixes advance count only into effect level and selected recipients',name=>{let s=makeVoidSwordPhysical(name,players);const m=voidSwordMode(name),targets=m.targets.map(i=>players[i]!.id),hand=[...s.players.A!.hand],deck=[...s.deck],distances=structuredClone(s.distances),markers=structuredClone(s.distanceMarkers??{}),rolls=s.rolls?.length??0;if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C'],m.costs));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});if(!m.dedicated)reject(s,'A',cmd(false,['B','C']));s=act(s,'A',cmd(m.dedicated,targets,m.dedicated?m.costs:undefined));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD&&!m.costs.includes(id as never)));expect(s.deck).toEqual(deck);expect(source(s).technique.effectLevel).toBe(m.dedicated?7+m.costs.length:6);expect(source(s).advanceCosts??[]).toEqual(m.costs);s=passReclaims(s);for(const id of m.costs)expect(s.discard.filter(c=>c===id)).toHaveLength(1);expect(s.distances).toEqual(distances);expect(s.distanceMarkers??{}).toEqual(markers);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'far',useLevel:6,effectLevel:m.dedicated?7+m.costs.length:6,damage:m.dedicated?15:10,attributes:['戦','剣'],destroyFollowerAttributes:['白'],evadeProhibited:true,target:m.dedicated?'all':'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(group(s).targets.map(t=>t.actorId)).toEqual(targets);reject(s,'A',cmd(m.dedicated,targets,[]));reject(s,'A',{type:'PAY_HIT_ADVANCES',groupId:group(s).id,cardInstanceIds:[]});s=settle(s);for(const id of ['B','C','D'])expect(s.players[id]!.damage).toBe(!targets.includes(id)?0:(m.dedicated?15:10)-(id==='C'?1:0));expect(s.players.B!.followers).toEqual([]);if(m.guard&&targets.includes('C'))expect(s.players.C!.followers).toEqual([]);for(const id of [CARD,...m.costs])expect(s.discard.filter(c=>c===id)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);expect(s.distances).toEqual(distances);expect(s.distanceMarkers??{}).toEqual(markers);});
it.each(['void-sword-water-ordinary','void-sword-water-zero','void-sword-water-one','void-sword-water-two'] as const)('%s actual nonwhite Water morale level7 resolves below equal and above paid effect without a damage bonus',name=>{let s=makeVoidSwordPhysical(name,players);const m=voidSwordMode(name);s=settle(act(s,'A',cmd(m.dedicated,['B'],m.dedicated?m.costs:undefined)));expect(s.players.B!.damage).toBe(m.dedicated&&m.costs.length>0?11:0);expect(s.players.B!.followers).toHaveLength(m.dedicated?0:1);expect(s.rolls).toHaveLength(1);expect(s.rolls![0]).toMatchObject({purpose:'follower-morale',success:true});});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior5 spirit6 actual shortage %s plus %s succeeds=%s',(x,y,success)=>{let s=act(makeVoidSwordPhysical('void-sword-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?10:0);expect(s.rolls).toHaveLength(1);});
it('actual warrior0 spirit0 elected four-cost all-target attack skips six usage checks while effect reaches11 damage stays15',()=>{let s=makeVoidSwordPhysical('void-sword-cost-four',players,{spirit:0});expect(gameStats(s,'A')).toMatchObject({warrior_level:0,spirit:0});s=settle(act(s,'A',cmd(true,['B','C','D'],ADV)));expect(s.players.B!.damage).toBe(15);expect(s.players.C!.damage).toBe(14);expect(s.players.D!.damage).toBe(15);expect(s.rolls?.length??0).toBe(0);});
it.each(['void-sword-maai','void-sword-maai-spare'] as const)('%s actual combat Maai cannot reuse an effect cost but a separate unspent advance can cancel it',name=>{let s=makeVoidSwordPhysical(name,players);const m=voidSwordMode(name),distances=structuredClone(s.distances);s=until(act(s,'A',cmd(true,['B','C'],m.costs)),s=>s.windows?.at(-1)?.kind==='normal-defense');s=passReclaims(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'}));s=until(s,s=>s.windows?.at(-1)?.kind==='defense-advance');reject(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:ADV[0]});if(m.suffix==='maai-spare')s=passReclaims(act(s,'A',{type:'PLAY_ADVANCE',cardInstanceId:ADV[1]}));expect(group(s).technique.effectLevel).toBe(8);s=settle(s);expect(s.players.B!.damage).toBe(m.suffix==='maai-spare'?15:0);expect(s.players.C!.damage).toBe(14);expect(s.players.B!.followers).toHaveLength(m.suffix==='maai-spare'?0:1);expect(s.distances).toEqual(distances);expect(s.distanceMarkers??{}).toEqual({});for(const id of [CARD,ADV[0],...(m.suffix==='maai-spare'?[ADV[1]]:[])])expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it.each(['void-sword-evade-ordinary','void-sword-evade-dedicated'] as const)('%s actual Evade prohibition applies to ordinary and elected attack',name=>{let s=makeVoidSwordPhysical(name,players);const m=voidSwordMode(name);s=until(act(s,'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(true);reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=settle(s);expect(s.players.B!.damage).toBe(m.dedicated?15:10);expect(s.players.B!.hand).toContain('a2-p05-r3c1');});
it('actual Fate cancellation retains two paid advances without forming distance or damaging either target',()=>{let s=makeVoidSwordPhysical('void-sword-fate',players);s=passReclaims(act(s,'A',cmd(true,['B','C'],ADV.slice(0,2))));const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId}));expect(s.players.B!.damage).toBe(0);expect(s.players.C!.damage).toBe(0);expect(s.players.B!.followers[0]!.revealed).toBe(false);expect(s.players.C!.followers[0]!.revealed).toBe(false);expect(s.distanceMarkers??{}).toEqual({});for(const id of [CARD,...ADV.slice(0,2)])expect(s.discard.filter(c=>c===id)).toHaveLength(1);});
it('actual invalid costs reject duplicates source non-advance foreign stale and ordinary payment before any spending',()=>{let s=makeVoidSwordPhysical('void-sword-invalid-cost',players);for(const costs of [[ADV[0],ADV[0]],[CARD],['a2-p06-r1c3'],['a2-p08-r3c3'],[ADV[2]],['missing']])reject(s,'A',cmd(true,['B'],costs));reject(s,'A',cmd(false,['B'],[ADV[0]]));for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',cmd(true,targetIds,[ADV[0]]));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:ADV[0],targetId:'B'}));reject(s,'A',cmd(true,['B'],[ADV[0]]));s=settle(act(s,'A',cmd(true,['B'],[ADV[1]])));expect(s.players.B!.damage).toBe(15);expect(Object.values(s.distanceMarkers!)[0]!.cardInstanceId).toBe(ADV[0]);expect(s.discard).not.toContain(ADV[0]);expect(s.discard).toContain(ADV[1]);});
it('actual incoming Bow refuses attack-only Void Sword in both defense modes',()=>{let s=makeVoidSwordPhysical('void-sword-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner stopped recovery and own action decline preserve unpaid sword',()=>{let s=makeVoidSwordPhysical('void-sword-wrong-owner',players,{warrior:6});reject(s,'A',cmd(true));expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(10);s=makeVoidSwordPhysical('void-sword-stopped',players);expect(s.players.A!.statuses?.some(x=>x.kind==='stopped')).toBe(true);expect(s.seatOrder[s.turnSeat]).not.toBe('A');reject(s,'A',cmd(true));s=makeVoidSwordPhysical('void-sword-decline',players,{beforeStart:true});reject(s,'A',cmd());s=act(s,'A',{type:'START_TURN'});reject(s,'A',cmd());s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});reject(s,'B',cmd());reject(s,'A',{type:'REST',cardInstanceIds:[CARD]});reject(s,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);});
