import {getCharacter} from '@madou/catalog';
import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeWaterDragonPhysicalScenario,waterDragonPhysicalMode,type WaterDragonPhysicalScenario} from './fixtures/water-dragon-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['water-dragon-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WATER_DRAGON_TURN');}throw Error('WATER_DRAGON_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p23-r1c1',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=makeWaterDragonPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});for(const id of s.seatOrder)s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hpValue,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=ready(makeWaterDragonPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p22-r3c3']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=waterDragonPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeWaterDragonPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=waterDragonPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeWaterDragonPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hpValue,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?Math.max(0,6-m.hpValue)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=until(incoming(ready(makeWaterDragonPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
const WATER_DRAGON='a2-p23-r1c1',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);return act(s,'B',grant(s,'B','a2-p21-r2c3'));}


it.each(['pass','fail'] as const)('actual Water Dragon spirit6 morale %s shares one result across Dwarf8 hits and applies HP4 reduction',mode=>{
 let s=ready(makeWaterDragonPhysicalScenario('water-dragon-higher',players,{spirit:6}),WATER_DRAGON);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',modifier:0,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,4]:[3,4]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:6,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.descriptor.hp).toBe(4);expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual(Array(3).fill(mode==='pass'?4:0));s=finish(s);expect(s.players.A!.damage).toBe(mode==='pass'?6:18);expect(s.discard.filter(id=>id===WATER_DRAGON)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual surviving Water Dragon checks each later group while an unreached hidden rear never checks',()=>{
 let s=ready(makeWaterDragonPhysicalScenario('water-dragon-setup',players),WATER_DRAGON);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);
 let q=ready(makeWaterDragonPhysicalScenario('water-dragon-setup',players,{spirit:0}),WATER_DRAGON,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',WATER_DRAGON]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each(['竜皇子アスフェルト','獣使いのウパニシャット'] as const)('actual %s cannot elect unprinted Water Dragon morale waiver or direct hand or placed attack',owner=>{
 let s=ready(makeWaterDragonPhysicalScenario('water-dragon-morale-fail',players,{owner}),WATER_DRAGON);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[WATER_DRAGON]});s=finish(s);expect(s.players.A!.damage).toBe(18);
 for(const placed of [false,true]){const q=ready(makeWaterDragonPhysicalScenario('water-dragon-army',players,{owner}),WATER_DRAGON,placed);for(const dedicated of [false,true])reject(q,'A',{type:'ATTACK',cardInstanceId:WATER_DRAGON,targetIds:['B','C','D'],dedicated});reject(q,'A',{type:'CHANT',cardInstanceId:WATER_DRAGON});}
});
it.each(['water-dragon-sky','water-dragon-destroy'] as const)('%s actual sky ignore or explicit destruction bypasses Water Dragon HP4 before morale',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=next(ready(makeWaterDragonPhysicalScenario(scenario,players),WATER_DRAGON));s=until(act(s,'B',{type:'ATTACK',cardInstanceId:m.sky?'a2-p15-r1c3':'a2-p13-r1c2',targetIds:m.sky?['A','C']:['A'],dedicated:true}),'hit');const f=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense![0]!;expect(f.hits[0]!.outcome).toBe(m.sky?'passed-through':'level-destroyed');s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.sky?[12,12]:[0,0]);expect(s.players.A!.followers).toHaveLength(m.sky?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toEqual([]);if(m.sky)expect(s.players.A!.followers[0]!.revealed).toBe(false);else expect(s.discard.filter(id=>id===WATER_DRAGON)).toHaveLength(1);
});
const UPA='c2-p05-r1c2-ab02';
function waterAttack(s:GameState,scenario:WaterDragonPhysicalScenario,targets=['B','C','D']){if(waterDragonPhysicalMode(scenario).army)return{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:WATER_DRAGON,targetIds:targets};const o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId===UPA)!;expect(o).toBeDefined();return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:UPA,targetEventId:o.targetEventId,sources:[{cardInstanceId:WATER_DRAGON,dedicated:false,targetIds:targets}]};}
it.each(['water-dragon-army','water-dragon-grant-hand','water-dragon-grant-field'] as const)('%s actual Army or Upa beast grant preserves mandatory all far water magic6 damage5 and ordinary checks',scenario=>{
 const m=waterDragonPhysicalMode(scenario);for(const magic of [5,6]){let s=ready(makeWaterDragonPhysicalScenario(scenario,players,{magic,warrior:magic===5?20:0}),WATER_DRAGON,m.initial);for(const targetIds of [[],['A'],['B'],['B','C'],['B','B','C','D']])reject(s,'A',waterAttack(s,scenario,targetIds));if(m.grant){const command=waterAttack(s,scenario);if(command.type!=='USE_FOLLOWER_ATTACK')throw Error('EXPECTED_GRANT');reject(s,'A',{...command,sources:command.sources.map(source=>({...source,dedicated:true}))});}s=act(s,'A',waterAttack(s,scenario));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===WATER_DRAGON)!;expect(a.checks).toHaveLength(6-magic);expect(a.technique).toMatchObject({range:'far',school:'magic',useLevel:6,effectLevel:6,damage:5,attributes:['遠','魔','水'],noChecks:false,hitCount:1,target:'all',mandatoryAll:true,stopUntilSourceTurn:true});s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([5,5,5]);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.players.A!.followers).toEqual([]);for(const id of m.army?[WATER_DRAGON,ARMY]:[WATER_DRAGON])expect(s.discard.filter(x=>x===id)).toHaveLength(1);}
});
it('actual Dia human grant excludes Water Dragon and hand-only Army excludes placed source',()=>{
 let s=ready(makeWaterDragonPhysicalScenario('water-dragon-army',players,{owner:'魔聖母ディア'}),WATER_DRAGON,false);expect(viewFor(s,'A').followerBundleOptions.flatMap(o=>o.sources).some(o=>o.cardInstanceId===WATER_DRAGON)).toBe(false);reject(s,'A',{type:'USE_FOLLOWER_ATTACK',abilityId:'c2-p06-r1c2-ab04',targetEventId:`turn-${s.turnNumber??0}-A-action`,sources:[{cardInstanceId:WATER_DRAGON,dedicated:false,targetIds:['B','C','D']}]});s=ready(makeWaterDragonPhysicalScenario('water-dragon-army',players),WATER_DRAGON);reject(s,'A',waterAttack(s,'water-dragon-army'));
});
it.each(['water-dragon-army','water-dragon-grant-hand'] as const)('%s actual mandatory all remains legal after approach and target-local maai or Mirror never refunds source',scenario=>{
 for(const defense of ['maai','mirror']){let s=ready(makeWaterDragonPhysicalScenario(scenario,players),WATER_DRAGON,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=until(act(s,'A',waterAttack(s,scenario)),'normal-defense');s=finish(act(s,'B',defense==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}));expect(['A','B','C','D'].map(id=>s.players[id]!.damage)).toEqual([defense==='mirror'?5:0,0,5,5]);expect(s.discard.filter(id=>id===WATER_DRAGON)).toHaveLength(1);}
});
it.each(['parent','child','morale','use','grant','grant-child','grant-use'] as const)('actual Water Dragon %s cancellation or forced failure spends physical costs once before all targets',mode=>{
 const scenario=mode.startsWith('grant')?'water-dragon-grant-field':'water-dragon-army',m=waterDragonPhysicalMode(scenario);let s=ready(makeWaterDragonPhysicalScenario(scenario,players,{magic:5}),WATER_DRAGON,m.initial);s=act(s,'A',waterAttack(s,scenario));if(mode==='child'||mode==='grant-child')s=closeWindow(s);if(mode==='morale'||mode==='use'||mode==='grant-use'){s=until(s,'before-roll');if(mode==='use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='morale'?'follower-morale':'excess-level');}const a=Object.values(s.actions!).find(a=>a.cardInstanceId===(mode==='parent'?ARMY:WATER_DRAGON))!,roll=s.rolls?.at(-1),ability=Object.values(s.abilities??{}).find(a=>a.abilityId===UPA);while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='morale'||mode==='use'||mode==='grant-use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a.id}));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.players.A!.followers).toEqual([]);for(const id of m.army?[WATER_DRAGON,ARMY]:[WATER_DRAGON])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});

function stepTurn(s:GameState){const w=s.windows?.at(-1),id=s.seatOrder[s.turnSeat]!;if(w)return pass(s);if(s.phase==='action')return act(s,id,{type:'PASS_ACTION'});if(s.phase==='withdrawal')return act(s,id,{type:'PASS_WITHDRAWAL'});if(s.phase==='hand-adjustment')return act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});if(s.phase==='turn-start')return act(s,id,{type:'START_TURN'});if(s.phase==='draw')return act(s,id,{type:'CHOOSE_DRAW',draw:false});throw Error(`WATER_TURN_${s.phase}`);}
function seat(s:GameState,id:string){for(let n=0;n<250;n++){if(!s.windows?.length&&s.seatOrder[s.turnSeat]===id&&s.phase==='turn-start')return s;s=stepTurn(s);}throw Error('WATER_SEAT_LIMIT');}
function waterStops(s:GameState,id:string){return (s.players[id]!.statuses??[]).filter(status=>status.sourceCardInstanceId===WATER_DRAGON&&status.timing==='source-turn');}
function attackReady(s:GameState,scenario:WaterDragonPhysicalScenario){const m=waterDragonPhysicalMode(scenario);if(m.initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:WATER_DRAGON});s=act(s,'A',{type:'PASS_SETUP'});for(const cardInstanceId of m.pair??[])s=act(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId});for(const id of ['B','C','D'])s=act(s,id,{type:'PASS_SETUP'});s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
it.each(['water-dragon-army','water-dragon-grant-hand','water-dragon-grant-field'] as const)('%s actual body hits stop all recipients without resistance until source seat arrives before recovery',scenario=>{
 let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=finish(act(s,'A',waterAttack(s,scenario)));for(const id of ['B','C','D']){expect(s.players[id]!.damage).toBe(5);expect(waterStops(s,id)).toEqual([expect.objectContaining({kind:'stopped',sourceActorId:'A',sourceCardInstanceId:WATER_DRAGON,targetId:id})]);}expect(s.rolls?.filter(r=>r.purpose==='status-resistance')??[]).toEqual([]);s=seat(s,'B');expect(waterStops(s,'B')).toHaveLength(1);s=stepTurn(s);expect(waterStops(s,'B')).toHaveLength(1);s=seat(s,'A');for(const id of ['B','C','D'])expect(waterStops(s,id)).toEqual([]);expect(s.rolls?.filter(r=>r.purpose==='status-recovery')??[]).toEqual([]);expect(s.discard.filter(id=>id===WATER_DRAGON)).toHaveLength(1);
});
it.each(['water-dragon-army-block','water-dragon-army-hp'] as const)('%s actual follower blocking or HP-only reduction distinguishes whether the body was hit',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=finish(act(s,'A',waterAttack(s,scenario)));expect(s.players.B!.damage).toBe(0);expect(waterStops(s,'B')).toHaveLength(m.block?0:1);expect(s.players.B!.followers.map(f=>f.cardInstanceId)).toEqual(m.block?m.pair:[]);for(const id of ['C','D']){expect(s.players[id]!.damage).toBe(5);expect(waterStops(s,id)).toHaveLength(1);}
});
it.each(['water-dragon-army-maai','water-dragon-army-mirror'] as const)('%s actual local defense prevents recipient stop and reflection changes only its source clock',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=until(act(s,'A',waterAttack(s,scenario)),'normal-defense');s=finish(act(s,'B',m.mirror?{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false}:{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));expect(waterStops(s,'B')).toEqual([]);expect(waterStops(s,'A')).toHaveLength(m.mirror?1:0);if(m.mirror)expect(waterStops(s,'A')[0]!.sourceActorId).toBe('B');for(const id of ['C','D'])expect(waterStops(s,id)[0]!.sourceActorId).toBe('A');s=seat(s,'B');expect(waterStops(s,'A')).toEqual([]);for(const id of ['C','D'])expect(waterStops(s,id)).toHaveLength(1);s=seat(s,'A');for(const id of s.seatOrder)expect(waterStops(s,id)).toEqual([]);expect(s.rolls?.filter(r=>r.purpose==='status-recovery')??[]).toEqual([]);
});
it('actual Dragon King hit schedules the Water attacker to skip but its arriving seat still expires all water stops',()=>{
 const scenario='water-dragon-army-skip';let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=until(act(s,'A',waterAttack(s,scenario)),'normal-defense');s=finish(act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}));s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p09-r2c2',targetIds:['A'],dedicated:true}));expect(s.players.A!.skipTurns).toBe(1);for(const id of ['C','D'])expect(waterStops(s,id)).toHaveLength(1);s=seat(s,'A');for(const id of ['C','D'])expect(waterStops(s,id)).toEqual([]);expect(s.players.A!.skipTurns).toBe(1);s=act(s,'A',{type:'START_TURN'});expect(s.seatOrder[s.turnSeat]).toBe('B');expect(s.players.A!.skipTurns).toBe(0);expect(s.rolls?.filter(r=>r.purpose==='status-recovery')??[]).toEqual([]);
});
it.each(['water-dragon-army-dead','water-dragon-army-wander'] as const)('%s actual reflected death or protector death still expires Water stop when inactive source seat arrives',scenario=>{
 const m=waterDragonPhysicalMode(scenario);let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=act(s,'A',waterAttack(s,scenario));if(m.dead){s=until(s,'normal-defense');s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:false});}s=finish(s);if(m.wander){expect(s.players.C!.presence).toBe('dead');expect(s.players.A!.protection!.characterIds).toContain(s.players.C!.characterId);}expect(s.players.A!.presence).toBe(m.dead?'dead':'wandering');expect(s.outcome).toBeUndefined();const recipients=m.dead?['C','D']:['B','D'];for(const id of recipients)expect(waterStops(s,id)[0]!.sourceActorId).toBe('A');s=seat(s,'D');for(const id of recipients)expect(waterStops(s,id)).toHaveLength(1);s=seat(s,'B');expect(s.players.A!.presence).toBe(m.dead?'dead':'wandering');for(const id of recipients)expect(waterStops(s,id)).toEqual([]);expect(s.rolls?.filter(r=>r.purpose==='status-recovery')??[]).toEqual([]);expect(s.discard.filter(id=>id===WATER_DRAGON)).toHaveLength(1);
});
it('actual unrelated Nightmare stop survives Water expiry with only its own recovery rolls',()=>{
 const scenario='water-dragon-army-overlap';let s=attackReady(makeWaterDragonPhysicalScenario(scenario,players),scenario);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p15-r2c2',targetIds:['C'],dedicated:false}));const other=s.players.C!.statuses!.find(status=>status.sourceCardInstanceId==='a2-p15-r2c2')!;expect(other.kind).toBe('stopped');s=next(s,'A');expect(s.players.A!.faction).not.toBe(s.players.C!.faction);expect(viewFor(s,'A').allArmyOptions[0]!.legalTargetIds).toEqual(['B','C','D']);s=finish(act(s,'A',waterAttack(s,scenario)));expect(s.players.C!.statuses).toEqual(expect.arrayContaining([expect.objectContaining({id:other.id}),expect.objectContaining({sourceCardInstanceId:WATER_DRAGON,timing:'source-turn'})]));s=seat(s,'A');for(const id of ['B','C','D'])expect(waterStops(s,id)).toEqual([]);expect(s.players.C!.statuses).toContainEqual(expect.objectContaining({id:other.id,kind:'stopped'}));const recoveries=s.rolls!.filter(r=>r.purpose==='status-recovery');expect(recoveries).toHaveLength(2);expect(recoveries.every(r=>r.rollerId==='C')).toBe(true);
});
