import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeWaterStatusScenario,waterStatusMode,type WaterStatusScenario} from './fixtures/water-status-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
const rows=['poison-flow-ordinary','poison-flow-dedicated','freeze-ordinary','freeze-dedicated'] as const;
function command(scenario:WaterStatusScenario){const m=waterStatusMode(scenario);return {type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C']:['B'],dedicated:m.dedicated};}
function settle(s:GameState,faces:number[]=[1,1]){for(let n=0;n<400&&s.windows?.length;n++){const r=s.rolls?.at(-1);s=pass(s,r?.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)&&r.stage==='before-roll'?faces:[1,1]);}expect(s.windows??[]).toEqual([]);return s;}
function nextB(s:GameState){for(let n=0;n<200;n++){const id=s.seatOrder[s.turnSeat]!;if(s.windows?.length)s=pass(s);else if(s.phase==='turn-start'){if(id==='B')return s;s=act(s,id,{type:'START_TURN'});}else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WATER_STATUS_PHASE');}throw Error('WATER_STATUS_TURN_LIMIT');}
function reject(s:GameState,actorId:string,command:unknown,code?:string){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id)),r=transition(s,{actorId,command} as never,entropy());expect(r.ok).toBe(false);if(code)expect(r).toMatchObject({code});expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(rows)('%s actual profile use-level boundary and successful target resistance keep printed base damage',scenario=>{
 const m=waterStatusMode(scenario);for(const level of [m.use-1,m.use]){let s=act(makeWaterStatusScenario(scenario,players,{level}),'A',command(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.use,effectLevel:m.effect,damage:m.damage,attributes:['魔','水'],chant:false,noChecks:m.dedicated,target:m.dedicated?'all':'one',onHitResistance:{modifiers:[m.modifier]}});expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=settle(s);expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([m.damage,m.dedicated?m.damage:0,0]);const rolls=s.rolls!.filter(r=>r.purpose==='status-resistance');expect(rolls).toHaveLength(m.dedicated?2:1);expect(rolls[0]).toMatchObject({rollerId:'B',modifier:m.modifier,threshold:6+m.modifier,success:true,faces:[1,1]});expect(s.players.B!.statuses??[]).toEqual([]);}
});
it.each(rows)('%s actual failed target resistance adds only Poison six or creates source-owned Freeze stop',scenario=>{
 const m=waterStatusMode(scenario);let s=settle(act(makeWaterStatusScenario(scenario,players),'A',command(scenario)),[6,6]);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([m.damage+(m.poison?6:0),m.dedicated?m.damage:0]);expect(s.rolls!.filter(r=>r.purpose==='status-resistance').map(r=>({actor:r.rollerId,modifier:r.modifier,success:r.success}))).toEqual(m.dedicated?[{actor:'B',modifier:m.modifier,success:false},{actor:'C',modifier:m.modifier,success:true}]:[{actor:'B',modifier:m.modifier,success:false}]);expect(s.players.B!.statuses??[]).toEqual(m.poison?[]:[expect.objectContaining({kind:'stopped',modifiers:[m.modifier],nextCheck:1,sourceActorId:'A',sourceCardInstanceId:m.card,targetId:'B'})]);expect(s.players.C!.statuses??[]).toEqual([]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual maai or Evade prevents B resistance and leaves dedicated C independent',scenario=>{
 const m=waterStatusMode(scenario);for(const defense of ['maai','evade']){let s=until(act(makeWaterStatusScenario(scenario,players),'A',command(scenario)),'normal-defense');s=defense==='maai'?act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}):act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=settle(s,[6,6]);expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,m.dedicated?m.damage:0]);expect((s.rolls??[]).filter(r=>r.purpose==='status-resistance').map(r=>r.rollerId)).toEqual(m.dedicated?['C']:[]);expect(s.players.B!.statuses??[]).toEqual([]);}
});
it.each(rows)('%s actual Fate cancellation pays once without target resistance or stop',scenario=>{
 const m=waterStatusMode(scenario);let s=act(makeWaterStatusScenario(scenario,players),'A',command(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;s=pass(s);s=pass(s);s=settle(act(s,'C',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.B!.damage,s.players.C!.damage]).toEqual([0,0]);expect(s.rolls??[]).toEqual([]);expect(s.players.B!.statuses??[]).toEqual([]);expect(s.discard.filter(id=>id===m.card)).toHaveLength(1);
});
it.each(['freeze-ordinary','freeze-dedicated'] as const)('%s actual repeated own-turn recovery retains its original modifier until success and then refills',scenario=>{
 const m=waterStatusMode(scenario);let s=until(act(makeWaterStatusScenario(scenario,players,{follower:true}),'A',command(scenario)),'normal-defense');const initialHand=s.players.B!.hand.length;s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p06-r1c1',dedicated:false});s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'teleport',rollerId:'B'});s=closeWindow(s,[6,6]);s=until(s,'normal-defense');expect(s.rolls!.at(-1)!.success).toBe(false);expect(s.players.B!.hand).toHaveLength(initialHand-1);s=until(s,'before-roll');expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-resistance',rollerId:'B'});s=settle(s,[6,6]);expect(s.discard.filter(id=>id==='a2-p06-r1c1')).toHaveLength(1);expect(s.rolls!.filter(r=>r.rollerId==='B').map(r=>({purpose:r.purpose,faces:r.faces,threshold:r.threshold,success:r.success}))).toEqual([{purpose:'teleport',faces:[6,6],threshold:6,success:false},{purpose:'status-resistance',faces:[6,6],threshold:6+m.modifier,success:false}]);expect(s.players.B!.damage).toBe(m.damage-1);expect(s.players.B!.hand).toHaveLength(gameStats(s,'B').handLimit-1);const id=s.players.B!.statuses![0]!.id;s=nextB(s);s=act(s,'B',{type:'START_TURN'});expect(s.rolls!.at(-1)).toMatchObject({purpose:'status-recovery',modifier:m.modifier,faces:[]});s=settle(s,[6,6]);expect(s.players.B!.statuses![0]).toMatchObject({id,nextCheck:2,modifiers:[m.modifier]});expect(s.players.B!.hand).toHaveLength(gameStats(s,'B').handLimit-1);expect(s.seatOrder[s.turnSeat]).toBe('C');s=nextB(s);const draws=s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B').length;s=act(s,'B',{type:'START_TURN'});s=settle(s,[1,1]);expect(s.events.filter(e=>e.type==='CARD_DRAWN'&&e.actorId==='B')).toHaveLength(draws+1);expect(s.players.B!.statuses).toEqual([]);expect(s.players.B!.hand).toHaveLength(gameStats(s,'B').handLimit);expect(s.phase).toBe('draw');expect(s.seatOrder[s.turnSeat]).toBe('B');s=act(s,'B',{type:'CHOOSE_DRAW',draw:false});expect(s.phase).toBe('action');expect(s.rolls!.filter(r=>r.rollerId==='B'&&['status-resistance','status-recovery'].includes(r.purpose)).map(r=>({modifier:r.modifier,success:r.success}))).toEqual([{modifier:m.modifier,success:false},{modifier:m.modifier,success:false},{modifier:m.modifier,success:true}]);
});
it.each(['freeze-ordinary','freeze-dedicated'] as const)('%s the same actual four-point resistance distinguishes minus1 from minus3',scenario=>{
 const m=waterStatusMode(scenario),s=settle(act(makeWaterStatusScenario(scenario,players),'A',command(scenario)),[2,2]);expect(s.rolls!.find(r=>r.purpose==='status-resistance')!.success).toBe(!m.dedicated);expect((s.players.B!.statuses??[]).length).toBe(m.dedicated?1:0);
});
it.each(rows)('%s refuses foreign dedicated owner ordinary multiple targets unprinted chant and unsupported variant',scenario=>{
 const m=waterStatusMode(scenario),s=makeWaterStatusScenario(scenario,players),foreign=makeWaterStatusScenario(scenario,players,{owner:'聖騎士ランスロット'});reject(foreign,'A',{...command(scenario),dedicated:true});reject(s,'A',{...command(scenario),targetIds:['B','C'],dedicated:false});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});reject(s,'A',{...command(scenario),techniqueVariant:'two-hit'});
});
