import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeWhirlwindKickPhysical,whirlwindKickCard as CARD,whirlwindKickMode} from '../../../apps/worker/test/fixtures/whirlwind-kick-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s);}throw Error('WHIRLWIND_KICK_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['whirlwind-kick-ordinary','whirlwind-kick-owner-ordinary','whirlwind-kick-dedicated','whirlwind-kick-same-faction','whirlwind-kick-suppressed','whirlwind-kick-silenced'] as const)('%s actual approached physical strike preserves six fixed damage two Maai and optional Gil mode',name=>{let s=makeWhirlwindKickPhysical(name,players);const m=whirlwindKickMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],rolls=s.rolls?.length??0;expect(s.distances.A!.B).toBe('near');expect(gameStats(s,'A').spirit).toBe(6);expect(gameStats(s,'B').spirit).toBe(11);if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);s=until(s,s=>s.windows?.at(-1)?.kind==='damage');expect(source(s).technique.damage).toBe(6);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique).toMatchObject({school:'warrior',range:'near',useLevel:6,effectLevel:6,damage:6,attributes:['戦','格'],maaiRequired:2,target:'one',chant:false,counter:false,noChecks:m.dedicated,followerIgnore:false});expect(group(s).technique.characterImmunityExceptions??[]).toEqual([]);s=settle(s);expect(s.players.B!.damage).toBe(6);expect(s.players.C!.damage).toBe(0);expect(s.discard.filter(c=>c===CARD)).toHaveLength(1);expect(s.rolls?.length??0).toBe(rolls);});
it.each([[false,0],[false,1],[false,12],[true,0],[true,1],[true,12]] as const)('actual caster spirit boundary dedicated=%s spirit%s preserves fixed six independent of either spirit',(dedicated,spirit)=>{let s=makeWhirlwindKickPhysical(dedicated?'whirlwind-kick-dedicated':'whirlwind-kick-ordinary',players,{spirit});expect(gameStats(s,'A').warrior_level).toBe(dedicated?0:6);s=until(act(s,'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(6);expect(group(s).targets[0]!.hits[0]!.damage).toBe(6);s=settle(s);expect(s.players.B!.damage).toBe(6);expect(s.rolls??[]).toHaveLength(0);});
it.each([['whirlwind-kick-water',0,true],['whirlwind-kick-equal',0,false],['whirlwind-kick-lower',4,false]] as const)('%s actual follower level boundary yields%s and survives=%s without follower bypass',(name,damage,survives)=>{let s=settle(act(makeWhirlwindKickPhysical(name,players),'A',cmd(true)));expect(s.players.B!.damage).toBe(damage);expect(s.players.B!.followers).toHaveLength(survives?1:0);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(name==='whirlwind-kick-water'?1:0);if(!survives)expect(s.discard).toContain(whirlwindKickMode(name).follower);});
it.each(['whirlwind-kick-maai-one-ordinary','whirlwind-kick-maai-two-ordinary','whirlwind-kick-maai-one-dedicated','whirlwind-kick-maai-two-dedicated'] as const)('%s actual one or two physical Maai preserves shared extra-one requirement in both modes',name=>{const m=whirlwindKickMode(name),two=m.suffix.includes('-two-');let s=until(act(makeWhirlwindKickPhysical(name,players),'A',cmd(m.dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});if(two){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');reject(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r1c3'});s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId:'a2-p06-r2c1'});}s=settle(s);expect(s.players.B!.damage).toBe(two?0:6);expect(s.discard.filter(id=>id==='a2-p06-r1c3')).toHaveLength(1);if(two)expect(s.discard.filter(id=>id==='a2-p06-r2c1')).toHaveLength(1);expect(s.distances.A!.B).toBe('near');});
it.each([false,true] as const)('actual physical strike allows Evade in both selected modes dedicated=%s',dedicated=>{let s=until(act(makeWhirlwindKickPhysical(dedicated?'whirlwind-kick-evade-dedicated':'whirlwind-kick-evade-ordinary',players),'A',cmd(dedicated)),s=>s.windows?.at(-1)?.kind==='normal-defense');expect(viewFor(s,'B').currentAttack!.defenseRestrictions.evadeProhibited).toBe(false);s=settle(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.discard.filter(id=>id==='a2-p05-r3c1')).toHaveLength(1);});
it.each([[3,3,true],[3,4,false]] as const)('ordinary warrior5 spirit6 actual shortage check %s plus %s success=%s',(x,y,success)=>{let s=act(makeWhirlwindKickPhysical('whirlwind-kick-low',players),'A',cmd());s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',threshold:6,total:x+y,success});s=settle(s);expect(s.players.B!.damage).toBe(success?6:0);expect(s.rolls).toHaveLength(1);});
it.each([false,true] as const)('actual far target rejects until real approach enables near strike dedicated=%s',dedicated=>{let s=makeWhirlwindKickPhysical('whirlwind-kick-far',players,{warrior:6});reject(s,'A',cmd(dedicated));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(dedicated)));expect(s.players.B!.damage).toBe(6);});
it('actual Fate source cancellation spends source once before spirit value or hit',()=>{let s=act(makeWhirlwindKickPhysical('whirlwind-kick-fate',players),'A',cmd(true));const actionId=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:actionId}));expect(s.players.B!.damage).toBe(0);expect(s.rolls??[]).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);});
it('actual incoming Bow refuses normal and dedicated attack-only strike',()=>{let s=makeWhirlwindKickPhysical('whirlwind-kick-noncounter',players);for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);});
it('actual wrong owner malformed targets foreign actor unused timing and stopped turn reject unpaid',()=>{const s=makeWhirlwindKickPhysical('whirlwind-kick-wrong-owner',players,{warrior:6});reject(s,'A',cmd(true));for(const targetIds of [[],['A'],['B','B'],['missing'],['B','C']])reject(s,'A',cmd(false,targetIds));reject(s,'B',cmd());expect(settle(act(s,'A',cmd())).players.B!.damage).toBe(6);let t=makeWhirlwindKickPhysical('whirlwind-kick-decline',players,{beforeStart:true});reject(t,'A',cmd());t=act(t,'A',{type:'START_TURN'});reject(t,'A',cmd());t=act(t,'A',{type:'CHOOSE_DRAW',draw:false});reject(t,'A',{type:'REST',cardInstanceIds:[CARD]});reject(t,'A',{type:'PLAY_TURN_CARD',cardInstanceIds:[CARD]});t=act(t,'A',{type:'PASS_ACTION'});expect(t.players.A!.hand).toContain(CARD);t=makeWhirlwindKickPhysical('whirlwind-kick-stopped',players);expect(t.seatOrder[t.turnSeat]).not.toBe('A');reject(t,'A',cmd(true));expect(t.players.A!.hand).toContain(CARD);});
