import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,finish,until,closeWindow,readySetup} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeWingedFolkPhysicalScenario,wingedFolkPhysicalMode,type WingedFolkPhysicalScenario} from '../../../apps/worker/test/fixtures/winged-folk-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['winged-setup'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function ready(s:GameState,card:string,initial=true,rear=false){if(initial)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:card});if(rear)s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:'a2-p22-r1c1'});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});return act(s,'A',{type:'CHOOSE_DRAW',draw:false});}
function next(s:GameState,target='B'){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(id===target&&s.phase==='action')return s;else if(s.phase==='action')s=act(s,id,{type:'PASS_ACTION'});else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p24-r1c2','a2-p24-r2c1','a2-p21-r2c3'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('WINGED_FOLK_TURN');}throw Error('WINGED_FOLK_LIMIT');}
function incoming(s:GameState){s=next(s);return act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false});}
function grant(s:GameState,actor='A',card='a2-p21-r1c3',target=actor==='A'?'B':'A'){const o=viewFor(s,actor).followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04');if(!o)throw Error('MISSING_DIA_GRANT');return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:card,dedicated:false,targetIds:[target]}]};}
it.each(rows)('%s actual setup placement hides identity and physical Bow3 compares printed level HP and attributes',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);let s=makeWingedFolkPhysicalScenario(scenario,players);reject(s,'B',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=act(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});expect(s.players.A!.followers).toContainEqual({cardInstanceId:m.card,revealed:false,placedById:'A',placedLifeId:'initial-life:A'});for(const id of ['B','C','D'])expect(JSON.stringify(viewFor(s,id))).not.toContain(m.card);reject(s,'A',{type:'PLACE_INITIAL_FOLLOWER',cardInstanceId:m.card});s=readySetup(s);s=act(s,'A',{type:'START_TURN'});s=act(s,'A',{type:'CHOOSE_DRAW',draw:false});s=until(incoming(s),'follower-start');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.source).toBe('physical');if(f.source!=='physical')throw Error('EXPECTED_PHYSICAL_FOLLOWER');expect(f.cardInstanceId).toBe(m.card);expect(f.levels).toEqual([m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(f.hits).toEqual([]);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(m.level>3?[m.card]:[]);expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it.each(rows)('%s actual own-action placement reordering and voluntary removal maintain physical order and hidden input',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);let s=ready(makeWingedFolkPhysicalScenario(scenario,players),m.card,false);reject(s,'B',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,m.card]});reject(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1','a2-p23-r1c1']});s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:[m.card,'a2-p22-r1c1']});expect(s.phase).toBe('hand-adjustment');expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual([m.card,'a2-p22-r1c1']);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1',m.card]);s=next(s,'A');s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1']});expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(['a2-p22-r1c1']);expect(s.discard.filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s actual front-first defense consumes reached low follower but high front keeps hidden rear untouched',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);for(const reverse of [false,true]){let s=ready(makeWingedFolkPhysicalScenario(scenario,players),m.card,true,true);if(reverse)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',m.card]});s=until(incoming(s),'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!;expect(t.followerSnapshot).toEqual(reverse?['a2-p22-r1c1',m.card]:[m.card,'a2-p22-r1c1']);s=finish(s);expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers.map(f=>f.cardInstanceId)).toEqual(reverse?['a2-p22-r1c1',m.card]:m.level>3?[m.card,'a2-p22-r1c1']:['a2-p22-r1c1']);if(reverse){expect(s.players.A!.followers[1]!.revealed).toBe(false);expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);}else expect(s.discard.filter(x=>x===m.card)).toHaveLength(m.level>3?0:1);}
});
it.each(rows)('%s actual granted Dwarf three hits compare higher equal lower and apply HP independently to every hit',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);for(const level of [m.level-1,m.level,m.level+1]){let s=ready(makeWingedFolkPhysicalScenario(scenario,players,{dwarf:true,level}),m.card);s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));s=act(s,'B',grant(s,'B','a2-p21-r2c3'));s=until(s,'follower-start');const t=Object.values(s.groups!)[0]!.targets[0]!,f=t.followerDefense![0]!;expect(t.hits).toHaveLength(3);expect(f.levels).toEqual([m.level,m.level,m.level]);expect(f.descriptor).toMatchObject({level:m.level,hp:m.hp,attributes:m.attributes});expect(t.hits.map(h=>h.damage)).toEqual([6,6,6]);s=finish(s);expect(s.players.A!.damage).toBe(level>m.level?(6-m.hp)*3:0);expect(s.players.A!.followers).toHaveLength(level<m.level?1:0);expect(s.players.C!.damage).toBe(0);}
});
it.each(rows)('%s actual maai prevents final follower defense and maintains hidden physical source',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);let s=until(incoming(ready(makeWingedFolkPhysicalScenario(scenario,players),m.card)),'normal-defense');s=finish(act(s,'A',{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c1'}));expect(s.players.A!.damage).toBe(0);expect(s.players.A!.followers).toContainEqual(expect.objectContaining({cardInstanceId:m.card,revealed:false}));expect(JSON.stringify(viewFor(s,'B'))).not.toContain(m.card);
});
it.each(rows)('%s actual direct ordinary and foreign dedicated attacks reject without permission',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);for(const initial of [false,true]){let s=ready(makeWingedFolkPhysicalScenario(scenario,players,{owner:'竜皇子アスフェルト'}),m.card,initial);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));for(const dedicated of [false,true])reject(s,'A',{type:'ATTACK',cardInstanceId:m.card,targetIds:['B'],dedicated});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});}
});


const WINGED='a2-p21-r1c3',ARMY='a2-p05-r2c2';
function dwarf(s:GameState){s=next(s);s=finish(act(s,'B',{type:'APPROACH',cardInstanceId:'a2-p24-r2c1',targetId:'A'}));return act(s,'B',grant(s,'B','a2-p21-r2c3'));}
it.each(['pass','fail'] as const)('actual Winged Folk spirit6 minus1 morale %s precedes all Dwarf6 hits and failure disables all defense',mode=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-higher',players,{spirit:6}),WINGED);s=until(dwarf(s),'before-roll');expect(s.rolls!.at(-1)!).toMatchObject({purpose:'follower-morale',rollerId:'A',modifier:-1,formula:'2d6'});s=closeWindow(s,mode==='pass'?[2,3]:[3,3]);expect(s.rolls!.at(-1)!).toMatchObject({threshold:5,success:mode==='pass'});s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!;expect(f.hits.map(h=>h.outcome)).toEqual(Array(3).fill(mode==='pass'?'lower-destroyed':'morale-failed'));expect(f.hits.map(h=>h.hpReduction)).toEqual([0,0,0]);s=finish(s);expect(s.players.A!.damage).toBe(18);expect(s.discard.filter(id=>id===WINGED)).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
});
it('actual Winged Folk surviving ordinary source checks each later group and hidden unreached rear never checks',()=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-setup',players),WINGED);s=finish(dwarf(s));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);s=next(s,'B');s=finish(act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p24-r1c2',targetIds:['A'],dedicated:false}));expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(2);expect(s.players.A!.damage).toBe(0);
 let q=ready(makeWingedFolkPhysicalScenario('winged-setup',players,{spirit:0}),WINGED,true,true);q=act(q,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',WINGED]});q=finish(incoming(q));expect(q.players.A!.followers[1]!.revealed).toBe(false);expect(q.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);
});
it.each([6,7,8])('actual explicit Tia package freezes follower7 HP0 without morale against Dwarf%i triple hits',level=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-waive',players,{level}),WINGED);s=until(dwarf(s),'normal-defense');expect(viewFor(s,'A').followerDefenseOptions).toContainEqual({cardInstanceId:WINGED});s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[WINGED]});s=until(s,'follower-start');expect(Object.values(s.groups!)[0]!.targets[0]!.followerDefense![0]!.levels).toEqual([7,7,7]);s=finish(s);expect(s.rolls?.filter(r=>r.purpose==='follower-morale')??[]).toEqual([]);expect(s.players.A!.damage).toBe(level===8?18:0);expect(s.players.A!.followers).toHaveLength(level===6?1:0);
});
it('actual Tia omitted defense package keeps ordinary5 and morale while foreign or duplicate selections reject',()=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-waive',players),WINGED);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[WINGED,WINGED]});s=finish(act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[]}));expect(s.players.A!.damage).toBe(18);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(1);
 s=ready(makeWingedFolkPhysicalScenario('winged-setup',players,{owner:'竜皇子アスフェルト'}),WINGED);s=until(dwarf(s),'normal-defense');reject(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[WINGED]});
});
it.each(['winged-earth','winged-earth-fail','winged-earth-waive','winged-earth-rear','winged-earth-ignore'] as const)('%s actual Earth Spear is local nullification only after morale or explicit Tia waiver and paid surprise bypasses it',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);let s=ready(makeWingedFolkPhysicalScenario(scenario,players),WINGED,true,m.rear);if(m.rear)s=act(s,'A',{type:'ARRANGE_FOLLOWERS',cardInstanceIds:['a2-p22-r1c1',WINGED]});s=next(s);if(m.ignore)s=act(s,'B',{type:'REVEAL_CHARACTER'});s=act(s,'B',{type:'ATTACK',cardInstanceId:'a2-p16-r2c3',targetIds:m.rear||m.ignore?['A']:['A','C'],dedicated:!m.rear&&!m.ignore});if(m.waive){s=until(s,'normal-defense');s=act(s,'A',{type:'START_FOLLOWERS',dedicatedCardInstanceIds:[WINGED]});}if(m.ignore){s=until(s,'follower-entry-abilities');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='B')s=pass(s);const o=viewFor(s,'B').abilityOptions.find(o=>o.abilityId==='c2-p02-r1c1-ab02')!;s=act(s,'B',{type:'USE_ABILITY',abilityId:o.abilityId,targetEventId:o.targetEventId,costCardInstanceId:'a2-p24-r2c1'});}s=until(s,'hit');const f=Object.values(s.groups!)[0]!.targets.find(t=>t.actorId==='A')!.followerDefense!.find(f=>f.source==='physical'&&f.cardInstanceId===WINGED)!;expect(f.descriptor).toMatchObject({level:5,hp:0,earthMagicNullify:true,moraleModifier:-1});expect(f.hits.map(h=>h.outcome)).toEqual(m.rear?[]:m.ignore?['passed-through']:m.fail?['morale-failed']:['earth-nullified']);s=finish(s);expect([s.players.A!.damage,s.players.C!.damage]).toEqual(m.ignore?[6,0]:m.rear?[0,0]:[m.fail?9:0,9]);expect(s.players.A!.followers.some(f=>f.cardInstanceId===WINGED)).toBe(!m.fail);expect((s.rolls??[]).filter(r=>r.purpose==='follower-morale')).toHaveLength(m.rear||m.ignore||m.waive?0:1);if(m.rear||m.ignore)expect(s.players.A!.followers.find(f=>f.cardInstanceId===WINGED)!.revealed).toBe(false);
});
const attackRows=['winged-ded-hand','winged-ded-field','winged-grant-hand','winged-grant-field','winged-army'] as const;
function attackCommand(s:GameState,scenario:WingedFolkPhysicalScenario,targets=['B','C','D']){const m=wingedFolkPhysicalMode(scenario);if(m.army)return{type:'PLAY_ALL_ARMY' as const,cardInstanceId:ARMY,followerCardInstanceId:WINGED,targetIds:targets};if(m.grant){const o=viewFor(s,'A').followerBundleOptions.find(o=>o.abilityId==='c2-p06-r1c2-ab04')!;return{type:'USE_FOLLOWER_ATTACK' as const,abilityId:o.abilityId,targetEventId:o.targetEventId,sources:[{cardInstanceId:WINGED,dedicated:false,targetIds:targets}]};}return{type:'ATTACK' as const,cardInstanceId:WINGED,targetIds:targets,dedicated:true};}
it.each(attackRows)('%s actual far wind magic7 mandatory all retains checks and shares one 10plus2d6 roll across every target',scenario=>{
 const m=wingedFolkPhysicalMode(scenario);for(const magic of [6,7]){let s=ready(makeWingedFolkPhysicalScenario(scenario,players,{magic}),WINGED,m.initial);for(const bad of [[],['B'],['B','C'],['A','B','C','D'],['B','B','C','D']])reject(s,'A',attackCommand(s,scenario,bad));s=act(s,'A',attackCommand(s,scenario,['D','B','C']));const a=Object.values(s.actions!).find(a=>a.cardInstanceId===WINGED)!;expect(a.checks).toHaveLength(7-magic);expect(a.technique).toMatchObject({school:'magic',range:'far',useLevel:7,effectLevel:7,damageFormula:'2d6',damageAdditive:10,noChecks:false,attributes:['遠','魔','風'],target:'all',mandatoryAll:true});expect(a.technique.counterProhibited??false).toBe(false);s=until(s,'damage');s=closeWindow(s,[2,5]);expect(s.rolls!.at(-1)!).toMatchObject({purpose:'attack-damage',faces:[2,5],total:7});s=until(s,'normal-defense');const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.actorId).sort()).toEqual(['B','C','D']);expect(g.targets.map(t=>t.hits[0]!.damage)).toEqual([17,17,17]);s=finish(s);expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([17,17,17]);expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.rolls!.filter(r=>r.purpose==='follower-morale')).toHaveLength(m.army?1:0);expect(s.discard.filter(id=>id===WINGED)).toHaveLength(1);expect(s.players.A!.followers).toEqual([]);}
});
it('actual Winged Folk far attack also reaches near players but placed source is unavailable to Army',()=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-ded-hand',players),WINGED,false);s=finish(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=finish(act(s,'A',attackCommand(s,'winged-ded-hand')));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([12,12,12]);s=ready(makeWingedFolkPhysicalScenario('winged-army',players),WINGED);expect(viewFor(s,'A').allArmyOptions.some(o=>o.followerCardInstanceId===WINGED)).toBe(false);reject(s,'A',attackCommand(s,'winged-army'));
});
it.each(['maai','mirror'] as const)('actual Winged Folk local %s preserves other target damage and reflection never rerolls attack dice',mode=>{
 let s=ready(makeWingedFolkPhysicalScenario('winged-ded-hand',players,{defender:'聖騎士ランスロット'}),WINGED,false);s=until(act(s,'A',attackCommand(s,'winged-ded-hand')),'damage');s=closeWindow(s,[2,5]);s=until(s,'normal-defense');s=act(s,'B',mode==='maai'?{type:'PLAY_MAAI',cardInstanceId:'a2-p07-r1c2'}:{type:'PLAY_DEFENSE',cardInstanceId:'a2-p11-r1c3',dedicated:true});s=finish(s);expect(['A','B','C','D'].map(id=>s.players[id]!.damage)).toEqual([mode==='mirror'?17:0,0,17,17]);expect(s.rolls!.filter(r=>r.purpose==='attack-damage')).toHaveLength(1);expect(s.discard.filter(id=>id===WINGED)).toHaveLength(1);
});
it.each(['hand','field','army-parent','army-child','army-morale','army-use','use','grant'] as const)('actual Winged Folk %s canceled source or failed roll is consumed once without return',mode=>{
 const army=mode.startsWith('army'),scenario=army?'winged-army':mode==='grant'?'winged-grant-field':mode==='field'?'winged-ded-field':'winged-ded-hand';let s=ready(makeWingedFolkPhysicalScenario(scenario,players,{magic:6}),WINGED,mode==='field'||mode==='grant');s=act(s,'A',attackCommand(s,scenario));if(mode==='army-child')s=closeWindow(s);if(mode==='army-morale'||mode==='army-use'||mode==='use'){s=until(s,'before-roll');if(mode==='army-use'){s=closeWindow(s);s=closeWindow(s);s=until(s,'before-roll');}expect(s.rolls!.at(-1)!.purpose).toBe(mode==='army-morale'?'follower-morale':'excess-level');}const roll=s.rolls?.at(-1),a=Object.values(s.actions??{}).find(a=>a.cardInstanceId===(mode==='army-parent'?ARMY:WINGED)),ability=Object.values(s.abilities??{}).find(a=>a.abilityId==='c2-p06-r1c2-ab04');while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',mode==='grant'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel-ability',targetAbilityId:ability!.id}:mode==='army-morale'||mode==='army-use'||mode==='use'?{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'force-fail',targetRollId:roll!.id}:{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:a!.id}));expect(['B','C','D'].map(id=>s.players[id]!.damage)).toEqual([0,0,0]);expect(s.players.A!.followers).toEqual([]);expect(s.players.A!.hand).not.toContain(WINGED);for(const id of army?[WINGED,ARMY]:[WINGED])expect(s.discard.filter(x=>x===id)).toHaveLength(1);
});
