import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState} from '../src/index.js';
import {act,pass,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeWolfFangPhysical,wolfFangCard as CARD,wolfFangMode} from './fixtures/wolf-fang-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id}));
function until(s:GameState,done:(s:GameState)=>boolean,dice:number[]=Array(30).fill(3)){for(let n=0;n<700;n++){if(done(s))return s;s=pass(s,dice);}throw Error('WOLF_FANG_LIMIT');}
function settle(s:GameState){return until(s,s=>!s.windows?.length);}
function cmd(dedicated=false,targetIds=['B']){return {type:'ATTACK',cardInstanceId:CARD,targetIds,dedicated};}
function source(s:GameState){return Object.values(s.actions!).find(a=>a.cardInstanceId===CARD)!;}
function group(s:GameState){return Object.values(s.groups!).find(g=>g.actionId===source(s).id)!;}
function reject(s:GameState,id:string,command:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId:id,command} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
it.each(['wolf-fang-ordinary','wolf-fang-owner-ordinary','wolf-fang-low','wolf-fang-dedicated','wolf-fang-far','wolf-fang-same-faction','wolf-fang-water','wolf-fang-metal','wolf-fang-lower','wolf-fang-maai-one-ordinary','wolf-fang-maai-one-dedicated','wolf-fang-maai-two-dedicated','wolf-fang-evade-ordinary','wolf-fang-evade-dedicated','wolf-fang-fate','wolf-fang-suppressed','wolf-fang-silenced','wolf-fang-stopped','wolf-fang-wrong-owner','wolf-fang-decline','wolf-fang-noncounter','wolf-fang-reroll-ordinary','wolf-fang-reroll-dedicated'] as const)('%s actual physical near two dice or optional far three dice survives real defenses and cancellation',name=>{
 let s=makeWolfFangPhysical(name,players);const m=wolfFangMode(name),hand=[...s.players.A!.hand],deck=[...s.deck],prior=s.rolls?.length??0;
 if(m.suffix==='stopped'||m.suffix==='wrong-owner'){reject(s,'A',cmd(true));expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.decline){s=act(s,'A',{type:'PASS_ACTION'});expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='noncounter'){for(const dedicated of [false,true])reject(s,'A',{type:'PLAY_DEFENSE',cardInstanceId:CARD,dedicated});s=settle(s);expect(s.players.A!.damage).toBe(4);expect(s.players.A!.hand).toContain(CARD);return;}
 if(m.suffix==='same-faction')reject(s,'A',cmd(true,['C']));if(m.suffix==='far')reject(s,'A',cmd(false));reject(s,'A',cmd(m.dedicated,['B','C']));reject(s,'A',{type:'CHANT',cardInstanceId:CARD,dedicated:m.dedicated});
 s=act(s,'A',cmd(m.dedicated));expect(s.players.A!.hand).toEqual(hand.filter(id=>id!==CARD));expect(s.deck).toEqual(deck);expect(source(s).technique).toMatchObject({range:m.dedicated?'far':'near',useLevel:5,effectLevel:5,damage:null,damageFormula:m.dedicated?'3d6':'2d6',attributes:['戦','格'],noChecks:m.dedicated,chant:false,counter:false,target:'one'});
 if(m.cancel){const id=source(s).id;s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=settle(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect(s.players.B!.damage).toBe(0);expect((s.rolls??[]).slice(prior).filter(r=>r.purpose==='attack-damage')).toHaveLength(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);return;}
 let damage=m.dedicated?9:6;
 if(m.reroll){s=until(s,s=>s.rolls?.at(-1)?.purpose==='attack-damage'&&s.rolls.at(-1)?.stage==='after-roll',Array(30).fill(1));const id=s.rolls!.at(-1)!.id;expect(s.rolls!.at(-1)!.total).toBe(m.dedicated?3:2);s=until(s,s=>s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]==='D');s=act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r1c3',mode:'reroll',targetRollId:id});s=until(s,s=>s.rolls!.find(r=>r.id===id)?.generation===1,Array(30).fill(6));expect(s.rolls!.find(r=>r.id===id)).toMatchObject({generation:1,total:m.dedicated?18:12});damage=m.dedicated?18:12;}
 s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(damage);expect(group(s).technique.maaiRequired??1).toBe(m.dedicated?2:1);expect(group(s).targets[0]!.hits[0]!.damage).toBe(damage);
 if(m.maai||m.evade){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');if(m.evade){s=act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});damage=0;}else{const count=m.suffix.includes('two')?2:1;for(const cardInstanceId of ['a2-p06-r1c3','a2-p06-r2c1'].slice(0,count)){s=until(s,s=>s.windows?.at(-1)?.kind==='normal-defense');s=act(s,'B',{type:'PLAY_MAAI',cardInstanceId});}if(!m.dedicated||count===2)damage=0;}}
 s=settle(s);if(m.follower){damage=m.suffix==='lower'?7:0;expect(s.players.B!.followers).toHaveLength(m.suffix==='lower'?0:1);}expect(s.players.B!.damage).toBe(damage);for(const id of ['A','C','D'])expect(s.players[id]!.damage).toBe(0);expect(s.discard.filter(id=>id===CARD)).toHaveLength(1);expect((s.rolls??[]).slice(prior).filter(r=>r.purpose==='attack-damage')).toHaveLength(1);
});
it.each([[false,[1,1],2],[false,[2,5],7],[false,[6,6],12],[true,[1,1,1],3],[true,[2,3,5],10],[true,[6,6,6],18]] as const)('actual damage dice bounds and sum dedicated=%s faces%s total%s before defense',(dedicated,faces,total)=>{let s=act(makeWolfFangPhysical(dedicated?'wolf-fang-dedicated':'wolf-fang-ordinary',players),'A',cmd(dedicated));s=until(s,s=>s.windows?.at(-1)?.kind==='damage');expect(source(s).technique.damage).toBeNull();s=closeWindow(s,[...faces]);s=until(s,s=>s.windows?.at(-1)?.kind==='attack-abilities');expect(group(s).technique.damage).toBe(total);expect(s.rolls!.find(r=>r.purpose==='attack-damage')).toMatchObject({faces:[...faces],total});s=settle(s);expect(s.players.B!.damage).toBe(total);});
it.each([[3,3,true],[3,4,false]] as const)('actual ordinary warrior4 spirit6 shortage %s plus %s success=%s before damage dice',(x,y,success)=>{let s=act(makeWolfFangPhysical('wolf-fang-low',players),'A',cmd(false));s=until(s,s=>s.windows?.at(-1)?.kind==='before-roll');s=closeWindow(s,[x,y]);expect(s.rolls!.at(-1)).toMatchObject({purpose:'excess-level',total:x+y,success});s=settle(s);expect((s.rolls??[]).filter(r=>r.purpose==='attack-damage')).toHaveLength(success?1:0);expect(s.players.B!.damage).toBe(success?6:0);});
it('actual far ordinary rejection ends after paid Approach while optional owner can choose normal at near',()=>{let s=makeWolfFangPhysical('wolf-fang-far',players,{warrior:5});reject(s,'A',cmd(false));s=settle(act(s,'A',{type:'APPROACH',cardInstanceId:'a2-p24-r1c3',targetId:'B'}));s=settle(act(s,'A',cmd(false)));expect(s.players.B!.damage).toBe(6);expect(JSON.stringify(s.distanceMarkers)).toContain('a2-p24-r1c3');});
it('actual malformed targets actor and preparation timing preserve unpaid source',()=>{let s=makeWolfFangPhysical('wolf-fang-dedicated',players);for(const targetIds of [[],['A'],['B','B'],['B','C'],['missing']])reject(s,'A',cmd(true,targetIds));reject(s,'B',cmd(true));s=makeWolfFangPhysical('wolf-fang-decline',players,{beforeStart:true});reject(s,'A',cmd());});
