import {expect,it} from 'vitest';
import {gameStats,transition,viewFor,type GameState, discardIds } from '../src/index.js';
import {act,pass,finish,until,closeWindow} from './combat-helpers.js';
import {entropy} from './fixtures.js';
import {makeYotsurmMagicPhysicalScenario,yotsurmMagicPhysicalMode,type YotsurmMagicPhysicalScenario} from './fixtures/yotsurm-magic-physical-scenarios.js';
const players=['A','B','C','D'].map(id=>({id,name:id})),rows=['beast-magic-ordinary','beast-magic-dedicated','wolf-magic-ordinary','wolf-magic-dedicated'] as const;
function reject(s:GameState,actorId:string,c:unknown){const before=JSON.stringify(s),views=s.seatOrder.map(id=>viewFor(s,id));expect(transition(s,{actorId,command:c} as never,entropy()).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);expect(s.seatOrder.map(id=>viewFor(s,id))).toEqual(views);}
function attack(scenario:YotsurmMagicPhysicalScenario){const m=yotsurmMagicPhysicalMode(scenario);return{type:'ATTACK' as const,cardInstanceId:m.card,targetIds:m.dedicated?['B','C','D']:['B'],dedicated:m.dedicated};}
it.each(rows)('%s actual printed profile ordinary use checks versus selected waiver without CHANT',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario);for(const level of [m.use-1,m.use]){let s=makeYotsurmMagicPhysicalScenario(scenario,players,{level,follower:'none'});reject(s,'A',{type:'CHANT',cardInstanceId:m.card});s=act(s,'A',attack(scenario));const f=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!;expect(f.technique).toMatchObject({school:'magic',range:'far',useLevel:m.use,effectLevel:m.effect,damage:m.wolf?null:m.damage,attributes:['魔','精','黒'],chant:false,noChecks:m.dedicated,target:m.dedicated?'all':'one'});if(m.wolf)expect(f.technique.damageFormula).toBe('attacker-magic-x2');expect(f.checkSpecs).toHaveLength(m.dedicated?0:m.use-level);s=finish(s);const damage=m.wolf?level*2:m.damage;expect(s.players.B!.damage).toBe(damage);expect([s.players.C!.damage,s.players.D!.damage]).toEqual(m.dedicated?[damage,damage]:[0,0]);expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);expect(s.players.A!.chants).toEqual([]);}
});
it.each(rows)('%s actual white Guardian8 and Angel7 destruction precedes comparison while mental Metal passes and Soldier reduces',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario),s=finish(act(makeYotsurmMagicPhysicalScenario(scenario,players),'A',attack(scenario)));expect(s.players.B).toMatchObject({damage:m.damage,followers:[]});expect(s.players.C!.damage).toBe(m.dedicated?m.damage-1:0);expect(s.players.C!.followers.map(f=>f.cardInstanceId)).toEqual(m.dedicated?['a2-p22-r1c1']:['a2-p22-r1c1','a2-p18-r3c3']);expect(s.players.D!.damage).toBe(m.dedicated?m.damage:0);
});
it.each(rows)('%s actual nonwhite Water7 blocks and survives with no white destruction',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario),s=finish(act(makeYotsurmMagicPhysicalScenario(scenario,players,{follower:'water'}),'A',attack(scenario)));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(1);expect(s.players.C!.damage).toBe(m.dedicated?m.damage-1:0);
});
it.each(rows)('%s actual Teleport protects only B and mental Evade is rejected with white followers intact',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario);for(const cardInstanceId of ['a2-p06-r1c1']){let s=until(act(makeYotsurmMagicPhysicalScenario(scenario,players),'A',attack(scenario)),'normal-defense');reject(s,'B',{type:'PLAY_DEFENSE',cardInstanceId:'a2-p05-r3c1',dedicated:false});s=finish(act(s,'B',{type:'PLAY_DEFENSE',cardInstanceId,dedicated:false}));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.damage).toBe(m.dedicated?m.damage-1:0);expect(s.players.D!.damage).toBe(m.dedicated?m.damage:0);}
});
it.each(rows)('%s actual failed use and Fate cancellation retain followers after source payment',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario);if(!m.dedicated){let s=until(act(makeYotsurmMagicPhysicalScenario(scenario,players,{level:m.use-1}),'A',attack(scenario)),'before-roll');s=finish(closeWindow(s,[6,6]));expect(s.players.B!.damage).toBe(0);expect(s.players.B!.followers).toHaveLength(2);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);}let s=act(makeYotsurmMagicPhysicalScenario(scenario,players),'A',attack(scenario));const id=Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.id;while(s.windows!.at(-1)!.participants[s.windows!.at(-1)!.cursor]!=='D')s=pass(s);s=finish(act(s,'D',{type:'PLAY_REACTION',cardInstanceId:'a2-p02-r2c3',mode:'cancel',targetActionId:id}));expect([s.players.B!.damage,s.players.C!.damage,s.players.D!.damage]).toEqual([0,0,0]);expect(s.players.B!.followers).toHaveLength(2);expect(s.players.C!.followers).toHaveLength(2);expect(discardIds(s).filter(x=>x===m.card)).toHaveLength(1);
});
it.each(rows)('%s rejects foreign dedication invalid targets actor and turn forms with all views unchanged',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario),s=makeYotsurmMagicPhysicalScenario(scenario,players);if(!m.dedicated)reject(s,'A',{...attack(scenario),targetIds:['B','C']});for(const targetIds of [[],['A'],['B','B'],['missing']])reject(s,'A',{...attack(scenario),targetIds});reject(s,'B',attack(scenario));reject(s,'A',{type:'PLAY_TURN_TECHNIQUE',cardInstanceId:m.card,targetIds:['B'],dedicated:m.dedicated});reject(makeYotsurmMagicPhysicalScenario(scenario,players,{owner:'魔導王ガイナス'}),'A',{...attack(scenario),dedicated:true});
});
it.each([['wolf-magic-ordinary',3],['wolf-magic-ordinary',6],['wolf-magic-ordinary',9],['wolf-magic-dedicated',3],['wolf-magic-dedicated',6],['wolf-magic-dedicated',9]] as const)('%s actual caster magic%s determines damage independently of use6 and Prayer effect7',(scenario,level)=>{
 let s=until(act(makeYotsurmMagicPhysicalScenario(scenario,players,{level}),'A',attack(scenario)),'effect-level');const id=Object.values(s.actions!).find(a=>a.cardInstanceId==='a2-p16-r2c2')!.id;s=act(s,'A',{type:'PLAY_REACTION',cardInstanceId:'a2-p05-r2c3',mode:'effect-plus',targetActionId:id});s=until(s,'damage');expect(gameStats(s,'A').magic_level).toBe(level);expect(s.actions![id]!.technique.effectLevel).toBe(7);s=closeWindow(s);const g=Object.values(s.groups!)[0]!;expect(g.targets.map(t=>t.hits[0]!.damage)).toEqual(Array(scenario.endsWith('-dedicated')?3:1).fill(level*2));s=finish(s);expect(s.players.B!.damage).toBe(level*2);expect(s.players.C!.damage).toBe(scenario.endsWith('-dedicated')?level*2-1:0);expect(s.players.D!.damage).toBe(scenario.endsWith('-dedicated')?level*2:0);
});
function nextOwn(s:GameState){for(let n=0;n<180;n++){const id=s.seatOrder[s.turnSeat]!,w=s.windows?.at(-1);if(w)s=pass(s);else if(s.phase==='action'){if(id==='A')return s;s=act(s,id,{type:'PASS_ACTION'});}else if(s.phase==='withdrawal')s=act(s,id,{type:'PASS_WITHDRAWAL'});else if(s.phase==='hand-adjustment')s=act(s,id,{type:'END_TURN',discardIds:s.players[id]!.hand.filter(x=>!['a2-p16-r2c1','a2-p16-r2c2'].includes(x)).slice(0,Math.max(0,s.players[id]!.hand.length-gameStats(s,id).handLimit))});else if(s.phase==='turn-start')s=act(s,id,{type:'START_TURN'});else if(s.phase==='draw')s=act(s,id,{type:'CHOOSE_DRAW',draw:false});else throw Error('YOTSURM_TURN');}throw Error('YOTSURM_TURN_LIMIT');}
it.each(rows)('%s actual owned name reclaim returns after parent completion for later turn reuse with opposite dedication',scenario=>{
 const m=yotsurmMagicPhysicalMode(scenario);let s=act(makeYotsurmMagicPhysicalScenario(scenario,players,{follower:'none'}),'A',attack(scenario)),taken=false;for(let n=0;n<300&&s.windows?.length;n++){const r=viewFor(s,'A').reclaim;if(!taken&&s.windows!.at(-1)!.kind==='reclaim'&&r?.pendingActorId==='A'&&r.cardInstanceId===m.card){const base=r.claims.find(c=>c.right==='base');expect(base).toBeDefined();s=act(s,'A',{type:'CHOOSE_RECLAIM',decisionId:r.decisionId,choice:'take',claimId:base!.claimId});taken=true;expect(s.windows??[]).toEqual([]);expect(s.players.A!.hand.filter(id=>id===m.card)).toHaveLength(1);expect(discardIds(s)).not.toContain(m.card);reject(s,'A',attack(scenario));}else s=pass(s);}expect(taken).toBe(true);expect(s.players.A!.hand).toContain(m.card);s=nextOwn(s);s=act(s,'A',{...attack(scenario),dedicated:!m.dedicated,targetIds:m.dedicated?['B']:['B','C','D']});expect(Object.values(s.actions!).find(a=>a.cardInstanceId===m.card)!.technique.noChecks).toBe(!m.dedicated);s=finish(s);expect(s.players.B!.damage).toBe(m.wolf?24:12);expect([s.players.C!.damage,s.players.D!.damage]).toEqual(m.wolf?[12,12]:[7,7]);expect(discardIds(s).filter(id=>id===m.card)).toHaveLength(1);
});
